Graph generator stackplot fix
RuminantFarmSystems/RuFaS pull request #1000
Opened 2023-11-28 19:49 UTC by ew3361zh

PR to address issue #989 in which graph generator errors when trying to plot a stackplot where the filter is not a dictionary.

To accomplish this:
1. Add functionality within the `_draw_graph()` to handle and direct stackplot data that is not in a dictionary.
2. Rename and update `_handle_type_based_plot()` -> `_handle_dict_plots()`
3. Move repeated functionality from `_draw_graph()` to `_handle_dict_plots()`
4. Updates example graph filter examples with new functionality (and with changes that are in main now which broke the example plot function filter as well).
5. Updates unit testing.

2023-11-29 15:37 UTC, Isgotkowitz approved these changes
Code LGTM. I was able to generate some novel stackplots with data from different variables and the example graphs were producing as expected.

2023-11-30 22:22 UTC, ew3361zh commented
Updates:
1. Creates new function in Output Manager `_prepare_plot_data()` that readies the data to be graphed before it's sent to Graph Generator.
2. Simplifies the logic in Graph Generator's `_draw_graph()` now that it is no longer manipulating the data that's sent to it.
3. Updates unit testing and docstrings.

2023-11-30 23:10 UTC, Isgotkowitz reviewed
@ew3361zh I think I have identified an edge case that is causing a stack plot to be produced incorrectly. It might be more of an issue with the variable names though.

```json
    {
      "type": "stackplot",
      "filters": [
        "field='.*',layer_index='.*'.water_content"
      ],
      "variables": ["water_content", "water_content", "water_content", "water_content"],
      "title": "Soil Water Content Stack Plot",
      "legend": ["Layer 0 Water Content (mm)", "Layer 1 Water Content (mm)", "Layer 2 Water Content (mm)", "Layer 3 Water Content (mm)"]
    },
    {
      "type": "plot",
      "filters": [
        "field='.*',layer_index='.*'.water_content"
      ],
      "title": "Soil Water Content Line Plot",
      "legend": ["Layer 0 Water Content (mm)", "Layer 1 Water Content (mm)", "Layer 2 Water Content (mm)", "Layer 3 Water Content (mm)", "Layer 4 Water Content (mm)"]
    }
``` 

Edit: the top graph specification can be modified to be:
```json
    {
      "type": "stackplot",
      "filters": [
        "field='.*',layer_index='.*'.water_content"
      ],
      "variables": ["0'.water_content", "1'.water_content", "2'.water_content", "3'.water_content"],
      "title": "Soil Water Content Stack Plot",
      "legend": ["Layer 0 Water Content (mm)", "Layer 1 Water Content (mm)", "Layer 2 Water Content (mm)", "Layer 3 Water Content (mm)"]
    }
```
and it seems to work as expected.

2023-12-01 14:32 UTC, Isgotkowitz approved these changes
Changes look good Niko. Left some suggestions on small things.

I got the stack plot specified in earlier comments to work, it just required being more specific about how variables were being specified in the `"variables"` column.

2023-12-01 14:32 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +                continue
```suggestion
                if not selected_variables:
                    self.add_error("No selected variables. Can't plot this data set.",
                                   "List your 'variables' in the graph output filter.", info_map)
                    continue
                data_dict = Utility.convert_list_of_dicts_to_dict_of_lists(values)
                for selected_variable in selected_variables:
                    if selected_variable in data_dict:
                        prepared_pool.setdefault(selected_variable, []).extend(data_dict[selected_variable])
```
Not an important change, but reworking this branching statement to something similar to the above would make the code a little flatter.

2023-12-01 14:32 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +        """Extracts the values from the filtered pool data and converts them a dict format
```suggestion
        """Extracts the values from the filtered pool data and converts them to a dictionary format
```

2023-12-01 15:20 UTC, ew3361zh commented on RUFAS/output_manager.py
> +                continue
I can take a look. I think if the user hasn't added selected_variables to their filter file then we just want to break out of this loop (i.e. not continue) because we can't plot any of the data from that filter file (as of now). I think this will get addressed when I dive into issue #899.

2023-12-01 16:13 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _prepare_plot_data(self, filtered_pool: Dict[str, pool_element_type],
Are there any particular reasons why this function is in OM and not in GG?

2023-12-01 16:16 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        """Extracts the values from the filtered pool data and converts them a dict format
dictionary is a data structure, not a format.

2023-12-01 16:20 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                continue
>Not an important change, but reworking this branching statement to something similar to the above would make the code a little flatter.

Checking for the unhappy path first is a good idea and one the best practices in writing code. It leads to a cleaner, more understandable, and maintainable code and is less prone to bugs.

2023-12-01 18:29 UTC, ew3361zh commented on RUFAS/output_manager.py
> +                continue
I've adjusted the code accordingly and put the unhappy path first (and just break the loop at that point since it's unnecessary to continue).

2023-12-01 18:32 UTC, ew3361zh commented on RUFAS/output_manager.py
> +    def _prepare_plot_data(self, filtered_pool: Dict[str, pool_element_type],
I looked at both locations and the deciding factor was that we could log errors to help users/devs debug issues with their filter data better when the function is in OM. (Since we can't import OM into GG because of the circular import issue).

2023-12-04 19:48 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _prepare_plot_data(self, filtered_pool: Dict[str, pool_element_type],
preparing the plot data is beyond the domain of the output manager (preparing the plot data is different from managing the outputs). It should be move to GG. To avoid circular imports, you can return the results/status to the caller (output manager) so it can log it. Since the function is accepting a set of inputs, you may want to make it asynchronous and use `yield`.

2023-12-04 20:02 UTC, JoeWaddell approved these changes
Tested with various filters I've been using, and this works nicely!

As a suggestion: since the milk lactose/protein/fat values are (currently) less dynamic than they will be in the future, you could replace the currently stackplot in the `graph_filter_example.json` with the animal population filter below.

```
{
  "type": "stackplot",
  "filters": [
    "AnimalManager.daily_updates.(num_calves|num_heiferIs|num_heiferIIs|num_heiferIIIs|num_lactating_cows|num_dry_cows)"
  ],
  "title": "Herd composition (stackplot)",
  "legend": ["num_calves","num_heiferIs","num_heiferIIs","num_heiferIIIs","num_lactating_cows","num_dry_cows"]
}
```

2023-12-04 21:43 UTC, ew3361zh commented
> Tested with various filters I've been using, and this works nicely!
> 
> As a suggestion: since the milk lactose/protein/fat values are (currently) less dynamic than they will be in the future, you could replace the currently stackplot in the `graph_filter_example.json` with the animal population filter below.
> 
> ```
> {
>   "type": "stackplot",
>   "filters": [
>     "AnimalManager.daily_updates.(num_calves|num_heiferIs|num_heiferIIs|num_heiferIIIs|num_lactating_cows|num_dry_cows)"
>   ],
>   "title": "Herd composition (stackplot)",
>   "legend": ["num_calves","num_heiferIs","num_heiferIIs","num_heiferIIIs","num_lactating_cows","num_dry_cows"]
> }
> ```

Thanks, Joe!

2023-12-07 15:28 UTC, ew3361zh commented
After looking further into the matter, I wasn't able to get yield to work properly with the `prepare_plot_data()` method in `graph_generator`.

BUT!

I think we don't need it here. The order of the filters getting to `prepare_plot_data()` is 

1. OM's `save_results()` method loads the filter file and then loops through the list of filters.
2. For each filter, OM's `_route_save_functions()` is called and sends the data to GG's `prepare_plot_data()`.
3. So `prepare_plot_data()` will only be handling a single filter at a time.
4. For each filter, if the data provided is in a dictionary, the filter file either has selected_variables or doesn't and there is one route for each case (filter the provided data by the selected_variables and prepare a log of the successful filter or prepare and error message to be sent back to OM).
5. If the data provided is not in a dictionary, we have 2 other routes to be able to prepare the data accordingly (and add log messages).
6. Therefore there shouldn't be a situation where there's a backlog of filters stuck in `prepare_plot_data()` and we're needing to return data before its finished going through all the filters.

2023-12-08 00:33 UTC, ew3361zh commented
Updates:

- [x] `prepare_plot_data` function moved to GG, returns prepared data and logs of data being prepared (logs/errors/warnings) for OM to add to its pools.
- [x] creates method in OM to handle these returned logs and to direct graph_generator to act accordingly (i.e. don't graph if there was an error preparing the data which means there's no graphable data).
- [x] updates unit testing.

Please see note left above (9 hours prior) for discussion on why use of yield didn't seem necessary because `prepare_plot_data` is only receiving and processing 1 filter at a time.

2023-12-08 00:37 UTC, ew3361zh commented
With this last bunch of code added, I think we're touching on a good portion of #927. @Isgotkowitz if you could take another look with that issue in mind, that would be helpful.

2023-12-08 15:57 UTC, PooyaHekmati requested changes
The PR is on the right track, however, I couldn't understand the details to approve it. It is more complex/complicated than needs to be. Also, unable to comment on the applicability of `yield` for the same reason.

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +        log_pool = []
```suggestion
        log_pool : Dict[str, str|Dict[str, str]]= []
```

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +        prepared_pool = {}
I spent 5 minutes trying to infer the type of data that goes into this dict and I couldn't, chances are other people won't be able to do it as well.

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                    log_pool.append(error)
Simplify, we add documentary variables when the statement is hard to understand. `error = error` doesn't make the code more readable.
```suggestion
                    log_pool.append({"error": f"Can't plot {title} data set", "message": f"No selected variables for {key}.",
                             "info_map": info_map})
```

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                else:
remove unnecessary `else` and its indentation: we first check for the unhappy path first and either raise or return or break, so for the rest of the function we can safely assume everything is in order and we don't need to indent the code.
`Flat is better than nested.`
```suggestion
```

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                    selected_variables_in_data = 0
```suggestion
                    selected_variables_counter = 0
```

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                            log = {"log": f"Successfully added {title} data to prepared_pool",
`added {title} data`?

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                            log_pool.append(log)
simplify

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                            log_pool.append(warning)
check for unhappy path first

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                            prepared_pool.setdefault(selected_variable, []).extend(data_dict[selected_variable])
I spent 5 minutes trying to understand what is happening here, this is my doubtful understanding: if we already have the `selected_variable` in the `prepared_pool.keys()` we extend its values by `data_dict[selected_variable]`, otherwise, we first make an empty list and then extend it?
`Readability counts.`
`Simple is better than complex.`
`If the implementation is hard to explain, it's a bad idea.`

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                    if selected_variables_in_data == 0:
if this variable is used to determine the validity of the data, then it should be a `bool` rather integer.

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                if selected_variables:
I don't understand. `selected_variables` is supposed to tell us which items in the dict we want to plot. If data is not in dict, then why we need to check for the presence of `selected_variables`?

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                    log_pool.append(log)
simplify

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                    log_pool.append(log)
simplify

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                    prepared_data, log_pool = graph_generator.prepare_plot_data(filtered_pool,
can we move this call to `graph_generator.generate_graph()`? That way, GG takes care of its own business, instead of expecting others to prepare the data for it.

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _route_graph_generator_logs(self, log_pool: List[Dict[str, str | Dict[str, str]]]) -> bool:
Let's give this function a more generic name and decouple it from the GG.

2023-12-08 15:57 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        return error_count == 0
`Readability counts.`
```suggestion
        is_valid = True
        for log in log_pool:
            if "error" in log:
                self.add_error(log["error"], log["message"], log["info_map"])
                is_valid = False
            elif "log" in log:
                self.add_log(log["log"], log["message"], log["info_map"])
            elif "warning" in log:
                self.add_warning(log["warning"], log["message"], log["info_map"])

        return is_valid 
```

2023-12-08 15:58 UTC, PooyaHekmati commented
@Isgotkowitz @JoeWaddell Since the PR already has your approval, please feel free to answer my comments.

2023-12-11 21:15 UTC, Isgotkowitz commented
> With this last bunch of code added, I think we're touching on a good portion of https://github.com/RuminantFarmSystems/MASM/issues/927. @Isgotkowitz if you could take another look with that issue in mind, that would be helpful.

I think the changes made are definitely steps in the right direction, but not enough to close 927.

2023-12-11 22:12 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +    def prepare_plot_data(self, filtered_pool: Dict[str, Dict[str, List[Any]]],
I think this function could have the functionality of `_route_graph_generator_logs()` added to it, without adding much complexity. Instead of saving all the errors/warnings/logs and returning them, raise everything to the Output Manager where it finds it and track whether it caught any errors with a boolean.

Then when it reaches the end of the function, return `None` if it caught any errors. Otherwise return `prepared_pool`.

2023-12-11 22:12 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +        log_pool = []
I think it would be `List[Dict[str, str | Dict[str, str]]]`

2023-12-11 22:12 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +        prepared_pool = {}
Based on the return type hint, it should be `Dict[str, List[int | float]]`. But this raises the question: what happens if the user tries to plot a variable that is a list of strings?

2023-12-12 16:10 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +        log_pool = []
@Isgotkowitz that is the correct type annotation for the log pool, I will add it (it's essentially a list of dicts of what the add_log/add_warning/add_error methods take as arguments: log name, log message, info map).

2023-12-12 16:14 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +        prepared_pool = {}
Added the type hint here as well. I considered the functionality of type checking the values for each of the variables listed in the filter but when Pooya and I talked it over, we determined it was too much responsibility to take on. I will double check what happens if someone adds a variable that has string data in it.

2023-12-12 16:16 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +                    log_pool.append(error)
Makes sense. Updated.

2023-12-12 16:23 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +                            log = {"log": f"Successfully added {title} data to prepared_pool",
This is an effort to make the logs clearer by associating them with the title from the filter file being used to prepare the date. So for example in the graph_generator_example.json file, the stackplot example's title is "Hard composition (stackplot)". So the message would be "...added Hard composition stackplot data."

2023-12-12 16:52 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +    def prepare_plot_data(self, filtered_pool: Dict[str, Dict[str, List[Any]]],
If I understand this correctly, I think we'd need to import OM to GG which we can't do for circular import error concerns. If I'm misunderstanding, please let me know.

2023-12-12 16:58 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +                if selected_variables:
I think we have 4 main possibilities:
1. The values are in a dict and there are selected variables.
2. The values are in a dict and there are no selected variables.
3. The values are not in a dict and there are selected variables.
4. The values are not in a dict and there are no selected variables.

I'm not sure if option 3 is a probable possibility but in the case it comes up, my thought was we'd take the variable name the user chose (maybe it differs from the variable name assigned when it was added to OM) and add the data to the prepared pool with the variable. As I'm looking at it again though, we're opening the possibility for a list index out of range error (i.e. the list of variables they want to plot is shorter than the list of variables in the filtered pool). Maybe this is better addressed when we've incorporated regex into the prepare pool function.

2023-12-12 16:59 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +                if selected_variables:
I can remove it for now.

2023-12-12 17:50 UTC, ew3361zh commented on RUFAS/output_manager.py
> +        return error_count == 0
Agreed!

2023-12-12 22:13 UTC, ew3361zh commented on RUFAS/output_manager.py
> +                    prepared_data, log_pool = graph_generator.prepare_plot_data(filtered_pool,
Yes

2023-12-12 22:48 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +                            prepared_pool.setdefault(selected_variable, []).extend(data_dict[selected_variable])
Yes, your "doubtful" understanding is correct.

2023-12-12 22:55 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +        prepared_pool = {}
I couldn't find an instance of a dictionary having a string value to add here to check what would happen.

2024-01-02 17:15 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +            error_found = any("error" in log for log in log_pool)
just a thought: what about naming the variable: `found_errors`?

2024-01-02 17:15 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +            plot_function(list(range(len(values_tuple[0]))), values_tuple)
please decompose this into multiple lines. The variable names will help to make it easier to understand and maintain.

2024-01-02 17:15 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +                if all(selected_variable not in data_dict for selected_variable in selected_variables):
use explanatory variable here

2024-01-02 18:49 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +            error_found = any("error" in log for log in log_pool)
That works for me!

2024-01-02 19:19 UTC, PooyaHekmati approved these changes

2024-01-02 19:42 UTC, merged