Capability to create updated Data Collection App schema inputs with RuFaS
RuminantFarmSystems/RuFaS pull request #1022
Opened 2023-12-05 20:39 UTC by Isgotkowitz

This is the first iteration of the `SchemaGenerator`, which automates the process of creating input schema for the Data Collection App. It has a GNU arg that can be used to invoke when running RuFaS (`-gs` or `--generate-schemas`)

If you want to check out these schemas in action (which I would highly recommend and appreciate), see PR [54](https://github.com/RuminantFarmSystems/Data-Collection-App/pull/54) in the DCA repo.

### In this PR
- The `SchemaManager` and associated tests have been created.
- `main.py` (and associated tests) have been updated to accept the new GNU arg and run SchemaManager when told to do so.
- The `.gitignore` has been configured to track the directory `data_collection_app_schemas/` but not any of the schemas in it.
- I found some irregularities in the metadata properties and corrected them to be consistent with the rest of the properties. Also a reason why this PR looks so massive. None of the changes I have made should effect how the simulation actually runs, but that should be verified independently as much as possible.
- The non default metadata properties have been synched up with the default metadata properties. Changes were made in the properties in #921 in the default metadata that were not added to the rest of the metadata files.

### Notes
This PR is already massive, so I held off on making changes that will probably be necessary in the future. They include:
- The log verbosity for the OutputManager is set multiple times in main, but this seems like the kind of thing that should only happen once. I added another call to set it before the SchemaManager runs so that it is possible to see logs and errors produced when generating schemas.
- A future feature for the SchemaGenerator/main would be adding the capability to specify which file the metadata properties are pulled from (which determine what the input schema are), and where the schemas are written to.
- As Allister pointed this out in his review, adding a way to specify the grid columns would be very beneficial.
- Also as Allister pointed out, there should be a better name for elements of an array than just "<array title>_element". I think a good solution would be adding a `"title"` key to the metadata properties.

Closes #968

2023-12-12 17:15 UTC, allisterakun requested changes
Looks great! Just some small issues.

2023-12-12 17:15 UTC, allisterakun commented on RUFAS/schema_manager.py
> +        keys = [key for key in input_properties.keys() if key != "type" and key != "description" and key != "default"]
maybe have a list of keys to ignore?

2023-12-12 17:15 UTC, allisterakun commented on RUFAS/schema_manager.py
> +                "grid_columns": 12,
Maybe have this to be passed in as an argument, so that we can choose to have the variable take up half of the page width or full page width

2023-12-12 17:15 UTC, allisterakun commented on RUFAS/schema_manager.py
> +            "type": "boolean",
```suggestion
            "type": "boolean",
            "format": "checkbox",
```

2023-12-12 17:15 UTC, allisterakun commented on RUFAS/schema_manager.py
> +            "type": "boolean",
The default format is a dropdown list of `True` and `False`. I think using a checkbox to indicate a boolean variable is more intuitive and more user-friendly.

2023-12-12 17:15 UTC, allisterakun commented on RUFAS/schema_manager.py
> +                "format": "select2",
```suggestion

```

2023-12-12 17:15 UTC, allisterakun commented on RUFAS/schema_manager.py
> +                "format": "select2",
The "format" option should not go into the "options"; it does not have effect if placed here.

2023-12-12 17:15 UTC, allisterakun commented on RUFAS/schema_manager.py
> +        element_title = title + "_element"
After conversation with @Isgotkowitz, we decided this would be a future improvement to avoid the name becoming "variableName_element_element" for nested arrays.

2023-12-12 17:15 UTC, allisterakun commented on RUFAS/schema_manager.py
> +        keys = [key for key in input_properties.keys() if key != "type" and key != "description" and key != "default"]
```suggestion
        ignored_keys = ["type", "description", "default"]
        keys = [key for key in input_properties.keys() if key not in ignored_keys]

```

2024-01-18 15:52 UTC, allisterakun approved these changes
Looks GREAT, Ed!!! Wonderful job! Left some comments on unit tests, just some suggestions.

2024-01-18 15:52 UTC, allisterakun commented on main.py
> +        output_manager.add_log(log_title, log_message, info_map)
Maybe put this into a separate function in main? Just to keep the top-level run_rufas() clean.

2024-01-18 15:52 UTC, allisterakun commented on tests/test_schema_generator.py
> +    assert actual == schema
Would it be a better practice to patch `setup_number_schema()`, `setup_bool_schema()`, and `setup_string_schema()` and check the number of calls to each method? (This would also mean having tests for array of numbers, array of bools, and array of strings)

2024-01-18 15:52 UTC, allisterakun commented on tests/test_schema_generator.py
> +    assert actual == schema
Same thing here, I would suggest to patch `setup_number_schema()`, `setup_bool_schema()`, and `setup_string_schema()`. Passing the expected number of calls to each sub-function in as an input, and check for the number of calls to each function.

2024-01-18 18:37 UTC, Isgotkowitz commented on main.py
> +        output_manager.add_log(log_title, log_message, info_map)
Good idea

2024-01-18 18:56 UTC, Isgotkowitz commented on tests/test_schema_generator.py
> +    assert actual == schema
Yes, it would definitely be a better practice. I will work on setting up these tests.

Update: the way that data types are mapped to schema setup methods (with the `DATA_TYPE_TO_SCHEMA_SETUP_MAP` variable) is problematic, it required a bunch of workarounds to get the mocking correct. To do this, I moved `DATA_TYPE_TO_SCHEMA_SETUP_MAP` to be outside of `SchemaGenerator`, and mocked the methods it contains directly. In future iterations, this design should be revisited.

2024-01-18 18:56 UTC, Isgotkowitz commented on tests/test_schema_generator.py
> +    assert actual == schema
Same as above response.

2024-01-19 17:51 UTC, elle-andreen commented on input/metadata/default_metadata.json
> +          "description": "Breed (select one Holstein/Jersey) -- The predominant breed of the herd (Holstein or Jersey)"
I would just leave this as 'select one' as the breeds/options are given in the description, similar to other 'select one' variables

2024-01-19 18:13 UTC, elle-andreen commented
This is looking great to me thus far as well! I had no issues running the simulation on this branch and don't see any issues with what you've modified in the metadata and other files, other than the one very minor comment above. This is great groundwork as for eventually refining and optimizing the SchemaGenerator.

I have pasted some thoughts from other conversation and my comments PR 54 (in the DCA repo) to spur others' thoughts on this:
- Eventually, for SchemaGenerator to function optimally (and save us the most time), the metadata will need to undergo some reformatting. As soon as we reasonably can, we may want to try to establish guidelines for how existing and new metadata entries should be formatted so that SchemaGenerator can pull the necessary information for each input variable. I'm sure that some of that reformatting can be done automatically, but will likely also require SME's taking the time to ensure the necessary info for each variable is there and is clear/complete. Ideally this would have happened in conjunction with the metadata review process, but we deemed it too labor and time intensive for the moment. But we should keep it on our mental horizon!
- We need the DCA to align with the metadata, but we also need it to be readable and easy to use. The DCA may need addition things not found in the metadata, like extra information, maybe different input formats that are then converted under the hood to match what's required by the metadata, external links, etc. I have started thinking about what those 'extras' may be, and I'm sure folks involved in the pilot testing have as well. I'm also curious about what can and cannot be easily preserved with each automatic update. If we were to add additional formatting beyond what we have here, then every time we update the content of the metadata, will that formatting and other content be preserved? 
- I see this script brings the metadata default values to the DCA, which is great. Can/are we incorporating the min/max values given in the metadata as well? Either as part of the infotext/description, or as some kind of validation in coordination with the JSON (or maybe that's happening already!)

2024-01-23 18:10 UTC, 0luchi approved these changes
Very well documented and runs the simulation with no issues. Looks good to me!

2024-01-27 03:31 UTC, ltp23 approved these changes
Awesome PR, Ed! I did check out how the generated schemas would look in the DCA and the functionality remained the same. I guess the next step would be to auto-populate the sections that involve importing the schema files and the schema variables into the index.html file.

2024-01-27 03:31 UTC, ltp23 commented on RUFAS/schema_generator.py
> +            new_schema_file_name = f"{schema_name}.json"
Based on what I see in the DCA, I think you would want the output file type to be `.js` instead of `.json`, right?

2024-01-27 03:31 UTC, ltp23 commented on RUFAS/schema_generator.py
> +                json.dump(new_schema, outfile, indent=2)
And to save each schema into a variable,

```
outfile.write(f"var {schema_name} = ")
json.dump(new_schema, outfile, indent=2)
outfile.write(";")
```

2024-01-27 03:31 UTC, ltp23 commented on RUFAS/schema_generator.py
> +    def setup_bool_schema(title: str, input_properties: dict[str, Any]) -> dict[str, Any]:
Need some docstring here?

2024-01-27 03:31 UTC, ltp23 commented on RUFAS/schema_generator.py
> +        pattern = "\\^\\(.*\\)\\$"
Can we assume this is the expected pattern?

2024-01-27 15:07 UTC, Isgotkowitz commented on RUFAS/schema_generator.py
> +            new_schema_file_name = f"{schema_name}.json"
Yes, but even changing `.json` to `.js` would not ensure that the names of the newly generated schema line up perfectly with names of the old schema. For example, the old field schema file name is `field_management.js` but the new schema file name is `field_schema.json`.

2024-01-27 15:11 UTC, Isgotkowitz commented on RUFAS/schema_generator.py
> +                json.dump(new_schema, outfile, indent=2)
The issue with adding this in (like above) is that there isn't a clean way to map the schema name generated by `SchemaGenerator` to the name that was in the old schema files.

2024-01-27 15:12 UTC, Isgotkowitz commented on RUFAS/schema_generator.py
> +    def setup_bool_schema(title: str, input_properties: dict[str, Any]) -> dict[str, Any]:
Yes good catch.

2024-01-27 15:22 UTC, Isgotkowitz commented on RUFAS/schema_generator.py
> +        pattern = "\\^\\(.*\\)\\$"
Great question. I think we have to. It seems like all string inputs are either names (which have no constraints and don't need this method to be used) or have a very rigid set of strings that are considered valid inputs. For the latter, we need to be able to extract that rigid set from the pattern in order to properly create the drop down menu of options in the input schema.

Two notes: there are two inputs that don't work with the above assumption, the start and end dates specified in the config input. I think these are special cases though, and a better solution would be to modify their structure instead of modifying the `SchemaGenerator` to accommodate them.

The second note is that I don't know if it is possible to embed a Regex pattern in a schema and have the DCA enforce it on inputs. I didn't find a way to do this but if it is possible we should opt for utilizing that.

2024-01-29 14:19 UTC, Isgotkowitz commented
> Awesome PR, Ed! I did check out how the generated schemas would look in the DCA and the functionality remained the same. I guess the next step would be to auto-populate the sections that involve importing the schema files and the schema variables into the index.html file.

Thank you for your review and comments @ltp23. You raised a lot of good points about how the SchemaGenerator could/should be improved, but I think most of those changes would be too much to try and include in this PR. I will create an issue laying out steps and tasks for SchemaManager improvement and will include your suggestions there.

2024-10-29 21:47 UTC, Isgotkowitz commented
Issues addressed by this PR will be addressed by #2046 (and more!)

2024-10-29 21:47 UTC, closed without merging