[1/n][Feed Storage] Implement Storage structure
RuminantFarmSystems/RuFaS pull request #1023
Opened 2023-12-05 20:42 UTC by PooyaHekmati

This PR implements the structure of the storage class based on the design doc https://docs.google.com/document/d/1C86lch2dkYBERR-qLDmE7L7n1gYQjETrIKUyrQpWrPs/edit?usp=sharing along with its tests. The logic will be populated in future PRs.

2023-12-06 03:54 UTC, Isgotkowitz requested changes
Great start. Majority of comments related to type annotations and units. Requesting changes because I think it would be good to have units in docstrings.

2023-12-06 03:54 UTC, Isgotkowitz commented on RUFAS/config.py
> +        )
Can this conditional and associated TODO be removed? It seems that since `simulate_animals` is now in the config properties, it is safe to assume that simulate animals will be in the data.

2023-12-06 03:54 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/harvested_crop.py
> +    storage_time: Time
As an alternative to using two full `Time` object, what about keeping four `int`s: calendar year of harvest, ordinal day of harvest, calendar year of storage, and ordinal day of storage?

2023-12-06 03:54 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/storage.py
> +    recalculate_nutrient_fractions():
```suggestion
    receive_crop(crop: HarvestedCrop)
        Receives a harvested crop and adds it to the storage.
    process_degradations()
        Processes the degradations and losses of the stored crops.
    give_feed(amount: float, crop_type: str)
        Gives out a specified amount of feed of a certain crop type.
    calculate_dry_matter_loss_to_gas(dry_matter: float, time_in_silo: int)
        Calculates the dry matter loss to gas.
    calculate_dry_matter_loss_to_effluent(dry_matter: float, estimated_maximum_effluent: float, time_in_silo: int)
        Calculates the dry matter loss to effluent.
    calculate_protein_degradation()
        Calculates protein degradation.
    calculate_heat_generated()
        Calculates the total sensible heat generated.
    calculate_bale_density(initial_dry_matter: float)
        Calculates the density of a bale.
    recalculate_nutrient_fractions()
```

2023-12-06 03:54 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/storage.py
> +    def receive_crop(self, crop: HarvestedCrop):
```suggestion
    def receive_crop(self, crop: HarvestedCrop) -> None:
```
Might be overkill

2023-12-06 03:54 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/storage.py
> +    def calculate_dry_matter_loss_to_gas(self, dry_matter: float, time_in_silo: int):
```suggestion
    def calculate_dry_matter_loss_to_gas(self, dry_matter: float, time_in_silo: int) -> float:
```

2023-12-06 03:54 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/storage.py
> +    ):
```suggestion
    ) -> float:
```

2023-12-06 03:54 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/storage.py
> +    def calculate_heat_generated(self):
```suggestion
    def calculate_heat_generated(self) -> float:
```

2023-12-06 03:54 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/storage.py
> +            The amount of dry matter lost to effluent.
Units?

2023-12-06 03:54 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/storage.py
> +            The amount of dry matter lost to gas.
Units in docstring

2023-12-06 03:54 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/storage.py
> +        The maximum capacity of the storage, currently set to infinity.
Units should be specified.

2023-12-06 03:54 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/storage.py
> +    def calculate_bale_density(self, initial_dry_matter: float):
```suggestion
    def calculate_bale_density(self, initial_dry_matter: float) -> float:
```

2023-12-06 03:57 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/storage.py
> +            The amount of dry matter lost to effluent.
will be added at the implementation time

2023-12-06 03:58 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/storage.py
> +            The amount of dry matter lost to gas.
will be added at the implementation time

2023-12-06 03:58 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/storage.py
> +        The maximum capacity of the storage, currently set to infinity.
will be added at the implementation time

2023-12-06 03:59 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/harvested_crop.py
> +    storage_time: Time
What is the benefit of that?

2023-12-06 04:01 UTC, PooyaHekmati commented on RUFAS/config.py
> +        )
It's out of the scope of this PR. This will be addressed in issue 1017.

2023-12-06 04:34 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/harvested_crop.py
> +    storage_time: Time
Eliminates unneeded complexity. A timestamp is just a static recording of a time, it doesn't need to be a full object that has methods for modifying it.

Also, it is more space efficient, because keeping a copy of `Time` would need to be created to be stored in each field.

2023-12-06 14:40 UTC, Isgotkowitz approved these changes

2023-12-07 18:22 UTC, KevinP-B approved these changes
Harvest and storage times added to test

2023-12-08 15:04 UTC, JoeWaddell commented on RUFAS/routines/feed_storage/storage.py
> +    stored : List[HarvestedCrop]
Since this deals with just storage of harvested crops, is there a separate class that will handle storage for A) purchased crops, and B) feed additives?

2023-12-08 16:29 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/harvested_crop.py
> +    storage_time: Time
Some operations such as comparison, subtraction, addition, etc... can be defined on timestamps which need special handling. So it is not just a normal integer. We have to be consistent across the codebase on how we track and store time to prevent compatibility issues down the road. The space that an instance of time requires is nothing compared to other things that we store, I/O pools, for examples.

2023-12-08 16:32 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/storage.py
> +    stored : List[HarvestedCrop]
That is indirectly an open question that we had in the design doc. For now, the focus here is on the harvested crops. We can always modify it of course. We could also consider bringing the purchase feed logic to this module (instead of handling it in the animal module)

2023-12-08 16:32 UTC, merged