Pen Rework
RuminantFarmSystems/RuFaS pull request #103
Opened 2021-12-21 03:07 UTC by ancheypeng

This pull request includes a rework of the Pen class which focuses on fixing the variable initializations as well as adding Sphinx style documentation.

**Problem:** 
Some of the attributes for the Pen class were declared outside of the initializer, and thus, the attributes maintained the same value for all instances of the class.

This caused some calculations relating to the pens to use the wrong values; instead of using the values tied to any specific instance, all instances of the pen class would share the same values for certain attributes because some attributes were declared outside of the class initializer.

**Fix:**
The attributes that were declared outside of the initializer were moved into the initializer. Any calculation involving an instance of the Pen class now uses the attributes corresponding to that instance.

**Additional Changes:**

Getters and setters were added for the “id” and “pen_type” instance attributes. The usage in other files for these two attributes has not yet been changed, but in the future, the getters and setters will be used instead of directly accessing the attributes. The rest of the variables remain the same.

Documentation was added detailing all of the Pen class attributes including the type and a short description. 

Some of the Pen class attributes involving dictionaries that contained the same fields were re-written to reduce line count. Instead of each attribute containing its own initialization of the same dictionary, a single dictionary was created, and each attribute was initialized to a deep copy of the dictionary.

Getters and setters were created for the other Pen class attributes as well, however, most were deemed unnecessary and removed. In the future, if any of these getters or setters need to be added, they can be found here: 

https://docs.google.com/document/d/1q6cxTo51KCaM3dtiPrtBWWqtMbAajhXgY7p0jfgg8bQ/edit?usp=sharing

2021-12-23 04:18 UTC, PooyaHekmati requested changes
Good job on applying the changes. I have commented on individual commits as well as the pull request. Please check both of them.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +                         [0], globals(), locals())
Let's put self.daily_variables[variable][0] in a variable with an intuitive name to help the reader understand why index 0 needs such treatment.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
>                  self.annual_variables[variable][2] = \
Let's put self.annual_variables[variable][2] in a variable with an intuitive name to help the reader understand why index 2 needs such treatment.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +            print(pen)
Are these prints necessary?

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +            print(self.daily_variables)
print?

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +            # this subsets the pen's allotted feed given the animals type(s)
What a sentence! Can you state it in a simpler form?

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +            #print(all_feeds)
remove this

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +            #index at 0 because there is a nested list here for some unknown reason
Change this to TODO, we need to know why this is the case

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +            print(individual_pen.feed_ids)
print?

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +            print(pen_id_list)
print?

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +                        'pen.ration[\'%s\'] if pen.pen_populated and \'%s\' in pen.feed_ids else 0' % (
Please add a TODO here, we need to reduce the complexity of this line; preferably, wrap this statement in a function with a good name

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +    # the following attributes were moved from outside the class' initializer into the
Is this comment needed? We already have the history in VCS.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
>      id = -1
why -1? If you don't know the answer, please add a TODO so we know someone needs to work on this

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        # __________________MOVED ATTRIBUTES IN___________________________
Unnecessary comment

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        self.animals_in_pen = []
If possible, rename the variable to all_animals_in_pen and remove the comment

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        self.pen_populated = False
Why do we have a variable for this? Let's create a function named is_pen_populated instead and implement the commented logic in it.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        self.classes_in_pen = set()
This should be in a function as well.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        self.avg_BW = 0
rename to an intuitive name like avg_body_weight

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        self.avg_DMIest = 0
rename to avg_dry_matter_intake_est

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +    # getters
remove

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +    # setters
remove

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        # total manure excretion of the animals in the pen
Is it a good idea to wrap all these total manure excretions in a dict, so we end up with a nested dict?

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        Returns the id_number: the unique id number of the pen
No, it doesn't. it returns id, not id_number.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        Returns the vertical distance to milking parlor, km
Does this function do anything to ensure the unit is km? If not, then the km belongs to the variable, not this function. So let's remove km from this comment.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        Returns the horizontal distance to milking parlor, km
Does this function do anything to ensure the unit is km? If not, then the km belongs to the variable, not this function. So let's remove km from this comment.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        return self.pen_type
pen_type sound like a private attribute

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        Returns the manure handling method used to clean the pen
This doesn't sound right

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        This variable represents the dictionary containing the ration for all the animals in the pen.
We already know that this comment is about this variable and you just mentioned that it is a dict; so "This variable represents the dictionary" is unnecessary and the whole line can be rewritten as "contains the ration for all the animals in the pen"
The same applies to other comments as well.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        Returns:
I have already commented on Adding some getters to pen.py commit.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        Sets the pen's vertical distance to milking parlor, measured in kilometers, to vert_dist.
remove measured in kilometers, it is explained in args

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        Sets the pen's horizontal distance to milking parlor, measured in kilometers, to hori_dist.
remove measured in kilometers, it is explained in args

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        self.init_dict = {"U": 0,
init_dict is a misleading name. Let's rename to something like manure excretion dict template. It must be private, if someone changes this variable that would cause a problem in the reset_manure method.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +
Why is this commented out? If you have implemented the same logic somewhere else, then you should remove this. Don't worry, we always have access to it in VCS.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +
Let's keep these comments, for now, we might need them in the future.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        self.lactating_total = copy.deepcopy(self.init_dict)
Can we wrap all of these in a dict?

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        self.lactating_total = copy.deepcopy(self.init_dict)
Let's move this entire thing into reset_manure method.

2021-12-23 04:18 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
>      def reset_manure(self):
Let's rename it to reset_manure_dicts or something similar

2021-12-30 17:38 UTC, KFosterReed commented on RUFAS/output_handler/reports/pen_report.py
> +
It looks like this is a copy and paste of the work that Simon was doing in this file to try to fix the ration reporting bug. We wanted the reporting bug fix separate from the pen rework request so I'm guessing that is why this is commented out? If so, as Pooya suggests, I think a better strategy would be to remove it since we will have access to this work through GitHub commit history.

2021-12-30 17:41 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +        It is gotten from the input file.
```suggestion
        Obtained from the input file.
```
small language clarity suggestion

2021-12-30 18:06 UTC, KFosterReed requested changes
I think it is looking good! I think a few edits following the comments/suggestions provided will get it ready for merging quickly!

2021-12-30 18:06 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +        It is gotten from the input file
```suggestion
        Obtained from the input file
```

2021-12-30 18:06 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +        It is gotten from the input file
small language clarity suggestion

2021-12-30 18:06 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +        This variable represents the number of stalls, gotten from the input file.
```suggestion
        This variable represents the number of stalls.
        Obtained from the input file.
```

2021-12-30 18:06 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +        This variable represents the housing type of the pen, gotten from the input file.
```suggestion
        This variable represents the housing type of the pen.
        Obtained from the input file.
```

2021-12-30 18:06 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +        This variable represents the bedding type of the pen, gotten from the input file.
```suggestion
        This variable represents the bedding type of the pen.
        Obtained from the input file.
```

2021-12-30 18:06 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +        This variable represents the housing type of the pen, gotten from the input file.
Should the definitions include descriptions of the acceptable values? For example, housing type can currently only be 'barn' but we are working on a couple of others

2021-12-30 18:06 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +    avg_nutrient_rqmts : dict
I think this is missing a description. An appropriate one would be: 

Represents the average nutrient requirements of the animals in the pen

2021-12-30 18:06 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +    avg_calf_nutrient_rqmts : dict
I don't remember why we needed this calf requirements variable separate from the other ration requirements variable but I am going to make an issue to remove this and just have one variable where the contents change based on the animal class

2021-12-30 22:37 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +        This variable represents the housing type of the pen, gotten from the input file.
Yes, if the accepted values are stored somewhere in the code, we can state in the comment that the accepted values are stored in address xyz. Also, ideally, we want the code to reject unaccepted values by throwing errors. When discussing these exceptions, we can write something like: rasies ValueError if house type is not in set abc.

2022-01-03 16:35 UTC, militsasotirova commented on RUFAS/routines/animal/pen.py
> +        This variable represents the housing type of the pen, gotten from the input file.
I see that this code is outdated, but for things like this (i.e. strings we use for different cases) we should probably create a constant. See `routines/animal/life_cycle/animal_events_constants.py` for how I did this in the life cycle code. This could be a fix-a-thon task, as it doesn't necessarily relate to the goal for this PR.

2022-01-03 16:45 UTC, militsasotirova commented on RUFAS/routines/animal/pen.py
> +        self.MEdiet = None
It looks like this is used on line 439. We could probably remove the declaration of `ME_intake`, and just directly pass `self.MEdiet` to `calc_manure_excretion()` if you want.

2022-01-03 16:47 UTC, militsasotirova commented on RUFAS/routines/animal/pen.py
> +        # TODO: add initial value
Initial value here could be 0. We should be consistent with what we have below where we initialize 
        `self.manure = None
        self.calf_total = None
        self.heifer_total = None
        self.dry_total = None
        self.lactating_total = None`
Should the initial values be 0 or None for all numerical attributes? I think it should be 0 but I'm open to other suggestions.

2022-01-03 16:51 UTC, militsasotirova commented on RUFAS/routines/animal/pen.py
> +    id : int
Adding comments for the attributes is a great idea! In future PRs that add attributes, we just have to ensure that this comment is expanded.

2022-01-03 16:53 UTC, militsasotirova commented on RUFAS/routines/animal/pen.py
> +    def set_id(self, pen_id):
Do we need this? The pen's ID should only be set once in the constructor and never changed, so an outside class should not have the ability to change this attribute.

2022-01-03 16:54 UTC, militsasotirova commented on RUFAS/routines/animal/pen.py
> +        self.heifer_total = self._copy_manure_template()
I like the simplifications here!

2022-01-03 16:57 UTC, militsasotirova commented on RUFAS/output_handler/reports/pen_report.py
> +                         [0], globals(), locals())
This structure is everywhere in the output handler code, so I think this change would be better as a fix-a-thon task.

2022-01-03 17:06 UTC, militsasotirova commented
I responded to a few of the previous conversations and made a few comments. Otherwise, looks good and I'll approve once those conversations are all resolved!

2022-01-03 22:26 UTC, ancheypeng commented on RUFAS/routines/animal/pen.py
> +        # TODO: add documentation for the following 8 attributes
These variables need documentation

2022-01-03 22:29 UTC, ancheypeng commented on RUFAS/routines/animal/pen.py
>          self.MEdiet = None
This variable needs documentation

2022-01-03 22:52 UTC, ancheypeng reviewed
I made some changes to the pen reporting system. The original code calculates the value for each variable by evaluating code stored in a string literal. This makes the code harder to debug and maintain, and it also led to some difficulty understanding the code because of the nested lists without clear documentation. The updated code uses the function "evaluate_variable" to convert a daily or annual variable to the actual value from the model. It is essentially just a long list of conditional statements. I also simplified the daily variables themselves. The old code stored the daily variables in the form { reporting_variable: [ code_variable_representation, units, [accumulator] }. Updating the accumulator would lead to some code in the form of "self.daily_variables[variable][2].append(some_value_here)" without an explanation for the 2 index. The new code stores the daily variables in the form { (reporting_variable, units) : [accumulator] }. The reporting variable and the corresponding units are paired together in a tuple, and the accumulator list is no longer nested. The code variable representation is also no longer included because it is replaced by the "evalute_variable" function. With this code, updating the accumulator could be done with just self.daily_variable.append(some_value_here). However, this is not yet implemented because the entire system relies on the accumulator being at the same index for all the reports. As a temporary fix, I created the function "remap_variables_dict" which remaps a dictionary of the new format to one of the old format to preserve the reporting functionality. This change in format could also be applied to the other reports as well.

2022-01-03 22:55 UTC, ancheypeng commented on RUFAS/routines/animal/pen.py
> +        # TODO: add initial value
The manure variables are all initialized to None because they are actually initialized in the reset_manure method, but according to the style guidelines, all attributes should be present in the initializer

2022-01-03 22:59 UTC, ancheypeng commented on RUFAS/output_handler/reports/pen_report.py
> +                         [0], globals(), locals())
I somewhat addressed this issue in my commit regarding a partial rework of pen_report

2022-01-04 20:07 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +        This variable represents the housing type of the pen, gotten from the input file.
I like the idea of adding this as a fixathon task.

2022-01-04 20:09 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +    avg_calf_nutrient_rqmts : dict
Anchey and I discussed this. We will revisit this another time

2022-01-05 06:13 UTC, ancheypeng commented on RUFAS/routines/animal/pen.py
> +        self.animals_in_pen = []
I think renaming variables and changing variables to functions might be a better task for the fixathon because most of them have to be changed outside of the Pen class as well.

2022-01-05 20:51 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +    TODO: make sure this description is correct
This is correct

2022-01-05 22:57 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +        The average phosphorus intake of the animals in the pen.
```suggestion
        The average phosphorus requirements of the animals in the pen.
```

2022-01-05 22:58 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +    avg_p_animal : float
```suggestion
    avg_p_animal : float
                            The average phosphorus content/mass of the animals in the pen
```

2022-01-05 23:01 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
>          self.MEdiet = None
The documentation for this should be: 

The metabolizable energy concentration of the diet fed to the pen

2022-01-06 21:45 UTC, KFosterReed approved these changes

2022-01-07 01:45 UTC, ancheypeng commented on RUFAS/output_handler/reports/pen_report.py
> +                         [0], globals(), locals())
This issue will be addressed in Fixathon Task 26.

2022-01-07 01:45 UTC, ancheypeng commented on RUFAS/output_handler/reports/pen_report.py
>                  self.annual_variables[variable][2] = \
This issue will be addressed in Fixathon Task 26.

2022-01-07 01:46 UTC, ancheypeng commented on RUFAS/routines/animal/pen.py
> +        self.animals_in_pen = []
This issue will be addressed in Fixathon Task 25.

2022-01-07 01:47 UTC, ancheypeng commented on RUFAS/routines/animal/pen.py
> +        self.pen_populated = False
This issue will be addressed in Fixathon Task 25.

2022-01-07 01:48 UTC, ancheypeng commented on RUFAS/routines/animal/pen.py
> +        self.classes_in_pen = set()
This issue will be addressed in Fixathon Tasks 12 and 13, along with the work done in heifer_ration_tester.

2022-01-07 01:48 UTC, ancheypeng commented on RUFAS/routines/animal/pen.py
> +        # total manure excretion of the animals in the pen
This issue will be addressed in Fixathon Task 25.

2022-01-07 01:49 UTC, ancheypeng commented on RUFAS/routines/animal/pen.py
> +        self.lactating_total = copy.deepcopy(self.init_dict)
This issue will be addressed in Fixathon Task 25.

2022-01-07 01:50 UTC, ancheypeng commented on RUFAS/routines/animal/pen.py
>      def reset_manure(self):
This issue will be addressed in Fixathon Task 25.

2022-01-07 02:05 UTC, PooyaHekmati approved these changes

2022-01-07 03:35 UTC, merged