Perform aggregation on referenced columns and scalar operations on each column
RuminantFarmSystems/RuFaS pull request #1042
Opened 2023-12-13 13:43 UTC by ltp23

This PR focuses on adding a couple of features to the report generator.

- Cross-referencing: Ability to refer to previously defined reports in the same report json config file (Issue #998).
- Constant columns: Adding a column that contains only some value. The typical use case for this is to do a horizontal aggregation operation with such a column first and then optionally do a vertical aggregation (Issue #997). 

```
   {
      "name": "Last Year's Average Daily Milk Production (gallons)",
      "filters": [
        "LifeCycleManager.daily_update.daily_milk_production"
      ],
      "constants": {
        "Liters to Gallons": 0.264172
      },
      "horizontal_aggregation": "product",
      "horizontal_first": true,
      "vertical_aggregation": "average",
      "slice_start": -365
    },
    {
      "name": "Last Year's Average Daily Number of Milking Cows",
      "filters": [
        "LifeCycleManager.daily_update.milking_cow_num"
      ],
      "vertical_aggregation": "average",
      "slice_start": -365
    },
    {
      "name": "Last Year's Average Daily Milk Production per Cow (gallons)",
      "cross_references": [
        "Last Year's Average Daily Milk Production (gallons)_hor_ver_agg",
        "Last Year's Average Daily Number of Milking Cows_ver_agg"
      ],
      "horizontal_aggregation": "division"
    }
```

The existing code for generating reports is still intact, just in case there is a need to go back to that version. However, I moved the code for handling the report generator in the OutputManager into a separate method.

---

Edit 1:
- Added issue numbers for the first two bullet points.
- Removed the padding section
- Changed the column titles a bit

---
Edit 2:
- Simplified the format for constants.
- Added suffixes to cross-reference columns.

2024-01-02 16:48 UTC, PooyaHekmati requested changes
Could not finish the review as the PR is not in a review-ready state. 
1. Clearly mention the issues that this PR is aiming to address.
2. Avoid packing other focal points in one PR (padding is out of the scope of this PR).
3. Docstrings are not informative and clear enough.
4. There are code organization issues here: misplaced methods (things that belong to RG are placed in OM, static methods are used with no justification)

2024-01-02 16:48 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                    )
Why is this if statement needed? what happens if filters is not in filter_content?

2024-01-02 16:48 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                filtered_pool = {}
add type annotation

2024-01-02 16:48 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                                  filtered_pool: Dict[str, Any] | None,
wrong type hint, `filtered_pool` comes from `_filter_variables_pool` which returns `Dict[str, pool_element_type]`

2024-01-02 16:48 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _handle_report_generation(self,
This method should be placed in ReportGenerator

2024-01-02 16:48 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            If there is an error in report generation, such as missing data or invalid configuration.
This docstring doesn't give any extra information. Provide more details for each case separately.

---
Update after reading the code: this function doesn't raise anything

2024-01-02 16:48 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                filtered_pool.update(reference_data)
```suggestion
                reference_datal.update(filtered_pool)
```
this prevents potential side effects.

2024-01-02 16:48 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    @staticmethod
why does this need to be static?

2024-01-02 19:33 UTC, ltp23 commented on RUFAS/output_manager.py
> +                    )
There is an if statement above that that checks for the absence of the `filters` and `cross_references` keys. 

```
if (
        not isinstance(filter_content, dict)
        or ("filters" not in filter_content.keys() and "cross_references" not in filter_content.keys())
):
    self.add_error(...)
```

If this part checks out, then we know there must be either `filters` or `cross_references` or both keys in the `filter_content`.

This means it is okay to have both filtered data from the output manager (using the `filters` key) and previously aggregated data (using the `cross_references` key) in the same report.

If this seems unnecessary, I can just allow for one or the other option.

2024-01-02 20:34 UTC, ltp23 commented on RUFAS/output_manager.py
> +                filtered_pool = {}
Okay, I will add this type to it `Dict[str, Dict[str, List[Any]]]`

2024-01-02 20:41 UTC, ltp23 commented on RUFAS/output_manager.py
> +    def _handle_report_generation(self,
I think this method should stay in the Output Manager so we can have easier access to all the `reports` and timestamp generation used in naming.

2024-01-02 20:59 UTC, tomhuhh reviewed
Thanks Loi! Here is a summary of my comments on this PR from the output standpoint based on our discussion. 

1. For the 'Last 6 Month's Heifer Population Growth' value, if it is not a special request, I think we can remove it as an example because it can be misleading. Otherwise, we need to find ways to correctly calculate it. 
2. We also agreed to update the unit for methane. So instead of '90 to 30 days ago Methane Emission from Lactating Cows', I would write '90 to 30 days ago Methane Emission from Lactating Cows (grams)'.
3. Calculations for milk yield need to be revisited, either it is daily milk yield per cow or  annual milk production per cow. 

Thanks for the hard work!

2024-01-02 21:34 UTC, ltp23 commented on RUFAS/output_manager.py
> +            If there is an error in report generation, such as missing data or invalid configuration.
Right, I will add a Notes section to describe when an error can occur and cause that report to be skipped. There won't be a `Raises` section because the error is logged by the Output Manager.

2024-01-03 15:09 UTC, ltp23 commented on RUFAS/output_manager.py
> +                filtered_pool.update(reference_data)
I think both versions are equivalent because `filtered_pool` and `reference_data` are created anew for every new report. Unless we make deep copies every time, both dictionaries can be modified in-place, which can corrupt the original data pool if not careful. The code in the report generator doesn't modify existing data and only creates new data, so it is okay not to do the deep copying. But if we want to be sure, deep copying may be necessary.

2024-01-03 15:29 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                    )
Please use explanatory variables to make the code more understandable and maintainable.

2024-01-03 15:31 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _handle_report_generation(self,
The domain of responsibility dictates where each method belongs to, not ease of access. This method is doing things that are not under the umbrella of Managing Outputs.

2024-01-03 15:35 UTC, ltp23 commented on RUFAS/output_manager.py
> +    @staticmethod
It doesn't need to be static. It could also be a normal instance method with `self` or a classmethod with `cls`. The general way that I use `staticmethod` here and in other places is when we don't need a specific instance object for that method to work on. For example, here, I could call this method directly without creating an `om` object — `OutputManager._check_for_missing_references(refs, reports)`. It can also be called like this `self._check_for_missing_references(...)` from another `self` method in OutputManager.

I understand this can be confusing by switching back and forth between different method styles. I'm open to keeping things simple by just using one style. 

Another thing to notice is static methods don't use the `self` variables, so these methods could also be moved somewhere else. But I don't think this is worth it if the methods are not that reusable in other contexts.

2024-01-03 15:42 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                filtered_pool.update(reference_data)
You have two dictionaries here and are appending them together. One of them is instantiated locally, the other one is an incoming arg. If you append the local one to the arg one (your current version), the caller receives this change as well, i.e., the function has a side effect. But if you append the arg to the local one, there won't be any side effects without needing deepcopy.
This code:
```Python
def append_local_to_arg(d):
    local_d={"2":2}
    d.update(local_d)
    
def append_arg_to_local(d):
    local_d={"3":3}
    local_d.update(d)
    
d={"1":1}
print(f"before any function calls {d=}")
append_local_to_arg(d)
print(f"after call to append_local_to_arg {d=}")
append_arg_to_local(d)
print(f"after call to append_arg_to_local {d=}")
```
Generates this output:
```
before any function calls d={'1': 1}
after call to append_local_to_arg d={'1': 1, '2': 2}
after call to append_arg_to_local d={'1': 1, '2': 2}
```

2024-01-03 16:14 UTC, ltp23 commented
Thank you, Haowen!

> 1. For the 'Last 6 Month's Heifer Population Growth' value, if it is not a special request, I think we can remove it as an example because it can be misleading. Otherwise, we need to find ways to correctly calculate it.

I will remove this example. Maybe we can add another example later about this topic.

> 2. We also agreed to update the unit for methane. So instead of '90 to 30 days ago Methane Emission from Lactating Cows', I would write '90 to 30 days ago Methane Emission from Lactating Cows (grams)'.

I will update the title to include the units.

> 3. Calculations for milk yield need to be revisited, either it is daily milk yield per cow or  annual milk production per cow.

This example is leaning more toward the average daily milk yield per cow. I tweaked the column names a bit to improve clarity. What I wanted to do was to come up with an example that was fairly plausible and also able to demonstrate the use of cross-referencing between columns in the report.

2024-01-03 17:20 UTC, ltp23 commented
> 1. Clearly mention the issues that this PR is aiming to address.

I will tag the issues in the descriptions.

> 2. Avoid packing other focal points in one PR (padding is out of the scope of this PR).

I will remove the code for padding for later.

> 3. Docstrings are not informative and clear enough.

I updated some docstring regarding the error handling.

> 4. There are code organization issues here: misplaced methods (things that belong to RG are placed in OM, static methods are used with no justification)

I added some more explanations to your specific questions. Since these are more organization and style questions without affecting functionality too much, they can be changed either here or later. Some choices I made were about convenience and accessibility to the existing code while others were more about coding style preferences.

2024-01-04 21:47 UTC, ltp23 commented on RUFAS/output_manager.py
> +    def _handle_report_generation(self,
Okay, I have moved the report generation code out of the OutputManager class and into the ReportGenerator class.

2024-01-05 20:52 UTC, Isgotkowitz requested changes
This is a great start on these issues Loi. Most of my comments are on minor things (formatting, docstrings, type annotations, etc).

I am requesting changes on 2 things:
1. There is almost no validation of constants right now, which makes it possible to crash the report generator or have it fail to report the reason why the report generation failed.
2. The current behavior on main allows a report to have no vertical or horizontal aggregation specified for a report. This is a very handy feature and it would be nice to have it preserved if possible.

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            info_map: Dict[str, Any],
Do you have an autoformatter makes these changes? If so, could you let me know what it is please? I would like to propose one for the team to use so that we can start to make our code look really consistent.

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +# !/usr/bin/env python3
```suggestion
```
I think we are trying to eliminate headers/shebangs in the codebase.
Edit: with issue #910, all credit lines were removed from the codebase, but not necessarily all shebangs. It seems that they are used inconsistently across the RuFaS codebase. Is there a particular reason or benefit to having this one here? If not, I think it would be better to remove it.

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +                                 ) -> List[Dict[str, str | Dict[str, str]]]:
```suggestion
    def handle_report_generation(
            self,
            filter_content: Dict[str, Any],
            filtered_pool: Dict[str, Dict[str, List[Any]]],
    ) -> List[Dict[str, str | Dict[str, str]]]:
```

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +            event_logs.append(error_event)
Would it be possible/reasonably easy to separate the except statement into two, one for each error type? If so, I think that should be done here and the error message made a little more specific.

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +                If there are no horizontal or vertical aggregation keys in the filter content.
```suggestion
        ValueError
            If the report data is empty.
            If the type of aggregation is not supported. The supported types are: sum, average, product,
                subtraction, division, SD.
            If there are no horizontal or vertical aggregation keys in the filter content.
```
This keeps the style consistent with what is requested in issue #1074

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +        for report inclusion.
```suggestion
        Notes
        -----
        This method organizes data from a filtered pool based on selected variables and slicing parameters.
        It caters to different data structures within the pool, ensuring data is formatted appropriately
        for report inclusion.
```

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +
Raises section here.

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +        -----
```suggestion
        Examples
        --------
```

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +            Otherwise, the name is set to the value of the `name` key in the filter content.
I think the description of the returned value should be "The unique name for this report generated from its contents." and the current description of the returned value should be kept, but placed in a "Notes" section.

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +        data = dict(filtered_pool)
Why does this line need to be here? `filtered_pool` should already be a dictionary?

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +    def clear_reports(self):
```suggestion
    def clear_reports(self) -> None:
```

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +    ) -> List[float]:
```suggestion
    ) -> Dict[str, List[float]]:
```
This should be changed back or the values being returned should be changed.

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +                raise ValueError(f"Constant name {constant.get('name')} already exists in report data.")
Are constants always going to be numbers? If so, they should be validated somewhere - it is currently possible to make the ReportGenerator crash by passing certain non-number values. There are also some non-number values that it handles somewhat gracefully, like when a value is `None`/null - but it doesn't log any errors specific to this issue.

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +            ]
What would you think about changing the way constants are specified to be a dictionary with the key being the name and the value being the value? For example, the above would change to: 
```suggestion
            "constants": {
                "Kilograms to Pounds": 2.20462,
                "Pounds to Dollars": 10
            }
```
This would make the constants section a little more robust because 1) it would not be possible* to pass constants with the same name, and 2) it would not be possible* to forget to add a name or value to any constants (*these would be possible, except the JSON would be invalid - which I think would be a benefit but I can see why this could be considered a drawback).

The drawbacks include the above design being less future-proof (for example, if constants needed to have more elements than just "name" and "value", this design would have to be scrapped), and it also might be a lot of work at this point to change the structure. If either of these are the case, disregard this comment.

2024-01-05 20:52 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +            f"Didn't find `horizontal_aggregation` or `vertical_aggregation` in {filter_content.get('name')}.")
I think it would be beneficial to modify this function so that reports without vertical or horizontal aggregation are allowed through. This is the current behavior on main, and I find it extremely useful when working with reports.

2024-01-08 19:11 UTC, PooyaHekmati commented
@ltp23 what is the status here?

2024-01-09 18:34 UTC, ltp23 commented on RUFAS/output_manager.py
> +            info_map: Dict[str, Any],
I think this one was auto-formatted by Pooya's IDE.

2024-01-09 18:45 UTC, ltp23 commented on RUFAS/output_manager.py
> +# !/usr/bin/env python3
I think we can remove the shebang lines across the files because they are useful when we run them individually on a unix-based machine.

2024-01-09 19:35 UTC, ltp23 commented on RUFAS/report_generator.py
> +            event_logs.append(error_event)
I can add the type of error in the log message. Because the way I handle those two error types is the same, I still have them combined though.

2024-01-09 20:28 UTC, ltp23 commented on RUFAS/report_generator.py
> +            Otherwise, the name is set to the value of the `name` key in the filter content.
Okay. I will move the rules for naming into the Notes section.

2024-01-09 20:31 UTC, ltp23 commented on RUFAS/report_generator.py
> +        data = dict(filtered_pool)
This is to create a shallow copy so new columns won't be appended to the `filtered_pool`.

2024-01-09 20:42 UTC, ltp23 commented on RUFAS/report_generator.py
> +    ) -> List[float]:
Right, the type here should be `Dict[str, List[float]]`.

2024-01-09 21:20 UTC, ltp23 commented on RUFAS/report_generator.py
> +                raise ValueError(f"Constant name {constant.get('name')} already exists in report data.")
I would assume the constants to be of type `int` or `float`. I'm not sure where the ideal place to validate these json specs files is. For now, I think we are doing the validation in the generator classes. 

Here, I will add a helper method to validate the `name` and `value` fields for each constant.

2024-01-10 01:54 UTC, ltp23 commented on RUFAS/report_generator.py
> +            ]
Right, I do see the merits and drawbacks of either approach. I like the dictionary approach for its succinctness. The array approach allows more info for each constant. Since the code for managing constants is isolated to this part of the code, we can change it later when we know more.

2024-01-10 23:01 UTC, ltp23 commented on RUFAS/report_generator.py
> +            ]
I decided to change to your suggestion because with the current use case, the dictionary format is easier for the user and it didn't take too long to make the update.

2024-01-10 23:05 UTC, ltp23 commented on RUFAS/report_generator.py
> +            f"Didn't find `horizontal_aggregation` or `vertical_aggregation` in {filter_content.get('name')}.")
I'm sorry about leaving out this existing functionality along with the suffixes for different aggregation types. I have put them back. 

Now with the additional feature of referencing previously generated columns, one thing to be careful of when using this is to not forget the appropriate suffixes like `_<column_name>`, `_hor_agg`, `_hor_ver_agg`, etc.

2024-01-11 14:25 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +# !/usr/bin/env python3
Sounds good. I will make an issue about this

2024-01-11 15:10 UTC, Isgotkowitz commented
@ltp23 would it be possible to change the behavior when no name is present? I think the prepending of `untitled_<number>-<timestamp>`, or just `_`, is unnecessary in many cases.

For example, reporting the time. It can be done effectively with this filter:
```json
{
  "multiple": [
    {
      "name": "",
      "filters": ["Time\\..*"]
    }
  ]
}
```
But in the behavior of Report Generator on `main`, it results in this report:
|_Time.day|_Time.year|_Time.calendar_year|
|-----------|-----------|----------------------|
|...|...|...|

And with the current behavior of Report Generator in this PR it results in
|untitled_11-Jan-2024_Thu_09-50-44.081395_Time.day|untitled_11-Jan-2024_Thu_09-50-44.081395_Time.year|untitled_11-Jan-2024_Thu_09-50-44.081395_Time.calendar_year|
|-----------|-----------|----------------------|
|...|...|...|

When it would probably be cleanest just to have the report be
|Time.day|Time.year|Time.calendar_year|
|-----------|-----------|----------------------|
|...|...|...|

This would obviously mean more work on the code though, and since it is not essential for addressing the issues in this PR it may be better to leave changing this behavior for another PR.

2024-01-11 18:38 UTC, ltp23 commented
Hi @Isgotkowitz, I simplified the column names as you suggested. I included your example in the example json file. Thank you for your suggestion.

2024-01-11 19:35 UTC, PooyaHekmati requested changes
I could not review the whole PR as I ran out of time and energy. AVOID submitting massive PRs like this.

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> -                    self.add_log(
don't remove this log.

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                    log_pool = report_generator.handle_report_generation(filter_content, filtered_pool)
why is `generate_report` renamed to `handle_report_generation`?

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        self.reports = {}
```suggestion
        self.reports: Dict[str, Dict[str, List[Any]]] = {}
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
>      def generate_report(
This method is now obsolete, why is it still in the codebase?

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +    def handle_report_generation(
I like `generate_report` as the name better, it is shorter and less ambiguous.

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        Generates a single report based on filtered data and aggregation criteria.
This can't be true because in the code you are calling `_generate_single_report` plus doing some other stuff. Therefore, this method is doing more than generating a single report.

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        """
```suggestion
        """
    Generates a report based on filtered data and aggregation criteria specified in filter_content. 
    This method logs the process of report generation and incorporates cross-references if provided.
    
    Note
    -----
    This method does not explicitly raise exceptions; it handles potential issues internally 
    and logs them.

    Parameters
    ----------
    filter_content : Dict[str, Any]
        Configuration for the report. This includes keys like 'name', 'filters', 'cross_references', 
        and aggregation instructions. The structure should align with the expected format for report generation.

    filtered_pool : Dict[str, Dict[str, List[Any]]]
        The data pool from which the report is generated. This should follow the structure of OutputManager's 
        variables pool, where each key represents a data category with its associated data.

    Returns
    -------
    List[Dict[str, str | Dict[str, str]]]
        A list of log events generated during the report creation process. Each log event is a dictionary 
        containing information such as 'log' type, 'message', and an 'info_map' with additional details.
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        init_event = {
```suggestion
        init_event_log = {
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +            error_event = {
```suggestion
            error_event_log = {
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        data = dict(filtered_pool)
```suggestion
        data_shallow_copy = dict(filtered_pool)
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +    def _generate_unique_report_name(self, report_name: str | None) -> str:
`ensure_unique_report_name_with_timestamp` sounds more descriptive

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        Checks if all the referenced reports are present.
are present in where?

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +    @staticmethod
I don't see why this needs to be static.

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +            raise ValueError(f"Error preparing report data => {e}")
Don't format it.
```suggestion
        except ValueError:
            raise
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +            raise ValueError(f"Error validating aggregation keys => {e}")
Don't format it.
```suggestion
        except ValueError:
            raise
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +    def _package_report_data(
```suggestion
    def _combine_aggregated_report_data(self,
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        Packages the horizontally and vertically aggregated data into a dictionary.
```suggestion
        Combines horizontally and vertically aggregated data based on specified aggregation criteria from filter_content.
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +    def _validate_aggregation_keys(filter_content: Dict[str, Any]) -> tuple[str | None, str | None]:
```suggestion
    def extract_and_check_aggregation_keys(self, filter_content: Dict[str, Any]) -> tuple[str | None, str | None]:
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        """
```suggestion
       """
    Extracts horizontal and vertical aggregation keys from the filter content and validates them against
    supported aggregation types.

    Parameters
    ----------
    filter_content : Dict[str, Any]
        A dictionary containing filter criteria, aggregation instructions, and scalar operation details.
        It should include keys for 'horizontal_aggregation' and 'vertical_aggregation' if applicable.

    Returns
    -------
    tuple[str | None, str | None]
        A tuple containing the horizontal and vertical aggregation keys, respectively.
        Returns None for each key if it is not specified or if it is not among the supported types.

    Raises
    ------
    ValueError
        Raised if the specified horizontal or vertical aggregation type is not supported. Supported types are defined in the AGGREGATION_FUNCTIONS dictionary.
    """
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +    def _apply_horizontal_aggregation(report_data: Dict[str, List[float]], loop_list: List[str],
```suggestion
    def _apply_horizontal_aggregation(self, report_data: Dict[str, List[float]], loop_list: List[str],
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        aggregated_data = []
```suggestion
        aggregated_data: List[float]= []
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +            filtered_temp_data = list(filter(None.__ne__, temp_data))
```suggestion
            non_null_data_points = list(filter(None.__ne__, temp_data))
```

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +    def _apply_vertical_aggregation(report_data: Dict[str, List[float]],
same comments as `_apply_horizontal_aggregation` apply.

2024-01-11 19:35 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +
```suggestion
```
As per setup.py, RUFAS is intended to run using Python 3.10+.

2024-01-11 19:39 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +                data.update(cross_reference_data)
```suggestion
                cross_reference_data.update(data)
```
with this change, do you still need the shallow copy?

2024-01-11 19:53 UTC, Isgotkowitz approved these changes
Addresses issues well, so I am approving. There are a few suggestions/comments that should be addressed before merging, but should all be simple fixes.

2024-01-11 19:53 UTC, Isgotkowitz commented on RUFAS/output_manager.py
>          Reads a text file containing a list of keys and filters the variables pool by those keys.
Seems like this function is used to parse all kinds of filter files, not exclusively filters files in text format. This docstring should be updated to reflect and any other things in it that are out of date.

2024-01-11 19:53 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +                         info_map)
I think this log should be relocated to the if statement which calls `handle_report_generation()`. As it is now, the OutputManager will log that it is generating a report for a filter file even if that filter file doesn't start with `report`.

2024-01-11 19:53 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +                        filter_content["filters"], filter_file
PyCharm is flagging the following type mismatch to me on this line: "Expected type 'list[str]', got 'str | int' instead"

2024-01-11 19:53 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +            raise ValueError(f"Error validating aggregation keys => {e}")
What about checking if there is any horizontal or vertical agg keys at all, and if not then returning `report_data` immediately? I.e. checking the easiest return path first. That would allow the `_package_report_data()` method to be simplified.

2024-01-11 19:53 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +        1. If the report name is None or empty, the name is set to `untitled_<timestamp>`.
```suggestion
        1. If the report name is None, the name is set to `untitled_<timestamp>`.
```

2024-01-11 20:29 UTC, ltp23 commented on RUFAS/report_generator.py
> +            raise ValueError(f"Error validating aggregation keys => {e}")
What I could improve here is moving the validation step for agg keys up before the report data prep step. 

I think the `_package_report_data()` is alright because I have different conditional checks. I could pass the two agg keys as direct arguments instead of through the `filter_content`.

2024-01-11 20:38 UTC, ltp23 commented on RUFAS/output_manager.py
> +                        filter_content["filters"], filter_file
This one is still somewhat unpredictable. Originally, we expected the type for each filter content object to be `Dict[str, str | int]`. Now the type of the values has evolved since, so it is no longer `str | int`.

2024-01-11 20:45 UTC, ltp23 commented on RUFAS/output_manager.py
> +                         info_map)
I think the location for `add_log()` is alright here because this message is for the whole filter file and not just an individual filter content. But I can add a check and only log the message when it is a report filter file.

2024-01-11 20:56 UTC, ltp23 commented on RUFAS/report_generator.py
> +                data.update(cross_reference_data)
This is optional. The code should still work without the shallow copy. Because the `cross_reference_data` variable is initialized inside the `if` clause, I don't want to use it outside the scope.

2024-01-11 20:58 UTC, ltp23 commented on RUFAS/report_generator.py
> +
Okay. I can remove this.

2024-01-12 14:34 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +            raise ValueError(f"Error validating aggregation keys => {e}")
> What I could improve here is moving the validation step for agg keys up before the report data prep step.
> I could pass the two agg keys as direct arguments instead of through the filter_content.

I think both of these changes improve the code, but they are not what I am suggesting.

I am suggesting changing this:
```python
        horizontally_aggregated = None
        vertically_aggregated = None

        if horizontal_agg_key:
            horizontal_aggregator = AGGREGATION_FUNCTIONS.get(horizontal_agg_key)
            loop_list = filter_content.get("horizontal_order", report_data.keys())
            horizontally_aggregated = self._apply_horizontal_aggregation(report_data, loop_list,
                                                                         horizontal_aggregator)

        if vertical_agg_key:
            vertical_aggregator = AGGREGATION_FUNCTIONS.get(vertical_agg_key)
            vertically_aggregated = self._apply_vertical_aggregation(report_data, vertical_aggregator)

        aggregate_report = self._combine_aggregate_report_data(horizontally_aggregated,
                                                               vertically_aggregated,
                                                               filter_content)

        return aggregate_report if aggregate_report else report_data
```
to this:
```python
        if not horizontal_agg_key and not vertical_agg_key:
            return report_data

        horizontally_aggregated = None
        vertically_aggregated = None

        if horizontal_agg_key:
            horizontal_aggregator = AGGREGATION_FUNCTIONS.get(horizontal_agg_key)
            loop_list = filter_content.get("horizontal_order", report_data.keys())
            horizontally_aggregated = self._apply_horizontal_aggregation(report_data, loop_list,
                                                                         horizontal_aggregator)

        if vertical_agg_key:
            vertical_aggregator = AGGREGATION_FUNCTIONS.get(vertical_agg_key)
            vertically_aggregated = self._apply_vertical_aggregation(report_data, vertical_aggregator)

        aggregate_report = self._combine_aggregate_report_data(horizontally_aggregated,
                                                               vertically_aggregated,
                                                               filter_content)

        return aggregate_report
```
I tried this and it doesn't seem to break the code - but it is up to you whether or not this is a worthwhile change to make.

2024-01-12 18:03 UTC, PooyaHekmati requested changes
In addition to the new comments, there are unresolved comments from the last review.

2024-01-12 18:03 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        if not isinstance(report_name, str):
`report_name` is typed as `str`, how can it not be str?!

2024-01-12 18:03 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +            raise
```suggestion
        try:
            horizontal_agg_key, vertical_agg_key = self._extract_and_check_aggregation_keys(filter_content)
            report_data = self._prepare_report_data_with_constants(filtered_pool, filter_content)
        except ValueError:
            raise
```

2024-01-12 18:03 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +            filtered_data = list(filter(None.__ne__, data))
non_null_data_points

2024-01-12 18:03 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        aggregated_data = []
add type hint

2024-01-12 18:03 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +    def _add_constants_data(
```suggestion
    def _add_constants_to_report_data(
```

2024-01-12 18:03 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        None
```suggestion
```

2024-01-12 18:03 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        constant_config = filter_content.get("constants")
```suggestion
        constants_config = filter_content.get("constants")
```

2024-01-12 18:03 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        Validate constants before adding them to report data.
As far as this method is concerned, adding constants to the report is not a thing. Instead, briefly explain what validation means in this context.

2024-01-12 18:03 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +            constant_config: Dict[str, int | float]
```suggestion
            constants_config: Dict[str, int | float]
```

2024-01-12 18:06 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +                data.update(cross_reference_data)
I don't understand what you mean by _optional_. A function has to have no side effects and avoid any unnecessary operations. If swapping the operands saves a shallow copy operation while ensuring there are no side effects, there is no reason to do the extra work of copying.

2024-01-12 18:17 UTC, ltp23 commented on RUFAS/output_manager.py
> +                    log_pool = report_generator.handle_report_generation(filter_content, filtered_pool)
This is okay now. I removed the older version.

2024-01-12 18:18 UTC, ltp23 commented on RUFAS/report_generator.py
> +        Generates a single report based on filtered data and aggregation criteria.
I changed the name `_generate_single_report` to `_generate_report_data`.

2024-01-12 18:32 UTC, ltp23 commented on RUFAS/report_generator.py
> +            raise ValueError(f"Error validating aggregation keys => {e}")
I see. I can add this check to exit early. Thanks, Ed.

2024-01-12 18:37 UTC, ltp23 commented on RUFAS/report_generator.py
> +        if not isinstance(report_name, str):
I will remove this check because before I allowed the name to not be of type str and then converted it to str.

2024-01-12 20:10 UTC, PooyaHekmati requested changes
Please address all comments before requesting a review:
https://github.com/RuminantFarmSystems/MASM/pull/1042/files#r1449241431
https://github.com/RuminantFarmSystems/MASM/pull/1042#discussion_r1450771190
https://github.com/RuminantFarmSystems/MASM/pull/1042#discussion_r1450774937

Also, the name and docstring of `generate_report` and `_generate_report_data` need to be improved. Probably, removing the word `single` from `generate_report`'s docstring and renaming `_generate_report_data` to something that better captures its functionality would fix the issue.

2024-01-12 20:10 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        Generates a report based on filtered data and aggregation criteria, including scalar operations and constants.
So, the name of the function states that we generate `report_data` here, while the docstring states that we generate a `report` here. What's going on? Which one are we doing? How can `report` and `report_data` be the same? They are inherently different things. What do you think about `perform_aggregation` or something like that for its name?

2024-01-12 20:10 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        Generates a single report based on filtered data and aggregation criteria.
why do we need to emphasize on report being `single` here?

2024-01-12 21:39 UTC, ltp23 commented on RUFAS/report_generator.py
> +        Validate constants before adding them to report data.
I added the following to the docstring

```
Validate each name-value pair in the constants config dictionary before adding
        each constant as a column to the report data.
```

2024-01-12 21:41 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        Validate constants before adding them to report data.
That doesn't address the comment. The comment is saying that this method has nothing to do with adding constants to report data, so there is no reason to mention that in its docstring. Instead, docstring has to elaborate what does validation mean here, which still doesn't.

2024-01-12 21:48 UTC, ltp23 commented on RUFAS/report_generator.py
> +                data.update(cross_reference_data)
If I adjust it like you suggested, it would look like this

```
if "cross_references" in filter_content.keys():
    self._check_for_missing_references(filter_content["cross_references"])
    cross_reference_data = {ref: self.reports[ref] for ref in filter_content["cross_references"]}
    cross_reference_data.update(filtered_pool)

report_data = self._generate_report_data(cross_reference_data, filter_content)
```

This should work and the functionality would be the same. My point was the `cross_reference_data` variable was defined inside the if-clause. But this is not a problem if you are more concerned about the extra copying. I will use your version.

2024-01-12 21:52 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +                data.update(cross_reference_data)
I still don't understand the hesitation and resistance to the change. If there are some objective problems with it and it doesn't work as intended, please elaborate. Otherwise, the suggested change saves an unnecessary operation.

2024-01-12 21:56 UTC, ltp23 commented on RUFAS/report_generator.py
> +        Generates a report based on filtered data and aggregation criteria, including scalar operations and constants.
The names are confusing for me too. I can change to `perform_aggregations`.

2024-01-12 22:00 UTC, ltp23 commented
> why do we need to emphasize on report being single here?

What I mean here is the RG generates an individual report for each filter-content object. I changed the docstring to this 'Generates an individual report specified by the given filter content.'

2024-01-12 22:30 UTC, PooyaHekmati requested changes
two edits to docstrings plus two unresolved comments:
https://github.com/RuminantFarmSystems/MASM/pull/1042/files#r1449241431
https://github.com/RuminantFarmSystems/MASM/pull/1042#discussion_r1450950546

2024-01-12 22:30 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        Generates an individual report specified by the given filter content.
```suggestion
        Generates a report specified by the given filter content.
```

2024-01-12 22:30 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        Generates a report based on filtered data and aggregation criteria, including scalar operations and constants.
```suggestion
        Fetches aggregation keys from the filter content and applies aggregation to the data.
```

2024-01-12 22:47 UTC, ltp23 commented on RUFAS/report_generator.py
> +        Validate constants before adding them to report data.
I updated it to this to explain what rules are being checked. Or maybe this is too detailed.

```
Validates the names and values of the constants in the constants_config.

This method checks that each constant's name is not None, a non-empty string, and
is unique compared to the names of all the existing reports. It also verifies that
each constant's value is a number (int or float) and not None.

```

2024-01-12 23:02 UTC, ltp23 commented on RUFAS/output_manager.py
> -                    self.add_log(
I haven't removed this log. There were two places I added init log comments.

1. In the OutputManager class, around lines 779-784

```
if filter_file.startswith(
        self.__supported_filter_types_prefixes["report"]
):
    self.add_log("init_report_generation",
                 f"Generating report for file: {filter_file}",
                 info_map)
```

2. Then for each filter-content, there is another init log. This is done in the ReportGenerator class. (Around lines 190-195)

```
init_event_log = {
    "log": "start_generate_individual_report",
    "message": f"Start generating individual report: {individual_report_name}",
    "info_map": info_map,
}
event_logs.append(init_event_log)
```

2024-01-14 18:17 UTC, PooyaHekmati approved these changes

2024-01-14 19:07 UTC, merged