Cow repro refactor
RuminantFarmSystems/RuFaS pull request #1055
Opened 2023-12-15 19:48 UTC by ltp23

This PR focuses on restructuring the different reproduction protocols for cows. 

In the metadata files, I have removed the `cow_repro_programs` section and the `cows` section is the one being used instead. 

There are many different possible protocol combinations to mix and match, but I think the resynch ones seem trickier to get right. There is an open issue #1033 related to the ED-TAI coupled with the presynch process. It seems like it is possible to include it here or in the next PR though I'm not sure. 

cow_repro_method: `ED`
presynch_protocol: `N/A`
resynch_protocol: `N/A`
repro_sub_protocol: `N/A`

cow_repro_method: `TAI`
presynch_protocol: `PreSynch`, `Double OvSynch`, `G6G`
resynch_protocol: `TAIbeforePD`, `TAIafterPD`, `PGFatPD`
repro_sub_protocol: `Ov Synch 48`, `Ov Synch 56`, `CoSynch 72`, `5d CoSynch`

cow_repro_method: `ED-TAI`
presynch_protocol: `N/A`
resynch_protocol: `TAIbeforePD`, `TAIafterPD`, `PGFatPD`.
repro_sub_protocol: `Ov Synch 48`, `Ov Synch 56`, `CoSynch 72`, `5d CoSynch`

---

Diagrams

[Link to folder](https://whimsical.com/cow-repro-protocols-KCGFZkgpcTz8gCh4GtEWDc)

2023-12-20 05:25 UTC, tomhuhh reviewed
Thanks Loi! So far I have only reviewed the input file and left some comments there. I also tested the code with some example scenarios using 'ED-TAI' as the cow repro protocol. I think the results look promising. I'll review the rest of the code when I find more time, either this week or next week. Thanks again! 

![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/f1290fe4-289e-4811-9440-95e9b30949cd)

2023-12-20 05:25 UTC, tomhuhh commented on input/data/animal/default_animal.json
> +                    "tai_program_start_day": 72
Thanks Loi for working on this! I think we should be able to remove the duplicate requests for information related to cow repro protocols?

2023-12-20 05:25 UTC, tomhuhh commented on input/data/animal/default_animal.json
> +
Similarly here, should we remove the duplicate for input requests related to preg check?

2023-12-20 19:25 UTC, ltp23 commented on input/data/animal/default_animal.json
> +                    "tai_program_start_day": 72
Thanks Haowen. I will remove the `cow_repro_programs` section.

2023-12-20 19:27 UTC, ltp23 commented on input/data/animal/default_animal.json
> +
I added an extra set of preg-check parameters for cows but I didn't have the literature values for them. So currently, they have the same values as those of heifers.

2023-12-21 21:05 UTC, krb78 requested changes
Hi Loi! I think you did an awesome job with this! It's much clearer! I had a few questions that would be great for us to address before we merge this in (especially in regards to the ED-TAI protocol) and a few minor changes I think you can make easily (or I hope). Also, I hope it's straightforward enough that sometimes I only made a comment once, but there are a few places we need to make the update (ie the default value for Ovsynch56 conception rate). 

I saw a lot of code about Estrus Detection deleted, but is there some that was changed that we do need to review?

2023-12-21 21:05 UTC, krb78 commented on RUFAS/routines/animal/life_cycle/animal_constants.py
> +PRESYNCH_PERIOD_START = "Presynch period started"
There are many different "presynch" protocols, could we label this one "presynch11" or "presynch12" as appropriate? (there are 14, 12, 11, and 10 day versions of this protocol, so labeling it as the one it is will help us and users)

2023-12-21 21:05 UTC, krb78 commented on RUFAS/routines/animal/life_cycle/hormone_delivery_schedule.py
> +            16: {
If we have a presynch11 (the "presynch" protocol ends 11 days after the final PGF and the first GnRH of the ovsynch protocol begins on day 25), then I think the double ovsynch protocol is missing a day. The GnRH shot of the ovsynch (TAI protocol) should begin on day 17. I might misunderstand what day the GnRH of the TAI protocol is beginning, but based off of how G6G and presynch are set up, I think we are off by a day.

2023-12-21 21:05 UTC, krb78 commented on RUFAS/routines/animal/life_cycle/hormone_delivery_schedule.py
>              10: {'deliver_hormones': ['GnRH']},
In a cosynch72 protocol, the final GnRH shot should occur at the same time as breeding on day 11.

2023-12-21 21:05 UTC, krb78 commented on RUFAS/routines/animal/life_cycle/hormone_delivery_schedule.py
> +                'set_ai_day': True,
In a 5 day cosynch, the final GnRH shot and the TAI happen on the same day (day 8)

2023-12-21 21:05 UTC, krb78 commented on input/data/animal/default_animal.json
> +			"breeding_start_day_h": 380,
Maybe I'll arrive at the answer to this question as I progress, but is this truly the date breeding begins in heifers or is it the date we start simulating estrus? If it's the latter (which it was prior to refactor) - can we update the name of the input to accurately show that?

2023-12-21 21:05 UTC, krb78 commented on input/data/animal/default_animal.json
> +				"preg_loss_rate_1": 0.02,
so these are for heifers? could we call it "heifer_preg_loss_rate_1"?

2023-12-21 21:05 UTC, krb78 commented on input/data/animal/default_animal.json
> +
I think that's fine, Loi. Across the industry this data isn't well established because truthfully heifers lose so few pregnancies. But we can determine updated defaults for that at a later time.

2023-12-21 21:05 UTC, krb78 commented on input/metadata/ARL_metadata.json
> +                "description": "Sub-protocol for cow reproductive program. This ONLY applies to the TAI repro protocol.",
Question, Loi: what protocol for TAI is instituted in an "ED-TAI" herd? I thought it would be the same as this "repro_sub_protocol" in which case we actually need this "sub-protocol" to be able to be instituted for animals in the TAI-ED program. In this scenario, it will need to have a start date AFTER the VWP date. In a TAI only program, the sub-protocol will begin BEFORE the VWP date. Perhaps I just misunderstand how the ED-TAI group is working and it will become clearer as I progress through the code.

2023-12-21 21:05 UTC, krb78 commented on input/metadata/ARL_metadata.json
> +                  "description": "Conception Rate -- The conception rate for the cow reproductive program (default is 0.6). This ONLY applies to the TAI repro protocol.",
just an FYI you have this written as 0.6 in the description but the code one line below says the default is 0.5. Also, like my question above, it seems this conception rate should apply to animals receiving TAI in either the TAI protocol or the ED-TAI protocol.

2023-12-21 21:05 UTC, krb78 commented on input/metadata/ARL_metadata.json
>                  "description": "Resynch Protocol -- Resynch protocol for cow before/at/after pregnancy check day in the TAI (Timed Artificial Insemination) program",
A Resynch_protocol needs to be able to be instituted in both the TAI and the ED-TAI programs.

2023-12-21 21:05 UTC, krb78 commented on tests/animal_module_tests/test_repro_helper_modules.py
>          10: {'deliver_hormones': ['GnRH']},
There shouldn't be 2 GnRH shots in this protocol on days 9 and 10, just one on day 9. Breeding occurs on day 10.

2023-12-21 21:05 UTC, krb78 commented on tests/animal_module_tests/test_repro_helper_modules.py
>          10: {'deliver_hormones': ['GnRH']},
Same here as above - breeding (TAI) should occur on day 10, not another GnRH shot.

2023-12-21 21:05 UTC, krb78 commented on tests/animal_module_tests/test_repro_helper_modules.py
>          10: {'deliver_hormones': ['GnRH']},
The GnRH and TAI should both occur on day 10.

2023-12-21 21:05 UTC, krb78 commented on tests/animal_module_tests/test_repro_helper_modules.py
>          8: {'deliver_hormones': ['GnRH']},
TAI should occur the same day (day 8) as the GnRH shot.

2023-12-22 18:31 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/animal_constants.py
> +PRESYNCH_PERIOD_START = "Presynch period started"
Yes, we can add a specific label. Currently in the animal event log, it will look like this. When you run the program, one of the output files is `default_scenario_saved_variables_json_animal_events_for_cows<timestamp>.json` in the `output` folder. 
<img width="660" alt="image" src="https://github.com/RuminantFarmSystems/MASM/assets/98855117/fbf822f6-ed01-4f33-986c-782f26cd52b8">

Also, we only have 3 options for presynch protocols: Presynch, Double OvSynch, and G6G, so we are missing one. I'm not sure how to map these to the 4 options you mentioned.

2023-12-22 19:56 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/hormone_delivery_schedule.py
> +            16: {
This point is kinda subtle. Here, the `set_tai_start` flag means starting the TAI protocol on the following day. Before going into more details, I think the event log looks correct actually.

<img width="572" alt="image" src="https://github.com/RuminantFarmSystems/MASM/assets/98855117/f570c057-82d8-4b31-9a9a-f7139203b27f">

The code would be easier to work with when we set the presynch end and tai start flags on the same day. This would prevent the following scenario where the presynch period has just ended but the TAI period hasn't started yet, there is a possibility of re-entering another presynch. 

Ideally, we would want the stated day to be the day that the event is happening. There are several workarounds: 
- If we can assume another presynch cannot happen right after one another, then a simple check between the current day and the day the last presynch ended would work.
- Change from `set_tai_start` label to `set_tai_start_next_day` for clarity.
- Have a mini repro program state management system that helps keep track of the many possible transitions between repro programs. For example, at any one point, a cow's repro program can be in one or more of the following states: waiting, presynch, TAI, resynch, ED, etc.

2023-12-22 20:22 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/hormone_delivery_schedule.py
>              10: {'deliver_hormones': ['GnRH']},
Yes, I will move that to day 11.

2023-12-22 20:32 UTC, ltp23 commented on input/data/animal/default_animal.json
> +			"breeding_start_day_h": 380,
I have been only using this parameter in heifers. When a heifer reaches this day, we start simulating estrus or start a TAI protocol. What name would you like to change it to?

2023-12-22 20:37 UTC, ltp23 commented on input/data/animal/default_animal.json
> +				"preg_loss_rate_1": 0.02,
Based on this and the other comment about the parameters for cow pregnancy loss rates not so well-established and so minuscule, I think I would remove those newly added parameters and keep these the same for both heifers and cows.

2023-12-22 21:28 UTC, ltp23 commented on input/metadata/ARL_metadata.json
>                  "description": "Resynch Protocol -- Resynch protocol for cow before/at/after pregnancy check day in the TAI (Timed Artificial Insemination) program",
Yes, I will update the metadata descriptions to clarify this.

2023-12-22 21:39 UTC, ltp23 commented on input/metadata/ARL_metadata.json
> +                  "description": "Conception Rate -- The conception rate for the cow reproductive program (default is 0.6). This ONLY applies to the TAI repro protocol.",
Right, I will update this. This conception applies to any TAI procedure used in both TAI and ED-TAI protocols.

2023-12-22 21:47 UTC, ltp23 commented on input/metadata/ARL_metadata.json
> +                "description": "Sub-protocol for cow reproductive program. This ONLY applies to the TAI repro protocol.",
In both TAI and ED-TAI protocols, the `repro_sub_protocol` specifies the specific TAI procedure to be used.

2023-12-22 22:35 UTC, ltp23 commented on input/metadata/ARL_metadata.json
> +                "description": "Sub-protocol for cow reproductive program. This ONLY applies to the TAI repro protocol.",
In the TAI-only protocol, if there is a presynch period, then the presynch period will start when the number of days in milk is equal to the voluntary waiting period (currently set at 50).  The first day of the TAI procedure will follow immediately the day after the presynch period ends. So I think this is different from your description, and I'm missing the scenario where there is no presynch protocol set.

2023-12-22 23:28 UTC, ltp23 commented on input/metadata/ARL_metadata.json
> +                "description": "Sub-protocol for cow reproductive program. This ONLY applies to the TAI repro protocol.",
For the ED-TAI protocol, if there is no estrus detected in the period between the end of the voluntary waiting period and the day before the tai program start day (between 51 and 69 days in milk), then a TAI procedure will start on day 70.

2023-12-25 20:19 UTC, tomhuhh commented on input/data/animal/default_animal.json
> +						"tai_program_start_day": 70
I'm just curious, what is the difference between 'estrus_detection_rate' and 'estrus_conception_rate' of the animal category (i.e. either 'heifers' or 'cows') vs. 'conception_rate' and 'estrus_detection_rate' for the specific repro sub protocol? Should they refer to the same things? Thanks!

2023-12-26 14:45 UTC, krb78 commented on RUFAS/routines/animal/life_cycle/animal_constants.py
> +PRESYNCH_PERIOD_START = "Presynch period started"
Hi Loi, I'm actually only requesting that we label "Presynch" to be "PresynchXX" with the XX being the number of days between the last PGF shot and the start of the Ovsynch56. Double Ovsynch and G6G are specific protocols in and of themselves, but "Presynch" has a number of days associated with it because there are 4 different versions of this protocol and we are only simulating one of the 4 options.

2023-12-26 14:48 UTC, krb78 commented on RUFAS/routines/animal/life_cycle/hormone_delivery_schedule.py
> +            16: {
Ah, ok, thanks for clarifying this. Your event log does look correct. I think changing the name from set_tai_start to set_tai_start_next_day might be the easiest and most clarifying change we can make. :) From there, the reader/user will know what is happening :)

2023-12-26 15:02 UTC, krb78 commented on input/data/animal/default_animal.json
> +			"breeding_start_day_h": 380,
Thanks, Loi! I think if we changed this from breeding_start_day_h to estrus/repro_simulation_start_day_h (am I allowed to have a / in my name?) or breeding_protocol_start_day_h that would clarify things! I just want us to signify its not the day we start breeding, it's the day we start the breeding protocol.

2023-12-26 15:05 UTC, krb78 commented on input/data/animal/default_animal.json
> +				"preg_loss_rate_1": 0.02,
I wouldn't remove the newly added parameters, Loi. We should keep them, they are very different than cows. If cows lose almost 10% of pregnancies between 32 and 60 days, heifers lose ~1% of pregnancies and virtually 0% of pregnancies between 60 and 200 days. We need to make this differentiation but the problem is, the rate of pregnancy loss is so low, it's not something that is well researched and reported on. We could look at some farm or DHIA repro records to base this number on.

2023-12-26 15:16 UTC, krb78 commented on input/metadata/ARL_metadata.json
> +                "description": "Sub-protocol for cow reproductive program. This ONLY applies to the TAI repro protocol.",
In reality, many farms do a "presynchronization" to bring cows into estrus, then breed off heats, then do what we colloquially call a "clean up" or "back door" ovsynch. In this scenario, a protocol most similar to the one we have labeled as "presynch" would be instituted, but then cows that demonstrate estrus would be bred and those that don't demonstrate estrus would continue on to the TAI protocol (Ovsynch56 for example). 

Largely, I was just trying to ensure that RuFaS will allow for the VWP to be before or after the TAI program start day and that I understand the code well enough to understand what to put in as the VWP. Technically the VWP should be the earliest day at which we breed cows. Therefore it would be the following in each of the following scenarios: 
1) A TAI only (double ovsynch starts on day 45, ovsynch 56 starts on day 62, TAI occurs on day 72): VWP = 72
2) A ED-TAI program (estrus detection begins on day 50, we give cows 1 week to show estrus, ovsynch 56 begins on day 57, TAI is day 67): VWP = 50
3) An ED only program (estrus detection begins on day 50): VWP = 50. 

The above VWP are what someone familiar with dairy management would write for the VWP in each scenario. I just want to make sure that RuFaS does not always expect VWP to occur **before** the TAI protocol start date, because in the 1st scenario of TAI only, VWP occurs at the very end/upon completion of the protocols.

2023-12-26 19:43 UTC, tomhuhh commented
Hello Loi! If I set 'resynch_protocol' to 'TAIafterPD', the following error will show up. However, if I set it to 'TAIbeforePD', there is no error. I think this might need some further investigation. Thanks! 
![Screenshot 2023-12-26 at 2 42 53 PM](https://github.com/RuminantFarmSystems/MASM/assets/52800053/947d9306-87d8-4be6-a63c-c99bbcb8123f)

2023-12-26 20:06 UTC, tomhuhh commented
Something might have changed since last week I reviewed this branch. In addition to the error mentioned above, the behavior of the herd structure is also not as good as last week's version. 

This is with the input provided by the farm except that 'resynch_protocol' is set to 'TAIbeforePD'. 

![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/b7695b55-4bf7-419e-84e7-e69e18e211eb)

This is when I made the changes suggested by Kaitlyn a while ago while keeping  'resynch_protocol' as 'TAIbeforePD'.  The specific changes include: 

- TAI conception rate to 55%, DNB to 250 days, & estrus detection rate for cows to 0.9 
- Low MY cut-off - 30 kg 
- Also, I had to run longer for the herd structure to stablize. 

![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/c19c6589-86d1-4e16-b6ef-7f1238c218dc)

The performance of the herd structure is better with these assumptions. 

Thanks!

2023-12-27 21:59 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/animal_constants.py
> +PRESYNCH_PERIOD_START = "Presynch period started"
Kaitlyn was suggesting to just change the name of "PreSynch" to "PreSynch11" @ltp23

2023-12-27 23:47 UTC, YijingGong commented
The PR looks in good shape already. Good job @ltp23. Just a few comments:

1. cow ED
pure ED with N/A for presynch, repro_sub_protocol, and resynch_protocol. VWP = 50, detection rate = 0.65, conception rate = 0.6
The event log seems pretty correct:
"1379": [
            "simulation_day=47",
            "new birth, start milking",
            "1st estrus after calving: estrus day scheduled on day 1403"
          ],
          "1403": [
            "simulation_day=71",
            "estrus occurred before the end of voluntary waiting period",
            "estrus day scheduled on day 1420"
          ],
          "1420": [
            "simulation_day=88",
            "estrus occurred before the end of voluntary waiting period",
            "estrus day scheduled on day 1445"
          ],
          "1445": [
            "simulation_day=113",
            "estrus occurred",
            "estrus not detected",
            "estrus day scheduled on day 1459"
          ],
          "1459": [
            "simulation_day=127",
            "estrus occurred",
            "estrus detected",
            "AI day scheduled on day 1460"
          ],
          "1460": [
            "simulation_day=128",
            "AI performed",
            "inseminated with conventional",
            "failed conception at rate 0.5",
            "cow not pregnant",
            "estrus day scheduled on day 1482"
          ],
          "1482": [
            "simulation_day=150",
            "estrus occurred",
            "estrus detected",
            "AI day scheduled on day 1483"
          ],
          "1483": [
            "simulation_day=151",
            "AI performed",
            "inseminated with conventional",
            "successful conception",
            "cow pregnant"
          ],
But it seems the parity 1 cow % is a bit too high (~70%), any thoughts? <img width="581" alt="Screenshot 2023-12-27 at 4 41 04 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/51036031/ae209e8e-3c8d-40cc-9c1c-bb84c0285313">

2. cow TAI 
"PreSynch" + "OvSynch 56" + "TAIbeforePD", VWP = 69, tai_start_day = 45
"1217": [
            "simulation_day=63",
            "new birth, start milking"
          ],
          "1285": [
            "simulation_day=131", **<-- 1285 - 1217 = 68. The code currently starts the TAI program on the day of VWP, but we should have started it on the day of tai_start_day. VWP should be used to determine whether the ai_day should be scheduled (before WVP, no ai_day should be scheduled).**
            "Presynch period started: PreSynch",
            "inject PGF"
          ],
          "1299": [
            "simulation_day=145",
            "inject PGF"
          ],
          "1310": [
            "simulation_day=156",
            "Presynch period ended: PreSynch",
            "TAI period started: OvSynch 56"
          ],
          "1311": [
            "simulation_day=157",
            "inject GnRH"
          ],
          "1318": [
            "simulation_day=164",
            "inject PGF"
          ],
          "1320": [
            "simulation_day=166",
            "inject GnRH"
          ],
          "1321": [
            "simulation_day=167",
            "inject GnRH"
          ],
          "1322": [
            "simulation_day=168",
            "AI day scheduled on day 1322",
            "TAI period ended: OvSynch 56",
            "AI performed",
            "inseminated with conventional",
            "successful conception",
            "cow pregnant",
            "setting up resynch TAI protocol: **OvSynch 56**" **<-- It's doing the "TAIbeforePD" correctly, but the event log is wrong here**
          ],
          "1348": [
            "simulation_day=194",
            "inject GnRH"
          ],
          "1354": [
            "simulation_day=200",
            "pregnancy check 1: confirmed",
            "discontinued resynch TAI protocol after first preg check confirmed: **OvSynch 56**" **<-- same here**
          ],


3. cow ED-TAI
VWP = 50, tai_start = 80, "N/A"for presynch, "OvSynch 56" for repro_sub_protocol + "TAIafterPD" for resynch_protocol:
"1195": [
            "simulation_day=103",
            "AI performed",
            "inseminated with conventional",
            "failed conception at rate 0.5499999999999999",
            "cow not pregnant", 
            "estrus day scheduled on day 1213" **<-- starting from here, doing correctly the "TAIafterPD" resynch, but can we keep consistency, add a line as before saying "setting up resynch TAI protocol: TAIafterPD". Similarly for "PGFatPD"**
          ],
          "1213": [
            "simulation_day=121",
            "estrus occurred",
            "estrus detected",
            "AI day scheduled on day 1214"
          ],
Another case when I tested "PGFatPD":
"1546": [
            "simulation_day=142",
            "AI day scheduled on day 1546",
            "TAI period ended: OvSynch 56",
            "AI performed",
            "inseminated with conventional",
            "failed conception at rate 0.4",
            "cow not pregnant",
            "estrus day scheduled on day 1573"
          ],

When I was reviewing the code, I had a question. Likely this is for Kaitlyn and Kristan. Currently, the code has a function (_reduce_conception_rate_based_on_parity) to reduce the conception rate for higher parity cows, do we still want this function? Cuz I am thinking about the pilot farms, they are basically reporting what they observed. Maybe we don't want to account for the reduced fertility for higher parity cows? @KFosterReed @krb78

2024-01-02 16:16 UTC, krb78 commented
I have 2 questions/thoughts. 

1) @YijingGong in your comments above, in scenario 2 where you are testing the resynch function. Do you just want RuFaS to write "TAIbeforePD" instead of "Ovsynch56" in the event log because technically, RuFaS is doing an Ovsynch56 protocol (and it should be doing this - so it is correct)? I'll defer to you and your expertise with this, because for me, I don't inherently see a problem with calling it "Ovsynch56" as that is the protocol we are executing, but if you wanted to be able to track resynchronization breedings differently than first breedings, I understand why you'd want your event log to read differently. 

2) For the pilot farms because the farmers are reporting their average conception rate, we should be setting the conception rate parity decrease to 0.0 instead of 0.026. However, if RuFaS is being used to run research simulations or other scenarios, I think we will still want this parity conception rate decrease to exist. Does that make sense to you @KFosterReed and @YijingGong?

2024-01-02 17:19 UTC, jadamchick commented on RUFAS/routines/animal/life_cycle/cow.py
> +        in order to save time.
Just a note that this is also important because in real life, you don't know whether or not the insemination was successful until the first preg check (unless she already came into estrus). So even cows who will be confirmed pregnant will receive a GNRH shot 6 days before preg check when using the TAIbeforePD protocol.

2024-01-02 17:23 UTC, jadamchick commented
>        "1285": [
>        "simulation_day=131", **<-- 1285 - 1217 = 68. The code currently starts the TAI program on the day of VWP, but we should have started it on the day of tai_start_day. VWP should be used to determine whether the ai_day should be scheduled (before WVP, no ai_day should be scheduled).**
>        "Presynch period started: PreSynch",
>        "inject PGF"
>        ],

I agree with Yijing here - voluntary waiting period meaning needs to be consistent across all protocols as the day before which animals will not be bred. If it means something different in the TAI protocol (eg still means the day of the first hormone injection of presynch or ovsynch), that is confusing. 
For TAI protocol, voluntary waiting period should be the earliest day that AI is scheduled to occur.

2024-01-02 17:30 UTC, jadamchick commented
This is looking great! I haven't run it yet but after reviewing the code have a couple comments/clarifications: 

- See above about VWP meaning
- Clarification about TAI_program_start_day: Is this used for both TAI and ED-TAI protocols? The metadata says it is, but the metadata also says for VWP that "If TAI is chosen for the cow, it is days after parturition when the 1st hormonal injection is made in TAI programs." Which is used to indicate day of first injection for TAI protocol? 
- In the ideal world, TAI_program_start_day would refer to the day the first hormone injection is given for presynch (if specified) or ovsynch (if presynch not specified). However, for ED-TAI, I think it always refers to the first day of the Ovsynch protocol, not a presynch protocol? Can that be clarified in the metadata?
- Relatedly, I see that presynch is still not an option with ED-TAI, and assume it is beyond the scope of this refactor. In the future, would it be possible to do a presynch protocol with ED-TAI, and then allow estrus detection for a period of time before starting Ovsynch shots? (see "presynch" protocol on the reference sheet [here](https://www.dcrcouncil.org/wp-content/uploads/2019/04/Dairy-Cow-Protocol-Sheet-Updated-2018.pdf), with 10-14 days of estrus detection AI). @krb78 what are your thoughts?

I will update with more review after running it and looking at outputs. Thanks Loi!

2024-01-02 18:55 UTC, YijingGong commented
> I have 2 questions/thoughts.
> 
> 1. @YijingGong in your comments above, in scenario 2 where you are testing the resynch function. Do you just want RuFaS to write "TAIbeforePD" instead of "Ovsynch56" in the event log because technically, RuFaS is doing an Ovsynch56 protocol (and it should be doing this - so it is correct)? I'll defer to you and your expertise with this, because for me, I don't inherently see a problem with calling it "Ovsynch56" as that is the protocol we are executing, but if you wanted to be able to track resynchronization breedings differently than first breedings, I understand why you'd want your event log to read differently.
> 2. For the pilot farms because the farmers are reporting their average conception rate, we should be setting the conception rate parity decrease to 0.0 instead of 0.026. However, if RuFaS is being used to run research simulations or other scenarios, I think we will still want this parity conception rate decrease to exist. Does that make sense to you @KFosterReed and @YijingGong?

For Q1, you are right that Rufas is actually doing the Ovsynch56 protocol correctly. When I wrote the comments, I subconsciously connected the event log of "setting up resynch TAI protocol" with the options of the resynch protocols. 
Q2. Make sense to me.

2024-01-02 20:43 UTC, jadamchick requested changes
I ran this for one of the pilot testing herds; the necessary updates to animal.json and metadata.json were the only changes I made compared to earlier runs. 
This was using the ED protocol for both heifers and cows. 
I ran it for 5 years (1230-cow herd), and compared the results to compiled results from previous runs. 

With this new refactor, there were: 
- 2x as many Parity 1 animals (63% of the herd, v. 36% previously)
- Half as many dry cows (6% vs. 12% of the cow herd)
- 10x as many cows sold for low production in the last year (347 v. 31; 56% of total culls vs. 9%)

So I feel comfortable saying something is not working right with the ED protocol in this refactor. 

I looked at the logs and noticed a couple oddities: 
- when pregnancy loss occurs, it reschedules the next estrus to an earlier day in the simulation: 
![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/9f9cb1b8-a12b-4d90-b821-7c495a133df3)

- when insemination fails and the subsequent estrus is not detected, so the cow reaches pregnancy check and is checked "not pregnant", it reschedules estrus again (so is pushed out an extra ~20+ days) instead of maintaining the already-scheduled estrus: 
![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/99e360ae-cc3b-458c-8a98-934a29eb97da)

On a brighter note, I did not see any pgf injections given while the protocol was set to ED!

2024-01-02 20:48 UTC, jadamchick commented
> I have 2 questions/thoughts.
> 
>     1. @YijingGong in your comments above, in scenario 2 where you are testing the resynch function. Do you just want RuFaS to write "TAIbeforePD" instead of "Ovsynch56" in the event log because technically, RuFaS is doing an Ovsynch56 protocol (and it should be doing this - so it is correct)? I'll defer to you and your expertise with this, because for me, I don't inherently see a problem with calling it "Ovsynch56" as that is the protocol we are executing, but if you wanted to be able to track resynchronization breedings differently than first breedings, I understand why you'd want your event log to read differently.
> 
>     2. For the pilot farms because the farmers are reporting their average conception rate, we should be setting the conception rate parity decrease to 0.0 instead of 0.026. However, if RuFaS is being used to run research simulations or other scenarios, I think we will still want this parity conception rate decrease to exist. Does that make sense to you @KFosterReed and @YijingGong?

The second point caught my eye too -- because, I think, the parity decrease is hard-coded as a 0.05 penalty for each older parity. (So when looking through the logs of a herd where we inputted a 0.5 conception rate, there are many reports of "failed conception at rate 0.4" or "0.45").   If there is a way to control whether this penalty is implemented or not (eg so we can "turn it off" for pilot testing herds), that would be great. 
The 0.026 that Kaitlyn is referencing is the decrease applied for repeated breedings, I think?

2024-01-02 20:50 UTC, tomhuhh reviewed
Thanks Loi! I added a couple minor comments on the code/docstring.

2024-01-02 20:50 UTC, tomhuhh commented on RUFAS/routines/animal/animal_manager.py
>                  self._record_animal_events(self.cows)
'365' seems like a magic value to me. Should we add it to the constant list?

2024-01-02 20:50 UTC, tomhuhh commented on RUFAS/routines/animal/life_cycle/heiferII.py
> +        1. The estrus detection rate and conception rate are different.
'The estrus detection rates and conceptions rates are different. '

2024-01-03 16:53 UTC, jadamchick commented
This morning I ran this code with the same herd as above, using the TAI and then ED-TAI protocols. 

- TAI looked like it performed well. Outputs were similar to what I saw previously (without the refactor). Presynch shots consistently began on the day I specified as "voluntary waiting period" (see earlier comments about confusion around this name for this input). 

- ED-TAI is confusing. The outputs were poor (52% L1, high number of culls for low production, etc.). When I looked at the event logs, it appears that something is funky about when the first GnRH shot is occurring: a) it varies across a range of ~15 days, and b) it is later than either the "TAI program start day" or the "Voluntary waiting period" inputs. It also seems to always coordinate with a scheduled estrus (e.g., is it waiting for a scheduled estrus day to begin her first Ovsynch shot?)

For more detail, my inputs for ED-TAI run were: 
- ED-TAI
- presynch: Double Ovsynch (assuming this would be ignored, and it appears that it was in fact ignored)
- sub-protocol: Ovsynch 56
- program start day: 64 (assumed this would be the day of the first Ovsynch shot)
- voluntary waiting period: 74 (since this herd does first breeding entirely on TAI, then rebreeding on heat detection)

Results from several cows scrolled to at random in the event log: 
![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/6cb08169-b7a1-47da-a20c-b805cfdb0417)


Let me know if you have any questions, I'm happy to discuss any of this if it would be easier to talk through!

2024-01-16 19:48 UTC, ltp23 commented
Hi everyone, I have made some logic changes based on the design [diagrams](https://whimsical.com/cow-repro-protocols-KCGFZkgpcTz8gCh4GtEWDc)  and the feedback so far. Some additional changes. which I can revert or modify further, are:

- I added two true/false fields to control whether to decrease conception rate or not: `decrease_conception_rate_in_rebreeding` (I keep track of how many times the cow has entered the open state and multiply it some user-defined, hard-coded value), and `decrease_conception_rate_by_parity` (based on number of calves).
- Input parameter name changes
```
"cows": {
"estrus_detection_rate": 0.65,
"estrus_conception_rate": 0.6,
"presynch_program": "Double OvSynch",
"presynch_program_start_day": 50,
"ovsynch_program": "OvSynch 56",
"ovsynch_program_start_day": 66,
"ovsynch_program_conception_rate": 0.7,
"resynch_program": "TAIbeforePD"
}
```
If both presynch and ovsynch programs are used in TAI protocol, the correct way to set the ovsynch program start day would be on the last day of the presynch program or later. But if the ovsynch program start day is set before the end of the presynch program, then still, the ovsynch program can't start until the last day of presynch.  

- I added a list of possible repro states that a cow can be in based on what I have gathered so far. Some are more aligned with real-world scenarios than others. Typically, I would expect the cow to be in only one of those states at any point. The main use of this whole design is so that we can route to different functions depending on the current repro state. 
  - `NONE`: the empty state that acts as the starting state, or a useful intermediate state while the cow is transitioning between different states.
  - `WAITING_FULL_ED_CYCLE`: The typical state when we do estrus detection.
  - `WAITING_SHORT_ED_CYCLE`: This only applies when we choose the `PGFatPD` resynch method, in which the cow waits a maximum of 7 days for estrus. 
  - `WAITING_ED_DAILY`: This is used only in the period between `program_start_day` and `tai_program_start_day` when ED-TAI protocol is selected.
  - `IN_PRESYNCH`: Used in the duration of the presynch program.
  - `HAS_DONE_PRESYNCH`: After the cow has gone through a presynch program.
  - `IN_OVSYNCH`: When an ovsynch program is used. This can happen in both TAI-only and ED-TAI protocols.
  - `ESTRUS_DETECTED`: A very brief state in which we mark an estrus has been detected and then the following day an AI will be performed.
  - `AFTER_AI`: As the name suggests, after an AI has been performed, the cow enters this state. With a successful conception, she will enter the pregnant state.
  - `PREGNANT`: A cow enters or stays in this state when she is successfully conceived or when she passes a pregnancy check. If she fails a pregnancy check, she will exit this state.   
- For simplicity, in PGFatPD, all failed pregnancy checks will lead to a PGF injection, followed by a short estrus cycle detection, which is then followed by a TAI program if estrus not detected.

2024-01-16 19:50 UTC, ltp23 commented
One thing I haven't figured out yet is why the number of cows with parity 3 or more just drops off after a while. 

![default_scenario_herd-composition-16-Jan-2024_Tue_11-35-12](https://github.com/RuminantFarmSystems/MASM/assets/98855117/5812cde2-8d20-411b-ade7-4a683b57cb90)

![default_scenario_cow-population-by-parity-16-Jan-2024_Tue_11-35-12](https://github.com/RuminantFarmSystems/MASM/assets/98855117/aee20b80-dc3b-46fa-a37e-3febf3890721)

2024-01-16 20:24 UTC, ltp23 commented on RUFAS/routines/animal/animal_manager.py
>                  self._record_animal_events(self.cows)
Right, Haowen. This is definitely temporary. I just wanted to log the animal events for cows at a regular interval. I think what I will do before merging is to call it once at the end of the simulation.

2024-01-16 21:29 UTC, ltp23 commented
> With this new refactor, there were:
> 
> * 2x as many Parity 1 animals (63% of the herd, v. 36% previously)
> * Half as many dry cows (6% vs. 12% of the cow herd)
> * 10x as many cows sold for low production in the last year (347 v. 31; 56% of total culls vs. 9%)


Hi Julie, I still haven't been able to resolve the strange results for ED-only protocol. Even with the latest updates, the patterns you observed still exist.


> * when insemination fails and the subsequent estrus is not detected, so the cow reaches pregnancy check and is checked "not pregnant", it reschedules estrus again (so is pushed out an extra ~20+ days) instead of maintaining the already-scheduled estrus:

I can try to fix this one so that we don't reschedule a new estrus day and continue with the existing schedule. This makes me think that by extending the next estrus day, the cow may have gotten culled because of not getting pregnant within the breeding stage and having low milk production.

Update: I have updated it to not scheduling a new estrus day.

2024-01-16 21:31 UTC, ltp23 commented
> Relatedly, I see that presynch is still not an option with ED-TAI, and assume it is beyond the scope of this refactor. In the future, would it be possible to do a presynch protocol with ED-TAI, and then allow estrus detection for a period of time before starting Ovsynch shots?

This is doable and I can pick up on this later.

2024-01-19 06:51 UTC, ltp23 commented
Hi Haowen (@tomhuhh), with the latest changes and using the parameters you tried, I got the following

> * TAI conception rate to 55%, DNB to 250 days, & estrus detection rate for cows to 0.9
> * Low MY cut-off - 30 kg
> * Also, I had to run longer for the herd structure to stabilize.

`cow_repro_method`: ED-TAI
`do_not_breed_time`: 250
`estrus_detection_rate`: 0.9
`ovsynch_program_conception_rate`: 0.7
`resynch_program`: TAIbeforePD
![default_scenario_cow-population-by-parity-18-Jan-2024_Thu_22-41-28](https://github.com/RuminantFarmSystems/MASM/assets/98855117/ee5a0c60-4c0a-432a-9f4c-e149c9ada050)
![default_scenario_culling-cow-stats-18-Jan-2024_Thu_22-41-28](https://github.com/RuminantFarmSystems/MASM/assets/98855117/fc52160d-e43c-46fb-b52e-33bac8b07d4d)
![default_scenario_herd-composition-18-Jan-2024_Thu_22-41-28](https://github.com/RuminantFarmSystems/MASM/assets/98855117/d67d559f-d58c-4dea-8de5-bd992e5d1f2e)

2024-01-23 15:33 UTC, jadamchick commented
Thanks for all of the great + persistent work on this Loi! 
I ran several different combo's of repro programs and these are my observations: 

- ED: looks good! no red flags in the herd dynamics or the animal events
- TAI: also looks good! I would like to try more combinations of presynch and resynch programs. When I ran PresynchOvsynch paired with TAIafterPD, all seems to run smoothly. 
- **ED-TAI: a few issues yet....** 

1. It seems as though every single cow comes into estrus + is detected/bred for her first breeding (eg no one makes it to Ovsynch). I was looking at a herd with VWP=60, Ovsynch_start_day = 70, and estrus_detection = 0.6. So I would expect < 50% of cows to come into estrus during that 10-d window (10/21=0.48). And I would expect 40% of those who do come into estrus, not to be detected. That leaves roughly 70% of cows to proceed to Ovsynch. But when I looked through the events, I didn't see a single cow go into Ovsynch for her first AI event (they were only bred on TAI through resynch). 

2. Something funky is happening with animals who enter the herd during the time between calving ("new birth") and AI. They don't have any repro events, until DNB. (see screen shot for example). 
 
![image](https://github.com/RuminantFarmSystems/MASM/assets/146877580/71436b5a-ff48-41a6-9e9c-71ae2d4bbbee)



Lastly, I think there are a few metadata updates that could make things more clear for inputs: 
a- VWP: update the description to match the updated meaning, and include "N/A" option (to use for TAI protocol)
b- estrus_detection_rate and estrus_conception_rate: properties describes that these values are only relevant for ED programs. Is that true? 
c- presynch_program_start_day and ovsynch_program_start_day: it would be nice to have the option of "N/A" for when these are not in use 


Thanks Loi!! Let me know if you have any questions & we'll keep working through this together :)

2024-01-23 15:52 UTC, KFosterReed commented
Glad to see there is progress on this front! One comment in response to Julie's point 2 above is that other than during initialization, there should not be cows entering the herd at this time period (between calving and reproduction). My guess it is a misalignment between the cows in the herd database and the desired simulation. 

Two thoughts for fixing this are 1) look at the methods for herd initialization and modify something related to repro, 2) add an issue about this and ignore for now as it will sort it self out by the end of the simulation.  

@jadamchick, one workaround thought for you would be to initialize the herd when running the simulations (last time I checked it was much much quicker) in which case the repro methods will align and the ideal outcome is that these gaps in achieving pregnancy won't happen

2024-01-23 22:59 UTC, ltp23 commented
> 1. It seems as though every single cow comes into estrus + is detected/bred for her first breeding (eg no one makes it to Ovsynch). I was looking at a herd with VWP=60, Ovsynch_start_day = 70, and estrus_detection = 0.6. So I would expect < 50% of cows to come into estrus during that 10-d window (10/21=0.48). And I would expect 40% of those who do come into estrus, not to be detected. That leaves roughly 70% of cows to proceed to Ovsynch. But when I looked through the events, I didn't see a single cow go into Ovsynch for her first AI event (they were only bred on TAI through resynch).

Hi Julie, I can answer the first point first. We might have glossed over this point. Currently, we do estrus detection **daily** during the period between VWP and OvSynch Start Day. This means it almost guarantees we will detect estrus the longer the interval is and the more often we check it. An alternative is to designate only one or two estrus days (doing some calculations) in this interval and detect estrus. This will likely lead to what you expect. Please let me know if you want this alternative.

2024-01-23 23:04 UTC, ltp23 commented
> a- VWP: update the description to match the updated meaning, and include "N/A" option (to use for TAI protocol)
> b- estrus_detection_rate and estrus_conception_rate: properties describe that these values are only relevant for ED programs. Is that true?
> c- presynch_program_start_day and ovsynch_program_start_day: it would be nice to have the option of "N/A" for when these are not in use

I can make updates to these suggestions.

2024-01-23 23:13 UTC, jadamchick commented
Hi Loi! The estrus detection should be whatever the farm input is for % of estrus events that are detected and lead to an AI event. Happy to chat more tomorrow if you have more questions on that. Thanks!

2024-01-24 10:54 UTC, krb78 commented
Hi Loi!

The way you currently have estrus being detected every day is correct. I think Julie is commenting that the % of cows found in estrus during a 10 day window seemed off given the length of the estrus cycle is 21 days with a standard deviation of 6.

Kaitlyn Briggs, DVM, MBA
C: 607.386.0040

If you receive an email from me outside of your own working hours, please do not feel pressure to respond outside of your own work schedule.
________________________________
From: jadamchick ***@***.***>
Sent: Tuesday, January 23, 2024 6:13:40 PM
To: RuminantFarmSystems/MASM ***@***.***>
Cc: Briggs, Kaitlyn ***@***.***>; Mention ***@***.***>
Subject: Re: [RuminantFarmSystems/MASM] Cow repro refactor (PR #1055)


 CAUTION: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender and know the content is safe.

Hi Loi! The estrus detection should be whatever the farm input is for % of estrus events that are detected and lead to an AI event. Happy to chat more tomorrow if you have more questions on that. Thanks!

—
Reply to this email directly, view it on GitHub<https://github.com/RuminantFarmSystems/MASM/pull/1055#issuecomment-1907073121>, or unsubscribe<https://github.com/notifications/unsubscribe-auth/A7S3V4NCQLFHW6TPRQQCB43YQA72JAVCNFSM6AAAAABAW5GOL6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSMBXGA3TGMJSGE>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

2024-01-24 13:56 UTC, jadamchick commented
> Glad to see there is progress on this front! One comment in response to Julie's point 2 above is that other than during initialization, there should not be cows entering the herd at this time period (between calving and reproduction). My guess it is a misalignment between the cows in the herd database and the desired simulation.
> 
> Two thoughts for fixing this are 1) look at the methods for herd initialization and modify something related to repro, 2) add an issue about this and ignore for now as it will sort it self out by the end of the simulation.
> 
> @jadamchick, one workaround thought for you would be to initialize the herd when running the simulations (last time I checked it was much much quicker) in which case the repro methods will align and the ideal outcome is that these gaps in achieving pregnancy won't happen

Thanks @KFosterReed -- I wasn't sure how impactful this is/isn't. If we are running a herd for 4 years and only looking at the last year, then is it safe to assume that this subset of animals will no longer be relevant (since, as I understand it, they all enter on simulation day 1)? 
I will create an issue about this to flag it as something to revisit but not urgently needed during this refactor. 

Issue # 1157 created here: https://github.com/RuminantFarmSystems/MASM/issues/1157

2024-01-24 14:20 UTC, KFosterReed commented on RUFAS/routines/animal/life_cycle/cow.py
>          if not self.do_not_breed:
I am just reading through the code a bit to see if I can find any logic that might not make sense and it seems like this will start repro programs for cows that haven't yet calved? I ran it with a stop here and at least for cows entering the herd, the execute_ed_tai_protocol() function is being called before they have given birth

2024-01-24 21:59 UTC, jadamchick commented on input/metadata/default_metadata.json
> +              "description": "Voluntary Waiting Period (days) -- If 'TAI' (Timed Artificial Insemination) is chosen for cows, it is the number of days after parturition when the first hormonal inject
This should say something like: 
        When the cow's days in milk has reached this day, monitoring for estrus will begin. Used only in the ED and ED-TAI protocols. 

What value should be given when using TAI protocol? 0?

2024-01-24 22:01 UTC, jadamchick commented on input/metadata/default_metadata.json
> +                "description": "The percentage of in-heat animals that would be detected in the ED (Estrus Detection) programs (default is 0.6)",
could add something like: 
"The percentage of in-heat animals that would be detected in the ED (Estrus Detection) programs, including during the estrus detection portion of ED-TAI programs (default is 0.6)"

2024-01-24 22:03 UTC, jadamchick commented on input/metadata/default_metadata.json
> +                "description": "The percentage of inseminated animals that would be concepted in the ED (Estrus Detection) program (default is 0.6)",
same as above (include reference to ED-TAI). 
and maybe add something like "Conception rate for TAI protocols is specified under "Ovsynch_program_conception_rate" "

2024-01-24 22:05 UTC, jadamchick commented on input/metadata/default_metadata.json
> +                "description": "OvSynch program start day is the day of the first GnRH injection in an OvSynch program. It is used in both TAI and ED-TAI repro protocols.",
Add more description to describe how this works with relation to the presynch program (what you showed me today from the notes in the code seemed really helpful)

2024-01-26 18:15 UTC, jadamchick approved these changes
I approve!! What a work of perseverance, Loi :) 

TAI: I ran several farms with varying presynch, ovsynch, and resynch combinations for TAI and VWP=0. Everything seems to work as expected (including that OvSynch will not start until after Presynch is complete, even if the start day is specified as earlier). I noted that if PGFatPD is chosen for the resynch protocol, it will institute estrus detection, so it is important to have values filled in for ED detection + conception in that case.

ED-TAI: I ran several combinations of VWP, Ovsynch start day, and resynch protocols, and all worked as expected. Even when VWP was later than OvSynch start day, it appropriately skipped estrus detection before the first TAI and then started detecting after the first AI event occurred. 

ED: no hiccups noticed. 

Other eyes would be valuable at this point, since Loi has spent a lot of time addressing my observations and I'm sure I have blind spots that may have slipped past!  That said, I feel quite confident with what is here. Great work all. 

(I did make a couple suggested improvements to metadata for clarity on the TAI - PGFatPD situation above, but not dealbreakers).

2024-01-26 18:15 UTC, jadamchick commented on input/metadata/default_metadata.json
>                "estrus_conception_rate": {
Can we rename "estrus_conception_rate" to something like "ED_conception_rate" to make it clear that this is the conception rate used for estrus detection?

2024-01-26 18:15 UTC, jadamchick commented on input/metadata/default_metadata.json
> +                "description": "Resynch program for cow before/at/after first pregnancy check day in the TAI and ED-TAI repro protocols. When the ED protocol is used, this value will be ignored, and
Can we please add one statement like: "If PGFatPD is chosen, the values for estrus detection and conception to that detected estrus following PGF are determined by "estrus_detection_rate" and "ED_conception_rate" (even for TAI protocol).

2024-01-26 22:15 UTC, krb78 approved these changes
Woof! Amazing job, @ltp23 🥳 🕺 💃 Not that I didn't believe Julie, but I also ran a half dozen iterations (real ones provided by Blake) and weird fake ones to see if I could break it haha. It seems to work well! Great job! You deserve a full week of rest after this project! Who knew cow reproduction was so complicated?! 😆  

I just had 2 quick comments on wording otherwise!

2024-01-26 22:15 UTC, krb78 commented on RUFAS/routines/animal/animal_manager.py
> +                            animal_constants.LOW_PROD_CULL
I just want to say that I'm happy we've added this 😃 some of the feedback we got from farms as they filled out the pilot testing paperwork was "where do we put these low production culls?" and I always had to explain it was accounted for, but it'll be helpful to have this as an OM variable :)

2024-01-26 22:15 UTC, krb78 commented on input/metadata/ARL_metadata.json
> +              "description": "Voluntary Waiting Period (days) -- When the cow's days in milk has reached this day, monitoring for estrus will begin. Used only in the ED and ED-TAI protocols. When TAI
can we say "monitoring for estrus and subsequent breeding if found, will begin"? Because we were sort of monitoring before but we don't do anything other than say "before VWP, wait for next estrus" if she comes into estrus before the VWP.

2024-01-26 22:15 UTC, krb78 commented on input/metadata/ARL_metadata.json
> +                "description": "When set properly, OvSynch program start day is the day of the first GnRH injection in an OvSynch program. When the OvSynch program follows a presynch program, the sta
Wait, Loi, isn't ovsynch_program_start_day used in ED-TAI? Say we set VWP=50 and ovsynch_program_start_day to 70, that works and whatever cows we don't find in estrus between 50 and 70 days get started on an ovsynch program. I just tested this, so I know this is true and I'm hoping the language here is just a typo 😅

2024-01-29 00:17 UTC, YijingGong approved these changes
LGTM! Really good job Loi! One minor thing: I found the event log is empty when I put "start_date": "2009:244","end_date": "2010:264", but if I put a longer time such as 3 years or 5 years, I can see the animal events. 

I've tested:
1) cow ED:
Glad that this works:  "cows": {
					"estrus_detection_rate": 0.65,
					"ED_conception_rate": 0.6,
					"presynch_program": "N/A",
					"presynch_program_start_day": 0,
          			"ovsynch_program": "N/A",
					"ovsynch_program_start_day": 0,
					"ovsynch_program_conception_rate": 0,
          			"resynch_program": "N/A"
				}
2) TAI: zero estrus happening when resynch is TAIafterPD or TAIbeforePD
3) ED-TAI works well with VWP =50, presynch_start_day and ovsynch_start_day varied

2024-01-30 09:52 UTC, ltp23 commented
> I found the event log is empty when I put "start_date": "2009:244","end_date": "2010:264", but if I put a longer time such as 3 years or 5 years, I can see the animal events.

Thanks Yijing, before merging, I will adjust to only output events on the last day of the simulation.

2024-01-30 10:04 UTC, ltp23 commented on RUFAS/routines/animal/animal_manager.py
> +                            animal_constants.LOW_PROD_CULL
During debugging, a high count of culled cows due to low milk production was a sign of something going wrong in the rebreeding.

2024-01-30 10:15 UTC, ltp23 commented on input/metadata/ARL_metadata.json
> +                "description": "When set properly, OvSynch program start day is the day of the first GnRH injection in an OvSynch program. When the OvSynch program follows a presynch program, the sta
Good catch, Kaitlyn. Yes, this value is used in both TAI and ED-TAI.

2024-01-30 10:23 UTC, merged