Purchased feed emissions footprint report
RuminantFarmSystems/RuFaS pull request #1057
Opened 2023-12-15 22:54 UTC by Isgotkowitz

This PR introduces the ability to calculate the emissions associated with purchased feed that is fed to animals simulated by RuFaS. It does this through of the `FeedEmissionsManager`, which is contained within the `AnimalManager`, and utilizes a CSV input that contains a mapping of emissions (kg) per feed dry matter (kg).

At the beginning of the simulation, a Feed Emissions Manager is initialized by the Animal Manager. When it is initialized, it:
- Pulls location information from a field input file.
- Then gets the FIPS (county) code associated with the location via the FCC's API for getting the county FIPS code by lat/long.
- Builds a mapping between RuFaS feed IDs and the emissions associated with each.

Everyday, when the amounts of feed are reported per pen, the amounts are passed to a reporting method that calculated the emissions per feed per pen. To get the feed emissions, use the filter:

```AnimalModuleReporter.report_daily_feed_emissions.pen_.*```

I have added the feed emissions data to the `input/data/EEE` directory, and wrote a new properties section in the metadata.

### _Notes_
- If the is no lat/long provided to the simulation, the location defaults to Madison, WI.
- **Updated** The FCC API fails a lot (~50% of the time with a 502 Bad Gateway error). `FeedEmissionsManager` requests the county code three times, and if it does not get an ok response it adds an error to the OutputManager and the county code defaults to 55025 (Dane County, WI). **Update** now it is working super well, not sure what was going on with it over the weekend.
- If a feed is not in the feed emissions data a Warning is raised to the Output Manager.
- It is assumed that feed emissions data is all in kg emissions / kg dry matter feed.

2023-12-18 16:25 UTC, PooyaHekmati requested changes
The PR is on the right track but there are some changes needed before it can be merged onto main, even for a quick implementation. 
If the API is unreliable, since we already know the location of the pilot farms, can we plugin the county code into input files instead of making the API call at runtime? There is still value in having the automated API calls for scenarios other than the pilot farms, but since `Explicit is better than implicit` maybe we want to explore that avenue.
Also, until we fix the metadata structure, a change to `properties` mus be applied to all metadata files.

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/animal_module_reporter.py
> +            "function": "report_daily_feed_emissions",
avoid hardcoded values

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/animal_module_reporter.py
> +            f"ration_daily_feed_emissions_totals_for_pen_{pen_id}_{pen_animal_name}",
avoid formatting the data that is sent to downstream systems, unless they expect you to do so.
```suggestion
            f"pen_{pen_id}_animal_{pen_animal_name}_feed_emissions",
```
We don't have subtotal or weekly or monthly, so no need to specify. If clarity is needed, you can add them to `info_map`.

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +class FeedEmissionsManager:
This class seems to _estimate_ or _calculate_ the emissions that are caused by the purchased feed, it doesn't _manage_ it.
```suggestion
class PurchasedFeedEmissionsEstimator:

```

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +            self.county_code = 55025
avoid magic numbers

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        om.add_variable("FIPS_code", self.county_code, info_map)
maybe call it `FIPS_county_code`?

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        longitude = -89.401
avoid magic numbers

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +            om.add_warning(warning_name, warning_message, info_map)
```suggestion
            om.add_warning("Default Feed Emissions data", 
            "Could not obtain feed emissions geographic attributes, defaulting to Madison, WI.",
            info_map
            )

```

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        field_key = field_keys[0]
why index 0? What is its significance?

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        latitude = im.get_data(latitude_data_address)
```suggestion
        latitude = im.get_data(f"{field_keys[0]}.absolute_latitude")
```

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        longitude = im.get_data(longitude_data_address)
```suggestion
        longitude = im.get_data( f"{field_keys[0]}.longitude")

```

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        longitude = abs(longitude) * -1
what?? Why?!

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        for _ in range(3):
```suggestion
        retries = 3
        for _ in range(retries):
```
avoid magic numbers

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +            response = requests.get(endpoint, params=params)
add a log to OM before and after making the API call

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +                break
```suggestion
                return int(answer["County"]["FIPS"])

```

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        return county_code
simply log the API events when they happen, there is no reason to cache them and then process them. It's actually better to not make API calls in rapid succession when there is a failure, give the server some time to change its state; logging API events right after the API call makes a slight delay between API calls.

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +    def _setup_feed_emissions(self) -> dict[str, float]:
This function really needs docstrings to explain how it works

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +                    "Purchased Feed Emissions Warning",
```suggestion
                    "Missing Purchased Feed Emissions",

```

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +            elif feed_id not in self.feed_emissions.keys():
```suggestion
            if feed_id not in self.feed_emissions.keys():

```

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        return emissions_dict
```suggestion
            emissions_per_feed_id["feed_emissions_total"]+= emissions
            emissions_per_feed_id[feed_id] = emissions
        return emissions_per_feed_id

```

2023-12-18 16:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        emissions_dict = {}
```suggestion
        emissions_per_feed_id={"feed_emissions_total": 0}

```

2023-12-18 16:33 UTC, Isgotkowitz commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        longitude = abs(longitude) * -1
On the very off chance that someone tries to simulate a farm located at a longitude in the Eastern hemisphere.
This is not handled well though, at the very least an error should be raised.

2023-12-18 16:42 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_module_reporter.py
> +            "function": "report_daily_feed_emissions",
This is a little wonky because there is no `self`. I have changed it to
```python
        info_map = {
            "class": AnimalModuleReporter.__name__,
            "function": AnimalModuleReporter.report_daily_feed_emissions.__name__,
        }
```

2023-12-18 16:48 UTC, Isgotkowitz commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        field_key = field_keys[0]
Because there might be multiple field keys returned - one for each simulated field. The only thing that is known is at that point in the execution is that `field_keys` is not an empty list, so it just picks the first one.

2023-12-18 17:37 UTC, Isgotkowitz commented on RUFAS/routines/animal/feed_emissions_manager.py
> +    def _setup_feed_emissions(self) -> dict[str, float]:
Added a docstring, if it isn't clear I can hit it again.

2023-12-18 18:13 UTC, Isgotkowitz commented
Update: the API seems to be working perfectly now.

2023-12-18 18:18 UTC, Isgotkowitz commented
> If the API is unreliable, since we already know the location of the pilot farms, can we plugin the county code into input files instead of making the API call at runtime? There is still value in having the automated API calls for scenarios other than the pilot farms, but since `Explicit is better than implicit` maybe we want to explore that avenue. 

As noted in the update, the API seems to be working really well now. Not sure what was going on with it before. But I think passing in the county code is a good idea. I was thinking about this, and one hypothetical situation I thought of is a farmer whose farm is at the edge of a county, and feed is cheaper in the neighboring county, so that's where they buy their feed. In this case it would be good to allow them to directly set the county code.

> Also, until we fix the metadata structure, a change to `properties` mus be applied to all metadata files.

Done.

2023-12-18 19:17 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        field_key = field_keys[0]
I know, we have talked about it. But the one who will read and maintain the code won't. So the question is coming from that perspective rather mine.

2023-12-18 19:25 UTC, PooyaHekmati commented on RUFAS/routines/animal/feed_emissions_manager.py
> +        longitude = abs(longitude) * -1
So, if user plugins 42.4955242, 76.4205981 (lat, long) which belong to a village called Toru Aygyr in Kyrgyzstan, we convert it to 42.4955242, -76.4205981, which happens to be near Ithaca, fetch Tompkins County's ID, get the feed emissions according to Tompkin County and keep going without even letting user know about what just happened? That doesn't sound like a correct strategy.

2023-12-18 19:37 UTC, PooyaHekmati requested changes
The main reason that I am requesting changes is the line `longitude = abs(longitude) * -1`; that is a very dangerous move.

> As noted in the update, the API seems to be working really well now. Not sure what was going on with it before. But I think passing in the county code is a good idea. I was thinking about this, and one hypothetical situation I thought of is a farmer whose farm is at the edge of a county, and feed is cheaper in the neighboring county, so that's where they buy their feed. In this case it would be good to allow them to directly set the county code.

Right now the focus is on getting results for pilot farms. Evaluating different purchase strategies is something that we will explore in the future. wrt the API, there is no guarrantee that it won't become unresponsive again. So I think it is important to allow the possiblity of passing the county code directly and not mandating _either let me call the API or I force Madison WI to your results_.

2023-12-18 19:37 UTC, PooyaHekmati commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +        for attempt_count in range(attempts):
```suggestion
        max_attempts = 3
        for attempt_count in range(max_attempts):

```

2023-12-18 19:37 UTC, PooyaHekmati commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +                    f"Got successful response from the FCC's FIPS County Code API on attempt: {attempt_count}",
```suggestion
                    f"Got successful response from the FCC's FIPS County Code API on {attempt_count=}",

```

2023-12-18 19:37 UTC, PooyaHekmati commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +                f"FCC's FIPS County Code API attempt: {attempt_count} failed with status code: {response.status_code}.",
```suggestion
                f"FCC's FIPS County Code API {attempt_count=} failed with {response.status_code=}.",

```
you can shorten this f-strings like so.

2023-12-18 20:09 UTC, Isgotkowitz commented
> The main reason that I am requesting changes is the line `longitude = abs(longitude) * -1`; that is a very dangerous move.

@PooyaHekmati Ok, what is the best way to move forward then? A couple options that come to mind are:
- Adjust the metadata properties so that the longitude has to be in Western hemisphere.
- Assume the user passed a valid longitude and use it as is.

> Right now the focus is on getting results for pilot farms. Evaluating different purchase strategies is something that we will explore in the future. wrt the API, there is no guarrantee that it won't become unresponsive again. So I think it is important to allow the possiblity of passing the county code directly and not mandating _either let me call the API or I force Madison WI to your results_.

Would the config file be a good place to put the county code?

2023-12-18 22:39 UTC, Isgotkowitz commented
> > The main reason that I am requesting changes is the line `longitude = abs(longitude) * -1`; that is a very dangerous move.
> 
> @PooyaHekmati Ok, what is the best way to move forward then? A couple options that come to mind are:
> 
> * Adjust the metadata properties so that the longitude has to be in Western hemisphere.
> * Assume the user passed a valid longitude and use it as is.

Assume the longitude is valid, and make sure to check for null response from API.

> > Right now the focus is on getting results for pilot farms. Evaluating different purchase strategies is something that we will explore in the future. wrt the API, there is no guarrantee that it won't become unresponsive again. So I think it is important to allow the possiblity of passing the county code directly and not mandating _either let me call the API or I force Madison WI to your results_.
> 
> Would the config file be a good place to put the county code?

Yes.

2023-12-19 15:47 UTC, jadamchick reviewed
This is looking great! I had to add FIPS_county_code to the config file to get it to run, and looks like you just added that too.

- Eventually this CSV will contain all feeds in the feed library -- so we will need to add every feed individually to the metadata properties?
- Warnings look good for alerting when a feed is missing emissions data.
- I created an altered CSV (changed some values and added an additional feed) and used that easily; I had to add the new feed ID to the metadata properties in order for it to be utilized. Once I did that, it appropriately grouped those feed emissions in with the right pen's reporting and total.
- I'm sure you're already aware that we will eventually need to distinguish between which feeds are purchased and which are grown on-farm (identified in the input feed.json). For pilot farms right now, we are assuming all feeds are purchased. For the next iteration (when we incorporate crop & soil module), will need to be able to determine which are purchased to use the emissions factors from the CSV, and which are home grown (and calculate footprint using RuFaS). This works great for our scenario right now.
- I am able to use the report generator to slice and aggregate the feed emissions data. It is a little fiddly (need to specify each feed individually and make sure it is labeled in the title in order to know in the output which is which). Copying my example filter here FYI. It would be slick to be able to do this a little more smoothly, but this is functional for what we need.

```json
{
    "multiple":[
        {
            "name": "footprint by ingredient - 51 lact",
            "filters": [
                "AnimalModuleReporter.report_daily_feed_emissions.pen_3_animal_LAC_COW_feed_emissions"
            ],
            "variables": "51", 
            "slice_start": -365, 
            "vertical_aggregation": "sum"
        },
        {
            "name": "footprint by ingredient - 104 lact",
            "filters": [
                "AnimalModuleReporter.report_daily_feed_emissions.pen_3_animal_LAC_COW_feed_emissions"
            ],
            "variables": "104", 
            "slice_start": -365,
            "vertical_aggregation": "sum"
        },
        {
            "name": "footprint by ingredient - total lact",
            "filters": [
                "AnimalModuleReporter.report_daily_feed_emissions.pen_3_animal_LAC_COW_feed_emissions"
            ],
            "variables": "feed_emissions_total", 
            "slice_start": -365,
            "vertical_aggregation": "sum"
        }
    ]
} 
```

2023-12-19 16:07 UTC, Isgotkowitz commented
> * Eventually this CSV will contain all feeds in the feed library -- so we will need to add every feed individually to the metadata properties?

Yes, I think so. I have not worked extensively with the validation mechanism for tabular (CSV) data in the Input Manager, but I think it is both a requirement and a best practice to define properties for every column.

> * I'm sure you're already aware that we will eventually need to distinguish between which feeds are purchased and which are grown on-farm (identified in the input feed.json). For pilot farms right now, we are assuming all feeds are purchased. For the next iteration (when we incorporate crop & soil module), will need to be able to determine which are purchased to use the emissions factors from the CSV, and which are home grown (and calculate footprint using RuFaS). This works great for our scenario right now.

Yes. I am not sure how this will work, but at that point it may be good to move Purchased Feed Emissions Estimator closer to wherever feed is being "purchased".

2023-12-19 16:53 UTC, PooyaHekmati commented
> This is looking great! I had to add FIPS_county_code to the config file to get it to run, and looks like you just added that too. 
> 
> - Eventually this CSV will contain all feeds in the feed library -- so we will need to add every feed individually to the metadata properties? 

Yes, I know that is labor-intensive, we can/should improve it.

> - I'm sure you're already aware that we will eventually need to distinguish between which feeds are purchased and which are grown on-farm (identified in the input feed.json). For pilot farms right now, we are assuming all feeds are purchased. For the next iteration (when we incorporate crop & soil module), will need to be able to determine which are purchased to use the emissions factors from the CSV, and which are home grown (and calculate footprint using RuFaS). This works great for our scenario right now. 

Yes, that fits with the longer-term plan. Currently, there is a disconnect between the soil and crop module and the animal module. Once we finish implementing the feed storage module, that gap is bridged. Then we can/should move the purchasing feed logic from the animal module to the feed module. Quoting myself from a few days ago:
>_Just to have it on your radar, I am implementing a class called `FeedManager`. Right now it just does the inventory tracking and later on it will handle degradation as well (as we discussed). However, a longer term plan is to move purchasing feed logic to this class as well. The rationale is that the Animal module should be agnostic about the origin of the feeds. As far as Animal manager is concerned, the animals need to receive a certain amount of nutrition, where it comes from is a different question. This separation is a move toward SOLID principles and makes it possible/easier to experiment with different storage vs purchase strategies, incorporating econ and degradation._


> - I am able to use the report generator to slice and aggregate the feed emissions data. It is a little fiddly (need to specify each feed individually and make sure it is labeled in the title in order to know in the output which is which). Copying my example filter here FYI. It would be slick to be able to do this a little more smoothly, but this is functional for what we need.
> 
Yes, I added a comment to issue #899 to make sure this will ba taken care of as well.

2023-12-19 17:27 UTC, PooyaHekmati approved these changes
Just consider the comments before merging.
[![LGTM](https://lgtm.lol/p/811)](https://lgtm.lol/i/811)

2023-12-19 17:27 UTC, PooyaHekmati commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +            "Feed Emissions Estimator found invalid data.",
Knowing that county code is optional in the input data, would it be a warning when it is not provided? Maybe log suffices? Also, the missing data here is not invalid, right?

2023-12-19 17:27 UTC, PooyaHekmati commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +                "Using default FIPS county code",
I think we should mention the cause in the subject and talk about the effect/consequence in the body.

2023-12-19 17:27 UTC, PooyaHekmati commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +            )
I think an exception should be raised here so that the caller uses the default value.

2023-12-19 17:27 UTC, PooyaHekmati commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +        longitude = location[1]
these can be added to info_map

2023-12-19 17:27 UTC, PooyaHekmati commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +        endpoint = "https://geo.fcc.gov/api/census/block/find"
info_map

2023-12-19 18:12 UTC, Isgotkowitz commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +            "Feed Emissions Estimator found invalid data.",
> would it be a warning when it is not provided? Maybe log suffices?

Yes, good point.

> Also, the missing data here is not invalid, right?

Yes and no. A null FIPS code is never a valid FIPS code, but the way the metadata properties are set up it is not an unexpected case to have a `null` FIPS code in the Input Manager.

2023-12-19 18:20 UTC, Isgotkowitz commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +            )
Nice catch, that actually needs to be in there or it will crash.

2023-12-19 19:05 UTC, jadamchick approved these changes
Looks great! I'll keep playing with it with real pilot farms as we get them running and let you know if anything comes up. Thanks for getting this in place so quickly.

2023-12-19 19:37 UTC, PooyaHekmati commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +            "Feed Emissions Estimator found invalid data.",
> > Also, the missing data here is not invalid, right?
> 
> 
> Yes and no. A null FIPS code is never a valid FIPS code, but the way the metadata properties are set up it is not an unexpected case to have a null FIPS code in the Input Manager.
> 

`missing data is not invalid` doesn't mean it is valid. In order to make the statement that something is either valid or invalid, that thing has to exist first. When it doesn't, it is both valid and invalid at the same time and it is neither of them as well, we just don't know. Imagine you are hungry, I tell you why don't you eat something? You say the food that I have is rotten. This is an invalid scenario. Another possibility is when you say I don't have any food. In this case, you don't care the possibility of food poisoning when there is no food.

2023-12-20 17:21 UTC, merged