[6/n][Feed Storage] Implement receive_crop
RuminantFarmSystems/RuFaS pull request #1061
Opened 2023-12-19 16:08 UTC by PooyaHekmati

**IMPORTANT NOTE**: This PR actually modifies less than 300 lines of code, the numbers are inflated due to sphinx-build action, which I disabled after making this PR. Simply ignore the files that are the `docs` directory.
This PR implements `receive_crop`, ensuring that only acceptable crops can be stored in storage. The compatibility check is done via the following rules:

- Small grain goes to hay, grain, silage, and baleage
- Alfalfa goes to hay, silage, and balayage
- Grass goes to hay, silage, and balayage
- Corn goes to grain and silage
- Soy only goes to grain

While [the design doc](https://docs.google.com/document/d/1C86lch2dkYBERR-qLDmE7L7n1gYQjETrIKUyrQpWrPs/edit?usp=sharing) states these rules should be implemented in the `FeedManager` class, here I decided to leverage the existing inheritance structure for a cleaner implementation.

The PR also moves `CropCategory` and `CropType` to `enums.py` for better organization. And implements `stored_mass`.

2023-12-19 17:04 UTC, Isgotkowitz requested changes
Changes requested on docstring formatting. I am not sure exactly how docstrings for Enums should be formatted (the Numpy docstring guide does not provide any explicit guidance), but I think generally they should look a lot like regular class docstrings. Had some other comments about which will help make sure that the Crop module will line up with the Feed Storage module correctly.

2023-12-19 17:04 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/enums.py
> +        ALFALFA: Represents alfalfa crops.
```suggestion
    Attributes
    ----------
    SMALL_GRAIN : str
        Represents small grain crops.
    CORN : str
        Represents corn crops.
    SOY : str
        Represents soy crops.
    GRASS : str
        Represents grass crops.
    ALFALFA : str
        Represents alfalfa crops.
```

2023-12-19 17:04 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/enums.py
> +        MEADOW_FESCUE: Type of Grass.
```suggestion
    Attributes
    ----------
    WHEAT : str
        Type of Small Grain.
    RYE : str
        Type of Small Grain.
    OAT : str
        Type of Small Grain.
    RICE : str
        Type of Small Grain.
    HIGH_MOISTURE : str
        Type of Corn.
    SILAGE : str
        Type of Corn.
    WHOLE_PLANT : str
        Type of Corn.
    GRAIN : str
        Type of Corn or Soy.
    FORAGE : str
        Type of Soy.
    ALFALFA : str
        Type of Alfalfa.
    RYEGRASS : str
        Type of Grass.
    ORCHARDGRASS : str
        Type of Grass.
    FINE_FESCUE : str
        Type of Grass.
    TALL_FESCUE : str
        Type of Grass.
    MEADOW_FESCUE : str
        Type of Grass.
```

2023-12-19 17:04 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/enums.py
> +        FORAGE: Type of Soy.
If soy is harvested as a "forage", does it still get treated as a grain? I looked at the design doc on page 11, at the crop to storage mapping, and soy only has a mark for grain.

2023-12-19 17:04 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/baleage.py
> +        ]
Can you please add this to the attributes section?

2023-12-19 17:04 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/hay.py
> +        ]
Should soy be here? Somewhere in the discussion of setting of crop quality defaults, we came to the conclusion that soy should also be able to be harvested as hay, and there is currently a soy hay option for in the available crops. If this is a mistake we should remove the soy hay option from the Crop module.

2023-12-19 17:04 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/storage.py
> +                If adding the crop exceeds the storage's capacity.
```suggestion
        Raises
        ------
        NotImplementedError
            If the storage's acceptable crops is not populated.
        ValueError
            If the crop's category is not compatible with the storage.
        Exception
            If adding the crop exceeds the storage's capacity.
```

2023-12-19 17:06 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/enums.py
> +        FORAGE: Type of Soy.
That is a question for the SME @KevinP-B .

2023-12-19 17:07 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/baleage.py
> +        ]
It is already documented in the parent class.

2023-12-19 17:08 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/hay.py
> +        ]
That is a question for SME @KevinP-B .

2023-12-19 17:41 UTC, Isgotkowitz requested changes
Changes requested on the attributes section of the docstring of `CropCategory`. Also found some if conditions that could be broken down a bit, not sure how necessary those changes are though.

2023-12-19 17:41 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/storage.py
> +        if self.stored_mass + crop.fresh_mass > self.capacity:
```suggestion
        unacceptable_crop = crop.category not in self.acceptable_crops
        if unacceptable_crop:
            raise ValueError(
                f"Can't recieve the crop, the compatible crop categories are {self.acceptable_crops=},\
                    {crop.category} is not one of them."
            )
        capacity_exceeded = self.stored_mass + crop.fresh_mass > self.capacity
        if capacity_exceeded:
```
Missed these the first time through. Up to you if they are strictly necessary though.

2023-12-19 17:51 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/storage.py
> +        if self.stored_mass + crop.fresh_mass > self.capacity:
I have mentioned this in some other PRs before: we use documentary variables when understanding the statement is difficult. Here, the next line is explaining what is happening. Putting every single statement in variables is not a good practice.

2023-12-19 17:54 UTC, Isgotkowitz approved these changes
LG8TM, nice job Pooya.

2023-12-20 17:54 UTC, KevinP-B approved these changes
Efficient updates and ensuring crops match appropriate storage options elegantly

2023-12-20 22:10 UTC, merged