Separate and track manure nutrients by manure type
RuminantFarmSystems/RuFaS pull request #1071
Opened 2023-12-20 20:31 UTC by ew3361zh

PR to address issue #1043 to track manure nutrients by type within the manure module.

To address this the following changes were made:

### In manure_manager.py:
1. The `_add_manure_nutrients()` method which has the nutrients coming in from ManureTreatmentDailyOutput are now separated into liquid and solid ManureTypes and added to the manure_nutrient_manager separately.
2. The `daily_update()` method now has the nutrients sent to ManureModuleOutputManagerHelper by manure type.
3. ManureTreatmentTypes SLURRY_STORAGE_OUTDOOR and SLURRY_STORAGE_UNDERFLOOR were updated to use ManureType.LIQUID.

### In manure_nutrient_manager.py:
1. init method now creates a dictionary of ManureNutrients by type (just LIQUID and SOLID as instructed).
2. `values` property was updated to be the `get_values()` method which takes the manure_type as an arg and returns the ManureNutrients object of that type.
3. `add_nutrients()` method updated to add nutrients the same type of manure that the ManureNutrients arg is.
4. `evaluate_nutrients_request()` now takes into account the manure_type of the request.
5. `create_nutrient_request_results()` adds manure_type as an arg (sent from `evalute_nutrients_request).
6. `remove_nutrients()` now checks type of manure when removing results nutrients from ManureNutrients object.

### In manure_nutrients.py:
1. Adds manure_type as attribute for ManureNutrients object.
2. Adds check to ensure manure_type attribute is a valid ManureType.
3. Updates `dry_matter_fraction`, `__mul__`, `__sub__` methods to avoid doing math on the new manure_type attribute and ensure each is only doing said math on the same manure type ManureNutrient objects.

### In nutrient_request.py
1. manure_type added as attribute to NutrientRequest objects.
2. Code added to avoid doing math on the manure_type attribute and to ensure manure_type is a ManureType.

### Other changes
1. ManureType is added to field.py's `_execute_manure_application()` method where it requests nutrients from the manure module via a NutrientRequest object. When addressing #1044, this will be moved to the Field's manure_requests which I believe come from field input files.
2. "SLURRY" removed as manure_type option in manure_types.py.
3. "SEPARATED_SOLIDS_STORAGE" added as manure treatment type in manure_treatment_types.py (requested).
4. Unit testing updated/fixed.

2023-12-21 15:36 UTC, Isgotkowitz requested changes
Overall looks great Niko. Requested changes on the format of some docstrings and making code a little cleaner, after those are addressed it should be good to go.

2023-12-21 15:36 UTC, Isgotkowitz commented on RUFAS/routines/field/field/field.py
> +        # TODO add manure type into request
```suggestion
        # TODO add manure type into request - addressed by issue #1044 
```

2023-12-21 15:36 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_nutrients/manure_nutrients.py
> +                summed_attributes[f.name] = getattr(self, f.name) + getattr(other, f.name)
```suggestion
        summed_attributes = {
            f.name: getattr(self, f.name) + getattr(other, f.name) for f in fields(self) if f.name != "manure_type"
        }
```

2023-12-21 15:36 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_nutrients/manure_nutrients.py
> +                subtracted_attributes[f.name] = getattr(self, f.name) - getattr(other, f.name)
```suggestion
        subtracted_attributes = {
            f.name: getattr(self, f.name) - getattr(other, f.name) for f in fields(self) if f.name != "manure_type"
        }
```

2023-12-21 15:36 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_nutrients/nutrient_request.py
Please change this to Numpy style

2023-12-21 15:36 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_nutrients/nutrient_request.py
> +                    raise ValueError(f"Field {field.name} must be an instance of ManureType.")
```suggestion
            if field.name != "manure_type" and value < 0:
                raise ValueError(f"Field {field.name} must be non-negative.")
            if field.name == "manure_type" and not isinstance(value, ManureType):
                raise ValueError(f"Field {field.name} must be an instance of ManureType.")
```

2023-12-21 15:36 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_types.py
>      LIQUID: Represents liquid manure.
```suggestion
    Attributes
    ----------
    LIQUID : str
        Represents liquid manure.
    ...
```
This was how I suggested Pooya format the docstrings for Enums in the Feed Storage module - however, if the proper way to refer to elements of an Enum is "members", maybe it would be more appropriate to put:
```suggestion
    Members
    -------
    LIQUID : str
        Represents liquid manure.
    ...
```

2023-12-21 15:36 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_types.py
>      SOLID: Represents manure in solid form.
@KFosterReed is there a strict cutoff between liquid and solid manure in terms of dry matter fraction? For example, manure is only considered liquid if the dry matter fraction is 5% or less. If so, I think that would be a good detail to add to the documentation here.

2023-12-21 15:36 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_nutrients/manure_nutrients.py
> +
Should there be checks to throw some kind of error if you try to subtract more than what is currently held by `ManureNutrients`, or if you try to subtract a negative quantity. Or would it be more appropriate to have that happen at a higher/different level?

2023-12-21 15:36 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_nutrients/manure_nutrients.py
> +                multiplied_attributes[f.name] = getattr(self, f.name) * scalar
```suggestion
        multiplied_attributes = {
            f.name: getattr(self, f.name) * scalar for f in fields(self) if f.name != "manure_type"
        }
```

2023-12-21 15:55 UTC, ew3361zh commented on RUFAS/routines/manure/manure_nutrients/nutrient_request.py
I actually couldn't find specifics around numpy documenting multiple of the same type of error being raised by a single function. Do you have a reference?

When I asked chatgpt, it suggested:
"""
ValueError
    - If reason 1
    - If reason 2
    - Etc.
"""

I see you have it multiple places as:
"""
ValueError
    If reason 1
ValueError
    If reason 2
ValueError
    Etc.
"""

And Loi has (here: https://github.com/RuminantFarmSystems/MASM/blob/9c125dbdd207e8bc0831a26ae1617df287062ee2/RUFAS/routines/manure/gas_emissions/calculator.py#L364)
"""
        Raises
        ------
        ValueError
            If the input `hours` is not in the range [0, 24],
            If `min_temp` is greater than `max_temp`.
"""

2023-12-21 16:14 UTC, ew3361zh commented on RUFAS/routines/manure/manure_treatments/manure_types.py
>      LIQUID: Represents liquid manure.
I think your first way makes the most sense if we want to go one of these two routes. However, it looks like Numpy doesn't specify anything about how to write Enum class docstrings and in fact in their own repo don't have any Attributes or Members listed:

https://github.com/numpy/numpy/blob/84da5965e28e545cb84f8d3ab8bb2321db4ccd2e/numpy/f2py/symbolic.py#L36

class Language(Enum):
    """
    Used as Expr.tostring language argument.
    """
    Python = 0
    Fortran = 1
    C = 2

2023-12-21 16:26 UTC, ew3361zh commented on RUFAS/routines/manure/manure_nutrients/manure_nutrients.py
> +
That's a good idea, I can add that in. It does look like it's also caught in manure_nutrient_manager.py's `_remove_nutrients()` method.

2023-12-21 16:45 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_nutrients/nutrient_request.py
I don't have a reference, but I think Loi's style would be best to go with here - so 
```
Raises
------
ValueError
    Reason 1
    Reason 2
```

2023-12-21 16:49 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_types.py
>      LIQUID: Represents liquid manure.
Nice find, I did not look close enough at the NumPy repo. I think going the first route is best too (using "Attributes") - definitely better than not documenting the elements of an Enum at all.

2023-12-21 16:50 UTC, ew3361zh commented on RUFAS/routines/manure/manure_nutrients/nutrient_request.py
I can write up an issue to go through the code base to make all instances match this style if we agree on this.

2023-12-21 16:52 UTC, Isgotkowitz approved these changes

2023-12-22 16:22 UTC, KFosterReed commented on RUFAS/routines/manure/manure_treatments/manure_types.py
>      SOLID: Represents manure in solid form.
My understanding is that there are DM fractions that can be used for differentiating between solid and liquid but there is not consensus/standardizations among references. I would propose for now that we set a cut off at 15% DM

2023-12-22 18:13 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_types.py
>      SOLID: Represents manure in solid form.
Sounds good. In the `ManureApplication` module (in Crop and Soil) the cutoff for liquid manure is 15% or less DM, so that lines up nicely

2023-12-22 20:18 UTC, KFosterReed commented
This is looking really good! The solid manure management methods (CBPB and dry lots) are tracked in the ManureNutrients class separately from the liquid storage type. In methods with solid liquid separation the liquid fractions align with the liquid manures that are produced during separation.

The functionality that is missing is that even though there is a new Separated Solids Manure Treatment type, there is no manure being passed into that treatment type. My inclination is to make a separate issue for that and move forward with this PR. Question for @ew3361zh , since this is a stacked PR is the plan to merge with PR 1075? Thanks!

2023-12-22 20:56 UTC, ew3361zh commented
> This is looking really good! The solid manure management methods (CBPB and dry lots) are tracked in the ManureNutrients class separately from the liquid storage type. In methods with solid liquid separation the liquid fractions align with the liquid manures that are produced during separation.
> 
> The functionality that is missing is that even though there is a new Separated Solids Manure Treatment type, there is no manure being passed into that treatment type. My inclination is to make a separate issue for that and move forward with this PR. Question for @ew3361zh , since this is a stacked PR is the plan to merge with PR 1075? Thanks!

I think it makes sense to work on passing manure to that treatment type in a separate PR to keep this one as single-responsibility as possible if you're comfortable with that.

So 1075 has all the code from this PR up-to-date so when this one gets approved and merged in, it will be in much the same state as it is now - ready for review on its own terms.
As far as the protocol for merging I was thinking:
1. Get this PR approved.
2. Merge it into main.
3. Ensure 1075 has all the code from main.
4. Have PR 1075 reviewed.
5. Merge in PR 1075 to main.

Let me know if that sounds good!

2023-12-22 21:14 UTC, KFosterReed approved these changes
This accomplishes the manure tracking by type functionality as expected! Great work :)

2023-12-22 21:15 UTC, KFosterReed commented
> > This is looking really good! The solid manure management methods (CBPB and dry lots) are tracked in the ManureNutrients class separately from the liquid storage type. In methods with solid liquid separation the liquid fractions align with the liquid manures that are produced during separation.
> > The functionality that is missing is that even though there is a new Separated Solids Manure Treatment type, there is no manure being passed into that treatment type. My inclination is to make a separate issue for that and move forward with this PR. Question for @ew3361zh , since this is a stacked PR is the plan to merge with PR 1075? Thanks!
> 
> I think it makes sense to work on passing manure to that treatment type in a separate PR to keep this one as single-responsibility as possible if you're comfortable with that.
> 
> So 1075 has all the code from this PR up-to-date so when this one gets approved and merged in, it will be in much the same state as it is now - ready for review on its own terms. As far as the protocol for merging I was thinking:
> 
> 1. Get this PR approved.
> 2. Merge it into main.
> 3. Ensure 1075 has all the code from main.
> 4. Have PR 1075 reviewed.
> 5. Merge in PR 1075 to main.
> 
> Let me know if that sounds good!

Sounds good! I approved this PR then and will make an issue for adding the separated solids to the separated solids treatment

2023-12-22 21:20 UTC, merged