Implement FeedManager and recieve_crop
RuminantFarmSystems/RuFaS pull request #1082
Opened 2024-01-03 07:01 UTC by PooyaHekmati

This PR defines the structure of the `FeedManager` and implements its `recieve_crop` method.
[design doc](https://docs.google.com/document/d/1C86lch2dkYBERR-qLDmE7L7n1gYQjETrIKUyrQpWrPs/edit?usp=sharing)
It also enhances some existing docstrings.
Moves `sample_crop_data` to its own file to make it reusable and remove duplication.

2024-01-05 22:29 UTC, Isgotkowitz requested changes
Requesting changes on the way that `sample_crop_data` is implemented and shared between modules. I am all for increasing reusability and decreasing duplication, but I don't think it is worth the tradeoff of adding a bunch of `noqa`'s in this case. Everything else is minor comments.

2024-01-05 22:29 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/enums.py
> +        Represents a type of type of Small Grain.
```suggestion
        Represents a type of Small Grain.
```
Same comment for other attributes in this docstring.

2024-01-05 22:29 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/feed_manager.py
> +from .sileage import Sileage, Bag, Bunker, Pile
Is this the preferred way of writing import statements, i.e. `.baleage` instead of `RUFAS.routines.feed_storage.baleage`?

2024-01-05 22:29 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/feed_manager.py
> +    def process_degradations(self):
```suggestion
    def process_degradations(self) -> None:
```

2024-01-05 22:29 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/feed_manager.py
> +        self.active_storages: Dict[StorageType, Storage] = {}
There is a mismatch between type annotations here. I understand why it would be `List[Storage]`, but I do not understand why it would be a `Dict[StorageType, Storage]`.

2024-01-06 13:56 UTC, JoeWaddell approved these changes
Only minor comments here (and my suggestion to add units to docstrings might be premature) - this is a great start. Exciting to see this come together. @Isgotkowitz brought up great questions.

2024-01-06 13:56 UTC, JoeWaddell commented on RUFAS/routines/feed_storage/feed_manager.py
> +    def query_available_feeds(
Great name for this method: will be clear in the ration formulation process.

2024-01-06 13:56 UTC, JoeWaddell commented on RUFAS/routines/feed_storage/feed_manager.py
> +            The amount of feed to distribute.
```suggestion
            The amount of feed to distribute (kg).
```

2024-01-06 13:56 UTC, JoeWaddell commented on RUFAS/routines/feed_storage/feed_manager.py
> +            The amount of available feed, either as a total or for a specific crop type.
```suggestion
            The amount of available feed (kg), either as a total or for a specific crop type.
```

2024-01-06 13:56 UTC, JoeWaddell commented on RUFAS/routines/feed_storage/feed_manager.py
> +        """The purchase feed logic is currently in the Animal Module. We will move it to here."""
Excellent: looking forward to helping with that move!

2024-01-06 13:56 UTC, JoeWaddell commented on RUFAS/routines/feed_storage/feed_manager.py
> +            The actual amount of feed distributed.
```suggestion
            The actual amount of feed distributed (kg).
```

2024-01-08 18:34 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/feed_manager.py
> +from .sileage import Sileage, Bag, Bunker, Pile
Yes, always (is not limited to Python) relative path takes priority over the absolute path. The reason is that with relative paths, the module or package is bundled, if we decide to rename `routines`, as an example, relative path is agnostic about it.

2024-01-08 18:38 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/feed_manager.py
> +        self.active_storages: Dict[StorageType, Storage] = {}
`Dict[StorageType, Storage]` is correct, it maps `StorageType(Enum)` to instances of `Storage`.

2024-01-08 18:41 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/feed_manager.py
> +            The amount of feed to distribute.
I understand why you would want to have the unit here; however, this class is agnostic about the units. We cannot guarantee that the amount received from the caller (S&C) is indeed in kg. I am concerned that being explicit about the unit here, makes it harder to debug, should something go wrong.

2024-01-08 18:44 UTC, PooyaHekmati commented
> Requesting changes on the way that `sample_crop_data` is implemented and shared between modules. I am all for increasing reusability and decreasing duplication, but I don't think it is worth the tradeoff of adding a bunch of `noqa`'s in this case. Everything else is minor comments.

I disagree, duplication is known to be the root of many, if not most, problems in software. But I removed the noqas.

2024-01-08 19:31 UTC, Isgotkowitz approved these changes
Thank you for addressing requested changes. I have a follow up question about the typing of `active_storages` (in the comment/response above) and I also would like to get a better understanding of how units will work in this class, but otherwise looks good.

2024-01-08 19:31 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/feed_manager.py
> +            The amount of feed to distribute.
> this class is agnostic about the units. We cannot guarantee that the amount received from the caller (S&C) is indeed in kg. I am concerned that being explicit about the unit here, makes it harder to debug, should something go wrong.

Can you please expand on how this class can be agnostic to units? I am not understanding how labeling units in different methods would make things harder to debug.

2024-01-08 19:31 UTC, Isgotkowitz commented on tests/test_feed_storage_module/test_feed_manager.py
> +def feed_manager():
```suggestion
def feed_manager() -> FeedManager:
```

2024-01-08 19:31 UTC, Isgotkowitz commented on tests/test_feed_storage_module/test_feed_manager.py
> +def test_receive_crop_success(feed_manager: FeedManager, harvested_crop: HarvestedCrop):
```suggestion
def test_receive_crop_success(feed_manager: FeedManager, harvested_crop: HarvestedCrop) -> None:
```

2024-01-08 19:31 UTC, Isgotkowitz commented on tests/test_feed_storage_module/test_feed_manager.py
> +):
```suggestion
) -> None:
```

2024-01-08 19:31 UTC, Isgotkowitz commented on tests/test_feed_storage_module/test_feed_manager.py
> +def test_receive_crop_error(feed_manager: FeedManager, harvested_crop: HarvestedCrop):
```suggestion
def test_receive_crop_error(feed_manager: FeedManager, harvested_crop: HarvestedCrop) -> None:
```

2024-01-08 19:31 UTC, Isgotkowitz commented on tests/test_feed_storage_module/test_harvested_crop.py
>  ):
```suggestion
) -> None:
```

2024-01-08 19:31 UTC, Isgotkowitz commented on tests/test_feed_storage_module/test_harvested_crop.py
> +def test_attributes():
```suggestion
def test_attributes() -> None:
```

2024-01-08 19:31 UTC, Isgotkowitz commented on tests/test_feed_storage_module/test_storage.py
> +def test_receive_unacceptable_crop(storage: Storage):
```suggestion
def test_receive_unacceptable_crop(storage: Storage) -> None:
```

2024-01-08 19:31 UTC, Isgotkowitz commented on tests/test_feed_storage_module/test_harvested_crop.py
> +def test_valid_category_type_combinations(category: CropCategory, crop_type: CropType):
```suggestion
def test_valid_category_type_combinations(category: CropCategory, crop_type: CropType) -> None:
```

2024-01-08 19:31 UTC, Isgotkowitz commented on RUFAS/routines/feed_storage/feed_manager.py
> +        self.active_storages: Dict[StorageType, Storage] = {}
So the Feed Manager expects to only manage 0 or 1 instances of each type of Storage? I.e. it will only simulate one bunker, one hay storer, etc.

2024-01-08 20:05 UTC, KevinP-B commented on RUFAS/routines/feed_storage/feed_manager.py
> +        self.active_storages: Dict[StorageType, Storage] = {}
That should be correct, Ed. in situ, that isn't what we would see, but in silico, there is no reason we've yet thought of that we need multiple instances when a single instance storing feed of varying ages will suffice. Is that correct, Pooyah?

2024-01-08 20:07 UTC, KevinP-B approved these changes
Implementation of FeedManager and receive_crop look good at a lay level

2024-01-08 20:41 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/feed_manager.py
> +        self.active_storages: Dict[StorageType, Storage] = {}
Yes, that is correct. Representation of something is different from that thing itself.

2024-01-08 20:50 UTC, PooyaHekmati commented on RUFAS/routines/feed_storage/feed_manager.py
> +            The amount of feed to distribute.
This class is simply a (data) broker. It receives data from upstream (S&C) and passes it downstream (Storage classes and Animal module). There is no way that this class can verify the units, it just gets scalar values, so it cannot be used as a source of truth. Therefore, using it as a source of truth for units can lead to unexpected outcomes. For example, let's say an upstream process, purchase feed logic as an example, has passed weight in lb. Unable to verify that, Feed Manager has stored what it has received. An SME realizes that the outputs are not correct and tries to figure out why. They suspect that units might be wrong, and look at the docstring here and see kg when it is lb. This misrepresentation makes them rule out the possibility of units not being correct. But if we don't lie to them here about something that we cannot be confident about, the next logical step is to check the upstream caller, where they will look at it and find the problem.

2024-01-08 21:05 UTC, merged

2024-01-08 21:09 UTC, JoeWaddell commented on RUFAS/routines/feed_storage/feed_manager.py
> +            The amount of feed to distribute.
Great explanation, you just merged this PR, but wanted to chime in that I think the reasoning is solid, and something I think we'll need to implement elsewhere in the model.