fixing docstring styles in crop module (1/2)
RuminantFarmSystems/RuFaS pull request #1111
Opened 2024-01-17 20:02 UTC by matthew7838

### Summary
This PR will fix approximately half of the crop module's documentation.

2024-01-19 22:08 UTC, Isgotkowitz requested changes
Changes requested on just `crop_data.py`: there are a few attributes with extra notes in the docstrings. Those extra notes should be in the docstring, not kept underneath the code for the attribute.

Everything else is minor stuff. Nice job Matthew, thank you for taking on this task.

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/biomass_allocation.py
> +    partition_biomass()
```suggestion
    allocate_biomass(light: float) -> None
        Allocate a plant's accumulated biomass based on the day's light exposure.
    photosynthesize(light: float) -> None
        Simulate the photosynthesis process by converting light energy into biomass.
    partition_biomass() -> None
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop.py
> +    dynamics, nutrient incorporation, heat accumulation, and more.
This should go in the Notes section.

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop.py
> +    def __init__(self, crop_data: Optional[CropData] = None):
```suggestion
    
    """

    def __init__(self, crop_data: Optional[CropData] = None):
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_data.py
> +        Expected fraction of plant biomass comprised of nitrogen for the plant near maturity (unitless).
```suggestion
        Growth stage factor for nitrogen-fixing symbiotes
    near_mature_phosphorus_fraction : float, default 0.3
        Expected fraction of plant biomass comprised of nitrogen for the plant near maturity (unitless).
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_data.py
> +        Total expected maximum water loss by the plant during the growing season (mm).
```suggestion
    max_root_depth : float, default 2000
        Maximum depth of roots in the soil (mm).
    cumulative_evaporation : float, default 0.0
        Total water lost to evaporation by the plant during the growing season (mm).
    cumulative_transpiration : float, default 0.0
        Total water lost to transpiration by the plant during the growing season (mm).
    cumulative_evapotranspiration : float, default 0.0
        Total water lost to evapotranspiration by the plant during the growing season (mm).
    cumulative_potential_evapotranspiration : float, default 0.0
        Total expected maximum water loss by the plant during the growing season (mm).
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_data.py
> +        Maximum amount of water that can be trapped in the canopy on a given day when fully developed (mm).
```suggestion
    canopy_water : float, default 0
        Amount of water currently held in the canopy (mm).
    max_canopy_water_capacity : float, default 0.8
        Maximum amount of water that can be trapped in the canopy on a given day when fully developed (mm).
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_data.py
> +    cumulative_water_uptake : float, default 0.0 mm
```suggestion
    water_uptake : float, default 0.0
        Total amount of water the plant took from the soil on the current day (mm).
    cumulative_water_uptake : float, default 0.0
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_data.py
> +    lignin_dry_matter_percentage : float, default 1.518%
```suggestion
    dry_matter_percentage : float, default 85.689
        Percentage of fresh yield that is dry matter (unitless).
    lignin_dry_matter_percentage : float, default 1.518
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_data.py
> +            Fraction of potential heat units accumulated. (unitless)
```suggestion
            Fraction of potential heat units accumulated (unitless).
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_data.py
> -
This blank line between the last line of the docstring and the closing """ should be present.

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop.py
>          """
```suggestion
        crop_data : Optional[CropData]
            The crop data to be used for simulation. If not provided, default specifications are used.
        
        """
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop.py
>          """
```suggestion
            Maximum air temperature for the day (°C).
         
        """
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_data.py
> +        Minimum leaf area index for plants (perennials and trees only)
```suggestion
        Minimum leaf area index for plants (perennials and trees only).
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_data.py
>              hydrological impacts of land use change from temperate grassland to energy crops: A case study in western
This should be moved up to underneath the description for `max_canopy_water_capacity`. Same with all other extra detailed comments underneath parameters.

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_management.py
```suggestion
    data : CropData
        A reference to `crop_data`, on which crop management operations will be conducted.
        
    """
    
    def __init__(self, crop_data: Optional[CropData] = None):
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_management.py
>          """
```suggestion
        Notes
        -----
        This operation is based on the SWAT model's guidelines, where a kill operation converts all biomass of
        the plant to residue. It is typically executed after a harvest (when specified) or at the end of the
        growing season for annual plants.

        """
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_management.py
> +        If a custom harvest index is provided by the user (harvest index override), that value is used. Otherwise,
```suggestion
        Notes
        -----
        If a custom harvest index is provided by the user (harvest index override), that value is used. Otherwise,
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_management.py
>          """
```suggestion
        Notes
        -----
        This method is used if the crop remains uncut after reaching maturity. It reduces the crop's biomass
        based on species-specific water content, simulating the natural dry-down process.
        
        """
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_management.py
> +        harvest index for the plant at maturity under ideal conditions.
```suggestion
        Notes
        -----
        The harvest index is the ratio of grain to total shoot dry matter. This calculation takes into
        account the fraction of potential heat units accumulated to date and the species-specific optimal
        harvest index for the plant at maturity under ideal conditions.
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_management.py
> +        harvest_index are input below their bounds, they are updated to equal their lower bounds.
```suggestion
        Notes
        -----
        The method takes into consideration the minimum harvest index under drought conditions, the potential harvest
        index for the day, and the water deficiency factor of the plant. If values of min_harvest_index and
        harvest_index are input below their bounds, they are updated to equal their lower bounds.
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_management.py
> +        guidelines for crop yield calculation.
```suggestion
        Notes
        -----
        The yield is calculated as a proportion of the above-ground biomass. This method is based on the SWAT model's
        guidelines for crop yield calculation.
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/dormancy.py
>          """
```suggestion
```

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/dormancy.py
> +    """
Methods section

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/growth_constraints.py
> +    """
Methods section

2024-01-19 22:08 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/growth_constraints.py
> +        """
```suggestion
```

2024-01-23 14:35 UTC, Isgotkowitz approved these changes
Approving, but please address comments. All are minor, except for 1 on the docstring for `_determine_accumulated_biomass()` in `biomass_allocation.py`. The Returns section is incorrect and should be fixed.

2024-01-23 14:35 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/biomass_allocation.py
> +            biomass accumulated ('accumulated biomass').
This is incorrect.

2024-01-23 14:35 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop.py
Constructors do not need docstrings, they are documented with the with the class docstring, as per the NumPy documentation: "The constructor (`__init__`) should also be documented here, the [Parameters](https://numpydoc.readthedocs.io/en/latest/format.html#params) section of the docstring details the constructor’s parameters."

2024-01-23 14:35 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop.py
```suggestion
        Notes
        -----
        This function acts as a wrapper for all the Crop growth process sub-routines.
        It should be called every day that the crop is alive and growing in the simulation.

```

2024-01-23 14:35 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_management.py
> +    It is primarily based upon the "Crop Yield" (5:2.4) and "General Management" (6:1) sections of the SWAT model.
```suggestion
    Notes
    -----
    This class is designed to handle various crop management operations using data provided by the `CropData` class.
    It is primarily based upon the "Crop Yield" (5:2.4) and "General Management" (6:1) sections of the SWAT model.
```

2024-01-23 14:35 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_management.py
>          crop_data: CropData
See above comment about docstrings and init methods.

2024-01-23 14:35 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/crop_management.py
> +        based on species-specific water content, simulating the natural dry-down process.
```suggestion
        Notes
        -----
        This method is used if the crop remains uncut after reaching maturity. It reduces the crop's biomass
        based on species-specific water content, simulating the natural dry-down process.
```

2024-01-23 14:35 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/dormancy.py
> +    using its attributes to determine and manage the dormancy status of a crop.
```suggestion

    Notes
    -----
    This class handles dormancy-related operations for crops based on crop data. It is based on
    the "Dormancy" section of the SWAT model (5:1.2). The class operates on a `CropData` object,
    using its attributes to determine and manage the dormancy status of a crop.
```

2024-01-26 18:23 UTC, JoeWaddell approved these changes
LGTM: a couple minor comments.

I'll have to use this PR as an example for a few similar cleanup PRs we'll need to make in the Animal Module.

2024-01-26 18:23 UTC, JoeWaddell commented on RUFAS/routines/field/crop/biomass_allocation.py
> +    def allocate_biomass(self, light: float):
Should these include the `-> None` typing for the return? (applies to this and method `photosynthesize` and `partition_biomass`)

2024-01-26 18:23 UTC, JoeWaddell commented on RUFAS/routines/field/crop/crop_data.py
> +        Heat units accumulated on the current day (Celsius*).
Is there a reason for the asterisk by Celsius? Or was that meant to be a placeholder for a degree symbol?

2024-01-27 23:11 UTC, matthew7838 commented on RUFAS/routines/field/crop/biomass_allocation.py
> +    def allocate_biomass(self, light: float):
You're right.

2024-01-27 23:17 UTC, matthew7838 commented on RUFAS/routines/field/crop/crop_data.py
> +        Heat units accumulated on the current day (Celsius*).
I believe that Celsius itself is kind of a placeholder over here since units are tricky for heat units, the units are heat units, but the heat units are calculated in celsius not Fahrenheit. I think it's fine to leave it like this for now until a further check by SMEs.

2024-01-30 17:37 UTC, merged