Add milk fat and milk protein percentages as user inputs
RuminantFarmSystems/RuFaS pull request #1153
Opened 2024-01-23 20:32 UTC by ltp23

Issue #1097 

This PR adds two new user inputs for milk fat and milk protein percentages and directly replaces those two variables with the user inputs.

Before, the milk protein percentage was set as some default constant, and the milk fat percentage was calculated by an equation. 

This PR is probably also related this issue #1101. The filter `Cow.milking_update.milk_data_at_milk_update.milk_protein` is actually the milk protein percentage, which has always been a constant value.

---
Update: For verification purposes, I added several filters related to dry cows milk stats.

2024-01-24 20:53 UTC, JoeWaddell reviewed
Nice clean implementation. Just some general comments/questions. As a more general question: are we OK to still add to the input JSONs, and if not, should we use the animal_constants file, instead?

2024-01-24 20:53 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/cow.py
> +            self.mPrt = self.get_user_defined_milk_protein_percent()
Should the `MILK_TRUE_PROTEIN` value should be removed from the constants file now?

2024-01-24 20:53 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/cow.py
> +            self.fat_percent = self.get_user_defined_milk_fat_percent()
Should the `calculate_fat_percent` method be noted as deprecated with the intent that it would be re-implemented in the future?

2024-01-24 20:53 UTC, JoeWaddell commented on output/output_filters/graph_milk_fat_and_protein.json
> +{
I really appreciate the inclusion of the output filters! Since the variation here is due to dry cows being included in the total, should we include the change I made below (to confirm the dry cow thing) in this PR?
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/fa71915b-996c-4c9f-ab71-7d2f24b1acb9)

2024-01-24 22:37 UTC, ltp23 commented on output/output_filters/graph_milk_fat_and_protein.json
> +{
I will let you decide on this, Joe. I can add it here since it is a small change.

2024-01-24 22:38 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/cow.py
> +            self.fat_percent = self.get_user_defined_milk_fat_percent()
I can remove it in this PR. Can you help me make a small git issue as a reminder to revisit this part? Thanks Joe.

2024-01-24 22:39 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/cow.py
> +            self.mPrt = self.get_user_defined_milk_protein_percent()
Yes, I can remove this constant.

2024-01-24 22:45 UTC, ltp23 commented on output/output_filters/graph_milk_fat_and_protein.json
> +{
And yes it is helpful for me at least to look at some graphs during the review phase, but I will remove the filter files before merging.

2024-01-25 14:46 UTC, jadamchick requested changes
Thanks Loi! overall looks great, just a couple slips in transforming between "3.6%" and "0.036" that need to be addressed (see my comments). 

Just to summarize what is happening here -- I'm not sure it is actually spelled out anywhere, and maybe would be helpful? (I had to write this out in order to do the review): 

user input = herd milk fat (3.6%)
this gets assigned as each cow's milk fat percent
each cow's milk fat kg produced daily = cow milk production * cow milk fat percent (/100 if percent is expressed as 3.6)
herd milk fat kg produced daily = sum of cow milk fat kg over all cows (all cows milking, though dry cows should have values of 0)
herd milk fat % = herd milk fat kg / herd milk production (*100 if want this expressed as 3.6, not 0.036)

the calculated "herd milk fat %" should be the same as the user input value
(and ditto for protein)

2024-01-25 14:46 UTC, jadamchick commented on input/data/animal/default_animal.json
> +	    "milk_protein_percent": 3.5
Let's do default of 3.2 for milk_protein_percent

2024-01-25 14:46 UTC, jadamchick commented on input/metadata/default_metadata.json
> +            "default": 3.0,
default 3.2 for milk_protein_percent

2024-01-25 14:46 UTC, jadamchick commented on RUFAS/routines/animal/life_cycle/cow.py
>                  0.15 * self.fat_percent * estimated_daily_milk_produced
Just a note that we don't use this fat-corrected milk calcluation in RuFaS for anything; we report total milk and milk fat and milk protein so we can do the calculations (fat-corrected milk, energy-corrected milk, etc.) in post

2024-01-25 14:46 UTC, jadamchick commented on RUFAS/routines/animal/life_cycle/life_cycle.py
>          )
for herd_milk_fat_percent and herd_milk_fat_protein: need to multiply each * 100 to get a value in the same dimensions as we started with ("3.6%" instead of "0.036"): 

```
self.herd_milk_fat_kg = sum(cow.milk_fat_kg for cow in cows)
        self.herd_milk_fat_percent = self.herd_milk_fat_kg / self.daily_milk_production * 100 
        self.herd_milk_protein_kg = sum(cow.milk_protein_kg for cow in cows)
        self.herd_milk_protein_percent = (
            self.herd_milk_protein_kg / self.daily_milk_production
        ) * 100 
```


maybe these calculations (herd_milk_fat_percent & protein_percent) are redundant, since they are bringing us back to the input value that we specified in the animal.json... but it is a nice verification that all of the transformations along the way are working as expected.

2024-01-25 14:46 UTC, jadamchick commented on RUFAS/routines/animal/life_cycle/cow.py
>              self.milk_protein_kg = self.mPrt * self.estimated_daily_milk_produced
need to divide each of these (for fat and for protein) by 100 to get a value in kg (since the input is "3.6", not "0.036")

```
self.milk_fat_kg = self.fat_percent*estimated_daily_milk_produced / 100             
self.milk_protein_kg = self.mPrt * self.estimated_daily_milk_produced / 100 
```

2024-01-25 14:46 UTC, jadamchick commented on output/output_filters/graph_milk_fat_and_protein.json
> +{
I agree that herd milk protein should be the sum of milk protein for all milking cows -- but also that dry cows shouldn't have any value for milk protein kg (because their milk production should be zero?) . I tried to verify this but now that Cow.milking_update is only for lactation cows, I don't know how to check on milk production or milk protein production of dry cows :)

2024-01-25 16:51 UTC, tomhuhh commented
As a general thought, also related to Julie and Joe's comments- do we want to completely rule out the possibility to calculate milk fat and protein using the equations that are associated with the outputs from the rest of RuFaS? Thus, from a design perspective, could we add a 'if' statement, so that if the user provides milk protein and fat components, we use them in the calculations; if not, we still go back to use the default milk protein values and milk fat equations? 

Additionally, do we want to add some randomness to the milk fat and protein even if we assume a constant value? By this I mean, if we know the standard deviation of milk fat and protein, can we randomize it for the milking cows in the herd. Theoretically it should not change the herd average, but this is where the stochastic part of the model comes in. I'm open to thoughts because I can also see the argument where this randomness is unnecessary compared to the rest of the model. 

Alternatively, as I don't have the full picture of it, if this is for the January deadline and for pilot testing, is it okay to only implement this logic in the pilot testing branch and make a note of it? If that is the case, the concerns that I have listed above can be ignored for the moment.  

Also, I would recommend for any important logic changes we make, we should try to document it in the relative design doc/pseudocode and make a note of it. 

Thanks!

2024-01-25 17:12 UTC, jadamchick commented
Great thoughts @tomhuhh -- and I think @KFosterReed is the person to speak to ultimate direction/vision. The ideal would definitely be to have milk fat and protein be dynamic based on cow and herd attributes changing day to day; however RuFaS has not had that capacity yet (the only equation in there was based on days in milk for fat, and protein was a fixed value). We figured this is the most expedient way to enable the milk fat + protein values to reflect herd-to-herd variation for now, with the intention to update those dynamic equations "someday". 

My vote is to keep the pilot testing branch as close to main branch as possible, and think that this could be implemented on both (since, using the current version, I've always had the herd value for milk fat come out to be 3.6% -- I think it could benefit from being able to modify that value?). But not my decision :) 

The question of randomness is a good one and I'll trust the experts on whether it really adds value at this point.

2024-01-25 17:21 UTC, KFosterReed commented
Thanks for the thoughtful comments all! My preference is to start (or re-start in this case) simple so let's go with only the option for static milk and fat based on user inputs. We can add it to the wish list for the Animal module and implement it in a more strategic way. (Also note, that the current equations for fat and protein are old and likely not representative anyway).

2024-01-25 18:16 UTC, KFosterReed commented
> Thanks for the thoughtful comments all! My preference is to start (or re-start in this case) simple so let's go with only the option for static milk and fat based on user inputs. We can add it to the wish list for the Animal module and implement it in a more strategic way. (Also note, that the current equations for fat and protein are old and likely not representative anyway).

I realize this may not have been clear - we can add the goal of having dynamic and stochastic fat and protein to the wish list :)

2024-01-25 19:55 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/cow.py
>                  0.15 * self.fat_percent * estimated_daily_milk_produced
Right, I don't see that variable being used in any other calculations anywhere. I made a separate issue to remove it if we don't have plans to implement an improved version.

2024-01-25 20:23 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
>          )
I can multiply those by 100 and then in the life cycle file, I would divide the percentages by 100 before calculating amounts of milk fat and protein.

2024-01-25 22:12 UTC, ltp23 commented on output/output_filters/graph_milk_fat_and_protein.json
> +{
I added some filters to verify dry cows milk stats

```
LifeCycleManager.daily_update.dry_cows_daily_milk_production
LifeCycleManager.daily_update.dry_cows_milk_fat_kg
LifeCycleManager.daily_update.dry_cows_milk_protein_kg
```

2024-01-26 15:58 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/cow.py
> +            self.fat_percent = self.get_user_defined_milk_fat_percent()
Opened an issue for this: https://github.com/RuminantFarmSystems/MASM/issues/1165

If you do wind up removing the calc in the PR, you could add the removed code to that Issue, to keep in case we want to restore it directly.

2024-01-26 21:31 UTC, jadamchick commented on input/metadata/default_metadata.json
> +            "default": 3.5,
default for this should be 3.6 to match what is above (in the animal.json)

2024-01-26 21:35 UTC, jadamchick approved these changes
Looks great! runs smoothly, outputs match what I expect. The only quirk is that the graph seems to have an incorrect legend (attributing lots of kg of milk fat to dry cows), but I can see in the data that "LifeCycleManager.daily_update.dry_cows_milk_fat_kg" and      "LifeCycleManager.daily_update.dry_cows_milk_protein_kg" are all zeros so I'm confident that it's a graphing/labeling error. 

I would just reiterate that it's worthwhile to remove the calc_fat_percent from the code for now to avoid any confusion, and stash it in the issue for future reference.

2024-01-29 15:02 UTC, JoeWaddell approved these changes
LGTM: tested again, and since everyone is OK with the percentage format, this looks good to merge.

2024-01-29 18:39 UTC, merged