fixing docstring styles in crop module (2/3)
RuminantFarmSystems/RuFaS pull request #1163
Opened 2024-01-25 20:25 UTC by matthew7838

### Summary
Fixing the crop file's docstring to the correct format. There will be one additional PR since the changes exceed expectations.

2024-02-01 14:24 UTC, Isgotkowitz requested changes
Docstrings look good, but there are missing "Raises" sections. Please add these and make sure they match the RuFaS "Raises" style outlined in #1074.

2024-02-01 14:24 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/heat_units.py
> +        mean_air_temperature : float
```suggestion
        mean_air_temperature : Optional[float]
```

2024-02-01 14:24 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/heat_units.py
> +        add newly acquired heat units to accumulated heat units
```suggestion
        Add newly acquired heat units to accumulated heat units.
```

2024-02-01 14:24 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/heat_units.py
> +
Needs a "Raises" section here.

2024-02-01 14:24 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/leaf_area_index.py
> +        main leaf area index function
```suggestion
        Main leaf area index function.
```

2024-02-01 14:24 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/leaf_area_index.py
> +        SWAT :3.2.2
```suggestion
        SWAT 5:3.2.2
```

2024-02-01 14:24 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/leaf_area_index.py
> +
Needs a "Raises" section

2024-02-01 14:24 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/leaf_area_index.py
> +            The previous day's leaf area index (uniteless).
```suggestion
        leaf_area_fraction : float
            Optimal leaf area fraction for the day (unitless).
        previous_leaf_area_fraction : float
            Previous day's optimal leaf area fraction (unitless).
        max_leaf_area_index : float
            The maximum leaf area index achievable by the plant (unitless).
        previous_leaf_area_index : float
            The previous day's leaf area index (unitless).
```

2024-02-01 14:24 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/nitrogen_incorporation.py
> +        copies the current nitrogen value to previous_nitrogen (for use between time steps)
```suggestion
        Copies the current nitrogen value to previous_nitrogen (for use between time steps).
```

2024-02-01 14:24 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/nitrogen_incorporation.py
Needs a "Raises" section.

2024-02-01 14:24 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/nitrogen_incorporation.py
Needs a "Raises" section.

2024-02-01 14:24 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/nitrogen_incorporation.py
Needs a "Raises" section

2024-02-01 18:31 UTC, allisterakun approved these changes
Good job, Matthew!

2024-02-01 18:31 UTC, allisterakun commented on RUFAS/routines/field/crop/heat_units.py
> +        If the attribute `use_heat_unit_temperature` is False, both `min_air_temperature` and `max_air_temperature` are
Maybe clarify that the attribute `use_heat_unit_temperature` is from the CropData class/self.data

2024-02-01 19:21 UTC, Isgotkowitz requested changes
The style of "Raises" sections should adhere to what is outlined in #1074.

2024-02-01 19:21 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/heat_units.py
> +            If `use_heat_unit_temperature` is False, `mean_air_temperature` must be provided.
This does not follow the style of "Raises" sections in #1074.
```suggestion
        ValueError
            If `use_heat_unit_temperature` is True and both `min_air_temperature` and `max_air_temperature` are not provided.
            If `use_heat_unit_temperature` is False and `mean_air_temperature` is not provided.
```

2024-02-01 19:21 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/leaf_area_index.py
> +            optimal_leaf_area_fraction is not a valid fraction.
These descriptions do not accurately reflect what causes ValueErrors to be raised.

2024-02-01 19:21 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/nitrogen_incorporation.py
> +            half_mature_heat_fraction equals mature_heat_fraction.
```suggestion
            If half_mature_heat_fraction equals mature_heat_fraction.
```

2024-02-01 19:21 UTC, Isgotkowitz commented on RUFAS/routines/field/crop/nitrogen_incorporation.py
> +            pseudocode: C.5.C.2, C.5.C.3
```suggestion
        ----------
        pseudocode: C.5.C.2, C.5.C.3
```

2024-02-02 14:51 UTC, Isgotkowitz approved these changes
LGTM, thanks for working through those changes Matthew

2024-02-02 15:43 UTC, merged