Rewriting metadata descriptions
RuminantFarmSystems/RuFaS pull request #1190
Opened 2024-01-31 15:47 UTC by JoeWaddell

This is meant to address Issue #890. 

Currently in draft to get input from all teams, to ensure the descriptions of their associated files reflects their main purpose.

File descriptions will have to be applied to all metadata files, but here I've only written them for the default_metadata.json while still in progress.

2024-02-01 15:52 UTC, tomhuhh requested changes
LGTM! Minor suggestions and I'm unsure about the manure application scheduling. Thanks Joe!

2024-02-01 15:52 UTC, tomhuhh commented on input/metadata/default_metadata.json
>        "path": "input/data/manure/manure_management.json",
Suggested change: `bedding type, handler, separator, and treatment information  `

2024-02-01 15:52 UTC, tomhuhh commented on input/metadata/default_metadata.json
>        "path": "input/data/manure_schedule/default_manure_schedule.json",
I'm uncertain with this part. Would Ed or Elle know anything about this?

2024-02-01 18:34 UTC, Isgotkowitz approved these changes
I think this looks good. I left suggestions for a few descriptions that I thought could be improved, but lmk if you want me to revisit some of them again.

2024-02-01 18:34 UTC, Isgotkowitz commented on input/metadata/default_metadata.json
> +      "description": "Configuration file for general simulation parameters, e.g. start and end dates.",
```suggestion
      "description": "Configuration file for general simulation parameters.",
```
The config file contains some pretty important stuff besides start and end dates, so I think not being specific about what it contains would be better. This pushes a user towards actually looking in it to see what it is doing and how it may be effecting their simulation, instead of just assuming that it is the start and end dates and that they don't need to worry about it.

2024-02-01 18:34 UTC, Isgotkowitz commented on input/metadata/default_metadata.json
> +      "description": "Tillage emission values used in the EEE module.",
Right now that file only contains tillage-related emissions numbers, but I have a feeling that will change in the future. Maybe putting something more generic there for now would be better?

2024-02-01 18:34 UTC, Isgotkowitz commented on input/metadata/default_metadata.json
> +      "title": "Soil data #TODO does this need a unique name for the future?",
```suggestion
      "title": "Soil data",
```
No, uniqueness is just a nice-to-have, and only benefits the readability of the metadata.

2024-02-01 18:34 UTC, Isgotkowitz commented on input/metadata/default_metadata.json
>        "path": "input/data/manure_schedule/default_manure_schedule.json",
I think "Specifies manure applications to a field." would do it.

2024-02-01 18:34 UTC, Isgotkowitz commented on input/metadata/default_metadata.json
> +      "description": "Tillage schedule applied - historical and future?",
```suggestion
      "description": "Schedule of tillage applications for a field.",
```

2024-02-01 18:34 UTC, Isgotkowitz commented on input/metadata/default_metadata.json
> +      "description": "Field characteristics including size, location, watering interval, etc. Also includes references to specification files.",
```suggestion
      "description": "Field characteristics and references to field management specifications.",
```

2024-02-01 22:23 UTC, JoeWaddell commented on input/metadata/default_metadata.json
> +      "description": "Configuration file for general simulation parameters, e.g. start and end dates.",
Point well taken!

2024-02-01 23:31 UTC, PooyaHekmati approved these changes
[![LGTM](https://lgtm.lol/p/714)](https://lgtm.lol/i/714)

2024-02-02 15:20 UTC, tomhuhh approved these changes
LGTM!

2024-02-02 15:21 UTC, merged