Update feed range values in metadata properties
RuminantFarmSystems/RuFaS pull request #1191
Opened 2024-01-31 21:12 UTC by elle-andreen

This is a mini version of PR #1100 that contains only the changes pertaining to feed constituent default/max/min values. This PR was created to, 1. enable a quick merge of the simple range value changes, while more complicated issues with the feed module metadata can be resolved in due time, and 2. circumvent the recent change in the structure of the metadata/properties/config files. 

Most feeds constituents (e.g., crude protein, neutral detergent fiber, calcium, etc.) are described on a percentage basis, either % dry matter or % of some other constituent. Multiple feeds expressed on a percentage basis had ranges that were too restrictive, i.e., not min=0 max=100. 

This PR:

1. Sets the range of all feeds expressed on a percentage basis to 0-100. 
2. Addressed a few incorrect or out-of-range default values. 
3. Fixes a few minor description issues.

2024-02-01 17:20 UTC, jadamchick requested changes
Hi Elle -- this looks great! However, it won't run (even using all of the defaults). It gives an error that       `"Variable: 'CP.111' has invalid value: 134.1, and cannot be changed to a default value. Violates properties defined in metadata properties section 'NASEM_Comp_properties'."
`

When I sort the NASEM_Comp_with_TDN by CP values, it looks like feeds 244, 245, and 246 have CP values > 100. Based on my minimal nutrition knowledge, I think these are accurate (something to do with the calculation from amt of nitrogen). 
So the CP max will need to be increased, but probably also worth a look from Edward or someone with more nutrition savvy to make sure the rest of the % values are actually 0-100? (counter-intuitive, I know). 


Also, I'm not sure why this error is now stopping the simulation -- i.e., why it "cannot be changed to a default value".

2024-02-01 22:43 UTC, JoeWaddell commented
> Also, I'm not sure why this error is now stopping the simulation -- i.e., why it "cannot be changed to a default value".

This is because those are values without a default assigned: locally I added a default field, and it will now run. 
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/c758191e-8648-477a-804d-6ef8ee33f653)

@jadamchick if you get a chance to try adding the (temporary) default field (since I think we won't want to assume a default value for such an important measure) on the pilot farms you ran into problems with, it should give us a better idea if this will solve all the related issues you ran into.

Also tagging @Ed731551 so he can chime in about why the crude protein max (and potentially others?) would have NASEM values over 100%

2024-02-01 23:19 UTC, elle-andreen commented
Thank you for bringing that to my attention, Julie! And for the temporary workaround Joe! 

Finally, a technical issue I actually have some subject-matter knowledge on 😂 You are correct in your line of thinking about crude protein - since most labs these days actually measure N content and multiply % N by 6.25, technically you can have CP values > 100%. I changed the maximum to 625 for CP, NDICP, and ADICP to accommodate a theoretical feed with 100% N. 

The only other constituent I can see that could have a maximum value > 100 would be kd (rate of ruminal degradation). I don't have the NASEM in front of me, but this value is usually expressed on a % DM per **hour** basis. So, if your ingredient degrades completely in the rumen in 30 minutes, your kd would be 200% per hour. I think we should either remove the maximum for this value, or make it something quite large, like 10,000. @Ed731551, what are your thoughts on that? As Joe said, are there any others in the metadata I may have missed that we should reconsider?

2024-02-02 15:37 UTC, jadamchick commented
I made a temporary fix of increasing the defaults for: CP, NDICP, ADICP, kd (as Elle suggested) (worth noting -- some of these had to be updated in both the NRC and NASEM sections). But now, just running the defaults, I get warnings about TDN- 

```
"Invalid data fixed: 'TDN.17' value changed from 127.36 to 0. Fix enabled by default value specified in 'NRC_Comp_properties'.",
      "Invalid data fixed: 'TDN.19' value changed from 102.67 to 0. Fix enabled by default value specified in 'NRC_Comp_properties'.",
      "Invalid data fixed: 'TDN.39' value changed from 163.51 to 0. Fix enabled by default value specified in 'NRC_Comp_properties'.",
      "Invalid data fixed: 'TDN.40' value changed from 176.33 to 0. Fix enabled by default value specified in 'NRC_Comp_properties'.",
      "Invalid data fixed: 'TDN.42' value changed from 147.4 to 0. Fix enabled by default value specified in 'NRC_Comp_properties'.",
      "Invalid data fixed: 'TDN.43' value changed from 183.97 to 0. Fix enabled by default value specified in 'NRC_Comp_properties'.",
      "Invalid data fixed: 'TDN.95' value changed from 101.01 to 0. Fix enabled by default value specified in 'NRC_Comp_properties'.",
      "Invalid data fixed: 'TDN.99' value changed from 122.34 to 0. Fix enabled by default value specified in 'NRC_Comp_properties'."
```


I'll run it with one of the pilot farms and the regional diets to see if anything else flags right off the bat. Stay tuned!

2024-02-02 18:28 UTC, Ed731551 commented
Agree with @elle-andreen. Some feeds can have CP greater than 100% as calculation is N x 6.25 (urea for example).
Regarding second point raised, I would favor to remove the maximum values. 
On TDN values, I had a look on the NRC 2001 book and yes, some TDN tabulated values (e.g. some fat products) can be more than 100% assuming a high digestibility of those feeds at the maintenance level of intake (i.e., vegetable oil; TDN = 184 %). Hope that helps. Thank you.

2024-02-05 14:12 UTC, jadamchick commented
Having made the following updates locally (some had to updated in multiple sections of the metadata properties): 
- CP max to 625; added default of 0
- NDICP max to 625
- ADICP max to 625
- TDN max to 184
- KD max to 10000

The default feed file, first pilot farm (c1f1), and all of the default regional diets run w/o any warnings along these lines.

2024-02-06 13:18 UTC, KFosterReed commented
Hey team, where are we with this PR?

2024-02-06 13:22 UTC, JoeWaddell commented
> Hey team, where are we with this PR?

My instinct is that we could implement the maximum that Julie is using, since those have gone through the most diverse set of feed tests so far, and would be consistent with what Edward advised, as well.

2024-02-06 13:37 UTC, elle-andreen commented
I've updated the following ranges to:

CP max to 625
NDICP max to 625
ADICP max to 625
TDN max to 625
No maximum for Kd of N B2 fraction

@jadamchick, would you mind running this on a feed file or two to confirm you're not receiving warnings?

2024-02-06 14:56 UTC, jadamchick commented
> I've updated the following ranges to:
> 
> CP max to 625 NDICP max to 625 ADICP max to 625 TDN max to 625 No maximum for Kd of N B2 fraction
> 
> @jadamchick, would you mind running this on a feed file or two to confirm you're not receiving warnings?

Yep, will do today

2024-02-06 16:04 UTC, JoeWaddell approved these changes
LGTM, only the most minor of minor formatting comments.

2024-02-06 16:04 UTC, JoeWaddell commented on input/metadata/properties/default.json
> +      "description": "ADICP (% DM) -- Acid detergent insoluble nitrogen multiplied by 6.25.",
Super-minor formatting quirk: is there a specific reason that (%DM) was moved to the beginning of the description (unlike the rest), or for the `--` instead of a single `-`?

2024-02-06 16:41 UTC, jadamchick approved these changes
Runs well on a handful of farms without any warnings!

2024-02-06 16:46 UTC, elle-andreen commented on input/metadata/properties/default.json
> +      "description": "ADICP (% DM) -- Acid detergent insoluble nitrogen multiplied by 6.25.",
It's a residual of the original PR covering the entire feed module! Not anything specific to this variable. The intention eventually is to standardize the location of the units and use a standard separator (i.e. "--") between the title and description, to hopefully utilize in Ed's script to convert the metadata properties to the DCA. But it's not a top priority right now, hence those changes haven't been applied uniformly. We can revert those changes here if we want.

2024-02-06 16:48 UTC, merged