Additional manure module nitrous oxide calculations
RuminantFarmSystems/RuFaS pull request #1203
Opened 2024-02-02 08:47 UTC by ltp23

Closes #1199 

This PR adds nitrous oxide calculations for the following manure treatment: slurry storage underfloor/outdoor, anaerobic lagoon, and anaerobic digestion. 

The config objects for manure treatments now have an extra field — `manure_cover`, which can take on the following values: `cover`, `no cover`, or `N/A`. 

Here are the csv filters I used

```
^ManureTreatmentDailyOutput_Pen_0_CALF.storage_nitrous_oxide$
^ManureTreatmentDailyOutput_Pen_1_GROWING.storage_nitrous_oxide$
^ManureTreatmentDailyOutput_Pen_2_CLOSE_UP.storage_nitrous_oxide$
^ManureTreatmentDailyOutput_Pen_3_LAC_COW.storage_nitrous_oxide$
^AnaerobicDigestion_ManureTreatmentDailyOutput_Pen_4_LAC_COW.storage_nitrous_oxide$
^ManureTreatmentDailyOutput_Pen_4_LAC_COW.storage_nitrous_oxide$

^Accumulated_ManureTreatmentDailyOutput_Pen_0_CALF.storage_nitrous_oxide$
^Accumulated_ManureTreatmentDailyOutput_Pen_1_GROWING.storage_nitrous_oxide$
^Accumulated_ManureTreatmentDailyOutput_Pen_2_CLOSE_UP.storage_nitrous_oxide$
^Accumulated_ManureTreatmentDailyOutput_Pen_3_LAC_COW.storage_nitrous_oxide$
^Accumulated_ManureTreatmentDailyOutput_Pen_4_LAC_COW.storage_nitrous_oxide$

^ManureTreatmentDailyOutput_Pen_0_CALF.liquid_manure_nitrogen$
^ManureTreatmentDailyOutput_Pen_1_GROWING.liquid_manure_nitrogen$
^ManureTreatmentDailyOutput_Pen_2_CLOSE_UP.liquid_manure_nitrogen$
^ManureTreatmentDailyOutput_Pen_3_LAC_COW.liquid_manure_nitrogen$
^AnaerobicDigestion_ManureTreatmentDailyOutput_Pen_4_LAC_COW.liquid_manure_nitrogen$
^ManureTreatmentDailyOutput_Pen_4_LAC_COW.liquid_manure_nitrogen$

^Accumulated_ManureTreatmentDailyOutput_Pen_0_CALF.liquid_manure_nitrogen$
^Accumulated_ManureTreatmentDailyOutput_Pen_1_GROWING.liquid_manure_nitrogen$
^Accumulated_ManureTreatmentDailyOutput_Pen_2_CLOSE_UP.liquid_manure_nitrogen$
^Accumulated_ManureTreatmentDailyOutput_Pen_3_LAC_COW.liquid_manure_nitrogen$
^Accumulated_ManureTreatmentDailyOutput_Pen_4_LAC_COW.liquid_manure_nitrogen$

```

2024-02-03 15:05 UTC, tomhuhh reviewed
Thanks Loi! The code runs and there are outputs. 

I left a couple questions that I hope you could help me understand better. 

Thanks!

2024-02-03 15:05 UTC, tomhuhh commented on RUFAS/routines/manure/constants_and_units/gas_emission_constants.py
> +        }
I am wondering what happens if the manure treatment is `anaerobic lagoon and digestion`? One of the scenarios in the example filter is `anaerobic lagoon and digestion with separator` and it worked (there are outputs).

2024-02-03 15:05 UTC, tomhuhh commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +            and whether the manure is covered or not (kg :math:`N_2O`-N/kg manure N).
Good to know!

2024-02-05 19:24 UTC, ltp23 commented on RUFAS/routines/manure/constants_and_units/gas_emission_constants.py
> +        }
Thanks Haowen. I think it should still work. In pen 3, I tested this by using scenario 5 that includes the `anaerobic lagoon and digestion`.

2024-02-06 19:16 UTC, PooyaHekmati commented
I'm curious why we need to explicitly add two new csv filters here.

2024-02-06 21:35 UTC, ltp23 commented
> I'm curious why we need to explicitly add two new csv filters here.

They are there for review purposes and will be removed before merging.

2024-02-06 21:37 UTC, jadamchick approved these changes
Looks good to me, seems to run well for a variety of manure inputs.

2024-02-06 21:37 UTC, jadamchick commented on input/metadata/properties/default.json
> +            "pattern": "^(slurry storage underfloor|slurry storage outdoor|open lots|compost bedded pack barn|anaerobic lagoon|anaerobic digestion and lagoon|anaerobic digestion and lagoon with separ
Nice catch to add "composting"! I was just asking Allister about it and then saw you're on top of it here :)

2024-02-06 21:37 UTC, jadamchick commented on input/metadata/properties/default.json
> +            "description": "Indicates the presence or absence of a cover in the manure treatment or storage system. When used in the case of a Slurry Storage system (underfloor or outdoors) the cover
helpful description, thanks. 
Is there a functional difference between manure_cover = "N/A" (as for anaerobic digestion) and manure_cover not even being listed as a config (as for "open lots", for example)?

2024-02-08 02:24 UTC, ltp23 commented on input/metadata/properties/default.json
> +            "description": "Indicates the presence or absence of a cover in the manure treatment or storage system. When used in the case of a Slurry Storage system (underfloor or outdoors) the cover
Right, these calculations don't apply to systems other than slurry storage and anaerobic systems, even though the default value is `no cover`. The `N/A` option is currently only applicable to the anaerobic digestion treatment.

2024-02-09 13:57 UTC, ew3361zh approved these changes
LGTM! Nice work, Loi!

2024-02-09 13:57 UTC, ew3361zh commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +        emission_factor__kg_nitrous_oxide_N_per_kg_manure_N : float
```suggestion
        emission_factor_kg_nitrous_oxide_N_per_kg_manure_N : float
```

2024-02-09 17:32 UTC, PooyaHekmati requested changes
Please remove the output filters and revert the changes in gitignore.

2024-02-09 20:50 UTC, elle-andreen commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +        emission_factor__kg_nitrous_oxide_N_per_kg_manure_N : float
I think this same typo also occurs in a few other files!

2024-02-09 21:11 UTC, elle-andreen commented on input/metadata/properties/default.json
> +            "description": "Indicates the presence or absence of a cover in the manure treatment or storage system. When used in the case of a Slurry Storage system (underfloor or outdoors) the cover
According to Varma, the slurry underfloor treatment should not include the option for a crust, I assume because manure falls through slats continually throughout the day and doesn't allow a crust to form. This came up when Varma and I were discussing slurry NH3 emissions, because the presence of a crust on slurry also affects NH3 emissions (but we haven't implemented that aspect into the NH3 emission calculations yet). If @KFosterReed agrees, I would set slurry storage underfloor to always be 'no cover'.

2024-02-09 21:18 UTC, elle-andreen commented
This looks great to me Loi, thank you for making sure the necessary information was in the metadata descriptions! It really helps us remember the intricacies of data input down the line.

One question mostly for Kristan @KFosterReed: is there any need to subtract the N lost to N2O from the mass of manure N and/or TAN entering storage each day, similar to how we account for NH3-N losses from housing? I don't think we're doing that here, although maybe I'm missing it or it's not imperative at the moment because N2O losses are so small.

2024-02-09 21:49 UTC, PooyaHekmati approved these changes

2024-02-09 22:17 UTC, KFosterReed commented
> This looks great to me Loi, thank you for making sure the necessary information was in the metadata descriptions! It really helps us remember the intricacies of data input down the line.
> 
> One question mostly for Kristan @KFosterReed: is there any need to subtract the N lost to N2O from the mass of manure N and/or TAN entering storage each day, similar to how we account for NH3-N losses from housing? I don't think we're doing that here, although maybe I'm missing it or it's not imperative at the moment because N2O losses are so small.

First, this PR looks great! Thanks everyone!!

@elle-andreen It looks like the N2O nitrogen is in fact being subtracted from the total manure N as you rightly point out is expected. My understanding of the the formation of N2O is that it does not come directly from TAN so I think just the total N is sufficient! Good call to check this!!

2024-02-09 22:46 UTC, ltp23 commented
Thanks everyone!

2024-02-09 22:46 UTC, merged