Multiple Error and Enum Docstrings Alignment
RuminantFarmSystems/RuFaS pull request #1204
Opened 2024-02-02 15:11 UTC by ew3361zh

PR to address issue #1074.

This PR attempts to align the docstring formatting for functions that raise multiple instances of the same type of error and additionally aligns enum-based class docstrings to use the "Attributes" docstring category as is outlined in the issue.

Notes:
- I made some small updates to syntax ad grammar where I saw it necessary (a period at the end of a sentence, making a sentence clearer, making sure the variables referenced in the error raised were correctly spelled, etc).
- There were some functions that raised errors that didn't list the errors raised in the docstrings and I added those in.
- There was one enum class in the Animal module (AnimalGRoupingScenario) that had a TODO for the docstrings so I didn't update the Attributes formatting.
- I know Matthew is also working on docstring formatting in the C&S module so I hopefully am not duplicating any work he's doing right now.

2024-02-03 06:18 UTC, matthew7838 requested changes
Great improvements Niko! There are some parts where the extra line between the content of docstrings and closing `"""` is missing. I have pointed those out. Should be minor, once those are fixed should be good to go.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/field/crop/heat_units.py
This file duplicates, but you can just accept what's on the main branch now to solve the merge conflicts and it should be fine.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/field/soil/snow.py
> +            If the snow_content is < 0.0.
Need a blank line between end of docstring and closing `"""`.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/animal/life_cycle/cow.py
> +            If reproduction program not in list of current reproduction programs.
Need a blank line between the end of docstring and closing `"""`.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/animal/animal_types.py
> +    """
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/animal/animal_combinations.py
> +        Represents a pen with all heifers and dry cows only.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/output_manager.py
> +            If there is an error in decoding the JSON file.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/output_manager.py
> +            If an error occurs while saving to the file.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/input_manager.py
> +            If faulty data type found in data blob key.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/input_manager.py
> +            For any other unexpected errors during CSV file loading.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/input_manager.py
> +            For any other unexpected errors during JSON file loading.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/animal/life_cycle/heiferII.py
> +            If there is no hormone delivery schedule for the animal category.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/animal/life_cycle/heiferII.py
> +            If the reproduction program is not valid.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/animal/pen.py
> +            If prefix for animal type is not found.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/animal/purchased_feed_emissions_estimator.py
> +        """
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/animal/ration/ration_driver.py
> +            If the feed id is not found in the feed id list.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/feed_storage/harvested_crop.py
> +            If the crop type is not valid for the crop category.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/manure/manure_separators/manure_separator_classes.py
> +    The default sand lane separation method is SAND_LANE_MANURE_SEPARATION.
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/manure/manure_treatments/manure_treatment_types.py
> +    The DEFAULT manure treatmenet type is SLURRY_STORAGE_UNDERFLOOR
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/routines/manure/manure_treatments/manure_types.py
> -
Missing extra line.

2024-02-03 06:18 UTC, matthew7838 commented on RUFAS/util.py
> +        InvalidJSONFileError:
```suggestion
        InvalidJSONFileError
```

2024-02-05 17:12 UTC, matthew7838 approved these changes
LGTM, great work Niko. Thanks for the modification.

2024-02-05 22:24 UTC, allisterakun approved these changes
Good work, Niko! Nicely done~

2024-02-06 01:51 UTC, merged