Adding byproducts to daily feed totals
RuminantFarmSystems/RuFaS pull request #1239
Opened 2024-02-06 19:45 UTC by JoeWaddell

Changes cherry-picked from #1226

Adds Fd_Category to NRC comp library, and adds the total kg of byproducts fed to the ration totals output.

2024-02-07 17:06 UTC, jadamchick approved these changes
Looks good and runs well!

2024-02-09 17:43 UTC, jadamchick commented
As soon as you get a second set of eyes (@tomhuhh maybe, when you have the chance?) on those changes to feeds 135 and 137 in NASEM, I'll cherry pick the commits into the pilot testing branch and update that as part of PR #1246 .

2024-02-10 14:50 UTC, tomhuhh requested changes

2024-02-10 14:50 UTC, tomhuhh commented on input/data/feed/NRC_comp.csv
> +135,By-Product/Other,Conc,5.4,10.5,5.2,2.3,10.8,22.1,16.5,2.3,12.8,49,1,80.7,4.5,90.5,5,2,90,0.49,0.29,0.11,1.04,0.26,0.19,0.11,3.51,FALSE,FALSE,kg,57.49,100,0
This DM% should be 35.4 instead of 5.4 as far as I remember.

2024-02-10 14:50 UTC, tomhuhh commented on input/data/feed/NASEM_Comp_with_TDN.csv
>  138,Rice bran,By-Product/Other,Conc,92.376,10.021,14.813,31,45,24,3.38,53.429,85.033,30.483,0.778,2.18,13.84,23.055,23.333,4.943,22.181,7.953,12,18.503,3.21,0.779,1.774,0.784,1.402,0.02,0.133,0.174,8
I would also just double check that the assumed TDN and DE (from 114 meat meal) are correctly entered.

2024-02-12 15:04 UTC, JoeWaddell commented on input/data/feed/NRC_comp.csv
> +135,By-Product/Other,Conc,5.4,10.5,5.2,2.3,10.8,22.1,16.5,2.3,12.8,49,1,80.7,4.5,90.5,5,2,90,0.49,0.29,0.11,1.04,0.26,0.19,0.11,3.51,FALSE,FALSE,kg,57.49,100,0
Corrected, thanks!

2024-02-12 15:17 UTC, tomhuhh approved these changes
LGTM!

2024-02-12 20:40 UTC, allisterakun approved these changes
Code looks good! Straight-forward changes.

2024-02-12 20:44 UTC, merged