Remove example report and update `ReportGenerator` wiki
RuminantFarmSystems/RuFaS pull request #1241
Opened 2024-02-06 20:32 UTC by Isgotkowitz

This PR removes the example report `report_example.json`, as instructed in #1011.

The Report Generator wiki has been updated to include descriptions and examples of `constants`, `cross_references` and `filter_by_exclusion`. As part of reviewing this PR, please read through the wiki to see if it is missing anything or has any mistakes.

Closes #1011 closes #1184

2024-02-08 17:08 UTC, ew3361zh requested changes
Really nice additions to the Wiki, Ed. Clear and concise and I think covers a lot of what we need in there. 

A few recommendations:
- Adding a section about the filter-by-exclusion option for filter files (see the `_prepare_report_data_with_constants()` method in report generator)
- Adding info about being able to use regex patterns for variables filtering (it's mentioned for the filters section but it would be good to mention for the variables as well)
- Add variables key-values to one or two of the report examples (could even just be using the regex `.*`)
- Currently the variables definition of the filter content section is capitalized and should probably be done lower-case to match the style of the other entries

2024-02-08 20:09 UTC, Isgotkowitz commented
> Really nice additions to the Wiki, Ed. Clear and concise and I think covers a lot of what we need in there.
> 
> A few recommendations:
> 
> * Adding a section about the filter-by-exclusion option for filter files (see the `_prepare_report_data_with_constants()` method in report generator)
> * Adding info about being able to use regex patterns for variables filtering (it's mentioned for the filters section but it would be good to mention for the variables as well)
> * Add variables key-values to one or two of the report examples (could even just be using the regex `.*`)
> * Currently the variables definition of the filter content section is capitalized and should probably be done lower-case to match the style of the other entries

@ew3361zh thank you, I went back and I think have addressed all the above points correctly.

2024-02-08 20:54 UTC, ew3361zh approved these changes
Looks beautiful. Nice work, Ed!

2024-02-12 04:16 UTC, PooyaHekmati approved these changes

2024-02-12 14:43 UTC, merged