Update methane emission from slurry storage
RuminantFarmSystems/RuFaS pull request #1306
Opened 2024-02-17 21:19 UTC by ltp23

Closes #1271 

[Docs](https://docs.google.com/document/d/1EfYQUIwoIrt05yWLauEefcdTlgkGkk0WX6EoVqrL6eQ/edit)

This PR updates the slurry storage methane emission calculations based on the suggestions from the design doc.

To see the complete results, I use this filter

```
{
  "multiple": [
    {
      "name": "Storage methane, kg",
      "filters": [
        "^(?:AnaerobicDigestion_)?ManureTreatmentDailyOutput_Pen_.*storage_methane$"
      ]
    }
  ]
}
```

2024-02-19 13:50 UTC, tomhuhh requested changes
Thanks Loi! This is a great start point. Please see my comments. I hope we can get this function sorted out in the next couple of days. Keep up the good work!

2024-02-19 13:50 UTC, tomhuhh commented on RUFAS/routines/manure/gas_emissions/calculator.py
Hi @ltp23 ! This equation does not seem to be correct. Please refer to this document for the most up-to-date information- https://docs.google.com/document/d/1EfYQUIwoIrt05yWLauEefcdTlgkGkk0WX6EoVqrL6eQ/edit. To highlight what I am referring to, we should remove '24' in both locations. Thanks!

2024-02-19 13:50 UTC, tomhuhh commented on RUFAS/routines/manure/constants_and_units/gas_emission_constants.py
>      """
I did not know we can use '_' inside the numbers. This is good to know!

2024-02-19 13:50 UTC, tomhuhh commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +                GasEmissionConstants.METHANE_EMISSION_COEFFICIENT
As mentioned above, this should be deleted. We should also remove it from the constant file. Thanks!

2024-02-19 13:50 UTC, tomhuhh commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +        non_degradable_volatile_solids_fraction = non_degradable_volatile_solids / total_volatile_solids
It is great that we are calculating the fractions of degradable and non-degradable volatile solids here. A further step is to also pass through the degradable and non-degradable volatile solids in the argument of this function. Thanks!

2024-02-19 15:26 UTC, elle-andreen commented on RUFAS/routines/manure/constants_and_units/gas_emission_constants.py
>      """Natural log of the Arrhenius constant (unitless)."""
We can update the units of this value from "unitless" to "g CH4/kg manure VS/h"

2024-02-19 19:33 UTC, ltp23 commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +                GasEmissionConstants.METHANE_EMISSION_COEFFICIENT
Just to clarify, do you want to remove both the `arrhenius_exponent` and the `correcting_factor` while keeping the `methane_emission_coefficient`?

2024-02-19 19:45 UTC, ltp23 commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +        non_degradable_volatile_solids_fraction = non_degradable_volatile_solids / total_volatile_solids
I can do the fraction calculations inside the volatile components function.

2024-02-19 20:27 UTC, elle-andreen commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +                GasEmissionConstants.METHANE_EMISSION_COEFFICIENT
We would remove only `GasEmissionConstants.METHANE_EMISSION_COEFFICIENT` (this is where the value of 24 that Haowen referred to above is coming from). `degradable_volatile_solids` would become `degradable_volatile_solids_fraction`. The other terms in lines 96-99 are fine as-is!

2024-02-19 20:36 UTC, tomhuhh commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +        non_degradable_volatile_solids_fraction = non_degradable_volatile_solids / total_volatile_solids
Thanks! That is a great idea. In addition, we need to figure out a way to pass through the `degradable_volatile_solids` and `non_degradable_volatile_solids` from the animal module and serve as the input for the volatile components function.

2024-02-19 23:16 UTC, ltp23 commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +        non_degradable_volatile_solids_fraction = non_degradable_volatile_solids / total_volatile_solids
This would need some redesign. Currently, the two components merge into one after reception pit.

2024-02-20 13:46 UTC, KFosterReed commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +        non_degradable_volatile_solids_fraction = non_degradable_volatile_solids / total_volatile_solids
I want to add that the passage of the degradable and non degradable VS from the animal module will be addressed in a separate PR that addresses issue #1269.

2024-02-20 21:44 UTC, tomhuhh approved these changes
LGTM!

2024-02-21 14:09 UTC, elle-andreen approved these changes
Accounting for the daily update of VS not being altered yet, the daily methane values here look good! Thank you Loi!

2024-02-21 17:47 UTC, ltp23 commented
Thanks everyone! So I think the next step is to try to pass along the degradable and non-degradable VS values down to the treatment method so that we can use them for calculating storage methane.

2024-02-21 17:47 UTC, merged