Unit tests for Pen class
RuminantFarmSystems/RuFaS pull request #132
Opened 2022-04-13 23:35 UTC by ancheypeng

This pull request adds unit tests for some of the functions in the Pen class. 

The following unit tests have been implemented:

- test_reset_manure
- test_calc_avg_growth
- test_clear
- test_subset_class_feeds

2022-04-22 18:04 UTC, KFosterReed commented
This runs and reading through the tests it makes logical sense to me but I am going to defer to @PooyaHekmati. After he has approved them, if any further changes were made, I will run the model again and then give my approval. Great work Anchey!

2022-05-03 00:57 UTC, PooyaHekmati requested changes
Overall, looks good; good job! In addition to the minor comments I made, I do not see expected_feed_units.py being used anywhere. What's the plan for it?

2022-05-03 00:57 UTC, PooyaHekmati commented on tests/animal_config.json
> +                        16.13,
Just a thought: can we / does it make sense to put these numbers in the same line and reduce the number of lines in the file?

2022-05-03 00:57 UTC, PooyaHekmati commented on tests/expected_outputs/expected_feed_units.py
> +            'feed_name': 'BLOOD',
I think these can go in the same line.

2022-05-03 00:57 UTC, PooyaHekmati commented on tests/test_pen.py
> +def test_daily_p_update(pen):
Missed pass and type annotation here

2022-05-03 00:57 UTC, PooyaHekmati commented on tests/test_pen.py
> +    }
Can we use zip or something similar to avoid duplicated code here?

2022-05-03 04:52 UTC, ancheypeng commented
> Overall, looks good; good job! In addition to the minor comments I made, I do not see expected_feed_units.py being used anywhere. What's the plan for it?

The expected_feed_units.py and the animal_config.json were files used for old code/other tests that have been removed/replaced, but I forgot to remove them.

2022-05-03 04:52 UTC, ancheypeng commented on tests/test_pen.py
> +def test_daily_p_update(pen):
This unit test was not implemented yet, so I just removed the pen parameter.

2022-05-03 05:40 UTC, ancheypeng commented on tests/test_pen.py
> +    }
I couldn't think of a good way to reduce the duplication just in that section because each set has slightly different contents from all the others. Instead, I pushed a new change which changes the parameterization overall. However, I'm not sure if it's the best practice because I had to use a "fake" fixture (feed_allocations) because a real fixture did not work well with the pytest parameterization.

2022-05-04 00:57 UTC, PooyaHekmati approved these changes

2022-05-04 19:57 UTC, KFosterReed approved these changes
All the tests make logical sense to me and I was able to break a couple of them by changing what I thought it was testing in the function. Well done!

2022-05-04 20:24 UTC, merged