IM array and nested object validation, and element counting
RuminantFarmSystems/RuFaS pull request #1345
Opened 2024-02-28 06:29 UTC by ltp23

In this PR I modified/refactored several existing methods by creating second versions instead of doing so directly. I also added some new methods. I edited some metadata that got flagged. 

The total number of validated elements has increased from about 530K to 1.7mil elements.

I'm working on finalizing the remaining unit tests.

Attempt to close #873 and #683 

---

Update 1: I have modified in-place all the methods that needed to be changed for this PR. Updated all the relevant unit tests and wrote new ones.

---

Update 2: Fixed merged conflicts to make the PR work again. Compiled a list of follow-up tasks in issue #1401.

---

Update 3: Changed the default packing density to 200. Removed the active N percent and denitrification rate input variables.

---

Update 4: Removed issue #1401. Will replace with individual issues for each action item.

2024-02-28 19:26 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +    def _validate_json_element(  # noqa
```suggestion
    def _validate_json_element(
```
flake8 has no issues with this method, why is there noqa here?

2024-02-29 17:11 UTC, ltp23 commented on RUFAS/input_manager.py
> +    def _validate_json_element(  # noqa
Removed now.

2024-03-11 15:42 UTC, Isgotkowitz requested changes
Requested changes in the Input Manager. I think there are some things that could be done to make it simpler, though some of the suggestions may not apply after the changes from main are merged in.

2024-03-11 15:42 UTC, Isgotkowitz commented on RUFAS/input_manager.py
>                      )
```suggestion
```
This check is redundant. An invalid file type will be caught and handled when Input Manager attempts to load the file.

2024-03-11 15:42 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        elements_counter: "ElementsCounter",
```suggestion
        elements_counter: ElementsCounter,
```
I think it would be better to move `ElementsCounter` to the top of the file, then type hit it normally.

2024-03-11 15:42 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        return input_data
```suggestion
```
This method is defined twice.

2024-03-11 15:42 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        return new_counter
I think `ElementState` and `ElementCounter` are adding more than there need to be. Here are some changes that I think would make things simpler:
- Remove `decrement()` in `ElementCounter`. It isn't used at all, so it seems like it isn't needed. Also `_check_negative_counts()` could be removed.
- Remove `ElementState` and `increment()`. Instead have there be three methods in `ElementCounter`, one for adding a valid element, one for adding a fixed element, and one for adding an invalid element.

Alternatively, `ElementCounter` could be removed entirely and replaced with a few methods in Input Manager used to increment the counts of valid, fixed, and invalid elements.

2024-03-11 15:42 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        input_data: Dict[str, Any],
If the input data is a dict, it should be validated with the method dedicated to validating dict inputs.

2024-03-11 15:42 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        input_data : Any
The type should not be Any, it should be a list.

2024-03-11 15:42 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        Validates an input data element of type object.
This method is extremely similar to `_validate_dict_element()`. Please combine it with that method.

2024-03-12 17:38 UTC, ltp23 commented on RUFAS/input_manager.py
>                      )
It's been removed now.

2024-03-12 17:42 UTC, ltp23 commented on RUFAS/input_manager.py
> +        elements_counter: "ElementsCounter",
Yes, this would help with typing inside the InputManager class, but within the ElementsCounter class, I would still need to use quotation marks around the type (like the add method).

2024-03-12 17:46 UTC, ltp23 commented on RUFAS/input_manager.py
> +        return input_data
It's been removed now. I transferred this code to an earlier PR, so I thought it wouldn't duplicate but it did, probably because of the differences in location.

2024-03-12 18:27 UTC, ltp23 commented on RUFAS/input_manager.py
> +        return new_counter
I can remove `decrement()` and `_check_negative_counts()`. I would hold off on removing the class because I like some version of separation of concerns here and the decoupling helps with getting the counts from independent elements more easily, like when adding additional variables to the pool.

2024-03-12 18:40 UTC, ltp23 commented on RUFAS/input_manager.py
> +        input_data : Any
The type still needs to be checked inside the method to make sure it is a list.

2024-03-12 19:41 UTC, ltp23 commented on RUFAS/input_manager.py
> +        Validates an input data element of type object.
I have tried the following and it works: remove the `dict_type_validator()` method, and use `_validate_input_by_type()` method directly in `_populate_pool()` and `_add_variable_to_pool()`. 

I think this approach makes sense because each element will be funneled through the `_validate_input_by_type()` method first and go to the appropriate type validator.

Changing the code is fairly simple, but fixing the broken tests and/or writing new ones in their place takes some non-trivial amount of work and I can't do that right now. So, I will leave that as one of the follow-up housekeeping tasks.

2024-03-12 19:53 UTC, ltp23 commented on RUFAS/input_manager.py
> +        input_data: Dict[str, Any],
I would revisit this point when combining the two `_dict_type_validator()` and `_object_type_validator()`.

2024-03-12 20:15 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        Validates an input data element of type object.
Ok, that sounds like a plan.

2024-03-12 21:19 UTC, Isgotkowitz approved these changes

2024-03-12 21:19 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            The name of the json data element just under the level of properties_blob_key.
```suggestion
            The name of the data element just under the level of properties_blob_key.
```
Two things here:
1. It would be incorrect to say that this is came from a JSON, it isn't known in the context of this function where it came from.
2. Could please reword this description or give some examples? I am not sure what you mean by this.

2024-03-12 21:19 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                    "Validation: array container length less than minimum",
```suggestion
                    "Validation: array length less than minimum",
```
"array container" makes it sounds like it is something that contains arrays.

2024-03-12 21:19 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                    "Validation: array container length greater than maximum",
```suggestion
                    "Validation: array length greater than maximum",
```

2024-03-12 21:19 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +    FIXED = 3
```suggestion
    VALID = "valid"
    INVALID = "invalid"
    FIXED = "fixed"
```
Definitely more redundant, but is clearer.

2024-03-12 21:19 UTC, Isgotkowitz commented on input/metadata/properties/default.json
> +          "minimum": 14,
Where is this number coming from?

2024-03-12 21:19 UTC, Isgotkowitz commented on input/metadata/properties/default.json
> +          "default": 0.0
```suggestion
        },
```
These should be removed from inputs, instead of being allowed in.

2024-03-12 21:19 UTC, Isgotkowitz commented on input/metadata/properties/default.json
> +          "pattern": "^freestall|tiestall|open lot|compost bedded pack barn$",
```suggestion
          "pattern": "^(freestall|tiestall|open lot|compost bedded pack barn)$",
```

2024-03-13 14:12 UTC, JoeWaddell reviewed
Assuming @Isgotkowitz 's remaining comments are addressed prior to merge, this looks good. 

Given the size of this PR I agree with pushing some of the cleanup to Issues #1335 and #1401

2024-03-13 14:12 UTC, JoeWaddell commented on input/metadata/properties/default.json
> +          "minimum": 14,
Looks like from the conflict between the default and the former minimum, but confirmation that one or the other is correct from a SME would be best. I couldn't find it in the Feed design doc, and checking some sources online, 14 kg / m^3 seems low.

2024-03-13 14:12 UTC, JoeWaddell commented on RUFAS/input_manager.py
> +    FIXED = 3
Strings make more intuitive sense to me as well, but for my own edification, is there any benefit in using the existing ints?

2024-03-13 16:30 UTC, ltp23 commented
> Looks like from the conflict between the default and the former minimum, but confirmation that one or the other is correct from a SME would be best. I couldn't find it in the Feed design doc, and checking some sources online, 14 kg / m^3 seems low.

There seems to be a mismatch between the metadata and the input data also. I saw that all the feed json files use 14 so I thought that I would update the metadata. But of course, this can be changed with further confirmation.

---

Update: I changed the default to 200.

2024-03-13 19:56 UTC, ltp23 commented on input/metadata/properties/default.json
> +          "default": 0.0
Ok I will remove these in the metadata and input json files.

2024-03-14 16:12 UTC, JoeWaddell approved these changes
LGTM

2024-03-14 16:58 UTC, merged