Standardizing random draw process
RuminantFarmSystems/RuFaS pull request #135
Opened 2022-04-18 21:27 UTC by manfei-L

Standardizing the random draw process in the animal life cycle with unified functions for drawing random variables between +- 2 standard deviations of each normal distribution.

2022-04-18 21:35 UTC, PooyaHekmati requested changes

2022-04-18 21:35 UTC, PooyaHekmati commented on RUFAS/routines/animal/life_cycle/calf.py
> +        self.mature_body_weight = truncnorm.rvs(-2, 2,\
No hardcoded values please, either use helper variables or use function's args names to add clarity to the code. Also, when passing args to a function in multiple lines, slash is not needed, simply break it into multiple lines after a comma.

2022-04-18 21:35 UTC, PooyaHekmati commented on RUFAS/routines/animal/life_cycle/cow.py
> +        estrus_cycle = truncnorm.rvs(-2, 2, avg, std)
same as above

2022-04-18 21:35 UTC, PooyaHekmati commented on RUFAS/routines/animal/life_cycle/cow.py
> +                self.gestation_length = int(truncnorm.rvs(-2, 2, AnimalBase.config['avg_gestation_len'],\
same

2022-04-18 21:35 UTC, PooyaHekmati commented on RUFAS/routines/animal/life_cycle/cow.py
> +                    self.calf_birth_weight = truncnorm.rvs(-2, 2, \
same

2022-04-18 21:35 UTC, PooyaHekmati commented on RUFAS/routines/animal/life_cycle/cow.py
> +                    self.calf_birth_weight = truncnorm.rvs(-2, 2, \
same

2022-04-18 21:35 UTC, PooyaHekmati commented on RUFAS/routines/animal/life_cycle/heiferII.py
> +        estrus_cycle = truncnorm.rvs(-2, 2, AnimalBase.config['avg_estrus_cycle_heifer'],
same

2022-04-18 21:35 UTC, PooyaHekmati commented on RUFAS/routines/animal/life_cycle/heiferII.py
> +        synch_ed_estrus = truncnorm.rvs(-2, 2, avg, std)
same

2022-04-18 21:35 UTC, PooyaHekmati commented on RUFAS/routines/animal/life_cycle/heiferII.py
> +                    self.calf_birth_weight = truncnorm.rvs(-2, 2, \
same

2022-04-18 21:35 UTC, PooyaHekmati commented on RUFAS/routines/animal/life_cycle/heiferII.py
> +                    self.calf_birth_weight = truncnorm.rvs(-2, 2, \
same

2022-04-18 21:47 UTC, manfei-L commented on RUFAS/routines/animal/life_cycle/calf.py
> +        self.mature_body_weight = truncnorm.rvs(-2, 2,\
-2 and 2 are not hardcoded values but standard deviation indications. I changed the line break positions as you requested.

2022-04-18 21:55 UTC, PooyaHekmati commented on RUFAS/routines/animal/life_cycle/calf.py
> +        self.mature_body_weight = truncnorm.rvs(-2, 2,\
Please see https://www.techtarget.com/whatis/definition/hardcode .
Simply create a variable with a reasonable name such standard_deviation_indication or SDI, set it to 2, and use that variable instead of the explicit value in the code.

2022-04-18 21:56 UTC, PooyaHekmati requested changes
Please fix harcoded values.

2022-04-21 23:29 UTC, PooyaHekmati approved these changes
Nicely done, I have no more comments in terms of code quality. I leave the logic to be validated by our subject matter experts.

2022-04-22 14:13 UTC, KFosterReed commented
This looks good to me! It runs and gets the same outputs as far as I can tell. I like the addition of the standard deviation variables. Great work!

2022-04-22 14:13 UTC, KFosterReed approved these changes

2022-04-23 02:14 UTC, merged