C1f3 crops testing
RuminantFarmSystems/RuFaS pull request #1382
Opened 2024-03-06 17:48 UTC by krb78

This PR is adding the crop rotation jsons for c1f3 (Spruce Haven Farm) to the pilot testing branch 

I don't think there are other issues or PRs related to this. :) 

I don't think I need to update the change log. 

I've added crop rotation, fertilizer schedules, manure schedules, tillage schedules, the field specifications, and updated the metadata file "c1f3_wcrops_metatdata". 

There are two fields. One field starts in corn, the other field starts in alfalfa and they switch back and forth every 4 years between alfalfa and corn. 

Hopefully, this will work and give us our first real farm field level outputs. Fingers crossed it'll also give us some insight into how our purchased feed emission factors stack up to our field level emissions. We will also be able to see if we get reasonable yields and N&P losses from the fields.

2024-03-06 20:02 UTC, Isgotkowitz requested changes
Noticed a couple things looking through these inputs. I think the alfalfa schedule is not set up to do what you want it to do. 
Also, I noticed a lot of files that had almost the same name, but one had "final" tacked on to the end. This is not a great practice, because it is easy to wind up with a lot of files that all have the same information but only is actually usable.

2024-03-06 20:02 UTC, Isgotkowitz commented on input/data/crop/c1f3_alfalfa_corn_rotation.json
>              "harvest_operations": ["harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "har
This harvest schedule is saying that it is going to start harvesting alfalfa a bunch in the years 2000 through 2003, then leave it alive in the ground until 2008-2011, leave it alive again, then harvest it a bunch in 2016-2019 and then kill it.

2024-03-06 20:02 UTC, Isgotkowitz commented on input/data/crop/c1f3_alfalfa_corn_rotation_final.json
> +            "harvest_operations": ["harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "harvest_only", "har
Same thing here as above.

2024-03-06 20:02 UTC, Isgotkowitz commented on input/data/crop/c1f3_alfalfa_corn_rotation.json
Two files that are present are `input/data/crop/c1f3_alfalfa_corn_rotation.json` and `input/data/crop/c1f3_alfalfa_corn_rotation_final.json`, I assume these are the same thing? If so, then only one of them should be kept and it's name should be `input/data/crop/c1f3_alfalfa_corn_rotation.json`.

2024-03-06 20:02 UTC, Isgotkowitz commented on input/data/crop/c1f3_corn_alfalfa_rotation_final.json
Same thing with this file name.

2024-03-06 23:57 UTC, krb78 commented
ok Ed, I think I addressed all of these :) see what you think!

2024-03-07 12:14 UTC, jadamchick approved these changes
I didn't try running it, but the input files look fine to me given Ed's requested changes. Hope it works!

2024-03-07 14:43 UTC, jadamchick commented
Just noticing that on the pilot testing branch, there are 2 metadata files for c1f3 that seem to have crops -- "_metadata_wcrops.json" and "wcrops_metadata.json". Is one of them redundant/outdated and can be deleted?

2024-03-07 20:39 UTC, krb78 commented
c1f3_wcrops_metadata.json is the correct one. The other one can be deleted.

2024-03-11 20:53 UTC, Isgotkowitz approved these changes
I think these inputs look good, they appear to be running all the plantings and harvestings correctly based on the 2014-2022 simulation I looked at. I was trying to run the full 22 year simulation and I keep getting an error with the first alfalfa seeding, but I think that is a separate bug. I'll keep looking into it tomorrow.

2024-03-12 14:50 UTC, merged