Updates calc_pen_requirements() and adds a unit test file.
RuminantFarmSystems/RuFaS pull request #1386
Opened 2024-03-07 08:22 UTC by Fjordrunner

This pull request updates `calc_pen_requirements()` within `animal_requirements.py` to include additional statistics metrics options and overall code quality. It also introduces the `test_animal_requirements.py` test file with two unit tests.

### Context
This pull request is a fix to [Issue 557](https://github.com/RuminantFarmSystems/MASM/issues/557), which requested more statistical metrics options for calculating the animal requirements for a pen. A significant part of this PR was rewriting the function `calc_pen_requirements()` so that it can easily support future statistical metrics without having to copy code.

### What
This function now supports the median as an option for a statistical metric. More importantly, this PR cleans up the function's code so that further statistical metrics can be added in the future as needed. Instead of chaining if-statements, using one if-statement for each statistical metric (with 13 lines of code in each if-clause, pertaining to setting the value of the 13 `AnimalRequirements` class variables), different statistical use cases are handled more efficiently and cleanly.  At this point, unless any immediate changes are suggested, we have included support for the statistical metrics that we deemed the most useful. Additionally, a new test file with unit tests was added.

### Why
Given the weaknesses of each type of statistical metric, such as outliers affecting the mean significantly, we deemed it necessary to add an additional statistical metric option used for calculating the animal requirements for animals in a pen. The median has shown to be a much more "reasonable" metric in finding a good middle ground for pen values. Additionally, the code now allows for future statistical metrics that might be found useful to be integrated seamlessly, in the case that any were to be found more preferable. Lastly, this PR introduces a new test file for `animal_requirements.py`, which was necessary. This test file includes a unit test that checks that an AnimalRequirements object gets initialized correctly.

### Test plan
This PR added two unit tests. The first of these was a unit test that ensure that the initialization of the `AnimalRequirements` class worked properly, which was done by simply checking that all of the class' variables got initialized to what they were expected to be. The second unit test pertained to the `calc_pen_requirements()` function, and was done via parametrization. By using a different list of values for each one of the 13 class variables, for each one of the three supported statistic metrics, test coverage appears to be thorough.

2024-03-07 20:33 UTC, JoeWaddell requested changes
This looks great! Nice job writing a thorough description. Definitely a pythonic way to handle this method, and definitely ready to add in more complex methods once those are developed/decided to be added.

The tests looks solid, I'm just curious how you decided on using three sets of inputs, instead of the same input three  times (with different results). Using the same sets each time might be a better way to show off the method in the unit test, but if it's a pain to generate don't worry about it.

Only changes requested are to handle the linting/format errors, otherwise this looks good to go. There were what look like perhaps extra indentations through a lot of it, and pylint is showing a few misaligned spaces. Looks like different linting setups. In any case, once those are handled just re-request me and I'll approve. Nice job!

2024-03-12 19:55 UTC, Fjordrunner commented
> This looks great! Nice job writing a thorough description. Definitely a pythonic way to handle this method, and definitely ready to add in more complex methods once those are developed/decided to be added.
> 
> The tests looks solid, I'm just curious how you decided on using three sets of inputs, instead of the same input three times (with different results). Using the same sets each time might be a better way to show off the method in the unit test, but if it's a pain to generate don't worry about it.
> 
> Only changes requested are to handle the linting/format errors, otherwise this looks good to go. There were what look like perhaps extra indentations through a lot of it, and pylint is showing a few misaligned spaces. Looks like different linting setups. In any case, once those are handled just re-request me and I'll approve. Nice job!

I ended up using the same set of inputs for the three current statistics methods, done thrice with a different set of numbers each time. I also got my formatter up and running so fingers crossed this PR should now be good to go! Please let me know what you think!

2024-03-13 14:44 UTC, JoeWaddell approved these changes
Looks good, barring a few comments (easy fixes) that need to be addressed before merge.

2024-03-13 14:44 UTC, JoeWaddell commented on tests/animal_module_tests/ration/test_animal_requirements.py
> +def test_calc_pen_requirements(argument_lists: List[List[float]], stat_method: str, expected: List[float]):
This needs return typing e.g. `-> None`

2024-03-13 14:44 UTC, JoeWaddell commented on tests/animal_module_tests/ration/test_animal_requirements.py
> +def test_default_initialization():
Also needs return typing here to avoid Mypy error.

2024-03-13 14:44 UTC, JoeWaddell commented on RUFAS/routines/animal/ration/animal_requirements.py
> +            - (
This is split on two lines, and is causing this equation to give the wrong results, and fails its unit tests.

2024-03-13 14:44 UTC, JoeWaddell commented on RUFAS/routines/animal/ration/animal_requirements.py
> +            self,
Curious why here (and elsewhere in this file) the inputs have been indented an additional time: 
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/82e49335-4b5e-402c-956c-bb8cdd7220c2)

It doesn't elicit any errors on my end, but it deviates from the formatting in other files.

2024-03-20 05:54 UTC, Fjordrunner commented on tests/animal_module_tests/ration/test_animal_requirements.py
> +def test_calc_pen_requirements(argument_lists: List[List[float]], stat_method: str, expected: List[float]):
Thanks for catching this, I shouldn't have let this go through the first time around. My bad!

2024-03-20 05:55 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/animal_requirements.py
> +            - (
I think the issue should be fixed now. I ended up simply copying the format from the main branch and it seemed to work.

2024-03-20 05:56 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/animal_requirements.py
> +            self,
I have no idea why the deviation from our typical formatting occurred but I think this should be fixed now, at least regarding the function parameter indentation.

2024-03-20 12:44 UTC, matthew7838 approved these changes
Great work and solid tests, minor comments.

2024-03-20 12:44 UTC, matthew7838 commented on tests/animal_module_tests/ration/test_animal_requirements.py
> +    """
Need an extra line at the end of the docstring.
```suggestion
    any parameters, all its attributes are correctly set to their default values.

    """
```

2024-03-20 12:44 UTC, matthew7838 commented on tests/animal_module_tests/ration/test_animal_requirements.py
> +    """
same

2024-03-20 20:40 UTC, Fjordrunner commented on tests/animal_module_tests/ration/test_animal_requirements.py
> +    """
Fixed.

2024-03-20 20:40 UTC, Fjordrunner commented on tests/animal_module_tests/ration/test_animal_requirements.py
> +    """
Fixed. Thanks for pointing this out!

2024-03-20 20:41 UTC, merged