Sequential v2
RuminantFarmSystems/RuFaS pull request #141
Opened 2022-05-26 19:27 UTC by rhensen

This PR reaches the first version of many of the v1 soil and crop objectives: 

Management practices:

- Crop types - corn (grain and silage), alfalfa, grass (tall fescue_, soybeans, winter wheat, winter rye, triticale
- Cover cropping
- No-till vs. tillage vs. conservation tillage
- Manure and fertilizer application - surface, incorporation, injections

Outcomes: 

- N2O, NH3, and CO2 Emissions
- N & P Leaching and Runoff
- Water use
- Soil C
- Crop yields and compositions

In addition, unit tests are provided for some of the recent changes. We hope to add more of these in the future.

2022-05-26 19:27 UTC, rhensen commented on RUFAS/routines/field/field_management/field_management.py
> +                'percent_manure_incorporated': 0.8, #need to check this one out and potentially change to nutrient
percent_nutrient_incorporated
percent_nutrient_mixed

2022-06-07 03:54 UTC, PooyaHekmati reviewed
I made these comments as a partial review to unblock this PR. Will get back to it and add more soon.

2022-06-07 03:54 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/field_report.py
> +                                        'AG_met_layer0': ['soil.soil_layers[0].AG_met', '%', []],
There are two levels of repetition here, both can be mitigated using zip() and lambda functions with some loops. Also, to add clarity, this big dict structure initialization should be wrapped in a function with an adequately intuitive name.

2022-06-07 03:54 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/field_report.py
> +                                            'soil.soil_layers[3].C_passive_decomp', '%', []]                                        }
misplaced curly brace

2022-06-07 03:54 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +from .crop_types import base_crop, alfalfa, corn, soybean, tall_fescue, spring_barley, potato, sugar_beet, spring_wheat,\
Line too long, please see https://peps.python.org/pep-0008/#maximum-line-length

2022-06-07 03:54 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +    # If there is no crop in rotation, current crop will be named
there are no if conditions next to this comment, how is this decision being made?

2022-06-07 03:54 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +        #if the crop was killed the previous day, set the new crop
remove comment by something like this:
crop_was_killed_yesterday = crop_type.killed
if crop_was_killed_yesterday:

2022-06-07 03:54 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +            if crop_type.harvest_day > crop_type.planting_day:
can we wrap this in a function and call it set_next_crop or something like that?

2022-06-07 03:54 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +                        crop.current_crop = crop.current_crop_year[1]
unclear and unexplained hardcoded value, what is the significance of 1? what happens if we change it to 0?

2022-06-07 03:54 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +            # current crop year will be this years current crop while the current crop
vague and unclear comment

2022-06-07 03:54 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +        # If the crop is not planted yet, determine whether it is planted today
unnecessary comment

2022-06-07 03:54 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +        # Once the crop is planted:
unnecessary and probably misleading comment. if crop_type.planted is true, how do we know it has been just planted? Moreover, can a type of crop really be planted? A crop can be planted, the type is describing it. A type is not plantable, a crop is.

2022-06-07 03:54 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
>              # If the crop is growing, run the routines
unnecessary comment

2022-06-15 21:21 UTC, HectorMM3 requested changes
Reid, only small comments. I would proceed, and we can follow up on the details later.

2022-06-15 21:21 UTC, HectorMM3 commented on RUFAS/output_handler/reports/field_report.py
> +                                                 'M_DRP_runoff': ['soil.M_DRP_runoff_annual', 'kg', 0],
Why is M_DRP_runoff tabbed over? Does it need to be?

2022-06-15 21:21 UTC, HectorMM3 commented on RUFAS/routines/field/crop/crop.py
> +            if crop_type.harvest_day > crop_type.planting_day:
Pooya, I think we want to leave it as is for now because we can going to make version 3 more complex at that time we will attempt to put it in a function.

2022-06-15 21:21 UTC, HectorMM3 commented on RUFAS/routines/field/crop/crop.py
> +    #crop_type.bio_BG = 0
Did we comment this out to avoid the error in carbon? I think we still need this variable as an output.

2022-06-15 21:21 UTC, HectorMM3 commented on RUFAS/routines/field/crop/crop.py
> +                        # if the crop is cold, set it to the latter year slot, if it is warm or
#replace comment with "if the crop is grown in the fall or winter then it gets placed later in the year if it is a "warm #season" -planted and grown during spring and summer or null then put it belongs in the initial year slot."

2022-06-15 21:21 UTC, HectorMM3 commented on RUFAS/routines/field/crop/crop.py
> +        # list(filter(lambda crop: crop.crop_name != 'null', self.grow_regimen))
why is it commented out?

2022-06-15 21:21 UTC, HectorMM3 commented on RUFAS/routines/field/crop/crop_types/spring_wheat.py
> +        self.fix_nitrogen = False  # TODO: change back
please delete "# TODO: change back" it should not be changed back spring wheat does not fix nitrogen so the False value is correct.

2022-06-15 21:21 UTC, HectorMM3 commented on RUFAS/routines/field/field_management/manure_application.py
> +        N_frac = 1 if N_frac == 0 else N_frac #TODO: this is an adjustment feature that is availabe if the manure input where total manure, not the exact values.
add in 0.05 and 0.06 into the comments so we can have them for later.

2022-06-15 21:21 UTC, HectorMM3 commented on RUFAS/routines/field/soil/carbon_cycling/residue_partitioning.py
> +    return (layer_thickness / soil_profile_depth) * crop_type_bio_BG
I see a weird red symbol at the end of line 146.

2022-06-15 23:38 UTC, PooyaHekmati requested changes

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +            if crop_type.harvest_day > crop_type.planting_day:
In this case, we should create a git issue for it and add it here as TODO

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +    # If there is no crop in rotation, current crop will be named
A reviewer's comment needs to be addressed either as changes in the code or as a conversation on why the comment was wrong or not applicable. Just marking the comment resolved is not helpful.

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +    crop.current_crop_year = crop.grow_regimen[time.year - 1]
where is this -1 coming from?

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +    # the following code checks if the crop is annually grown,
what about moving these comments to docstrings which ended two lines above?

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +    if crop.current_crop.crop_type == 'annual' or len(crop.grow_regimen) == time.year or \
readability can be enhanced by moving len(crop.grow_regimen) == time.year or to next line, so each line checks one condition

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +        # default setting
Please add a verb such as loading, setting, etc.

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +        double_cropping_limit = 2
avoid hardcoding by changing to 
double_cropping_limit_default_value = 2
double_cropping_limit = double_cropping_limit_default_value

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop.py
> +                        # if the crop is cold, set it to the latter year slot, if it is warm or
how is this if statement being executed? where is the decision being made?

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        """GENERAL PLANT INFO"""
Invalid format for docstrings

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.T_base_max = 30  # TODO
Add details to TODO

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.PHU = 996  # TODO
Add details to TODO

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.fr_PHU_harvest = 1.2  # TODO
Add details to TODO

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.fr_PHU_1 = 0.15
Please add reference for these values (a link to a document which explains these)

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.kl = 0.65  # TODO
Add details to TODO

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.epco = 0.5  # TODO
Add details to TODO

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.fr_n3ish = 0.01301  # TODO
Add details to TODO

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.fr_p3ish = 0.00191  # TODO
Add details to TODO

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.biomass_dry_down_percent = 0.0  # TODO: Hard coded total dry down until daily method is modeled
make git issue and mention it here

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.DM_harvest_percent = 0.0001  # TODO: Hard coded dry matter percent at harvest
make git issue and put it here

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/soybean.py
> +        self.beta_w = 10  # water-use distribution parameter
this explanation should be inside docstrings

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/crop/crop_types/triticale.py
> +        """GENERAL PLANT INFO"""
invalid format for docstring

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/soil/carbon_cycling/residue_partitioning.py
> +            residue_incorp = layer.tillage_percent * 0
what about residue_incorp = 0 ?

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/soil/carbon_cycling/residue_partitioning.py
> +    return (layer_thickness / soil_profile_depth) * crop_type_bio_BG
That shows that this is the end of the file (EOF) and no new lines are after this point.

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/soil/soil.py
> +        # self.practice_factor = data['practice_factor']
why is this commented out?

2022-06-15 23:38 UTC, PooyaHekmati commented on RUFAS/routines/field/soil/soil_erosion.py
> +    #P = soil.practice_factor
why is this commented out?

2022-06-15 23:38 UTC, PooyaHekmati commented on config/defintions.py
> +ROOT_DIR = os.path.realpath(os.path.join(os.path.dirname(__file__), '..'))
why is this needed? where is it used?

2022-06-15 23:52 UTC, PooyaHekmati commented
There are a bunch of TODOs in this PR, I commented on some of them but gave up on commenting on them all. A TODO is not desired, it is only acceptable when a git issue is created for it and it is mentioned in front of the TODO. Also, there are a bunch of docstrings with invalid formats. More importantly, this PR is heavily missing unit tests.

2022-07-14 17:29 UTC, KFosterReed commented
I tried to run this and got a Key Error for the alfalfa 'extracted' input. It looks like you added this input variable to the alfalfa crop but it isn't added to all the crop jsons. Here is the full error report:

 

          > Initializing simulation environment from input\ARL.json
          > Traceback (most recent call last):
          >   File "C:\Users\kfr3\PycharmProjects\MASM\main.py", line 25, in <module>
          >     main()
          >   File "C:\Users\kfr3\PycharmProjects\MASM\main.py", line 20, in main
          >     simulator = SimulationEngine(input_file_path)
          >   File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\simulation_engine.py", line 23, in __init__
          >     self._initialize_simulation(input_file_path)
          >   File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\simulation_engine.py", line 153, in _initialize_simulation
          >     self.state = State(data['farm'], self.config,
          >   File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\classes.py", line 46, in __init__
          >     self.fields = Fields(data['fields'], time)
          >   File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\routines\field\field.py", line 45, in __init__
          >     self.fields[field_name] = Field(field_name, field_data, time)
          >   File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\routines\field\field.py", line 225, in __init__
          >     self.crop = Crop(crop_data, time)
          >   File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\routines\field\crop\crop.py", line 263, in __init__
          >     crop = alfalfa.Alfalfa(crop_name, crop_data)
          >   File "C:\Users\kfr3\PycharmProjects\MASM\RUFAS\routines\field\crop\crop_types\alfalfa.py", line 34, in __init__
          >     self.extracted = alfalfa_data['extracted']
          > KeyError: 'extracted'
          > 
          > Process finished with exit code 1
  
I got a similar key error for a tillage attribute of soil

2022-07-14 21:40 UTC, KFosterReed commented on RUFAS/routines/field/soil/soil.py
> +        # self.practice_factor = data['practice_factor']
I think this is supposed to be deleted. Is that correct?

2022-07-14 21:41 UTC, KFosterReed commented on RUFAS/routines/field/soil/soil_erosion.py
> +    #P = soil.practice_factor
Same as the other practice factor. Please delete all references

2022-07-14 21:43 UTC, KFosterReed commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        """GENERAL PLANT INFO"""
I think we should make a GIT issue to reformat the documentation in all crop types. They are all following this same style of in code documentation so let's change them all at one time and not let that hold up this pull request

2022-07-14 21:45 UTC, KFosterReed commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.T_base_max = 30  # TODO
Ideally they are GIT issues but let's at least have information about what the TODOs mean somewhere. As Pooya mentioned in the meeting, they can be in a google doc, written here in the comment or made into a git issue but I agree that we don't want to pull in even more cryptic TODOs than we already have

2022-07-14 21:45 UTC, KFosterReed commented on RUFAS/routines/field/crop/crop_types/cereal_rye.py
> +        self.fr_PHU_1 = 0.15
If the reference values are provided in the pseudocode documentation then values like this are OK for now

2022-07-14 22:02 UTC, KFosterReed commented on RUFAS/routines/field/soil/carbon_cycling/residue_partitioning.py
> +            residue_incorp = layer.tillage_percent * 0
this makes sense to me!

2022-07-14 22:02 UTC, KFosterReed commented on config/defintions.py
> +ROOT_DIR = os.path.realpath(os.path.join(os.path.dirname(__file__), '..'))
Also curious...

2022-07-19 16:13 UTC, KFosterReed commented on RUFAS/output_handler/reports/field_report.py
> +                                        'AG_met_layer0': ['soil.soil_layers[0].AG_met', '%', []],
I think we should make a GitIssue for updating the output handlers in general and leave this as is for this pull request

2022-07-19 16:41 UTC, KFosterReed requested changes
This seems very close to me but there are a few things that need to be done before we can merge it in: 
1) The logic of how the crop rotations are managed needs to be more clear. That is the heart of the new functionality and it is very difficult to follow. Whether it is with external documentation, updates to the in code documentation, or changes to the code itself does not matter to me. 
2) Please create git issues that group opportunities for improving the code clarity and 'cleanness' and add TODOs where identified
3) The model needs to run on all .json files

2022-07-19 16:41 UTC, KFosterReed commented on RUFAS/routines/field/crop/crop.py
> +            if crop_type.harvest_day > crop_type.planting_day:
It will be good to translate these crop management functionalities into functions but I agree with Hector that the higher priority is to pull this into the master branch

2022-07-19 16:41 UTC, KFosterReed commented on RUFAS/routines/field/crop/crop.py
> +                        crop.current_crop = crop.current_crop_year[1]
I also find the logic here and below hard to follow for most of the daily_reset() function. Providing pseudocode (and possibly a diagram?) would be super helpful

2022-07-19 16:41 UTC, KFosterReed commented on RUFAS/routines/field/crop/crop.py
> +    crop.current_crop_year = crop.grow_regimen[time.year - 1]
I am also confused about the logic here. It would be helpful to have the variables used here defined in the Sphinx documentation above & in the pseudocode (or at least one or the other).

2022-07-19 16:41 UTC, KFosterReed commented on RUFAS/routines/field/crop/crop.py
> +    # the following code checks if the crop is annually grown,
There are several places like this where the code can be improved for readability. I think tagging them with a TODO and linking them into a single GITissue would be great

2022-09-30 20:23 UTC, KFosterReed commented
@rhensen I am guessing the new PR replaces this one? If so, can we close this one?

2022-09-30 20:33 UTC, closed without merging