C1f2 crop testing
RuminantFarmSystems/RuFaS pull request #1420
Opened 2024-03-18 13:24 UTC by krb78

SunnyDene (c1f2) crop and soil jsons

### Context
This enables the cropped acres of c1f2 to be simulated in RuFaS. 

The change log doesn't need to be updated. 

### What
The same crop rotation exists on all fields of this farm, but to capture fields in each part of the rotation, there are 3 "fields" simulated: alfalfa, corn/triticale double crop, and wheat. No fertilizer is applied to the fields, only manure. 

Hopefully, you'll find that this simulation runs and plants/harvests crops. Fair warning, it takes A WHILE.

2024-03-18 13:31 UTC, jadamchick approved these changes
looks good

2024-03-18 15:04 UTC, Isgotkowitz requested changes
The metadata doesn't include the new field files in the "files" section, so the Crop and Soil module isn't simulating anything right now. After that is corrected, the field input files need to add a specification for the fertilizer applications, even though none is actually applied. There is a more detailed comment on this below.

2024-03-18 15:04 UTC, Isgotkowitz commented on input/data/manure_schedule/c1f2_alfalfa_2020_manure_schedule.json
> +    "days": [155, 277, 420, 155, 277, 420, 155, 277, 420, 120, 274, 120, 274, 120, 274 , 60],
There is not a 420th day of the year.

2024-03-18 15:04 UTC, Isgotkowitz commented on input/data/manure_schedule/c1f2_corn_2020_manure_schedule.json
> +    "days": [155, 277, 420, 155, 277, 420, 155, 277, 420, 120, 274, 120, 274, 120, 274 , 60],
Same as above

2024-03-18 15:04 UTC, Isgotkowitz commented on input/data/manure_schedule/c1f2_wheat_2020_manure_schedule.json
> +    "days": [155, 277, 420, 155, 277, 420, 155, 277, 420, 120, 274, 120, 274, 120, 274 , 60],
Same as above

2024-03-18 15:04 UTC, Isgotkowitz commented on input/metadata/c1f2_wcrops_metadata.json
> +    },
All of these inputs are outside of the "files" object, so RuFaS isn't seeing them at all.

2024-03-18 15:04 UTC, Isgotkowitz commented on input/data/field/c1f2_alfalfa_2020_field.json
> +  "field_size": 540,
```suggestion
  "fertilizer_management_specification": "no_fert",
  "field_size": 540,
```
Even if there is not going to be any fertilizer applied, that still has to be specified. The above line can be added to each new field input file, and the following input added to the "files" section of the metadata:
```json
    "no_fert": {
      "title": "Fertilizer schedule.",
      "description": "No fertilizer is scheduled to be used.",
      "path": "input/data/fertilizer_schedule/no_fertilizer.json",
      "type": "json",
      "properties": "fertilizer_schedule_properties"
    },
```

2024-03-18 15:04 UTC, Isgotkowitz commented on input/data/field/c1f2_corn_2020_field.json
Same as above

2024-03-18 15:04 UTC, Isgotkowitz commented on input/data/field/c1f2_wheat_2020_field.json
Same as above

2024-03-18 16:14 UTC, krb78 commented on input/data/manure_schedule/c1f2_alfalfa_2020_manure_schedule.json
> +    "days": [155, 277, 420, 155, 277, 420, 155, 277, 420, 120, 274, 120, 274, 120, 274 , 60],
wait, what? I thought that's what leap year was about?!

2024-03-19 13:12 UTC, Isgotkowitz requested changes

2024-03-19 13:12 UTC, Isgotkowitz commented on input/data/crop/c1f2_corn_2020_rotation.json
> +            "harvest_years": [2001, 2001, 2001, 2001, 2001, 2001, 2002, 2002, 2002, 2002, 2000, 2002, 2003, 2003, 2003, 2003, 2003, 2003, 2004],
The harvest years need to be in ascending order

2024-03-20 14:16 UTC, Isgotkowitz approved these changes
LGTM, nice job Kaitlyn. I ran this sim and it plants and harvests everything correctly (I believe). Before merging, I think the following files may need to be reverted to their original state: `scenario_manager.py`, `default_animal.json`, and `c1f2_config.json`. Also the weather in the C1F2 metadata might need to be changed back to the C1F2 weather file.

When

2024-03-20 14:16 UTC, Isgotkowitz commented on input/data/crop/c1f2_alfalfa_2020_rotation.json
> +            "harvesting_skip": 6,
```suggestion
            "harvesting_skip": 3,
```
I think this should only be three. Reason being that the final harvest is in 2001, and harvests should start again in 2005 (after it is planted the year before) - so skip 2002, 2003, 2004.

2024-03-20 14:16 UTC, Isgotkowitz commented on input/data/crop/c1f2_corn_2020_rotation.json
> +            "harvesting_skip": 6,
Same as above

2024-03-20 14:16 UTC, Isgotkowitz commented on input/data/crop/c1f2_wheat_2020_rotation.json
> +            "harvesting_skip": 6,
Same as above

2024-03-20 14:28 UTC, merged