Optionally auto-include simulation day to info map when adding variable to OM pool
RuminantFarmSystems/RuFaS pull request #1428
Opened 2024-03-19 20:58 UTC by ltp23

This PR adds an option in the config json to enable the auto-inclusion of the current simulation day in the info map when the OM's `add_variable()` method is called.

### Context

Issue(s) closed by this pull request: closes #

- [ ] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What & Why

To address the two issues #912 and #1366 more effectively, I think it is helpful or even necessary to associate each value added to the output manager with its corresponding simulation day. 

Currently in the `graph_generator.py` when you plot a variable (a time-series), the `_draw_graph()` method at line `361` (`plot_function(value)`) assumes the x-axis to be the indices of the value series, which is a happy coincidence that it matches the concept of simulation day in RuFaS. 

Also, the list of matplotlib plot functions in `MATPLOTLIB_PLOT_FUNCTIONS` is not all working because some of them require a supply of both x- and y-series.

### How

I don't have all the steps laid out yet to solve the two issues listed above, but I think this PR is a good first step to at least get a hold of the time data needed to pair up with the corresponding value data.

I added a flag in the `default_config.json` to turn on/off this auto-inclusion feature: `"auto_generate_simulation_day": false`.

If the info map already has the simulation day in it, then that will take precedence over the autogenerated one.

In order to synchronize the time in the simulation engine with that in the output manager, I give the output manager a very simple callback function from the simulation engine so that the OM can retrieve the current simulation day when needed. The detail of the callback may need to be modified a bit later when the `Time` class is refactored so that one place is responsible for keeping track of the simulation day. 

### Test plan

- You can try to turn on and off the config flag.
- Pick a variable that doesn't have a simulation day in its info map and check out the results.

2024-03-21 13:26 UTC, Isgotkowitz requested changes
I think this is an excellent start towards addressing #912 and #1366. I am requesting changes on only one thing: the change to the `add_variable()` does not appear to be tested. Once that gets fixed, I can come back and approve.

I have also left a bunch of other comments with suggestions, but address or ignore them as you see fit.

2024-03-21 13:26 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +        """
```suggestion
        
        """
```

2024-03-21 13:26 UTC, Isgotkowitz commented on RUFAS/simulation_engine.py
> +            om.set_get_simulation_day_callback(lambda: self.day_counter)
Instead of using the day counter in `SimulationEngine` to track the time, what about using the `index` in the `Time` class? Even though the name is worse, they track the same thing, and it would be beneficial because it moves us closer to realizing `Time` as the single source of truth for tracking time in RuFaS simulations/

2024-03-21 13:26 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            If present, overrides any autogenerated simulation day
```suggestion
            If present, overrides any autogenerated simulation day

```

2024-03-21 13:26 UTC, Isgotkowitz commented on input/data/config/default_config.json
> +    "auto_generate_simulation_day": false
Instead of adding to the inputs about whether or not this should be added, maybe it would be better to always record the day in the info maps and make it optional to use when generating a graph or report?

2024-03-21 13:26 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            self._get_simulation_day_callback: Callable[[], int] | None = None
I think this attribute should be reset in the method `flush_pools`, just to make the code a bit more robust.

2024-03-21 13:26 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +    def set_get_simulation_day_callback(self, callback: Callable[[], int] | None) -> None:
Instead of passing a function in that gets the simulation day, what about just making Time an attribute of `OutputManager` that is passed by Simulation Engine at the beginning of a simulation? Then the index can just be read out of the Time class. IMO this would be simpler than using lambda expressions.

2024-03-21 13:26 UTC, Isgotkowitz commented on input/metadata/properties/default.json
> +        "default": false
I think this should default to true instead.

2024-03-21 13:26 UTC, Isgotkowitz commented on tests/test_output_manager.py
> +
The changes to `add_variable()` still need to be tested.

2024-03-26 20:18 UTC, PooyaHekmati commented
This PR is only about the tech part of the code and does not involve any logic related to the animal module or other sciency things, therefore unassigning @JoeWaddell as a reviewer. Such PRs should not concern SMEs.

2024-05-15 15:30 UTC, ltp23 commented
Closed because this feature is not needed.

2024-05-15 15:30 UTC, closed without merging