Adding option to include time in graphs and reports
RuminantFarmSystems/RuFaS pull request #1438
Opened 2024-03-21 16:45 UTC by ltp23

### Context

Issue(s) closed by this pull request: closes #
May close #912 
Hopefully this PR partially addresses issue #1366 

- [ ] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What

This PR does two main things:
- Allows time formatting in the x-axis if there is simulation days data associated with the reported variable.
- Allows the addition of an index/simulation day column next to each data column.

### Why

It is helpful at times to have the time context for the report data.

### How

We have been making an implicit assumption about the x-axis to represent simulation days because in the GG we only pass in the data with no information about time.  The next step here would be to create a separate list of day values to be passed along with the data. 

1. In config files, like `default_config.json`, two new properties are added:
    a. `"time_format_string": "%m/%d/%y"` (e.g., 01/01/24). There are other possibilities.
    b. `"add_formatted_time": true`  (Default is `false`): This would add a property in the info maps `"formatted_time": "01/01/24"`
2. In graph filter files, two new options are added:
    a. `"time_step_unit": "day"`. Pick one from `"day", "month", or "year"`.
    b. `"time_step_value": 365`. If `"year"` is selected above, then this property should be left out. 
3. In report filter files, a new option is added: `"indexing": true` (Default is `false` and can be left out).
    - This would add either an index column (0, 1, 2, …) or a date column (09/01/09, 09/02/09, …) next to each data column.
4. The complicating factor in this PR is when the property `"graph_and_report": true` is present in a report filter file. This allows the generation of both graphs and reports at the same time, and the capabilities of both the graph and report generators still need to be preserved.
5. To summarize, anything related to actual dates (like those on the x-axis in graphs and date indexing in the reports), the following are required:
    1. `simulation_day` property in the info maps for the reported variable.
    2. `1b` is `true`, i.e., `"add_formatted_time": true` 
    3. `Item 2`, or `Item 3`, or both.

### Test plan

1. Check that the existing functionalities of the graph and report generators are unaffected.
2. I have tested the following plot functions: `plot`, `scatter`, `stackplot`. I will write a separate issue to do more reading on how to add more options.

For making graphs

```
{
  "multiple": [
    {
      "type": "plot",
      "filters": [
        "AnimalManager._record_animal_counts.num_animals",
        "AnimalManager._record_animal_counts.num_heiferIIs",
        "AnimalManager._record_animal_counts.num_lactating_cows"
      ],
      "title": "Daily Herd Structure"
    },
    {
      "type": "plot",
      "filters": [
        "AnimalModuleReporter.report_life_cycle_manager_data.cull_reason_stats"
      ],
      "variables": [
        "culled for death",
        "culled for low production"
      ],
      "title": "Cull Reasons"
    },
    {
      "type": "scatter",
      "filters": [
        "AnimalModuleReporter.report_ration_interval_data.ration_per_animal_for_pen_0_CALF"
      ],
      "title": "Ration Per Animal",
      "variables": [
        ".*"
      ],
      "time_step_unit": "day",
      "time_step_value": 365
    },
    {
      "type": "stackplot",
      "filters": [
        "AnimalModuleReporter.report_milk.milk_data_at_milk_update"
      ],
      "variables": [
        "milk_lactose",
        "milk_protein",
        "milk_fat"
      ],
      "title": "Daily Milk Nutritions",
      "legend": [
        "lactose",
        "fat",
        "protein"
      ]
    }
  ]
}
```

For making reports.

```
{
  "multiple": [
    {
      "name": "Daily Herd Structure",
      "filters": [
        "AnimalManager._record_animal_counts.num_animals",
        "AnimalManager._record_animal_counts.num_heiferIIs",
        "AnimalManager._record_animal_counts.num_lactating_cows"
      ],
      "indexing": true,
      "graph_and_report": true,
      "graph_details": {
        "type": "plot"
      }
    },
    {
      "name": "Ration Per Animal Graph and Report",
      "filters": [
        "AnimalModuleReporter.report_ration_interval_data.ration_per_animal_for_pen_0_CALF",
        "AnimalModuleReporter.report_ration_interval_data.ration_per_animal_for_pen_1_GROWING"
      ],
      "variables": [
        "202",
        "44",
        "dry_matter_intake_total"
      ],
      "indexing": true,
      "graph_and_report": true,
      "graph_details": {
        "type": "scatter",
        "time_step_unit": "day",
        "time_step_value": 365
      }
    }
  ]
}
```

### Follow-up issues

- Let the output manager handle all the filtering of data. This should help with the decoupling of the graph generator from the report generator when using the `graph_and_report` feature. #1458

2024-03-26 20:20 UTC, PooyaHekmati commented
Similar to #1428, this PR needs two reviews from SWEs before getting merged.

2024-03-28 13:39 UTC, jadamchick approved these changes
From a report-user perspective, this looks good to me and produces the specified graphs/reports without seeming to disrupt any of my already-established reports. I definitely see how this could be helpful, though I don't have an immediate use case for it. 
It would be great to have this added to the wiki once it is finalized and merged.

2024-03-28 20:09 UTC, Isgotkowitz requested changes
> 5. To summarize, anything related to actual dates (like those on the x-axis in graphs and date indexing in the reports), the following are required:
          i. simulation_day property in the info maps for the reported variable.

So in order to know the time of something that is recorded, it has to be manually added into the info map? Is this why none of the graphs or reports given as examples report time?

Also this PR is too large, please consider reducing its size.

2024-03-29 15:13 UTC, ltp23 commented
> So in order to know the time of something that is recorded, it has to be manually added into the info map? Is this why none of the graphs or reports given as examples report time?

Yes, the simulation days info needs to be manually added for them to be converted to dates. It is too much to assume that each variable has something to do with simulation days. 

The examples that have the time settings should show the dates, whereas the ones without should have the same results as before, zero-based indexing.

> Also this PR is too large, please consider reducing its size.

I can postpone this work till a later time when the output manager, graph, and report generators are more decoupled and maintainable. A fair bit of work has to be done to untangle things so that the new additions don't break the existing functionalities.

2024-03-29 19:45 UTC, JoeWaddell commented
While the provided graph/report filters worked (nice job!), this more complicated case I've tried is failing: 
![image](https://github.com/RuminantFarmSystems/MASM/assets/109082924/cef15e1a-f630-4836-8a95-d9245b4b6fc4)

Note: the figure title is different because I've generated it using a separate filter that is identical to the one I've presented here, except the `name` field, and that it doesn't include the new `time_step_unit` or `time_step_value` fields

Also note: I modified the call to output manager to include `simulation_day` in the info_map, as can be seen in the variables file on the left. It just gets lost when converting to a report and graphing from there.

One major problem with this example: there are repeated variable names (feed IDs that overlap in some but not all pens, in this case) *and* dates (which causes weird graphical offsets, as in the provided graph). This may be beyond the scope of what is necessary in graph generator, and almost certainly beyond this PR: I just wanted to bring it up as a potential complicating factor.

2025-02-13 19:51 UTC, ew3361zh commented
the two issues mentioned in this PR are both successfully closed and this PR is nearly a year old.

2025-02-13 19:51 UTC, closed without merging