removing report_ration calls
RuminantFarmSystems/RuFaS pull request #1446
Opened 2024-03-25 17:43 UTC by JoeWaddell

### Context

Issue(s) closed by this pull request: Won't close #1436, but should help.

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
- [x] `default_animal.json` has been reverted to default

### What

The number of calls to RationReporter.report_ration is reduced in this PR. Instead, we're accessing Pen attributes that store the information calculated by report_ration.

### Why

RationReporter.report_ration shouldn't be called so many times. The method itself can of course be improved (it's old by RuFaS standards, so it's not terribly pythonic) to speed things up, but the information from that call is saved as pen attributes (pen.ration_nutrient_amount and pen.ration_nutrient_conc), so it shouldn't need to be called again in calf_manure_excretion/dry_cow_manure_excretion/growing_cow_manure_excretion/lactating_cow_manure_excretion.

### How

In addition to removing calls to RationReporter.report_ration in various manure calculations, also added type hints and updated docstrings as appropriate, to reduce Mypy errors. Also updated unit tests accordingly.

### Test plan

This change seems to have cut the time to run a 10X default herd simulation (e.g. all default metadata settings, except multiplying the number of animals by 10) from 952s to 498s. I haven't noted any differences in the manure outputs, but more testing may be needed. 

### 

### Other Issues
This will complete much of #1218 and #1219 , as it removes the need for a `Feed` object and `ration_formulation`.

### Ongoing problems to try to fix during review
Challenging Mypy errors: 
1) In the file Pen.py, in `_calc_animal_manure_excretion`, it gives a complex error for the call to `calc_manure_excretion`, because there is a separate method for each animal class, and for lactating cows there are more input args required than for other classes. This flags a Mypy error where there are too many calls for Calf/HeiferI-III objects, but too few for cows. This logic is handled by `_calc_animal_manure_excretion`, where the animal object is routed to the correct call setup, but Mypy flags it anyway.
Question: Should this method be A) refactored in this PR, B) should I open an Issue, or C) this Mypy error should be flagged to be ignored?

2) The method `calc_manure_excretion` in Cow.py gives the following error: Signature of "calc_manure_excretion" incompatible with supertype "HeiferIII"Mypy[override](https://mypy.readthedocs.io/en/latest/_refs.html#code-override)
Question: Should this error be officially ignored (e.g. flagging it in the code) while any changes to Animal objects (specifically related to inheritance) are made, or should we simply informally ignore it (e.g. allow the error, and open an Issue)?

2024-04-02 16:38 UTC, ew3361zh approved these changes
LGTM! Time on main running the default scenario was reduced by almost 25% running the same scenario on this branch!

This ran successfully on all other metadatas.

There were a number of updates to the docstrings and I added some comments/suggestions there but nothing vital that would prevent this being merged. Nice work!

2024-04-02 16:38 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/calf.py
> +            Amount of nutrients in pen ration, calculated per animal.
Is there a unit for this?

2024-04-02 16:38 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/calf.py
> +            Concentration of nutrients in pen ration, calculated per animal.
Unit?

2024-04-02 16:38 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/cow.py
> +            Amount of methane mitigation additive, mg/kg dry matter intake (DMI).
```suggestion
            Amount of methane mitigation additive per kg dry matter intake (DMI) (mg/kg).
```

2024-04-02 16:38 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/cow.py
> +            Metabolizable energy intake, Mcal/kg DM
```suggestion
            Metabolizable energy intake per kg DMI (Mcal/kg).
```

2024-04-02 16:38 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/cow.py
> +            Amount of nutrients in pen ration, calculated per animal.
Unit?

2024-04-02 16:38 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/cow.py
> +            Concentration of nutrients in pen ration, calculated per animal.
Unit?

2024-04-02 16:38 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/heiferI.py
> +            Amount of nutrients in pen ration, calculated per animal.
Unit?

2024-04-02 16:38 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/heiferI.py
> +            Concentration of nutrients in pen ration, calculated per animal.
Unit?

2024-04-02 16:38 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/heiferI.py
> +            The Dry Matter Intake (kg)
```suggestion
            The Dry Matter Intake (kg).
```

2024-04-02 16:38 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/heiferI.py
> +            The second stage of heifer -- breeding stage starts.
I like what you had for the same boolean for heiferIIIs moving to cows. Something along the lines of:

```suggestion
            True if should be moved to second stage of heifer -- breeding stage start.
```

2024-04-04 15:52 UTC, tomhuhh requested changes
Great work Joe! Sorry for the delay in my review. 

I think this is a great use of existing resources in the code to make the simulation process more efficient. I'm also amazed by your efforts towards bringing the code documentation up to standard. 

I tested with manure management scenario 6 to check the manure collected by the manure handler and reception pit to see if it is in alignment with a run (with the same animal input file) that I made early today on a different branch so to verify if the manure output still remains the same after the updates proposed. The results look promising. 

On an irrelevant topic, I made some minor suggestions to the doc string updates that are included in this PR. I noticed that Niko has made some nice suggestions too in terms of the doc string. I believe we can easily address them here. 

Lastly, I would appreciate some SWE's expertise on the questions/concerns Joe brought up in the 'Ongoing problems' section of the PR description. 

Thanks!

2024-04-04 15:52 UTC, tomhuhh commented on RUFAS/routines/animal/animal_module_constants.py
>      """Minimum daily growth for heifers, kg."""
Great efforts on updating the doc string for animal module constants! 

Minor suggestion: Consider adding 'daily' into the variable name? For example, 'MINIMUM_HEIFER_DAILY_GROWTH_RATE'. Also the unit should be kg/day to more precisely reflect the meaning of the variable.

2024-04-04 15:52 UTC, tomhuhh commented on RUFAS/routines/animal/animal_module_constants.py
>      """Minimum estimated DMI (kg/day), as a percentage of body_weight in kg"""
Minor suggestion/concern: Consider the name 'MINIMUM_DAILY_DMI_RATIO' instead? It is not a percentage (0.01%), instead it is a multiplier (1%) of the body weight (kg) to calculate estimate for intake in the animal_requirements.py file under the calculate_NRC_DMI and calculate_NASEM_DMI methods.

2024-04-04 15:52 UTC, tomhuhh commented on RUFAS/routines/animal/life_cycle/heiferI.py
> +        when we have heifer nutrition from the ration formulation module.
Nice catch!

2024-04-04 15:55 UTC, tomhuhh commented
Sharing some results from my testing. They look identical. 

This is from earlier: 
![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/25afc180-eeee-482c-b5ae-2bf72ae3381c)

![image](https://github.com/RuminantFarmSystems/MASM/assets/52800053/db48c6a1-9f96-4b17-8d96-827d1ade106e)

This is from this PR: 
![default_reception-pit-total-degradable-solids-04-Apr-2024_Thu_11-46-00](https://github.com/RuminantFarmSystems/MASM/assets/52800053/5902ee16-ad82-4ac3-bbf4-b18beaaa773f)

![default_reception-pit-total-non-degradable-solids-04-Apr-2024_Thu_11-46-00](https://github.com/RuminantFarmSystems/MASM/assets/52800053/5c6bd95d-aa8a-42fe-b84e-6d249ed9a9d9)

2024-04-04 18:19 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/calf.py
> +            Amount of nutrients in pen ration, calculated per animal, see Notes section for units.
```suggestion
            Amounts of nutrients in pen ration, calculated per animal, see Notes section for units.
```

2024-04-04 18:20 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/calf.py
> +            Concentration of nutrients in pen ration, calculated per animal, percentage.
If you think this is unnecessary, please feel free to disregard. It's just a side effect of having a partner that's an English major.
```suggestion
            Concentrations of nutrients in pen ration, calculated per animal, percentage.
```

2024-04-04 18:45 UTC, ew3361zh commented
MyPy errors:

>In the file Pen.py, in _calc_animal_manure_excretion, it gives a complex error for the call to calc_manure_excretion, because there is a separate method for each animal class, and for lactating cows there are more input args required than for other classes. This flags a Mypy error where there are too many calls for Calf/HeiferI-III objects, but too few for cows. This logic is handled by _calc_animal_manure_excretion, where the animal object is routed to the correct call setup, but Mypy flags it anyway.
Question: Should this method be A) refactored in this PR, B) should I open an Issue, or C) this Mypy error should be flagged to be ignored?

For this one I'd probably just ignore it for now. I think it could potentially be fixed with Allister's refactoring of the animal types and how they're inheriting from one another.

>The method calc_manure_excretion in Cow.py gives the following error: Signature of "calc_manure_excretion" incompatible with supertype "HeiferIII"Mypy[override](https://mypy.readthedocs.io/en/latest/_refs.html#code-override)
Question: Should this error be officially ignored (e.g. flagging it in the code) while any changes to Animal objects (specifically related to inheritance) are made, or should we simply informally ignore it (e.g. allow the error, and open an Issue)?

I think similarly for this one. It should be ignored and we return back to it after Allister's refactoring of the animal types.

2024-04-04 19:54 UTC, tomhuhh approved these changes
Thanks Joe! Great work!

2024-04-04 19:55 UTC, merged