Farm specific lactation curve
RuminantFarmSystems/RuFaS pull request #1461
Opened 2024-03-27 21:06 UTC by harry-samuels

This pull request implements farm specific lactation curve parameter calculation based on temporal, location, and management data as well as reported milk yield.

### Context

Issue(s) closed by this pull request: closes #1881 

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What

This PR adds the class `LactationCurve`, which adjusts and generates the parameters for Wood's equation to estimate daily milk production. The adjustments to these parameters include temporal, spatial, and management components that requires minimal additional input from users.

### Why

This PR improves the accuracy of milk production estimations.

### How

`LactationCurve` gathers several inputs, including the location, herd composition, and annual milking yields from the config and animal inputs. It also grabs the new lactation inputs dedicated to setting and adjusting the lactation curve parameters.

After gathering all these inputs, `LactationCurve` calculates and adjusts Wood's l, m, and n lactation curve parameters for parities 1, 2, and 3+. When new `Cow`s are initialized, they get their l, m, and n values from `LactationCurve`, which is stored as a class attribute of `AnimalBase`.

### Test plan

An extensive test suite has been written for `LactationCurve` and run to make sure that LactationCurve performs as expected.

Also, the predicted milk yields from RuFaS will be checked against the values that were calculated when the underlying methodology for setting the Lactation Curve parameters was being developed.

Edit 8/8/2024 ~11am EDT: actual results are currently being compiled into a google sheet to be compared against expected results. Actual results will be calculated using relative differences, I (Ed) am pretty sure the expected values were computed with absolute differences so that should be considered when evaluating outputs. Will add a link to the google sheet here when it is complete.

Edit again: [link](https://docs.google.com/spreadsheets/d/1RQLw6wBqVwr-GsXExek1t5MlHtq2ipen25lM0M_YOFg/edit?usp=sharing) to the Google sheet with expected vs. actual results. During testing, there were a number of parity 1, 2 and 3+ fractions that had to be rounded in order to make sum to exactly 1.0. This seems like it would likely be the source of differences between expected and actual results if any. The exception to this is farm 9, there seems to be something off for the results of parities 2 and 3.

Edit again again: @YijingGong and I (Ed) found the the issue with farm 9: the problem was that the range that parameter l was fitted in was too restrictive ([-10, 10)). We bumped this up to a range of [-20, 20] and this did the trick.

### Open Questions
- Should there be different standard deviations for l, m, and n by parity? There were previously in the inputs, I am not sure if they should be carried over. Edit: the answer is yes, and these have been implemented.

### Next Steps
There are a number of next steps that can be taken, however given the size this PR has already reached I think it would be better to save these for a follow up issue/PR.

Several parts of `Cow` are either redundant or no longer necessary.
- The breed index and parity index are no longer needed - they should be removed.
- `calculate_daily_milk_produced` should use the method in `LactationCurve`, instead of reimplementing Wood's equation.
- All uses of `determine_param_value` should be replaced with calls to the new method in `Utility`.

The method `scipy.integrate.quad` is used in `calc_305_day_milk_yield`, and this method is slow (noticeably so - I can see the test cases ticking off one by one). Right now this isn't a problem, because this method is only called a handful of times per simulation. But this may not always be the case, so there should be a faster integration method used. I found that vectorized integration with NumPy was much faster, and provided accuracy comparable to `quad`.

Month adjustments are currently not made in `LactationCurve`, but we have everything in place to make them happen. So that is one option for future expansion.

2024-04-03 15:26 UTC, tomhuhh commented
Good work Harry and Catherine! 

I performed some tests by changing the following input parameters in the `default_animal.json` and `default_config.json` files. 

```
“cow_num”, 
“parity_percentage”, 
“annual milk yield”, 
“cow_times_milked_per_day”, 
‘end_date’, 
“FIPS_county_code” 
```
The results are in alignment with the results from the standalone code for farms c2f2 and c2f27.

To get this PR ready for a final review, here are some of my suggestions: 

1. Update all the input animal and metadata files. This PR involves structural changes in the input animal and metadata files. It is essential to make sure those files are updated across all files. 
2. Include the unit testing for the new feature. 
3. I noticed that there are a couple constants that could be moved into the constant file. For example, '305/365' could be named as something like 'assumed_milking_cow_percentage'.  

Keep up the good work! Thanks! 
Haowen

2024-04-05 14:16 UTC, Isgotkowitz reviewed
This is headed in the right direction, but there are a number of things that need to be done before this feature is ready. I suggest breaking it up into smaller PRs so that each piece may be fully implemented in a more digestible manner.

2024-04-05 14:16 UTC, Isgotkowitz commented on input/data/animal/LACTATION_CURVE_ADJUSTMENT_CONSTANTS.json
> +		"3x/d": [0.74, -0.090, -0.15]
Do you anticipate this list of parameter adjustments ever changing? If so, it would be good to consider an input structure that would be easier to maintain.

2024-04-05 14:16 UTC, Isgotkowitz commented on input/metadata/properties/default.json
> +        "default": null
Is this determining how much milk will be determined, regardless of how cows are managed?

2024-04-05 14:16 UTC, Isgotkowitz commented on input/metadata/properties/default.json
> +      "description" : "The corresponding region for each state/location that can be described by the FIPS code. FIPS codes that do not correspond to a region in the dataset are the empty string.",
Corresponding to what?

2024-04-05 14:16 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +    @staticmethod
Instead of adding these new methods into AnimalBase, why not create a new module dedicated to handling the lactation curve logic. Then AnimalBase can just call a top level routine in that module to get the milking parameters.

Also, there are a lot of things missing from these methods. There are no type hints, return types, docstrings or tests. These will need to be added.

2024-04-05 14:16 UTC, Isgotkowitz commented on input/data/animal/LACTATION_CURVE_ADJUSTMENT_CONSTANTS.json
These are not constants, these are inputs.

2024-04-12 14:56 UTC, JoeWaddell commented on input/data/animal/LACTATION_CURVE_ADJUSTMENT_CONSTANTS.json
> +		"3x/d": [0.74, -0.090, -0.15]
To echo this, I agree it would be better to further categorize the levels, like was done with the `fips_region`.

E.g. another section for year, another for parity, etc.

2024-04-12 14:56 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +            MY_305d = AnimalBase.calc_integral_wood_curve(parameter_a, parameter_b, parameter_c)
This section (where `MY_305d` is `None`) could be its own helper method.

2024-04-12 14:56 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +            y = AnimalBase.get_y_values_wood_curve(t, parameter_a, parameter_b, parameter_c)
Is there a future need for `y`?

2024-04-12 14:57 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +        parameter_a = 19.9
Are the values (e.g. 19.9, 24.7, 33.76) ones that should be put in another file, e.g. in the LACTATION_CURVE json? Or do they come straight from the literature/ongoing work?

2024-04-12 14:58 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +            min_diff = float("inf")
This section (where `MY_305d` is not `None`) could also be its own helper method.

2024-04-12 14:59 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +            percent_P1 = parity_percentages[0] * 100
This shows as not being used: is this for future reference, or an output to be logged elsewhere?

2024-04-12 15:00 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +        P2_MY305_adj = im.get_data("lactation.parity_milk_adjustments.MY305_P2_adjustment")
In general I'd recommend more readable names, if possible (e.g. writing out parity and milk year in this variable name).

Same for other variables below, all the P# names

2024-04-12 17:00 UTC, JoeWaddell reviewed
A few comments, please let me know if you need clarification! Looking good, but I have some thoughts on some structural changes and a few smaller items.

2024-07-16 16:58 UTC, YijingGong commented on input/data/animal/LACTATION_CURVE_ADJUSTMENT_CONSTANTS.json
> +		"3x/d": [0.74, -0.090, -0.15]
> Do you anticipate this list of parameter adjustments ever changing? If so, it would be good to consider an input structure that would be easier to maintain.

It does not change, they are values from a published paper (https://www.sciencedirect.com/science/article/pii/S0022030222004362). Unless we, as developers, want to change it, for example, to add years after 2016, etc. <- but for this purpose, I remember we have some plan for this extrapolation, not sure if it is in this PR though.

2024-07-16 17:04 UTC, YijingGong commented on input/metadata/properties/default.json
> +        "default": null
> Is this determining how much milk will be determined, regardless of how cows are managed?

It is the observed annual milk yield (whatever reported in the Excel sheet when the farm data is collected)

2024-07-16 20:40 UTC, YijingGong requested changes
I checked the code. Comments are left in line. Then I tried to run this branch, trying to see if the Wood's lactation curve parameter values are as expected. I ran across this error: 
<img width="1059" alt="Screenshot 2024-07-16 at 3 31 51 PM" src="https://github.com/user-attachments/assets/ff74b2bd-32a5-4315-8e79-be5769a22821">
I am just using the default inputs.

2024-07-16 20:40 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +        parameter_a = 19.9
Agree. Better to put in a constant file or at least need some reference

2024-07-16 20:40 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +            year = "2016"
Looks like there's no extrapolation here yet. That's ok. Just make sure to include it in the PR description

2024-07-16 20:40 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +                    print(code_region["region"])
Do we want those prints?

2024-07-16 20:40 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +        print("Params 3: " + str(AnimalBase.lactation_parameters[3]))"""
Same here. Do we want those prints while running Rufas?

2024-07-16 20:40 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/cow.py
> +                parity_key = 0
Just out of my curiosity, why can parity be negative?

2024-07-16 20:40 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        )
I get confused. Why does this lactation_curve.py have similar codes as what is in the animal_base.py? Do you want to move these here and forget to delete the code in animal_base.py?

2024-07-16 20:40 UTC, YijingGong commented on input/data/animal/default_animal.json
> +				]
Not sure if we still want to have these STD in the input file. My feeling is that farmers will likely never change these values.

2024-07-16 20:40 UTC, YijingGong commented on input/metadata/properties/default.json
> +        "description": "Percentage of total herd represented by parity 1, 2, and 3+ (length 3)",
description can be "Percentage of the animal population in parity 1, 2, and 3 and beyond. The array length needs to be 3"

2024-07-16 20:40 UTC, YijingGong commented on input/metadata/properties/default.json
> +          "description": "Percentage of total herd made up by given parity group, either 1, 2, or 3+",
description can be "Percentage of the animal population in parity 1, 2, or 3 and beyond"

2024-07-19 16:57 UTC, ew3361zh commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +im = InputManager()
As a heads up, we are trying to no longer instantiate IM as a global variable - it was causing some issues with instantiating IM before we expected it to. Please see guidance and best practices in the wiki: 

https://github.com/RuminantFarmSystems/MASM/wiki/Input-Manager#getting-data-from-input-managers-data-pool

2024-07-23 21:34 UTC, yangcatherine commented on input/metadata/properties/default.json
> +      "description" : "The corresponding region for each state/location that can be described by the FIPS code. FIPS codes that do not correspond to a region in the dataset are the empty string.",
Corresponding to in the M. Li et al. lactation curve paper. Updated this just now.

2024-07-28 15:26 UTC, yangcatherine commented on input/data/animal/LACTATION_CURVE_ADJUSTMENT_CONSTANTS.json
> +		"3x/d": [0.74, -0.090, -0.15]
This was updated and the constants were categorized.

2024-07-28 19:37 UTC, yangcatherine commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +        parameter_a = 19.9
These are now included in the lactation curve inputs json file

2024-07-29 02:56 UTC, yangcatherine commented on RUFAS/routines/animal/life_cycle/cow.py
> +                parity_key = 0
Line 276 is "self.parity_index = 2 if self.calves - 1 > 2 else self.calves - 1" but self.calves is initialized to 0 so I believe we ran into problems with that. Thank you for raising my attention to this though, I will bring it up at the next meeting.

2024-08-02 14:08 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +            Milk yield on the provided day (kg).
Kg needs to be double checked here

2024-08-02 14:16 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +            305 day milk yield for a cow with the given lactation curve (kg).
Kg needs to be double checked here

2024-08-02 14:16 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        params = self.parity_to_parameter_mapping[parity]
Add in check to prevent parity 0 cows from crashing the simulation?

2024-08-02 14:44 UTC, Isgotkowitz commented on input/metadata/properties/default.json
> +        "type": "array",
Change this to be dictionary- also these are fractions, not percentages.

2024-08-02 16:49 UTC, Isgotkowitz commented on input/metadata/properties/default.json
>              "description": "Standard deviation of parameter l ",
Remove standard dev inputs

2024-08-02 18:00 UTC, Isgotkowitz commented on input/metadata/properties/default.json
> +    "milking_cow_percentage": {
This is fraction, not a percentage

2024-08-05 13:47 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        params = self.parity_to_parameter_mapping[parity]
After running the simulation a couple time, this has not been an issue. So Ig it would be better to not add a check, and if something goes wrong with it we'll know pretty quickly

2024-08-07 22:46 UTC, Isgotkowitz commented
Update: after a discussion with @YijingGong, the logic of `_estimate_305_day_milk_yield_by_parity` has been changed to use relative differences instead of absolute ones (i.e. the 305 day milk yield of P2 cows is 18% higher than the 305 day milk yield of P1 cows instead of the 305 day milk yield of P2 cows being 1632 kg greater than the 305 day milk yield of P1 cows). This required a change to the values used to calculate the 305 day milk yields relative to each other, which has also been made.

2024-08-10 15:44 UTC, tomhuhh approved these changes

2024-08-10 15:44 UTC, tomhuhh commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +
Should we add these to a constant sheet?

2024-08-10 15:46 UTC, tomhuhh commented
This looks great! Thanks Ed! 

I tested by changing milking frequency from 3x to 2x. Results can be found below. 

3x: 

l:  18.14
m:  0.2329
n:  0.0023420000000000003
l:  24.479999999999997
m:  0.2246
n:  0.003539
l:  24.339999999999996
m:  0.2523
n:  0.0039380000000000005

2x: 
l:  16.66
m:  0.2347
n:  0.002372
l:  23.0
m:  0.2264
n:  0.003569
l:  22.86
m:  0.2541
n:  0.003968

Thanks!

2024-08-12 13:21 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +
Like a documentation sheet, or a constants module in the code?

2024-08-12 13:42 UTC, tomhuhh commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +
I was picturing a constants module in the code but whatever works the best with the rest of the submodule sounds good to me.

2024-08-12 21:40 UTC, KFosterReed commented on RUFAS/general_constants.py
> +        LBS_TO_KG: The conversion factor from pounds to kilograms.
I don't see where either of these conversions are used, which is great because there shouldn't be any conversions betwen metric and English units in the biophysical model! If that is truly the case, let's delete these from the constants file

2024-08-13 12:51 UTC, KFosterReed commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +            305 day milk yield for a cow with the given lactation curve (kg).
The referenced work was conducted in kg so the parameters drawn from it are also predicting milk yield in kg and I believe this is correct

2024-08-13 13:27 UTC, allisterakun approved these changes
It generally looks good! I left some suggestions for type hints.

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +
We have the `animal_constants.py` and  `general_constants.py` holding animal-level or the entire simulation-level constants. From my understanding, if a variable only really applies to a submodule file, we can keep that in the submodule to avoid complicating the constant file.

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        self.om = OutputManager()
@matthew7838, please advise if we should initiate a local om instance in each function or if it's fine to have this `self.om` initialized at the class init.

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        lactation_inputs = im.get_data("lactation")
```suggestion
        lactation_inputs: dict[str, any] = im.get_data("lactation")
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        fips_code = im.get_data("config.FIPS_county_code")
```suggestion
        fips_code: int = im.get_data("config.FIPS_county_code")
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        all_year_adjustments = lactation_inputs["adjustments"]["year"]
```suggestion
        all_year_adjustments: dict[str, dict[str, float]] = lactation_inputs["adjustments"]["year"]
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        all_region_adjustments = lactation_inputs["adjustments"]["region"]
```suggestion
        all_region_adjustments: dict[str, dict[str, float]] = lactation_inputs["adjustments"]["region"]
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        region_mapping = lactation_inputs["state_to_region_mapping"]
```suggestion
        region_mapping: dict[str, str] = lactation_inputs["state_to_region_mapping"]
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        animal_inputs = im.get_data("animal")
```suggestion
        animal_inputs: dict[str, Any] = im.get_data("animal")
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        animal_milking_frequency = animal_inputs["animal_config"]["management_decisions"]["cow_times_milked_per_day"]
```suggestion
        animal_milking_frequency: int = animal_inputs["animal_config"]["management_decisions"]["cow_times_milked_per_day"]
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        all_milking_frequency_adjustments = lactation_inputs["adjustments"]["milking_frequency"]
```suggestion
        all_milking_frequency_adjustments: dict[str, dict[str, float]] = lactation_inputs["adjustments"]["milking_frequency"]
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        animal_milking_frequency = animal_inputs["animal_config"]["management_decisions"]["cow_times_milked_per_day"]
Is this an int or a float?

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        parity_adjustments = lactation_inputs["adjustments"]["parity"]
```suggestion
        parity_adjustments: dict[str, dict[str, float]] = lactation_inputs["adjustments"]["parity"]
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        base_wood_parameter_n = lactation_inputs["parameter_mean_values"]["parameter_n_mean"]
```suggestion
        base_wood_parameter_l: float = lactation_inputs["parameter_mean_values"]["parameter_l_mean"]
        base_wood_parameter_m: float = lactation_inputs["parameter_mean_values"]["parameter_m_mean"]
        base_wood_parameter_n: float = lactation_inputs["parameter_mean_values"]["parameter_n_mean"]
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        self.parity_to_std_dev_mapping = {
```suggestion
        self.parity_to_std_dev_mapping: dict[int, float] = {
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        annual_milk_yield = animal_inputs["herd_information"]["annual_milk_yield"]
```suggestion
        annual_milk_yield: float = animal_inputs["herd_information"]["annual_milk_yield"]
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        num_milking_cows = animal_inputs["herd_information"]["cow_num"] * lactation_curve_inputs["milking_cow_fraction"]
```suggestion
        num_milking_cows: float = animal_inputs["herd_information"]["cow_num"] * lactation_curve_inputs["milking_cow_fraction"]
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        parity_3_percentage = animal_inputs["herd_information"]["parity_fractions"]["3"]
```suggestion
        parity_1_percentage: float = animal_inputs["herd_information"]["parity_fractions"]["1"]
        parity_2_percentage: float = animal_inputs["herd_information"]["parity_fractions"]["2"]
        parity_3_percentage: float = animal_inputs["herd_information"]["parity_fractions"]["3"]
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        annual_milk_yield = animal_inputs["herd_information"]["annual_milk_yield"]
```suggestion
        annual_milk_yield: float = animal_inputs["herd_information"]["annual_milk_yield"]
```

2024-08-13 13:27 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        ]
```suggestion
        parity_2_milk_yield_adjustment: float = lactation_curve_inputs["parity_milk_yield_adjustments"][
            "parity_2_305_day_milk_yield_adjustment"
        ]
        parity_3_milk_yield_adjustment: float = lactation_curve_inputs["parity_milk_yield_adjustments"][
            "parity_3_305_day_milk_yield_adjustment"
        ]
```

2024-08-13 14:15 UTC, KFosterReed approved these changes
Great work team! I tested this with different annual milk production values, different herd parity inputs, and different county codes and the milk production changes as expected!

2024-08-13 14:39 UTC, matthew7838 commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        self.om = OutputManager()
This is perfect. We initialize it every time method for static methods, for non-static we should initialize it in a constructor like the one here.

2024-08-13 14:43 UTC, tomhuhh commented
As suggested by Kristan (@KFosterReed), I cross-checked the parameters entered in the LACTATION_CURVE_ADJUSTMENT_INPUTS.json file, and everything aligns with the data reported in Li et al. (2022).

Great job! Thanks!

2024-08-13 14:48 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +
This is the approach that guided my decision. If we find that any of these values are actually needed in more places in `life_cycle/` or `animal/`, we can always move them into a constants file as needed.

2024-08-13 14:49 UTC, Isgotkowitz commented on RUFAS/general_constants.py
> +        LBS_TO_KG: The conversion factor from pounds to kilograms.
Nice catch Kristan, these are unused and I will take them out.

2024-08-13 15:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +        animal_milking_frequency = animal_inputs["animal_config"]["management_decisions"]["cow_times_milked_per_day"]
Float, but rounded to an int, will add it into the code.

2024-08-13 15:27 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +            305 day milk yield for a cow with the given lactation curve (kg).
Thanks Kristan

2024-08-13 17:45 UTC, YijingGong approved these changes
Great job! I just have two small questions for my own curiousity. Approved it already.

2024-08-13 17:45 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +                f"Fractions of milking cows that are parity 1, 2 and 3+ sum to {parity_fractions_sum}, not 1.0",
Curious about this. I used the Farm 2 (c2f2) in the testing data where the herd parity is ("parity_fractions": {
      "1": 0.269305,
      "2": 0.2386925,
      "3": 0.49121
    },), and it gives me this error `[13-Aug-2024_Tue_12-25-34.866581][ERROR][default] Fractions of milking cows that are parity 1, 2 and 3+ sum to 0.9992075, not 1.0. Using 0.386, 0.281 and 0.333 as the fractions of parity 1, 2 and 3+ cows in the milking herd, respectively`, which is expected based on this code. 
However, your testing results of Farm2 match to my results. I am thinking should we add some "error range" for it, for example, if the difference is within 0.01, it's ok? Or could you help me understand how your testing cases work even if they did not add up to exactly 1.

2024-08-13 17:45 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +            animal_inputs["herd_information"]["cow_num"] * lactation_curve_inputs["milking_cow_fraction"]
So this says we don't have the ability to input the milking cow number, we always have a fixed proportion of milking cows (0.8356). I guess that's ok in our case where cohort farms did not report the # of milking cows. But again, I'm curious how did you do the testing where I passed you the # of milking cows?

2024-08-13 19:12 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +                f"Fractions of milking cows that are parity 1, 2 and 3+ sum to {parity_fractions_sum}, not 1.0",
When we ran into this in the tests, we would tweak the parity fractions until they added up to exactly 1.0. Usually this meant tweaking the numbers by a couple thousandths or ten thousandths, and the difference between the actual and expected results seemed small enough (like, a few kg in the 305 day milk yield) that this wasn't a big deal.

2024-08-13 19:15 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +                f"Fractions of milking cows that are parity 1, 2 and 3+ sum to {parity_fractions_sum}, not 1.0",
An error range could definitely be added in, and 0.01 sounds like a good cutoff for it. Would that be something that needs to go in this PR, or would it be ok for a follow up PR?

2024-08-13 19:17 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +            animal_inputs["herd_information"]["cow_num"] * lactation_curve_inputs["milking_cow_fraction"]
For test cases, we calculated the milking cow fraction as the number of milking cows divided by the number of adult cows.

2024-08-13 19:17 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +            animal_inputs["herd_information"]["cow_num"] * lactation_curve_inputs["milking_cow_fraction"]
> we always have a fixed proportion of milking cows (0.8356)

This proportion is not fixed, it is an input. So we would change it for each test case. Would it be preferred to have the milking cow # as an input instead?

2024-08-13 20:35 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +            animal_inputs["herd_information"]["cow_num"] * lactation_curve_inputs["milking_cow_fraction"]
Ohh perfect! I did not realize "lactation_curve_adjustment_inputs.json" is an input file as well. I thought it is a constant file.

2024-08-13 20:38 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +                f"Fractions of milking cows that are parity 1, 2 and 3+ sum to {parity_fractions_sum}, not 1.0",
I personally think it would be good to have it in this PR, since it's closely related and it should be fairly straightforward, right?

2024-08-14 14:26 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +                f"Fractions of milking cows that are parity 1, 2 and 3+ sum to {parity_fractions_sum}, not 1.0",
Yes, I will put it in right now. I will implement it so that if the difference is < 0.01 it will use the numbers as-is. This will be the most straightforward solution, but an alternative would be to round the numbers up so that they are exactly equal to 1.0.

2024-08-14 15:09 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/lactation_curve.py
> +                f"Fractions of milking cows that are parity 1, 2 and 3+ sum to {parity_fractions_sum}, not 1.0",
Added

2024-08-15 20:17 UTC, merged