Enable json filter files with .json extension
RuminantFarmSystems/RuFaS pull request #1491
Opened 2024-04-02 19:12 UTC by ltp23

### Context

Issue(s) closed by this pull request: closes #1432 

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What & Why
This PR is part 1 of a series of PRs aiming to improve the handling of data origins info. To allow more customizations, first, we want to be able to incorporate user settings. Currently, this is mainly targeted towards json filter files.

### How
Before, to generate json output, we would use a filter file with this name format `json_<example_name>.txt`. Now, in addition to this, the output manager also accepts the extension `.json`. For example, `json_<example_name>.json` should also work.

I also added a `detailed_values` in the config files flag to turn on/off the detailed_values property.

### Test plan

For example, I would create a filter file with the name `json_example.json`. The following two formats are equivalent and acceptable. 

The first format is simpler and makes sure that there is only one `filters` key.

The second format is more familiar as it is consistent with how to specify graphs and reports but there is no enforcing of only one object inside the array.  

```
{
  "filters": [
    ".*"
  ],
  "name": "All Variables"
}
```

```
{
  "multiple": [
    {
      "filters": [
        ".*"
      ],
      "name": "All Variables"
    }
  ]
}
```

2024-04-10 02:59 UTC, Isgotkowitz approved these changes
Two suggestions on minor things, but functions just as expected. Nice job Loi!

2024-04-10 02:59 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            self._detailed_values_flag: bool = False
Add to attributes section of class docstring

2024-04-10 02:59 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +                max_depth = 4
Instead of defining this in the method, could it be defined at the top of the file as a constant, with something explaining what it's doing.

2024-04-10 16:44 UTC, ltp23 commented on RUFAS/output_manager.py
> +                max_depth = 4
I can add a class constant called `JSON_OUTPUT_MAX_RECURSIVE_DEPTH` for this.

2024-04-11 16:36 UTC, PooyaHekmati requested changes
1. in json filters all filters are in the `filters` entry. this pr is assuming multiple blobs.
2. the changelog entry is not clear enough
3. the PR is not backward compatible.
4. it is not clear how json filters are handled.

2024-04-11 16:36 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    _detailed_values_flag : bool
```suggestion
    _include_detailed_values : bool
```

2024-04-11 16:36 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        Flag to include detailed values in the json output files
missing verb in `Flag to include detailed values in the json output files` 
if this flag is true, what does it mean? are details already included or are you going to include them later?

2024-04-11 16:36 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        for key in data_dict:
```suggestion
        for key, sub_data_dict in data_dict.values():
```

2024-04-11 16:36 UTC, PooyaHekmati commented on RUFAS/output_manager.py
>              sub_data_dict = data_dict[key]
```suggestion
```

2024-04-11 16:36 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        Checks if the provided sub_data_dict is suitable for adding detailed values.
```suggestion
        Checks if the provided sub_data_dict is compatible for adding detailed values.
```
?

2024-04-11 16:36 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            The dictionary to check for suitability.
```suggestion
            The dictionary to check for compatiblity.
```

2024-04-11 16:36 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            Flag to include milliseconds in the timestamp.
```suggestion
```
I don't think this is necessary.

2024-04-11 16:36 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        if filter_file.endswith(".json") and "name" not in filter_content:
why?

2024-04-11 16:36 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        self._detailed_values_flag = flag
```suggestion
    def set_detailed_values_flag(self, flag: bool) -> None:
        """
        Sets the flag for adding detailed values to the output files.
        """

        self._detailed_values_flag = flag
```

2024-04-11 20:37 UTC, ltp23 commented on RUFAS/output_manager.py
> +        Flag to include detailed values in the json output files
I changed it to this

```
_include_detailed_values : bool
        Set to True to include detailed values in the json output files after the simulation
```

Adding the detailed value property happens after the simulation when we are at the step of making json output files.

2024-04-11 20:37 UTC, ltp23 commented on RUFAS/output_manager.py
> +    _detailed_values_flag : bool
Ok. I can rename that.

2024-04-11 20:56 UTC, ltp23 commented on RUFAS/output_manager.py
> +        Checks if the provided sub_data_dict is suitable for adding detailed values.
I changed it to this

```
    def _can_add_detailed_values(self, sub_data_dict: Dict[str, Any]) -> bool:
        """
        Checks if the provided sub_data_dict has the necessary structure and data to add detailed values.

        The sub_data_dict should meet the following requirements:
        - It must be a dictionary.
        - It must contain the keys "info_maps" and "values".
        - The length of the "info_maps" list and the "values" list must be equal.

        Parameters
        ----------
        sub_data_dict : Dict[str, Any]
            The dictionary to check for compatibility with adding detailed values.

        Returns
        -------
        bool
            True if the sub_data_dict meets the requirements for adding detailed values, False otherwise.
        """
```

2024-04-12 13:48 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +        Checks if the provided sub_data_dict is suitable for adding detailed values.
That looks like a good docstring but I think the "sub_data_dict" part and bullets beneath should go into the `Notes` section.

2024-04-13 07:20 UTC, ltp23 commented
> 1. in json filters all filters are in the `filters` entry. this pr is assuming multiple blobs.

With the latest updates, the following two formats are equivalent and acceptable. 

The first format is simpler and makes sure that there is only one `filters` key.

The second format is more familiar as it is consistent with how to specify graphs and reports but there is no enforcing of only one object inside the array. If necessary, I can manually enforce it by checking that the array of the `multiple` key has a length of 1.

```
{
  "filters": [
    ".*"
  ],
  "name": "All Variables"
}
```

```
{
  "multiple": [
    {
      "filters": [
        ".*"
      ],
      "name": "All Variables"
    }
  ]
}
```

> 2. the changelog entry is not clear enough

I changed it to this "Enable json filter files with .json extension to allow more customizations later such as formatting detailed values."

> 3. the PR is not backward compatible.

Let me know if there are other things to make it more backward compatible.

> 4. it is not clear how json filters are handled.

I don't think I have made any changes to the way json filters are handled (`dict_to_file_json()` method). This PR is more about preparing user-created filter files and their contents before feeding them into that method.

2024-04-13 07:24 UTC, ltp23 commented on RUFAS/output_manager.py
> +        if filter_file.endswith(".json") and "name" not in filter_content:
That was when there were multiple blobs and they had no name fields, so a suffix of milliseconds timestamp would be needed to differentiate between files.

I have simplified it to the following, assuming only one file will be created.

```
        if "name" in filter_content:
            base_name = f"saved_variables_{filter_content['name']}"
        else:
            base_name = f"saved_variables_{filter_file}"

        file_name = self.generate_file_name(base_name, "json")
```

2024-04-24 05:57 UTC, allisterakun approved these changes
LGTM! Good job, Loi!

2024-04-25 21:44 UTC, PooyaHekmati approved these changes

2024-04-25 22:08 UTC, merged