[1/n] Track simulation day in Time class and set up time in classes
RuminantFarmSystems/RuFaS pull request #1499
Opened 2024-04-03 21:31 UTC by ltp23

### Context

Issue(s) closed by this pull request: closes #

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What & Why

This PR aims to reduce the size of a bigger PR, #1438, by focusing on consolidating the logic of keeping track of the simulation day in the Time class and making the following classes — SimulationEngine, OutputManager, Rreportgenerator, GraphGenerator, have a reference to the Time object for later use. 

The overall goal is to incrementally resolve the two issues #912 and #1366.

### How

Main steps
- [x] Rename the `self.index` attribute to `self.simulation_day` in the Time class.
- [x] Remove the `self.day_counter` attribute in the SimulationEngine class.
- [x] Make the above-mentioned classes store a reference to the same Time object that was created in the SimulationEngine class.
- [x] Update unit tests.

### Test plan

2024-04-09 18:32 UTC, PooyaHekmati requested changes
In addition to in-code comments, `self.calendar_year` and `self.year` attributes in the Time class need better names. Why do we even have two kinds of year?

2024-04-09 18:32 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        self.time = time_obj
```suggestion
```
a public attribute doesn't need a setter function.

2024-04-09 18:32 UTC, PooyaHekmati commented on RUFAS/report_generator.py
> +        self.time = time
why is this needed?

2024-04-09 18:32 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +        self.time = time
why is this needed?

2024-04-09 18:32 UTC, PooyaHekmati commented on RUFAS/time.py
> +        Advances the time in the simulation by 1 day and automatically detects end of months and years.
I don't see any logic for handling month. Also, the year doesn't seem to be incremented.

2024-04-09 18:32 UTC, PooyaHekmati commented on RUFAS/time.py
> +            True if it is the end of a year, False otherwise
vague docstring.
the logic is not clear either.

2024-04-09 18:32 UTC, PooyaHekmati commented on RUFAS/time.py
> +        """
```suggestion
```

2024-04-09 18:32 UTC, PooyaHekmati commented on RUFAS/time.py
> +                "simulation_year_day": "Year: {}, Day: {}".format(self.year, self.day),
use f-string; `format` is bad.

2024-04-10 16:04 UTC, ltp23 commented on RUFAS/time.py
> +        """
I will remove the docstring for the str method.

2024-04-10 16:04 UTC, ltp23 commented on RUFAS/time.py
> +                "simulation_year_day": "Year: {}, Day: {}".format(self.year, self.day),
I will use f-string instead.

2024-04-10 16:04 UTC, ltp23 commented on RUFAS/time.py
> +            True if it is the end of a year, False otherwise
I will clarify the docstring.

2024-04-10 16:04 UTC, ltp23 commented on RUFAS/time.py
> +        Advances the time in the simulation by 1 day and automatically detects end of months and years.
I didn't see any mention of how months should be handled in the time file.

In the `advance()` method, there is a section that increments the year.

```
self.simulation_day += 1

if self.end_year():
    self.day = 1
    self.year += 1
    self.calendar_year += 1
else:
    self.day += 1
```

2024-04-10 16:05 UTC, ltp23 commented on RUFAS/report_generator.py
> +        self.time = time
In later PRs, it is needed to convert simulation days into actual dates in reports.

2024-04-10 16:05 UTC, ltp23 commented on RUFAS/graph_generator.py
> +        self.time = time
In later PRs, it is needed to convert simulation days into actual dates in reports.

2024-04-10 16:06 UTC, ltp23 commented on RUFAS/output_manager.py
> +        self.time = time_obj
Ok. I will remove the setter.

2024-04-10 16:09 UTC, ltp23 commented
> `self.calendar_year` and `self.year` attributes in the Time class need better names. Why do we even have two kinds of year?

The `self.calendar_year` refers to the real year (e.g., 2009), whereas the `self.year` is the current simulation year (counting from 1). Maybe a better name for the latter would be `simulation_year`?

2024-04-19 18:55 UTC, Isgotkowitz reviewed
I think this makes some good steps forward in improving the use and structure of `Time` in RuFaS. I left a couple of comments on, mostly minor stuff. I think `SimulationEngine` could be further refactored to put have less time-related functionality, but it may be more appropriate to save those changes for another PR more dedicated to refactoring SimEngine.

2024-04-19 18:55 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +    def __init__(self, metadata_prefix: str = "", time=None) -> None:
Can time be imported and type annotated here?

2024-04-19 18:55 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            self.time = None
This attribute needs type hinting and a docstring. Also, does it need a setter?

2024-04-19 18:55 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +    def __init__(self, time=None) -> None:
Also needs type hinting and docstring update.

2024-04-19 18:55 UTC, Isgotkowitz commented on RUFAS/simulation_engine.py
> +            },
Instead of recording this on only one day and doing so outside of the `Time` class, what about adding it to the method `record_time` in the `Time` class?

That change might be a little outside the scope of this PR though.

2024-04-19 18:55 UTC, Isgotkowitz commented on RUFAS/simulation_engine.py
>              om.add_log("simulation_day", simulating_day_log, info_map)
Maybe it would be better to just remove this recording entirely, and leave all recording of time to the `record_time` method in `Time`? Especially since this recording of time is never actually used.

2024-04-19 18:55 UTC, Isgotkowitz commented on RUFAS/time.py
> +        Advances the time in the simulation by 1 day and automatically detects end of months and years.
Currently months aren't explicitly tracked in `Time` at all - the day field is the ordinal day of the year, so it is agnostic to whatever the month is.

2024-04-19 18:55 UTC, Isgotkowitz commented on RUFAS/time.py
> +            The date object that corresponds to the simulation day.
```suggestion
            The simulation day to convert to a date object.
        
        Returns
        -------
        datetime.date
            The date object that corresponds to the simulation day.

```

2024-04-19 18:55 UTC, Isgotkowitz approved these changes

2024-04-22 21:56 UTC, ltp23 commented on RUFAS/graph_generator.py
> +    def __init__(self, metadata_prefix: str = "", time=None) -> None:
Due to the circular imports error, I can't use the Time annotation.

2024-04-22 22:29 UTC, ltp23 commented on RUFAS/output_manager.py
> +            self.time = None
I can add a docstring but not a type hint because of circular imports error. It is a public attribute so it can be set directly without a setter.

2024-04-23 05:52 UTC, ltp23 commented on RUFAS/simulation_engine.py
> +            },
I have added a `simulation_day` variable in the `record_time` method. So, now we have the following four variables

```
Time.day
Time.year
Time.calendar_year
Time.simulation_day
```

2024-04-23 05:52 UTC, ltp23 commented on RUFAS/simulation_engine.py
>              om.add_log("simulation_day", simulating_day_log, info_map)
I have removed the `print_day` block.

2024-04-24 12:17 UTC, allisterakun approved these changes
Thank you Loi! Good PR

2024-04-25 21:45 UTC, PooyaHekmati approved these changes

2024-04-25 22:36 UTC, merged