[GG] Option to omit prefixes from auto-populated legend keys
RuminantFarmSystems/RuFaS pull request #1518
Opened 2024-04-10 06:19 UTC by allisterakun

This PR introduces a new `omit_legend_prefix` flag in the graph filter file to give the user the option to omit the prefixes for auto-generated legend keys
### Context

Issue(s) closed by this pull request: closes #1338.

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What

Introduces a new `omit_legend_prefix` flag in the graph filter file to give the user the option to omit the prefixes for auto-generated legend keys. This flag will default to False unless otherwise specified.

### Why

To address the issue of the auto-generated legends being too long.

### How

By giving the user the option to omit the prefixes of the auto-generated legends.

### Test plan

Before
![image](https://github.com/RuminantFarmSystems/MASM/assets/39185942/c70410dc-2c95-4cbf-8f1b-efe7a34f911a)
After
![image](https://github.com/RuminantFarmSystems/MASM/assets/39185942/14f334a5-de6d-430e-b920-575bee2b18b1)
The above graph is generated with the following filter running on the default scenario:
```JSON
{
  "type": "plot",
  "filters": [
    "AnimalModuleReporter.report_daily_pen_total.*"
  ],
  "title": "AnimalModuleReporter daily_pens",
  "omit_legend_prefix": true
}
```

2024-04-10 14:20 UTC, Isgotkowitz requested changes
The variable name is not included when there is a suffix - try using this filter:
```json
{
  "multiple": [
    {
      "type": "plot",
      "filters": [
        ".*\\.snow_(melt|content).field='.*'"
      ],
      "variables": ["snow_content", "snow_melt"],
      "title": "Snow Dynamics",
      "omit_legend_prefix": true
    }
  ]
}
```

2024-04-10 14:27 UTC, JoeWaddell commented on RUFAS/graph_generator.py
> +                    graph_details["legend"] = list(key.split(".")[-1] for key in prepared_data.keys())
The only issue here is that if a decimal point is in a variable name, e.g. if there was some hypothetical `growth_above_1.5kg` key. 

It doesn't appear we have any like that currently, but if a variable is introduced in the future, it would break this functionality. 

Could we count from the other direction instead, or are the prefixes more variable/tough to clip off?

2024-04-24 01:27 UTC, allisterakun commented
1. len() == 1:
    1. name
2. len() == 2:
    1. prefix.name
3. len() == 3:
    1. Class.Method.Name
    2. prefix.name1.name2
    3. prefix.name.suffix
4. len() == 4:
    1. Class.Method.name.suffix
    2. prefix.name1.name2.name3
    3. prefix.name1.name2.suffix
5. len() == 4+:
    1. Class.Method.name1.name2...suffix
    2. Class.Method.name1.name2.name3…
    3. prefix.name1.name2.name3.name4…
    4. prefix.name1.name2.name3…suffix

```python
        combined_var_name_list = combined_var_name.split('.')

        if len(combined_var_name_list) == 1:
            # no prefix and no suffix
            return combined_var_name_list[0]

        elif len(combined_var_name_list) == 2:
            # prefix.name
            return combined_var_name_list[1]

        elif len(combined_var_name_list) >= 3:
            # has suffix
            if '=' in combined_var_name_list[-1]:
                slice_end = -1
                # class.method.*.suffix
                if re.match('([A-Z][a-z0-9]+)+', combined_var_name_list[0]):
                    slice_start = 2
                    return ".".join(combined_var_name_list[2:-1])
                # prefix.*.suffix
                else:
                    slice_start = 1
                    return ".".join(combined_var_name_list[1:-1])
            # no suffix
            else:
                slice_end = len(combined_var_name_list)
                # class.method.*
                if re.match('([A-Z][a-z0-9]+)+', combined_var_name_list[0]):
                    slice_start = 2
                    return ".".join(combined_var_name_list[2:])
                # prefix.*
                else:
                    slice_start = 1
                    return ".".join(combined_var_name_list[1:])
```
||
v
simplified logic
```python
combined_var_name_list = combined_var_name.split('.')
        if len(combined_var_name_list) == 1:
            # no prefix and no suffix
            return combined_var_name_list[0]
        elif len(combined_var_name_list) == 2:
            # prefix.name
            return combined_var_name_list[1]

        elif len(combined_var_name_list) >= 3:
            # class.method.* or prefix.*
            slice_start = 2 if re.match('([A-Z][a-z0-9]+)+', combined_var_name_list[0]) else 1
            # *.suffix or no suffix
            slice_end = -1 if '=' in combined_var_name_list[-1] else len(combined_var_name_list)

            return ".".join(combined_var_name_list[slice_start:slice_end])
```

2024-04-24 14:13 UTC, Isgotkowitz approved these changes
Works on the various filters I tried. Left some on cleaning code up a little and fixing some typos. Also would be good to identify where the new Mypy errors are being introduced and fix them so the number of errors isn't going up.

With respect to the fix, I think it is good for now but relying on string parsing is not a good long term solution. A better one would be to get info maps into the graph generator so that the class name, function name, prefix, suffix, and anything else that may be added gets removed precisely. That may or may not require significant changes to the Graph generator and other parts of the code though.

2024-04-24 14:13 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +    def _generage_legend_keys(self, combined_var_name: str) -> str:
```suggestion
    def _generate_legend_keys(self, combined_var_name: str) -> str:
```

2024-04-24 14:13 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +            The striped variable name.
```suggestion
            The stripped variable name.
```

2024-04-24 14:13 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +            slice_end: int = -1 if "=" in combined_var_name_list[-1] else len(combined_var_name_list)
I think these different cases should be explained in the notes section of the docstring, not with inline comments.

2024-04-24 14:13 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +                if graph_details.get("omit_legend_prefix", False):
I think it would help readability a little if these two conditions were put in there own variables.

2024-04-24 18:31 UTC, JoeWaddell reviewed
As a general observation and suggestion here: in reading the code (and testing!), I see the 'field=field' type suffix is being removed in this method.

This is misleading since the filter option only refers to the prefix. I could see renaming the filter option to `omit_legend_prefix_and_suffix`, but you could also separate the two out e.g. `omit_legend_prefix` and a new `omit_legend_suffix`, if it's not a big bother, since maybe there's utility in keeping the suffix (though that's more a question for @Isgotkowitz )

2024-04-24 18:31 UTC, JoeWaddell commented on RUFAS/graph_generator.py
> +            slice_end: int = -1 if "=" in combined_var_name_list[-1] else len(combined_var_name_list)
Agreed: some explanation of what other edge cases you're handling here (e.g. it would be good to explain why you're searching for `([A-Z][a-z0-9]+)+` and `=`).

2024-04-24 18:31 UTC, JoeWaddell commented on tests/test_graph_generator.py
> +    actual_output = graph_generator._generage_legend_keys(combined_var_input)
```suggestion
    actual_output = graph_generator._generate_legend_keys(combined_var_input)
```

2024-04-25 19:51 UTC, JoeWaddell commented on RUFAS/graph_generator.py
> +            list(FIGURE_SETTERS.keys()) + list(AXES_SETTERS.keys()) + ["variables", "omit_legend_prefix"]
Should include `omit_legend_suffix` as well, right?

2024-04-25 19:54 UTC, JoeWaddell commented on RUFAS/graph_generator.py
> +
To avoid the MyPy error about lacking a return statement (since this doesn't cover a combined_var_name_list length of 0 or less), should there be a final `else` statement that doesn't do any prefix/suffix removal, and logs that there was an unexpected length?

2024-04-25 20:26 UTC, JoeWaddell approved these changes
Works well (tested multiple options with modified calls to om), and the code is clean. Easy approval assuming the comments are handled.

Also: reminder to update the changelog to reflect that there's an option to omit the suffix, as well. Likewise for any documentation that needs to be updated.

2024-04-25 20:26 UTC, JoeWaddell commented on tests/test_graph_generator.py
> +def test_generage_legend_keys(
```suggestion
def test_generate_legend_keys(
```

2024-04-26 16:45 UTC, Isgotkowitz commented
> As a general observation and suggestion here: in reading the code (and testing!), I see the 'field=field' type suffix is being removed in this method.
> 
> This is misleading since the filter option only refers to the prefix. I could see renaming the filter option to `omit_legend_prefix_and_suffix`, but you could also separate the two out e.g. `omit_legend_prefix` and a new `omit_legend_suffix`, if it's not a big bother, since maybe there's utility in keeping the suffix (though that's more a question for @Isgotkowitz )

Yes, the suffix can be very important when differentiating between the same variable but in different fields, soil layers, crops, etc.

2024-05-02 05:22 UTC, merged