Add disclaimer message to all output txt, JSON, and CSV files
RuminantFarmSystems/RuFaS pull request #1520
Opened 2024-04-10 14:52 UTC by allisterakun

This PR added a disclaimer message to all output txt, JSON, and CSV files and printed out the message to the console when the `LogVerbosity` is set to any level except None.
### Context

Issue(s) closed by this pull request: closes #1462. 

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What

Introduced a new function, `OutputManager._write_disclaimer()`, to write a line of disclaimer.
```python
    def _write_disclaimer(self, file_pointer: TextIO) -> None:
        """
        Writes the predefined disclaimer message to a given file.

        Parameters
        ----------
        file_pointer: TextIO
            A file-like object (supporting the `.write()` method) that points to the file where the disclaimer should
            be written.

        Example
        -------
        >>>
        ... with open('output.txt', 'w') as f:
        ...    self._write_disclaimer(f)
        """
```

Introduced a new function, `OutputManager.print_disclaimer()`, to print the disclaimer message to stdout if the `LogVerbosity` is set to any level except None.
```python
    def print_disclaimer(self) -> None:
        """
        Prints out the disclaimer message when LogVerbosity is set to any level except None.
        """
```

Introduced a new function, `OutputManager._remove_disclaimer_from_input_file`, to handle the issue of disclaimer message breaking the loading pool.
```python
    def _remove_disclaimer_from_input_file(self, file_path: Path) -> str:
        """
        Read the input data file, remove the disclaimer message is it is present on the first line.

        Parameters
        ----------
        file_path : Path
            The path to the file to be loaded to the variables pool.

        Returns
        -------
            The input file content joined into a string
        """
```

### Why

To add and print a disclaimer message.

### How

Modifying all data to file methods to call this function to add the disclaimer.

### Test plan

All affected tests are updated.

2024-04-10 15:42 UTC, ew3361zh requested changes
Looks good for the most part. A couple of things that need to get updated:

1. According to the issue, the disclaimer should print out after the credits (for all LogVerbosity >= credits).
2. One way we use json files is to rerun a set of results back through OM to do further processing (graphs, reports, filtering, etc) and if that first line is there in a json file used for this purpose, it will error. What do you think about adding something to the end of the disclaimer in json files that says to remove it if the user needs the results for reprocessing? Or adding it to json files in a way that wouldn't affect a user running the `--load-pool` gnu arg option with the file? Maybe there's a better solution as well - just my initial thought.

2024-04-23 17:19 UTC, ew3361zh reviewed
This is looking good and was working but there's a new function `_remove_disclaimer_from_input_file()` that isn't used at all. Is this for potential txt input files?

I think for json input files we'd discussed maybe not even needing to remove the disclaimer since it's a dictionary k-v pair and will be filtered out. I don't think we have the capacity to load csv/txt files for further processing at this time so maybe not necessary to have this new function?

I think if this function gets accounted for then I'm good to approve.

2024-04-23 17:19 UTC, ew3361zh commented on RUFAS/output_manager.py
> +        print(df)
remove print statement

2024-04-23 17:19 UTC, ew3361zh commented on RUFAS/output_manager.py
> +    def _remove_disclaimer_from_input_file(self, file_path: Path) -> str:
This function doesn't look like it's used at all.

2024-04-23 21:17 UTC, ew3361zh approved these changes
LGTM, nice work, Allister!

2024-04-24 05:12 UTC, ltp23 approved these changes
Looks good to me. I left a couple of comments. Thanks Allister!

2024-04-24 05:12 UTC, ltp23 commented on RUFAS/output_manager.py
> +        """
This example is not working yet and has the side-effect of creating a new file. A workaround is to use a throwaway string that acts as a file.

```
Examples
--------
>>> output_manager = OutputManager()
>>> import io
>>> file_like_string = io.StringIO()
>>> output_manager._write_disclaimer(file_like_string)
>>> assert file_like_string.getvalue() == DISCLAIMER_MESSAGE + "\\n"
```

2024-04-24 05:12 UTC, ltp23 commented on RUFAS/output_manager.py
This will cause repeated disclaimer messages in the first column.

```
DISCLAIMER,Column1,Column2  ...
This is a disclaimer message,Value1,Value2   ...
This is a disclaimer message,Value3,Value4   ...
...
```

I think we may want to keep only one value.

```
df = pd.concat(csv_columns, axis=1)
disclaimer_column = [DISCLAIMER_MESSAGE] + [""] * (len(df) - 1)
disclaimer_df = pd.DataFrame({"DISCLAIMER": disclaimer_column})
df = pd.concat([disclaimer_df, df], axis=1)
```

2024-04-24 05:40 UTC, merged