[OM] [Refactor] Remove duplicate filtering function in GG and RG
RuminantFarmSystems/RuFaS pull request #1550
Opened 2024-04-16 04:53 UTC by allisterakun

This PR removes the duplicate filtering functions in GG and RG by moving the filter process upstream into the OM
### Context

Issue(s) closed by this pull request: closes #1387.

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What

1. Removes `GraphGenerator._prepare_plot_data()` and `ReportGenerator._prepare_report_data_with_constants()` as they have the same functionality. 
2. Extends `OutputManager.filter_variables_pool()` with the functionalities from the above functions. 
3. Creates a `_log_non_int_float_data()` function in GraphGenerator to log the non-numerical data, which was originally handled in the removed  `GraphGenerator._prepare_plot_data()`.

### Why

To remove duplicate filtering functions in GG and RG by moving the filtering process upstream into the OM.

### How

Move the filtering process into the OM.

### Test plan

All affected unit tests have been updated.
New unit tests are written for the extended `OM.filter_variables_pool()` function to account for the new scenarios that result from the addition of functionalities.
Tested with different filters (graph, report, CSV, JSON), and they all work as expected.

2024-04-18 19:03 UTC, Isgotkowitz requested changes
Requesting changes on one thing, all other comments are suggestions.

When a report tries to graph something, it doesn't check if it is trying to graph any non-numerical data. Observe the behavior while plotting this graph:
```json
{
    "multiple": [
        {
            "title": "Implement Graph",
            "filters": [
                "TillageApplication._record_tillage.tillage_record.field='field'"
            ],
            "variables": [
                "implement"
            ],
            "type": "plot"
        }
    ]
}
```
vs this report:
```json
{
    "mulitple": [
        {
            "name": "Implement Graph",
            "filters": [
                "TillageApplication._record_tillage.tillage_record.field='field'"
            ],
            "variables": [
                "implement"
            ],
            "slice_start": -365,
            "graph_and_report": true,
            "graph_details": {
                "type": "plot"
            }
        }
    ]
}
```

Also, one strange thing about python is that bools are considered ints, so if you try to plot a bool it will plot `True` as 1 and `False` as 0. Not sure if this is a bug or feature, but it does allow the plotting of boolean outputs in RuFaS and I thought this was worth mentioning.

2024-04-18 19:03 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +    def _log_non_int_float_data(
```suggestion
    def _log_non_numerical_data(
```
This might be a cleaner name.

2024-04-18 19:03 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
Docstring for return type needs to be updated.

2024-04-18 19:03 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +            log_pool = self._log_non_int_float_data(filtered_pool, graph_details)
```suggestion
            log_pool = self._log_non_int_float_data(filtered_pool, graph_details)
```
I think a more specific name for "log_pool" would be better, something more like "non_numeric_data_logs"

2024-04-18 19:03 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +            key
Two things to consider here:
1. It might be good to create the log message here in the list comprehension, so that there doesn't have to be a loop over `non_int_float_keys`.
2. When recording the key, it would also be nice to record the type of the non-numerical key and put that in the error message as well.

2024-04-18 19:03 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +    ) -> Dict[str, List[float]] | None:
Could you update the docstring to reflect why/when this can return None?

2024-04-19 17:40 UTC, ltp23 commented on RUFAS/output_manager.py
> +    def filter_variables_pool(self, filter_content: Dict[str, Any]) -> Dict[str, pool_element_type]:
Can you update the docstring for this method?

2024-04-19 17:40 UTC, ltp23 commented on RUFAS/output_manager.py
> +        use_filter_name: bool = filter_content.get("use_name", False)
Is this a new feature?

I'm testing out this example, but it is not working yet. I think because the keys are overwritten due to the counter not being updated.

```
{
  "multiple": [
    {
      "name": "Daily Herd Structure Graph and Report",
      "filters": [
        "AnimalManager._record_animal_counts.num_animals",
        "AnimalManager._record_animal_counts.num_heiferIIs",
        "AnimalManager._record_animal_counts.num_lactating_cows"
      ],
      "use_name": true,
      "graph_and_report": true,
      "graph_details": {
        "type": "plot"
      }
    }
  ]
}

2024-04-19 17:40 UTC, ltp23 commented on RUFAS/output_manager.py
> +        counter: int = 0
This counter should be incremented. Otherwise, key-value pairs would be overwritten.

2024-04-19 17:40 UTC, ltp23 commented on RUFAS/output_manager.py
> +                    results[key] = {"values": sliced_data}
Can you extract this block and the block at 913-920 into a separate method, just to de-nest the outer for loop by one level? If you can de-nest even further that would be great too.

2024-04-24 07:03 UTC, ltp23 approved these changes
LGTM. It works as expected now. Thanks Allister. Good job!

2024-04-24 16:01 UTC, Isgotkowitz reviewed
I think this works as expected and is pretty much good to go.

One thing I noticed though while trying out different filters was that I was getting this warning message a lot:
"[24-Apr-2024_Wed_11-58-45.476595][WARNING][default] Can't plot data for produce_graphics. Invalid filter file key 'produce_graphics' does not matchany optional keys. Please see Graph Generator wiki for a list of valid filterkeys.
[24-Apr-2024_Wed_11-58-45.476633][WARNING][default] Can't plot data for metadata_prefix. Invalid filter file key 'metadata_prefix' does not matchany optional keys. Please see Graph Generator wiki for a list of valid filterkeys."

I believe it has to do with the method `_prepare_report_data_to_be_graphed` in `ReportGenerator`, so I think if that gets fixed this should be perfect.

2024-04-24 16:01 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +    ) -> List[Dict[str, str | Dict[str, str]]] | List[Dict[str, Collection[str]]]:
This return type should be annotated and explained in the docstring.

2024-04-24 16:02 UTC, Isgotkowitz approved these changes

2024-04-25 14:17 UTC, merged