[Feed Storage] Feed Storage Scientific documentation
RuminantFarmSystems/RuFaS pull request #1551
Opened 2024-04-16 17:01 UTC by Isgotkowitz

This PR adds a first iteration of Feed Storage Scientific documentation to the `docs` folder, and changes `index.rst` so that it is visible after generating the documentation with Sphinx.

It should be noted that the document is titled "Feed Storage Scientific Documentation", but it is only a start to the scientific documentation and not the final finished product.

### Context

Issue(s) closed by this pull request: None

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### Test Plan
Run the following commands within the `docs` directory:
```sh
$ make clean
```
then 
```sh
$ make html
```
(or make.bat if you're on Windows) and check the newly generated html documentation. The Feed Storage Scientific Documentation should be available to view underneath the title "Scientific Documentation".

2024-05-06 19:00 UTC, PooyaHekmati requested changes
We do not accept md files in docs, only RST. Also, subdirectories are not ok. `docs_sc` is also an anomaly that needs to be fixed.
The purpose of this folder is to host the raw files for the Sphinx engine. Therefore, all documents have to be inter-linked and accessible via index tree. Majority of the files are to inform the autogeneration process from docstrings. Manual additions are welcome, but have to adhere to the general pattern in fit into the big picture.

2024-05-06 21:01 UTC, Isgotkowitz commented
> We do not accept md files in docs, only RST. Also, subdirectories are not ok. `docs_sc` is also an anomaly that needs to be fixed. The purpose of this folder is to host the raw files for the Sphinx engine. Therefore, all documents have to be inter-linked and accessible via index tree. Majority of the files are to inform the autogeneration process from docstrings. Manual additions are welcome, but have to adhere to the general pattern in fit into the big picture.

Ok, what would a good place to put this file (and `docs_SC`) be then? I think it would be nice to have it hosted on GitHub, as it makes it easier to track the history and check that documentation is getting updated alongside the code.

Would it be acceptable to make a new directory at the root called something like `scientific_documentation`, and place it there?

2024-05-08 15:02 UTC, KevinP-B approved these changes
Solid conversion of the design doc information and current progress to a trackable, git hosted doc. I'll leave file format and directory requirements for the project to Pooya's change request and sign off on content. Thanks, Ed!

2024-05-09 16:13 UTC, PooyaHekmati approved these changes

2024-05-10 17:11 UTC, merged