Deprecate `update_classes_in_pen`
RuminantFarmSystems/RuFaS pull request #1569
Opened 2024-04-21 20:55 UTC by 0luchi

### Context

Issue(s) closed by this pull request: closes #1208

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What
This PR deprecates the use of `classes_in_pen` in `pen.py` and replaces its instances with `self.animal_combination` and updates the corresponding test cases.

### Why
This change is a design decision following the integration of `AnimalCombination` in `pen.py`.

### How
Functions like `update_classes_in_pen` were removed to reflect this change.

### Test plan
The existing test cases were modified to reflect the changes made

2024-04-22 14:37 UTC, PooyaHekmati requested changes
I'm worried that writing "classes in pen" is misleading as I thought you were deprecating some classes. I recommend editing the title of this PR and its change log entry to capture the fact that you deprecating an attribute of a class.
Also, the newly introduced method `set_up_new_animal` is not mentioned in the PR description, nor in the change log. It also doesn't adhere to our coding guidelines and style (it's a long function with lots of comments and docstring is misformatted).

2024-04-22 15:21 UTC, 0luchi commented
@PooyaHekmati  
Thanks. I changed the PR name. And, you're right about the `set_up_new_animal` method being wordty. Although it shows I added it in the files changed, I didn't write that function. I created this branch a while ago and it seems that the method has been removed from main so I will take it out.

2024-04-23 15:58 UTC, Isgotkowitz requested changes
Found some places where the code could be cleaned up and places where the docstrings did not line up with the code. All changes that are made should be unit tested, and unit tests should be deterministic.

Also there should be at least one non-dev reviewer on this PR.

2024-04-23 15:58 UTC, Isgotkowitz commented on RUFAS/routines/animal/pen.py
> +        # self. = set()
```suggestion
```

2024-04-23 15:58 UTC, Isgotkowitz commented on RUFAS/routines/animal/pen.py
> +        True iff there is at least 1 animal in the pen, and false otherwise.
`populated` is never declared as an attribute of `Pen` - should it be or should it be removed from the docstring?

2024-04-23 15:58 UTC, Isgotkowitz commented on RUFAS/routines/animal/pen.py
> +            self.animal_grouping_scenario = AnimalGroupingScenario.CALF__GROWING_AND_CLOSE_UP__LACCOW
`animal_grouping_scenario` needs to be documented.

2024-04-23 15:58 UTC, Isgotkowitz commented on RUFAS/routines/animal/pen.py
>                      animal.calc_daily_walking_dist(self.vertical_dist_to_parlor, self.horizontal_dist_to_parlor)
```suggestion
        should_calc_walking_distance = (AnimalType.DRY_COW or AnimalType.LAC_COW in list(self.animal_grouping_scenario.values()) or self.animal_combination == 2 or self.animal_combination == 3 or self.animal_combination == 4
        if shoul_calc_walking_distance:  # CHECK
            for animal in list(self.animals_in_pen.values()):
                if type(animal).__name__ == "Cow":
                    animal.calc_daily_walking_dist(self.vertical_dist_to_parlor, self.horizontal_dist_to_parlor)
```
Why does it say "CHECK" here? Also the if statements can be combined.

2024-04-23 15:58 UTC, Isgotkowitz commented on RUFAS/routines/manure/pen_manure/manure_manager_pen.py
> +        ):
```suggestion
        pen_contains_cows = (
            self.animal_combination == AnimalCombination.LAC_COW
            or self.animal_combination == AnimalCombination.GROWING_AND_CLOSE_UP
            or self.animal_combination == AnimalCombination.CLOSE_UP
        )
        if pen_contains_cows:
```
When writing if statements, it is good to make the conditional its' own variable if it is not trivial

2024-04-23 15:58 UTC, Isgotkowitz commented on tests/test_manure_module/test_manure_manager_pen.py
> +    mock_pen.animal_combination = random.choice(animal_combinations) if has_cows else AnimalCombination.CALF
This test needs to be verify that this method will always run correctly. By randomly choosing cases, it is possible that not all test cases will be covered. Instead of randomly choosing a case, the animal combination should be a parameter of the test.

2024-04-23 15:58 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_manager.py
> +
Will `_determine_classes_in_pen` be used again? If not, then it should be removed from `AnimalManager`.

2024-04-23 15:58 UTC, Isgotkowitz commented on tests/animal_module_tests/test_pen.py
The test for `calc_daily_walking_dist` should be written to verify correct behavior.

2024-04-24 03:29 UTC, 0luchi commented on RUFAS/routines/animal/pen.py
>                      animal.calc_daily_walking_dist(self.vertical_dist_to_parlor, self.horizontal_dist_to_parlor)
The two if statements are two potential implementations that I made (I was going to pick one) which is why they both have "check" on them.

2024-04-24 16:17 UTC, 0luchi commented on RUFAS/routines/animal/animal_manager.py
> +
You're right. I'm taking it out

2024-04-26 11:50 UTC, Isgotkowitz commented on RUFAS/routines/animal/pen.py
>                      animal.calc_daily_walking_dist(self.vertical_dist_to_parlor, self.horizontal_dist_to_parlor)
Ok. In situations like that it is important to discuss the options with whoever can provide insight, then decide how you're gonna implement something, then implement it, then open up the PR for review. If you still unsure about it, then you can leave a comment in the PR and ask reviewers specifically if it would be better to do xyz there, for reasons abc.

2024-08-25 15:38 UTC, closed without merging