Add CIDR count to heiferII
RuminantFarmSystems/RuFaS pull request #1570
Opened 2024-04-21 22:02 UTC by 0luchi

### Context

Issue(s) closed by this pull request: closes #1217

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What
This PR adds `CIDR_count` to `heiferII.py` by adding it as a property and updating it when there is a `CIDR_injection`

### Why
This is important because it enables `CIDR_count` tracking for `lifecycle_manager.py` 

### How
I set `CIDR_injections` equal to `CIDR_count` as I assumed that every injection increments the CIDR level by 1 from [Repreoduction Refactoring design doc](https://docs.google.com/document/d/1Uro29xXOIfrNWv3jg5uy3FuC1FEQR3CGQaHnoyuKF8Q/edit)

### Test plan
I uncommented existing the existing test case in `test_animal_life_cycle.py` to confirm the functionality

2024-04-22 20:48 UTC, JoeWaddell requested changes
This is a tricky one to wrap my head around, and I think I wrote the issue as far simpler than it really is, my mistake! So I left a couple comments that hopefully make sense. I think it just needs to mimic the logic for the other injections, since `_execute_hormone_delivery_schedule` in `cow.py` uses the heiferII `_execute_hormone_delivery_schedule`...it's a little confusing, so don't take my suggestions as infallible: we can always ask Loi to help if we need to!

2024-04-22 20:48 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        self.CIDR_count += heiferII.CIDR_count
I think this should be a new attribute for a `LifeCycle` object, `CIDR_count_h` (in addition to the existing `CIDR_count`), to fit alongside the others below. The `_h` indicates that it's the count for heifers.

So here instead of assigning the value in `CIDR_count` to `CIDR_count_h`, it would add the value in `heiferII.CIDR_injections`.

Then in  `_extract_repro_stats_from_cow` you'd need to add similar logic (operating on a `cow` object, and assigning them to the `CIDR_count` attribute in LifeCycle)

2024-04-22 20:48 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/heiferII.py
> +        self.CIDR_count = self.CIDR_injections
I think this should just be initalized to 0, just to avoid confusion.

2025-06-11 14:27 UTC, KFosterReed commented
@JoeWaddell can you confirm if this branch, PR and the related issue can be deleted?

2025-06-12 14:57 UTC, JoeWaddell commented
> @JoeWaddell can you confirm if this branch, PR and the related issue can be deleted?

Confirmed! This functionality was added in the Refresh, for future reference see `_update_heifer_reproduction_statistics` in `herd_manager.py`, and the resetting of injections in `reset_daily_statistics` in `reproduction.py`, and also resetting of the CIDR_count in `herd_statistics.py`

2025-06-12 14:57 UTC, closed without merging