Quick fix for missing body weight history in ration driver
RuminantFarmSystems/RuFaS pull request #1574
Opened 2024-04-23 08:51 UTC by ltp23

### Context

Issue(s) closed by this pull request: closes #1564 

- [ ] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What

### Why

### How

- In `ration_driver`, when reporting failed constraints, if body weight history is missing, I set the simulation day to -1. I'm open to different alternatives. I also denested the `pen_requirements` key in the `fail_summary_units` by removing it.
- In `animal_module_reporter`, when padding data, there needs to be an exact mapping between the units and the values.

### Test plan

2024-04-24 13:44 UTC, jadamchick approved these changes
Thanks Loi - this runs smoothly for me and seems to avoid the error. I don't have much insight into the approach to the fix, so will let the SWE's weigh in on the approach. 
Also reminder to update the changelog :)

2024-04-26 18:29 UTC, JoeWaddell commented
Were you able to find out the reason some animals were lacking a body weight history? Was it just animals that were purchased on the same day as this check, or at the initialization of the sim?

2024-04-29 14:32 UTC, Isgotkowitz requested changes
It is good that this issue has a solution, but I think it would be better to find a more permanent solution. Some things to consider:
- It seems that the ration driver needs the simulation day to record when it fails. This means two things: it should report the correct simulation day (not -1) and it should get the simulation day from `Time`, which should be the single source of truth for time in a simulation.
- There is no explanation of why some animals have no body weight history, or any fix for it. Is it ok that some animals have no body weight history, or is it indicative that something is not working correctly upstream?
- There needs to be testing done.

2024-04-29 14:32 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_module_reporter.py
> +                {variable: 0 for variable in nutrient_amount.keys()},
```suggestion
                {key: val for key, val in nutrient_amount.items()},
```
I think this would be more correct than adding in 0. Same goes for all the other instances of adding in values.

2024-04-29 14:32 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +                simulation_day = animal_list[0].body_weight_history[-1].simulation_day
Why is this only checked for the first animal in the animal list? What if another animal in the list does have a bodyweight history?

Also, `simulation_day` is a recording of when this ration failure is happening, so it would definitely be incorrect to say that it is failing on day -1. It would be better to pass `Time` in and use the simulation day in there.

2024-05-14 19:21 UTC, ltp23 commented on RUFAS/routines/animal/animal_module_reporter.py
> +                {variable: 0 for variable in nutrient_amount.keys()},
I don't think this is correct because we want to pad the missing days with 0s when pens are created on the fly.

2024-05-14 19:28 UTC, ltp23 commented on RUFAS/routines/animal/ration/ration_driver.py
> +                simulation_day = animal_list[0].body_weight_history[-1].simulation_day
An alternative is to find latest simulation day among all the animals in the list.

Passing in a Time object and getting simulation day from it may or may not be what we want. The Time object will store the current day but the latest simulation days in the body weight histories may not coincide with the current day.

Though, having access to the current simulation day is good if the animal list is empty and we can use it as a fallback value.

2025-06-19 03:50 UTC, closed without merging