[OM] Make use of VM in OutputManager
RuminantFarmSystems/RuFaS pull request #1575
Opened 2024-04-23 09:09 UTC by allisterakun

Users can periodically dump the current variable pool and save a chunk into a JSON file. This will allow us to break down a larger simulation pool into smaller chunks.

### Context

Issue(s) closed by this pull request: closes #1513

Users can set the `chunkification` flag to Ture in the tasks input JSON file to enable the functionality.
Then users can specify one of the following in the tasks input JSON file for each task:
1. "save_chunk_threshold_call_count": 
      ```json
      {
        "type": "number",
        "description": "The threshold adds variable call count for saving the output variable pool chunk.",
        "default": 0
      }
      ```
      If this variable is specified, the OM will keep track of the number of calls to the `OM.add_variable()` function. Once it reaches the threshold number, the current variable pool will be dumped, and the other metrics will be ignored.
2. "maximum_memory_usage": 
      ```json
      {
        "type": "number",
        "description": "The maximum memory usage in Bytes.",
        "default": 0
      }
      ```
      If `save_chunk_threshold_call_count` is not specified but this variable, the OM will set `OM.max_pool_size` to the specified `maximum_memory_usage` amount. The OM will estimate the current pool size every time the `OM.add_variable()` function is called and check against the max pool size. If the threshold is reached, the current variable pool will be dumped.

      The OM will accumulate the average size addition per add_variable call to estimate the current pool size.

      If multiple workers are defined, the `TaskManager` will treat each task equally and evenly distribute the max_memory_usage to all tasks. This means if the max_memory_usage is 8 * (1024 **3) Bytes and there are 8 workers; each worker will get 1 * (1024 **3) Bytes of max memory
3. "maximum_memory_usage_percent": 
      ```json
      {
        "type": "number",
        "description": "The maximum percentage of memory use.",
        "default": 80
      }
      ```
      
      If neither `save_chunk_threshold_call_count` nor `maximum_memory_usage` is specified, we will use `maximum_memory_usage_percent` to determine the maximum memory usage by simply multiplying it with the available memory. The OM will estimate the current pool size the same way as the last section, and this percentage number is also evenly distributed across all workers.

Here is a logic diagram:
![image](https://github.com/user-attachments/assets/776a931b-5aae-40a2-bcd6-b27aac331c66)
https://whimsical.com/om-chunkification-32XPBmYkA5ncJmVytzLQdT

### Test plan

Updated and added new unit tests to cover all functions modified/added.

I changed the `input/data/tasks/default_task.json` to the following scenarios, they all run with no errors. 
```JSON
{
  "parallel_workers": 4,
  "tasks": [
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "default",
      "log_verbosity": "warnings",
      "random_seed": 42
    }
  ]
}
```
```JSON
{
  "parallel_workers": 4,
  "tasks": [
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "default",
      "log_verbosity": "warnings",
      "random_seed": 42,
      "chunkification": true,
      "maximum_memory_usage": 800000000
    }
  ]
}
```
```JSON
{
  "parallel_workers": 4,
  "tasks": [
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "default",
      "log_verbosity": "warnings",
      "random_seed": 42,
      "chunkification": true,
      "save_chunk_threshold_call_count": 1000000
    }
  ]
}
```
```JSON
{
  "parallel_workers": 4,
  "tasks": [
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "default",
      "log_verbosity": "warnings",
      "random_seed": 42,
      "chunkification": true
    }
  ]
}
```
I also compared the output results from the following filter, the results from all runs are identical.
```
^.*AnimalModuleReporter.report_ration_interval_data.avg_rqmts_pen.*$
```

The `average_add_variable_call_addition` is estimated to be 118 bytes per add_variable call. Throughout testing, I found this estimation to be quite accurate with usually less than 10% variance.

2024-06-06 13:45 UTC, ew3361zh commented
@allisterakun I wondered if you could write up how you tested this on your end and how you would suggest reviewers test it?

2024-06-06 13:49 UTC, allisterakun commented
> @allisterakun I wondered if you could write up how you tested this on your end and how you would suggest reviewers test it?

Will do!

2024-06-12 14:35 UTC, Isgotkowitz reviewed
I think this is a good start to finishing chunkification, but is gonna need some more work to iron out the kinks. Left a bunch of comments on things that I think could be improved.

I tried running this on the default scenario by changing "parrallel_workers" to 1, setting "chunkification" to true, and setting max memory usage percent to 10 (this should make it dump once for me on my VM). It seems that it got itself into an infinite loop though when I tried to run it (the cycle of logs that starts with "Attempting to create a new directory.." kept repeating):
![image](https://github.com/RuminantFarmSystems/MASM/assets/43901812/663e5c81-7a10-4c9c-bafb-7158459d64b7)

2024-06-12 14:35 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +                           f"{self.maximum_pool_size} Bytes"
For the `elif max_memory_usage` and `else` cases, I think it would be good to make the log messages distinct so that it is possible to tell from the log message which method was used to set the maximum pool size.

2024-06-12 14:35 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            f"saved_pool/{Utility.get_timestamp(include_millis=True)}"
Maybe it would be good idea to make the metadata prefix part of the directory name? I think it would make zero functional difference, but would help to make the newly created directories a little easier to understand.

2024-06-12 14:35 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            ):
I think these if conditions should be put into variables, then used in the if statement.

2024-06-12 14:35 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +        self.saved_pool_chunks_num = 0
This is initialized as zero in the init method, is there a need to reset it here?

2024-06-12 14:35 UTC, Isgotkowitz commented on RUFAS/task_manager.py
> +            0,
Just out of curiosity, do you anticipate chunkification ever being used for the Task Manager's Output Manager?

2024-06-12 14:35 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +        self.create_directory(self.saved_pool_chunks_path)
Create directory is called on `self.saved_pool_chunks_path` in `self._save_current_variable_pool`, does it need to be called in both places?

2024-06-12 14:35 UTC, Isgotkowitz commented on input/metadata/properties/tasks_properties.json
> +        "maximum_memory_usage_percent": {
Might be good to bound this input in the range [1, 100].

2024-06-12 14:35 UTC, Isgotkowitz commented on input/metadata/properties/tasks_properties.json
> +          "description": "Select this flag if you want to periodically dump the output variable pool.",
```suggestion
          "description": "Whether to periodically save the output variable pool to a file.",
```

2024-06-12 14:35 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            self.save_chunk_threshold_call_count: int | None = None
```suggestion
            self.save_chunk_threshold_call_count: int = 0
```
Maybe it would be better to have this be 0 as the marker that a different method for deciding when to dump the pool should be used? I don't think it would make a huge difference, but I'm guessing it will lead to fewer Mypy errors being generated, and since `run_startup_sequence` takes in an int to set this attribute I think it would be reasonable to just type it as an int.

2024-06-12 14:35 UTC, Isgotkowitz commented on input/metadata/properties/tasks_properties.json
> +          "default": 0
Also might be good to have upper and lower bounds here, but I'm not sure what an appropriate upper bound would be.

2024-06-12 14:35 UTC, Isgotkowitz commented on input/metadata/properties/tasks_properties.json
> +        },
And same thing about bounding here, although it might only need a lower bound.

2024-06-12 14:35 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            self.average_add_variable_call_addition: int | None = None
```suggestion
            self.average_add_variable_call_addition: int = 0
```
I think it is better to have this default to an int, I got a NoneType error when trying to run it with the default set to None.

2024-08-02 18:26 UTC, PooyaHekmati requested changes
This PR is stale. Please rebase and update to make it reviewable.

2024-08-28 07:30 UTC, allisterakun commented on RUFAS/output_manager.py
> +        self.create_directory(self.saved_pool_chunks_path)
Good point! Updated!

2024-09-02 16:31 UTC, Isgotkowitz reviewed
> If multiple workers are defined, the TaskManager will treat each task equally and evenly distribute the max_memory_usage to all tasks. This means if the max_memory_usage is 8 * (1024 **3) Bytes and there are 8 workers; each worker will get 1 * (1024 **3) Bytes of max memory

Wouldn't this only be true for multiple workers on the same task? If two different tasks have different inputs defined for chunkification, then the different workers assigned to them would have different thresholds for chunkification.

2024-09-02 16:31 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            self.maximum_pool_size: int = np.inf
These new attributes should be included in docstrings. I think this will be particularly helpful for `average_add_variable_call_addition`, because it will be a good place to explain what that number is and where it came from. Would it be worthwhile to have that value as configurable to user as well? If someone is running a different type of simulation they might be able to better tune this for their needs.

2024-09-02 16:31 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +        available_memory_gb = self.available_memory / (1024**3)
1024**3 should be a constant

2024-09-02 16:31 UTC, Isgotkowitz commented on RUFAS/task_manager.py
> +            Path(""),
Why move this to outside the try block?

2024-09-02 16:31 UTC, Isgotkowitz commented on input/metadata/properties/tasks_properties.json
> +        },
I think it would be good to note the hierarchical nature of these inputs: if `save_chunk_threshold_call_count` is provided, then that is what is used to determine when to chunk, otherwise it is maximum memory usage, otherwise it is max memory usage percent.

2024-09-03 16:26 UTC, allisterakun commented on RUFAS/task_manager.py
> +            Path(""),
I believe it was initially outside the try block. Another PR moved it into the try block. However, due to the changes made to this line, it did not get properly merged. I will move this into the try block. Great catch, Ed!

2024-09-05 13:48 UTC, ew3361zh commented on RUFAS/output_manager.py
> +        self.create_directory(self.saved_pool_chunks_path)
I'm not sure how the previous version was working but running it this way was creating a `saved_pool` dir at the same level as RUFAS

<img width="493" alt="Screenshot 2024-09-05 at 9 43 14 AM" src="https://github.com/user-attachments/assets/cf439a32-87d1-4d1d-b4d1-a33596024d42">

2024-09-05 13:57 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            self.average_add_variable_call_addition: int = 118
Why is this set to 118? I will second Ed that adding these to the docstrings would be helpful.

2024-09-05 13:58 UTC, allisterakun commented on RUFAS/output_manager.py
> +        self.create_directory(self.saved_pool_chunks_path)
Interesting, I will take a look!

2024-09-05 14:26 UTC, ew3361zh commented
Nice work, Allister!

One concern I have is over the reassembly of the data after chunkification. I ran this task:

```
{
  "parallel_workers": 4,
  "tasks": [
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "default",
      "log_verbosity": "errors",
      "random_seed": 42
    },
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "Task 2",
      "log_verbosity": "errors",
      "random_seed": 42,
      "chunkification": true,
      "maximum_memory_usage": 800000000
    },
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "Task 3",
      "log_verbosity": "errors",
      "random_seed": 42,
      "chunkification": true,
      "save_chunk_threshold_call_count": 1000000
    },
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "Task 4",
      "log_verbosity": "errors",
      "random_seed": 42,
      "chunkification": true
    }
  ]
}
```

And ran it with this report filter:
```
{
    "multiple": [
        {
            "name": "Calves",
            "filters": ["AnimalModuleReporter.report_daily_animal_population.num_calves"],
            "vertical_aggregation": "average",
            "slice_start": -365
           },
        {
            "name": "Heifers",
            "filters": ["AnimalModuleReporter.report_daily_animal_population.num_(heiferIs|heiferIIs|heiferIIIs)"],
            "vertical_aggregation": "average",
            "horizontal_aggregation":"sum",
            "horizontal_first": true,
            "slice_start": -365
           },
           {
            "name": "Dry cows",
            "filters": ["AnimalModuleReporter.report_daily_animal_population.num_dry_cows"],
            "vertical_aggregation": "average",
            "slice_start": -365
           },
           {
            "name": "Milking cows",
            "filters": ["AnimalModuleReporter.report_daily_animal_population.num_lactating_cows"],
            "vertical_aggregation": "average",
            "slice_start": -365
           },
           {
            "name": "Total cows",
            "filters": [
                "AnimalModuleReporter.report_daily_animal_population.num_cows_total"
            ],
            "vertical_aggregation": "average",
            "slice_start": -365
           }
    ]
}
```

And I got 3 different results.
Task 1 and task 4 were identical but tasks 2 and 3 got different results:

Task 1 and Task 4 (identical):
```
DISCLAIMER,Calves_ver_agg,Heifers_hor_ver_agg,Dry cows_ver_agg,Milking cows_ver_agg,Total cows_ver_agg
"Under construction, use the results with caution.",7.967123287671233,89.46027397260274,13.402739726027397,86.96164383561644,100.36438356164383
```
Task 2:
```
DISCLAIMER,Calves_ver_agg,Heifers_hor_ver_agg,Dry cows_ver_agg,Milking cows_ver_agg,Total cows_ver_agg
"Under construction, use the results with caution.",8.542465753424658,92.27945205479452,13.846575342465753,86.54931506849314,100.3958904109589
```
Task 3:
```
DISCLAIMER,Calves_ver_agg,Heifers_hor_ver_agg,Dry cows_ver_agg,Milking cows_ver_agg,Total cows_ver_agg
"Under construction, use the results with caution.",9.139726027397261,92.92785388127854,13.417351598173516,87.06849315068493,100.48584474885845
```

It may be the slicing that's affecting it.

2024-09-30 13:07 UTC, ew3361zh commented on RUFAS/output_manager.py
> +        self.create_directory(self.saved_pool_chunks_path)
This is now working correctly for me.

2024-09-30 14:15 UTC, Isgotkowitz reviewed
Unfortunately I found some differences between the same simulation after running with different settings. It seems like all the variables that are in the output file are the same between tasks, but one task is missing a couple of variables. Tasks:
```json
{
  "parallel_workers": 4,
  "tasks": [
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "test_1",
      "log_verbosity": "logs",
      "random_seed": 42
    },
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "test_2",
      "log_verbosity": "logs",
      "random_seed": 42,
      "chunkification": true,
      "maximum_memory_usage": 800000000
    }
  ]
}
```

<details>
<summary>Filter</summary>
<br>

```json
{
    "multiple": [
        {
            "name": "Count by pen",
            "filters": ["AnimalModuleReporter.report_daily_pen_total.*"],
            "vertical_aggregation": "average",
            "slice_start": -30
        },
        {
            "name": "Calves",
            "filters": ["AnimalModuleReporter.report_daily_animal_population.num_calves"],
            "vertical_aggregation": "average",
            "slice_start": -30
           },
        {
            "name": "Heifers",
            "filters": ["AnimalModuleReporter.report_daily_animal_population.num_(heiferIs|heiferIIs|heiferIIIs)"],
            "vertical_aggregation": "average",
            "horizontal_aggregation":"sum",
            "horizontal_first": true,
            "slice_start": -30
           },
           {
            "name": "Dry cows",
            "filters": ["AnimalModuleReporter.report_daily_animal_population.num_dry_cows"],
            "vertical_aggregation": "average",
            "slice_start": -30
           },
           {
            "name": "Milking cows",
            "filters": ["AnimalModuleReporter.report_daily_animal_population.num_lactating_cows"],
            "vertical_aggregation": "average",
            "slice_start": -30
           },
           {
            "name": "Total cows",
            "filters": [
                "AnimalModuleReporter.report_daily_animal_population.num_cows_total"
            ],
            "vertical_aggregation": "average",
            "slice_start": -30
           },
           {
            "name": "# Growing",
            "filters": [
                "AnimalModuleReporter.report_daily_animal_population.num_(heiferIs|heiferIIs)"
            ],
            "vertical_aggregation": "average",
            "horizontal_aggregation": "sum",
            "slice_start": -30
           },
           {
            "name": "# Close-up",
            "filters": [
                "AnimalModuleReporter.report_daily_animal_population.num_(heiferIIIs|dry_cows)"
            ],
            "vertical_aggregation": "average",
            "horizontal_aggregation": "sum",
            "slice_start": -30
           },
           {
            "name": "% L1",
            "filters": [
                "AnimalModuleReporter.report_life_cycle_manager_data.num_cow_for_parity_1",
                "AnimalModuleReporter.report_daily_animal_population.num_cows_total"
            ],
            "horizontal_aggregation": "division",
            "vertical_aggregation": "average",
            "horizontal_first": true,
            "horizontal_order": [
                "AnimalModuleReporter.report_life_cycle_manager_data.num_cow_for_parity_1",
                "AnimalModuleReporter.report_daily_animal_population.num_cows_total"
            ],
            "slice_start": -30
           },
           {
            "name": "% L2",
            "filters": [
                "AnimalModuleReporter.report_life_cycle_manager_data.num_cow_for_parity_2",
                "AnimalModuleReporter.report_daily_animal_population.num_cows_total"
            ],
            "horizontal_aggregation": "division",
            "vertical_aggregation": "average",
            "horizontal_first": true,
            "horizontal_order": [
                "AnimalModuleReporter.report_life_cycle_manager_data.num_cow_for_parity_2",
                "AnimalModuleReporter.report_daily_animal_population.num_cows_total"
            ],
            "slice_start": -30
           },
           {
            "name": "% L3",
            "filters": [
                "AnimalModuleReporter.report_life_cycle_manager_data.num_cow_for_parity_3",
                "AnimalModuleReporter.report_daily_animal_population.num_cows_total"
            ],
            "horizontal_aggregation": "division",
            "vertical_aggregation": "average",
            "horizontal_first": true,
            "horizontal_order": [
                "AnimalModuleReporter.report_life_cycle_manager_data.num_cow_for_parity_3",
                "AnimalModuleReporter.report_daily_animal_population.num_cows_total"
            ],
            "slice_start": -30
           },
           {
            "name": "% L4+",
            "filters": [
                "AnimalModuleReporter.report_life_cycle_manager_data.num_cow_for_parity_greater_than_3",
                "AnimalModuleReporter.report_daily_animal_population.num_cows_total"
            ],
            "horizontal_aggregation": "division",
            "vertical_aggregation": "average",
            "horizontal_first": true,
            "horizontal_order": [
                "AnimalModuleReporter.report_life_cycle_manager_data.num_cow_for_parity_greater_than_3",
                "AnimalModuleReporter.report_daily_animal_population.num_cows_total"
            ],
            "slice_start": -30
           },
           {
            "name": "Total milk, kg",
            "filters": ["AnimalModuleReporter.report_life_cycle_manager_data.daily_milk_production"],
            "vertical_aggregation": "sum",
            "slice_start": -30
           },
           {
            "name": "Milk per cow/d, kg",
            "filters": [
                "AnimalModuleReporter.report_life_cycle_manager_data.daily_milk_production",
                "AnimalModuleReporter.report_daily_animal_population.num_lactating_cows"
            ],
            "horizontal_aggregation": "division",
            "horizontal_order": [
                "AnimalModuleReporter.report_life_cycle_manager_data.daily_milk_production",
                "AnimalModuleReporter.report_daily_animal_population.num_lactating_cows"
            ],
            "horizontal_first": true,
            "vertical_aggregation": "average",
            "slice_start": -30
           },
           {
            "name": "% milk fat",
            "filters": ["AnimalModuleReporter.report_life_cycle_manager_data.herd_milk_fat_percent"],
            "constants": {
                "By 100": 100
            },
            "vertical_aggregation": "average",
            "horizontal_aggregation": "division",
            "slice_start": -30
        },
        {
            "name": "% milk protein",
            "filters": ["AnimalModuleReporter.report_life_cycle_manager_data.herd_milk_protein_percent"],
            "constants": {
                "By 100": 100
            },
            "vertical_aggregation": "average",
            "horizontal_aggregation": "division",
            "slice_start": -30
        },
        {
            "name": "Milk fat, kg",
            "filters": [
                "AnimalModuleReporter.report_life_cycle_manager_data.herd_milk_fat_kg"
            ],
            "vertical_aggregation": "sum",
            "slice_start": -30
        },
        {
            "name": "Milk protein, kg",
            "filters": [
                "AnimalModuleReporter.report_life_cycle_manager_data.herd_milk_protein_kg"
            ],
            "vertical_aggregation": "sum",
            "slice_start": -30
        },
        {
            "name": "weighted fat value",
            "cross_references": [
                "Milk fat, kg_ver_agg"
       [...]

2024-09-30 14:15 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            self.maximum_pool_size = (max_memory_usage_percent / 100) * self.available_memory
```suggestion
            self.maximum_pool_size = max_memory_usage_percent * GeneralConstants.PERCENTAGE_TO_FRACTION * self.available_memory
```

2024-10-02 19:48 UTC, ew3361zh commented
Trying to help figure out what's going on here but noticed and wanted to note that the variable_names files for tasks that use chunkification are showing up as empty for me when there are no output filters.

Maybe the reassembly of the pool should be done separate from the filtering process?

2024-10-28 18:45 UTC, ew3361zh commented
Updates:
- Rebuilds variables pool from chunk files and then applies filter as it would with a non-chunkified variables pool in `OM.save_results()`.
- Added `IM.flush_pool()` call to `TM.handle_post_processing()` to increase size of available memory prior to call to `OM.save_results()`.
- Fixed the units tests broken by the above changes.

2024-10-28 21:26 UTC, ew3361zh commented on RUFAS/output_manager.py
> +        available_memory_gb = self.available_memory / (1024**3)
Added.

2024-10-29 15:27 UTC, Isgotkowitz commented
Outside of how enum members are serialized, the vm features appear to be working correctly!

I tried running the following tasks:
```json
{
  "parallel_workers": 4,
  "tasks": [
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "default",
      "log_verbosity": "warnings",
      "random_seed": 42
    },
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "one",
      "log_verbosity": "warnings",
      "random_seed": 42,
      "chunkification": true,
      "maximum_memory_usage": 800000000
    },
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "two",
      "log_verbosity": "warnings",
      "random_seed": 42,
      "chunkification": true,
      "save_chunk_threshold_call_count": 1000000
    },
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "three",
      "log_verbosity": "warnings",
      "random_seed": 42,
      "chunkification": true
    }
  ]
}
```

The results were exactly the same for all the filters that I tested, with the exception of one variable which can be filtered with
```json
{
    "multiple": [
        {
        "name": "Yield",
        "filters": [
            "CropManagement._record_yield.harvest_yield.field='*'"
        ],
        "variables": [
            "crop"
        ]
        }
    ]
}
```

When run with no chunkification, this results in 
|DISCLAIMER|Yield_crop|
|--------------|-----------|
|Under construction, use the results with caution.|corn_grain|

But when run with chunkification (tasks one, two and three) it results in

|DISCLAIMER|Yield_crop._value_|Yield_crop._name_|Yield_crop.__objclass__|
|-|-|-|-|
|Under construction, use the results with caution.|corn_grain|CORN_GRAIN|{'_generate_next_value_': <function Enum._generate_next_value_ at 0x7f20692da830>,...|

To me, this suggests that the only problem with the VM feature is that when it serializes the pool to JSON it does it in a slightly different way than when results are written as part of a report.

2024-10-29 19:25 UTC, ew3361zh commented
> To me, this suggests that the only problem with the VM feature is that when it serializes the pool to JSON it does it in a slightly different way than when results are written as part of a report.

Good catch, Ed! I added handling for Enums in Utility.make_serializable() which addressed the issue.

2024-10-30 21:31 UTC, allisterakun commented
Thank you, Niko, for taking over this PR. I cannot approve this PR on GitHub since I am still the owner/original-author. Therefore, I will leave my approval in this comment.

> To me, this suggests that the only problem with the VM feature is that when it serializes the pool to JSON it does it in a slightly different way than when results are written as part of a report.

First, I confirm that a new commit has fixed this serialization issue.

I tried many other filters (JSON, TXT, and report), which all behaved as expected.

### Pool Comparison
I simulate with the following task_properties:
```JSON
{
  "parallel_workers": 4,
  "tasks": [
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "default",
      "log_verbosity": "errors",
      "random_seed": 42
    },
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "default_chunk",
      "log_verbosity": "errors",
      "random_seed": 42,
      "chunkification": true
    },
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "max_mem",
      "log_verbosity": "errors",
      "random_seed": 42,
      "chunkification": true,
      "maximum_memory_usage": 800000000
    },
    {
      "task_type": "SIMULATION_SINGLE_RUN",
      "metadata_file_path": "input/metadata/default_metadata.json",
      "output_prefix": "save_chunk_thresh",
      "log_verbosity": "errors",
      "random_seed": 42,
      "chunkification": true,
      "save_chunk_threshold_call_count": 1000000
    }
  ]
}
```

The pools are compared with DeepDiff using the following script:
<details>
  <summary> compare_json_diff.py </summary>
  
  ```python
  import json
  
  from deepdiff import DeepDiff
  
  default_pool_path = 'output/default_saved_pool.json'
  chunk_pool_path = 'output/saved_pool/default_chunk_29-Oct-2024_Tue_12-35-52.359088/' \
                    'default_chunk_saved_pool_0_29-Oct-2024_Tue_12-36-36.json'
  
  
  with open(default_pool_path, 'r') as file1, \
          open(chunk_pool_path, 'r') as file2:
      json_object1 = json.load(file1)
      json_object2 = json.load(file2)
  
  ddiff = DeepDiff(json_object1, json_object2, ignore_order=True)
  
  print(ddiff)
  ```

</details>

#### `default_chunck` pool vs `default` pool

I tried dumping the variable pool of the `default` run and comparing it against the saved pool on the `default_chunk` run (I set the parameter so there is only one chunk).

The result pools are almost identical except for some floating point variations after ~ten digits after the decimal point.

#### The rebuilt `max_mem` pool vs `save_chunk_thresh` pool

Like the previous process, I dumped the rebuilt variable pool after reloading it from the saved chunks on the `max_mem` run and the `save_chunk_thresh` run. The two rebuilt pools are also compared with the DeepDiff script. 

The results are identical to the previous process in that the two pools are the same except for the floating point variations. 
However, I did notice a size difference in the JSON files (310.55MB vs 309.83MB). I will make a script to compare the file character by character.

#### `default` pool vs. `save_chunk_thresh` pool

I checked the file sizes for all the dumped pools: 
- `default` pool: 314.5 MB
- `default_chunk` pool: 314.5 MB
- `max_mem` pool: 310.55 MB
- `save_chunk_thresh` pool: 309.83 MB

Given the significant difference of 5 MB, I compared the `default` pool and the `save_chunk_thresh` pool. 
The result is that the two pools are the same with only some floating point difference.

2024-10-31 18:49 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            ) or (self.save_chunk_threshold_call_count == 0 and self.current_pool_size >= self.maximum_pool_size):
Extract this into a more understandable boolean

2024-10-31 20:57 UTC, ew3361zh approved these changes
Approving based on reviews from both @allisterakun and myself.

2024-11-01 16:39 UTC, Isgotkowitz commented on changelog.md
> +- [1575](https://github.com/RuminantFarmSystems/MASM/pull/1575) - [minor change] [OutputManager] Adds options to periodically dump variables pool to a JSON file to help manage the size of the pool du
Please move this entry to the section under "Next Version Updates"

2024-11-01 16:51 UTC, Isgotkowitz commented
Had this discussion in-person with @ew3361zh:

I found that the flushing of `InputManager`'s pool messes with the E2E testing routine and causes it to fail. This is because the part of the E2E testing routine which compares actual and expected results* runs after the first post-processing routine and pulls data from the Input Manager.

There are a couple potential solutions:
1. Not flushing the Input Manager's pool at all.
2. Checking whether or not to flush IM's pool in TaskManager depending on the task type (if running E2E testing, don't flush input pool)
3. Grab the information E2E testing needs from IM before the pool is flushed, cache it, and pass it into the E2E results comparison routine when needed.

Each option has its pros and cons. My two cents is that 1 is the best option for right now, because it is the simplest and quickest way to get chunkification working with E2E testing. If we find that the data in the input pool is a limiting factor, we can revisit this and implement one of the other solutions.

*see compare_actual_and_expected_test_results in `e2e_test_results_comparer.py`.

2024-11-01 19:52 UTC, ew3361zh commented
> I found that the flushing of `InputManager`'s pool messes with the E2E testing routine and causes it to fail. This is because the part of the E2E testing routine which compares actual and expected results* runs after the first post-processing routine and pulls data from the Input Manager.

Top shelf catch, @Isgotkowitz! I went with option 2

`2. Checking whether or not to flush IM's pool in TaskManager depending on the task type (if running E2E testing, don't flush input pool)`

because I think it's the best option to try and accommodate the potential limited memory capacity for the user that this PR is trying to address.

Changes implemented:

- Added a new boolean arg `should_flush_im_pool` to `TM.handle_post_processing()` which defaults to `True`
- Updated the call to `TM._handle_simulation_engine_run_tasks()` to send a `False` value for `should_flush_im_pool` to `TM.handle_post_processing()` so that for the first part of end to end testing, the IM pool will not be flushed.
- Tested this with e2e (making the necessary adjustments to e2e config and metadata and then updating the results for feed storage) and it was successful.
- Also tested these changes against running the default single run simulation and it was successful.

2024-11-04 14:50 UTC, Isgotkowitz approved these changes
LGTM! Verified that End-to-End testing will be able to run without crashing, and that outputs for the same function with different chunkification settings will produce the same results.

2024-11-04 14:50 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +    average_add_variable_call_addition : int
```suggestion
    average_add_variable_call_addition : int, default 118
```

2024-11-04 14:50 UTC, Isgotkowitz commented on RUFAS/task_manager.py
> +        should_flush_im_pool: bool
```suggestion
        should_flush_im_pool: bool, default True
```
For this arg, it might be better to not give it a default value and force every caller to explicitly say whether or not the pool should be flushed. It just feels big/important enough that making it as explicit as possible might be better than the alternative.

2024-11-05 14:09 UTC, PooyaHekmati commented on RUFAS/general_constants.py
> +    # Hardware related
``` suggestion
    # Memeory related
```

2024-11-05 18:37 UTC, PooyaHekmati approved these changes

2024-11-08 15:26 UTC, Isgotkowitz approved these changes
Just looked at it again, the keyword args make it much clearer!

2024-11-08 18:00 UTC, merged