Validate Metadata and Properties
RuminantFarmSystems/RuFaS pull request #1584
Opened 2024-04-26 00:33 UTC by ew3361zh

IM now validates metadata and properties before validating input data.

### Context

Issue(s) closed by this pull request: closes #1333 #1332

- [ ] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What

Adds validation of properties:
1. `_validate_metadata()` method which validates the top level metadata (`files` section) - checks for required keys and checks the values for `path` and `type` to ensure they are valid.
2. `_validate_properties()` method which validates the depth of properties against established `metadata_depth_limit` which is based off the current deepest metadata properies.
3. For each set of properties for an array, bool, number, or string type, there is further validation that all the required keys are present for that property and that none of the keys present is invalid or unexpected. Additionally the values for defaults, minimums, maximums, patterns, etc are validated against the provided values to ensure there are no conflicts.

### Why

These validations can ensure the metadata and the associated properties used to validate the input data are themselves also valid.

### How

New functionality added as described above was added within the IM's `start_data_processing()` method to establish validity of the metadata before the properties are loaded and to establish validaty of the properties before the input data is loaded. Errors and logs are added to OM.

Additionally, some validity errors were raised during the process of setting up these validity checks and those were addressed within input data and properties sections. I did not exhaustively check all the other metadatas but can do so before merging.

### Test plan

Testing has been updated for much of the new functionality but some additional testing is still needed 100% coverage for IM. I'd suggest testing changes to required keys in both the metadata and properties. Also looking at changes to the depth of the properties (i.e. adding depth) or adjusting the `metadata_depth_limit` lower to see violations.

2024-04-29 15:30 UTC, Isgotkowitz requested changes
I think this is a good start towards having inputs that are not too deep, but there are more efficient routes that could be taken to realizing this goal. The big thing I am requesting changes on is checking the depth of the metadata properties, instead of checking the depths of the actual inputs - but if you feel that this would be a worse approach to take then we should take some time to discuss it.

2024-04-29 15:30 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        """
Docstring

2024-04-29 15:30 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                )
Instead of checking the actual input data, it would be much more efficient to check the metadata properties for 2 reasons: 
- The depth checking time will not fluctuate with the number of input files.
- Instead of checking every single array element, only the properties of that element would be checked.

2024-04-29 15:30 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +    def _check_max_depth(self, data: Any, current_depth: int = 0) -> Any:
I think this returns an int, not Any.

2024-04-29 15:30 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        Recursively find the maximum depth of nested dictionaries.
If possible/feasible, it would be worth considering if this would run more efficiently with an iterative approach instead of a recursive one.

2024-04-29 15:30 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        return max_depth
Instead of going all the way down until the bottom of the dict is reached, why not check if the max depth exceeds the limit and just fail as soon as it hits it?

2024-04-29 15:30 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            self.input_depth_limit = 5
This should be an attribute in the docstring.

2024-04-29 20:25 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        return max_depth
It's brought up a few questions for me which I can also check in with Pooya on but if you have thoughts, I'd be curious:
1. What are we expecting users to do with a failure on depth of the metadata properties file? 
2. What might be an appropriate failure message? 
3. Do we want to think of this to align with the "eager_termination" flag? - i.e. if someone is validating their input data, they'd probably want to know all the parts that violated the max depth but then if they're running a simulation, we'd have eager_termination on and it would fail at the first instance.

2024-04-29 20:30 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            self.input_depth_limit = 5
Looks like IM has no attributes in the docstring so I'll add them all.

2024-04-29 20:32 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        Recursively find the maximum depth of nested dictionaries.
Possibly. Recursing made more sense for input files. I'll need to think through what might work best with our metadata properties structure.

2024-04-30 13:22 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        return max_depth
> It's brought up a few questions for me which I can also check in with Pooya on but if you have thoughts, I'd be curious:
> 
> 1. What are we expecting users to do with a failure on depth of the metadata properties file?

Rewrite the metadata properties. Since this is a system that will work with what we currently have it won't come up until the input properties are being modified, which will happen when someone is working on a new feature.

> 2. What might be an appropriate failure message?

Similar to error messages for invalid data, something like `"Properties for input 'path.to.input' have greater than x level of nesting. These properties must be rewritten to be pass."`

> 3. Do we want to think of this to align with the "eager_termination" flag? - i.e. if someone is validating their input data, they'd probably want to know all the parts that violated the max depth but then if they're running a simulation, we'd have eager_termination on and it would fail at the first instance.

I think that would be a nice feature.

Also, definitely good to check with Pooya about this stuff. Everything I have said has been based on my recollections of conversations we had about this issue, but it would be good to get everyone on the same page about what the behavior is going to be.

2024-05-03 12:04 UTC, allisterakun commented
During group review session:
- We went through and tested the current code, and it seems to work with no issues.
- @ew3361zh will contact @PooyaHekmati to confirm how we want to traverse the metadata properties so that we can accurately represent the depth (length of path) of a variable in the input data.
- Potentially, we want to make a general function to traverse the metadata properties for validation and have this feature be one of the checks. Other checks may include: making sure all variables have a "type" property defined, making sure the properties of object and array variables follow the standard structure, validating if the provided default value of a variable is valid, checking if there are any extra unknown keywords...

2024-05-08 16:49 UTC, allisterakun reviewed
Generally looks good. As Ed mentioned, I do believe this PR should be split into at least two PRs.

2024-05-08 16:49 UTC, allisterakun commented on RUFAS/input_manager.py
> +            if invalid_keys:
```suggestion
            if invalid_keys := (data.keys() - valid_keys):
```

2024-05-08 16:49 UTC, allisterakun commented on RUFAS/input_manager.py
> +                missing_keys = required_keys - data.keys()
```suggestion
            if missing_keys := (required_keys - data.keys()):
```

2024-05-08 16:49 UTC, allisterakun commented on RUFAS/input_manager.py
> +                deepest_path = path
```suggestion
        current_max_depth = 0
        deepest_path = []

        type_to_validator_map: Dict[str, Callable] = {
            "number": self._metadata_number_validator,
            "array": self._metadata_array_validator,
            "bool": self._metadata_bool_validator,
            "string": self._metadata_string_validator,
        }
        while stack:
            current_obj, depth, path = stack.pop()

            if depth > self.metadata_depth_limit:
                om.add_error(
                    "Max metadata depth exceeded.",
                    "Metadata depth exceeds maximum allowed depth of " f"{self.metadata_depth_limit} at path {path}",
                    info_map,
                )
                raise ValueError(
                    "Metadata depth exceeds maximum allowed depth of " f"{self.metadata_depth_limit} at path {path}"
                )

            if depth > current_max_depth:
                current_max_depth = depth
                deepest_path = path
```
maybe rename this local variable to avoid confusion with `self.metadata_depth_limit`

2024-05-08 16:49 UTC, allisterakun commented on RUFAS/task_manager.py
> +            print("right before the exception")
```suggestion
```
remove print statement

2024-05-08 16:49 UTC, allisterakun commented on input/metadata/properties/default.json
> +        "default": 0.87
```suggestion
        "default": 0
```
restore the original value

2024-05-08 16:49 UTC, allisterakun commented on input/metadata/properties/default.json
>        "description": "Size of the field.",
```suggestion
      "description": "Size of the field.",
      "units": "ha",
```
Restore the previous state

2024-05-08 16:57 UTC, ew3361zh commented on input/metadata/properties/default.json
> +        "default": 0.87
This one is an incorrect default which falls outside the minimum-maximum range. I confirmed the new value with Joe but will document this in the new PR for validating properties.

2024-05-08 16:57 UTC, ew3361zh commented on input/metadata/properties/default.json
>        "description": "Size of the field.",
Confirmed change that should be happening in metadata properties - "units" is not a valid key and we shouldn't be tracking it in the metadata. Will document this though in the new PR.

2024-05-21 16:59 UTC, ew3361zh commented
Divided up into separate PRs #1637 and #1640.

2024-05-21 16:59 UTC, closed without merging