[IM] Fixed modifiability check during initialization
RuminantFarmSystems/RuFaS pull request #1589
Opened 2024-04-29 13:07 UTC by allisterakun

The modifiability check was accidentally removed. This PR fixes it for the `IM.populat_pool()` call during initialization.
### Context

Issue(s) closed by this pull request: closes #1565 

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.

### What

Introduced a new `IM._extract_input_data_by_key_list()` function:
```python
    def _extract_input_data_by_key_list(self,
                                        input_data: List[Any] | Dict[str, Any],
                                        variable_path: Sequence[str | int],
                                        variable_properties: Dict[str, Any],
                                        called_during_initialization: bool) -> Any:
        """
         Extracts a value from the input data based on a specified path and handles missing data by calling
         InputManager._log_missing_data().

        Parameters
        ----------
        input_data : List[Any] | Dict[str, Any]
            The input data containing the value to be extracted.
        variable_path : List[str | int]
            A list of keys to be used to extract the value from the input data.
        variable_properties : Dict[str, Any]
            The metadata properties for the variable being validated.
        called_during_initialization: bool
            Boolean variable indicating whether the function is being called during initialization.

        Returns
        -------
        Any
            The value extracted from the input data if found.
            None if not found.
        
        Notes
        -----
        This function navigates through the given input data (which can be a list or a dictionary) following the path
        specified in `variable_path`. If the path leads to a value, it is returned.
        If a KeyError occurs during this process (i.e., a key or index is missing in the path), the function extracts
        the variable name by finding the last string element in the `variable_path` array and handles this missing data
        by calling InputManager._log_missing_data().
        """
```
When retrieving the input data, the validator functions will call `IM._extract_input_data_by_key_list()` instead of calling `IM._extract_value_by_key_list()` to handle the possible missing data situiation.

### Why

The missing input data situation is improperly handled in the IM validation process; the modifiability is not checked.

### How

By calling the new `IM._extract_input_data_by_key_list()` function, if encountering a missing data situation, it will call `InputManager._log_missing_data()` to check the modifiability and properly handle the situation.

### Test plan

All affected unit tests are updated. 
Wrote new tests for the new `InputManager._extract_input_data_by_key_list()` function to bring the coverage for IM to 100%.
![image](https://github.com/RuminantFarmSystems/MASM/assets/39185942/b9038fc1-593e-4483-935a-f661306c07d6)

2024-04-29 16:56 UTC, Isgotkowitz requested changes
If the `modifiability` of an input is `unrequired unlocked` in the metadata properties and is missing at initialization, the Input Manager will still say that the input is required at runtime. Which I believe is not the correct behavior, but I am not actually sure. 

Also, there aren't any uses of modifiability in the metadata properties, and no mention of it in the Wiki page. I think this would be a good opportunity to revisit its use and documentation.

2024-04-29 16:56 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +         InputManager._log_missing_data().
```suggestion
        Extracts a value from the input data based on a specified path and handles missing data by calling
        InputManager._log_missing_data().
```

2024-04-29 16:56 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            var_name: str = [name for name in reversed(variable_path) if type(name) == str][0]
Instead of just using the variable name, I think it would be better to use `_convert_variable_path_to_str` and have the result it produces be the var name. This makes errors that are logged downstream much easier to understand.

2024-05-02 13:15 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                    called_during_initialization=True,
If we're setting it to True here, I think we should probably remove the default False value for it in _log_missing_data() (and probably not have a default value for it unless there's a good reason).

2024-05-02 13:16 UTC, allisterakun commented on RUFAS/input_manager.py
> +                    called_during_initialization=True,
Will update that!

2024-05-02 13:46 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                    called_during_initialization=True,
I'm also curious about it having a default value of False in all the `type_to_validator` functions.

2024-05-02 13:59 UTC, ew3361zh commented
I'm curious if it would work to add `called_during_initialization` to the args and then call `_extract_value_by_key_list()` instead of making this wrapper `_extract_input_data_by_key_list()` function?

2024-05-02 14:03 UTC, allisterakun commented
> I'm curious why it wouldn't work to just call `_extract_value_by_key_list()` instead of making this wrapper `_extract_input_data_by_key_list()` function?

Because `_extract_value_by_key_list()` is also used by other parts of the OM (e.g., extracting metadata). Instead of having a try-except block for all calls to `_extract_value_by_key_list()` for extracting input data, I made this wrapper `_extract_input_data_by_key_list()` function to handle the exception of missing input data specifically.

2024-05-02 21:36 UTC, Isgotkowitz approved these changes
LGTM, works as expected.

2024-05-02 21:36 UTC, Isgotkowitz commented on README.md
Whatever the new error is, it should be corrected.

2024-05-02 21:38 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            var_name: str = [name for name in reversed(variable_path) if type(name) == str][0]
This hasn't been changed, is this deliberate or should this be changed?

2024-05-03 17:47 UTC, ew3361zh approved these changes
LGTM, I had one suggestion which is to remove the default values for `called_during_initialization` in the validate by type functions since I think we have it set correctly now at the higher level and the defaults at the lower level could lead to unindended results. Nice work!

2024-05-08 15:27 UTC, merged