Adding str() method to unit enum class
RuminantFarmSystems/RuFaS pull request #1606
Opened 2024-05-02 21:27 UTC by ltp23

### Context

Issue(s) closed by this pull request: closes #1549 

- [ ] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

In this PR, I want to add a str() method for the units enum class so that when a units enum member is stringified, its value is returned instead of the default cumbersome dictionary string.

### Why

It'd be nice to simplify the usage of the units enum class by just when listing units in info maps.

### How

- Added a `__str__()` method in the `MeasurementUnits` enum class.
- Removed the use of `.value` when listing the units in the info maps.
- The `_validate_units()` method will convert a MeasurementUnits enum member into its 
corresponding string value.

### Test plan

- Make sure units still show up in csv and json output files.

2024-05-06 17:29 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            raise ValueError(f"'{units}' is not a valid MeasurementUnits value.")
Can this ValueError be reached?

2024-05-06 17:32 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            )
Why is this in this PR and what is it doing?

2024-05-06 17:41 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            raise TypeError(
Also log error to OM

2024-05-06 17:59 UTC, ew3361zh commented
A `.value` for a unit still present.

`animal_module_reporter.py` line 255:
```
AnimalModuleReporter.data_padder(
                f"{classname}.{funcname}.MEdiet_pen_0_CALF",
                f"{classname}.{funcname}.MEdiet_pen_{pen.id}_{pen.animal_combination.name}",
                0,
                simulation_day,
                info_map,
                MeasurementUnits.KILOGRAMS.value,
            )
```

2024-05-06 18:01 UTC, ew3361zh commented
A bunch in the`fail_summary_units` dict in `ration_driver.py` line 284:

```
fail_summary_units = {
            "simulation_day": MeasurementUnits.SIMULATION_DAY.value,
            "reattempt number": MeasurementUnits.UNITLESS.value,
            "constraints_failed_dict": MeasurementUnits.UNITLESS.value,
            "ration_attempted": MeasurementUnits.UNITLESS.value,
            "pen requirements": {
                "NEmaint_requirement": MeasurementUnits.MEGACALORIES.value,
                "NEa_requirement": MeasurementUnits.MEGACALORIES.value,
                "NEg_requirement": MeasurementUnits.MEGACALORIES.value,
                "NEpreg_requirement": MeasurementUnits.MEGACALORIES.value,
                "NEl_requirement": MeasurementUnits.MEGACALORIES.value,
                "MP_requirement": MeasurementUnits.GRAMS.value,
                "Ca_requirement": MeasurementUnits.GRAMS.value,
                "P_req": MeasurementUnits.GRAMS.value,
                "DMIest_requirement": MeasurementUnits.KILOGRAMS.value,
                "avg_BW": MeasurementUnits.KILOGRAMS.value,
                "avg_milk_production_reduction_pen": MeasurementUnits.KILOGRAMS.value,
            },
        }
```

2024-05-06 18:02 UTC, ew3361zh commented
`feed.py` line 208:

```
nutrient_dict_units = {
                "carbon": MeasurementUnits.KILOGRAMS.value,
                "nitrogen": MeasurementUnits.KILOGRAMS.value,
                "phosphorus": MeasurementUnits.KILOGRAMS.value,
                "dry_matter": MeasurementUnits.KILOGRAMS.value,
                "crude_protein": MeasurementUnits.KILOGRAMS.value,
                "carbon_loss": MeasurementUnits.KILOGRAMS.value,
                "crude_protein_loss": MeasurementUnits.KILOGRAMS.value,
            }
```

2024-05-06 18:03 UTC, ew3361zh commented
All references in `manure_handler_daily_output.py`, `manure_nutrients.py`, `manure_separator_daily_output.py`, `manure_trreatment_daily>output.py`, `pen_manure.py`, `reception_pit.py` need to be updated as well.

2024-05-08 15:29 UTC, ltp23 commented on RUFAS/output_manager.py
> +            raise ValueError(f"'{units}' is not a valid MeasurementUnits value.")
Right, I will remove the ValueError check because a ValueError would have been raised at the point of usage from some place else.

2024-05-08 15:53 UTC, ltp23 commented on RUFAS/output_manager.py
> +            raise TypeError(
Okay. I will add an error log entry for this.

2024-05-08 16:15 UTC, ltp23 commented on RUFAS/output_manager.py
> +            )
So if you run the main branch, you should notice the units are not included in the output. The units are located inside the info maps but the info maps are not being filtered along with their corresponding values.

2024-05-09 21:53 UTC, Isgotkowitz approved these changes
Looks good, and functions as expected. Before merging, I think the code that changes the info maps filtering should be taken out and left to #1638.

I left one suggestion about changing the behavior of validate_units back to its original behavior, but that is take it or leave it.

2024-05-09 21:53 UTC, Isgotkowitz commented on RUFAS/output_manager.py
>              If any unit or nested unit is not a valid MeasurementUnits value.
```suggestion
```

2024-05-09 21:53 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +    def _validate_units(self, units: Dict[str, Any] | MeasurementUnits) -> Dict[str, Any] | str:
Instead of having the behavior of this method change, I think it would be better to keep it as just a validator for units and put the responsibility of stringifying the units be on whatever library is writing it to a text file. This does get a little more tricky to get the units printing correctly though (because of the JSON library) but the following steps can be taken:
- have `MeasurementUnits` inherit `str`
- add the argument `ensure_ascii=False` to the `json.dump` method calls in OutputManager.

This is just a suggestion though, not a necessary change. If you keep it like this, I would just suggest changing the name to "stringify_units" - because it would be a little more reflective of what it is actually doing.

2024-05-13 13:21 UTC, ew3361zh requested changes
Hey Loi, updates to the PR are looking good. 

I'm still seeing the `.value` for MeasurementUnits instances in a few places that I'd mentioned in comments prior. Are they not supposed to be changed for some reason?
1. Line 255 in `animal_module_reporter.py`.
2. Line 306 in`ration_driver.py` for each of the units in the `fail_summary_units` dict.
3. Line 208 in `feed.py` for each of the units in the `nutrient_dict_units` dict.

2024-05-13 17:57 UTC, ltp23 commented on RUFAS/output_manager.py
>              If any unit or nested unit is not a valid MeasurementUnits value.
Actually, I already removed the ValueError check.

2024-05-13 19:40 UTC, ltp23 commented on RUFAS/output_manager.py
> +    def _validate_units(self, units: Dict[str, Any] | MeasurementUnits) -> Dict[str, Any] | str:
`MeasurementUnits` is an Enum class, so switching to it to inheriting from the str class is quite a change and would lose the automatic membership check or some workaround would be needed. 

Whenever we add a variable to the variables pool, we recursively validate and stringify the corresponding units. I think it is more efficient to intertwine those two steps like we have here and only do it once. This string conversion is done here before all downstream, post-simulation output processing. 

The tradeoff here is that there is consistency in how units are handled but we would lose some customization later on because units are no longer of the original enum type.

In the meantime, I will at least rename it to stringify-units and I agree calling it validate-units seems to miss the stringifying step.

2024-05-13 20:17 UTC, ltp23 commented
Hi @ew3361zh, thanks for catching those. I have removed those loose .value calls. The reason they were uncaught was that those variables were only added depending on the current states of the simulation.

2024-05-15 13:08 UTC, ew3361zh approved these changes

2024-05-15 15:20 UTC, merged