Update regional diets
RuminantFarmSystems/RuFaS pull request #1617
Opened 2024-05-07 22:52 UTC by harry-samuels

<Update to the close_up and growing feed lists of the MW/W/E Diets-->

- [ ] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [ ] No

### What
New feeds have been added to make the diets more complete

2024-05-10 14:51 UTC, Isgotkowitz requested changes
Some options for the storages are not being specified correctly and are being replaced with defaults. Also it is unclear why the metadata properties are being updated in this PR.

2024-05-10 14:51 UTC, Isgotkowitz commented on input/metadata/properties/default.json
> +        "maximum": 1000,
Why is this being changed? Same question for all of the increases in feed numbers.

2024-05-10 14:51 UTC, Isgotkowitz commented on input/data/feed/feed_MW_Diet_15.json
> +    }
The storage type, moisture, and packing density are not correctly specified and are being changed to defaults. Same for the other two feed files.

2024-05-10 18:03 UTC, tomhuhh commented on input/metadata/properties/default.json
> +        "maximum": 1000,
Hi Ed! Thanks for reviewing this. I personally think a maximum of 300 feed ingredients is not practical, and a higher threshold should be set. In the case of the pilot piloting branch, I believe there is a total of 306 ingredients.

2024-05-10 18:04 UTC, tomhuhh commented on input/metadata/properties/default.json
> +        "maximum": 1000,
However, this change may also need to happen on the main branch level. Thanks!

2024-05-15 14:59 UTC, jadamchick commented on input/metadata/properties/default.json
> +        "maximum": 1000,
On pilot testing, we've increased the max to 306 because there are 306 feeds in the library. Right now there isn't a plan to merge feeds 301-305 into Main because they are specific to FARM-ES. I think 306 is adequate, unless there are plans to add more feeds? (though I don't see any harm to a higher ceiling, either)

2024-05-15 15:25 UTC, jadamchick requested changes
Hi Harry, 
It looks like the metadata properties default.json is outdated and would revert some updates that have been made (i.e. it doesn't align with the default metadata properties json on either Main or Pilot_testing). Can you please make sure this is UTD with Main? (or even with pilot testing, which would incorporate the max feed_properties value of 306 already there)

2024-05-17 20:20 UTC, tomhuhh commented
Deprecating this PR because it is outdated. Updated PR can be found here: https://github.com/RuminantFarmSystems/MASM/pull/1667

@Isgotkowitz @jadamchick I have already tagged you on the new PR. Thanks everyone for your efforts!

2024-05-17 20:20 UTC, closed without merging