Validate metadata properties
RuminantFarmSystems/RuFaS pull request #1640
Opened 2024-05-09 18:45 UTC by ew3361zh

PR 3/3 breaking up PR #1584 to validate top level metadata and metadata properties. This one focuses on validating metadata properties and properties keys.

### Context

Issue(s) closed by this pull request: closes #1332

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

This PR adds functionality to validate the metadata properties of the types (array, string, bool, object, and number) as well as those properties' keys. This occurs after validating the top level metadata and loading the properties.

Additionally, as the code was being tested and run, a handful of violations were found within `default.json` and `tasks_properties.json` and those issues have been corrected and, where applicable, cleared with the appropriate SME.

### Why

This functionality ensures there are no unexpected, misspelled, or invalid keys within the properties section for a type property. For example, with a metadata number type property, it should have a `type` key and the full list of valid keys it should have is: `{"type", "description", "minimum", "maximum", "default"}`. If there is a default, that default should be greater than the minimum (if minimum exists) and less than the maximum (if it exists). There are a number of other validations that should occur as well and all are attempted to be covered in this PR to ensure the metadata properties are themselves valid and we're not fixing input data with bad default data.

### How

Within the new `_validate_properties()` method, there is a validate-by-type function map similar to what's used with the input data but specific to the structure of the metadata properties. When a properties section for one of these types is reached, it will be dispatched by type to have both its keys and values validated.

### Test plan

The strategy I took was to start changing and adding keys in the metadata properties to try and get errors to trigger.

e.g. take this entry in field_properties:

```
"absolute_latitude": {
      "type": "number",
      "description": "The absolute latitude of the center of this field.\nUnits: degrees.",
      "minimum": 0.0,
      "maximum": 90.0,
      "default": 43.5
    },
```

Change `minimum` to `manimus` -> will raise error.
Change the value for `maximum` to < 43.5 -> will raise error.
Add a key-value pair: `"flying_monkeys": 234` -> will raise error.

You can try similar changes with each type - bool, string, array, number. Object types currently only have validation set up for including the `type` key and at least one other key that's not `type` or `description`.

For testing object types successfully having at least one extra key, you can remove all keys from an object except `type` and `description`.

Additionally, check for nullability:
1. for `initial_labile_inorganic_phosphorus_concentration`, the default is currently `null`. I added `"nullable": "true"` to the properties for this input to support this default being `null`.
2. Try setting `nullable` to `false` or removing the nullable property altogether. It will fail in both instances because the default is `null`.

2024-05-10 15:24 UTC, allisterakun approved these changes
Good job, Niko! Just two minor comments.

2024-05-10 15:24 UTC, allisterakun commented on RUFAS/input_manager.py
> +        The maximum depth allowed for a metadata properties structure.
As we discussed earlier at the retro (or maybe planning) meeting, this should be removed

2024-05-10 15:24 UTC, allisterakun commented on RUFAS/input_manager.py
> +            self.__valid_input_types: Set[str] = {"json", "csv"}
Just curious, is there a specific reason that you chose Set instead of List (or other data structure)?

2024-05-24 18:50 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        data_type_to_loader_map: Dict[str, Callable[[Path], Dict[str, Any]]] = {
Fixes a mypy error.

2024-05-24 18:51 UTC, ew3361zh commented on input/metadata/properties/default.json
> -      "units": "ha",
Removed because it's not a valid property key for number type.

2024-05-24 18:52 UTC, ew3361zh commented on input/metadata/properties/default.json
> +        "default": 0.87
Confirmed change with @JoeWaddell - default was previously below the minimum value as defined in the properties here.

2024-05-29 14:53 UTC, Isgotkowitz requested changes
I think this is well on the way towards being ready, but there are some cases not covered which should be addressed before this PR is merged:
- With frequent use of the `.get()` function to retrieve a value associated with a key, there is no distinguishing between when the properties do not include the key vs. when they do include the key and the value is set to null/None.
- The validity of the `nullable` key is not checked. If the key is present, then its value must be a boolean. Also, the nullability of a value should be considered when checking the default.

2024-05-29 14:53 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        valid_number_property_keys = {"type", "description", "minimum", "maximum", "default", "nullable"}
```suggestion
        required_number_property_keys = {"type"}
        optional_number_property_keys = {"description", "minimum", "maximum", "default", "nullable"}
        valid_number_property_keys = union(required_number_property_keys, optional_number_property_keys)
```
I think this syntax would work, but I didn't check it - also there may be a cleaner way to do this. The idea though is that it would be beneficial to write out the required_number_property_keys once.

Edit: I didn't read the full code before I wrote this comment. Maybe it would be better to add the `union` step in `_validate_metadata_properties_keys` instead of writing this step into every individual validator function.

2024-05-29 14:53 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                "Invalid metadata array length range.",
```suggestion
                "Invalid range of acceptable numbers.",
```

2024-05-29 14:53 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        default = value.get("default")
I think the way that the default is collected needs to be changed. If the default key is present and its value is null, that is a different case than the default key not being present at all.

2024-05-29 14:53 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                raise ValueError
I think these checks of the max and min need to happen outside of the if block they are wrapped in. Currently they are only checked if there is a default present, and but they should be checked to make sure they are valid numbers regardless of whether or not there is a default present.

2024-05-29 14:53 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        valid_str_property_keys = {"type", "description", "pattern", "default", "nullable"}
Same as above

2024-05-29 14:53 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        default = value.get("default")
Also same as above for getting the default.

2024-05-29 14:53 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        pattern = value.get("pattern")
Similar to getting the default, the getting of the pattern should be changed to make sure that the case of the pattern key being present and set to null is treated differently from the pattern key not being present. Also, if the pattern key is present, it should be checked that it is a valid Regex pattern - `re.compile` does this in a pretty exhaustive way I think.

2024-05-29 14:53 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        valid_array_property_keys = {"type", "properties", "description", "minimum_length", "maximum_length", "default"}
Currently, the Input Manager will only attempt to fix data (i.e. use the default) if it is in `FIXABLE_INPUT_DATA_TYPES`. Which means that even if the properties specify a default for an array or object and an array or object is passed that is invalid, the default will not be used (I ran into this very issue in #1687, and the solution may just be making the object and array types fixable). As long as arrays and objects are not fixable, I think it should not be allowed for the properties to specify defaults for them because it is misleading for people who may read or write metadata properties without knowing the exact logic of the Input Manager.

2024-05-29 14:53 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                )
Similar to the above comment on max's and min's in the number validator method, these max and min lengths should be check regardless of whether or not a default is present.

2024-05-29 14:53 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        property_type = properties.get("type", "Unknown type")
```suggestion
        property_type = properties.get("type")
```
If the type is missing or invalid, won't it get caught in `_validate_properties` and not make it to this line?

2024-05-29 14:53 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            return
If the property is for an object, can/should it be assumed that there should be at least one key that is _not_ listed in the required or valid properties keys?

2024-05-30 14:21 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        valid_number_property_keys = {"type", "description", "minimum", "maximum", "default", "nullable"}
I like adding it to the `_validate_metadata_properties_keys()` function to minimize duplicate code. And it looks like sets have their own `.union()` method for joining sets together (and automatically removing duplicates).

2024-05-30 15:24 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        default = value.get("default")
You bring up an interesting point.
I made this diagram to try to organize the order of operations. Let me know what you think.
![Screenshot 2024-05-30 at 11 25 55 AM](https://github.com/RuminantFarmSystems/MASM/assets/70217952/53fe2f14-9dfb-4ffb-b4b9-13a8a6738ef7)

2024-05-30 19:22 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                raise ValueError
Good call.

2024-05-30 19:41 UTC, matthew7838 requested changes
Looks like things are on track. There are a few things. 

1. It seems like even though the value is valid, it will still not pass the validator if the input has an invalid default. Is this an intended behavior?
2. The docstrings are missing parameters.
3. As Ed mentioned, the case of key's existence should be differentiated. I would suggest using something like `in` to check that before calling the `get`.

2024-05-30 19:41 UTC, matthew7838 commented on RUFAS/input_manager.py
> +        default = value.get("default")
This graph will not check the default if the leftmost path is followed, which contradicts with 

> **If there is a default, that default should be greater than the minimum (if minimum exists) and less than the maximum (if it exists).**

 in the description.  However, I think this graph still makes logical sense and I'm not sure which is preferred.

2024-05-31 18:09 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        valid_array_property_keys = {"type", "properties", "description", "minimum_length", "maximum_length", "default"}
Thanks Ed. I'm going to check with SMEs about the instances of there being defaults for arrays (and objects if any of those exist).

2024-05-31 18:11 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        default = value.get("default")
Yea sorry this is confusing because this is from my map to overview the IM validation process so it's not at the level of detail (yet) that will show that check happening. Thank you for pointing that out though - I will definitely have that clear in the final version (maybe as a sub-map of this main map so it doesn't get too crowded).

2024-05-31 18:15 UTC, ew3361zh commented
> Looks like things are on track. There are a few things.
> 
> 1. It seems like even though the value is valid, it will still not pass the validator if the input has an invalid default. Is this an intended behavior?

Yes, this behavior is intended to ensure the metadata itself is valid which includes having a default that is itself fulfilling the guidelines set by the metadata.

> 2. The docstrings are missing parameters.

For lower level functions (sub functions deep within a particular class), we're not adding full docstrings because it's too cumbersome. Ed and I had a discussion about how we're judging this and it's not exact but I think if a function is a couple levels deep within a class, that's my current guideline for whether it needs full docstrings or just an overview docstring.

2024-05-31 18:25 UTC, matthew7838 approved these changes
Thanks for the explanation. I will approve the PR, but I agree that Ed raised some important points that need to be resolved before we proceed with the merge.

2024-05-31 20:00 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        property_type = properties.get("type", "Unknown type")
It would right now with the way things are set up but I thought adding this check would make this function less dependent on that initial check in `_validate_properties()` in case there is later on a different way this function gets called.

2024-06-03 13:29 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            return
Added a check for this so there should be at least one additional key that's not in the `valid_properties_keys` set if it's an object type property.

2024-06-03 13:50 UTC, ew3361zh commented on input/metadata/properties/default.json
> -          "default": [],
Checked with @Isgotkowitz on removing these default arrays.

2024-06-03 13:51 UTC, ew3361zh commented on input/metadata/properties/default.json
> +          "nullable": true
Added nullability for defaults that were `null`.

2024-06-03 13:52 UTC, ew3361zh commented on input/metadata/properties/tasks_properties.json
> -          "default": [{}],
Confirmed with @JoeWaddell that this default was not needed.

2024-06-03 18:01 UTC, Isgotkowitz approved these changes
Only spotted two things: when a string default is "" (left comment on this below), and checking "nullable" - I think it is good to do `.get("nullable", False)`, but the value should still be checked to make sure that it is a bool.

Other than that though, LGTM. Nice job Niko

2024-06-03 18:01 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        if default != "" and default is not None and not has_no_default:
```suggestion
        if default != "" and default is not None and not has_no_default:
```
If the default is an empty string, shouldn't it still be checked against pattern to make sure that it is a valid default?

2024-06-03 18:02 UTC, Isgotkowitz commented on input/metadata/properties/default.json
> -          "default": [],
:regular salute: (GitHub doesn't have an emoji for this)

2024-06-03 18:13 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        if default != "" and default is not None and not has_no_default:
Unfortunately an empty string doesn't match a regex pattern that specifically requires at least one character to be present. This mostly came up because of the default for `output_pool_path` in `tasks_properties.json` is an empty string. It needs to have a pattern because if a path is given, it needs to be a valid path. So I'm not sure the best way around it.

```
"output_pool_path": {
          "type": "string",
          "pattern": "^(?:[a-zA-Z]:[\\/])?(?:[a-zA-Z0-9._-]+[\\/])*(?:[a-zA-Z0-9._-]+\\.json)$",
          "description": "The path to a JSON files to load the Output Manager's pool from for post processing",
          "default": ""
        },
```

Any suggestions?

2024-06-03 18:16 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        default = value.get("default")
I think it looks good, the only thing that needs to change is the validation of the default - that should be in the map describing how metadata properties are validated. By the time it gets to validating input data, all defaults should have been validated.

2024-06-04 13:11 UTC, merged