Animal Health Module Setup
RuminantFarmSystems/RuFaS pull request #1767
Opened 2024-06-18 14:44 UTC by ew3361zh

The initial set up of the Animal Health module.

### Context

Issue(s) closed by this pull request: closes #1692

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

Sets up the following 4 classes:
- Disease
- DiseaseIncidence
- DiseaseRecovery
- AnimalHealthReporter

Each class has a series of methods that cover the outline from the design doc and issue. It's a little unclear from the design doc how this will be managed especially considering the large refactoring of the Animal Module on the horizon.

### Why

This skeleton structure is needed for further work and development of the Animal Health module.

### How

The structure as outlined in the Animal Health design doc as well as in the issue this PR closes was followed as best I could understand and the pieces were put into place accordingly.

### Test plan

There is no testing in place as these are just skeleton functions and frameworks.

2024-06-21 14:00 UTC, Isgotkowitz approved these changes
This is an excellent start to the Animal Health module Niko. I left a few comments and questions, but saw nothing specific that needs to changed right now.

A pattern I noticed a lot of was methods taking in a single AnimalBase instance at a time. What would you think of changing this so that lists of AnimalBase instances are taken instead? I ask because performance is already an issue in the Animal module, and as I understand it, it would be faster to have a single method call that takes in a list of things to process instead of iterating over a list of things and calling a method on every single thing.

2024-06-21 14:00 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_health/disease.py
> +    """
Should this class inherit from ABC? I don't know how strict the definition is for an abstract class, but it might be the case that this is not one because it doesn't have any abstract methods.

2024-06-21 14:00 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_health/animal_health_reporter.py
> +    # modeling after AnimalModuleReporter class - this could likely be folded into that if desired.
My gut reaction for this is that we should be going for an all-or-nothing approach - either all the animal outputs are recorded in one place or the outputs get recorded where they are calculated/used. But this might be the perfect balance between grouping the recording of outputs together and keeping the recording of outputs close to where they are calculated.

Either way, looking forward to seeing the final design - I think it will be really helpful in creating a template that we could apply to other modules.

2024-06-21 14:00 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_health/disease.py
> +    def start_disease(self, animal: AnimalBase, simulation_day: int) -> None:
Instead of passing in the simulation day, would it be better to pass in a `Time` instance?

2024-06-21 14:00 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_health/disease.py
> +    def _end_disease(self, animal: AnimalBase, outcome: str) -> None:
```suggestion
    def _end_disease(self, animal: AnimalBase, outcome: str) -> None:
```
Could this outcome be an enum instead of a string? I looked through the design doc, and it seems that there are a number of different outcomes that could happen for a cow, but it still might be better to define them through enums instead of strings.

2024-06-21 14:00 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_health/incidence.py
> +    def _will_develop_disease(incidence_rate: float) -> bool:
I would like to clarify, this method tells us whether an animal will or will not develop a disease, but not _when_ it will actually develop that disease?

2024-06-21 14:00 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_health/incidence.py
> +        # im.get_data("location.of.baseline_incidence_rate") - get the user-input baseline incidence rate for disease
Not very important because this isn't actually implemented yet, but would it better to pull this data in `init` and store as an attribute instead of calling it from the IM every time this method runs? I know that was an issue with some things in the past, and minimizing the number of IM calls had a not insignificant benefit to performance.

2024-06-24 04:18 UTC, allisterakun requested changes
I'm very sorry in advance. Niko, you'll probably hate me for this, but we have a circular import scenario due to my unclear design. 

The `Animal` class (which is `AnimalBase` atm) should import the `AnimalHealth` sub-module, and some daily routine "update/check" function for animal health should be run in `Animal.daily_routines()` (which is the update function rn).

I will discuss this more during our work together on Monday, 6/25, and I would appreciate your help with the animal module design in general. It would be a small change for this PR. But it does change how I pictured the Animal module in general.

Again, my apologies in advance!

2024-06-24 04:18 UTC, allisterakun commented on RUFAS/routines/animal/animal_health/disease.py
> +    def start_disease(self, animal: AnimalBase, simulation_day: int) -> None:
Second that

2024-06-26 15:00 UTC, ew3361zh commented on RUFAS/routines/animal/animal_health/disease.py
> +    """
That's a good call. I think this is left over from my initial design where I had the disease class doing a lot more and I thought there would be more specific outcomes that would need to occur for each disease type.

2024-06-26 15:16 UTC, ew3361zh commented on RUFAS/routines/animal/animal_health/animal_health_reporter.py
> +    # modeling after AnimalModuleReporter class - this could likely be folded into that if desired.
I will move it to the AnimalModuleReporter class for now.

2024-06-26 15:16 UTC, ew3361zh commented on RUFAS/routines/animal/animal_health/disease.py
> +    def start_disease(self, animal: AnimalBase, simulation_day: int) -> None:
Done!

2024-06-26 15:34 UTC, ew3361zh commented on RUFAS/routines/animal/animal_health/disease.py
> +    def _end_disease(self, animal: AnimalBase, outcome: str) -> None:
Definitely. I like this idea.

2024-06-26 15:58 UTC, ew3361zh commented on RUFAS/routines/animal/animal_health/incidence.py
> +    def _will_develop_disease(incidence_rate: float) -> bool:
That's correct. Though I was a little confused when trying to suss out the exact interaction of the at-risk-period and the incedence-rate. Perhaps there is more interaction than I've set up here or a better way of relating the two.

2024-07-08 16:42 UTC, allisterakun approved these changes
Great job, Niko!

2024-07-10 21:57 UTC, Isgotkowitz approved these changes
LGTM, this is laying excellent groundwork for the Animal Health submodule. Made a couple of comments but none of them are suggesting substantive things.

2024-07-10 21:57 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_health/outcomes.py
> +    REMAIN_DISEASED = "remain_diseased"
This is really splitting hairs, but could/should the enum terms be tweaked to make them a little more grammatically consistent? For example, changing them so that they all complete the sentence "the animal is _________". This might change death to dead, recovery to recovering, cull to culled, and remain diseased to diseased (of course there are many other possibilities though).

2024-07-10 21:57 UTC, Isgotkowitz commented on input/data/animal_health/example_animal_health.json
> +            }
```suggestion
            "milk_production_percentage_decrease": 5 ,
            "miscarriage_likelihood_percentage_increase": 3.5
```
I'm not sure what other data fields might need to be included for each effect, if they are not just limited to name and percent then my suggestion probably wouldn't be very helpful.

2024-07-10 21:57 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_health/animal_health_status.py
> +        # other attributes will likely be needed
AnimalHealthStatus will be a great way to package and share data about animals between different disease modules - I am curious to see how it will be integrated with the Animal object.

2024-07-10 21:57 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_health/animal_health.py
> +                pass
```suggestion
        elif animal_health_status.status == DiseaseOutcomes.RECOVERY:
            if animal_health_status:  # some way to determine if the animal is in the same life stage when it recovered
                # Disease.intermediate_effect()
                pass
            else:
                # Disease.lasting_effect()
                pass
        else:
            for disease in self.diseases:
                animal_at_risk = disease.assess_disease_risk(time, animal_health_status)
                if animal_at_risk:
                    incidence_rate = disease.calculate_incidence_rate()
                    will_develop_disease = disease.will_develop_disease(incidence_rate)
                    if will_develop_disease:
                        disease_start_date = disease.determine_at_risk_period(animal_health_status)
                        animal_health_status.disease_start_date = disease_start_date
```

2024-07-11 17:26 UTC, ew3361zh commented on RUFAS/routines/animal/animal_health/outcomes.py
> +    REMAIN_DISEASED = "remain_diseased"
I like it

2024-07-11 17:31 UTC, ew3361zh commented on input/data/animal_health/example_animal_health.json
> +            }
Yea, I don't know either. I might leave it this way for now just because I think there are a variety of effects and I'm not sure the flexibility we'll need/want for reading/implementing them.

2024-07-11 17:50 UTC, merged