Essential Amino Acid Requirement Implementation
RuminantFarmSystems/RuFaS pull request #1775
Opened 2024-06-20 06:26 UTC by allisterakun

### Context

Issue(s) closed by this pull request: closes #
This PR implements the calculation for the essential amino acid requirements for animals. These calculations are part of the animal requirement calculations, which are run at the beginning of the simulation and once every ration period.

### What

- `AminoAcidCalculator`: This class contains the methods for amino-acid-related calculations. 
    -  Currently, only the Essential Amino Acid requirement calculations are implemented. 
    - The Non-essential Amino Acid requirement calculations and other possible amino-acid-related calculations will be implemented in the future. 
- Added an attribute to `AnimalBase` for `essential_amino_acid_requirement` that indicates the daily EAA requirements for the animal.
- Added the calculated EAA requirements to the animal requirements. 
    - The average pen EAA requirement is calculated and reported along with other animal requirements at the beginning of the simulation and every ration interval.

### Why

Calculate the EAA requirement for each animal and report the average pen EAA requirement for all animals in each pen.

### How

Following the formula in the AA_requirements design doc provided by @Rebecavb.

### Test plan

Implemented unit tests for all calculation functions.
@Rebecavb is going to review the output to evaluate the result.
However, upon review, we found that one of the inputs for the EAA requirements calculation, `gravid_uterine_weight_gain`, can sometimes be a negative number, which leads to negative EAA requirements. This is outside the scope of this PR; @allisterakun is making a new issue about the investigation.
To review the reported daily pen average EAA requirements output, run the simulation with the following filter:
```
^.*AnimalModuleReporter.report_ration_interval_data.avg_rqmts_pen.*$
```

2024-06-20 15:55 UTC, Rebecavb commented on RUFAS/routines/animal/ration/amino_acid.py
> +            Daiy energy Requirement associated to increased gain of reproductive tissues as pregnancy advances (Mcal/d).
```suggestion
            Daily energy Requirement associated to increased gain of reproductive tissues as pregnancy advances (Mcal/d).
```

2024-07-17 09:05 UTC, matthew7838 requested changes
Looks solid! Caught some things which shouldn't be too complicated to fix. 

- There are some inconsistencies in the docstrings and missing docstrings for the tests. 
- Some suggestions for the assertions in the tests. 
- Is there a source for the calculations? If so, it should be added to the docstrings.

2024-07-17 09:05 UTC, matthew7838 commented on RUFAS/routines/animal/ration/amino_acid.py
> +        milk_true_protein : float
Is it possible to modify the name so it can be more differentiable between contents and amount?

2024-07-17 09:05 UTC, matthew7838 commented on RUFAS/routines/animal/ration/amino_acid.py
> +            Net protein in milk, or milk true protein yield, g
Better to have the same format for units as above.

2024-07-17 09:05 UTC, matthew7838 commented on RUFAS/routines/animal/ration/amino_acid.py
> +        """
Same with this formatting, also, I think having units in both the description and the return is a bit redundent.

2024-07-17 09:05 UTC, matthew7838 commented on tests/animal_module_tests/ration/test_amino_acid.py
> +    amino_acid_calculator = AminoAcidCalculator()
docstrings

2024-07-17 09:05 UTC, matthew7838 commented on tests/animal_module_tests/ration/test_amino_acid.py
> +    expected_result = NPscurf * AMINO_ACID_COMPOSITION[amino_acid]["scurf"] / 100
When possible, we should pass in the manual calculated expected result as an argument into the test signature and assert it.

2024-08-13 17:24 UTC, allisterakun commented on RUFAS/routines/animal/ration/amino_acid.py
> +        milk_true_protein : float
These input variables are from other parts of the animal module. I kept the original names to maintain consistency and avoid confusion.

2024-08-16 18:00 UTC, matthew7838 approved these changes
LGTM, very minor comments but if those numbers are SMEs approved I think you're good to merge.

2024-08-16 18:00 UTC, matthew7838 commented on RUFAS/routines/animal/ration/amino_acid.py
> +        return NPscurf * AMINO_ACID_COMPOSITION[amino_acid]["scurf"] / 100
`GeneralConstants.PERCENTAGE_TO_FRACTION` might come in handy in this case.

2024-08-16 18:00 UTC, matthew7838 commented on tests/animal_module_tests/ration/test_amino_acid.py
> +    assert actual_result == approx(expected, abs=0.001)
```suggestion
    assert actual_result == approx(expected)
```
I Have tried this on a few tests and without setting the abs value it is still fine. The default is 1e-6, so keeping the default is also more accurate.

2024-08-19 18:30 UTC, Rebecavb approved these changes

2024-08-23 16:40 UTC, merged