Refactor of test_animal.py
RuminantFarmSystems/RuFaS pull request #1780
Opened 2024-06-25 21:40 UTC by Fjordrunner

This PR moves certain unit tests in the animal module to an animal_requirements-specific test file. Additionally, this PR cleaned up various MyPy errors throughout the general test_animal.py file. 

This PR is in response to PR #1735, which reverted a bugged PR that attempted to move unit tests to an animal_requirements-specific test file.

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What
Some unit tests were migrated to an animal_requirements.py-specific test file. Additionally, multiple changes were made throughout the model, mostly incorporating type hints, to reduce the overall amount of Mypy errors in the test_animal.py file.

### Why
This PR increases our test modularity, reduces the length of the test_animal.py file, and reduces the amount of MyPy errors by adhering to best coding practices.

### Test plan
Multiple changes were made to test functions, resulting in many of them failing. All failing tests have been assessed and are now passing.

2024-07-15 21:27 UTC, Isgotkowitz requested changes
Good work, Simon, love seeing that error count go down. Left comments on a lot of small things, address as you feel appropriate. Changes requested are specific to a handful of tests in `test_animal.py` where the type hints of the test parameters do not match the method being tested, each has a comment.

I'm also curious, are you running the formatter manually? I saw a couple of formatting changes that I was unable to get Black to reproduce.

2024-07-15 21:27 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +    def update_pen_history(self, curr_pen: int, curr_day: int, classes_in_pen: Set[str]):
```suggestion
    def update_pen_history(self, curr_pen: int, curr_day: int, classes_in_pen: Set[str]) -> None:
```

2024-07-15 21:27 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/animal_requirements.py
> +        populates the corresponding class variables.s
```suggestion
        populates the corresponding class variables.
```

2024-07-15 21:27 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/animal_requirements.py
> +    ):
Can any type hints be added here?

2024-07-15 21:27 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/animal_requirements.py
> +    ):
Can any more type hints be added here?

2024-07-15 21:27 UTC, Isgotkowitz commented on RUFAS/routines/animal/clustering_pen_grouping.py
> +    return grouping_data
```suggestion
```

2024-07-15 21:27 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/calf_ration.py
> +        return animal_intake
```suggestion
```

2024-07-15 21:27 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/user_defined_ration.py
> +        return ration
```suggestion
```

2024-07-15 21:27 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +        previous_ration: Mapping[str, float | str] | None = None
```suggestion
        previous_ration: Dict[str, float | str] | None = None
```
Instead of changing this to `Mapping`, I suggest keeping it a `Dict` and adding the following at line 934: `value = int(value)`. The benefit is that it keeps the typing of `previous_ration` more consistent with the way it is typed in other places, and doesn't add the error associated with `Mapping`.

2024-07-15 21:27 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +        print(idx, history)
```suggestion
```

2024-07-15 21:27 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +    #  which is_constraint_violated() then handles
I think there is some missing info here.

2024-07-15 21:27 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +    print(expected)
```suggestion
```

2024-07-15 21:27 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +    body_weight: str,
The type hints for these params do not match `get_ME` expects.

2024-07-15 21:27 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +    body_weight: str,
Same issue as above, these param types do not match what is expected by `get_NE_maintenance_and_activity`

2024-07-15 21:27 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +    body_weight: str,
Same as issues above, these param types do not match what `get_NE_lactation` expects

2024-07-15 21:27 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +    body_weight: str,
Same as above, param type hints do not match what is expected by `get_NE_growth`.

2024-07-15 21:27 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +    body_weight: str,
Same as above, param type hints do not match what is expected by `get_calcium`.

2024-07-15 21:27 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +    body_weight: str,
Same as above, type params do not match what is expected by `get_phosphorus`

2024-07-15 21:27 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +    body_weight: str,
Same as above, the type hints of these params do not match what is expected by `get_forage_NDF`

2024-07-15 21:27 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +    assert np.isclose(actual, expected, rtol=1e-3)
```suggestion
```

2024-07-16 14:29 UTC, Fjordrunner commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +    def update_pen_history(self, curr_pen: int, curr_day: int, classes_in_pen: Set[str]):
Good catch, thank you! This is now added.

2024-07-16 14:30 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/animal_requirements.py
> +        populates the corresponding class variables.s
Changed.

2024-07-16 14:34 UTC, Fjordrunner commented on RUFAS/routines/animal/clustering_pen_grouping.py
> +    return grouping_data
This doubling of return statements happened a few other places...didn't catch this one, thank you! Changed.

2024-07-16 14:35 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/calf_ration.py
> +        return animal_intake
Done.

2024-07-16 14:35 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/user_defined_ration.py
> +        return ration
Done.

2024-07-16 14:38 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +        previous_ration: Mapping[str, float | str] | None = None
Good point, thank you! I think adding Mapping removed a Mypy error in the test_animal.py file but I did wince a bit when I added it.

2024-07-16 14:40 UTC, Fjordrunner commented on tests/animal_module_tests/test_animal.py
> +        print(idx, history)
Done.

2024-07-16 14:40 UTC, Fjordrunner commented on tests/animal_module_tests/test_animal.py
> +    print(expected)
Done.

2024-07-16 14:45 UTC, Fjordrunner commented on tests/animal_module_tests/test_animal.py
> +    assert np.isclose(actual, expected, rtol=1e-3)
Removed the double assert at the end here.

2024-07-16 14:51 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/animal_requirements.py
> +    ):
Adding type hints for AnimalGroupingScenario and Pen objects results in circular imports. There are some clever workarounds to these by using the "importlib" library, but I just spoke with Pooya, and since these files' structures are going to get heavily restructured soon, we will let this be for now.

2024-07-16 14:52 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/animal_requirements.py
> +    ):
See my response above. Good point though, it was definitely something I wanted to address!

2024-07-16 15:17 UTC, Fjordrunner commented on tests/animal_module_tests/test_animal.py
> +    #  which is_constraint_violated() then handles
I rewrote it as this, let me know if you have any more suggestions!


    # This dummy constraint returns the difference of the sum of x and 10
    #  which is_constraint_violated() then handles to return whether or not a constraint
    #  has been violated. The two constraints will either check to see whether the
    #  aforementioned difference is 0, in the case of an equality constraint, or greater
    #  than 0, in the case of an inequality constraint.

2024-07-16 15:17 UTC, Fjordrunner commented on tests/animal_module_tests/test_animal.py
> +    body_weight: str,
Depending on whether or not you want the values of the tests changed as well, this has been fixed. Thank you!

2024-07-16 15:38 UTC, Isgotkowitz commented on tests/animal_module_tests/test_animal.py
> +    #  which is_constraint_violated() then handles
Looking at it now, I think it would be simpler and cleaner just to give it a docstring like
```python
"""Simple constraint used to test is_constraint_violated()."""
```
because it is not very complicated, and doesn't need anything more than a one-liner.

2024-07-17 20:01 UTC, Isgotkowitz approved these changes
LGTM, nice job Simon

2024-07-18 18:29 UTC, JoeWaddell requested changes
Left a few comments, biggest concern is that the simulation fails unless you remove a specific new line - see my comment in ration_optimizer, I think the new line isn't necessary, so once it's removed should be OK

2024-07-18 18:29 UTC, JoeWaddell commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +                value = int(value)
Not sure why this is being changed to an int - just to round it as a starting place? My instinct is that keeping it as the previous float should be fine.

This also causes the simulation to fail: as it can't finish this optimize method since it's trying to convert strings to ints (in the cases where value is `status` or `objective`) . Removing it causes the simulation to complete, so I think the simple removal is sufficient.

2024-07-18 18:29 UTC, JoeWaddell commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +        solution_x: npt.NDArray[np.float32],
Is there are reason some of these are typed as `float32` instead of `float64`?

2024-07-18 18:29 UTC, JoeWaddell commented on RUFAS/routines/animal/clustering_pen_grouping.py
>      Args:
This could be updated to `Parameters` with the dashes below, likewise the indentation of the arguments/parameters should be updated to follow format elsewhere.

2024-07-18 20:30 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +        solution_x: npt.NDArray[np.float32],
Good point, switching that throughout the file now.

2024-07-18 20:31 UTC, Fjordrunner commented on RUFAS/routines/animal/clustering_pen_grouping.py
>      Args:
Good point, I'll change that now.

2024-07-18 20:43 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +                value = int(value)
This was changed in an effort to steer away from using the Mapping type hint as opposed to the Dict one, but in hindsight, the optimal solution here is just to maintain the old code completely and live with an extra Mypy warning. Good catch!

2024-07-18 21:28 UTC, JoeWaddell approved these changes
Looks great! Nice work tidying things. To test, I compared it to main using both user defined and automated ration formulation, and behavior is identical.

2024-07-18 21:47 UTC, merged