Weather.py refactor
RuminantFarmSystems/RuFaS pull request #1781
Opened 2024-06-26 09:58 UTC by matthew7838

Changes the structure of the `Weather` data class.

### Context

Issue(s) closed by this pull request: closes #1764 

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

- The data will now be a dictionary. A datetime timestamp is the key and the corresponding CurrentWeatherCondition will serve as the value.
- A float variable initialized to hold the mean_annual_temperature after data creation.
- Added helper methods in `Time` to help convert the day.
- A helper method to check the sufficient of the weather data provided.
- Methods related to getting conditions will simply use the key to retrieve data from the dictionary.

### Why

The current format introduces unnecessary complexity in trying to not only extract Weather data for a particular date or period of time but also in trying to assemble Weather class instances from input data. This can (and has) led to data access errors most notably within the Crop and Soil module. 

### How

The structure of Weather objects is flattened so that they’re easier to access, work with, and understand.

### Test plan

1. Tests created
2. Run with different metadata and make sure that they're still running as expected.

2024-07-09 16:07 UTC, allisterakun requested changes
Looks pretty good, Matthew! There are just some potential changes in the comments. 

However, please remove the following properties from the `Time` class (https://github.com/RuminantFarmSystems/MASM/issues/1507#issuecomment-2127449078). These functions were to be deprecated during the `Time` class refactor, but they were only kept because they were used in the old `Weather` initialization.
- `Time.years`
- `Time.start_year_int`
- `Time.start_day`
- `Time.end_year_int`
- `Time.end_year`

2024-07-09 16:07 UTC, allisterakun commented on RUFAS/weather.py
> +    weather_file : dict[str:List[Any]]
```suggestion
    weather_file : dict[str, List[Any]]
```
just to be consistent with the rest of the codebase

2024-07-09 16:07 UTC, allisterakun commented on RUFAS/weather.py
> +    weather_data : dict[datetime:CurrentDayCondition]
```suggestion
    weather_data : dict[datetime, CurrentDayCondition]
```

2024-07-09 16:07 UTC, allisterakun commented on RUFAS/weather.py
> +        while current_date != time.end_date:
Since we know the start and the end date, can we use a for loop instead?

2024-07-09 16:07 UTC, allisterakun commented on RUFAS/weather.py
> +            if (current_date_jday in days_list) and (current_date_year in years_list):
If we are validating by checking if we have a piece of weather data for all the simulation dates, how do we account for duplicate data? For example, what should we do with two different weather data entries for the same date?

2024-07-09 16:07 UTC, allisterakun commented on RUFAS/weather.py
> +            self.weather_data[time.current_date].annual_mean_air_temperature = self.mean_annual_temperature
Since we are using the same latitude for all calls, and the CurrenDayConditions is essentially queried every day  throughout the simulation (`AnimalManager.daily_updates()`), can we move these assignment into `__init__()`? I think this would make more sense than generating on the fly.

2024-07-09 17:35 UTC, matthew7838 commented on RUFAS/weather.py
> +            self.weather_data[time.current_date].annual_mean_air_temperature = self.mean_annual_temperature
This is a good point. However, I think the current implementation would serve better for an extension if we moved on to a more geographically precise solution in the future.

2024-07-09 18:29 UTC, matthew7838 commented on RUFAS/weather.py
> +            if (current_date_jday in days_list) and (current_date_year in years_list):
I think this should be fine. later on, with the transformation into a dictionary we will only keep the latest read of weather data from that day. I think it's a safe assumption for now to assume it is the newest data and should follow closely with the old code.

2024-07-11 14:33 UTC, ew3361zh approved these changes
I think this looks great, Matthew! Left some comments and suggestions on docstrings mostly but the structure looks really good imo and I think you did a good job implementing the design doc and taking some of the open ended questions into account.

A couple questions: 
1. I noticed you didn't have to update any of the files/modules that use weather data/current day conditions. Did you look through those references and were there any improvements to how weather data is used you might suggest?
2. I know we had an issue with not enough weather data for some C&S simulations. Were you able to test those and ensure this was catching those shortcomings effectively?

2024-07-11 14:33 UTC, ew3361zh commented on RUFAS/time.py
> +            The date time object from the provided inputs
```suggestion
            The datetime object from the provided inputs.
```

2024-07-11 14:33 UTC, ew3361zh commented on RUFAS/time.py
> +        Converts the year and its day of the year to a datetime object
```suggestion
        Converts the year and its day of the year to a datetime object.
```

2024-07-11 14:33 UTC, ew3361zh commented on RUFAS/weather.py
> +        The weather dictionary read from the provided weather file.
I think make this more general since it won't necessarily always be a file we're pulling weather from.

```suggestion
        The weather dictionary read from the provided weather input source.
```

2024-07-11 14:33 UTC, ew3361zh commented on RUFAS/weather.py
> +        A dictionary that map a date to the corresponding CurrentDayCondition.
```suggestion
        A dictionary that maps a date to the corresponding CurrentDayCondition.
```

2024-07-11 14:33 UTC, ew3361zh commented on RUFAS/weather.py
> +                    f"Dumping all logs from main.py because of error '{ValueError}'",
```suggestion
                    "Inadequate weather data.",
```

2024-07-11 14:33 UTC, ew3361zh commented on RUFAS/weather.py
> +        condition_list = []
And other refs to this var.
```suggestion
        conditions_list = []
```

2024-07-11 14:33 UTC, ew3361zh commented on RUFAS/weather.py
> +            A dictionary form of the weather file.
I think these should be updated to be more generic since we won't necessarily be using a file as our weather data source.

2024-07-11 14:33 UTC, ew3361zh commented on RUFAS/weather.py
> +            if (current_date_jday in days_list) and (current_date_year in years_list):
Yea I'm not sure what we'd do about duplicate data. It does seem like something to at least log as a warning to OM. One or two duplicates seems marginal but if there's a whole second set of data that's duplicated, it seems like it could have a real impact on the simulation if it's different.

2024-07-11 14:33 UTC, ew3361zh commented on RUFAS/weather.py
> +            self.weather_data[time.current_date].annual_mean_air_temperature = self.mean_annual_temperature
Good question, Allister - I think I agree with Matthew here on the possibility for extension when we consider a potential farm or simulation with multiple latitudes and wanting to be able to calculate daylight differently for each of them. We may end up seeing that the queries are too resource consuming and it's better to just make a set of weather data with CurrentDayConditions for each set of latitudes. It seemed like overall a 10-year set of weather data was not that memory-intensive so 2 sets wouldn't be much either.

2024-07-11 14:38 UTC, matthew7838 commented on RUFAS/weather.py
> +            if (current_date_jday in days_list) and (current_date_year in years_list):
Sounds like a good measure to log a warning.

2024-07-11 15:36 UTC, allisterakun approved these changes
Looks good! Great job, Matthew!

2024-07-11 18:46 UTC, merged