Simplifying _add_variable_to_pool in IM
RuminantFarmSystems/RuFaS pull request #1805
Opened 2024-07-08 17:21 UTC by matthew7838

Simplify the _add_variable_to_pool in Input manager to follow flake 8 complexity constrain
### Context

Issue(s) closed by this pull request: closes #1490 

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

Extract some conditional statements with helper methods to simply the method.

### Why

There are way too many conditional statements in _add_variable_to_pool of IM, which violates the complexity constrain of flake8.

### How

Separate the conditional statements into 4 helper methods,  `_prepare_data`,  
`_check_modifiability`, `_validate_data` and `_add_to_pool`. All are simple extractions with self-explanatory names.
### Test plan

Ran a complete test suite. `#noqa` removed and it passed linting.

2024-07-11 13:56 UTC, Isgotkowitz requested changes
Overall I think this looks quite good, nice job Matthew. I left suggestions on a few things, but I am specifically requesting changes on the how info maps are handled in some of the new subroutines. This is detailed in one of the comments.

2024-07-11 13:56 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +
```suggestion
```

2024-07-11 13:56 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +
```suggestion
```

2024-07-11 13:56 UTC, Isgotkowitz commented on RUFAS/input_manager.py
>              If eager_termination is True and the variable is not modifiable during runtime.
The docstring should be updated - this method no longer raises a PermissionError

2024-07-11 13:56 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        element_hierarchy, data, metadata_properties = self._prepare_data(
`element_hierarchy` is never used, why does it need to be returned by `_prepare_data`?

2024-07-11 13:56 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +
Needs a Raises section

2024-07-11 13:56 UTC, Isgotkowitz commented on RUFAS/input_manager.py
>              om.add_warning("IM Runtime Modification", f"{variable_name} is not modifiable during runtime.", info_map)
This code replicates the old behavior of the IM - but the old behavior doesn't make much sense to me here. If a variable is not modifiable at runtime, that variable should not be added to the pool. Currently it may or may not be, depending on `eager_termination`. Curious to hear what you think of this @allisterakun

2024-07-11 13:56 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        """
Passing in an info map for a method is an anti-pattern - it makes the information in the info map invalid. They should always be created within the method where they are being used.

2024-07-11 13:56 UTC, Isgotkowitz commented on tests/test_input_manager.py
> +    patch_prepare = mocker.patch("RUFAS.input_manager.InputManager._prepare_data", side_effect=side_effect_prepare_data)
```suggestion
    patch_add = mocker.patch("RUFAS.input_manager.InputManager._add_to_pool", wraps=input_manager._add_to_pool)
    patch_check = mocker.patch(
        "RUFAS.input_manager.InputManager._check_modifiability", wraps=input_manager._check_modifiability
    )
    patch_validate = mocker.patch(
        "RUFAS.input_manager.InputManager._validate_data", wraps=input_manager._validate_data
    )
    patch_prepare = mocker.patch("RUFAS.input_manager.InputManager._prepare_data", wraps=input_manager._prepare_data)
```
I suggest using this pattern for the test instead, it does pretty much the same thing but doesn't add any Mypy errors

2024-07-11 13:56 UTC, Isgotkowitz commented on tests/test_input_manager.py
> +                "root": {"nested_property": {"type": "string", "description": "An example property"}},
```suggestion
                "object_property": {"nested_property": {"type": "string", "description": "An example property"}},
```
Root is a pretty loaded term, I think it would be better to use a different term because the test cases get kind of confusing to read when there is a "root" present in them.

2024-07-11 14:08 UTC, matthew7838 commented on tests/test_input_manager.py
> +    patch_prepare = mocker.patch("RUFAS.input_manager.InputManager._prepare_data", side_effect=side_effect_prepare_data)
Thanks Ed, that is really helpful.

2024-07-11 14:15 UTC, matthew7838 commented on RUFAS/input_manager.py
> +        element_hierarchy, data, metadata_properties = self._prepare_data(
Good catch

2024-07-12 14:25 UTC, Isgotkowitz approved these changes
Found a few small things, but I think they will be easy to address before merging. In particular, please make sure there are _no_ instances of a method receiving the info map it uses as an argument. Also the Flake8 error should be fixed before merging.

Overall looks good though, nice job Matthew.

2024-07-12 14:25 UTC, Isgotkowitz commented on tests/test_input_manager.py
> +    mock_modifiable.assert_called_once_with(variable_name=variable_name, variable_properties=metadata_properties)
```suggestion
    mock_modifiable.assert_called_once_with(variable_name=variable_name, variable_properties=metadata_properties)
    mock_add_warning.assert_called_once()
```
Probably only needs to be called once?

2024-07-12 14:25 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        Prepare data and metadata properties for validation.
```suggestion
        Checks whether a variable is allowed to be modified at runtime.
```

2024-07-12 14:25 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +
Returns section

2024-07-12 14:25 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        self, variable_name: str, metadata_properties: dict[str, Any], eager_termination: bool, info_map: dict[str, Any]
This function is receiving info maps from as an argument - it should not do this. It should create them in the method.

2024-07-12 17:27 UTC, allisterakun approved these changes
Great job, Matthew! LGTM!

2024-07-12 17:29 UTC, merged