Extract validation logic
RuminantFarmSystems/RuFaS pull request #1809
Opened 2024-07-11 08:29 UTC by matthew7838

Extracts the validation logic from the InputManager.
### Context

Issue(s) closed by this pull request: closes #1800

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

- Every method that relates to the validation process in [This graph](https://whimsical.com/input-manager-data-validation-overview-T6TuSktxPUYe3BRUURhaDm) has been extracted and put into a separate file named `data_validator.py`.
- Elements and ElementCounter have been moved to a file named `data_validator.py`.
- Modifiability has been moved to a new file named `data_validator.py`.
- All validation methods are now static
- Some methods to extract data have also been moved to `data_validator.py` to avoid circular imports.
- Updated tests and fixed the usage of patching with `with()`.

### Why

`input_manager.py` is way too complicated and has too many classes. This change should follow closer to the SOILD principle.

### How

These changes will make the IM closer to a single-purpose class. The split of major functions (validation) will also make the code more maintainable. Extraction of classes in `input_manager.py` also prevents circular imports.

### Test plan

- Ran with a complete test suite.
- Ran with default metadata and it still works the same.

2024-07-18 12:15 UTC, allisterakun approved these changes
Great work, Mathew! This cleans up the IM! 
Just one take-or-leave suggestion: can we maybe put all the IM-related Python files into a folder so that we don't end up with many .py files lying around under the main RUFAS folder?

2024-07-18 15:30 UTC, matthew7838 commented
> Great work, Mathew! This cleans up the IM! Just one take-or-leave suggestion: can we maybe put all the IM-related Python files into a folder so that we don't end up with many .py files lying around under the main RUFAS folder?

I think this is a good idea, I will double-check with Pooya about this in 1:1 since it involves a bit of structure change.

2024-07-23 21:38 UTC, PooyaHekmati commented
Hi @matthew7838 
Does this need to be draft still?

2024-07-23 22:06 UTC, matthew7838 commented
> Hi @matthew7838 Does this need to be draft still?

No, my bad for forgetting to bring it out of draft.

2024-07-31 05:10 UTC, PooyaHekmati requested changes
1. The file organization is not clear. Having `elements.py` and `modifiability.py` under RUFAS is confusing. Besides their un-informative and un-descriptive names, why do they need to be in their own files? why not having everything in one file?
2. The purpose of this logic extraction is to make it accessible by the other sub-systems (OM). This PR; however, does not facilitate that. It still calls the logic `input validation`. As stated in issue #1800 :
>This new validation class is agnostic about the source of the data. 

and

> It has to be maintainable, extendable, and scalable.

3. Based on the following:
>It receives data and validation rules (currently known as metadata), performs the validation, and returns the result.

these two function calls are not correct as they don't return anything:
```InputValidator.validate_metadata(self.__metadata)```
and 
```InputValidator.validate_properties(self.__metadata, self.metadata_depth_limit)```

2024-08-08 15:08 UTC, allisterakun approved these changes
It generally looks look, great job, Matthew! I left a comment about removing the repeating om definition.

Also, please consider updating the [data validation diagram](https://whimsical.com/input-manager-data-validation-overview-T6TuSktxPUYe3BRUURhaDm) and the PR description before merging.

2024-08-08 15:08 UTC, allisterakun commented on RUFAS/data_validator.py
> +#  Move elements counters...etc to here
```suggestion
```
remove comments

2024-08-08 15:08 UTC, allisterakun commented on RUFAS/data_validator.py
> +        om = OutputManager()
Do we have to create an instance like this for all the static methods that report to the OM every time they are called? Is there a workaround? I tried deleting all the `om = OutputManager()` in each function and just have one definition of a global `om = OutputManager()` at the beginning of the file. The simulation seems to run without crashing and the logs seem to be reported correctly. So... just something to look into!

2024-08-08 15:13 UTC, matthew7838 commented on RUFAS/data_validator.py
> +        om = OutputManager()
I've discussed this with Pooya, we will stick to this way for now. We want to avoid global initialization and OM is a singleton; therefore, initializing them like this won't impact the performance.

2024-10-30 15:47 UTC, Isgotkowitz approved these changes
Compared simulation results and logs produced between this branch and `dev`, seemed to be exactly the same except for `InputManager` being changed to `DataValidator` - as expected.

The only substantive thing that should be addressed before merging are the test suites, because the coverage has gone down a bit. In particular, `_log_missing_data`, `_is_data_required_upon_initialization` and `_get_variable_modifiability` appear to not be covered at all. Ideally though both `DataValidator` and `InputManager` would have 100% test coverage.

Nice job Matthew!

2024-10-30 15:47 UTC, Isgotkowitz commented on RUFAS/data_validator.py
> +    # Validate input by type related
```suggestion
```

2024-10-30 15:47 UTC, Isgotkowitz commented on RUFAS/data_validator.py
> +            print(message)
```suggestion
```

2024-10-30 15:47 UTC, Isgotkowitz commented on RUFAS/data_validator.py
> +class DataValidator:
Could you please add a docstring for `DataValidator`? It is well documented and named otherwise, so a one-liner should be sufficient IMO

2024-10-31 17:54 UTC, PooyaHekmati approved these changes

2024-11-01 05:52 UTC, merged