Build manure management class #1
RuminantFarmSystems/RuFaS pull request #181
Opened 2022-08-04 11:22 UTC by ltp23

In this small pull request, I did the following:
- Created the ManureManagement class to replace the ManureStorage class in the future. For now, the ManureStorage class is still intact.
- Created the SimpleAnimalManagement class to simplify the AnimalManagement from the animal module, and similarly, SimplePen class (still incomplete) for Pen class. The reason is that the manure module doesn't require that many attributes from those classes, so having simplified versions would provide a cleaner interface. 

Plan for the next pull request:
- Update the SimplePen class and extract manure data from the animal module.

2022-08-07 15:55 UTC, PooyaHekmati requested changes
There are 3 reasons for sending this back to the author:
1- there are no tests in this pr
2- simple_animal_management and simple_pen classes do NOT belong to the manure module, they should be moved to their respective modules. Consider using wrappers if applicable.
3- There are comments on the code.

I am happy to see we have made progress making PRs smaller, but we can do even better by applying the single responsibility principle: a PR (similar to classes and functions) should do one thing and one thing only. This PR attempts to create two simplified classes AND build a new class.

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +        This class should replace the `ManureStorage` class.
This class _will_ replace

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +    def all_data(self):
get_all_data?

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +    def all_data(self):
missing return type

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +        self._manure_handlers = {}
missing documentation

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +    def _build(self, simple_animal_management: SimpleAnimalManagement) -> None:
why not _setup or _setup_manure_components (rather _build)?

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +        Set up all the manure components.
setups

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +        # TODO: Will add the actual components in later pull requests
can we have a git issue with an appropriate label for this?

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +        # TODO: Will add the actual outputs in later pull requests
git issue

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +        Update all the components and subcomponents given new information
Updates all the components and subcomponents based on the information from the passed in SimpleAnimalManagement object.

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +            self._all_data[pen.id].append(daily_update_data)
So, this function doesn't actually update anything, it adds to the existing data?

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +def daily_manure_management_routine(manure_management: ManureManagement, animal_management: AnimalManagement) -> None:
Please use verbs in function names.

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +    Entry point to the manure management module.
Please add more explanation

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +        manure_management: A ManureManagement object.
This is not informative, consider answering questions like: why is this here? what happens if we remove it? what is its significance? etc...

2022-08-07 15:55 UTC, PooyaHekmati commented on RUFAS/routines/manure_management/manure_management.py
> +        animal_management: An AnimalManagement object from the animal module.
same

2022-08-08 14:09 UTC, KFosterReed commented
So I like the concept of only copying the information that is needed from the Animal Management and Pen classes but I don't really like the idea of creating a duplicate but simplified class. Instead, what about classes called "PenManureMangement" and "PenManure"?

2022-08-11 20:59 UTC, ltp23 commented on RUFAS/routines/manure_management/manure_management.py
> +    def all_data(self):
My intention of using @property here and at other places is to make it appear more natural as an instance variable (e.g., manure_management.all_data) and without having to use parentheses. The name get_all_data seems to imply a function. 
For now, I can put in the return type as Dict[int, List[Tuple]], though this can be further clarified later on as I specify more detailed object types inside the tuple.

2022-08-11 20:59 UTC, ltp23 commented on RUFAS/routines/manure_management/manure_management.py
> +        self._manure_handlers = {}
Documentation added.

2022-08-11 20:59 UTC, ltp23 commented on RUFAS/routines/manure_management/manure_management.py
> +    def _build(self, simple_animal_management: SimpleAnimalManagement) -> None:
Noted and changed.

2022-08-11 20:59 UTC, ltp23 commented on RUFAS/routines/manure_management/manure_management.py
> +        Set up all the manure components.
Noted and changed.

2022-08-11 20:59 UTC, ltp23 commented on RUFAS/routines/manure_management/manure_management.py
> +        animal_management: An AnimalManagement object from the animal module.
More explanation added.

2022-08-11 20:59 UTC, ltp23 commented on RUFAS/routines/manure_management/manure_management.py
> +        manure_management: A ManureManagement object.
More explanation added.

2022-08-11 20:59 UTC, ltp23 commented on RUFAS/routines/manure_management/manure_management.py
> +    Entry point to the manure management module.
More explanation added.

2022-08-11 20:59 UTC, ltp23 commented on RUFAS/routines/manure_management/manure_management.py
> +def daily_manure_management_routine(manure_management: ManureManagement, animal_management: AnimalManagement) -> None:
I will change it to simulate_daily_manure_management(). Similar names are also used in other modules like daily_animal_routine, daily_fields_routine, ... so maybe they should be changed later as well.

2022-08-11 20:59 UTC, ltp23 commented on RUFAS/routines/manure_management/manure_management.py
> +            self._all_data[pen.id].append(daily_update_data)
Each manure component has its own update() function and will return a daily output object. All the daily output objects will then be put into a tuple and appended to the _all_data dictionary. So, "updating" here just means appending daily data, unless there is another more apt name for it.

2022-08-18 11:13 UTC, KFosterReed approved these changes
I think the changes and clarifications improved the pull request. I better understand the utility of having a simple animal management and simple pen class. The structure of the manure management and how it will update the four main object types (handling, reception pit, separator, and storage) is clear. Looking forward to the next installment!

2022-08-30 16:03 UTC, ltp23 commented
Thanks Pooya and Kristan for your input. 
The way I used the prefix 'Simple-' in SimplePen and SimpleAnimalManagement was not great and meant to be a placeholder for a better name. I have decided to change the name SimplePen to ManureManagementPen and get rid of the SimpleAnimalManagement class. Since the manure module is mostly interested in the 'all_pens' attribute of the AnimalManagement class, it looks much simpler to just access it directly.

2022-09-14 01:40 UTC, PooyaHekmati approved these changes
lgtm

2022-09-14 20:16 UTC, merged