Update Anaerobic digestion
RuminantFarmSystems/RuFaS pull request #1843
Opened 2024-07-18 20:01 UTC by Isgotkowitz

### Context

Issue(s) closed by this pull request: closes #1832, closes #1370

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

This PR makes several updates to the Anaerobic Digestion and Anaerobic Lagoon modules, and several related spots in the code.

The changes include:
- Applying an automatic increase of Total Ammoniacal Nitrogen during the anaerobic digestion process (#1370)
- Swapping the term "biogas" for "methane" when referring to what is captured by the digester (#1417) edit: this change is not happening in this PR any longer, as it is not backwards compatible.
- Deprecating the Chen-Hashimoto method of methane generation estimation in the digester.
- Adding an input that allows users to control how much methane leakage there is in the digestion process.

### Why

These are just some improvements that were suggested/asked for to improve the Anaerobic digestion process.

### How

Constants have been added and removed in two of the manure constants files as equations are replaced. Methane generation, leakage, and energy content are now calculated with `calculate_CSTR_methane_volume`, `calculate_digester_methane_leakage`, and `calculate_methane_energy_content`, respectively, in `GasEmissionsCalculator`.

The process of calculating methane generation in `AnaerobicDigestion` has been modified so that it now accounts for methane leakage while calculating the final amounts of methane and methane-energy.

The metadata and manure module input have been updated so that the leakage fraction of methane from digesters can be controlled by the user, and the `ManureTreatmentConfig` class has been extended to handle this new input.

`ManureTreatmentDailyOutput` has been updated to include leaked methane and methane energy content (instead of biogas energy content).

### Test plan

Unit tests have been added and modified as appropriate to test all code changes. The outputs for anaerobic digestion have been updated to ensure that all methane generation and volatile solids loss is happening as expected.

Note that the new input files will be removed before merging, they are currently just here for testing purposes.

### Other
#1540/#1803 are not addressed in this PR. I think (but still need to confirm) that #1540 will be closed as unplanned and the issue will be addressed by #1803 instead, which I think will be large enough to merit its own PR.

I love that volatile solids loss is called volatile solids "destruction" in the code, it is very cathartic.

Edit: in order to maintain backwards-compatibility in this PR, the changes to variable names/outputs have been removed. So biogas is still biogas, instead of being changed to methane:/ i.e. this PR _does not_ fix #1417

2024-07-22 15:06 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/anaerobic_digestion.py
> +        )
@elle-andreen is this the blanket increase in TAN that is called for by #1370?

2024-07-22 17:35 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/anaerobic_digestion.py
> +        )
Yes! This is the blanket increase - the `AD_TAN_INCREASE_FACTOR` constant should be equal to 1.60 to result in a blanket 60% increase in TAN content.

2024-07-22 17:55 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/anaerobic_digestion.py
> +        )
Awesome, thank you

2024-07-22 20:44 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Energy content of methane, MJ/m^3.
@elle-andreen these units should be MJ not MJ/cubic meter right?

2024-07-24 18:11 UTC, elle-andreen commented on RUFAS/routines/manure/manure_handlers/manure_handler_classes.py
> +            liquid_manure_nitrogen=max(0.0, pen.manure.nitrogen - housing_ammonia_emission),
This is my doing rather than Ed's, but this change is definitely outside the scope of this PR. It _is_ something that should be changed, it just doesn't belong here 😊 I can pull it out and either pin it to the issue for doing the manure management chain mass balance, or create a mini PR for it. It's only downstream effect on emissions would be a slight drop in N2O, because N2O is estimate from manure N, rather than TAN.

2024-07-24 18:31 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/anaerobic_digestion_and_lagoon.py
> +        anaerobic_lagoon_daily_output.methane_generation_mass = (
I believe this variable should not be passed to the anaerobic lagoon treatment file (i.e., it should not appear in the ManureTreatmentDailyOutput for the anaerobic lagoon). This methane is strictly from the digester and should only be reported in the anaerobic digestion output, it is confusing to have it in the lagoon output because you end up with both `methane_generation_mass` and `storage_methane`.

2024-07-24 18:39 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/manure_treatment_configs.py
> +    digester_methane_leakage_fraction : float, default 0.0
Other variables in this list (dictionary?) don't have 'float' or 'default' included - are the other variables incomplete, or is the new addition incorrect? And, does `default` here need to be the actual default value or is `0.0` just the value format?

2024-07-24 18:44 UTC, elle-andreen commented on RUFAS/routines/manure/gas_emissions/calculator.py
>          return methane_volume * GasEmissionConstants.AD_METHANE_DENSITY * GasEmissionConstants.METHANE_ENERGY_DENSITY
I did not realize this originally but I think we can just pass `captured_methane_generation_mass` here instead of methane volume, since we are just multiplying by the same density value (e.g. `methane_volume * GasEmissionConstants.AD_METHANE_DENSITY` here is equal to `captured_methane_generation_mass`).

2024-07-24 18:46 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Energy content of methane, MJ/m^3.
Correct, it's MJ, good question. We are multiplying captured methane mass (kg) by the energy density constant, which is actually in MJ/kg (rather than m3 as it read originally). So we end up with a MJ value.

2024-07-24 18:47 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +    methane_energy_content_unit: MeasurementUnits = MeasurementUnits.MEGAJOULES_PER_CUBIC_METER
Related to your Q above - this should be MJ, not MJ/kg

2024-07-24 18:52 UTC, elle-andreen commented on input/data/manure/manure_management.json
> +      "digester_methane_leakage_fraction": 0.005
The leakage fraction default here is different from the default given in the metadata properties (0.01) - is that intentional? I also want to check with Kristan and others on this value before we merge. It's one little value but leakage is pretty controversial in the real world!

2024-07-24 19:55 UTC, elle-andreen commented
This is look great so far Ed. I left some comments in the code, and the comments below are moreso for other folks and for future reference:

- I like the naming scheme you went with - `captured_methane_generation_volume` for total methane minus leakage, and `total_methane_generation_volume` for the actual total amount. If it's not problematic, I would actually propose using these names in the output - I think they make the interpretation clearer! This PR intrinsically changes the inputs, so we can also confirm that output renaming is acceptable. 
- Heating input energy: I debated taking this out but ultimately I think we should leave it for now. I expect it will be an important part of EEE for anaerobic digestion and I don't see any big problems with the function, it does include manure moisture content as a variable but I think moisture vs solids content at the point of an anaerobic digester (e.g. before a lot of evaporation occurs in storage, that we are not accounting for) is reasonably correct for now. Addressing moisture content at different points in the manure module is on the improvements list anyway. 
- Evaporated water: when I send the design doc for SMEs to review, I will ask if this is something we should have. I don't know where this equation came from, but also it seems that the volume from evaporated water is not being subtracted from total manure volume anyway, so it's not having any effect. 
- (Just a reminder) Remove all changes from `manure_management.json` before marking as ready for review, with the exception of the addition of the leakage fraction input of course

2024-07-25 12:59 UTC, elle-andreen commented
In the [google doc with calculation details](https://docs.google.com/document/d/1om-czbamAUBlSAGegGuNhlSUny6EWygnwFSLF6wWkx0/edit?usp=sharing), I have added a sample output to help people reviewing this follow how calculations work. Hopefully it's helpful!

That being said, outputs are being calculated as expected! We still have a couple accessory things to change or confirm should be changed, but the core function is there. 

Also just saw:
>I love that volatile solids loss is called volatile solids "destruction" in the code, it is very cathartic.

It is a good term, the usual term in the literature is reduction or destruction, and the VS are literally being destroyed (degraded into a new chemical form) so 😄

2024-07-25 13:10 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_handlers/manure_handler_classes.py
> +            liquid_manure_nitrogen=max(0.0, pen.manure.nitrogen - housing_ammonia_emission),
I recommend creating a small PR to address exactly this - in fact, it is a really good practice to make very small PRs. I will undo the changes here

2024-07-25 13:14 UTC, Isgotkowitz commented on input/data/manure/manure_management.json
> +      "digester_methane_leakage_fraction": 0.005
No, I just wanted to try a value that I hoped was realistic - I will change it to 0.01

2024-07-25 14:04 UTC, Isgotkowitz commented on RUFAS/routines/manure/gas_emissions/calculator.py
>          return methane_volume * GasEmissionConstants.AD_METHANE_DENSITY * GasEmissionConstants.METHANE_ENERGY_DENSITY
Implemented

2024-07-25 14:06 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Energy content of methane, MJ/m^3.
Updated

2024-07-25 14:21 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_treatment_configs.py
> +    digester_methane_leakage_fraction : float, default 0.0
The other variables are incomplete. The things I added are in accordance with Numpy's [class docstring guideline](https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring).

0.0 is the default - in the `ManureTreatmentConfig` class. This default is not necessarily the same as the default defined in the metadata properties. A better solution would probably be to have no default for `digester_methane_leakage_fraction` in `ManureTreatmentConfig`.

2024-07-25 14:40 UTC, Isgotkowitz commented on input/data/manure/manure_management.json
> +      "digester_methane_leakage_fraction": 0.005
Also, this is an important distinction, that value is an input not a default. If a user were to not include the key `"digester_methane_leakage_fraction"`, then the Input Manager would pull a default value from the metadata properties, if provided.

2024-07-25 15:01 UTC, Isgotkowitz commented
> This is look great so far Ed. I left some comments in the code, and the comments below are moreso for other folks and for future reference:
> 
> * I like the naming scheme you went with - `captured_methane_generation_volume` for total methane minus leakage, and `total_methane_generation_volume` for the actual total amount. If it's not problematic, I would actually propose using these names in the output - I think they make the interpretation clearer! This PR intrinsically changes the inputs, so we can also confirm that output renaming is acceptable.

Thanks:) and I agree, I think it would make the outputs easier to understand. However the changes to outputs would be different in nature to the changes being made to the inputs here. The input changes are backwards compatible, i.e. someone with an existing manure management input file would not have to change it all for it to work with this new code. But a filter for getting digester methane outputs would likely have to be rewritten to work with the new naming scheme. We should talk to Pooya and/or Kristan about this. 

> * Heating input energy: I debated taking this out but ultimately I think we should leave it for now. I expect it will be an important part of EEE for anaerobic digestion and I don't see any big problems with the function, it does include manure moisture content as a variable but I think moisture vs solids content at the point of an anaerobic digester (e.g. before a lot of evaporation occurs in storage, that we are not accounting for) is reasonably correct for now. Addressing moisture content at different points in the manure module is on the improvements list anyway.

I am not sure what the heating input energy is, which spot in the code is this located?

> * Evaporated water: when I send the design doc for SMEs to review, I will ask if this is something we should have. I don't know where this equation came from, but also it seems that the volume from evaporated water is not being subtracted from total manure volume anyway, so it's not having any effect.

Is this equation changed at all in the code?

> * (Just a reminder) Remove all changes from `manure_management.json` before marking as ready for review, with the exception of the addition of the leakage fraction input of course

Will do.

2024-07-25 15:29 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/anaerobic_digestion.py
> +        assert self._current_manure_treatment_daily_input is not None
Added this just to make the number of Mypy errors go down.

2024-07-26 20:04 UTC, elle-andreen commented on input/data/manure/manure_management.json
> +      "digester_methane_leakage_fraction": 0.005
That's a good point! I always forget that the defaults come from the metadata properties, not the default input files.

2024-07-26 20:11 UTC, elle-andreen commented
> The input changes are backwards compatible, i.e. someone with an existing manure management input file would not have to change it all for it to work with this new code. But a filter for getting digester methane outputs would likely have to be rewritten to work with the new naming scheme. We should talk to Pooya and/or Kristan about this.

This is true! It will definitely be on the list of things to confirm before this merges. It is certainly not an essential change, it could stay as-is without a problem.

> I am not sure what the heating input energy is, which spot in the code is this located?

It is calculated in the `anaerobic_digestion.py` file using the `self._calc_specific_input_energy` function. It was not modified in any way by this PR though, I am mostly noting it so that the SMEs remember to revisit it down the line.

> Is this equation (Evaporated water) changed at all in the code?

Nope, it should be unchanged by this PR

2024-07-29 08:43 UTC, tomhuhh requested changes

2024-07-29 08:43 UTC, tomhuhh commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Mass of methane produced from anaerobic digestion, kg.
Would it help improve the clarity of the variable names by modifying it to 'AD_methane_generation_mass'? Likewise for the other variables. Thanks!

2024-07-29 08:43 UTC, tomhuhh commented on RUFAS/routines/manure/gas_emissions/calculator.py
What is the reference for this equation? 

The unit for `GasEmissionConstants.ACHIEVABLE_METHANE_EMISSION` is kg, while the unit of what is returned from `calculate_CSTR_methane_volume` is m^3 as indicated in the doc string. This creates a discrepancy. Either the doc string and the variable name need to be updated or the equation requires a unit conversion. Thanks!

2024-07-29 13:02 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Mass of methane produced from anaerobic digestion, kg.
That's a great question - is anaerobic digestion the only manure processor component that can or that should record methane generated like this?

2024-07-29 13:03 UTC, Isgotkowitz commented on RUFAS/routines/manure/gas_emissions/calculator.py
Nice catch Haowen, I will talk to Elle about this

2024-07-29 14:19 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Mass of methane produced from anaerobic digestion, kg.
Yes, anaerobic digesters are the only component with methane generation being estimated via the `calculate_CSTR_methane_volume` method and reporting the methane generation mass and volume variables. In terms of outputs, this variable should only appear in the anaerobic digestion daily output, not any other manure treatment, so I think that should largely avoid confusion. That being said, if you (@tomhuhh) feel like it would be helpful to have the names changed in the actual code to help avoid confusing these anaerobic digestion-specific methane variables with other methane variables, that would be fine with me!

2024-07-29 15:43 UTC, elle-andreen commented on RUFAS/routines/manure/gas_emissions/calculator.py
Great questions! First: this equation came directly from the SME's, they did not provide a specific reference. It is more of a generalization/expert interpretation of the agreed-upon constant conversion constant of manure VS to CH4 (240 L or 0.24 m3 of CH4 per kg manure VS). 

Second, for the `GasEmissionConstants.ACHIEVABLE_METHANE_EMISSION` constant: other than in the new CSTR methane estimation function in this PR, this constant is being called in calculator.py by the unused `methane_emission_from_anaerobic_lagoon` function, as well as in `ifsm_methane_emission` (used in open lots, CBPB). I double checked those design docs and I believe the original units of the constant (kg CH4/kg VS) are incorrect should be updated to m3 CH4/kg VS.

2024-07-29 20:27 UTC, Isgotkowitz commented on RUFAS/routines/manure/gas_emissions/calculator.py
I will update the constant to m^3 / kg

2024-07-29 20:57 UTC, Isgotkowitz commented on RUFAS/routines/manure/gas_emissions/calculator.py
@elle-andreen should all effected methods be changed so that they are returning cubic meters of methane, or should the equations be modified so that they convert the volume of methane to kg?

2024-07-30 03:42 UTC, tomhuhh commented on RUFAS/routines/manure/gas_emissions/calculator.py
Thanks for the great discussion here! I think we should make a note in the doc string that this equation comes from communication with subject matter experts and add a point of contact. I do not know about you guys, but I can easily forget this level of details. If we have a question about it down the road, it will cost us extra time and efforts to remember what exactly happened here and who we should contact. Thanks!

2024-07-30 03:50 UTC, tomhuhh commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Mass of methane produced from anaerobic digestion, kg.
Thank you for the clarification, Elle! I think choosing clear, descriptive variable names is essential for writing understandable and maintainable code. An example is that we recently changed the naming for enteric methane from 'methane' to 'enteric_methane' in the animal module code to avoid confusion with the variables in the manure module. Similarly, some variables in the anaerobic digestion submodule have already been using names containing 'AD' such as `AD_TAN_INCREASE_FACTOR`, `AD_carbon_dioxide`, `AD_VS_destruction`, etc. Thank you!

2024-07-30 12:51 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Mass of methane produced from anaerobic digestion, kg.
By changing the variable name, I assume we will change outputs - probably in a way that would require someone's filters to be rewritten. Is this ok, or would this be considered too much of a change to make right now?

2024-07-30 14:27 UTC, Isgotkowitz commented
@elle-andreen @tomhuhh while updating the units for the `ACHIEVABLE_METHANE_EMISSION` constant I found an inconsistency in the `METHANE_CONVERSION_FACTOR` (located in GasEmissionConstants). It states that it is used to convert cubic meters of methane to kg of methane, but also that it is "unitless". This is wrong - should I also update it in this PR?

2024-07-30 15:55 UTC, matthew7838 approved these changes
LGTM! The coding looks good, but some minor comments and things that I think are a good place to clear things up up sort it. Overall, impressive work to manage so many file changes.

2024-07-30 15:55 UTC, matthew7838 commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +        digester_methane_leakage_fraction : float
I think we should also decide if we want to use the current format for units or the ('unit') format we had in S&C. It's not a big problem but the earlier we can have a conclusion the less we have to modify later on.

2024-07-30 15:55 UTC, matthew7838 commented on RUFAS/routines/manure/gas_emissions/calculator.py
Might be beneficial to know which SME's equation it's from or at least stating it.

2024-07-30 15:55 UTC, matthew7838 commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +        """Calculates CH4 generation volume of anaerobic digestion in a continuously-stirred tank reactor.
```suggestion
        """
        Calculates CH4 generation volume of anaerobic digestion in a continuously-stirred tank reactor.
```

2024-07-30 15:55 UTC, matthew7838 commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +            Fraction of generated methane that escapes as leakage.
```suggestion
            Fraction of generated methane that escapes as leakage (unitless).
```

2024-07-30 15:55 UTC, matthew7838 commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +        """Calculates energy content of methane generated in a digester.
```suggestion
        """
        Calculates energy content of methane generated in a digester.
```

2024-07-30 15:55 UTC, matthew7838 commented on RUFAS/routines/manure/manure_treatments/anaerobic_digestion.py
> +        )
What's the purpose of "()" ?

2024-07-30 15:55 UTC, matthew7838 commented on tests/test_manure_module/test_gas_emissions_calculator.py
> +    expected = GasEmissionConstants.ACHIEVABLE_METHANE_EMISSION * VS_total
If these are constants, maybe we can pass in manually calculated values for expected?

2024-07-31 05:52 UTC, tomhuhh commented
> @elle-andreen @tomhuhh while updating the units for the `ACHIEVABLE_METHANE_EMISSION` constant I found an inconsistency in the `METHANE_CONVERSION_FACTOR` (located in GasEmissionConstants). It states that it is used to convert cubic meters of methane to kg of methane, but also that it is "unitless". This is wrong - should I also update it in this PR?

It sounds like an easy fix. I would include the change in this PR. Thanks for catching that Ed! Good work!

2024-07-31 05:58 UTC, tomhuhh commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Mass of methane produced from anaerobic digestion, kg.
That is a good point, Ed! My understanding is that the variable name `methane_generation_mass` is already a modification from the original variable name `biogas`. This means that the filter needs to be changed either way.  Thanks!

2024-07-31 13:29 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/manure_treatment_configs.py
> +    digester_methane_leakage_fraction : float, default 0.0
I'm a little fuzzy on what purpose defaults in the configs serve - if there was no default in `ManureTreatmentConfig` and the user also did not supply a value in the inputs, would this cause the simulation to fail? Or just take the metadata default value?

2024-07-31 13:39 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Mass of methane produced from anaerobic digestion, kg.
Haowen is correct, we're already proposing to change the variable name, so we may as well change it to exactly what we want. I think we can go ahead and add the AD prefix to all variables that are specific to anaerobic digestion. In `manure_treatment_daily_output.py`, this is all variables from line 159 to 191 (although some of these, like top cover volume and minimum digester volume, may end up being removed).

Just to add a note here as well regarding naming and other changes to outputs - right now we are making changes to this PR according to the "ideal" without regard to maintain backward-compatibility. We are waiting on specific guidance from Kristan and Pooya on how exactly to handle these types of proposed changes. The likely outcome is that we will create a branch off of this branch that contains only the "internal" changes to preserve backward-compatibility, and preserve the rest of the changes in this PR to be merged at a later date.

2024-07-31 13:50 UTC, elle-andreen commented on RUFAS/routines/manure/gas_emissions/calculator.py
Agreed, we can add info on the source of the function directly to the docstring here (I'll push a commit with this @Isgotkowitz). I can also ask the SMEs if they have one or more references where this method was used.

2024-07-31 14:07 UTC, elle-andreen commented
> @elle-andreen @tomhuhh while updating the units for the `ACHIEVABLE_METHANE_EMISSION` constant I found an inconsistency in the `METHANE_CONVERSION_FACTOR` (located in GasEmissionConstants)


(Just pasting this here to preserve the info) The constant `METHANE_CONVERSION_FACTOR` is related to what % of VS are converted to methane I believe, it's not a units conversion. The constant `METHANE_FACTOR` is actually where the m3 -> kg conversion takes place, and its units are okay. The constants are definitely named confusingly but other than that there is no calculation or units issue that I can see!

2024-07-31 14:23 UTC, elle-andreen commented on RUFAS/routines/manure/gas_emissions/calculator.py
```suggestion
This function originates from personal communications with subject matter experts Wei Liao (liaow@msu.edu) and April Leytem (april.leytem@usda.gov). The equation is a simplification of the IPCC Tier II estimate of CH4 emissions from anaerobic digesters, where CH4 generated in the digester is assumed to be equivalent to the amount of manure volatile solids loaded per day, multiplied by the generally-accepted methane potential value for dairy manure (240 L CH4 per kg of manure volatile solids).

2024-07-31 14:57 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/anaerobic_digestion.py
> +        )
It's just formatting. `new_daily_output.liquid_manure_total_solids = self._current_manure_treatment_daily_input.liquid_manure_total_solids - AD_VS_destruction` is too long to fit on a single line.

2024-07-31 16:18 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Mass of methane produced from anaerobic digestion, kg.
>Just to add a note here as well regarding naming and other changes to outputs - right now we are making changes to this PR according to the "ideal" without regard to maintain backward-compatibility. We are waiting on specific guidance from Kristan and Pooya on how exactly to handle these types of proposed changes. The likely outcome is that we will create a branch off of this branch that contains only the "internal" changes to preserve backward-compatibility, and preserve the rest of the changes in this PR to be merged at a later date.

I can make these changes if that is what is desired for this PR. However we should consider whether this is an effective development strategy to employ. I think there are a number of problems with it.

First, making a lot of changes but only intending to actually merge some of them by creating another PR with a subset of those changes is a fraught process. It requires making the same changes not once but twice, which is not efficient but more importantly, opens up a window for those changes to be made incorrectly.

Second, after the changes that are possible are merged in, we're left with a PR that might easily be left open for a very long time. This is bad for several reasons: it takes time and effort to keep that PR from getting stale (potentially a lot of time and effort, because there might be significant changes merged in which require fixing a lot of merge conflicts). Also, the longer the PR is open, the harder it will be to remember exactly what and why it has the changes it does. Which will increase the amount of time needed to keep it updated.

In my opinion, a better strategy would be to write an issue specifically for the changes that we are unsure about, get those changes greenlit with Pooya and/or Kristan, then implement those changes. That way, the time and effort to actually make the changes only happens after we know that we are ready to accept the changes. If it turns out that we don't want to make the changes, then we just close the issue without having spent much time working on it. This agrees with what is stated in the code review Wiki: "Making a PR means that the code is ready to be merged as-is. A PR has to have any temporary and test files and pieces of code removed, and a clean and ready-to-merge submission is needed."

2024-07-31 16:20 UTC, Isgotkowitz commented on RUFAS/routines/manure/gas_emissions/calculator.py
Thanks Elle!

2024-07-31 18:57 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Mass of methane produced from anaerobic digestion, kg.
I agree that it's not a great option, but I'm just relaying what has been conveyed to me. From my understanding, we should receive specific guidance on what to do with this specific PR, and also for these cases going forward, so I would not change anything until we hear from Kristan/Pooya (but I would definitely share your comment with them!). The request to make these changes to anaerobic digestion and the work on this branch predated the initiation of the new branching strategy, and I think if the branching strategy change plus absolute requirement for backward compatibility had been apparent at that time, we would have gone about this PR differently. I expect this will not be the only case where there are good but maybe not immediately urgent reasons to change inputs/outputs, I think we're just waiting on technical guidance for how to handle that

2024-07-31 19:20 UTC, Isgotkowitz commented on RUFAS/routines/manure/gas_emissions/calculator.py
> +        digester_methane_leakage_fraction : float
I agree. For now though I will keep it consistent with the rest of the units in this file.

2024-07-31 19:20 UTC, Isgotkowitz commented on tests/test_manure_module/test_gas_emissions_calculator.py
> +    expected = GasEmissionConstants.ACHIEVABLE_METHANE_EMISSION * VS_total
Yes, that would be much better.

2024-07-31 20:29 UTC, Isgotkowitz commented
> > @elle-andreen @tomhuhh while updating the units for the `ACHIEVABLE_METHANE_EMISSION` constant I found an inconsistency in the `METHANE_CONVERSION_FACTOR` (located in GasEmissionConstants)
> 
> (Just pasting this here to preserve the info) The constant `METHANE_CONVERSION_FACTOR` is related to what % of VS are converted to methane I believe, it's not a units conversion. The constant `METHANE_FACTOR` is actually where the m3 -> kg conversion takes place, and its units are okay. The constants are definitely named confusingly but other than that there is no calculation or units issue that I can see!

Sorry, you're right, I was unsure of the units on `METHANE_FACTOR`, not `METHANE_CONVERSION_FACTOR`. I do think though that the docstring for `METHANE_FACTOR` is incorrect, if it converts cubic meters of methane to kg methane then its units are $m^3$ / kg, not unitless.

2024-07-31 20:33 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Mass of methane produced from anaerobic digestion, kg.
Ok, thank you @elle-andreen. I will hold off on making more changes for now. Do you want to reach out to Kristan or Pooya about this PR, or would it be better if I asked about it?

Also, if it would be helpful, I could go ahead and split up this PR so that there is an additional PR, that one with backwards-compatible changes and this one with non-backwards compatible changes?

2024-08-02 20:28 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/anaerobic_digestion.py
> +        new_daily_output.methane_energy_content = captured_methane_energy_content
```suggestion
        new_daily_output.biogas_energy_content = captured_methane_energy_content
```
Reverting output name change but preserve new internal calculation of biogas methane content

2024-08-02 21:16 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/anaerobic_digestion.py
> +        new_daily_output.methane_generation_mass = captured_methane_generation_mass
```suggestion
        new_daily_output.biogas = captured_methane_generation_mass
```
Remove the output name change but preserve the new value of the output.

2024-08-05 14:00 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/anaerobic_digestion_and_lagoon.py
```suggestion

anaerobic_lagoon_daily_output.biogas = self.anaerobic_digestion_daily_output.biogas
```
Reverting removal of this output to maintain backwards compatibility

2024-08-05 14:02 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +        Unit for methane_energy_content.
```suggestion
   biogas: float, default 0.0
        Mass of methane produced from anaerobic digestion, kg.
   biogas_unit: MeasurementUnits, default MeasurementUnits.KILOGRAMS_PER_DAY
        Unit for methane_generation_mass.
    biogas_energy_content : float, default 0.0
        Energy content of methane, MJ.
   biogas_energy_content_unit: MeasurementUnits, default MeasurementUnits.MEGAJOULES
        Unit for methane_energy_content.
```
Reverting output name changes to maintain backwards compatibility

2024-08-05 14:04 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +    methane_generation_mass_unit: MeasurementUnits = MeasurementUnits.KILOGRAMS_PER_DAY
```suggestion
   biogas: float = 0.0
    biogas_unit: MeasurementUnits = MeasurementUnits.KILOGRAMS_PER_DAY
```
Reverting output name changes to maintain backwards compatibility

2024-08-05 14:06 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +    methane_energy_content_unit: MeasurementUnits = MeasurementUnits.MEGAJOULES
```suggestion
   biogas: float = 0.0
   biogas_unit: MeasurementUnits = MeasurementUnits.KILOGRAMS_PER_DAY
```
Reverting output name changes to maintain backwards compatibility

2024-08-06 12:58 UTC, Isgotkowitz commented on RUFAS/routines/manure/constants_and_units/gas_emission_constants.py
> +    The volumetric ratio of carbon dioxide to methane generated during anaerobic digestion :math:`m^3`
Would the units here be cubic meters CO2 to cubic meters CH4?

2024-08-06 13:10 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_treatment_configs.py
> +    digester_methane_leakage_fraction : float, default 0.0
> I'm a little fuzzy on what purpose defaults in the configs serve

Honestly they don't serve much of a purpose at all, if all the defaults were removed I would expected the behavior to be the same for the most part.

> if there was no default in `ManureTreatmentConfig` and the user also did not supply a value in the inputs, would this cause the simulation to fail?

Not necessarily, it depends on the input. If there was a default for that input in the metadata then that default would be used and the simulation would run normally. If there was no default in the metadata then the simulation would crash, but that crash would occur while parsing the inputs. In either case though, it wouldn't really matter if there was a default in `ManureTreatmentConfig` or not

2024-08-06 13:38 UTC, elle-andreen commented on RUFAS/routines/manure/constants_and_units/gas_emission_constants.py
> +    The volumetric ratio of carbon dioxide to methane generated during anaerobic digestion :math:`m^3`
Yes, I think that would be the more technically correct unit! (m^3 CO2 : m^3 CH4)

2024-08-06 14:58 UTC, Isgotkowitz commented on RUFAS/routines/manure/constants_and_units/gas_emission_constants.py
> +    The volumetric ratio of carbon dioxide to methane generated during anaerobic digestion :math:`m^3`
Will update it

2024-08-06 17:57 UTC, elle-andreen commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +    biogas_energy_content_unit: MeasurementUnits = MeasurementUnits.KILOGRAMS_PER_DAY
```suggestion
    biogas_energy_content_unit: MeasurementUnits = MeasurementUnits.MEGAJOULES
```

2024-08-06 18:28 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +    biogas_energy_content_unit: MeasurementUnits = MeasurementUnits.KILOGRAMS_PER_DAY
Nice catch

2024-08-06 19:23 UTC, elle-andreen approved these changes
Thanks for your hard work on this Ed!

Because this PR includes changes to inputs and outputs (though backwards-compatibility is maintained), for others' reference, here is a table of the input and output changes from this PR. The actual table can be accessed [here](https://docs.google.com/document/d/1om-czbamAUBlSAGegGuNhlSUny6EWygnwFSLF6wWkx0/edit?usp=sharing).


![image](https://github.com/user-attachments/assets/d6e6676a-32fb-404b-ad48-06e2b47e4b0c)

2024-08-10 14:07 UTC, tomhuhh commented
Great work Elle and Ed! I tested with manure scenarios 5 through 7, before and after the changes suggested in this PR and the results are summarized below. 

<meta charset="utf-8"><b style="font-weight:normal;" id="docs-internal-guid-1e05ef04-7fff-0d96-1206-769607413276">
  | AD updated | main
-- | -- | --
5: Manure trt storage CH4(kg) | 7.86 | 8.64
5: Biogas (m^3/day) | 26.48 | 19.07
6: Manure trt storage CH4(kg) | 4.96 | 7.29
6: Biogas (m^3/day) | 26.86 | 16.16
7: Manure trt storage CH4(kg) | 2.51 | 6.03
7: Biogas (m^3/day) | 35.40 | 21.34

</b>

The results agree with my expectations. Generally, with the changes proposed, more methane (biogas) is generated during the anaerobic digestion step compared to previously, and less methane (storage_methane) is generated during the anaerobic lagoon step. 

One final observation is that I noticed some inconsistency in terms of how biogas is reported. It seems that biogas is also listed as an attribute of ManureTreatmentDailyOutput in addition to as an attribute of anaerobic digestion. This makes sense because we can consider anaerobic digestion and lagoon as a manure treatment. However, if that is the case, we should also output biogas_energy_content, methane_generaton_volume, and methane_leakage_mass as attributes of ManureTreatmentDailyOutput as well. Currently they are output as zero. 

As my final observation has minimal impact on the final outcome of the model, so I decided to approve this PR. My suggestion is to have it fixed before the merge. Thanks!

2024-08-10 14:08 UTC, tomhuhh approved these changes

2024-08-10 14:50 UTC, Isgotkowitz commented
> Great work Elle and Ed! I tested with manure scenarios 5 through 7, before and after the changes suggested in this PR and the results are summarized below.
> 
>  	AD updated	main
> 5: Manure trt storage CH4(kg)	7.86	8.64
> 5: Biogas (m^3/day)	26.48	19.07
> 6: Manure trt storage CH4(kg)	4.96	7.29
> 6: Biogas (m^3/day)	26.86	16.16
> 7: Manure trt storage CH4(kg)	2.51	6.03
> 7: Biogas (m^3/day)	35.40	21.34
> The results agree with my expectations. Generally, with the changes proposed, more methane (biogas) is generated during the anaerobic digestion step compared to previously, and less methane (storage_methane) is generated during the anaerobic lagoon step.
> 
> One final observation is that I noticed some inconsistency in terms of how biogas is reported. It seems that biogas is also listed as an attribute of ManureTreatmentDailyOutput in addition to as an attribute of anaerobic digestion. This makes sense because we can consider anaerobic digestion and lagoon as a manure treatment. However, if that is the case, we should also output biogas_energy_content, methane_generaton_volume, and methane_leakage_mass as attributes of ManureTreatmentDailyOutput as well. Currently they are output as zero.
> 
> As my final observation has minimal impact on the final outcome of the model, so I decided to approve this PR. My suggestion is to have it fixed before the merge. Thanks!

Thank you for taking to the time to do such a detailed analysis @tomhuhh. I will look into why the biogas_energy_content, methane_generation_volume and leakage mass are 0 and figure out a fix.

2024-08-12 15:16 UTC, elle-andreen commented
> > One final observation is that I noticed some inconsistency in terms of how biogas is reported. It seems that biogas is also listed as an attribute of ManureTreatmentDailyOutput in addition to as an attribute of anaerobic digestion. This makes sense because we can consider anaerobic digestion and lagoon as a manure treatment. However, if that is the case, we should also output biogas_energy_content, methane_generaton_volume, and methane_leakage_mass as attributes of ManureTreatmentDailyOutput as well. Currently they are output as zero.
> > As my final observation has minimal impact on the final outcome of the model, so I decided to approve this PR. My suggestion is to have it fixed before the merge. Thanks!
> 
> Thank you for taking to the time to do such a detailed analysis @tomhuhh. I will look into why the biogas_energy_content, methane_generation_volume and leakage mass are 0 and figure out a fix.

@tomhuhh I may be wrong, but my understanding is that the ManureTreatmentDailyOutput values for pens assigned to the anaerobic digestion and lagoon combo treatment are from only the anaerobic lagoon, not both the digester and lagoon, as the digester output values are reported separately in their own output. I think the repetition of the biogas variables/values in both the anaerobic digestion and anaerobic lagoon outputs is confusing and I worry that adding these values where there were previously 0's may cause confusion for FARM ES. If not for needing to keep all changes backward-compatible, in this PR we would have removed the biogas output value from the anaerobic lagoon daily output I believe. I realize it's not ideal, but my recommendation would be to leave those outputs alone for now, then resolve or remove them once we are able to make non-backwards-compatible changes again, but I am open to your thoughts! We do also have a PR to separate manure treatments and storages (issue #1619) which will likely result in the removal of this type of output from the set of anaerobic lagoon daily outputs.

2024-08-12 17:38 UTC, tomhuhh commented
> > > One final observation is that I noticed some inconsistency in terms of how biogas is reported. It seems that biogas is also listed as an attribute of ManureTreatmentDailyOutput in addition to as an attribute of anaerobic digestion. This makes sense because we can consider anaerobic digestion and lagoon as a manure treatment. However, if that is the case, we should also output biogas_energy_content, methane_generaton_volume, and methane_leakage_mass as attributes of ManureTreatmentDailyOutput as well. Currently they are output as zero.
> > > As my final observation has minimal impact on the final outcome of the model, so I decided to approve this PR. My suggestion is to have it fixed before the merge. Thanks!
> > 
> > 
> > Thank you for taking to the time to do such a detailed analysis @tomhuhh. I will look into why the biogas_energy_content, methane_generation_volume and leakage mass are 0 and figure out a fix.
> 
> @tomhuhh I may be wrong, but my understanding is that the ManureTreatmentDailyOutput values for pens assigned to the anaerobic digestion and lagoon combo treatment are from only the anaerobic lagoon, not both the digester and lagoon, as the digester output values are reported separately in their own output. I think the repetition of the biogas variables/values in both the anaerobic digestion and anaerobic lagoon outputs is confusing and I worry that adding these values where there were previously 0's may cause confusion for FARM ES. If not for needing to keep all changes backward-compatible, in this PR we would have removed the biogas output value from the anaerobic lagoon daily output I believe. I realize it's not ideal, but my recommendation would be to leave those outputs alone for now, then resolve or remove them once we are able to make non-backwards-compatible changes again, but I am open to your thoughts! We do also have a PR to separate manure treatments and storages (issue #1619) which will likely result in the removal of this type of output from the set of anaerobic lagoon daily outputs.

Hello Elle! I think this is a great idea. Let's write an issue for it and merge this PR for now. 

@Isgotkowitz Do you mind keeping a record of this issue? Thanks!

2024-08-12 18:22 UTC, Isgotkowitz commented
@tomhuhh pointed out that anaerobic lagoons are reporting biogas when they are combined with anaerobic digesters, which is why it would be strange that lagoons would not also report biogas energy content, methane generation, and methane leakage. It seemed to us that it would be best to remove this copying of biogas so that anaerobic lagoons never report having any biogas, but this should be done in a follow-up PR so that we can take our time to clear this change with FARM-ES.

2024-08-12 18:25 UTC, merged