Feed quality patch
RuminantFarmSystems/RuFaS pull request #187
Opened 2022-08-18 22:12 UTC by KFosterReed

This pull request addresses an couple of issues that arose when we merged the heifer_ration branch to add ration formulation for all animal types as well as a few other bugs with the output reporting. 

Specifcially, it addresses the following issues: 
- #129 
- #111 
- #112 
- #186 

To address the functional issues of 112 and 129, we changed the ration report to create columns for all potential feeds and then subset the dictionary of available feeds that is passed to the ration formulation driver using the input_feed_combinations set in the feed class. I also deleted some duplicated lists of feed_ids in feed.py to try to streamline the tracking of which feeds are being used to feed which animals. 

There are a couple of new functions that helped make this possible: 
- in ration_driver.py the function get_feed_data_from_feed_ids()
- in feed.py the function get_quality_specific_feed_costs()
Both functions are accompanied by their associated unit tests. 

To test the new functionality you can run the feed_update.json file or add any feed that has multiple feed ids that indicate a different quality (e.g. 34, 52, 57, 81, etc). If you are unfamiliar with the feed library, you can find a description of it here: [https://docs.google.com/document/d/1f3nWrn5fMy8NSIuZlrgZY5SXwmKcIF3t93O70qdSBVc/edit?usp=sharing](url)

I think this is an easy to medium review. There is very little new code to review (<100 lines). I think it might take 1-2 hours to review. I am requesting a review by next week Thursday (August 25th). 

Also, I used the following diagram to help me debug this issue. Maybe it will be helpful to you: 
![image](https://user-images.githubusercontent.com/41019131/185499157-e4ba53d9-4e63-4458-8a91-44202122503e.png)

2022-08-26 17:10 UTC, Fjordrunner requested changes
I didn't want to comment on every single commented line of old code, but shouldn't those be deleted if this is a quality patch? Doing so would improve the readability of the code significantly. I can take another look at the code once again after you've responded to the comments, but it looks pretty good overall.

2022-08-26 17:10 UTC, Fjordrunner commented on RUFAS/routines/animal/animal_management.py
>              if len(self.all_pens[pen].animals_in_pen) > 0 and 'Cow' in self.all_pens[pen].classes_in_pen and \
Wouldn't we want the else statement to reflect some of the additional conditions besides the length of the "animals_in_pen" variable to reflect similar logic? That is, shouldn't the second two conditions in the if-statement hold for the else statement? If so, why don't we extract those last two conditions in the if-statement? If not, then we should add additional checks for the else logic so that it mirrors that of the initial if-statement in my opinion.

2022-08-26 17:10 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_driver.py
> +                idx = self._feed_id_to_list_idx_dict[int(feed_id)]
What does "idx" stand for? A more descriptive variable name might be helpful here, unless "idx" is a commonly used abbreviation I'm just not familiar with.

2022-08-26 19:13 UTC, Brandon-DeBoer reviewed
Unit tests look good! each test has a clear objective in what is being tested, and everything passes.

2022-08-26 19:50 UTC, ancheypeng commented on RUFAS/routines/animal/pen.py
> +            animal.manure_excretion[key] = self.manure[key] / (len(self.animals_in_pen)+ 0.01)
Could we instead check if the length of `self.animals_in_pen` is 0 with an if statement, and then set the value to whatever it should be when there are no animals?

2022-08-26 22:06 UTC, KFosterReed commented
> 
Thanks for the review Simon!  

I did try to remove commented out code both in cases where I did it and other places where there was older code left in there. I will check for any places where I left code that I commented out and remove it. In general though I want to make sure we are speaking the same language with the name of the branch in case this is related to your comment. I used the phrase 'feed quality path' to refer to the need to fix the bug related to using feeds that have different quality levels (i.e. a high quality hay vs. a low quality hay) due to the way these are stored and identified in the feed database. So the purpose of this pull request is not to improve the quality of the code. I'm not sure if that is how you interpreted it but wanted to add some clarity.

2022-08-26 22:10 UTC, KFosterReed commented on RUFAS/routines/animal/pen.py
> +            animal.manure_excretion[key] = self.manure[key] / (len(self.animals_in_pen)+ 0.01)
Good idea!

2022-08-26 22:15 UTC, KFosterReed commented on RUFAS/routines/animal/ration/ration_driver.py
> +                idx = self._feed_id_to_list_idx_dict[int(feed_id)]
@ltp23 can you add some description to this?

2022-08-26 22:26 UTC, KFosterReed commented on RUFAS/routines/animal/animal_management.py
>              if len(self.all_pens[pen].animals_in_pen) > 0 and 'Cow' in self.all_pens[pen].classes_in_pen and \
Hmm, I think I see what you're saying. The second if statement on 480 was only added in response to an error but let me rework it and see if I can improve the logic a bit

2022-08-30 11:34 UTC, ltp23 commented on RUFAS/routines/animal/ration/ration_driver.py
> +                idx = self._feed_id_to_list_idx_dict[int(feed_id)]
Some extra comments were added.

2022-08-30 12:11 UTC, KFosterReed commented
@ancheypeng @Fjordrunner I think Loi and I have addressed all your comments. Could you please take a look at them by the end of the week? 
@PooyaHekmati could you please also give this a review?

2022-08-30 15:32 UTC, Fjordrunner commented on RUFAS/routines/animal/animal_management.py
>              if len(self.all_pens[pen].animals_in_pen) > 0 and 'Cow' in self.all_pens[pen].classes_in_pen and \
This looks better! I think that extracting the logic that would apply to both the if-clause and else-clause outside of both of them is usually good practice, to reduce the length of if-clauses and have cleaner code in general. Thanks!

2022-08-30 15:39 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_driver.py
> +                idx = self._feed_id_to_list_idx_dict[int(feed_id)]
Those comments look pretty good and definitely provide some insight! A couple of critiques though:

1. I think that adding a one-line description of what the variable "idx" stands for, or what specifically it is would be helpful. I was able to infer that it tracks the list index of each feed_id, but I'm not confident that's right because of the indirectness of the description. Making a description of the variable that's short, simple, and explicit would be helpful in my opinion.
2. I also think that it's best practice to not have blocky comments, that is, comments that are too long because they're trying to explain too much. Ideally, good code is able to explain its functionality by itself. Is there some info that could be  left out from the larger comment block?

 Once again, I think the comments provided a lot of insight, but I think some minor cleanup would make the code a bit more readable. I could also be wrong in my comments, so I'm definitely open to some discussion. I was just able to work with a rather clean codebase at Google over the summer, and making ours as clean and readable as possible is definitely one of my goals. Thanks again Loi!

2022-08-30 15:41 UTC, Fjordrunner commented
> > 
> 
> Thanks for the review Simon!
> 
> I did try to remove commented out code both in cases where I did it and other places where there was older code left in there. I will check for any places where I left code that I commented out and remove it. In general though I want to make sure we are speaking the same language with the name of the branch in case this is related to your comment. I used the phrase 'feed quality path' to refer to the need to fix the bug related to using feeds that have different quality levels (i.e. a high quality hay vs. a low quality hay) due to the way these are stored and identified in the feed database. So the purpose of this pull request is not to improve the quality of the code. I'm not sure if that is how you interpreted it but wanted to add some clarity.

I appreciate the clarification: that definitely makes more sense now. Thanks for removing the commented-out that wasn't being used, every step we take to clean up the codebase is one in the right direction!

2022-08-30 15:42 UTC, Fjordrunner commented
> @ancheypeng @Fjordrunner I think Loi and I have addressed all your comments. Could you please take a look at them by the end of the week? @PooyaHekmati could you please also give this a review?

The PR is looking pretty clean, good job everyone! LGTM

2022-08-31 15:45 UTC, ancheypeng commented
> @ancheypeng @Fjordrunner I think Loi and I have addressed all your comments. Could you please take a look at them by the end of the week? @PooyaHekmati could you please also give this a review?

Looks good now!

2022-08-31 15:55 UTC, ancheypeng approved these changes

2022-09-04 19:08 UTC, PooyaHekmati requested changes
I think the difficulty of this review was hard. This is mainly due to the fact that it does not follow the single responsibility principle (the PR aims to achieve multiple things instead of one). Returning the PR (1) to give the author chance to address my comments (2) address codefactor issues (3) add unit tests for modified functions (4) solve the merge conflict.

2022-09-04 19:08 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +            self.reports['pen_' + str(pen.id)] = PenReport(data, state.feed, pen.id)
let's use f-strings here:
self.reports[f'pen_{pen.id}'] = PenReport(data, state.feed, pen.id)

2022-09-04 19:08 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +    def __init__(self, data, feed, pen_id):
can we have type annotation here?

2022-09-04 19:08 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
> +        def __init__(self, data, feed, pen_id):
type annotation

2022-09-04 19:08 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
>              all_feeds = feed.all_feed_ids
unless we are using names incorrectly, feed.all_feed_ids is a list but the comment says all_feeds is a dictionary. Either feed.all_feed_ids has a misleading name or all_feeds is not a dictionary. Something is off here.

2022-09-04 19:08 UTC, PooyaHekmati commented on RUFAS/routines/animal/animal_management.py
> +               #     self.all_pens[pen].ration == {}:
why are we keeping commented-out lines?

2022-09-04 19:08 UTC, PooyaHekmati commented on RUFAS/routines/animal/animal_management.py
>          for pen in range(len(self.all_pens)):
this is not a good name; it has to change to either for pen in self.all_pens or for i in range(len(self.all_pens)

2022-09-04 19:08 UTC, PooyaHekmati commented on RUFAS/routines/animal/ration/ration_driver.py
> +        #self.pyomo_data = {}
?

2022-09-04 19:08 UTC, PooyaHekmati commented on RUFAS/routines/animal/ration/ration_driver.py
> +        #self.feeds = []
?

2022-09-04 19:08 UTC, PooyaHekmati commented on RUFAS/routines/animal/ration/ration_driver.py
> +                idx = self._feed_id_to_list_idx_dict[int(feed_id)]
idx stands for index, I think this is well-known and clear. I agree that comments are not good (generally speaking). This is not something new, we have been talking about this from uncle bob's videos onward. Two common techniques to mitigate this issue are (1) breaking the code into smaller functions and giving them good names, (2) using explanatory variables. Any additional info that could not be expressed via code, should go to docstrings.

2022-09-04 19:20 UTC, KFosterReed commented on RUFAS/output_handler/reports/pen_report.py
> +            self.reports['pen_' + str(pen.id)] = PenReport(data, state.feed, pen.id)
I am sure that the suggested string method would be an improvement but currently the entire output handler is formatted in the same way as this line. I would prefer to leave it as it now and either update the method for the entire handler or one report at a time. It doesn't make much sense to me to change one line

2022-09-04 19:20 UTC, KFosterReed commented on RUFAS/output_handler/reports/pen_report.py
> +    def __init__(self, data, feed, pen_id):
This is the same as the above.

2022-09-04 19:25 UTC, KFosterReed commented on RUFAS/routines/animal/animal_management.py
>          for pen in range(len(self.all_pens)):
This is not part of the new code

2022-09-04 19:36 UTC, KFosterReed commented on RUFAS/output_handler/reports/pen_report.py
>              all_feeds = feed.all_feed_ids
This is a dictionary with all feed ids and their units

2022-09-04 20:25 UTC, KFosterReed commented on RUFAS/routines/animal/animal_management.py
> +               #     self.all_pens[pen].ration == {}:
removed

2022-09-04 20:25 UTC, KFosterReed commented on RUFAS/output_handler/reports/pen_report.py
> +        def __init__(self, data, feed, pen_id):
same as above

2022-09-04 20:32 UTC, KFosterReed commented
> 
Thanks for the feedback about the difficulty of the pull request. Can you give me an estimate of how long it took you to review for future reference?

A couple of comments on the requested changes: 

1) there are unit tests for the new functions added. The other functions that were 'changed' were only minimally adjusted to change inputs and outputs. I think adding unit tests to all the functions used to fix this functionality is outside the scope of this pull request.

2) I think the merge conflict that was introduced by your merge to the master branch is now fixed

3) The codefactor issues with the output handler are extensive and, as we have discussed, the output handler needs to be updated so I also think that is outside the scope of this pull request

2022-10-18 17:45 UTC, KFosterReed commented
I'd like to revive this pull request. Other than the output handler changes which we agree to hold off on since Pooya is taking the lead to overhaul that part of the model, it looks like we have addressed most of the existing comments. The two things I think we are waiting on are:

1) Potential renaming and improving of the get_feed_data_from_feed_ids() function - @ltp23 can you please check with @PooyaHekmati about this?
2) Subject matter expert review - @TEDS-91 and @manfei-L can you please provide your review?

2022-10-19 01:57 UTC, Fjordrunner approved these changes

2022-10-19 01:57 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_driver.py
> +        Returns a subset of data from all the available feeds based on the
This is very nitpicky, but having a upper description explaining what the function returns while also having a returns field lower in the docstring is a bit redundant.

2022-10-19 01:57 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_driver.py
> +                idx = self._feed_id_to_list_idx_dict[int(feed_id)]
I will make a separate pull request with Loi's help and pull these comments into some external file that will then be linked here for an explanation, so as to eliminate the blocky comments.

2022-10-19 12:07 UTC, KFosterReed commented on RUFAS/routines/animal/ration/ration_driver.py
> +        Returns a subset of data from all the available feeds based on the
What about 'creates a subset of the available feeds based on the set of feed ids provided so feeds can be allocated to specific pens or animal classes'

Maybe that is too much information but I thought giving some context as to why we need to subset the available feeds dict might be helpful?

2023-01-12 20:12 UTC, closed without merging