Cap and flare modification
RuminantFarmSystems/RuFaS pull request #1892
Opened 2024-08-07 08:34 UTC by matthew7838

Add representation of 'Cap and Flare' to outdoor manure storage/treatment systems.
### Context

Issue(s) closed by this pull request: closes #1857

- [ ] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

- Add an input option to the current "manure_cover" input field within the "manure_treatment_configs" section of the manure_management input file. The new option could be "cover and flare" to indicate that this storage system has a cover as well as a flare.
- Added a manure module constant that is the methane_destruction_efficiency with a default value of 81%
- Added conditional statements so the methane predicted by the methane_emission_from_slurry_storage is multiplied by (1- methane_destruction_efficiency/100) when the newly added cover and flare were used.
- Add a new daily output called storage_methane_avoided.

### Why

This technology was on our original V1 requirements and we would like to add a simple representation of this method that is a modifier of our current slurry storage outdoor and anaerobic lagoon methods.

### How

### Test plan

- SMEs to confirm simulation results as intended

2024-08-09 19:57 UTC, Isgotkowitz reviewed
This is a good start to introducing cap and flare, but I noticed several things that do not follow best practices for clean code. Left comments on several things, please let me know if you have any questions.

2024-08-09 19:57 UTC, Isgotkowitz commented on RUFAS/routines/manure/constants_and_units/manure_constants.py
> +    The fraction of methane destruction efficiency rate.
```suggestion
    The percentage of methane destroyed on a daily(?) basis in systems using a cap and flare.
```
This constant is a percentage, not a fraction. Also, I am not sure that this is exactly what/how this constant used.

2024-08-09 19:57 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/anaerobic_lagoon.py
> +            methane_loss = methane_loss * (1 - ManureConstants.METHANE_DESTRUCTION_EFFICIENCY / 100)
```suggestion
            daily_output.storage_methane_avoided = methane_loss * ManureConstants.METHANE_DESTRUCTION_EFFICIENCY * GeneralConstants.PERCENTAGE_TO_FRACTION
            methane_loss = methane_loss * (1 - ManureConstants.METHANE_DESTRUCTION_EFFICIENCY * GeneralConstants.PERCENTAGE_TO_FRACTION)
```

2024-08-09 19:57 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/anaerobic_lagoon.py
> +        if self.config.manure_cover == "cover and flare":
```suggestion
        if self.config.manure_cover == ManureCoverEnum.COVER_AND_FLARE.value:
```
Ideally, `self.config.manure_cover` would be an enum element and not a string, and would be compared directly to the `ManureCoverEnum`.

2024-08-09 19:57 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/manure_treatment_daily_output.py
> +
Docstring needs to be updated. Also, I suggest the name `storage_methane_burned` instead - "avoided" is kinda unclear.

2024-08-09 19:57 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/slurry_storage_outdoor.py
> +            daily_output.storage_methane = methane_loss
This code perfectly duplicates the new code in `AnaerobicDigestion`, which means that it should be extracted out into a method that can be used by both storages.

2024-08-12 06:24 UTC, matthew7838 commented on RUFAS/routines/manure/constants_and_units/manure_constants.py
> +    The fraction of methane destruction efficiency rate.
I am not sure of the best description either. @KFosterReed do you have any suggestions?

2024-08-12 07:04 UTC, matthew7838 commented on RUFAS/routines/manure/manure_treatments/slurry_storage_outdoor.py
> +            daily_output.storage_methane = methane_loss
Not sure where would be the best place to extract this. Do you have any class in mind?

2024-08-12 13:09 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/slurry_storage_outdoor.py
> +            daily_output.storage_methane = methane_loss
My best educated guess is that it should be placed at the lowest interface/module/class that is shared by both Anaerobic Digestion and Slurry Storage Outdoor. So in this case I think the best bet would be `BaseManureTreatment`.

2024-08-14 14:33 UTC, KFosterReed commented on RUFAS/routines/manure/constants_and_units/manure_constants.py
> +    The fraction of methane destruction efficiency rate.
Ed's suggestion is great. I just removed 'daily' because although we are applying it daily, it is not exclusively a daily estimate

2024-08-14 15:09 UTC, KFosterReed commented
[C+F_test-AL_errors_14-Aug-2024_Wed_10-04-35.json](https://github.com/user-attachments/files/16615227/C%2BF_test-AL_errors_14-Aug-2024_Wed_10-04-35.json)

When I tried to test this, the simulation is failing because it is producing a key error from the nitrous oxide emissions methods that also require the manure cover inputs but don't have an option for the `'cover and flare'` input. Please let me know when this is corrected

2024-08-14 22:10 UTC, KFosterReed commented
Alright! This works as expected! The only thing missing is that there is no data added to the new output variable `storage_methane_burned` so it is always 0. If this can be updated so that it is actually reporting the destroyed methane then it is ready to go!

2024-08-14 22:37 UTC, KFosterReed commented
> Alright! This works as expected! The only thing missing is that there is no data added to the new output variable `storage_methane_burned` so it is always 0. If this can be updated so that it is actually reporting the destroyed methane then it is ready to go!

Update! I realized there was just a mismatch in the names for the variables addeded to the manure treatment outputs and the variables in the treatment files where the data was being assigned! I fixed it and now it works fully as expected! Nicely done Matthew

2024-08-14 22:45 UTC, KFosterReed commented
And here is an example of the summary outputs for slurry storage (SS) and anaerobic lagoons (AL) with and without cap and flare (C+F):

![image](https://github.com/user-attachments/assets/817c9546-54f2-470e-8c2a-ac774ecb92a2)

2024-08-14 22:46 UTC, KFosterReed approved these changes

2024-08-15 19:40 UTC, Isgotkowitz requested changes
There is a bug in anaerobic lagoon. Also, how is testing going to be handled? Will it be done in this PR or in a follow up?

2024-08-15 19:40 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/base_manure_treatment.py
> +        adjusted_methane_loss = methane_loss * (1 - ManureConstants.METHANE_DESTRUCTION_EFFICIENCY / 100)
```suggestion
        storage_methane_burned = methane_loss * ManureConstants.METHANE_DESTRUCTION_EFFICIENCY *  GeneralConstants.PERCENTAGE_TO_FRACTION
        adjusted_methane_loss = methane_loss * (1 - ManureConstants.METHANE_DESTRUCTION_EFFICIENCY *  GeneralConstants.PERCENTAGE_TO_FRACTION)
```

2024-08-15 19:40 UTC, Isgotkowitz commented on RUFAS/routines/manure/manure_treatments/anaerobic_lagoon.py
> +
Storage methane is overwritten on line 128, that line needs to be moved up above this function the same as in slurry storage outdoor.

2024-08-15 19:48 UTC, matthew7838 commented on RUFAS/routines/manure/manure_treatments/base_manure_treatment.py
> +        adjusted_methane_loss = methane_loss * (1 - ManureConstants.METHANE_DESTRUCTION_EFFICIENCY / 100)
Thanks, I did not update the old code and used the commit on GitHub, so I copied the old code.

2024-08-15 20:01 UTC, Isgotkowitz approved these changes
LGTM, nice job Matthew

2024-08-15 20:02 UTC, merged