Migrating manure functions
RuminantFarmSystems/RuFaS pull request #1910
Opened 2024-08-09 09:38 UTC by matthew7838

This PR will migrate as much manure function as possible from `manure.py` to `manure_pool.py`.
### Context

Issue(s) closed by this pull request: closes #1814 

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

- Methods that do not modify the SoilData will be moved to `manure_pool.py`.
- Testings have been rewritten to mock in a preferred way.
- Manure pool now does its own update, the caller in manure.py will call those update methods from each pool instead of updating in the main routine.

### Why

Better extendability for future manure extension.

### How

Extracting manure functions into a more general class.

### Test plan

- Run with a complete test suite.
- Compare the generated data and see no difference. Used this 
[filter](https://github.com/user-attachments/files/16670259/csv_manure.txt)

2024-08-22 22:30 UTC, ew3361zh commented on RUFAS/routines/field/soil/phosphorus_cycling/manure.py
> +        self.data.grazing_manure.runoff_reset()
Nice, this is much clearer and easier to track.

2024-08-23 14:20 UTC, allisterakun requested changes
It generally looks excellent; good job, Matthew!
However, I found that `manure_pool.py` is not fully covered, the test coverage for this file is at 97% with four statements missing. Could you please also cover these cases?

```
Name                                                                         Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------------------------------------
.\RUFAS\routines\field\manager\field_data_reporter.py                          209      0   100%
.\RUFAS\routines\field\soil\manure_pool.py                                     147      4    97%   73, 146, 207-208
.\RUFAS\routines\field\soil\phosphorus_cycling\manure.py                        26      0   100%
.\RUFAS\routines\field\soil\soil_data.py                                       205      3    99%   694-697
.\tests\soil_crop_tests\soil_tests\phosphorus_cycling_tests\test_manure.py      45      0   100%
.\tests\soil_crop_tests\soil_tests\test_manure_pool.py                         175      0   100%
.\tests\soil_crop_tests\soil_tests\test_soil_data.py                           148      3    98%   445, 450, 466
----------------------------------------------------------------------------------------------------------
TOTAL                                                                          955     10    99%

```

2024-08-23 14:20 UTC, allisterakun commented on RUFAS/routines/field/soil/manure_pool.py
> +        mineralized_stable_organic = self.determine_mineralized_surface_phosphorus(
Are these comments necessary?
```suggestion
        decomposed_mass, decomposed_coverage = self.determine_decomposed_surface_manure(temperature_factor)

        mineralized_stable_organic = self.determine_mineralized_surface_phosphorus(
```

2024-08-23 14:22 UTC, matthew7838 commented on RUFAS/routines/field/soil/manure_pool.py
> +        mineralized_stable_organic = self.determine_mineralized_surface_phosphorus(
They're originally there, I think they're somewhat helpful. Let me know what you think I'm also fine with removing them.

2024-08-23 14:24 UTC, ew3361zh reviewed
This looks good, Matthew, nice work. Results were matching for the filter I used (the provided filter didn't work for me for some reason).

And very nice work lowering the MyPy count significantly.

I have some updates/comments/questions. Once those are addressed, please retag me and I will approve.

```
{
  "multiple": [
    {
      "name": "Manure Pool Data",
      "filters": [
          ".*machine_manure.*",
          ".*grazing_manure.*"
      ],
      "vertical_aggregation": "sum"
  }
  ]
}
```

2024-08-23 14:24 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                info_map,
What happened here?

2024-08-23 14:24 UTC, ew3361zh commented on RUFAS/routines/field/soil/manure_pool.py
> +)
I think we're going to migrate away from using these because we have a more generic constants file where we are centralizing all this - could you please use the RUFAS/GeneralConstants instead?

If there are any missing there that are here, can you add them there?

2024-08-23 14:24 UTC, ew3361zh commented on RUFAS/routines/field/soil/manure_pool.py
> +        Tuple[float, float]
```suggestion
        tuple[float, float]
```

2024-08-23 14:24 UTC, ew3361zh commented on RUFAS/routines/field/soil/manure_pool.py
> +    ) -> Dict[str, float]:
```suggestion
    ) -> dict[str, float]:
```

2024-08-23 14:24 UTC, ew3361zh commented on RUFAS/routines/field/soil/manure_pool.py
> +        Dict (keys listed below)
```suggestion
        dict (keys listed below)
```

2024-08-23 14:27 UTC, matthew7838 commented on RUFAS/input_manager.py
> +                info_map,
For some reason,, I stumbled across this line and think adding info maps to OM warning makes sense.

2024-08-23 14:28 UTC, matthew7838 commented on RUFAS/routines/field/soil/manure_pool.py
> +)
Sure thing. Thanks for addressing this.

2024-08-23 19:40 UTC, matthew7838 commented on RUFAS/routines/field/soil/manure_pool.py
> +        mineralized_stable_organic = self.determine_mineralized_surface_phosphorus(
Looking at it again i will remove those.

2024-08-25 14:14 UTC, ew3361zh commented on RUFAS/routines/field/soil/phosphorus_cycling/manure.py
>          if self.data.machine_manure.manure_dry_mass > 0 and self.data.machine_manure.manure_field_coverage > 0:
Similar to our discussion on my PR migrating Crop related actions and data access out of Field, what do you think about wrapping this first line in a function in ManurePool so that Manure doesn't have to have be the one determining whether ManurePool.leach_phosphorus_pools() gets called?

All it would do would be to `return self.data.machine_manure.manure_dry_mass > 0 and self.data.machine_manure.manure_field_coverage > 0`

2024-08-25 14:15 UTC, ew3361zh commented on RUFAS/routines/field/soil/phosphorus_cycling/manure.py
>          if self.data.grazing_manure.manure_dry_mass > 0 and self.data.grazing_manure.manure_field_coverage > 0:
Same comment as above.

2024-08-25 14:31 UTC, ew3361zh commented on RUFAS/routines/field/soil/phosphorus_cycling/manure.py
>          if self.data.machine_manure.manure_dry_mass > 0 and self.data.machine_manure.manure_field_coverage > 0:
My fault, I meant `return self.manure_dry_mass > 0 and self.manure_field_coverage > 0`

2024-08-25 14:32 UTC, matthew7838 commented on RUFAS/routines/field/soil/phosphorus_cycling/manure.py
>          if self.data.machine_manure.manure_dry_mass > 0 and self.data.machine_manure.manure_field_coverage > 0:
Gotcha, on it.

2024-08-25 21:20 UTC, ew3361zh approved these changes
Nice job, Matthew.

2024-08-26 15:47 UTC, allisterakun approved these changes
Great work!

2024-08-26 16:23 UTC, merged