Handle NaNs sent to RG Aggregator functions
RuminantFarmSystems/RuFaS pull request #1932
Opened 2024-08-15 16:47 UTC by ew3361zh

Stemming out of the original issue #1856, this PR seeks to properly handle NaNs when sent to the RG aggregator functions.

### Context

Issue(s) closed by this pull request: closes #1896

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

Accounts for and handles NaNs in the aggregator functions of ReportGenerator.

### Why

Previously if there were NaNs in the data sent to RG, the simulation crashed (which we don't want to happen).

### How

Using the Numpy nan library, the aggregator functions all take NaNs into account and avoid crashing the code when they're encountered.

### Test plan

Testing is updated. I will try to provide some test cases.

2024-08-19 18:08 UTC, allisterakun requested changes
During Group review:
1. Found duplicate protections against None and Nan. We are filtering out the None and Nan values before most of the aggregation operations. We are also adding the ability to handle None and Nan data in the actual aggregator functions.
2. Some decisions to consult about the division and subtraction operations: see comments below.

Consider:
1. Remove all the None and Nan filtering before the aggregation operations and just let the aggregator functions to handle these scenrios.
This would implement option A in issue #1896: 

> A. We can use libraries like SciPy or NumPy to perform data cleaning before performing the actual aggregation.
2. User option C in issue #1896, which is the preferred option:

> C. [preferred] Raise an exception when something goes wrong in the aggregation and let the caller catch and handle it by populating the result with 0 or None or NaN etc... . This approach is preferred as it avoid code duplication.

Also, come up with a plan for when to use 0 or None or NaN when these issues come up.

2024-08-19 18:08 UTC, allisterakun commented on RUFAS/report_generator.py
>          return None
During group review:
Since we're skipping all the other None values in the list, please consult Pooya or Kristan about skipping the leading Nans until a non-Nan is found.

2024-08-19 18:08 UTC, allisterakun commented on RUFAS/report_generator.py
> +        valid element (non-NaN).
Update the return to reflect the case of returning None (if the first element is None)

2024-08-19 18:08 UTC, allisterakun commented on RUFAS/report_generator.py
> +    if len(data) < 2 or np.isnan(data[0]):
Same comment as above for the division.

2024-08-21 18:47 UTC, ew3361zh commented
@matthew7838 @allisterakun updates summary:

- Removed NaN and None handling from aggregator functions and apply_vertical/apply_horizontal functions
- Added a wrapper function to check incoming data being sent to aggregators to be scanned for Nones and NaNs
- Report error to OM if there is a None or NaN in a data set and return None for the data
- Updated unit testing
- For testing, I added a line into the new `_handle_aggregator_errors()` method which would add a NaN or None into the data and saw the appropriate return (see pic for example)

<img width="832" alt="Screenshot 2024-08-21 at 11 53 43 AM" src="https://github.com/user-attachments/assets/19df0811-38cf-45f5-a9e6-c932aa88147c">

Continuing to work on reducing mypy error count but the new approach can be reviewed in the meantime.

2024-08-21 19:10 UTC, ew3361zh commented on RUFAS/report_generator.py
> +    def _aggregate_units(
This function is unchanged, I just moved it to be closer to similar functionality in the class.

2024-08-26 14:26 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +            The vertically aggregated data as a dictionary of lists.
This return type does not match the type hints.

2024-08-26 14:26 UTC, Isgotkowitz commented on RUFAS/report_generator.py
>              non_null_data_points = list(filter(lambda x: x is not None, temp_data))
Should this line be removed? It seems that handle_aggregration_errors will handle the data if there is a None passed

2024-08-26 14:26 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +            non_null_data_points = list(filter(lambda x: x is not None, data))
I think there should be no filtering of Nones from the data, because `_handle_aggregation_errors` has the functionality to deal with Nones in the data, and it seems problematic to me to have to different places handling the same error condition in two different ways.

2024-08-26 14:26 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +        if any(x is None or math.isnan(x) for x in data):
Might also be good to check for Numpy nan type too? Edit: seems that math.isnan catches numpy nans, so nevermind

2024-08-26 14:26 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +        if any(x is None or math.isnan(x) for x in data):
Alternatively, it could be checked that all data is numerical, to make sure no strings, bools, etc. are making it into the aggregation function

2024-08-26 14:26 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +            }
When I try aggregating some data that contains a lot of Nones or nans, this error seems to print for once for each of the None or Nan values that I am trying to aggregate? Is this intended, or would it be possible to only have it print once for a single data set that has aggregation attempted on it?

2024-08-26 14:50 UTC, ew3361zh commented on RUFAS/report_generator.py
>              non_null_data_points = list(filter(lambda x: x is not None, temp_data))
Yes! Thank you. I think I've been hitting the git stash and not enough of the git apply.

2024-08-26 14:50 UTC, ew3361zh commented on RUFAS/report_generator.py
> +            non_null_data_points = list(filter(lambda x: x is not None, data))
Agreed

2024-08-26 14:51 UTC, ew3361zh commented on RUFAS/report_generator.py
> +            }
Interesting. I will address that.

2024-08-26 14:57 UTC, ew3361zh commented on RUFAS/report_generator.py
> +        if any(x is None or math.isnan(x) for x in data):
Good call on the bools, strings. NaNs count as floats oddly enough so I'll still need to specifically check for those.

2024-08-26 15:14 UTC, ew3361zh commented on RUFAS/report_generator.py
> +            }
Could you share what your testing process was here so I can try to replicate? I am still getting one error per set of data that contains any number of Nones/NaNs/strings/bools

2024-08-26 15:26 UTC, ew3361zh commented on RUFAS/report_generator.py
> +    return (sum((x - mean) ** 2 for x in data) / len(data)) ** 0.5 if data else 0.0
addresses mypy warning.

2024-08-26 18:24 UTC, allisterakun approved these changes
It generally looks good; great job, Niko!
Just two minor comments.
Also, since you're introducing a new function in the PR, it'd be nice to mention it in the PR description.

2024-08-26 18:24 UTC, allisterakun commented on RUFAS/report_generator.py
> +        event_log = {}
Is there a reason we're removing the type hint for `event_logs`?

2024-08-26 18:24 UTC, allisterakun commented on RUFAS/report_generator.py
> +    def _handle_aggregation_errors(
Maybe a better name for this function. Because it handles the aggregation errors and performs the aggregation.

2024-08-26 18:41 UTC, ew3361zh commented on RUFAS/report_generator.py
> +        event_log = {}
I think what happened here is that this changed from a list of event logs to a single event log. I can add the type hints for this new version.

2024-08-26 18:41 UTC, ew3361zh commented on RUFAS/report_generator.py
> +    def _handle_aggregation_errors(
how about just `_handle_aggregation()`?

2024-08-26 19:58 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +            }
I added the following to Simulation Engine, then wrote a report filter to try and aggregate `none_var` (and same thing with Nan, could also be used to test bool, str, etc):
```python
    def simulate(self) -> None:
        """
        Executes the simulation.
        """

        # -- snip -- 
        EEEManager.estimate_all()
        info_map.update({"units": MeasurementUnits.UNITLESS})
        for i in range(100):
            self.om.add_variable("none_var", None, info_map)
        # -- snip --
```

2024-08-26 20:10 UTC, ew3361zh commented on RUFAS/report_generator.py
> +            }
Hmm, I added this then used this report filter: 

```
{
      "name": "Ed Data",
      "filters": [
          ".*none_var.*"
      ],
      "vertical_aggregation": "sum"
  }
```

and only got one error:
<img width="1326" alt="Screenshot 2024-08-26 at 4 10 10 PM" src="https://github.com/user-attachments/assets/b1a05eb6-f7c3-4c57-9a3b-3d3039f3a386">


Are you still seeing the multiple errors?

2024-08-26 20:32 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +            }
Ooh I bet it was because I was using horizontal aggregation, that would make way more sense

2024-08-26 21:03 UTC, Isgotkowitz approved these changes
LGTM, thank you for addressing comments. Had one random question about a piece of the code. Tried this out with some filters and found no difference between dev and this branch

2024-08-26 21:03 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +                aggregator, temp_data, next(iter(report_data))
Is `next(iter(...))` used here because there should only ever be one key in "report_data"?

2024-08-26 21:45 UTC, ew3361zh commented on RUFAS/report_generator.py
> +                aggregator, temp_data, next(iter(report_data))
It's an interesting question, I should have brought it up - I added the key to this function definition to be able to track where the potentially bad data (with nones, strings, nans, etc) were coming from. So it's only for error logging.

In the case of horizontal aggregation I was honestly not quite sure how to handle this because it's the only case of all the uses of this function where we're getting multiple keys there (sending each row's data to be aggregated). 

But trying to then track which key's data belongs to which key and then tracking that back to Output Manager to log became way too complicated. Especially since the other callers of this function have one key.

I could send the list of the keys for the data and add it as a string to the error message. We don't have access to the report filter at this point to know the title of the report which could be another reference point for users to go back and track down the bad data (but then they'd have to know their filter well enough to know all the vars it's capturing if they're using Regex).

2024-08-26 21:57 UTC, ew3361zh commented on RUFAS/report_generator.py
> +                aggregator, temp_data, next(iter(report_data))
I will hold off on merging this until we've come to an agreed solution. But will add the list of all the keys of the horizontally aggregated data as a string for error logging.

So for example for this filter:
```
{
            "name": "Heifers",
            "filters": ["AnimalModuleReporter.report_daily_animal_population.num_(heiferIs|heiferIIs|heiferIIIs)"],
            "vertical_aggregation": "average",
            "horizontal_aggregation":"sum",
            "horizontal_first": true,
            "slice_start": -365
           }
```

if I add some bad data to the data to be aggregated, it would print out this error:
`[26-Aug-2024_Mon_17-54-45.921209][ERROR][default] ReportGenerator aggregation error. Encountered unaggregatable values in ['AnimalModuleReporter.report_daily_animal_population.num_heiferIs', 'AnimalModuleReporter.report_daily_animal_population.num_heiferIIs', 'AnimalModuleReporter.report_daily_animal_population.num_heiferIIIs'] data, returning None instead.`

2024-08-27 16:37 UTC, Isgotkowitz commented on RUFAS/report_generator.py
> +                aggregator, temp_data, next(iter(report_data))
Sounds good to me - my only suggestion would be to make the log message prettier/more readable, if this is doable without too much additional effort. Something like
`[26-Aug-2024_Mon_17-54-45.921209][ERROR][default] ReportGenerator aggregation error. Encountered unaggregatable values in variable(s): 'AnimalModuleReporter.report_daily_animal_population.num_heiferIs', 'AnimalModuleReporter.report_daily_animal_population.num_heiferIIs', 'AnimalModuleReporter.report_daily_animal_population.num_heiferIIIs', returning None instead.`

2024-08-27 18:22 UTC, merged