Manure management PR
RuminantFarmSystems/RuFaS pull request #194
Opened 2022-09-20 20:31 UTC by ltp23

This PR added the following files. 

`constants.py`: a list of constants to be used in the manure module.
`default_enum.py`: an extended version of the built-in Enum class that supports member lookup and returns default member in the case of an unsuccessful lookup.
`manure.py`: specifies what data expected from the animal module. 
`bedding_classes.py`: implements different bedding classes used in the manure handlers. 
`milking_center.py`: calculates the time spent in the milking center and amount of manure produced by cows there.

2022-09-30 21:16 UTC, varrma approved these changes

2022-10-05 02:13 UTC, PooyaHekmati requested changes
Looks good overall, just added a few comments

2022-10-05 02:13 UTC, PooyaHekmati commented on RUFAS/routines/manure/default_enum/default_enum.py
> +    def get_type(cls, member_name: str) -> DefaultEnum:
Based on the function signature, I expect this function to return the type of a given member, but docstring says it returns the member itself. Which one is correct?

2022-10-05 02:13 UTC, PooyaHekmati commented on RUFAS/routines/manure/default_enum/default_enum.py
> +            if member.name.upper() == member_name.strip().upper():
avoid using names that differ only in one character. It is so easy to misread/misuse member.name and member_name.

2022-10-05 02:13 UTC, PooyaHekmati commented on RUFAS/routines/manure/default_enum/default_enum.py
> +        return list(cls)[0]
what if the list is empty?

2022-10-05 02:13 UTC, PooyaHekmati commented on RUFAS/routines/manure/manure_handlers/bedding_classes.py
> +        pass
why pass?

2022-10-05 02:13 UTC, PooyaHekmati commented on RUFAS/routines/manure/manure_handlers/bedding_classes.py
> +    pass
if these passes are planned work, please mention them.

2022-10-05 06:50 UTC, ltp23 commented on RUFAS/routines/manure/default_enum/default_enum.py
> +        return list(cls)[0]
I added a try/except clause with IndexError to catch this case.

2022-10-05 06:51 UTC, ltp23 commented on RUFAS/routines/manure/default_enum/default_enum.py
> +            if member.name.upper() == member_name.strip().upper():
I changed the name of the parameter accordingly.

2022-10-05 06:57 UTC, ltp23 commented on RUFAS/routines/manure/manure_handlers/bedding_classes.py
> +    pass
Those passes just mean that they inherit the init() from the parent without adding extra attributes of their own. I added some quick notes in the docstrings.

2022-10-05 07:24 UTC, ltp23 commented on RUFAS/routines/manure/default_enum/default_enum.py
> +    def get_type(cls, member_name: str) -> DefaultEnum:
That return type is meant to be generic. At runtime, the actual return type will be whatever the specific enum type that is being called upon. Members of an enum have the same type as the enum itself.  For example, if I have a DaysOfWeek enum that is extended from DefaultEnum, when I call DaysOfWeek.get_type('monday'), I will get the member DaysOfWeek.MONDAY, which has the type of DaysOfWeek. 

Though there are some subtle differences regarding the exact typing,
`type(DaysOfWeek.MONDAY) == DaysOfWeek  # True`
`type(DaysOfWeek.MONDAY) == DefaultEnum # False, need to be an exact match.`
`isinstance(DaysOfWeek.MONDAY, DaysOfWeek) # True`
`isinstance(DaysOfWeek.MONDAY, DefaultEnum) # True, inheritance works fine here.`

2022-10-05 18:59 UTC, KFosterReed commented on RUFAS/routines/manure/constants/constants.py
> +    INCHES_TO_METERS = 0.0254
We should not have a need for this conversion because we should not be using inches anywhere.

2022-10-05 19:14 UTC, varrma commented on RUFAS/routines/manure/constants/constants.py
> +    INCHES_TO_METERS = 0.0254
Yes makes sense. We have the unit "inches" related to the Lagoon system design, where we have to set Freeboard and Run off space. Will check with Loi to see the best place fit.

2022-10-05 19:18 UTC, KFosterReed commented on RUFAS/routines/manure/constants/constants.py
> +    INCHES_TO_METERS = 0.0254
That is good to know but the input to the model should still be in metric. Please change the inputs from inches to cm before they enter the RuFaS simulation

2022-10-05 19:33 UTC, KFosterReed commented on RUFAS/routines/manure/constants/constants.py
> +    INCHES_TO_METERS = 0.0254
As a follow up for more context, we will want to accept inputs in English units in the future but in that case we would want all units to be provided in English units and do the conversions at one time before the simulation is initialized. This will only work if all of the internal units (i.e. all of the units within the RuFaS routines) are the same, which means we need everything to be in metric units

2022-10-05 20:18 UTC, KFosterReed commented on RUFAS/routines/manure/manure_handlers/bedding_classes.py
> +        bedding_dry_matter: Dry matter content of the bedding, kg.
Are these the right units for this? If so, can we change the definition to be something like 'Dry matter mass of the bedding'? Dry matter content is often understood to be the composition and expressed in %

2022-10-05 20:34 UTC, KFosterReed commented on RUFAS/routines/manure/manure_handlers/milking_center.py
> +    def _has_cow_in_pen(pen: ManureManagementPen) -> bool:
I think we should modify this function to be _has_lac_cow_in_pen and use the AnimalCombination attribute instead of the classes_in_pen. Making this change will ensure that you are checking if there are lactating cows in the pen. 

Once an animal 'graduates' or grows up to be a cow class, she goes through cycles when she is lactating and non-lactating (aka dry). Basing this function on the cow class will find pens with both lactating cows and dry cows. Since dry cows aren't producing milked, they don't go to the milking parlor and wouldn't contribute to the manure here.

2022-10-05 20:36 UTC, KFosterReed commented on RUFAS/routines/manure/pen/manure_management_pen.py
> +        """Calculates the manure volume of this pen.
Should this be 'calculates the manure mass of this pen'?

2022-10-05 20:45 UTC, KFosterReed requested changes
Overall this looks great! There are a few small changes that I requested and a couple of things that I would like clarification on. The most important changes will be: 
1) making sure you are only counting manure from lactating cows
2) making sure all variables and calculations are done in metric

2022-10-06 19:12 UTC, ltp23 commented on RUFAS/routines/manure/constants/constants.py
> +    INCHES_TO_METERS = 0.0254
Thanks Kristan for your input. Non-metric conversion constants have been safely removed. In fact, we didn't use any such conversions anywhere. The only place we originally thought would need unit conversion was in weather data. So, the more maintainable way of using weather data is to make sure it is using the unit system to begin with.

2022-10-06 19:52 UTC, ltp23 commented on RUFAS/routines/manure/manure_handlers/milking_center.py
> +    def _has_cow_in_pen(pen: ManureManagementPen) -> bool:
Very good explanation. I will adjust accordingly.

2022-10-06 20:55 UTC, ltp23 commented on RUFAS/routines/manure/pen/manure_management_pen.py
> +        """Calculates the manure volume of this pen.
Yes, it is fixed now.

2022-10-12 17:34 UTC, KFosterReed commented on RUFAS/routines/manure/manure_handlers/bedding_classes.py
> +        bedding_dry_matter: Dry matter content of the bedding, kg.
I see you addressed this in the latest commit! Thanks! :)

2022-10-12 17:35 UTC, KFosterReed approved these changes
Thanks team for thoroughly addressing all my questions! It looks good to me!

2022-10-16 16:25 UTC, PooyaHekmati approved these changes

2022-10-17 05:16 UTC, merged

2022-10-17 13:05 UTC, KFosterReed commented
Great work team! On to the next one!!