Deprecated update classes in pen function
RuminantFarmSystems/RuFaS pull request #1958
Opened 2024-08-27 04:00 UTC by 0luchi

### Context

Issue(s) closed by this pull request: closes #1208 

- [x] The [changelog](https://docs.google.com/spreadsheets/d/1U-3igxdstHTFb6k5dVcE5-x9IL0r6q18eUiwwytKZyA/edit#gid=0) has been updated.
      
How big are the changes in the PR? Would you nominate it for a major version upgrade?
- [ ] Yes
- [x] No

### What

- This PR deprecates `update_classes_in_pen` and all tests it covers since animal_combination covers this scenario and makes the function irrelevant.
- The PR also deprecates `classes_in_pen` and replaces it with `animal_combination`

### Why

This is important because `animal_combination` does the function of `classes_in_pen` and if a pen has an animal combination, then that already represents the classes in the pen.

### How

- I removed the `update_classes_in_pen` function and removed every instance of where it was called. 
- I also replaced all instances of `classes_in_pen` with `animal_combination` and updated all the test cases.

### Test plan

No tests were added but test cases were updated to reflect changes

2024-08-28 14:17 UTC, Isgotkowitz reviewed
This is a good start to deprecating the update animals classes in pen, however it seems like there is more work to do. If `update_classes_in_pen` is removed, is the attribute `classes_in_pen` ever updated? Since `classes_in_pen` is still being used, I assume it has to be.

2024-08-28 14:17 UTC, Isgotkowitz commented on RUFAS/routines/animal/pen.py
> +        ):
With if statements like this, it makes it often makes the code cleaner if the condition is extracted into its own line and named explicitly:
```suggestion
cows_are_in_pen = self.animal_combination in {AnimalCombination.LAC_COW, AnimalCombination.CLOSE_UP}
if cows_are_in_pen:
```

2024-08-28 14:17 UTC, Isgotkowitz commented on RUFAS/routines/animal/pen.py
> +        ):
Also, this change does not appear to be explicitly related to deprecating `update_classes_in_pen`, why is this needed?

2024-09-03 19:37 UTC, 0luchi commented
@Isgotkowitz  Thanks for looking at my PR. Concerning your comment, https://github.com/RuminantFarmSystems/MASM/pull/1958#pullrequestreview-2266383661 the issue related to it required `update_classes_in_pen` to be deprecated because `animal_combination`  has been implemented. So, I don’t think it needs to be updated anymore. Maybe @JoeWaddell would know more since he created the issue?

2024-09-03 20:03 UTC, JoeWaddell commented
> @Isgotkowitz Thanks for looking at my PR. Concerning your comment, [#1958 (review)](https://github.com/RuminantFarmSystems/MASM/pull/1958#pullrequestreview-2266383661) the issue related to it required `update_classes_in_pen` to be deprecated because `animal_combination` has been implemented. So, I don’t think it needs to be updated anymore. Maybe @JoeWaddell would know more since he created the issue?

Thanks for the tag! This issue I created from an old comment in the code from someone else - I think during one of the earlier animal manager refactors in 2022/23?

So agreed with Ed: it's a good start, and this PR will require replacing all instances of the `classes_in_pen` attribute with the appropriate pen attribute (`animal_combination`), and use of `AnimalType` checks instead of direct checks to strings (e.g. `AnimalType.LAC_COW` or `AnimalType.DRY_COW` instead of `Cow`)

2024-09-16 13:46 UTC, Isgotkowitz reviewed
Found a few minor things that I commented on, but overall this looks great! I don't expect there would be any changes to outputs from this PR, and while I did not thoroughly check this I did check that the list of variable names produced is the same as on `dev` and it was, which makes me reasonably confident that nothing changed in the outputs.

Before approving I just want to confirm with @allisterakun that it is ok to make changes to the `animal` directory that is in the `routines` directory, instead of `biophysical`. Once that happens I will come back and approve.

2024-09-16 13:46 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/pen_history.py
> +    A class  to represent the history of a pen on a farm.
```suggestion
    A class to represent the history of a pen on a farm.
```

2024-09-16 13:46 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_base.py
> +from ....enums import AnimalCombination
```suggestion
from RUFAS.enums import AnimalCombination
```
Relative pathing should be avoided if not at the same level or one higher, i.e. `from .enums ... ` or `from ..enums ...` would be fine but `from ...enums ...` should be turned into a full path instead. I am still not 100% sure about the best practices related to relative pathing or the logic underlying these guidelines, but this is what I have been told.

2024-09-16 13:46 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/pen_history.py
> +from ....enums import AnimalCombination
Same comment on relative pathing here

2024-09-16 13:46 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/pen_history.py
> +    animal_combination : list[str]
```suggestion
    animal_combination : AnimalCombination
```

2024-09-25 20:37 UTC, Isgotkowitz reviewed
Code looks good to me! Once all the Flake8 errors are worked out and the new changelog (`changelog.md` in the codebase) is updated I will come back and approve.

2024-09-27 19:58 UTC, JoeWaddell requested changes
Looks good! Just commented on a few things to tidy up

2024-09-27 19:58 UTC, JoeWaddell commented on RUFAS/routines/animal/pen.py
> +        if cows_are_in_pen:
Here you might want to simply make the check directly, instead of creating a local variable, since it'll conform better to logic elsewhere in the codebase.

Also out of curiosity, is there a reason to use a set instead of a list?

2024-09-27 19:58 UTC, JoeWaddell commented on RUFAS/routines/manure/pen_manure/manure_manager_pen.py
> +        if AnimalCombination.LAC_COW == self.animal_combination:
Reversing the logic here might read better, but it's the same functionality. Just thinking ahead in case there's more branching logic in the future, since checking `self.animal_combination` against lists might come up.


```suggestion
        if self.animal_combination == AnimalCombination.LAC_COW:
```

2024-09-27 19:58 UTC, JoeWaddell commented on tests/animal_module_tests/test_animal.py
> +from RUFAS.enums import AnimalCombination
duplicate import, see line 11

2024-09-27 19:58 UTC, JoeWaddell commented on RUFAS/routines/manure/pen_manure/manure_manager_pen.py
> +from RUFAS.routines.animal.animal_types import AnimalType
unused import

2024-10-02 19:48 UTC, 0luchi commented on RUFAS/routines/animal/pen.py
> +        if cows_are_in_pen:
No reason in particular

2025-06-11 13:11 UTC, KFosterReed commented
@JoeWaddell and/or @allisterakun  can you confirm that this branch/PR are OK to delete?

2025-06-17 22:29 UTC, closed without merging