Implement Animal digest
RuminantFarmSystems/RuFaS pull request #2004
Opened 2024-09-17 11:03 UTC by matthew7838

This PR implements AnimalDigest submodule logic according to the design doc and creates unit tests for the module.
### Context

Issue(s) closed by this pull request: closes #1927 

### What

This PR refactors the animal digestion code in the animal module. The original code has a digestion-related calculation logic for dry/ lactating cows, heifers,s, and calves. Now they're extracted into three classes, `EntericMethaneCalculator`, `ManureExcretionCalculator`, and `MethaneMitigationCalculator`. Finally, they will be called in the `DigestiveSystem` class for daily updates depending on the animal types passed in from the properties.

### Why

To resolve the entanglement issue in Animal module.

### How

Separate methods in to different classes.

### Test plan

Write necessary unit tests to bring the coverage for the animal growth submodule to 100%.

Unit tests cover all methods, and all mock test cases run error-free. At this point, we are not able to run it in a simulation, because the animal module in the new `biophyscial` module is yet to be set up.

2024-09-30 16:36 UTC, Isgotkowitz requested changes
Left comments on a bunch of different things, but this PR is headed in the right direction. The most important things I noticed were 1) attributes being duplicated across different properties, and 2) the main routine for digestive system should be modifying and returning one or more of the properties dataclasses. Also, this PR is pretty massive. Maybe it would be better to implement something like the manure excretion changes in a PR stacked on top of this one?

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/animal_properties/general_properties.py
>      id: int
Could the attributes `breed` and `gender` please be updated to reflect that there are now enums for these fields, and that gender should be sex?

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/animal_properties/milk_production_properties.py
> +    daily_milk_production: float
This attribute is already in `GeneralProperties`, and it should only be in one place.

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/animal_properties/nutrient_properties.py
> +    urine_phosphorus_required: float
Could you please start a docstring for this class? It doesn't have to document all the attributes, just the ones you added would be enough to get it started.

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/animal_properties/nutrient_properties.py
I see a number of attributes in this class that are already in `GeneralProperties`. They should be removed from this class.

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +        methane_model: str
```suggestion
        methane_model: str | None
```
I think it would be good to note in this docstring (probably for this parameter) that if the methane_model is none then the methane emissions are set as zero

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +                * (1 + methane_yield_reduction / GeneralConstants.FRACTION_TO_PERCENTAGE)
```suggestion
                * (1 + methane_yield_reduction * GeneralConstants.PERCENTAGE_TO_FRACTION)
```
All of the constants in `GeneralConstants` are/should be multiplicative

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/methane_mitigation_calculator.py
> +            "EssentialOils", and "Seaweed".
If the methane mitigation method is Essential Oils or Seaweed, then the methane is never going to be mitigated at all. Should there be a warning logged if a user tries to use one of these methods to let them know that they are not gonna be effective at all? Or maybe we just remove these options entirely?

@KFosterReed - if I remember your practice presentation correctly, you said that there wasn't enough information in the literature to model the mitigation from Essential Oils and Seaweed? If this is the case then I think it would be better to remove these options entirely

2024-09-30 16:36 UTC, Isgotkowitz commented on changelog.md
> +- [2004](https://github.com/RuminantFarmSystems/MASM/pull/2004) - [minor change] [Animal] Implement the animal digestive system in the biophysical folder.
There should be no removals of changelog entries. Also, the entry for this PR needs to go in the "Next Version Updates" section.

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +import numpy
Instead of importing the whole module, what about just importing `exp` because that is the only function that is needed for this method?

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +                (GeneralConstants.FRACTION_TO_PERCENTAGE - ASH_concentration)
The use of this constant does not make sense in this line

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +            # Default: IPCC Tier 2
What is the default here? What are the alternatives? How are they set?

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/animal_properties/general_properties.py
> +    metabolizable_energy_intake: float
For the attributes that you are adding/modifying, could you please add them to the docstring?

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/digestive_system.py
> +    ) -> tuple[float, float, AnimalManureExcretions]:
I don't think this method conforms to the pattern laid out for the animal refactor. Instead of returning floats for the enteric methane and excreted phosphorus, it should store them in the appropriate properties structure and return the modified properties

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +    def calf_methane(methane_model: str | None, body_weight: float) -> float:
```suggestion
    def calculate_calf_methane(methane_model: str | None, body_weight: float) -> float:
```
These method names should start with verbs

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +            ASH_concentration = nutrient_concentrations["ash"]
I think these variable names should be changed, so that they are not abbreviated (CP -> crude_protein) and use snake case (ASH -> ash)

2024-09-30 16:36 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +        if methane_model == "Mutian":  # [A.3E.C.1]
I think these in-line references should be removed and references should go in the docstring

2024-10-01 09:51 UTC, matthew7838 commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +            # Default: IPCC Tier 2
Looking at the code, I don't think there's any alternatives for now. So it will always be the IPCC Tier 2 method, which is the calculations below, I will remove these inline comments to prevent confusion and also move the references as mentioned in the comments below.

2024-10-01 12:55 UTC, matthew7838 commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +            ASH_concentration = nutrient_concentrations["ash"]
Is there a reference available for me to understand these abbreviations?

2024-10-01 13:11 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +            ASH_concentration = nutrient_concentrations["ash"]
Might be somewhere in the animal scientific documentation (https://3.basecamp.com/3486446/buckets/5296287/vaults/7108677681)? If you can't find it there, the asking the SMEs would be a good way to go

2024-10-04 14:22 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/animal_properties/general_properties.py
> -    daily_milk_produced: float
`daily_milk_produced` is used in `AnimalPhosphorus`, so removing it from `GeneralProperties` will cause those routines to fail.

2024-10-18 20:22 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/animal_properties/general_properties.py
> +    """Enum indicating the gender of the animal."""
```suggestion
    """Enum indicating the sex of the animal."""
```

2024-10-18 20:22 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/animal_properties/general_properties.py
> -    is_milking
These attributes should not be deleted

2024-10-18 20:22 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +            Milk fat (from animal input), % of milk.
```suggestion
            Milk fat, % of milk.
```
Right now this value comes from the animal input, but this may not always be the case. And because the source of this value doesn't change how this method works, I don't think it is necessary to include it.

2024-10-21 14:02 UTC, Isgotkowitz reviewed
I think this is looking really good and getting much closer to being finished Matthew! A few things I noticed:
- There is still an unresolved comment from my first review about removing some methane mitigation methods because there is no support for them in RuFaS. I tagged Kristan in the comment, but I think you will have to follow up with her to get an answer
- `AnimalManureExcretions` is modified, which is good, but not all uses of it have been modified which is problematic. There is a more detailed comment about this below
- In a lot of the tests, the logic being tested is duplicated. This is not a good testing practice

2024-10-21 14:02 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +            }
```suggestion
        Notes
        -----
        The dry matter ("dm") unit is kg per animal. Crude protein ("CP"), ADF, NDF, lignin, ash, phosphorus, potassium, and nitrogen ("N") are all percentages of dry matter.

```
I think it is not a good practice to put python in the docstring, unless it is in the Examples section

2024-10-21 14:02 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/animal_properties/general_properties.py
> -    is_milking
Why is this taken out?

2024-10-21 14:02 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/digestive_system.py
> +    METHANE_MITIGATION_ADDITIVE_AMOUNT: float
Could docstrings please be added for these class vars?

Also, for stuff like the model and mitigation method would it be possible to convert them to enums? This doesn't have to happen in this PR, but it would be a nice change to make after the animal refactor if it is possible.

2024-10-21 14:02 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +        urine = 9.0
It would be good to declare urine as a module constant.

2024-10-21 14:02 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/methane_mitigation_calculator.py
> +            "EssentialOils", and "Seaweed".
@matthew7838 please follow up with Kristan and see if this is the case

2024-10-21 14:02 UTC, Isgotkowitz commented on tests/animal_module_tests/digestive_system/test_digestive_system.py
> +    observed_statistics, observed_excretions = DigestiveSystem.process_digestion(
Instead of using the term "observed", it is conventional to use the term "actual"

2024-10-21 14:02 UTC, Isgotkowitz commented on tests/animal_module_tests/digestive_system/test_enteric_methane_calculator.py
> +    expected = (0.065 * expected_gross_energy_concentration * dry_matter_intake) / 0.05565
Duplicating logic being tested inside the body of the test is not a good practice. It is better to have the expected result be a parameter of the test case

2024-10-21 14:02 UTC, Isgotkowitz commented on RUFAS/data_structures/animal_manure_excretions.py
> -    enteric_methane_g: float
Instead of changing this Animal Manure excretions, I suggest making a duplicate of this module, using the duplicate in `biophysical/` and modifying that duplicate. This is because this data type is shared between the Animal and Manure modules, and if it is changed here that change should be propagated to all other parts of the codebase that use it, which I don't think we are ready for.

2024-10-21 15:29 UTC, matthew7838 commented on RUFAS/biophysical/animal/animal_properties/general_properties.py
> -    is_milking
Should properties be listed with attributes in docstrings? My IDE is giving me warnings.

2024-10-21 15:30 UTC, matthew7838 commented on RUFAS/biophysical/animal/digestive_system/digestive_system.py
> +    METHANE_MITIGATION_ADDITIVE_AMOUNT: float
I agree, I will add the docstrings for the sake of easy transformation into enums in the future.

2024-10-21 16:33 UTC, KFosterReed commented on RUFAS/biophysical/animal/digestive_system/methane_mitigation_calculator.py
> +            "EssentialOils", and "Seaweed".
Hi Ed and Matthew! Sorry I missed this earlier and thanks for pinging me again! Yes, you're correct that we are going to wait to add essential oils and seaweed as actual options in our methane mitigation set. I think there is a possibility that we will get essential oils figured out in the next ~ 6 months but am I correct that it is 'easy enough' to add back when the time comes?

2024-10-21 19:49 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/animal_properties/general_properties.py
> -    is_milking
Yes, they should, but they should not have any description in the class docstring: https://numpydoc.readthedocs.io/en/latest/format.html#class-docstring

2024-10-21 19:54 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/methane_mitigation_calculator.py
> +            "EssentialOils", and "Seaweed".
> but am I correct that it is 'easy enough' to add back when the time comes?

Yes, I think so. If essential oils are that close, it may be better to leave that option in and just take out seaweed

2024-10-23 11:11 UTC, matthew7838 commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +        urine = 9.0
The total urine is actually different for each animal. I don't think it makes sense to declare it as module constants here.

2024-10-24 20:55 UTC, JoeWaddell commented on RUFAS/biophysical/animal/digestive_system/digestive_system.py
> +        else:
Minor point, but should we explicitly check that the animal is a Cow, in cases that additional/custom animal stages are added in the future and not caught here? E.g. explicitly check cow, then have an else that logs and error/warning if it doesn't fall under any of the explicit cases?

2024-10-25 07:50 UTC, matthew7838 commented on RUFAS/biophysical/animal/digestive_system/digestive_system.py
> +        else:
Good point. I will address this change.

2024-10-25 14:07 UTC, Isgotkowitz approved these changes
Left a bunch of minor comments, mostly related to the use of constants. But overall LGTM! Nice job working through all these equations Matthew

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/data_types/animal_manure_excretions.py
> +class AnimalManureExcretions(TypedDict):
Can you please write up an issue for syncing up this `AnimalManureExcretions` with the one in `data_structures/`, and add a TODO to this file noting that eventually the `AnimalManureExcretions` will have to be replaced with this one?

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/digestive_system.py
> +        milk_production_properties: ReproductionProperties
```suggestion
        milk_production_properties: MilkProductionProperties
```

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +                GeneralConstants.FRACTION_TO_PERCENTAGE
I like the use of a constant here instead of just `100`. But in this case I think it would be better to define a new constant, `ONE_HUNDRED_PERCENT`, instead of using a constant that has the same value but is supposed to be used in a different way. This is because it is very confusing to have a conversion factor being subtracted from. Also, if you define a new constant for 100 percent, could you please update `_calculate_dry_cow_manure` and `calculate_heifer_methane` to use the same constant?

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
What do you think about renaming `_calculate_lactating_cow_manure` and `_calculate_dry_cow_manure` to `_calculate_lactating_cow_methane` and `_calculate_dry_cow_methane`, respectively?

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +            112.55 * dry_matter_intake * (crude_protein_concentration / 100)
```suggestion
            112.55 * dry_matter_intake * (crude_protein_concentration * GeneralConstants.PERCENTAGE_TO_FRACTION)
```

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +        Total amount of phosphorus excreted by the given animal (g).
```suggestion
            Total amount of phosphorus excreted by the given animal (g).
```

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +            / GeneralConstants.FRACTION_TO_PERCENTAGE
```suggestion
            * GeneralConstants.PERCENTAGE_TO_FRACTION
```

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +            / GeneralConstants.FRACTION_TO_PERCENTAGE
```suggestion
            * GeneralConstants.PERCENTAGE_TO_FRACTION
```

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +            * (potassium_concentration / GeneralConstants.FRACTION_TO_PERCENTAGE)
```suggestion
            * (potassium_concentration * GeneralConstants.PERCENTAGE_TO_FRACTION)
```

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +            / GeneralConstants.FRACTION_TO_PERCENTAGE
```suggestion
            * GeneralConstants.PERCENTAGE_TO_FRACTION
```

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +            7.21 * dry_matter_intake + 15944 * potassium_concentration / GeneralConstants.FRACTION_TO_PERCENTAGE - 164.5
```suggestion
            7.21 * dry_matter_intake + 15944 * potassium_concentration * GeneralConstants.PERCENTAGE_TO_FRACTION - 164.5
```

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +            / GeneralConstants.FRACTION_TO_PERCENTAGE
```suggestion
            * GeneralConstants.PERCENTAGE_TO_FRACTION
```

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +            * (GeneralConstants.FRACTION_TO_PERCENTAGE - ash_concentration)
```suggestion
            * (GeneralConstants.FRACTION_TO_PERCENTAGE - ash_concentration)
```
Same comment on subtracting from `FRACTION_TO_PERCENTAGE` as in `enteric_methane_calculator` module.

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +            / GeneralConstants.FRACTION_TO_PERCENTAGE
```suggestion
            * GeneralConstants.PERCENTAGE_TO_FRACTION
```

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +            / GeneralConstants.FRACTION_TO_PERCENTAGE
```suggestion
            * GeneralConstants.PERCENTAGE_TO_FRACTION
```

2024-10-25 14:07 UTC, Isgotkowitz commented on RUFAS/biophysical/animal/digestive_system/manure_excretion_calculator.py
> +            * (potassium_concentration / GeneralConstants.FRACTION_TO_PERCENTAGE)
```suggestion
            * (potassium_concentration * GeneralConstants.PERCENTAGE_TO_FRACTION)
```

2024-10-25 20:43 UTC, JoeWaddell commented on RUFAS/biophysical/animal/digestive_system/enteric_methane_calculator.py
> +        if methane_model == "Mutian":  # [A.3E.C.1]
Agreed: especially when the documentation winds up on a website accessible to a wider userbase (e.g. non programmers), it'll help folks know where we're sourcing our logic for the equations in each method.

It is hard to keep track of when/where the references are used, so some simple description of where they currently are could be included, e.g. `Mutian calculation: [A.3E.C.1]`

2024-10-25 20:43 UTC, JoeWaddell commented on RUFAS/biophysical/animal/digestive_system/digestive_system.py
> +        else:
This statement probably needs a return or a raised error at this stage, to tamp down the mypy error

2024-10-25 20:43 UTC, JoeWaddell commented on RUFAS/biophysical/animal/digestive_system/digestive_system.py
> +                f"Supported animal types are cow, heifer and calf. Got {general_properties.animal_type}",
This might be overengineering, but do we have a dynamic list you could use here to show what classes are supported? e.g. maye a set of the `AnimalType`s found inside the `AnimalGroupingScenario`?

On second thought: the more explicit thing might be to just add a list of the `general_properties.animal_type`s hardcoded above, since those would necessarily need to be updated in cases that would cause this error

2024-10-28 14:12 UTC, JoeWaddell approved these changes
Nice job!

2024-10-28 15:04 UTC, merged