[DCA] Put DCA in RuFaS
RuminantFarmSystems/RuFaS pull request #2046
Opened 2024-10-28 20:44 UTC by Isgotkowitz

Integrates the Data Collection App into the RuFaS repo.

_Reviewers_: I recommend only reviewing the `.py` files in GitHub, and using your local git client and browser to try out the Data Collection App. If you're unsure of how to do this, please let me know and I can help you.

### Context

Issue(s) closed by this pull request: closes #1171, closes #968, closes #682

### What

This PR establishes the Data Collection as part of the RuFaS repo, by putting it in its own directory (`DataCollectionApp/`) at the same level as `RUFAS/`.

A task type is added to `TaskManager` which will update the Data Collection App so that any input files generated it will be compatible with the metadata properties.

The module `DataCollectionAppUpdater` is added to `RUFAS/`, and handles the updating of the Data Collection App when called by `TaskManager`.

### Why

Keeping the Data Collection App close to RuFaS makes them much easier to integrate, and by integrating so that updates can be made easily and conveniently we set ourselves up to make the Data Collection App a much more useful tool in the RuFaS ecosystem.

### How

The `DataCollectionAppUpdater` provides a one-stop shop for updating the DCA. When its main routine is called, it grabs the metadata properties from the `InputManager` and traverses them to create a dictionary. That dictionary is translated into JSON and then inserted into a Javascript file which is written into the DCA's `schema` directory.

The `DataCollectionAppUpdater` also rewrites the import scripts and list of available schema in DCA's `index.html` so that the changes in schema will be usable in the DCA. 

The original `index.html` has been modified so that it will save the data from different schemas as individual JSON files -- translation: if you enter Feed data, Animal data, and Config data in the DCA you will get a file for each. `DataCollectionAppUpdater` adds an extra field to each schema for collecting the filename, so that when each file is saved it will be with a name that the data enterer added.

### Test plan

Wrote a unit test suite for `DataCollectionAppUpdater` and the new method in `TaskManager`.

In addition to updating and expanding the unit test suite, I ran the task dedicated to updating the DataCollectionApp then checked the result of those updates - meaning I opened up the DCA and played around with it to make sure it worked right. I highly encourage reviewers to do the same. The default metadata has been modified so that you can run `python main.py` and it will update the DCA for you (I will change this back before merging).

2024-11-04 16:47 UTC, Isgotkowitz commented on input/metadata/task_manager_metadata.json
I will change this back before merging.

2024-11-04 20:02 UTC, PooyaHekmati commented
Do we need to have those document files?

2024-11-04 22:08 UTC, Isgotkowitz commented
> Do we need to have those document files?

Great question. I think we only _need_ the user guide, because it is the only PDF that is actually accessible through the DCA interface (as far as I can tell). The others might be helpful though, so maybe we should keep them and follow up on them in a separate PR?

2024-11-05 03:59 UTC, PooyaHekmati commented
> > Do we need to have those document files?
> 
> Great question. I think we only _need_ the user guide, because it is the only PDF that is actually accessible through the DCA interface (as far as I can tell). The others might be helpful though, so maybe we should keep them and follow up on them in a separate PR?

I don't see why we need to introduce files to the codebase whose purpose is not known.

2024-11-05 14:17 UTC, Isgotkowitz commented
> > > Do we need to have those document files?
> > 
> > 
> > Great question. I think we only _need_ the user guide, because it is the only PDF that is actually accessible through the DCA interface (as far as I can tell). The others might be helpful though, so maybe we should keep them and follow up on them in a separate PR?
> 
> I don't see why we need to introduce files to the codebase whose purpose is not known.

Ok, they're out of there.

2024-11-06 18:57 UTC, KFosterReed commented
I was able to produce the Data Collection App using this PR in the RuFaS repo so that's great! However, the intro page to the different data collection pages doesn't seem to be behaving properly for me. I opened it on Chrome and Microsoft Edge and the "Data Entry" just shows up as text and not a button that can be used to start data entry: 

![image](https://github.com/user-attachments/assets/61e99a7e-cebd-4208-9e1b-f75625c121a7)


I will try on my personal computer as well to see if it is a USDA thing
** Update: Also does not work on my personal computer

2024-11-06 19:41 UTC, Isgotkowitz commented
> I was able to produce the Data Collection App using this PR in the RuFaS repo so that's great! However, the intro page to the different data collection pages doesn't seem to be behaving properly for me. I opened it on Chrome and Microsoft Edge and the "Data Entry" just shows up as text and not a button that can be used to start data entry:
> 
> ![image](https://private-user-images.githubusercontent.com/41019131/383689477-61e99a7e-cebd-4208-9e1b-f75625c121a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjIzMjUsIm5iZiI6MTczMDkyMjAyNSwicGF0aCI6Ii80MTAxOTEzMS8zODM2ODk0NzctNjFlOTlhN2UtY2ViZC00MjA4LTllMWItZjc1NjI1YzEyMWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE5NDAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOWEyMDVlZTJiZTdmZjNhOWFlYzI1ZGMxNzUwMzgxN2M0ZGM1OTFhZjY3MDVjMDgwZGMwZTk0YzQ2ODZkYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CImQJqUbGEstiJE6GC77iGsgjtSLCPVb-Y6FG_HVM04)
> 
> I will try on my personal computer as well to see if it is a USDA thing ** Update: Also does not work on my personal computer

Crud, I will see if I can reproduce this on my computer.

Did you try running `python main.py` on this branch and seeing if anything changed in the DCA?

2024-11-06 19:45 UTC, KFosterReed commented
> > I was able to produce the Data Collection App using this PR in the RuFaS repo so that's great! However, the intro page to the different data collection pages doesn't seem to be behaving properly for me. I opened it on Chrome and Microsoft Edge and the "Data Entry" just shows up as text and not a button that can be used to start data entry:
> > ![image](https://private-user-images.githubusercontent.com/41019131/383689477-61e99a7e-cebd-4208-9e1b-f75625c121a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjIzMjUsIm5iZiI6MTczMDkyMjAyNSwicGF0aCI6Ii80MTAxOTEzMS8zODM2ODk0NzctNjFlOTlhN2UtY2ViZC00MjA4LTllMWItZjc1NjI1YzEyMWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE5NDAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOWEyMDVlZTJiZTdmZjNhOWFlYzI1ZGMxNzUwMzgxN2M0ZGM1OTFhZjY3MDVjMDgwZGMwZTk0YzQ2ODZkYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CImQJqUbGEstiJE6GC77iGsgjtSLCPVb-Y6FG_HVM04)
> > I will try on my personal computer as well to see if it is a USDA thing ** Update: Also does not work on my personal computer
> 
> Crud, I will see if I can reproduce this on my computer.
> 
> Did you try running `python main.py` on this branch and seeing if anything changed in the DCA?

I did! That is how I got the HTML file that produced the image pasted above :/

2024-11-06 19:46 UTC, Isgotkowitz commented
> > > I was able to produce the Data Collection App using this PR in the RuFaS repo so that's great! However, the intro page to the different data collection pages doesn't seem to be behaving properly for me. I opened it on Chrome and Microsoft Edge and the "Data Entry" just shows up as text and not a button that can be used to start data entry:
> > > ![image](https://private-user-images.githubusercontent.com/41019131/383689477-61e99a7e-cebd-4208-9e1b-f75625c121a7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA5MjIzMjUsIm5iZiI6MTczMDkyMjAyNSwicGF0aCI6Ii80MTAxOTEzMS8zODM2ODk0NzctNjFlOTlhN2UtY2ViZC00MjA4LTllMWItZjc1NjI1YzEyMWE3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTA2VDE5NDAyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNiOWEyMDVlZTJiZTdmZjNhOWFlYzI1ZGMxNzUwMzgxN2M0ZGM1OTFhZjY3MDVjMDgwZGMwZTk0YzQ2ODZkYWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.CImQJqUbGEstiJE6GC77iGsgjtSLCPVb-Y6FG_HVM04)
> > > I will try on my personal computer as well to see if it is a USDA thing ** Update: Also does not work on my personal computer
> > 
> > 
> > Crud, I will see if I can reproduce this on my computer.
> > Did you try running `python main.py` on this branch and seeing if anything changed in the DCA?
> 
> I did! That is how I got the HTML file that produced the image pasted above :/

Good news: I reproduced the issue. Bad news: its a Windows thing 😭

2024-11-06 20:02 UTC, Isgotkowitz commented
@KFosterReed should be working for you now

2024-11-06 22:21 UTC, KFosterReed commented
So far I just looked at the Animal Module page but it looks great! The save and validate functionalities work well and the layout is pretty easy to follow (ignoring some improvements we should make on the metadata properties for the Animal Module). 

I would like to look through the rest of the input files as well as try to run a simulation with the json files produced but so far so good!

2024-11-07 14:58 UTC, Isgotkowitz commented
> So far I just looked at the Animal Module page but it looks great! The save and validate functionalities work well and the layout is pretty easy to follow (ignoring some improvements we should make on the metadata properties for the Animal Module).
> 
> I would like to look through the rest of the input files as well as try to run a simulation with the json files produced but so far so good!

Strangely enough, it doesn't actually produce json files that can be fed right into RuFaS. It produces .txt files which contains a big list of all the inputs, which I believe was the same behavior as the old DCA.

I'm not fully sure what the vision for the DCA is, but I assume it would be better if it turned each individual entry into a standalone JSON

2024-11-08 14:44 UTC, elle-andreen commented
- I noticed some inputs are excluded from DCA (random and set seed in configs, for example). Is this intentional and where/how is it dictated which metadata variables are and are not included in the DCA schema? 
- I updated some descriptions in the metadata properties and they were correctly assimilated into the corresponding DCA descriptions 👍 
- I'm not sure if this is possible, but if a variable has no default supplied (e.g., the parity fraction variables) in the metadata properties, I think it would be helpful if the input box in the DCA was blank instead of being 0. I think it helps prevent situations where, if the user doesn't overwrite it, a 0 value will cause a failure or will be overwritten by another value unknown to the user. Maybe this falls under a future DCA improvement PR and this this PR. 
- I would be interested to get @KFosterReed's opinion but I think the PDF documents that were previously linked should still remain in the repo here. They are resources with a specific function to help users understand and translate inputs into the DCA. If they're not kept here in the repo and we still want to use them, they would have to be hosted elsewhere (Basecamp? Box?) and then linked somehow in the DCA. I think this is asking for accessibility issues and wrong link problems. But, maybe we want all DCA documentation elsewhere with the scientific/technical documentation.

The automatic updating of the content based on the metadata is super helpful and will come in handy. Some variables in the metadata need defaults and descriptions but that is a problem for another PR. The DCA itself also needs work to be easily usable but I think the specific goals of this PR have been accomplished!

2024-11-25 21:04 UTC, Isgotkowitz commented on DataCollectionApp/index.html
> +        });
This function differs from the old DCA. By parsing the data as an array, it is able to separate out the data from different input schemas and save them as individual JSONs

2024-11-26 14:40 UTC, Isgotkowitz commented
> * I noticed some inputs are excluded from DCA (random and set seed in configs, for example). Is this intentional and where/how is it dictated which metadata variables are and are not included in the DCA schema?

Right now, the DCA only works with the lowest level input files. You can think of the inputs sort of like a stack: at the top is the Task Manager metadata, then the next level is the tasks, then the regular metadata file, then the base input files (Animal, Feed, Field, etc.).

Right now this is intentional, because the metadatas and tasks files rely heavily on having correct file paths. I think a good next step would be to tweak some of the input schemas so that we can generate that lower level metadata automatically for the user, then allow them to write the tasks they want and link it to the metadata that was generated.

> * I updated some descriptions in the metadata properties and they were correctly assimilated into the corresponding DCA descriptions 👍

:grin:

> * I'm not sure if this is possible, but if a variable has no default supplied (e.g., the parity fraction variables) in the metadata properties, I think it would be helpful if the input box in the DCA was blank instead of being 0. I think it helps prevent situations where, if the user doesn't overwrite it, a 0 value will cause a failure or will be overwritten by another value unknown to the user. Maybe this falls under a future DCA improvement PR and this this PR.

I think this should be a future DCA improvement. It is definitely possible, but it would be good to make that change in a more isolated way so that we know exactly which inputs it effects and none of them are screwed up.

2024-11-26 14:45 UTC, Isgotkowitz commented
@KFosterReed and @elle-andreen this is ready for a re-review. The main thing that has changed is when the inputs are downloaded, they are individual JSON files. Also there is an input field that requires users to give a name which is used to name the corresponding JSON file. As Elle pointed out, there is still a lot of work to be done but I think it would be good to write up separate issues for each.

2024-11-26 14:54 UTC, Isgotkowitz commented
List of improvements to make after this PR:
- Add feature that automatically generates metadata containing all the input files.
  - Restructuring Field and all related inputs will make this feasible.
- Add Tasks as kind of input file that DCA can be used for.
- ~Don't automatically add 0's in input fields that don't have defaults.~
- ~Make null a valid input type for nullable inputs.~
- Improve messages when inputs are invalid
- Write Wiki for using the DCA
- Add boolean field to each property called "data_collection_app_compatible". When iterating through properties, use that field to determine whether or not to write a DCA schema for it, not the hard-coded list currently in `DataCollectionAppUpdater`
- Allow users to select from drop down of feed names instead of typing feed numbers.

2024-11-26 16:26 UTC, PooyaHekmati requested changes

2024-11-26 16:26 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +]
Why is this hardcoded? It has to come from an actual metadata file that IM has read and processed.

2024-11-26 16:26 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +                continue
Why?

2024-11-26 16:26 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +SCHEMA_SCRIPT_TAG_PLACEHOLDER: str = "    <!-- Spot where schema import scripts go -->"
```suggestion
SCHEMA_SCRIPT_TAG_PLACEHOLDER: str = "    <!-- Schema imports go here-->"
```

2024-11-26 16:26 UTC, PooyaHekmati commented on DataCollectionApp/template
> +    <!-- Spot where schema import scripts go -->
```suggestion
    <!-- Schema imports go here-->
```

2024-11-26 16:26 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +            schema["type"] = "number"
```suggestion
        schema["minimum"] = minimum or "null"
        schema["maximum"] = maximum or "null"
        schema["default"] = default or "null"
        schema["options"]["inputAttributes"]["placeholder"] = default or minimum or maximum or "null"
        schema["options"]["infoText"] = description or "null"
        if nullable:
            schema["type"] = ["number", "null"]
        else:
            schema["type"] = "number"
```

2024-11-26 16:26 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +            schema["type"] = "boolean"
same as bove

2024-11-26 16:26 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +        if pattern is not None:
same as above

2024-11-26 16:26 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +        unsplit_list = input_pattern[2:-2]
why?

2024-11-26 16:26 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +    def _get_list_of_options(input_pattern: str) -> list[str]:
this method is cryptic, maybe add examples to docstrings.
Also, why is it static?

2024-11-26 16:29 UTC, PooyaHekmati commented
> List of improvements to make after this PR:
> 
> * Add feature that automatically generates metadata containing all the input files.

The DCA schema is supposed to be generated from a metadata; how can the output not match the input metadata?

> * Add Tasks as kind of input file that DCA can be used for.

I don't understand this sentence.

> * Don't automatically add 0's in input fields that don't have defaults.

My comments on the PR should resolve this.

> * ~Make null a valid input type for nullable inputs.~
> * Improve messages when inputs are invalid

2024-11-26 16:45 UTC, Isgotkowitz commented on RUFAS/data_collection_app_updater.py
> +                continue
Can you please be more specific

2024-11-26 17:23 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +                continue
Why is `PROPERTIES_TO_CREATE_SCHEMA_FOR` needed in the first place?

2024-11-26 17:39 UTC, Isgotkowitz commented on RUFAS/data_collection_app_updater.py
> +        unsplit_list = input_pattern[2:-2]
The pattern ensures that the string starts with "^(" and ends with ")$". This snippet removes the "^(" and ")$" before the string is split into substrings which are used to create the dropdown in the DCA

2024-11-26 17:47 UTC, Isgotkowitz commented on RUFAS/data_collection_app_updater.py
> +]
The properties are pulled from the IM, which have been read and processed. As the properties are iterated over, this list is used to decided whether a DCA schema needs to be updated for that property.

This makes sense for a lot of properties, because the inputs associated with them contain so much data that it isn't helpful or feasible to collect them with the DCA. The properties that schema are not generated for are:
- animal_population_properties
- animal_net_merit_properties
- animal_top_listing_semen_properties
- lactation_properties
- economic_properties
- emissions_properties
- feed_emissions_properties
- user_feeds_properties
- NRC_Comp_properties
- NASEM_Comp_properties
- weather_properties
- EEE_constants_properties
- end_to_end_test_result_path_properties
- end_to_end_testing_input_properties

2024-11-26 18:24 UTC, Isgotkowitz commented on RUFAS/data_collection_app_updater.py
> +    def _get_list_of_options(input_pattern: str) -> list[str]:
Examples added. It is static because the logic of the method is entirely self-contained, it doesn't need any references to self and it doesn't make any other parts of the code cleaner to have it be an instance method

2024-11-26 18:40 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +        unsplit_list = input_pattern[2:-2]
I think this explanation merits a comment in the code to explain why 2 and -2 are there.

2024-11-26 18:42 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +    def _get_list_of_options(input_pattern: str) -> list[str]:
The method is inconsistent with the rest of the methods. In the absence of good reasons to decide on the static-ness of a method, consistency is a good reason to rely on. Therefore, I don't think this needs to be static.

2024-11-26 18:47 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +]
This approach makes it harder to maintain. A better solution is to have metadata that only contains inputs that can be collected by DCA. Alternatively, you can add a new field to the metadata itself to indicate should a properties be added to DCA or not. This approach is not only more explicit and maintainable, it also facilitates the generation of metadata that is functional (the data either comes directly from the IM or is populated as user input.)

2024-11-26 19:47 UTC, Isgotkowitz commented on RUFAS/data_collection_app_updater.py
> +]
> Alternatively, you can add a new field to the metadata itself to indicate should a properties be added to DCA or not.

I like this idea -- my first thought for field name is `data_collection_app_compatible`. For this approach though, would it be ok to implement it in a follow-up PR? To prevent the new field name from making the metadata illegal, `DataValidator` has to be modified, and given the size of this PR already I think it would be better to make that change separately

2024-11-26 20:30 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +]
Sure.
Also, remove the generated schemas from this PR before merging and add the schema directory to git ignore.

2024-11-26 20:52 UTC, Isgotkowitz commented on RUFAS/data_collection_app_updater.py
> +        unsplit_list = input_pattern[2:-2]
Roger that, a comment has been added

2024-11-26 22:01 UTC, Isgotkowitz commented on RUFAS/data_collection_app_updater.py
> +                continue
See comment above -- but in a nutshell, it is to prevent the DCA from getting schemas for inputs that aren't DCA appropriate. This method will be rewritten so that it doesn't rely on a hardcoded list though

2024-11-27 03:19 UTC, Isgotkowitz commented on RUFAS/data_collection_app_updater.py
> +            schema["type"] = "number"
I did not implement this exact suggestion, but I did change the code in what I think is the spirit of this suggestion.

Min and max can't have "null" as their values, it screws up how inputs are validated. For the infoText, it can just be whatever the "description" is, JSON-Editor handles it well.

Instead of putting in the default, min, or max as the placeholder, I made them empty strings. While I was working with this I found that the grey placeholder values were hard to distinguish visually from blue, actual inputs, and that a blank box was more striking. I'm happy with the blank box, but an even better solution might be to have a string that says something like "Add numerical input"

2024-11-27 03:32 UTC, Isgotkowitz commented
> > List of improvements to make after this PR:
> > 
> > * Add feature that automatically generates metadata containing all the input files.
> 
> The DCA schema is supposed to be generated from a metadata; how can the output not match the input metadata?

Each schema corresponds to a single input file. The metadata is a single file with paths to a bunch of different input files. When a user puts information into the DCA and hits "Save Result", they get a bunch of individual input files, but no metadata with references to all those individual input files.

> > * Add Tasks as kind of input file that DCA can be used for.
> 
> I don't understand this sentence.

One of the input files contains the tasks which are given to TaskManager. There is no DCA schema for collecting that type of input in this PR

2024-11-27 04:56 UTC, PooyaHekmati commented on RUFAS/data_collection_app_updater.py
> +            schema["type"] = "number"
I appreciate your feedback about the placeholders and your efforts to improve the user experience. That said, the decision to use the placeholders as they were originally specified was intentional, as empty strings defeat the purpose of having placeholders. Additionally, the text at the top of the DCA page already explains the meaning of blue and grey colors, ensuring users can differentiate between them.

Please proceed with implementing the placeholders as instructed. If there’s a need to revisit this feature in the future, we can address it as a team. Also, as part of this task, please add placeholders to other data types as well.

2024-11-27 04:58 UTC, PooyaHekmati commented
> > > List of improvements to make after this PR:
> > > 
> > > * Add feature that automatically generates metadata containing all the input files.
> > 
> > 
> > The DCA schema is supposed to be generated from a metadata; how can the output not match the input metadata?
> 
> Each schema corresponds to a single input file. The metadata is a single file with paths to a bunch of different input files. When a user puts information into the DCA and hits "Save Result", they get a bunch of individual input files, but no metadata with references to all those individual input files.

Normally, I would insist that this needs to be done in this PR as it was part of the plan. However, knowing that you are going to have another PR to remove that hardcoded list of properties, I think it makes more sense to implement this there.

2024-11-27 14:49 UTC, elle-andreen commented
- There are some metadata-to-DCA translation issues with the manure separator and treatment Name inputs (they're appearing as a drop-down instead of a text box). I did not see any other obvious instances of this in other schema though.
- For Field Properties, just to confirm, are field properties supposed to be provided _per field_ or just one set of properties that apply to your whole farm? I ask because there is no "Add new element" type option in that page, but I'm guessing that users do not need more than one set of Field Properties inputs
- There are still variable names that are being translated from the metadata to the DCA correctly, but don't make sense in the DCA context, e.g. under Manure Manage Scenarios, the variable "Bedding Type" would be easier to understand if it was named "Bedding _Name_", but "Bedding Type" is in fact its current name. It's not the end of the world but I'm curious to know whether we will address these types of things by changing the variable name in the metadata, or by changing how it appears in the DCA. I don't need an answer now, just something to consider for future DCA improvements!
- I really like the 'file name' feature, and the JSONS saved and ran properly for me 😁 

One improvement to add to the list, if desired: for feeds, I think I recall the old DCA was able to reference the feed library via a dropdown selection, so users could choose the feed by name, not by number. Either way, that would be great to have. 

Overall, this looks great to me and I will approve notwithstanding any further changes from my or others' comments!

2024-11-27 15:30 UTC, Isgotkowitz commented
> * There are some metadata-to-DCA translation issues with the manure separator and treatment Name inputs (they're appearing as a drop-down instead of a text box). I did not see any other obvious instances of this in other schema though.

Nice catch, I'll find a fix for this.

> * For Field Properties, just to confirm, are field properties supposed to be provided _per field_ or just one set of properties that apply to your whole farm? I ask because there is no "Add new element" type option in that page, but I'm guessing that users do not need more than one set of Field Properties inputs

Yes, the field properties require field inputs to be written per field. Users can specify multiple fields, but would need separate data entries for each field. This is a function of the current metadata properties structure, I am going to write up an issue proposing a change to the input structure which would result in a single input file for all field configurations.

> * There are still variable names that are being translated from the metadata to the DCA correctly, but don't make sense in the DCA context, e.g. under Manure Manage Scenarios, the variable "Bedding Type" would be easier to understand if it was named "Bedding _Name_", but "Bedding Type" is in fact its current name. It's not the end of the world but I'm curious to know whether we will address these types of things by changing the variable name in the metadata, or by changing how it appears in the DCA. I don't need an answer now, just something to consider for future DCA improvements!

Another good catch, the information pop-up helps a little with this but it is still pretty confusing. The thing is that the appearance of the DCA is dictated by the metadata, so we may need to add an extra field to the metadata in order to address this if we can't change the actual structure of the inputs.

> * I really like the 'file name' feature, and the JSONS saved and ran properly for me 😁

Noice, me too.

> One improvement to add to the list, if desired: for feeds, I think I recall the old DCA was able to reference the feed library via a dropdown selection, so users could choose the feed by name, not by number. Either way, that would be great to have.

That definitely sounds like it would make things a lot easier. I'm in favor of adding this in a follow-up PR, because I think it will require some significant additions to the metadata and/or code.

> Overall, this looks great to me and I will approve notwithstanding any further changes from my or others' comments!

👍

2024-11-27 15:33 UTC, Isgotkowitz commented on RUFAS/data_collection_app_updater.py
> +            schema["type"] = "number"
Placeholders have been implemented

2024-11-27 15:58 UTC, PooyaHekmati approved these changes
[![LGTM](https://lgtm.lol/p/809)](https://lgtm.lol/i/809)

2024-11-27 17:27 UTC, Isgotkowitz commented
@elle-andreen I think the Manure inputs have been fixed without breaking any of the other dropdowns.

2024-11-27 17:40 UTC, elle-andreen approved these changes
All looks good to me now, thanks Ed! Looking forward to having this functionality onboard and to future DCA updates!

2024-12-03 15:14 UTC, merged

2024-12-03 16:33 UTC, Isgotkowitz commented
> List of improvements to make after this PR:
> 
> * Add feature that automatically generates metadata containing all the input files.

#2122

>   * Restructuring Field and all related inputs will make this feasible.

#2121

> * Add Tasks as kind of input file that DCA can be used for.

#2123 

> * ~Don't automatically add 0's in input fields that don't have defaults.~
> * ~Make null a valid input type for nullable inputs.~
> * Improve messages when inputs are invalid

#2124 

> * Write Wiki for using the DCA
> * Add boolean field to each property called "data_collection_app_compatible". When iterating through properties, use that field to determine whether or not to write a DCA schema for it, not the hard-coded list currently in `DataCollectionAppUpdater`

#2125

> * Allow users to select from drop down of feed names instead of typing feed numbers.

#2126