[DataValidator] Removing OM usage from the data validator
RuminantFarmSystems/RuFaS pull request #2061
Opened 2024-11-12 07:02 UTC by matthew7838

Remove the usage of OM in Datavalidator to enable its use in OM.

### Context

Issue(s) closed by this pull request: closes #2052

### What

1. No more usage/imports of OM in the data validator.
2. logs/errors/warnings will now be saved in the instance variable called event_logs, the caller will have to deal with the om and the saved logs/errors/warnings.
3. Since we are now storing/modifying data for each instance of DV, methods will now be non-static.
4. Tests have been modified to reflect the changes. 

### Why

It prevents circular import when using the data validator in OM.

### How

Removed OM usage.

### Test plan

Run with default tasks and outputs are the same, and run and pass with modified tests, the amount of warnings/errors/logs remains the same. I would think that's promising enough for the content of this PR.
The test plan right now is something worth discussing, it is currently not that concrete due to a few reasons.
1. The original coverage is lacking, however, most methods' changes are covered and run with the test modification in this PR.  Should I cover them all in this PR? or should that be a separate issue(I personally think this is cleaner/better)?
2. I will not add tests for the route log method since it's already in OM it's exactly the same, and it should be extracted in the future.

2024-11-14 14:47 UTC, allisterakun requested changes
Requested change on this PR because:
1. Inconsistent key names in the event log array. Some of them are using "info_map" while the others are "info map".
    1. I think it is worth to create a `TypedDict` for the event log dictionary entires to prevent the inconsistency.
    2. Also, I think we should use snake case for all keys in event log dictionary for consistency with the rest of the code base.
5. After returning all of the logs/warnings/errors, are you adding them to the OM somewhere? I don't think I see them being processed in IM

2024-11-14 14:47 UTC, allisterakun commented on RUFAS/data_validator.py
> +                        "error message": f"Metadata depth exceeds maximum allowed depth"
```suggestion
                        "error_message": f"Metadata depth exceeds maximum allowed depth"
```
For consistency with the rest of the codebase

2024-11-14 14:47 UTC, allisterakun commented on RUFAS/data_validator.py
> +                        "info map": info_map,
```suggestion
                        "info_map": info_map,
```

2024-11-14 14:47 UTC, allisterakun commented on RUFAS/data_validator.py
> +            self.event_logs.append({"warning": warning_name, "warning message": warning_message, "info_map": info_map})
How is this key "info_map" and the rest are "info map"

2024-11-14 14:47 UTC, allisterakun commented on RUFAS/input_manager.py
> +        valid, message = self.data_validator.validate_properties(self.__metadata, self.metadata_depth_limit)
Are you adding these messages to the OM at some point?

2024-11-14 14:47 UTC, allisterakun commented on RUFAS/data_validator.py
> +        self.event_logs: list[dict[str, str | dict[str, str]]] = []
I think it is worth to define a `TypedDict` here for the event_log entries.

2024-11-14 15:08 UTC, matthew7838 commented on RUFAS/data_validator.py
> +            self.event_logs.append({"warning": warning_name, "warning message": warning_message, "info_map": info_map})
good catch

2024-11-14 15:09 UTC, matthew7838 commented on RUFAS/input_manager.py
> +        valid, message = self.data_validator.validate_properties(self.__metadata, self.metadata_depth_limit)
It's being raised in the error thrown. Those messages are stored in the dv instances and should be handled in the IM.

2024-11-14 15:10 UTC, matthew7838 commented on RUFAS/data_validator.py
> +        self.event_logs: list[dict[str, str | dict[str, str]]] = []
This sounds like a good idea.

2024-11-14 15:11 UTC, matthew7838 commented
> 2. After returning all of the logs/warnings/errors, are you adding them to the OM somewhere? I don't think I see them being processed in IM

Update: On second thought, I should modify this in this PR.

2024-11-14 16:39 UTC, matthew7838 commented on RUFAS/data_validator.py
> +        self.event_logs: list[dict[str, str | dict[str, str]]] = []
After some try, I think this is not the best option since one of the keys is constantly changing.

2024-11-15 04:24 UTC, ew3361zh reviewed
Nice work, Matthew, this seems like it's a good start to this issue. I left a few comments that I think need to be addressed before approving.

One side-note - the `info_map` function reference on line 930 for `check_modifiability()` in IM is incorrect. It has `"function": self._add_variable_to_pool.__name__,`. Could you fix it here?

2024-11-15 04:24 UTC, ew3361zh commented on RUFAS/data_validator.py
> +    def validate_properties(self, metadata: Dict[str, Any], metadata_depth_limit: int) -> Tuple[bool, str]:
```suggestion
    def validate_properties(self, metadata: dict[str, Any], metadata_depth_limit: int) -> tuple[bool, str]:
```
I think it's preferred practice to use the native python lowercase type hints where possible (doesn't yet work with Any).

2024-11-15 04:24 UTC, ew3361zh commented on RUFAS/input_manager.py
> +    def _route_logs(self, log_pool: list[dict[str, str | dict[str, str]]]) -> None:
I think the best thing to do would be to use the OM version of this function. I don't see a need to duplicate the code here. Did you try making that OM function public and calling it from IM?

2024-11-15 04:24 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        self._route_logs(self.data_validator.event_logs)
Should this happen before the ValueError is raised so that the logs can still be added to the OM? I think the way we have things set up the logs/errors/warnings pool still gets dumped even with a runtime error so that would probably be helpful to have these in that case.

I see that populate_pool also calls on data_validator and you will want to avoid double-adding the logs so maybe route_logs is only called in the `if not valid:` block.

2024-11-15 04:24 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            self._route_logs(self.data_validator.event_logs)
Should route_logs() be called in the else statement here as well?

2024-11-15 05:01 UTC, matthew7838 commented on RUFAS/input_manager.py
> +    def _route_logs(self, log_pool: list[dict[str, str | dict[str, str]]]) -> None:
Talked with Pooya about this, there will be an issue regarding this that will use the OM version for both the report generator and IM. This implementationwill be a short temporary place holder.

2024-11-15 05:01 UTC, matthew7838 commented on RUFAS/input_manager.py
> +        self._route_logs(self.data_validator.event_logs)
Great suggestion and good catch.

2024-11-15 05:02 UTC, matthew7838 commented on RUFAS/input_manager.py
> +            self._route_logs(self.data_validator.event_logs)
yes

2024-11-18 16:17 UTC, Isgotkowitz commented on RUFAS/data_validator.py
> +                    "message": f"Invalid 'default' for '{key_path}': Expected a number but " f"got {type(default)}.",
```suggestion
                    "message": f"Invalid 'default' for '{key_path}': Expected a number but got {type(default)}.",
```

2024-11-18 16:17 UTC, Isgotkowitz commented on RUFAS/data_validator.py
> +                    "message": f"Invalid 'default' for '{key_path}': " f"Value is not nullable and default is 'None'.",
```suggestion
                    "message": f"Invalid 'default' for '{key_path}': value is not nullable and default is 'None'.",
```

2024-11-18 16:17 UTC, Isgotkowitz commented on RUFAS/data_validator.py
> +                    "message": f"Invalid 'default' for '{key_path}': Value is not nullable and" f" default is 'None'",
```suggestion
                    "message": f"Invalid 'default' for '{key_path}': Value is not nullable and default is 'None'",
```

2024-11-18 16:17 UTC, Isgotkowitz commented on RUFAS/data_validator.py
> +                    "message": f"Invalid 'default' for '{key_path}': Expected a string but" f" got {type(default)}",
```suggestion
                    "message": f"Invalid 'default' for '{key_path}': Expected a string but got {type(default)}",
```

2024-11-18 16:17 UTC, Isgotkowitz commented on RUFAS/data_validator.py
> +                    "message": f"Invalid 'pattern' for '{key_path}': Expected a string but got" f" {type(pattern)}",
```suggestion
                    "message": f"Invalid 'pattern' for '{key_path}': Expected a string but got {type(pattern)}",
```

2024-11-18 16:17 UTC, Isgotkowitz commented on RUFAS/data_validator.py
> +                    "message": f"Invalid 'default' for '{key_path}': Value is not nullable and" f" default is 'None'",
```suggestion
                    "message": f"Invalid 'default' for '{key_path}': Value is not nullable and default is 'None'",
```

2024-11-18 16:17 UTC, Isgotkowitz commented on RUFAS/data_validator.py
> +                    "message": f"Invalid 'default' for '{key_path}': Expected a bool but got" f" {type(default)}",
```suggestion
                    "message": f"Invalid 'default' for '{key_path}': Expected a bool but got {type(default)}",
```

2024-11-18 16:17 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                    self.om.add_warning(log["warning"], log["message"], log["info_map"])
It would be good to check for the case when the log is not a log, warning, or error. Also if any error, warning, or log doesn't have the correct keyset.

2024-11-18 16:17 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                ):
```suggestion
                is_correct_type: bool = isinstance(log["error"], str) and isinstance(log["message"], str) and isinstance(log["info_map"], dict)
                is_keyset_correct: bool = log.keys() == ["error", "message", "info_map"]
                if is_correct_type and is_keyset_correct:
```

2024-11-18 16:17 UTC, Isgotkowitz commented on README.md
> +[![Coverage](https://img.shields.io/badge/Coverage-95%25-brightgreen)](https://github.com/RuminantFarmSystems/MASM/actions/workflows/combined_format_lint_test_mypy.yml)
I believe this drop in coverage is a result of a drop in coverage of the Input Manager. Please update the test suite so that it maintains the same coverage level.

2024-11-18 19:12 UTC, matthew7838 commented on README.md
> +[![Coverage](https://img.shields.io/badge/Coverage-95%25-brightgreen)](https://github.com/RuminantFarmSystems/MASM/actions/workflows/combined_format_lint_test_mypy.yml)
This is due to the routing method not being tested, it's the exact same as the one in OM. There will be a separate issue that cleans them and make use of the one in OM across the codebase regarding these log/error/warning routing. I also agree with your above comments and I'll address them in that issue/PR.

2024-11-19 15:11 UTC, Isgotkowitz commented on README.md
> +[![Coverage](https://img.shields.io/badge/Coverage-95%25-brightgreen)](https://github.com/RuminantFarmSystems/MASM/actions/workflows/combined_format_lint_test_mypy.yml)
Can you please write up that issue and mention this PR in it?

2024-11-19 15:11 UTC, Isgotkowitz approved these changes
LGTM, thank you for responding to FB Matthew.

2024-11-19 15:12 UTC, matthew7838 commented on README.md
> +[![Coverage](https://img.shields.io/badge/Coverage-95%25-brightgreen)](https://github.com/RuminantFarmSystems/MASM/actions/workflows/combined_format_lint_test_mypy.yml)
Will do!

2024-11-19 15:16 UTC, ew3361zh commented
I think this looks good - I'm a little concerned that I'm getting pretty different numbers of warnings and logs between dev and this branch. Maybe it's just what I merged into dev this morning (the C&S-Manure disentanglement PR). But I will also test out a few other scenarios where we'd expect the same number but after intentionally erroring out.

dev:
<img width="555" alt="Screenshot 2024-11-19 at 10 15 33 AM" src="https://github.com/user-attachments/assets/4a9e18ad-dcc1-419c-9a3d-3ffd4d686ad2">

om-remove branch:
<img width="553" alt="Screenshot 2024-11-19 at 10 16 00 AM" src="https://github.com/user-attachments/assets/9b0e2112-722a-48a3-88e2-d05d1c339f37">

2024-11-19 16:29 UTC, ew3361zh approved these changes
Nice work, Matthew - counts of warnings and logs are now matching on this branch and dev. Everything else looks good as well!

2024-11-19 17:49 UTC, allisterakun approved these changes
LGTM! Nice work!

2024-11-19 17:57 UTC, merged