command line functionality with option to suppress graphics production
RuminantFarmSystems/RuFaS pull request #207
Opened 2022-11-07 18:17 UTC by morrowcj

# Purpose
This small pull request adds functionality to allow RuFaS to run from the command line without being prompted for input.
It also adds the option to prevent graphics from being produced - which cuts the runtime in half. This functionality
is needed for circumstances in which RuFaS needs to be run many times in an automated way (i.e., batch mode). It will
be especially useful for model validation and optimization.

The model can be run exactly as it was previously, prompting users for direct input:

```commandline
python main.py
```

Or the input file (or dir) can be specified directly from the command line, skipping the need for interactive input:

```commandline
python main.py "input/ARL.json"
```

And you can prevent graphics from being created by passing the GNU-style flag `--no-graphics`:

```commandline
python main.py "input/ARL.json" --no-graphics
```

The same can be achieved from within python as well:
```python
from main import run_rufas

run_rufas(in_path="input/ARL.json", make_graphs=False)
```

# Changes

The primary changes were made in `main.py`. The main function has been renamed from `main()` to `run_rufas()`, which 
accepts an optional file path, an argument specifying if graphics should be produced, and an argument specifying if
messages should be printed (not fully implemented). In order to suppress graphics across all modules, a global variable 
`SUPPRESS_GRAPHICS` was created (`config/global_variables.py`) and is updated by this function. Command line arguments 
are parsed with the `argparse` python package when applicable. 

`user_prompt.py` was also slightly refactored to implement these changes. The main function in this file is now 
`get_files_from_input()`, which returns a formatted file path based on its `path` initiating a prompt for the user to 
give input if `path=None`. 

`simulation_engine.py` has been slightly altered to suppress graphics production if the `SUPPRESS_GRAPHICS=True` 

Finally, `base_report.py` assigns its `produce_graphics` attribute to `False` if `SUPPRESS_GRAPHICS=True`.

No unit tests have yet been added for these changes mostly because I am unsure how to formally test them.

2022-11-08 04:14 UTC, PooyaHekmati requested changes
I like this PR in many different aspects. Added some comments to make it even better.

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +def get_files_from_input(path=None, verbose=True):
Missing type annotation, docstring, and unit test. The testing can be done by mocking input_prompt and handle_input_file and counting their calls.

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +def get_files_from_input(path=None, verbose=True):
The name of the function is not descriptive. Which input? How does it retrieve files? Did you mean get_files_names_from_input?

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +        out = input_prompt()
Avoid using "out" as a name. It can be misinterpreted as a keyword.

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +def handle_input_file(path="input/ARL.json", verbose=True):
Vague and non-informative name: what does "handling" involve? it seems the function is performing some logic on the file names and paths, not the file themselves (misleading function name).

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +    """ Converts a file path string into usable file path objects (from pathlib package)
What does "usable" mean? How does the conversion happen?

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +def handle_input_file(path="input/ARL.json", verbose=True):
Missing type annotation and unit tests. Also, vague and incomplete docstring.

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +        path: The path to an input file (.json or .txt) or a directory containing .json files
Is this an absolute path or is it relative or it doesn't matter? What is the data type (str vs path)?

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +    Returns: a list of OS-specific files
What is the type of data in the list?

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +    """
It seems this function also raises some errors, yet they are not mentioned in the docstring.

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +    else:
This should probably move to the beginning of the function.

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +def accept_path_from_prompt():
Missing type annotation, docstring, and unit test.
Probably a better name can be used.

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +# ToDo make tests. The following should work (from RUFAS/ dir)
For a TODO, please create a git issue and mentioned it here. Also, for a block of comment, it is better to use """ rather # for every line.

2022-11-08 04:14 UTC, PooyaHekmati commented on main.py
> +# !/usr/bin/env python
why not python3?

2022-11-08 04:14 UTC, PooyaHekmati commented on main.py
> +def run_rufas(in_path=None, make_graphs=True, verbose=True):
Why do we need to rename the main function?

2022-11-08 04:14 UTC, PooyaHekmati commented on main.py
> +def run_rufas(in_path=None, make_graphs=True, verbose=True):
Missing type annotation, unit tests. Incomplete and incorrect docstring.

2022-11-08 04:14 UTC, PooyaHekmati commented on main.py
> +    """ main function to run RuFaS, with options. If in_file is not provided, the interactive user prompt is triggered
There is no "in_file" here. If it is referring to _in_path, I think it can have a better name.

2022-11-08 04:14 UTC, PooyaHekmati commented on main.py
> +    """set values of global variables in config/global_variables.py"""
docstrings explain the function, so we write them in third person (set vs sets)

2022-11-08 04:14 UTC, PooyaHekmati commented on main.py
> +    config.global_variables.SUPPRESS_GRAPHICS = not make_graphs
Just a thought: why not calling it PRODUCE_GRAPHICS? It has one less letter and removes all those negations in the code.

2022-11-08 04:14 UTC, PooyaHekmati commented on main.py
> +def print_rufas_intro() -> None:
I don't think we need a function for this; it's just a print...

2022-11-08 04:14 UTC, PooyaHekmati commented on main.py
> +    """execute simulations for each file"""
Can we use this docstring as the function name?

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +        if not input_path.is_file():
if we swap these two if conditions (first check if it is a file, then check if its type), then we can combine txt and json logics and remove some repetitions. Also, input_path.is_dir() can be the else statement.

2022-11-08 04:14 UTC, PooyaHekmati commented on main.py
> +    parser.add_argument("--no-graphics", help="prevent graphics from generating", action="store_true")
```suggestion
    parser.add_argument("-ng", "--no-graphics", help="prevent graphics from generating", action="store_true")
```

2022-11-08 04:14 UTC, PooyaHekmati commented on main.py
> +    parser.add_argument("in_path", type=str, metavar="path", nargs="?",
```suggestion
    parser.add_argument("input_path", type=str, metavar="path", nargs="?",
```

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/simulation_engine.py
> +            sys.stdout.write(f"Total Run Time: {total_runtime} seconds\n")
```suggestion
        sys.stdout.write(f"Total Run Time: {total_runtime} seconds\n")
        if not config.global_variables.SUPPRESS_GRAPHICS:
            sys.stdout.write(f"Time to produce graphics: {graphics_prod_time}\n")
            sys.stdout.write(f"Output Successful.\nGraphics stored in: {self.config.graphic_dir}\n")
        else:
            sys.stdout.write("Graphics were suppressed.\n")
       
```

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +    # check for global message flag
```suggestion
```

2022-11-08 04:14 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +        raise errors.UserInput("Invalid Input")
```suggestion
    if input_path.is_file():
        if input_path.suffix not in ['.txt', '.json']:
            raise errors.UserInput("The input file must be either txt or json.")
            
        if input_path.suffix == '.txt':
            if be_verbose:
                print("commented json file detected, stripping comments...\n")
            json_filename = fileReader.convert_to_json(str(input_path))
            json_path = Path(json_filename.strip())
            return [json_path]
            
        if input_path.suffix == '.json':
            if be_verbose:
                print("json file detected...\n")
            return [input_path]
        
    elif input_path.is_dir():
        # Grab all json files in dir
        path_list = list(input_path.glob('*.json'))
        if len(path_list) < 1:
            raise errors.UserInput("Directory contains no json files")
        if be_verbose:
            print(f"{len(path_list)} json files detected...\n")
        return path_list

    else:
        raise errors.UserInput("Invalid Input")
```

2022-11-08 04:19 UTC, PooyaHekmati commented
For future ref: I spent 75 minutes reviewing this PR.

2022-11-08 16:37 UTC, JoeWaddell approved these changes

2022-11-08 16:37 UTC, JoeWaddell commented on main.py
> +# !/usr/bin/env python
Is the potential for error here that a system with an older (pre 3.0) version of Python could use the wrong PATH?

2022-11-08 16:37 UTC, JoeWaddell commented on main.py
> +    config.global_variables.SUPPRESS_GRAPHICS = not make_graphs
There's even neurophysiological justification for using "affirmative" statements instead of "negation" whenever possible. There are a few studies about how even with a simple evaluation of "is blue" versus "not blue" - the latter takes (roughly) twice as long in human brains. Apologies if tangents like this are poor form in code reviews, but it sparked some thought on how we can keep the code simple, but also make it more rapidly understandable to human reviewers. 
All that said, I can see the logic in requiring an argument specifically to suppress graphics, since the default behavior would presumably be _to_ produce graphics. Of course this can be handled via default values if no user input is provided to request otherwise (as is already handled in the new code, but in reverse).

2022-11-08 16:37 UTC, JoeWaddell commented on main.py
> +    parser.add_argument("--no-graphics", help="prevent graphics from generating", action="store_true")
For my own clarification: is the addition of "-ng" to specify an abbreviation for the "--no-graphics" argument?

2022-11-08 16:55 UTC, morrowcj commented on main.py
> +    parser.add_argument("--no-graphics", help="prevent graphics from generating", action="store_true")
@PooyaHekmati, good call!

@JoeWaddell, Yes, it allows for use of either `-ng` or `--no-graphics` to achieve the same behavior.

2022-11-08 17:10 UTC, morrowcj commented on RUFAS/simulation_engine.py
> +            sys.stdout.write(f"Total Run Time: {total_runtime} seconds\n")
This edit causes the total run time to be printed twice when no graphics are produced: once for "Total Simulation Time" (`simulate()`) and then again here, since "Total Run Time" is "Total Simulation Time" plus the graphics time (which is 0).

2022-11-08 17:41 UTC, morrowcj commented on RUFAS/user_prompt.py
> +def get_files_from_input(path=None, verbose=True):
I've renamed, documented, and typed this function (I'll commit all changes together) but I think I need help writing the test. I can't figure out how to mock the functions and count their calls. Should I ask Loi for help here?

2022-11-08 18:41 UTC, morrowcj commented on RUFAS/user_prompt.py
> +        if not input_path.is_file():
Does anyone use the .txt option? I think it makes the most sense to just remove that functionality and enforce use of .json files for consistency.  What do we think of that?

2022-11-08 18:50 UTC, morrowcj commented on RUFAS/user_prompt.py
> +        raise errors.UserInput("Invalid Input")
I decided to refactor this whole section, since I was in it anyway. It'll be in the next commit.

2022-11-08 18:53 UTC, JoeWaddell commented on RUFAS/user_prompt.py
> +        if not input_path.is_file():
I haven't used the txt option, no. I agree with you that it makes sense to force folks to use json, because I can't think of cases in which it might be beneficial.

2022-11-08 19:39 UTC, morrowcj commented on RUFAS/user_prompt.py
> +# ToDo make tests. The following should work (from RUFAS/ dir)
In my IDE, the TODO block only stands out if it follows a `#`. This makes it more difficult to see them if they are in `"""` blocks, but I can absolutely make this change if you feel strongly about it.

2022-11-08 19:43 UTC, morrowcj commented on main.py
> +# !/usr/bin/env python
I thought that it needed to be this way. I know that `# !/usr/bin/python3` is not the preferred method because the executable is not in a standardized location. I did not know that `# !/usr/bin/env python3` was valid - but I think it is probably preferable.

@JoeWaddell, yes, if the user's **default** python (on PATH) is python2, for example, it wouldn't work.

2022-11-08 19:47 UTC, morrowcj commented on main.py
> +def run_rufas(in_path=None, make_graphs=True, verbose=True):
We don't **need** to, but I did it so that users calling the funciton from python could have a more descriptive name. 

```python
from MASM import *

main(...)
```

doesn't quite flow as well as 

```python
from MASM import *

run_rufas(...)
```

Even though this is a niche use case, I wanted to allow for it. Also, my understanding was that true "main" functions aren't supposed to accept arguments (as in C)

I can revert if you'd prefer.

2022-11-08 19:53 UTC, morrowcj commented on main.py
> +    config.global_variables.SUPPRESS_GRAPHICS = not make_graphs
This is an excellent idea. I originally did it this way because I wanted it to match the GNU flag convention of naming the options such that they alter the default functionality (i.e., `--no-graphics` turns off the graphics which are on by default). But there is no real reason that the global variable needs to have the same grammar as the flag.

Thanks!

2022-11-08 20:27 UTC, morrowcj commented
@PooyaHekmati, I implemented all the changes that you suggested except where I made comments to the contrary above. 

I also refactored `user_prompt.py` a bit further and added some place-holder tests for functions this file. I have not been able to figure out how to write good tests for most of these functions yet. It may be necessary to create (and clean up) files and directories to do a full test and I still have not been able to get mock to count my function calls yet. I will get to these tests ASAP.

2022-11-15 20:28 UTC, ltp23 commented
Hi Clay, overall it's a great PR. Thank you for your good work!

I think to disable the output of print statements you could create a context manager like the following and then wrap it around any block of code that may print to the console. 

```
import os
import sys
from contextlib import nullcontext

class PrintDisabler:
    """Suppresses printing to the console.

    Intended to be used with the 'with' statement.

    """
    def __init__(self):
        """Stores a reference to the original sys.stdout."""
        self.sys_stdout_ref = sys.stdout

    def __enter__(self):
        """Redirects sys.stdout to a null device."""
        sys.stdout = open(os.devnull, 'w')

    def __exit__(self, exc_type, exc_val, exc_tb):
        """Restores sys.stdout to its original value."""
        sys.stdout = self.sys_stdout_ref


def execute_simulations_from_files(files: list[Path]) -> None:
    """execute simulations for each file"""
    with PrintDisabler() if not config.global_variables.PRINT_STATUS_MESSAGES else nullcontext():
        for f in files:
            simulator = SimulationEngine(f)
            simulator.simulate()
```

2022-11-15 21:51 UTC, morrowcj reviewed
I conducted a review of my own PR to enlist some help from @ltp23. I've commented on the code sections where I'd like help writing tests.

2022-11-15 21:51 UTC, morrowcj commented on RUFAS/user_prompt.py
> +    return path_list
@ltp23, can you help me write a test for this function (`obtain_file_list()`)? I want to test that when `path is None`, then `user_prompt()` is called once and `conver_path_string_to_list()` is not called. Similarly, when `path is not None`, then the opposite occurs. 

I know that you can call `.count()` on a mocked function, but I can't figure out how to mock a function like this that is not contained in a class. Any ideas?

2022-11-15 21:51 UTC, morrowcj commented on RUFAS/user_prompt.py
> +def get_json_list_from_dir(dir_path: Path, verbose: bool) -> list[Path]:
@ltp23, I'd also like to test that file works properly.

I know that I could create directories (with `os.mkdir()`) containing files (with `pathlib.Path.touch()`). Then I could clean up by deleting anything created (with `os.rmtree()`) but I don't know if is a good idea to go messing with the file system in automated tests. What do you think?

@PooyaHekmati, I'd be interested in your opinion here as well.

2022-11-15 21:51 UTC, morrowcj commented on RUFAS/user_prompt.py
> +def prompt_user_for_input() -> str:
@ltp23, How can I write a test that user input is correctly interpreted automatically (i.e., without giving input interactively)?

2022-11-15 21:51 UTC, morrowcj commented on main.py
> +def parse_gnu_args():
@ltp23, similar to my comment about testing user input, can I also test that command-line arguments are being properly interpreted?

2022-11-21 15:53 UTC, morrowcj commented
Thank you very much, @ltp23 for these tests! I really appreciate it. I think I can write the rest myself now and understand how `patch` works much better now.

2022-11-21 23:28 UTC, ltp23 commented
Hi Clay, I'm happy to help with the rest too. Sorry, I accidentally closed and then reopened the PR.

2022-11-21 23:35 UTC, morrowcj commented
Oh, OK - cool. I definitely won't say no to your help, @ltp23. It will probably take me much longer to finish them than it would if you help. So, thank you!

2022-12-06 19:47 UTC, morrowcj commented on RUFAS/user_prompt.py
> +        print(e.msg)
This looks great and finally works, @ltp23! Thanks for addressing this.

2022-12-06 20:00 UTC, morrowcj commented on tests/test_user_prompt.py
> +    def mock_user_input_error_side_effect(*args, **kwargs):
@ltp23, are these arguments needed?

```suggestion
    def mock_user_input_error_side_effect():
```

2022-12-06 20:02 UTC, morrowcj commented on tests/test_user_prompt.py
> +                              mocker: MockerFixture) -> None:
@ltp23, it also seems that mocker is not used here. Can I remove it safely?
```suggestion
def test_set_global_variables(make_graphs: bool,
                              verbose: bool) -> None:
```

2022-12-06 20:08 UTC, morrowcj commented
@ltp23, these tests look excellent! Thank you so much for your work on this!

2022-12-07 06:00 UTC, PooyaHekmati requested changes
Please patch external dependencies; unit testing should be done in isolation.

2022-12-07 06:00 UTC, PooyaHekmati commented on tests/test_user_prompt.py
> +    dummy_dir.mkdir()
why are we not patching Path.mkdir() ?

2022-12-07 06:00 UTC, PooyaHekmati commented on tests/test_user_prompt.py
> +
Am I missing the body of this function?

2022-12-07 06:00 UTC, PooyaHekmati commented on tests/test_user_prompt.py
> +    def mock_user_input_error_side_effect(*args, **kwargs):
is this comment pending or resolved?

2022-12-07 19:57 UTC, ltp23 commented on tests/test_user_prompt.py
> +    def mock_user_input_error_side_effect(*args, **kwargs):
I believe those two arguments are required in this case and they are used internally by `pytest`.

2022-12-07 19:59 UTC, ltp23 commented on tests/test_user_prompt.py
> +                              mocker: MockerFixture) -> None:
Thank you. I removed the unused mocker parameter.

2022-12-07 20:18 UTC, ltp23 commented on tests/test_user_prompt.py
> +    dummy_dir.mkdir()
Fixed.

2022-12-07 20:27 UTC, ltp23 commented on tests/test_user_prompt.py
> +
Fixed.

2022-12-08 00:52 UTC, PooyaHekmati approved these changes
LGTM
![image](https://user-images.githubusercontent.com/51127592/206329419-9422d7e3-6d45-4a60-98dc-f262efa04415.png)

2022-12-08 16:58 UTC, morrowcj commented
> LGTM

I had to look up what this means. Thanks! I'll resolve the conflicts and merge it in.

2022-12-08 17:12 UTC, merged