[GraphGenerator] Add User Option for Setting Time on X-axis for Graphs
RuminantFarmSystems/RuFaS pull request #2143
Opened 2024-12-18 17:08 UTC by ew3361zh

Adds an user option to set the x-axis in graphs to use calendar dates instead of a simulation day counter.

### Context

Issue(s) closed by this pull request: closes #912

### What

Adds an optional boolean flag in graph filters `use_calendar_dates` to set whether they want the x-axis of their graphs to be calendar dates in the format of ordinal date (e.g. 001/2015, 229/2019). The default setting is `False` which will default the graph to plot using simulation day counter (i.e. what it currently does on dev).

### Why

This feature was requested from SMEs to have an option to see the data presented in a different manner which they said would be more helpful for results analysis.

### How

The `use_calendar_dates` flag is checked for and then sent to the GG's `_draw_graph()` method.
Within `draw_graph()`, the date range of the data to graph is determined based on the start date of the simulation from the Time class instance sent to GG.
A new helper function (`get_x_values()`) is set up within `_draw_graph()` which returns the x-axis values to match whether the user wants calendar dates or not.
Data is then plotted much the same way it was before and the only other difference is if the user does want calendar dates on the x-axis, some additional graph formatting is done to make the graph more readable.

### Test plan

Create a graph filter and try a version with `use_calendar_dates` set to `True` and then try it without that flag in the filter file.
The `True` version should have calendar dates across the x-axis.
Every other version should have the simulation day counter as before.

my example filter file:
`graph_tester.json`

```
{
    "type": "plot",
    "filters": [
      ".*ammonia_emissions.*"
    ],
    "title": "Ammonia Emissions",
    "use_calendar_dates": true
}
```
<img width="1257" alt="Screenshot 2024-12-18 at 12 06 47 PM" src="https://github.com/user-attachments/assets/20f2ed87-8e19-4777-b73c-eeb3824bc003" />

And then the default version without specifying the `use_calendar_dates` flag or setting it to `False`:
<img width="1257" alt="Screenshot 2024-12-18 at 12 10 37 PM" src="https://github.com/user-attachments/assets/cd00b388-961a-48e1-a712-2d8203d47749" />

2024-12-18 17:14 UTC, ew3361zh commented on RUFAS/graph_generator.py
> -        selected_variables: Optional[List[str]] = None,
This list won't be optional ever since we're pulling out variables to graph based on the filter and using them as `selected_variables` even if the user doesn't specify `selected_variables` in the output filter.

2024-12-18 19:48 UTC, ew3361zh commented on RUFAS/graph_generator.py
> -    "constrained_layout": Figure.set_constrained_layout,
This along with the other Figure import below were not recognized as viable imports from matplotlib.Figure by MyPy.

2024-12-18 19:52 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +            plt.xlabel("Simulation Day")
Initially thought about adding the units to the y-axis automatically but remembered there are times where the variables graphed can have different units. This is why we decided to add the units to the variables in the legend instead (ages ago).

2024-12-19 16:33 UTC, Isgotkowitz reviewed
This is an excellent start to having dates on the x-axis Niko! I left some comments on more minor things.

There are some edge cases that should be accounted for though, either by warning the users or adjusting the dates displayed.

The first is if the data is sliced in some way, the first date and last dates on the axis do not necessarily match up with the start and end dates of the simulation. To exemplify this, try:
```json
{
    "type": "plot",
    "filters": [
      ".*ammonia_emissions.*"
    ],
    "title": "Ammonia Emissions",
    "slice_start": -365,
    "slice_end": -1,
    "use_calendar_dates": true
}
```
I think this edge case can be addressed in the code.

Another edge case that I think can't be addressed in the code is if data is non-consecutive i.e. there are one or more days in between values. If this can't be addressed in the code, I think it would be good to at least warn users that this is one of the limitations of the graph generator.

2024-12-19 16:33 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> -    "constrained_layout": Figure.set_constrained_layout,
Huh interesting.

2024-12-19 16:33 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +            ax.xaxis.set_major_formatter(mdates.DateFormatter("%j/%Y"))
Instead of using the day of year (1 - 365/366), I think it would be better to use a format that specifies the month and day of the month. I'm not sure why DOY was used initially for so many things in RuFaS, but I think most users would prefer a more standard date format instead.

2024-12-19 16:33 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +            return dates_in_data_range[:values_length] if use_calendar_dates else list(range(values_length))
I like the deduplication of code, but I don't think functions within functions are kosher from a clean code standpoint. Maybe it would work as a lambda function?

2024-12-19 16:33 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +        ax: Axes,
```suggestion
        ax: Axes | None,
```
Does this need to be None as well?

2024-12-20 14:44 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +            return dates_in_data_range[:values_length] if use_calendar_dates else list(range(values_length))
My original thought was to create this function outside the function but it was so specific that it seemed like nesting it was simpler and cleaner. I did read up on nested functions and couldn't find anything explicitly saying they were a bad practice or weren't within the guidelines of clean code.

Do you have any references on the matter?

I personally think lambda functions are less readable/understandable than regular functions but it is just my preference.

2024-12-20 14:46 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +        ax: Axes,
If this is a reference to the docstring param notes, I removed the `default None` from the Axes section. Or were you seeing a warning in VS Code/MyPy somewhere about it? I think because of the way it's set up in the parent function, it wouldn't ever be None.

2024-12-20 14:47 UTC, ew3361zh commented
> Another edge case that I think can't be addressed in the code is if data is non-consecutive i.e. there are one or more days in between values. If this can't be addressed in the code, I think it would be good to at least warn users that this is one of the limitations of the graph generator.

@Isgotkowitz Do you have an example filter for this by any chance?

2024-12-20 14:48 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +            ax.xaxis.set_major_formatter(mdates.DateFormatter("%j/%Y"))
Curious what @JoeWaddell's opinion on this is as well. I'm not sure I have strong feelings one way or another.

2024-12-20 20:17 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +            return dates_in_data_range[:values_length] if use_calendar_dates else list(range(values_length))
> Do you have any references on the matter?

No, it just throws me for a loop whenever I see `def` nested inside a `def`. But I think you make a good case for using a nested function

2024-12-20 20:21 UTC, Isgotkowitz commented
> > Another edge case that I think can't be addressed in the code is if data is non-consecutive i.e. there are one or more days in between values. If this can't be addressed in the code, I think it would be good to at least warn users that this is one of the limitations of the graph generator.
> 
> @Isgotkowitz Do you have an example filter for this by any chance?

An example would be the ration formulation, because that data is only collected once per ration interval. I'll work on putting together a filter for it.

Edit: so the ration data that I could filter out is padded, as far as I could tell. AFAIK there isn't any data like this currently coming out of RuFaS, but it is important that we keep this in mind as something that would complicate setting the dates on the x-axis correctly

2024-12-20 20:51 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +        ax: Axes,
Gotcha, it was a reference to the docstring. I didn't see any warnings about it

2024-12-23 19:12 UTC, ew3361zh commented
Updates/responses to feedback:
1. Handles and properly assigns dates on x-axis to sliced data.
2. Adds function to Time class to convert a slice start or slice end to its corresponding simulation day.
3. Adds date formatting option to graph filter:
- `day_of_year` which would look like 234/2022
- `day_month_year` which would look like 23/12/2024
- default is `day_month_year` as requested (sort of) by @Isgotkowitz and @JoeWaddell

To test, here's a twofer example filter:
```
{
  "type": "plot",
  "filters": [
    ".*daily.*ammonia_emissions.*"
  ],
  "title": "Ammonia Emissions",
  "slice_start": -365,
  "slice_end": -1,
  "use_calendar_dates": true,
  "date_format": "day_month_year"
}
```

2024-12-23 22:21 UTC, Isgotkowitz reviewed
Nice! I think this looks awesome Niko. I left some suggestions about how the date feature could be improved, but those can wait for future expansion if you think they'd be too much to include in this PR.

Not approving right now because of two things: it looks like Matthew's PR got mixed up in here, and also the filter in your comment isn't working for me unfortunately. I get the error message "[23-Dec-2024_Mon_17-20-00.281182][ERROR][default] Error plotting 'Ammonia Emissions' data set. Unforeseen error max() arg is an empty sequence when trying to graph data." and no graph is printed

2024-12-23 22:21 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +            "day_month_year": "%d/%m/%Y",
European-style, I like it.

What would you think of making this an enum and putting it in a higher level module? My thought is that we may want to expand the range of options for date formats, and there may be other, higher-level modules which the user will want to configure to use a specific date format.

Also, for the graph generator, what about making it possible for users to select one of the pre-configured options (like the ones you have here) or inputting their own custom date format (i.e. a string with letters and percent symbols wherever they want)? This could be a good opportunity to dry-run an input like this, before we start trying to do something like this with dates in the inputs.

2024-12-24 15:30 UTC, ew3361zh commented
> Not approving right now because of two things: it looks like Matthew's PR got mixed up in here, 

Rebased and Matthew's stuff is gone.

> and also the filter in your comment isn't working for me unfortunately. I get the error message "[23-Dec-2024_Mon_17-20-00.281182][ERROR][default] Error plotting 'Ammonia Emissions' data set. Unforeseen error max() arg is an empty sequence when trying to graph data." and no graph is printed

I think the github markdown formatting replaced a `*` in the filter with italics style...should have done it as code, apologies! (editor's note: original version above is fixed as well)

Here is the correct version:

```
{
  "type": "plot",
  "filters": [
    ".*daily.*ammonia_emissions.*"
  ],
  "title": "Ammonia Emissions",
  "slice_start": -365,
  "slice_end": -1,
  "use_calendar_dates": true,
  "date_format": "day_month_year"
}
```

2024-12-24 15:34 UTC, ew3361zh commented on RUFAS/graph_generator.py
> +            "day_month_year": "%d/%m/%Y",
> What would you think of making this an enum and putting it in a higher level module? My thought is that we may want to expand the range of options for date formats, and there may be other, higher-level modules which the user will want to configure to use a specific date format.

Yea, I can write this up as an issue after this is merged if that works for you.

> Also, for the graph generator, what about making it possible for users to select one of the pre-configured options (like the ones you have here) or inputting their own custom date format (i.e. a string with letters and percent symbols wherever they want)? This could be a good opportunity to dry-run an input like this, before we start trying to do something like this with dates in the inputs.

I feel like custom date format could be an option we put in the enum. I find date formatting pretty unintuitive and always have to look these up so I could see some people struggling with it but there are enough resources available online that I think it wouldn't be too difficult to create the format they want.

2024-12-24 15:50 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +            "day_month_year": "%d/%m/%Y",
Works for me!

2024-12-24 15:50 UTC, Isgotkowitz approved these changes
LGTM! Nice job Niko

2025-01-02 16:24 UTC, JoeWaddell commented on RUFAS/graph_generator.py
> +            ax.xaxis.set_major_formatter(mdates.DateFormatter("%j/%Y"))
We talked on Slack, but to summarize: I like both options! Some inputs assume the day of the year (crop especially), but that's also not as easily readable to a general audience as having the actual months. The later (in this PR) addition to allow for both is excellent, since each serves different needs!

2025-01-02 16:59 UTC, JoeWaddell requested changes
Looks great! Just holding off because I can't get the `day_month_year` option to work: it's only using the `day_of_year`. Tried both default, and explicitly calling both separately. Looking through the code again...

UPDATE: false alarm, it works! Weird git issue on my end - had to switch branches, then pull again...it hadn't pulled in all changes (despite pulling it in from remote first thing this morning...)

2025-01-02 17:05 UTC, JoeWaddell approved these changes

2025-01-02 17:47 UTC, merged