Initial Output Manager Pool Population
RuminantFarmSystems/RuFaS pull request #218
Opened 2022-11-24 01:51 UTC by ew3361zh

- Added a first round of variables, warnings, and errors to Output Manager pools
- Primarily based on searches for print statements in the code with the idea that the Output Manager will eventually replace the need for those print statements.
- Created a (temporary) `print_pools` method in the OutputManager class which is called at the end of a simulation to show OutputManager is indeed collecting data being sent to it and will show some examples of how that raw data looks in the pools (and after prefixes/suffixes have been appended). This method will almost definitely not stick around but I found it useful in seeing the Output Manager's pool collection system in action.

2022-11-26 05:32 UTC, PooyaHekmati requested changes
As we have discussed in our meetings, these need to be addressed:

1. Import statements should be sorted in a-z order, so change the following (and similar cases)
`from RUFAS.util import Utility`
`from RUFAS.output_manager import OutputManager`
to
`from RUFAS.output_manager import OutputManager`
`from RUFAS.util import Utility`
3. Avoid using hard-coded values (see the example below)
4. Avoid using long lines (a line shouldn't be longer than 99 chars, preferably less than 79 chars)
5. Avoid adding new print statements
6. Signals on the PR are failing (linting failed), which needs to be fixed
7. info_map is meant to capture environment variables to have reproducible results, warnings, and errors. Just adding caller_class and caller_function is the bare minimum and is NOT a good practice. 
8. When adding errors and warnings, remove the corresponding print statements.
9. A PR should move the code base toward being production-ready. If a temporary code snippet is added, a proper plan should be devised for its removal. This plan has to be documented using git issues (needs to be mentioned as a TODO in the code) and communicated in the PR description.
10. Practical examples of output manager usage are available in the output_manager.py and its corresponding test cases; here is another example:
`from RUFAS.output_manager import OutputManager`
`om = OutputManager()`
`class foo (object):`
`    def bar(self, arg1, arg2):`
`        info_map={'caller_class': self.__class__.__name__,`
`                 'caller_function': self.bar.__name__,`
`                 'arg1':arg1,`
`                 'arg2':arg2,`
`                 }`
`        om.add_log('example_log',`
`                    'This is an example to demonstrate how'`
`                    +' a long string should be created and sent'`
`                    +' to output manager. Notice that + signs'`
`                    +' are at the beginning of each new line'`
`                    +' rather at the end of last line. This'`
`                    +' enhances readability and reduces confusion.',`
`                    info_map)`         
`        variable_x = some value`
`        variable_y = something else`
`        some logic that changes x and y`
`        om.add_variable('variable_x',variable_x,info_map)`
`        some logic that leads to a situation that needs user's attention`
`        info_map['variable_x']=variable_x`
`        info_map['variable_y']=variable_y`
`        om.add_warning('exmaple_warning',`
`                       'The values of x and y are not making sense!',`
`                       info_map)`
`        #now that we have added x and y to the info_map, moving forward,`
`        #they will always be logged. This may not be desired as it can lead`
`        #to a situation where there are so many keys in the info_map which`
`        #makes debugging difficult. To avoid this, instead of adding x and y`
`        #to info map, we could first call add_variable for them and then`
`        #add the warning without adding them to the info map. If this path`
`        #is used, then the warning message should clearly point out that the`
`        #last values of x and y led to this warning. Alternatively, we can`
`        #create a new info_map. Note that the name of this dict can be anything,`
`        #doesn't need to be info_map. We can also use the pop() method to remove`
`        #a key from a dict e.g., info_map. The samething applies to errors as well.`

2022-11-28 15:09 UTC, ew3361zh commented
> As we have discussed in our meetings, these need to be addressed:
> 
> 1. Import statements should be sorted in a-z order, so change the following (and similar cases)
>    `from RUFAS.util import Utility`
>    `from RUFAS.output_manager import OutputManager`
>    to
>    `from RUFAS.output_manager import OutputManager`
>    `from RUFAS.util import Utility`
> 2. Avoid using hard-coded values (see the example below)
> 3. Avoid using long lines (a line shouldn't be longer than 99 chars, preferably less than 79 chars)
> 5. Signals on the PR are failing (linting failed), which needs to be fixed
> 7. When adding errors and warnings, remove the corresponding print statements.

I will fix these today (and going forward).

> 4. Avoid adding new print statements
> 8. A PR should move the code base toward being production-ready. If a temporary code snippet is added, a proper plan should be devised for its removal. This plan has to be documented using git issues (needs to be mentioned as a TODO in the code) and communicated in the PR description.

I believe the only print statements added were for the temporary print_pools function which was added for the benefit of the reviewers to see what the gathered data would look like and have the option to provide feedback on whether that was capturing the data as they'd hoped. It's noted in the PR these will be removed prior to merging but I will add a git issue and in-code TODO statements as well.

> 6. info_map is meant to capture environment variables to have reproducible results, warnings, and errors. Just adding caller_class and caller_function is the bare minimum and is NOT a good practice.

Ok, this was a misunderstanding of the purpose of the info_map on my part. Perhaps we can discuss further in our check-in as I have some follow-up questions to what is explained in the example (9) below.

> 9. Practical examples of output manager usage are available in the output_manager.py and its corresponding test cases; here is another example:
>    `from RUFAS.output_manager import OutputManager`
>    `om = OutputManager()`
>    `class foo (object):`
>    `    def bar(self, arg1, arg2):`
>    `        info_map={'caller_class': self.__class__.__name__,`
>    `                 'caller_function': self.bar.__name__,`
>    `                 'arg1':arg1,`
>    `                 'arg2':arg2,`
>    `                 }`
>    `        om.add_log('example_log',`
>    `                    'This is an example to demonstrate how'`
>    `                    +' a long string should be created and sent'`
>    `                    +' to output manager. Notice that + signs'`
>    `                    +' are at the beginning of each new line'`
>    `                    +' rather at the end of last line. This'`
>    `                    +' enhances readability and reduces confusion.',`
>    `                    info_map)`
>    `        variable_x = some value`
>    `        variable_y = something else`
>    `        some logic that changes x and y`
>    `        om.add_variable('variable_x',variable_x,info_map)`
>    `        some logic that leads to a situation that needs user's attention`
>    `        info_map['variable_x']=variable_x`
>    `        info_map['variable_y']=variable_y`
>    `        om.add_warning('exmaple_warning',`
>    `                       'The values of x and y are not making sense!',`
>    `                       info_map)`
>    `        #now that we have added x and y to the info_map, moving forward,`
>    `        #they will always be logged. This may not be desired as it can lead`
>    `        #to a situation where there are so many keys in the info_map which`
>    `        #makes debugging difficult. To avoid this, instead of adding x and y`
>    `        #to info map, we could first call add_variable for them and then`
>    `        #add the warning without adding them to the info map. If this path`
>    `        #is used, then the warning message should clearly point out that the`
>    `        #last values of x and y led to this warning. Alternatively, we can`
>    `        #create a new info_map. Note that the name of this dict can be anything,`
>    `        #doesn't need to be info_map. We can also use the pop() method to remove`
>    `        #a key from a dict e.g., info_map. The samething applies to errors as well.`

2022-11-29 16:10 UTC, ew3361zh commented
@PooyaHekmati if you could review again, I believe I've addressed the changes requested

2022-11-29 16:28 UTC, morrowcj reviewed
This looks good. I looked through the changes to see how you were using the output manager in practice. I won't formally approve, since I think it is probably important for someone from the animal management team to do so.

2022-11-30 16:21 UTC, PooyaHekmati reviewed
LGTM from a code quality perspective. I have some comments and questions, waiting for the author's response.

2022-11-30 16:21 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +from pprint import pprint
Is this still needed?

2022-11-30 16:21 UTC, PooyaHekmati commented on RUFAS/routines/animal/animal_management.py
> +                             {'caller_class': 'AnimalManagement', 'caller_function': 'init_pens'})
Avoid using hardcoded values

2022-11-30 16:21 UTC, PooyaHekmati commented on RUFAS/simulation_engine.py
> +        total_simulation_time = t_end_sim - t_start_sim
```suggestion
        total_simulation_time = t_end_sim - t_start_sim
        print(f"Total Simulation Time: {total_simulation_time } seconds")
```

2022-11-30 16:21 UTC, PooyaHekmati commented on RUFAS/simulation_engine.py
> +        om.add_variable('total_simulation_time', total_simulation_time, info_map)
I think this is more of a log than a variable

2022-11-30 16:21 UTC, PooyaHekmati commented on RUFAS/simulation_engine.py
> +        om.add_variable('graphics_prod_time', graphics_prod_time, info_map)
Same, can this be a log?

2022-11-30 16:21 UTC, PooyaHekmati commented on RUFAS/simulation_engine.py
> +        om.add_variable('total_runtime', total_runtime, info_map)
log?

2022-11-30 16:21 UTC, PooyaHekmati commented on RUFAS/simulation_engine.py
> +        om.add_variable('simulation_initialization_file_path', file_path, info_map)
log?

2022-11-30 16:21 UTC, PooyaHekmati commented on RUFAS/simulation_engine.py
> +        om.add_variable('simulation_initialization_file_path', file_path, info_map)
@JoeWaddell What are your thoughts here? When running bulk simulations, are these variables or logs?

2022-11-30 16:21 UTC, PooyaHekmati commented on RUFAS/user_prompt.py
> +om = OutputManager()
I don't see any usage of output manager here, do we need this?

2022-11-30 16:21 UTC, PooyaHekmati commented on RUFAS/util.py
> +om = OutputManager()
same, no usage

2022-11-30 16:28 UTC, JoeWaddell commented on RUFAS/simulation_engine.py
> +        om.add_variable('simulation_initialization_file_path', file_path, info_map)
Great question: I could be convinced either way, but I think in my particular case saving it as a variable would be useful in my workflow. 
When I run simulations I use a key that associates the runs with a given suite of input parameters. Having the `file_path` saved as a variable could be useful to print in an output, just to ensure that things aren't getting mixed up when moving/copying files. 
I could also see it being useful to keep this as a variable for users who might want to run multiple simulations testing different scenarios: could help avoid problems from sloppy file management after the fact.

2022-11-30 16:31 UTC, JoeWaddell commented on RUFAS/user_prompt.py
> +om = OutputManager()
I was going to ask about this section as well (was reviewing it as these comments came in). Further down in this file, the `info_map` is set, but not used. I assumed it is a placeholder for adding logs/warnings, or somehow being used in a way that eluded me.

2022-11-30 16:38 UTC, JoeWaddell reviewed
Nice work! I've folded the couple comments I had into replies to Pooya's, as this all looks good otherwise. Seems like a nice demonstration of how this will work moving forward.

2022-11-30 16:42 UTC, PooyaHekmati commented on RUFAS/simulation_engine.py
> +        om.add_variable('simulation_initialization_file_path', file_path, info_map)
Thanks @JoeWaddell . What about 'total_runtime', 'total_simulation_time', and 'graphics_prod_time' ? See the comments above. Do you see them as logs or variables?

2022-11-30 16:50 UTC, JoeWaddell commented on RUFAS/simulation_engine.py
> +        om.add_variable('simulation_initialization_file_path', file_path, info_map)
@PooyaHekmati : for my own purposes, I think I'd treat those as logs. 
Likewise, for a typical user, I can't think of a good reason to treat them as variables. 
For advanced users who want to explore the runtimes for different farm sizes or longer time periods, I imagine checking the logs should be sufficient in those cases.

2022-11-30 18:16 UTC, ew3361zh commented on RUFAS/output_manager.py
> +from pprint import pprint
no longer needed, deleted.

2022-11-30 18:17 UTC, ew3361zh commented on RUFAS/routines/animal/animal_management.py
> +                             {'caller_class': 'AnimalManagement', 'caller_function': 'init_pens'})
switched to info_map variable to match other usages

2022-11-30 18:17 UTC, ew3361zh commented on RUFAS/simulation_engine.py
> +        total_simulation_time = t_end_sim - t_start_sim
addressed this in the commit for all the fixes suggested.

2022-11-30 18:19 UTC, ew3361zh commented on RUFAS/simulation_engine.py
> +        om.add_variable('total_simulation_time', total_simulation_time, info_map)
agreed, switched method to add_log

2022-11-30 18:19 UTC, ew3361zh commented on RUFAS/simulation_engine.py
> +        om.add_variable('graphics_prod_time', graphics_prod_time, info_map)
agreed, switched method to add_log

2022-11-30 18:19 UTC, ew3361zh commented on RUFAS/simulation_engine.py
> +        om.add_variable('total_runtime', total_runtime, info_map)
switched method to add_log

2022-11-30 18:22 UTC, ew3361zh commented on RUFAS/simulation_engine.py
> +        om.add_variable('simulation_initialization_file_path', file_path, info_map)
With the calculated times being added as logs are you both okay with eliminating the call to _show_final_messages() at the end of the simulate method?

2022-11-30 18:25 UTC, ew3361zh commented on RUFAS/user_prompt.py
> +om = OutputManager()
Thank you, Joe and Pooya! These were leftovers from my initial run through when I was adding the raised errors to the errors pool but after discussions with Pooya it was decided that this was not a useful type of error to be included.

2022-11-30 18:25 UTC, ew3361zh commented on RUFAS/util.py
> +om = OutputManager()
It has been removed.

2022-11-30 19:32 UTC, PooyaHekmati commented on RUFAS/simulation_engine.py
> +        om.add_variable('simulation_initialization_file_path', file_path, info_map)
I think it is better to leave it as is for now. We will come back and revisit these kinds of issues later.

2022-11-30 19:33 UTC, PooyaHekmati approved these changes

2022-11-30 20:45 UTC, JoeWaddell approved these changes

2022-11-30 21:27 UTC, merged