root development refactor
RuminantFarmSystems/RuFaS pull request #225
Opened 2022-11-30 22:09 UTC by morrowcj

This pull request involves the refactoring of the crop root development processes. It is a small PR and involves only a handful of functions.

The main change in this PR is [root_development.py](SC_redesign/Crop_and_Soil/crop/root_development.py) and associated tests: [test_root_development.py](SC_redesign/Crop_and_Soil/tests_SC/test_root_development.py). With this PR, I've used the pattern suggested to me by @ltp23, which I think works well. 

This PR follows #224. Review of this PR should probably wait until #224 is merged into SC_redesign.

2022-12-12 18:25 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop.py
>  # TODO: Should use an ENUM class to represent the supported species??
Sounds like a good idea, but this require extra code to update the ENUM every time a new crop species is added right?

2022-12-12 18:43 UTC, Isgotkowitz reviewed
Adding the SWAT reference in `root_development.py` is the only thing I think should be changed, otherwise LGTM

2022-12-12 18:43 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/root_development.py
> +
```suggestion

SWAT Reference: 5:2.1.23, 24

```

2022-12-12 18:47 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop.py
>  # TODO: Should use an ENUM class to represent the supported species??
I'm not sure. I don't fully understand ENUMs yet. It is something I want to learn more about (perhaps you can enlighten me a bit) before moving forward. I did a small amount of reading on the pattern and it seemed useful for what I'm planning. We'll need to re-evaluate later when we start working on the details of the `Crop` class.

2022-12-12 18:49 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/root_development.py
> +
Good catch, thanks!

2022-12-12 20:35 UTC, Isgotkowitz approved these changes

2022-12-12 20:40 UTC, Isgotkowitz requested changes

2022-12-12 20:40 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +    def list_all_var_names(self):
This function needs a return type

2022-12-12 20:40 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop.py
>  # TODO: Should use an ENUM class to represent the supported species??
Ok, I'm not sure how ENUMs work in Python so I will have to do some learning too.

2022-12-12 22:25 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +    def list_all_var_names(self):
Done. Thanks

2022-12-14 16:30 UTC, Isgotkowitz approved these changes

2022-12-15 00:45 UTC, ltp23 commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +        return vars(self)
I believe `vars(obj)` returns a dictionary, so if you want a list, then use `list(vars(obj).keys())` or `list(vars(obj).values())` depending on what makes sense to you.

2022-12-15 00:54 UTC, ltp23 approved these changes
Everything looks great! Thanks for your work.

2022-12-15 19:18 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +        return vars(self)
No, I think returning a dictionary makes more sense. I'll fix it and then merge.

2022-12-15 19:29 UTC, merged