LAI rewrote helper methods as static functions inside class
RuminantFarmSystems/RuFaS pull request #234
Opened 2022-12-12 17:42 UTC by Isgotkowitz

Moved helper functions from outside the LeafAreaIndex class inside and made them `@staticmethod`'s, and changed tests accordingly

Edit: changed senescence flag to get rid of redundancy

2022-12-12 17:59 UTC, morrowcj requested changes
There are a few small issues with the is_in_senescence property that I think need to be addressed.

2022-12-12 17:59 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/leaf_area_index.py
> +    def check_for_senescence(self) -> bool:
How about this?
```suggestion
    def is_in_senescence(self) -> bool:
```

2022-12-12 17:59 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/leaf_area_index.py
> +    def check_for_senescence(self) -> bool:
Also, consider changing line 48. Is the default starting value `False` actually needed?

2022-12-12 17:59 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/leaf_area_index.py
> +        self.is_in_senescence = self.check_for_senescence
I believe that `@property` functions don't need to be assigned to variables.
```suggestion
        self.is_in_senescence
```

2022-12-12 17:59 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/tests_SC/test_leaf_area_index.py
>          assert lai.is_in_senescence is True
might need to change this line (and 166 above) to reflect my suggestions in previous comments.

2022-12-12 18:17 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/test_leaf_area_index.py
>          assert lai.is_in_senescence is True
Made suggested changes to `is_in_senescence` and all tests passing

2022-12-12 18:37 UTC, morrowcj requested changes
This is a more thorough review, after the example review that we walked through together. I've left a few more in-line comments on the code and have a few more general comments below. Once these issues are addressed, I'll approve the PR. 

## General comments:

* I think that `determine_canopy_height()` should be converted to a static function. `shift_leaf_area_time()` and
`check_previous_leaf_area_values()`can remain as regular methods. 

* Type declarations:  on line 33, `grow_canopy()` needs a function type declaration (i.e., void function: `-> None`). 
Check the remaining functions as well - `shift_leaf_area_time()`, `determine_canopy_height()`, and
`check_previous_leaf_area_values()` all need typing. Caution: they won't all be void functions if you address the
previous bullet first.

* I know this is nit-picky, but can we organize the code so that the static functions are grouped together at the bottom of
the class?

2022-12-12 18:37 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/leaf_area_index.py
> +        self.is_in_senescence = self.check_for_senescence
I actually think I was wrong - after looking at the code in its entirety, I think this line can just be deleted. The next line (45) contains the code `if self.is_in_senescence:`, which will automatically check via the `@property` (I think).

2022-12-12 18:37 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/leaf_area_index.py
> +                             first_leaf_fraction: float, second_leaf_fraction: float) -> List[float]:
Should this be a "private" function (preceded with an underscore)? I don't think LAI shapes will ever be used outside of the class.

2022-12-12 18:37 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/leaf_area_index.py
> +
I'd like to update this todo
```suggestion
        # TODO: need to add any of these errors that get thrown when RuFaS runs to the  `OutputManager`. 
        #    This should probably be done in the `grow_canopy()` function 
        #    I'm still unsure how to do this effectively with warnings raised by static functions. - morrowcj
```

2022-12-12 18:37 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/leaf_area_index.py
> +        replaces method calc_optimal_leaf_area_fraction
No need for this during the redesign, but I appreciate the thoughtfulness.
```suggestion
```

go ahead and remove similar strings throughout.

2022-12-12 18:37 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/leaf_area_index.py
> +        replaces method calc_shape_parameters
```suggestion
```

2022-12-12 18:41 UTC, morrowcj commented
I've requested @ltp23 to look over this PR, since it implements some comments that you made on the last PR concerning these files.

2022-12-12 18:44 UTC, morrowcj commented
Before we merge this in, I'd also like to get @PooyaHekmati's opinion about the pattern that we've employed in this PR.

Edit: To be clear for Pooya's sake, the pattern I'm referring to is the use of static methods like so: 

```python
from math import exp

class SomeClass:
    def __init__(self):
        self.x = 1
        self.y = None

    def main_function(self) -> None:
        """update attributes and apply any logic by applying static methods"""
        self.x = self.change_x(self.x, 5)
        self.y = self.find_y(0.23)

    @staticmethod
    def change_x(x: float, plus: float) -> float:
        """performs a calculation and outputs a value"""
        return x + plus

    @staticmethod
    def find_y(power: float) -> float:
        """performs a different calculation"""
        return exp(power)
```

2022-12-12 20:13 UTC, morrowcj commented
To clarify and expand upon: 
>* Type declarations:  on line 33, `grow_canopy()` needs a function type declaration (i.e., void function: `-> None`).
>Check the remaining functions as well - `shift_leaf_area_time()`, `determine_canopy_height()`, and
>`check_previous_leaf_area_values()` all need typing. Caution: they won't all be void functions if you address the
>previous bullet first.

I simply meant that you'll need to make sure that the static function returns a float (i.e., `determine_canopy_height() -> float:`), while the others are void functions (they return nothing). Changing the typing like this should not affect the testing at all, as far as I know. 

As I'm sure you know, Python is a dynamically typed language by default but we want to suggest stricter typing, which is done by adding these type annotations to function declarations:

```python
def void_function(float_arg: float, str_arg: str, int_arg: int, bool_arg: bool, default_float_arg: float = 1.0) -> None:
  return None
```

2022-12-12 20:15 UTC, Isgotkowitz commented
> To clarify and expand upon:
> 
> > * Type declarations:  on line 33, `grow_canopy()` needs a function type declaration (i.e., void function: `-> None`).
> >   Check the remaining functions as well - `shift_leaf_area_time()`, `determine_canopy_height()`, and
> >   `check_previous_leaf_area_values()` all need typing. Caution: they won't all be void functions if you address the
> >   previous bullet first.
> 
> I simply meant that you'll need to make sure that the static function returns a float (i.e., `determine_canopy_height() -> float:`), while the others are void functions (they return nothing). Changing the typing like this should not affect the testing at all, as far as I know.
> 
> As I'm sure you know, Python is a dynamically typed language by default but we want to suggest stricter typing, which is done by adding these type annotations to function declarations:
> 
> ```python
> def void_function(float_arg: float, str_arg: str, int_arg: int, bool_arg: bool, default_float_arg: float = 1.0) -> None:
>   return NULL
> ```

Ok, I understand

2022-12-12 20:39 UTC, morrowcj approved these changes
This looks excellent! Great first PR! Thanks for your patience and let me know if you have any feedback about my reviewing process (now or in the future).

2022-12-13 21:35 UTC, ltp23 approved these changes
Overall, it looks very good and clean.

2022-12-14 16:32 UTC, merged