Heat units SC redesign
RuminantFarmSystems/RuFaS pull request #241
Opened 2022-12-14 22:58 UTC by Isgotkowitz

Redesign of Heat Units and associated tests

2022-12-15 19:17 UTC, morrowcj requested changes
Only one small request: add a few assertions to `test_accumulate_heat_units()`

2022-12-15 19:17 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/tests_SC/test_heat_units.py
> +        assert heat.new_heat_units == HeatUnits.determine_new_heat_units(temp, 15)
I think you should add assertions for all of the attributes that get changed in `accumulate_heat_units()`

For example, what should the values of `is_growing`, `heat_fraction`, `previous_heat_fraction`, `is_mature` etc. be? you can test for them by adding assertions:

```python
assert heat.new_heat_units == calc_new_heat_units(25, 15)
assert heat.is_growing = x
assert ...
```

2022-12-23 15:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/test_heat_units.py
> +        assert heat.new_heat_units == HeatUnits.determine_new_heat_units(temp, 15)
`is_growing`, `heat_fraction`, etc. are not touched by `accumulate_heat_units()`, they are only touched in `absorb_heat_units()` which was not being tested , so I wrote a separate test for just that method.

2022-12-23 16:18 UTC, morrowcj approved these changes
Looks good to me.

2022-12-23 16:18 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/tests_SC/test_heat_units.py
>      assert patch_b.assert_called_once
Good thinking for how to solve this test problem. You don't need to change anything, but for the future, I think it would've been sufficient to do:

```suggestion
def test_accumulate_heat_units(temp, mocker: MockerFixture):
    """check that accumulate_heat_units() calls the right functions"""
    patch_a = mocker.patch("SC_redesign.Crop_and_Soil.crop.heat_units.HeatUnits.assign_new_heat_units")
    patch_b = mocker.patch("SC_redesign.Crop_and_Soil.crop.heat_units.HeatUnits.add_heat_units")
    heat = init_heat()
    heat.accumulate_heat_units(temp)
    assert patch_a.assert_called_once
    assert patch_b.assert_called_once
```

since `assign_new_heat_units()` and `add_heat_units()` are tested elsewhere. Over-testing is always better than under-testing in my view, though. So, good job!

2022-12-23 16:20 UTC, morrowcj commented
I pushed a `#TODO` to remind our future selves to look here for output manager logging.

2022-12-23 16:25 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/test_heat_units.py
>      assert patch_b.assert_called_once
Thanks Clay, I will keep that in mind when looking at future tests

2022-12-23 22:16 UTC, ltp23 commented
Overall, everything looks great. 

Some minor comments:
- I really like how you document the `accumulate_heat_units()`.
- Some of the one-liner functions can just be used directly, but I understand you may want to provide more context to the code.

2022-12-23 22:16 UTC, ltp23 commented on SC_redesign/Crop_and_Soil/crop/heat_units.py
> +    def decide_to_use_heat_unit_temperature(self, use_heat_unit_temperature: bool) -> None:
This method is not really necessary. In Python, a normal instance variable can be accessed and modified directly (i.e., no need for getters and setters).

2022-12-23 22:16 UTC, ltp23 approved these changes

2022-12-23 22:50 UTC, merged