Root development wiki
RuminantFarmSystems/RuFaS pull request #263
Opened 2023-01-06 17:10 UTC by LaplacetteCM

2023-01-06 18:13 UTC, morrowcj requested changes
I think this is a good start.

2023-01-06 18:13 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/root_development.md
> +* root_fraction:
I'd give a short description of each variable here.

2023-01-06 18:13 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/root_development.md
> +```
I think that the following latex code should produce a piecewise equation we want.

```suggestion
```math
  r = 
  \left\{
    \begin(array){lr}
      ||0.4-0.2 \times h, \text{if} h < 2.0\\
      ||0, \text{otherwise}
    \end(array)
  \right\}
\```
where $r$ is `root_fraction` and $h$ is `heat_fraction`.
```

reference: https://latex-tutorial.com/piecewise-functions-latex/

## Note
You'll need to remove the `\` from the three back-ticks below the equation. I just needed to put it here so that GitHub didn't get confused.

2023-01-06 18:13 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/root_development.md
> +The main function is called **`develop_roots()`** and it is initialized with:
```suggestion
### Root development
The `RootDevelopment` class handles development of crop roots on a daily basis. The main function that carries out root development processes is called `develop_roots()` and it is initialized with:

```

2023-01-06 18:13 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/root_development.md
> +
I'd add a short reference to the appropriate SWAT section at the bottom of the file for users to go and get more info.

2023-01-07 20:55 UTC, LaplacetteCM commented on SC_redesign/Crop_and_Soil/docs/root_development.md
> +
Done, good idea!

2023-01-07 21:50 UTC, LaplacetteCM commented on SC_redesign/Crop_and_Soil/docs/root_development.md
> +```
I removed the \ but still cannot make it work in Pycharm. I checked but I can't figure it out, did it work for you?

2023-01-07 21:53 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/root_development.md
> +```
No, because Pycharm (like most editors) doesn't handle latex math (but GitHub does). So you'll probably have to upload the file and look at it in the browser to see if it worked properly, unfortunately.

2023-01-07 23:28 UTC, LaplacetteCM commented
[root_development_CML2.md](https://github.com/RuminantFarmSystems/MASM/files/10367365/root_development_CML2.md)

Version updated, not sure if this is the way I'm supposed to share it. I did it before looking at yours, so feel free to tell me if you'd like me to make the changes so all files will have the same look (I think descriptions should be the same when using same variables in dif files (e.g. heat_fraction)

2023-01-08 03:45 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/root_development.md
> +$$
@LaplacetteCM, I think I was able to get it to work! It turns out we needed to use the "cases" keyword.

2023-01-08 11:34 UTC, merged

2023-01-09 22:32 UTC, LaplacetteCM commented
[root_development_CML3.md](https://github.com/RuminantFarmSystems/MASM/files/10377401/root_development_CML3.md)
File corrected based on yesterday's feedback.