[T6006][T6007] Added OutputManager to manure handler and reception pits classes
RuminantFarmSystems/RuFaS pull request #275
Opened 2023-01-11 06:44 UTC by CorneliusOsei2

2023-01-11 17:02 UTC, ltp23 approved these changes

2023-01-11 18:21 UTC, ew3361zh requested changes
Cornelius, this looks good. There are some info_maps where you need to add the caller function key-value pair and then there are some info_maps where you didn't add the function arguments and I was curious why you decided to do so in each case. Was it a case by case basis or were there specific functions like class functions that you didn't think needed it? Just curious to get your decision making on those.

Please double check that each info_map has a caller class and caller function at a minimum though.

I also really liked your use of the vars() method to extract a more readable version of the data from the more complex structures. That could prove to be very useful in the final output of the OutputManager.

2023-01-11 18:21 UTC, ew3361zh commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +        info_map = {"class": self.__class__.__name__}
Add caller function to info_map

2023-01-11 18:21 UTC, ew3361zh commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +        info_map = {"class": self.__class__.__name__}
Add caller function to info_map

2023-01-11 18:21 UTC, ew3361zh commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +        info_map = {"class": self.__class__.__name__}
Add caller function to info_map

2023-01-11 18:21 UTC, ew3361zh commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +        info_map = {"class": self.__class__.__name__}
Add caller function to info_map

2023-01-11 18:21 UTC, ew3361zh commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +        info_map = {"class": self.__class__.__name__}
Add caller function to info_map

2023-01-11 18:21 UTC, ew3361zh commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +        info_map = {"class": self.__class__.__name__}
Add caller function to info_map

2023-01-11 18:21 UTC, ew3361zh commented on RUFAS/routines/manure/reception_pits/reception_pit.py
> +                    }
It looks like you used the vars() method on more complex data structures in other places in this PR, is there a reason you excluded the bedding, pen, and manure_handler_daily_output vars() structures here?

2023-01-11 18:21 UTC, ew3361zh commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +                    "function": cls._calc_fraction_of_day_from_minutes.__name__}
add minutes functional argument to infomap?

2023-01-11 18:21 UTC, ew3361zh commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +                    "function": self.calc_manure_volume_deposited_in_milking_parlor.__name__}
add num_cows, manure_mass functional arguments to info_map?

2023-01-11 18:21 UTC, ew3361zh commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +                    "function": self.calc_manure_mass_deposited_in_milking_parlor.__name__}
add num_cows, manure_mass functional arguments to info_map?

2023-01-12 13:52 UTC, CorneliusOsei2 commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +        info_map = {"class": self.__class__.__name__}
So that is a property of the class and not necessarily a "function". Can be deduced with the @property decorator on the function header. That is why the function name is not added to the info_map. It is not a regular function but simply computes a property for instances of the class. Thanks.

2023-01-12 13:52 UTC, CorneliusOsei2 commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +        info_map = {"class": self.__class__.__name__}
So that is a property of the class and not necessarily a "function". Can be deduced with the @property decorator on the function header. That is why the function name is not added to the info_map. It is not a regular function but simply computes a property for instances of the class. Thanks.

2023-01-12 14:02 UTC, CorneliusOsei2 commented on RUFAS/routines/manure/manure_handlers/milking_parlor.py
> +                    "function": cls._calc_fraction_of_day_from_minutes.__name__}
Given that the number of minutes in a day is constant, I presumed it should be possible (and relatively easy to  deduce the value of minutes from the "minutes_of_day_frac" that has been logged.

2023-01-12 15:20 UTC, ew3361zh approved these changes
Looks good, nice work, Cornelius!

2023-01-12 15:27 UTC, merged