Animal management comments
RuminantFarmSystems/RuFaS pull request #283
Opened 2023-01-12 06:16 UTC by Fjordrunner

Final commit for daily_update_id_pen() refactor. This pull request includes the addition of three new functions, remove_animal_from_herd(), track_former_pen_population(), and calculate_pen_rations(). Additionally, daily_update_id_pen() was renamed to daily_update_id_map() to better describe its purpose. This rework also fixed the docstrings across animal_management.py and life_cycle.py to reflect that we are working with Animal objects and not directly with their IDs, which is another new change introduced in this pull request. Unit tests for the 4 functions mentioned above will be introduced in the next pull request so as to not make this one too large.

2023-01-12 17:18 UTC, JoeWaddell reviewed
This is looking good. The use of animal objects instead of ids is great! Streamlines things nicely.

I can't find any errors, but I'll have to take another round through the codebase...seems like the variable/attribute names were all updated correctly. Runs on my end just fine, though I do notice that some cows are still moving between pens every few days: likely related to other parts of the code since it could be what's referenced in git issue #74

2023-01-12 17:18 UTC, JoeWaddell commented on RUFAS/routines/animal/animal_management.py
> +        return self.life_cycle_manager.initialize_db_summary
autoformatter wants a final blank line here

2023-01-12 19:00 UTC, KFosterReed commented on RUFAS/routines/animal/animal_management.py
> +        of the pens they were in. This function is void.
What does 'This function is void' mean? Is there a missing part of this doc string? 

Also, in light of a conversation we had during the fixathon checkin maybe a more succinct definition for this function would be: 

Deletes the IDs of animals from animal_to_pen_id_map dictionary when the animal was removed from the herd; updates the relevant pen's stocking density.

2023-01-12 19:27 UTC, JoeWaddell commented on RUFAS/routines/animal/animal_management.py
> +        of the pens they were in. This function is void.
I think "This function is void" is explicitly noting that it doesn't return anything.

2023-01-12 19:58 UTC, ancheypeng commented on RUFAS/routines/animal/animal_management.py
> +        of the pens they were in. This function is void.
It might be more clear to change that sentence to something like, "This function returns nothing" or "This function is a void type function".

2023-01-12 20:11 UTC, KFosterReed commented on RUFAS/routines/animal/animal_management.py
> +
I am trying to think of a more succinct way to say this. What about: 

Adjusts the amount of each feed within a ration that is delivered to a pen when the number of animals in the pen is changed

2023-01-12 20:15 UTC, ancheypeng commented on RUFAS/routines/animal/animal_management.py
> +        self.all_pens_ids = []
This might be nitpicky or just in my head, but it seems to me like `all_pens_ids` is less clear than `all_pen_ids` because the list contains all of the "pen_ids" not all of the "pens_ids"

```suggestion
        self.all_pen_ids = []
```

2023-01-12 20:24 UTC, PooyaHekmati requested changes

2023-01-12 20:24 UTC, PooyaHekmati commented on RUFAS/output_handler/reports/pen_report.py
>              self.reports['pen_' + str(pen.id)] = PenReport(data, state.feed, pen, pen.id)
if we are looping through all_pens_ids then the variable in the loop should be pen_id rather than pen. This means that in the next line, we will have pen_id.id which doesn't sounds right. There is something wrong in here.

2023-01-12 20:24 UTC, PooyaHekmati commented on input/animal_management.json
> +        "seed": 41,
Per convention, the seed has to be 42.

2023-01-12 20:26 UTC, PooyaHekmati commented on RUFAS/routines/animal/animal_management.py
> +        of the pens they were in. This function is void.
The fact that this function doesn't return anything has to be communicated using type annotation:
_def foo(args) -> None:_
Also, if it is important to reiterate this in docstring as well, it has to be done like:
Returns
\--------
            None

2023-01-12 20:28 UTC, ancheypeng commented on RUFAS/routines/animal/animal_management.py
> +    def remove_animal_from_herd(self, animals_removed):
```suggestion
    def remove_animals_from_herd(self, animals_removed):
```

Would this make more sense to be `remove_animals_from_herd` because its removing multiple animals?

2023-01-12 20:30 UTC, PooyaHekmati commented
Newly developed functions need to be type annotated and have unit tests.

2023-01-13 04:06 UTC, Fjordrunner commented on input/animal_management.json
> +        "seed": 41,
Just switched this, thanks for letting me know!

2023-01-13 04:27 UTC, Fjordrunner commented on RUFAS/routines/animal/animal_management.py
> +    def remove_animal_from_herd(self, animals_removed):
Thanks for catching that, good point!

2023-01-13 04:30 UTC, Fjordrunner commented on RUFAS/routines/animal/animal_management.py
> +        return self.life_cycle_manager.initialize_db_summary
Good catch, just changed that!

2023-01-13 15:08 UTC, Fjordrunner commented on RUFAS/routines/animal/animal_management.py
> +
I added this change, pushing a commit with it right now!

2023-01-13 15:31 UTC, Fjordrunner commented
> Newly developed functions need to be type annotated and have unit tests.

I was planning on adding those in a separate PR to immediately follow this one, since this PR is already on the larger side, but if you think that it is appropriate to add them here then I will do so.

2023-01-13 15:53 UTC, Fjordrunner commented on RUFAS/output_handler/reports/pen_report.py
>              self.reports['pen_' + str(pen.id)] = PenReport(data, state.feed, pen, pen.id)
Good catch. I've done some more investigating and all_pens_ids should have never referred to pens, as its contents are the Pen objects on a farm. However, that being said, there are some places in the code where this seems inconsistent, so this will probably require a lengthier conversation with @KFosterReed

2023-01-13 23:01 UTC, Fjordrunner commented on RUFAS/routines/animal/animal_management.py
> +        self.all_pens_ids = []
Good point. However, we're migrating away from the old name entirely as the class variable was changed to `all_pens` . In actuality, the variable contains a list of Pen objects and not their IDs, so this change was definitely needed.

2023-01-13 23:03 UTC, Fjordrunner commented on RUFAS/output_handler/reports/pen_report.py
>              self.reports['pen_' + str(pen.id)] = PenReport(data, state.feed, pen, pen.id)
As per our meeting, all instances of `all_pens_ids` are now more appropriately named `all_pens` . Once again, thanks for catching this!

2023-01-16 16:05 UTC, Fjordrunner commented on RUFAS/routines/animal/animal_management.py
> +        of the pens they were in. This function is void.
I removed the sentences indicating that a given function was void, and added type annotations to the 4 functions I created/edited. Should be good to go now, let me know if I can make anything clearer!

2023-01-17 21:58 UTC, KFosterReed commented on RUFAS/routines/animal/animal_management.py
How about: 

Updates the dictionary that maps animal objects to the pen they are housed in when new animals are born or purchased and when animals leave the herd due to death or culling

2023-01-19 17:40 UTC, Fjordrunner commented on RUFAS/routines/animal/animal_management.py
I like this, this sounds good! I think that we are operating off of IDs so I will make that distinction once confirming, but I'll be pushing this now! Only have unit tests and this PR should be good to go once that is done!

2023-04-25 13:57 UTC, KFosterReed approved these changes
This seems to work as expected! It doesn't fix our overall challenge of moving animals between pens but the animals added and removed are working as expected and the clarity is hugely improved :)

2023-04-25 21:13 UTC, ancheypeng approved these changes
Looks good to me!

2023-04-25 21:18 UTC, JoeWaddell approved these changes
Looks good to me! Nice work, and I think the issues raised in previous reviews have been worked out in the revision process.

2023-04-26 02:03 UTC, PooyaHekmati requested changes
LGTM overall.
As we discussed and agreed in the meeting, I was expecting a git issue linked to this PR both in the PR description/comments and as a comment in the code to document the faulty logic. Since I don't see it, I'd like to know the reason.
Sending back to fix those two minor comments.

2023-04-26 02:03 UTC, PooyaHekmati commented on RUFAS/routines/animal/animal_management.py
> +    def fully_update_animal_to_pen_id_map(self):
```suggestion
    def fully_update_animal_to_pen_id_map(self) -> None:
```

2023-04-26 02:03 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +    def add_new_animals(self, new_animals: List[Any]) -> None:
Why is type Any used here? That is not a good practice and should only be used when no other solution is possible.

2023-04-26 02:03 UTC, PooyaHekmati commented on RUFAS/routines/animal/pen.py
> +    def remove_animals_by_ids(self, animal_ids: List[int]):
```suggestion
    def remove_animals_by_ids(self, animal_ids: List[int]) -> None:
```

2023-04-26 14:44 UTC, Fjordrunner commented
> LGTM overall. As we discussed and agreed in the meeting, I was expecting a git issue linked to this PR both in the PR description/comments and as a comment in the code to document the faulty logic. Since I don't see it, I'd like to know the reason. Sending back to fix those two minor comments.

The issue we mentioned in the former meeting is seemingly fixed via some new code that Loi and I wrote. The problem that still persists is the one elaborated upon in [https://github.com/RuminantFarmSystems/MASM/issues/189](url). That will be the next step of making sure the animal-to-pen allocation is being done correctly.

2023-04-26 16:30 UTC, PooyaHekmati approved these changes

2023-04-26 16:31 UTC, PooyaHekmati commented
Please fix merge conflicts.

2023-04-26 18:40 UTC, merged