Phosphorus morrowcj
RuminantFarmSystems/RuFaS pull request #290
Opened 2023-01-18 07:00 UTC by morrowcj

## Summary
This PR refactors the old crop methods for `PhosphorusIncorporation` (`phosphorus_incorporation.py`). The methods used to calculate phosphorus uptake are basically identical to those used to calculate nitrogen uptake. Therefore, `PhosphorusIncorporation` uses many of the static methods of `NitrogenIncorporation`. 

Tests were also implemented for the new code. Many of the phosphorus tests are also extremely similar (or identical) to those of nitrogen.

## Other changes
* moved the script which finds project TODOs

## Notes 
`PhosphorusIncorporation` and `NitrogenIncorporation` should probably be combined into a single `NutrientIncorporation` class at some point, but this will have to be a a future project.

2023-02-01 21:06 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +        """Process component controlling plant nitrogen incorporation, including uptake and fixation"""
```suggestion
        """Process component controlling plant phosphorus uptake and incorporation"""
```

2023-02-01 23:05 UTC, Isgotkowitz requested changes
Looks good, only work that needs to be done is adding SWAT references to methods

2023-02-01 23:05 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/nitrogen_incorporation.py
>          Returns: list of the first and second shape coefficients, respectively
Could you a SWAT reference here

2023-02-01 23:05 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/phosphorus_incorporation.py
> +This module is based upon the 'Phosphorus Uptake" section of of the SWAT model documentation
Can you add the SWAT section numbers here

2023-02-01 23:05 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/nitrogen_incorporation.py
> +    def determine_layer_extracted_resource(requests: List[float], sources: List[float]) -> List[float]:
This method needs a comment

2023-02-02 17:25 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/nitrogen_incorporation.py
>          Returns: list of the first and second shape coefficients, respectively
Done.

2023-02-02 17:26 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/phosphorus_incorporation.py
> +This module is based upon the 'Phosphorus Uptake" section of of the SWAT model documentation
Done

2023-02-02 17:26 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/nitrogen_incorporation.py
> +    def determine_layer_extracted_resource(requests: List[float], sources: List[float]) -> List[float]:
And done.

2023-02-02 19:22 UTC, Isgotkowitz requested changes
I don't think I was clear enough before. I think it is a good idea for *every* method that is associated with a specific equation in SWAT to have a reference to that equation in its description.

2023-02-02 19:22 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/nitrogen_incorporation.py
>          Returns: list of the first and second shape coefficients, respectively
I think this method should also say that it references SWAT 5:2.3.2 and 3

2023-02-02 19:22 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/nitrogen_incorporation.py
>          """
This is SWAT 5:2.3.5, I believe

2023-02-02 20:16 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/nitrogen_incorporation.py
>          """
My bad, I thought they were. Thanks for the added clarity.

2023-02-02 21:08 UTC, morrowcj commented
OK, @Isgotkowitz. I think that all the methods that can be linked to SWAT now contain references. Thanks for your patience.

2023-02-02 21:49 UTC, Isgotkowitz approved these changes
Looks gucci to me

2023-02-02 23:25 UTC, ltp23 approved these changes
Great job, Clay!

If you think both nitrogen and phosphorus incorporation classes are similar enough to warrant using inheritance, then I think you should do it to make things more maintainable for you. 

For those static methods, you can simplify by using `self` like `self.some_static_method()` since they reside in the same class.

2023-02-03 05:10 UTC, morrowcj commented
> If you think both nitrogen and phosphorus incorporation classes are similar enough to warrant using inheritance, then I think you should do it to make things more maintainable for you.

That isn't a bad idea. I think that might be a job for a different PR though. 

I'm going to merge this.

2023-02-03 05:11 UTC, merged