Biomass_allocation.md wiki
RuminantFarmSystems/RuFaS pull request #298
Opened 2023-01-23 17:57 UTC by LaplacetteCM

This is the proposed wiki for biomass_allocation.py

Notes:
1. According to the comments in the code, the notation of the .py file will be updated to match the other files or to better indicate what the code is doing, so this wiki might need a future update (e.g., photosynthesize, intercept radiation). 
2. The code does not include the total biomass calculation yet but total biomass is used for 'partioned_biomass'. It is included  in the wiki. 
3. I'm making a list of the notation we are using because the idea is to be consistent between wikis. If there's a correction to make, I'll correct the other files as well.

2023-01-23 18:10 UTC, morrowcj commented
>     1. According to the comments in the code, the notation of the .py file will be updated to match the other files

The file already has been updated, actually. I think I forgot to remove the #TODO. I'll fix that and push it here.

Great!

>     2. The code does not include the total biomass calculation yet

Is this true? `photosynthesize()` calculates total `biomass` (line 29), by adding the maximum accumulation value (`biomass_growth_max`) to the previous `biomass`.

2023-01-23 18:39 UTC, morrowcj requested changes
This looks pretty good overall. A few variables names do need clarification, though.

2023-01-23 18:39 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +where $R_{\text{int}}$ is `intercept_radiation`, $R_{\text{inc}}$ is`incident_radiation`,
The code calls the intercepted radiation `usable_light`, not `intercept_radiation`. Also, `incident_radiation` is not used in the code and I think we can use a simpler term like "total incoming solar radiation" or something similar.

2023-01-23 18:39 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +where $Biom_{\text{max}}$ is `max_accumulation`, $R_{\text{int}}$ is `intercept_radiation`,
the max accumulation variable is `biomass_growth_max` in the code.

2023-01-23 18:39 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +and $Eff_{\text{rad}}$ is `efficiency`, the radiation-use efficiency of the crop.
the efficiency is called `light_conversion` factor, in the code. I could be easily persuaded to change this to something like `light_use_efficiency`, though.

2023-01-23 18:39 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +where $Biom_{\text{i}}$ is `daily_accumulated_biomass`, $Biom_{\text{max}}$ is `max_accumulation`,
```suggestion
where $Biom_{\text{i}}$ is daily accumulated `biomass`, $Biom_{\text{max}}$ is the maximum biomass accumulation,
```

2023-01-23 19:36 UTC, ew3361zh approved these changes
From my pov this looks good. I had one suggested change but it's not a dealbreaker for me. I do think it would be helpful to get Pooya to look at one of these wiki files to make sure they're matching up with what he had in mind (and maybe that's already happened).

2023-01-23 19:36 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +**photosynthesize** and **partition biomass**.
I don't know if I'd use the word "returns" here since `allocate_biomass()` is not really returning (in the coding sense) anything. I think something along the lines of "The central method, `allocate_biomass()`, calls on the **photsynthesize** and **partition biomass** methods to make daily updates on crop biomass allocation."

I don't know how consistently we're using python method vs python function but I think generally any functions associated with classes or objects are referred to as methods (a good rule of thumb is a method is passed a reference of self and is called with self.method_name). I also don't know how much of a stickler most people are on this point but here's some more info on it: https://www.geeksforgeeks.org/difference-method-function-python/

2023-01-23 20:04 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +**photosynthesize** and **partition biomass**.
I did not know this about functions vs. methods. Thanks for this info. I'll try to internalize it and be consistent.

2023-01-23 21:45 UTC, LaplacetteCM commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +**photosynthesize** and **partition biomass**.
Thank you Niko, l still need to get more familiar with the terms and this helps a lot. I didn't know about this difference so I'm gonna take a look through the previous wikis to check the way I used them.

2023-01-23 22:08 UTC, LaplacetteCM commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +and $Eff_{\text{rad}}$ is `efficiency`, the radiation-use efficiency of the crop.
Between the 2 options, I like "light_use_efficiency" here. It's closer to RUE and also describes more clearly what RUE is doing. But I'll leave it up to you!

2023-01-23 22:10 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +and $Eff_{\text{rad}}$ is `efficiency`, the radiation-use efficiency of the crop.
You're right. OK. Go with `light_use_efficiency` and I'll update it in the code and push to this branch.

----
Edit: Done

2023-01-23 22:21 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +**photosynthesize** and **partition biomass**.
@ew3361zh, would you consider things decorated with `@staticmethod` to be "functions" or "methods"? My intuition says they are functions (because they don't use a `self` reference and don't require the class to be initialized).

2023-01-24 00:05 UTC, LaplacetteCM commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +where $Biom_{\text{max}}$ is `max_accumulation`, $R_{\text{int}}$ is `intercept_radiation`,
Done

2023-01-24 00:10 UTC, LaplacetteCM commented
Thanks for your comments, I've included all the corrections you mentioned. 

I agree with Niko about asking Pooya if we are on the right track with this approach, maybe this is not what he had on mind for the wikis or he might have some suggestions for improvement.

2023-01-24 15:30 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/docs/biomass_allocation.md
> +**photosynthesize** and **partition biomass**.
@morrowcj good question - I think the name would indicate it's more considered a method than a function and static methods are still bound to classes so even though they don't take the self argument and aren't bound the object, they still operate just within the class where they're defined which seems to be a major distinguisher for a method vs a function. https://pynative.com/python-static-method/

2023-01-25 18:56 UTC, morrowcj approved these changes
This looks great! You can go ahead and merge it, or if you'd like to get @PooyaHekmati's opinion, you can request him as a reviewer and await his response. 

Great work and thank you!

2023-01-25 21:56 UTC, morrowcj commented
I spoke with Pooya, and he doesn't feel the need to look over this. Go ahead and merge when you are ready.

2023-01-25 21:58 UTC, merged