Evapotranspiration Refactor
RuminantFarmSystems/RuFaS pull request #307
Opened 2023-01-26 16:51 UTC by Isgotkowitz

# Summary
This PR refactors the `Evapotranspiration` module within the `Soil` module based on SWAT 2:2.3. All but three methods are `@staticmethods`, which eliminates the need to pass objects into methods as was done in the old code. `evapotranspirate()` is the main method within `Evapotranspiration` that handles all evapotranspiration operations from the soil. All methods are tested in the `test_evapotranspiration.py` file.

It also introduces the `SoilData` and `LayerData` classes. `SoilData` is the soil equivalent to `CropData`; it will store data that is generated and tracked by modules within `Soil`. Each instance of the `LayerData` class represents a single layer of soil within a soil profile, and a `Soil` object maintains a list of `LayerData` objects to manage the soil profile.

# Notes
* In the old code, `Evapotranspiration` included an operation to determine the maximum transpiration based on attributes of `CropData`. This method has been moved to the `WaterDynamics` module within the `Crop` module, and is now tested within the `test_water_dynamics.py` file.
* A separate folder has been added for `Soil` module tests, which includes an empty `init` file. At some future point all tests for `Crop` module should be moved into their own module.

2023-01-31 18:51 UTC, morrowcj requested changes
# Summary
Ed, I think that, in general, this PR is quite good: great work. My main comments involve `_determine_evaporative_demand()`, which I'd like you to address before moving forward. The comments on this method also apply generally to `determine_evaporative_demand_reduced()` and `_determine_amount_water_removed()`. Feel free to push back, if desired. I am hopeful that once we go through a few back-and-forths on this file, it will make the other soil refactors a bit easier. 

# Other Comments
* Try to be much more descriptive in the main comment of the PR. It is OK to open a draft with a placeholder, 
but once you're ready for review, it is very important to give reviewers information about what they're looking
at. What was the goal of the PR? What are the primary files affected? Are there any special considerations or 
context that should be available? etc. 
* Add a top-level docstring describing where in SWAT the functions in `evapotranspiraiton.py` and `water_dynamics.py` come
come from (see lines 5-8 in `crop/biomass_allocation.py`).

2023-01-31 18:51 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        # TODO: add field (in CropData?) to track amount of free water in canopy as it gets adjusted - issue #316
```suggestion
        # TODO: add attribute (in CropData?) to track amount of free water in canopy as it gets adjusted - issue #316
```

Let's avoid using the term "field" to refer to anything other than an agricultural field, if possible.

2023-01-31 18:51 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        SWAT Reference: 2:2.3.17
I'm having a hard time linking this SWAT equation to this code.

2023-01-31 18:51 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        top_quotient = top_depth / (top_depth + exp(2.374 - (0.00713 * top_depth)))
Where does this term (`top_quotient`) come from??

2023-01-31 18:51 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        """calculates the evaporative demand for a given layer of soil
Let's indicate in the name that this is a layer function. Also, how do you feel about removing the dependency on `LayerData`? My preference is to always do so (in `@staticmethod`s) unless it would require an unreasonable number of parameters

```suggestion
    def _determine_layer_evaporative_demand(max_soil_water_evaporation: float, top_depth: float, bottom_depth: float, compensation: float) -> float:
        """calculates the evaporative demand for a given layer of soil
```

note that the acronym "esco" should be replaced with a better name. As a parameter, I'm good with simply `compensation` but the corresponding `LayerData` attribute should be something like `evapotranspiration_compensation_coefficient`

2023-01-31 18:51 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        bottom_evaporative_demand = max_soil_water_evaporation * bottom_quotient
This violates "don't repeat yourself" because it is doing exactly the same thing as lines 214-217. It seems to me that a cleaner solution would be to change this function to something like:

```python
def _determine_depth_evaporative_demand(depth: float, max_evaporation: float) -> float:
    """calculate the evaporative demand at a particular soil depth"""
    pass

def _determine_layer_evaporative_demands(depths: List[float], compensations: List[float], max_evaporation: float) -> List[float]:
    """calculate the evaporative demand for each soil layer
    
    Args: 
        depths: the deepest depths for each soil layer (mm)
        compensations:  the compensation factors for each layer (mm)
        max_evaporation: the maximum water evaporation for the soil (layers?, if so should be a List) during the current day.
    """

    # add in the depth of the soil surface (depth of 0)
    new_depths = [0] + depths
   
    # get depth demands
    depth_demands = [Evapotranspiration._determine_depth_evaporative_demand(d) for d in new_depths]

    # calculate and return the layer demands for each layer
    return [lower - upper*coef for lower, upper, coef in zip(depth_demands[1:], depth_demands, compensations)]
```

It doesn't necessarily need to be split into two functions, but its how I think of this type of problem. What are your thoughts on this? It is how I've handled layers previously (i.e., in `nitrogen_incorporation.py`). But, as always, if you think there's a good reason not to do this, feel free to say so.

2023-01-31 19:07 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        SWAT Reference: 2:2.3.17
This is function is actually a combination of 2:2.3.16 (the first one, there is a duplicate) and 2:2.3.17. The 16 is to calculate the evaporative demand at a certain depth, and 17 is to calculate evaporative demand for a layer based on the its top and bottom depths

2023-01-31 19:08 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        top_quotient = top_depth / (top_depth + exp(2.374 - (0.00713 * top_depth)))
Equation 2:2.3.16, I'll add that into the comments

2023-01-31 19:09 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        top_quotient = top_depth / (top_depth + exp(2.374 - (0.00713 * top_depth)))
My bad, I don't know how I missed it.

2023-01-31 19:11 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        """calculates the evaporative demand for a given layer of soil
Removing the dependency is no problem here, I'll take care of it

2023-01-31 19:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        bottom_evaporative_demand = max_soil_water_evaporation * bottom_quotient
First, I think it would be a good idea to split it into two function cause I am definitely repeating myself.

2023-01-31 20:01 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        bottom_evaporative_demand = max_soil_water_evaporation * bottom_quotient
Second, I think it is better to do one layer at a time, and have a call for each layer in `evaporate_from_soil`. In this case either method works alright, but I find it more straightforward to work on one object a time. Also, as soon as multiple objects get separated into corresponding lists of attributes, the danger arises that somehow those lists will get/be used out of sync.

2023-01-31 21:13 UTC, morrowcj approved these changes
Looks great! Thanks for your patience.

2023-02-02 16:34 UTC, morrowcj reviewed
I noticed a couple things in `evapotranspiration.py` while I was reviewing #319 that I missed previously.

2023-02-02 16:34 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        Details: calculates and stores the potential evapotranspiration, soil evaporation in the SoilData object
I think we need a better verb than "does" - maybe "executes evapotranspiration processes"?

Also you're missing docstrings for the arguments.

2023-02-02 16:34 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +            return self.data.potential_evapotranspiration - initial_canopy_free_water
I like these contextual additions a lot.

2023-02-02 17:06 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +            return self.data.potential_evapotranspiration - initial_canopy_free_water
Thanks

2023-02-02 17:08 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        Details: calculates and stores the potential evapotranspiration, soil evaporation in the SoilData object
I have added a docstring and changed the description to use your suggested verb, I think it should be good now

2023-02-02 17:12 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +            latent heat of vaporization in MJ per kg
Good thinking to change this. Superscript notation in plain text is a pain. Hooray for parsimony!

2023-02-02 20:53 UTC, ew3361zh approved these changes
Really nice work. I'll leave the science part to Clay's review but the coding practices look sound. There was one place I didn't see docstrings (`def cycle_water` in the `WaterDynamics` class) but otherwise really consistent, well-documented doc strings, generally good typing practices, code is well broken up using single-responsibility principle guidelines. Testing from "old" testing modules were failing (see attached photo) but discussed with Ed and he assured me this was not a concern at this juncture as those will be obsolete.
<img width="1325" alt="Screenshot 2023-02-02 at 3 20 02 PM" src="https://user-images.githubusercontent.com/70217952/216446568-e712e880-0dce-4a9c-80eb-00a346a9b447.png">

2023-02-02 20:53 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/crop/water_dynamics.py
> +                    potential_evapotranspiration_adjusted: float) -> None:
Add doc strings for this method

2023-02-02 21:12 UTC, morrowcj commented
> Testing from "old" testing modules were failing (see attached photo) but discussed with Ed and he assured me this was not a concern at this juncture as those will be obsolete. 

To clarify, @ew3361zh, as Ed mentioned these tests are obsolete `pytest SC_redesign` is what we're most interested in. That being said, I do plan to fix those old tests, since I broke them by merging Reid's code into the `SC_Redesign` branch but did not update tests.

2023-02-02 21:30 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/soil.py
>      def make_from_config(cls, soil_config) -> Soil:
missing docstring

2023-02-02 21:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/water_dynamics.py
> +                    potential_evapotranspiration_adjusted: float) -> None:
Docstring is now present, but Clay and I will need to do some `TODO`'s before it can be finished

2023-02-02 21:41 UTC, matthew7838 approved these changes
Most styling and comments look good, all I can find are some missing docstrings. One thing I noticed is that there are no docstrings in the tests. I was told to add docstrings while writing my tests so I'm not sure if the same principle would apply to this PR.

2023-02-02 21:41 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil.py
>      def make_from_config(cls, soil_config) -> Soil:
This function is not actually implemented yet, I think it will be ok to wait until it is implemented to write the docstring. Nice catch though

2023-02-03 17:07 UTC, merged