Crop Species Data
RuminantFarmSystems/RuFaS pull request #314
Opened 2023-01-27 22:40 UTC by morrowcj

## Summary
This PR Incorporates the species data from the SWAT database and allows for different crops to be used interchangeably in RUFAS. The PR is misleadingly large and should be very straightforward to review (see details)

Thank you for your review!

## Changes 
* `CropSpecies` is an `Enum` of all the different crop species handled by RUFAS (`species_data_factory.py`)
* a new crop species class exists for each of the supported `CropSpecies` (`crop_data.py`)
* all crop species have attribute values taken from the [SWAT database](https://swat.tamu.edu/media/69419/Appendix-A.pdf), and have been fully validated (with the exception of `Triticale`).
* `CropSpeciesDataFactory` builds the crop data for the desired species. (`species_data_factory.py`)

## Details
* All changes to the `CropData` class are simply re-arranges or updating default variable values
* All other changes to `crop_data.py` setup the species default attribute values
* `species_data_factory.py` contains the main updates in need of review
* The tests should also serve as a demonstration of the functionality. In particular:
  - `test_species_factory_defaults()` is very long and simply tests that all attributes are initialized to their appropriate values for each data class.
  - `test_manual_custom_crop_data()` demonstrates how to manually create custom crops by directly altering the values of the data class.
  - `test_factory_alterations()` demonstrates the factory's utility at extending this customization

2023-02-02 20:58 UTC, Isgotkowitz requested changes
Looks really good, especially `species_data_factory.py`. There are just a few (hopefully minor) things to discuss, and after that it should be good to merge

2023-02-02 20:58 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +      The slots=True argument sets up the data class so that memory is pre-allocated for the instance. This means that
Where is the `slots=True` argument?

2023-02-02 20:58 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    """fraction of potential heat units accumulated to date (unitless)"""
```suggestion

```

2023-02-02 20:58 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
>      (unitless; [0, 1])"""
```suggestion
    (unitless; must be greater than or equal to 0 and less than or equal to 1)"""
```
Not really a necessary change, but it would eliminate the 30 seconds I needed to think about what `[0, 1]` meant

2023-02-02 20:58 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +"""
Would it be possible to put each child class into its own file and put each file into a dedicated folder? If so that would make it possible for someone to see what is and isn't there without having to actually open up the file and read through it.

2023-02-02 21:16 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +      The slots=True argument sets up the data class so that memory is pre-allocated for the instance. This means that
It accidentally got removed. I'll put it back in (though I'm not 100% sure it will remain).

2023-02-02 21:19 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
>      (unitless; [0, 1])"""
This is a good point - I have been using set notation occasionally. I'll need to think about this more.

2023-02-02 21:53 UTC, Isgotkowitz approved these changes
Nice

2023-02-03 04:35 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +"""
I've decided to leave this as-is for now. I may decide to do a reorganization in a separate PR.

2023-02-03 15:07 UTC, JoeWaddell approved these changes
This looks like good work! Straightforward code, and it runs without problems on my setup. 

Only a couple minor comments where I try to summon @ltp23 for some insight in how to handle unit tests. 

Also: I appreciate the Summary/Changes/Details you wrote: that helps a lot in reviewing a PR, especially for folks outside your subject area.

2023-02-03 15:07 UTC, JoeWaddell commented on SC_redesign/Crop_and_Soil/tests_SC/test_crop_data_and_species_factory.py
> +    del generic  # cleanup
This is a question for @ltp23 and others - would using a pytest fixture get around the need to delete a temporary object like this? It could be over-engineering things, but it's what I've tried doing in the [animal_tests branch](https://github.com/RuminantFarmSystems/MASM/pull/284/files), but I'm not sure if I've done it the best way (it works, but it's still in review so I can't vouch that it's 100% correct).

2023-02-03 15:07 UTC, JoeWaddell commented on SC_redesign/Crop_and_Soil/tests_SC/test_crop_data_and_species_factory.py
> +
If the fixture method isn't the way to go, would this require a `del aspen` line here, for cleanup?

2023-02-03 15:14 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/tests_SC/test_crop_data_and_species_factory.py
> +    del generic  # cleanup
I'm not sure it was necessary to delete anything at all. As I understand it, all these objects only exist in the scope of the function and are destroyed once it is done running. But, because this particular function creates many different class instances during it's execution, I thought it might be good to prevent clutter. I'm curious to know what @ltp23 has to say.

2023-02-03 15:17 UTC, JoeWaddell commented on SC_redesign/Crop_and_Soil/tests_SC/test_crop_data_and_species_factory.py
> +    del generic  # cleanup
Oh of course! It would be a local, since it's just inside the test function. Makes me feel better, because in the branch I linked there, I wasn't deleting those objects either (in the cases I didn't use a fixture).

2023-02-03 21:48 UTC, ltp23 commented on SC_redesign/Crop_and_Soil/tests_SC/test_crop_data_and_species_factory.py
> +    del generic  # cleanup
I agree it is not necessary to delete those local objects. It is only tricky when we have class variables, then we would have to save the initial states and then reassign afterward.

2023-02-03 21:55 UTC, ltp23 commented on SC_redesign/Crop_and_Soil/tests_SC/test_crop_data_and_species_factory.py
> +
Same as above. We don't need to delete the object. 

Just an aside, when we assert a boolean variable, we don't need to write `is True` or `is False`. A simpler `assert aspen.is_perennial` or `assert not aspen.is_perennial` would work too.

2023-02-03 22:00 UTC, ltp23 commented
I really like how you documented those dataclasses. I need to follow that in the code I wrote. 

There is another way to handle default values for each crop data object but it takes about the same number of lines of code. It may help streamline the unit testing a bit if using parameterization. 

```
@dataclass(kw_only=True)
class Corn(CropData):
    """crop data class with default values for corn"""
    pass
```

```
class DefaultCropDataFactory:
    DEFAULT_CORN = Corn(
            species="corn",
            name="default corn",
            plant_code="CORN",
            # ....
    )

    @classmethod
    def get_default_crop_data(cls, crop_species: CropSpecies) -> CropData:
        default_crop_data_by_species = {
            CropSpecies.CORN: cls.DEFAULT_CORN,
            # ...
        }
        return default_crop_data_by_species[crop_species]

```

2023-02-03 22:01 UTC, ltp23 approved these changes

2023-02-03 23:24 UTC, merged