growth_constraints.md
RuminantFarmSystems/RuFaS pull request #320
Opened 2023-01-31 20:15 UTC by LaplacetteCM

This is the proposed wiki for growth_constraints.py

2023-01-31 20:49 UTC, morrowcj approved these changes
This looks excellent.  I made a few minor comments about typos and format. Well done, and thanks again!

2023-01-31 20:49 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/growth_constraints.md
> +face during the growing season. This module addresses the stresses caused by insufficient
```suggestion
faces during the growing season. This module addresses the stresses caused by insufficient 
```

2023-01-31 20:49 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/growth_constraints.md
> +actual and potential plant transpiration according to:
```suggestion
**Water stress** is the stress caused by the water soil conditions on a given day by comparing 
actual and potential plant transpiration:
```

2023-01-31 20:49 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/growth_constraints.md
> +to grow, and $T_{\text{opt}}$ is `optimal_temperature`, the optimal temperature for the crop to grow.
One alternative way to write these things may be a bit simpler:

```suggestion
where $T_{\text{stress}}$ is the temperature stress (`temp_stress`), $T_{\text{air}}$ is the mean air
temperature (`temperature`) for a given day, $T_{\text{crop, min}}$ is the base or minimum temperature for the crop 
to grow (`minimum_temperature`), and $T_{\text{opt}}$ is the optimal temperature for the crop to grow (`optimal_temperature`). 
```

2023-01-31 22:07 UTC, JoeWaddell requested changes
The writing looks good (though I can't comment much on the actual science behind it - but I trust you two!). Just note the comment about math formatting - it might just be my display settings, but the preview shows funky formatting because of using the $$ notation nested inside the math block. Once that's fixed it should be clean! Nice work

2023-01-31 22:07 UTC, JoeWaddell commented on SC_redesign/Crop_and_Soil/docs/growth_constraints.md
> +```math
So in previews everything inside the ` ```math` notation shows up with the `$$` symbols, in both VS Code's preview feather, and in a markdown preview tool online. 

Seems like you only need one notation or the other (e.g. ```math or a $$): see https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/writing-mathematical-expressions#writing-expressions-as-blocks

2023-01-31 22:08 UTC, JoeWaddell commented on SC_redesign/Crop_and_Soil/docs/growth_constraints.md
> +```math
So you can see what I mean: 
![image](https://user-images.githubusercontent.com/109082924/215894670-233845b8-2789-4189-92db-da70dffb9adf.png)


Removing the math block: 
![image](https://user-images.githubusercontent.com/109082924/215894850-951fd840-244d-4e44-a4ff-3d39d2d7a5c8.png)

2023-01-31 23:15 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/docs/growth_constraints.md
> +```math
I didn't know VS code could handle LaTeX math, Pycharm cannot natively, unfortunately.

2023-02-01 17:48 UTC, LaplacetteCM commented on SC_redesign/Crop_and_Soil/docs/growth_constraints.md
> +```math
Thanks Joe! I've updated the file deleting the math block and worked. I'll update the rest of the wikis the same way.

2023-02-01 18:11 UTC, JoeWaddell approved these changes
That did the trick: looks nice!

2023-02-01 18:55 UTC, merged