Animal life cycle refactoring
RuminantFarmSystems/RuFaS pull request #322
Opened 2023-02-01 21:10 UTC by ltp23

Some notes:
- Currently, all the instance variables (those prefixed with `self`) are public (i.e., can be seen when accessed from outside the file). I guess not all of them need to be exposed but only those that are used by other classes. We can have a discussion on what should be public or semi-private (we would prefix it with an underscore `_`).
- Feel free to make suggestions on how to make names of variables and functions more descriptive and specific. I also think it is a good idea to spell out names instead of abbreviating them. 
- Please review the functionality of each function to see if it makes sense. 
- Please make suggestions on how to make docstrings more informative.

2023-02-13 21:56 UTC, JoeWaddell requested changes
Various docstrings will need to be updated, but overall this cleans things up nicely. Great work!

2023-02-13 21:56 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        # at parturition, the sum of P absorbed for gestation rqmts is
I think these comments could be modified and made part of a docstring, with cited references and/or the existing references to pseudocode

2023-02-13 21:56 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/life_cycle.py
>      Manages the life cycles of the animals.
This and other docstrings could be expanded on: see a later comment with more detail.

2023-02-13 21:56 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/life_cycle.py
>          Args:
Some/most of the docstrings are from the previous version, but we'll need to update these to keep consistent across modules (following the guidelines I've linked below). Note the typing specifically, but updating Args to an underlined "Parameters", with type annotation in the docstring will make things look nice online in Sphinx format.

https://numpydoc.readthedocs.io/en/latest/example.html#example

@YijingGong would be a big help in writing/updating these, given her experience with this part of the model and the underlying animal science.

2023-02-13 21:56 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +    #  calving_interval attribute is present, maybe set that to true instead?
This is a good question, and I think a separate issue to review of the default JSON values for a handful of scenarios would be useful.

2023-02-13 21:56 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        preg_heifer_num = 0  # TODO: Seems unused after calculation
This could be a useful metric to collect in the output manager.

2023-02-13 21:56 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        life_cycle_daily_herd_update = {key: vars(self)[key] for key in life_cycle_daily_herd_update_keys}
This is wonderfully concise! These improvements to the code are great

2023-02-13 21:56 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        self.sold_heifers: List[HeiferIII] = []
Question for my own edification: is this essentially a clean way of showing that the empty list should be filled with a given type? e.g. this list is instantiated empty, but will later be filled with HeiferIII (or similar) objects?

2023-02-13 21:56 UTC, JoeWaddell commented on tests/test_animal_life_cycle.py
> +    mocker.patch('RUFAS.routines.animal.life_cycle.life_cycle.HeiferI',
To clear up some of my confusion on the patch process here:

Does it need to be patched from the `RUFAS.routines.animal.life_cycle.life_cycle` (instead of the location of the class definition itself, in: `RUFAS.routines.animal.life_cycle.HeiferI`) because the method we're testing "sees" the class inside the life_cycle.life_cycle location since it's been imported?

2023-02-13 21:56 UTC, JoeWaddell commented on tests/test_animal_life_cycle.py
> +def test_extract_repro_stats_from_heiferII(mocker: MockerFixture,
This is a nice example of a test for a subtly complex function: just wanted to note my appreciation for your elegant unit tests!

2023-02-14 15:49 UTC, ltp23 commented on tests/test_animal_life_cycle.py
> +    mocker.patch('RUFAS.routines.animal.life_cycle.life_cycle.HeiferI',
Yes, this is often a tricky point. We patch at the location the class/object is being used, instead of where it is defined.

2023-02-14 15:58 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        self.sold_heifers: List[HeiferIII] = []
Yes, the type annotation is needed here to remind us that we would only add HeiferIII objects to this list later on. Hopefully, the editor will flash a warning when we add an object of a different type. The type checker cannot infer what the desired type is from an empty list.

2023-02-14 22:33 UTC, YijingGong requested changes
Great job, Loi. That's a lot of work. Thank you for your efforts. I really like how you make a lot of functions much more concise and readable. I also made some minor comments on the code.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    keep_female_calf_rate: int
This should be a float. It's a ratio (0-1)

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    user_define_tai_length: int
The current structure is: Heifers have 3 repro methods (ED, TAI, Synch-ED). TAI has 2 sub-methods (5dCG2P and 5dCGP), and Synch-ED has 2 sub-methods (2P and CP). Similarly, cows have 3 repro methods (ED, TAI, ED-TAI). TAI has 4 sub-methods (OvSynch 56, 48, 72, and 5d) as you wrote here. Currently, if a heifer/cow uses the TAI method, no matter which sub-method she uses, she has the same TAI_conception_rate. 

So 1) I am curious why you determine to separate the 5dCG2P_conception_rate and 5dCGP_conception_rate from TAI_conception_rate and separate cows' ovsynch56_conception_rate, etc. as well? Did Kristan suggest you to do so?
2) In addition, in Manfei's branch, the user-defined variables are deleted. I don't think we have the user-defined repro method now. 
3) I think you forget the TAI_conception_rate_1 (conception rate for cows' first service) and TAI_conception_rate_sub (conception rate for cows' second+ service)

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    TAI_related: Dict[str, Union[float, str]]
Not sure what is the different between those 2 structures. About which way is more efficient. probably talk to other software engineers? or could you explain what's the difference and advantages of both? Maybe we can discuss during our Wednesday meeting.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    tai_program_start_day: int
tai_program_start_day should be under farm level -> repro -> TAI_related

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    num_21_days_repro: int
This one seems not used in the code. Can be deleted

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    std_gestation_len: int
I think it might be good to move this avg_gestation_len and std_gestation_len to the section of # from_literature -> repro. Also, the type might be good to be consistent with avg_estrus_cycle_heifer and std_estrus_cycle_heifer. Int might be ok, but maybe float would be more general for like 1.5.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    avg_estrus_cycle_p: float
variable name of avg_estrus_cycle_after_pgf might be more descriptive.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    cull_day_count: List[float]
this should be int. It is day.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +GenericAnimal = TypeVar("GenericAnimal", bound=Union[Calf, HeiferI, HeiferII, HeiferIII, Cow])
To be honest, I am not very familiar with the typing class. Do you think it might be good to ask for a review from one more software developer? Or maybe we can use the Wednesday meeting to talk about this, or schedule a separate meeting.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +GenericAnimal = TypeVar("GenericAnimal", bound=Union[Calf, HeiferI, HeiferII, HeiferIII, Cow])
I guess I get the idea that it is checking the type of objects, but not sure about the details like TypeVar and Union.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> -    # statistics
Just trying to understand, could you explain why you delete all those variables without .self? Are they originally used in the life_cycle_report.py to get the values?

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
>      }
why this is outside (and the below avg_calving_to_preg_time and cull_reason_stats) while everything is inside of init function too?

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +    #  calving_interval attribute is present, maybe set that to true instead?
In terms of your question that 'use_input_calving_interval' is false but 'calving_interval' attribute is present, they are not related. The attribute of 'calving_interval' will always be present in the json no matter 'use_input_calving_interval' is true or false. 

I believe the logic of the original code is correct. If the 'use_input_calving_interval' is true, use the user-input calving interval, else, use the calving interval from the database initialization.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        return animals
Nice! Very concise!

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        preg_heifer_num = 0  # TODO: Seems unused after calculation
It is used to calculate 'avg_breeding_to_preg_time' (line 374-378 in left hand side old code).

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
>      }
I think I get it. They are used in later _reset_parity() and _reset_cull_reason_stats() functions, right?

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        self._reset_cull_reason_stats()
I am thinking do we need these two functions? Since life_cycle_manager object will be initialized every day in the animal_management.py, which means every day, the parity and cull_stats will be reset to zero already. I might be wrong. Maybe further testing is needed.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +                                                                               total_animal_num)
Love those 4 functions. Beautiful.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        life_cycle_daily_herd_update = {key: vars(self)[key] for key in life_cycle_daily_herd_update_keys}
Very cool. To enhance my understanding, Is this supposed to get the values from the class and later can be accessed in the life_cycle_report? But it seems to be locol (not public)? Or it is made public using the info_map? Can you explain a little bit the logic and syntax here?

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +
I believe those two functions should be after the _cull_cows_and_record_stats() because the _cull_cows_and_record_stats() function can change the cow number in the herd.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        # self.CIDR_count += heiferII.CIDR_count  # TODO: add CIDR count to heiferII
Why this is commented out?

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        sell_threshold = 1.03
I think it might be good to make the buy_threshold and sell_threshold user-input variables. I can bring this up for discussion.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +                removed_cows_idx.append(index)
If I have this removed_cows_idx.append(index), and later Utility.remove_items_from_list_by_indices(cows, removed_cows_idx), why do I still need to keep the ids_removed?

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +    def _calculate_cow_percentages(self) -> None:
Like this function. Very concise.

2023-02-14 22:33 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        while len(heiferIIIs) + len(cows) > self.herd_num * sell_threshold and len(heiferIIIs) > 0:
I previously found there was an inconsistency between len(cows) and cow_num, which I think was because the old code used the `del` in the loop to delete the animals. Since you modified that already, I guess now it should be fine. But just want to point this out. 

So I am thinking maybe there's no need to use both (cow_num and len(cows)) in the life_cycle.py, which causes confusion and potential problems. What do you think?

2023-02-14 22:59 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +                removed_cows_idx.append(index)
I understand this point. Since the daily update function is being used somewhere else  (in animal_management.py, I think) and ids_removed is one of the return variables, we would need to remove it here and there at the same time.

2023-02-15 05:16 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +                removed_cows_idx.append(index)
I see. Sounds good

2023-02-16 15:20 UTC, ltp23 commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    user_define_tai_length: int
Thanks Yijing for the details. Here, I was just listing out the attributes I saw in the `animal_management_animal.json`. Would you like to update that JSON file in lines 37-57, just because I don't understand the subject matter enough? Then, I would update the typed dictionaries accordingly.  

The purpose of all the typed dictionaries is to guard against using undefined keys, so there is a need for an exact match between what is in the JSON file and what is in the type dicts definition.

2023-02-16 15:51 UTC, ltp23 commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    TAI_related: Dict[str, Union[float, str]]
So, in the `animal_management_animal.json`, we have the following:

```
{
    "herd_information": {
        ...
    },
    "animal_config": {
       "management_decisions": {
           ...
       },
       "farm_level": {
           "calf": {
                ...
            },
            "repro": {
                "ED_related": {
                    ...
                },
                "TAI_related": {
                    ...
                 }
            }
       },
       "from_literature": {
           ...
        }
   },
   ...
}
```

The two keys `ED_related` and `TAI_related` are nested two levels deep, but when we define and use the config object, we want to flatten it all out. So we go from `animal_config -> farm_level -> repro -> ED_related & TAI_related` in the JSON object to just `animal_config -> ED_related & TAI_related` in the config object.  It may seem complicated, but you don't need to worry about it because these two keys are only there for completeness' sake.

2023-02-16 15:58 UTC, ltp23 commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    user_define_tai_length: int
Alternatively, I think it's probably better to make a separate pull request to address the contents of the JSON file along with your suggestions for buy/sell thresholds.

2023-02-16 16:03 UTC, ltp23 commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    tai_program_start_day: int
It's fixed now.

2023-02-16 16:04 UTC, ltp23 commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    num_21_days_repro: int
I could only delete the `num_21_days_repro` key. The other three are used in `heiferII.py`.

2023-02-16 16:08 UTC, ltp23 commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    std_gestation_len: int
I changed the type to float for these two attributes and moved them to be under the `from_literature -> repro` section.

2023-02-16 16:23 UTC, ltp23 commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    avg_estrus_cycle_p: float
OK. I changed `avg_estrus_cycle_p` to `avg_estrus_cycle_after_pgf`, and `std_estrus_cycle_p` to `std_estrus_cycle_after_pgf`.

2023-02-16 16:25 UTC, ltp23 commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    cull_day_count: List[float]
It's fixed now, and I fixed the type above too.

2023-02-16 16:34 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +GenericAnimal = TypeVar("GenericAnimal", bound=Union[Calf, HeiferI, HeiferII, HeiferIII, Cow])
I added some descriptions. Hopefully, it helps clarify a bit more.

2023-02-16 17:56 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> -    # statistics
Before those variables were class variables, i.e., they were defined right under the class name. So I moved them into the `__init__` function to make them instance variables. Class variables are shared among all the objects of the class, whereas instance variables are associated with a specific object.

In the case of the LifeCycleManager class, as we have here, I think it's ok to go with the previous design of using class variables too. It is likely that we only have one LifeCycleManager object, so it doesn't matter. 

Also, both class variables and instance variables can be used with `self.`.

2023-02-16 17:57 UTC, YijingGong commented on RUFAS/routines/animal/animal_typed_dicts.py
> +    user_define_tai_length: int
ohhhh, I see. We are looking about the different json files... I will slack you about it.

2023-02-16 18:10 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
>      }
Same as above.

2023-02-16 18:21 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +    #  calving_interval attribute is present, maybe set that to true instead?
That makes sense and I agree. It is easier to always have a calving interval in the JSON file and we can decide to use it or not, instead of adding or removing it depending on the true/false value of use_input_calving_interval.

2023-02-16 22:01 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        self._reset_cull_reason_stats()
Generally, manager classes tend to be instantiated once, i.e., only have only one object. Of course, we could create many objects out of a class, but the expected pattern of usage is to have only one manager object.

2023-02-16 22:49 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        life_cycle_daily_herd_update = {key: vars(self)[key] for key in life_cycle_daily_herd_update_keys}
Yes, the `vars()` function will return a dictionary that contains object attributes, and you can look things up using keys. What you see here is the results being recorded to the output manager (the variable `om`).

2023-02-16 22:59 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +
I moved those two functions down as you suggested. 

This is a good reminder for me to keep functions side-effect free (no changes to `self` variables) and make them return values instead. This way, any changes to the `self` variables only happen in one or a few places like in the `daily_update()`.

2023-02-16 23:05 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        # self.CIDR_count += heiferII.CIDR_count  # TODO: add CIDR count to heiferII
The current version of HeiferII class in the master branch doesn't have the `CIDR_count` variable.

2023-02-16 23:09 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        sell_threshold = 1.03
We can add these two parameters to the json files later.

2023-02-16 23:22 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        while len(heiferIIIs) + len(cows) > self.herd_num * sell_threshold and len(heiferIIIs) > 0:
I think this depends on what `cow_num` means. Does it always reflect the current size of the `cows` list? I don't fully grasp how these two variables correlate yet.

2023-02-16 23:23 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +    #  calving_interval attribute is present, maybe set that to true instead?
Yijing clarifies this point below so I have this TODO removed.

2023-02-16 23:29 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
>          Args:
Yes, I will update the docstring style from the Google style to the Numpy style. I will add some more text to the docstrings. We can always update them as we go along.

2023-02-24 18:12 UTC, YijingGong commented
Good job! I think it looks good now. Just a few follow-up discussions and one thing you need to change.

2023-02-24 18:13 UTC, YijingGong requested changes

2023-02-24 18:13 UTC, YijingGong commented on input/animal/animal_feed_management.json
> +					0.54, 0.62, 0.70, 0.77, 0.84, 0.92, 1],
Just curious, what's the difference between the new version and the old version?

2023-02-24 18:13 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/cow.py
>                  AnimalBase.config['std_estrus_cycle_p'], sim_day)
I think you forgot to change the 'std_estrus_cycle_p' to the same format as avg

2023-02-24 18:13 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        # self.CIDR_count += heiferII.CIDR_count  # TODO: add CIDR count to heiferII
I see... It will come later in the new repro branch. We can worry about it later.

2023-02-24 18:13 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        sell_threshold = 1.03
Issue submitted

2023-02-24 18:13 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        while len(heiferIIIs) + len(cows) > self.herd_num * sell_threshold and len(heiferIIIs) > 0:
`cow_num` should be the number of lactating cows in the herd on this simulation day. At the same time, the `cows` list keeps the ids of the cows in the herd on this simulation day. So I believe they should be the same. You deal with it in `_cull_cows_and_record_stats` function, if the cow is culled, you delete her id from the list. If she is not culled, you use `_handle_cow_body_weight_and_parity` to count how many cows are there.

2023-02-24 23:08 UTC, ltp23 commented on input/animal/animal_feed_management.json
> +					0.54, 0.62, 0.70, 0.77, 0.84, 0.92, 1],
It's the same, but with the typo fixed (unkown -> unknown)

2023-02-25 04:25 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/cow.py
>                  AnimalBase.config['std_estrus_cycle_p'], sim_day)
You are right. I'll fix it.

2023-02-25 05:08 UTC, ltp23 commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        while len(heiferIIIs) + len(cows) > self.herd_num * sell_threshold and len(heiferIIIs) > 0:
This can potentially become a difficult bug to track. The count of each animal type can get out of sync with the size of their list. 

At the start of the `daily_update()`, should we reset all the counts (e.g., `self.calf_num`, `self.heiferI_num`, ...) to 0?

2023-02-27 16:13 UTC, YijingGong commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +        while len(heiferIIIs) + len(cows) > self.herd_num * sell_threshold and len(heiferIIIs) > 0:
Yes, at the start of the `daily_update()`, those counts (e.g., `self.calf_num`, `self.heiferI_num,` ...) should be reset to zero. Because they are supposed to count the animal number of today. 

As I commented, I found this bug was due to the old code using the `del` in the loop to delete the animals. Since it was modified, maybe now we don't have this bug. But it would be good to keep it in mind. And if we can test this in the unit test, or talk about the possibility to use`cow_num` instead of `len(cows)`, it might be better.

2023-02-27 16:14 UTC, YijingGong commented on input/animal/animal_feed_management.json
> +					0.54, 0.62, 0.70, 0.77, 0.84, 0.92, 1],
I see the typo now... Really hard to find lol

2023-02-27 16:23 UTC, YijingGong commented
I think this PR looks good to me now. It looks like you need to re-request the review and I can approve it? Anyway, I am ok to merge it.

2023-03-01 20:30 UTC, YijingGong approved these changes
Looks good to me!

2023-03-02 20:37 UTC, KFosterReed commented
Hi team! I had a bit of extra time today and wanted to take a look at this PR. Looking at the code, the clarity and documentation is leagues above where it was before. Kudos for that and thank you for all the work to get to this stage! When I ran the model however, it looks like there is something wrong with the outputs because the animal numbers returned in the outputs are continuously increasing instead of tracking the current herd demographics. See the image below.  
![image (1)](https://user-images.githubusercontent.com/41019131/222545684-1852bc5b-cd38-47a0-919e-5fda89d59411.png)

I am assuming that this is just in the outputs because it should cause other problems in the model (i.e. create more and more pens!) if it was actually simulating 120,000 heiferI animals after 1 year. So hopefully it will be a relatively easy fix :)

2023-03-02 22:11 UTC, YijingGong commented
As reminded by Kristan, I checked other outputs of the life cycle part. Besides the increase in the count of all animal classes,  the same pattern is also found in culled animal number (culled_cow_num, culled_heifer_num), sold animal number, animal number for each parity, number of hormone injections, number of pregnancy checks, number of ai. 

However, I found that the culled cow number for the 8 different reasons is correct. So it's likely related to how you initialize the variables. For the cull_reason, you set them to zero at 2 places (under the `class LifeCycleManager` and the `def __init__(self, data: AnimalConfigTypedDict)` function).

For most other variables, you only set them to be zero in the `def __init__(self, data: AnimalConfigTypedDict)` function.

Another thing I found weird is the animal initialization:
<img width="784" alt="Screenshot 2023-03-02 at 4 00 25 PM" src="https://user-images.githubusercontent.com/51036031/222568357-47586f1b-c7cc-4b9c-8a8a-6f7b330e1815.png">

<img width="799" alt="Screenshot 2023-03-02 at 4 02 00 PM" src="https://user-images.githubusercontent.com/51036031/222568625-724f0d90-0815-4744-ad6d-1d91efe55b12.png">

<img width="798" alt="Screenshot 2023-03-02 at 4 02 09 PM" src="https://user-images.githubusercontent.com/51036031/222568687-4cfd918e-9281-4b95-aa82-aff164e83693.png">

It looks like the program initializes with cows only with fresh first lactation cows and cows in parity 3 or higher. During simulation, some cows in parity 1 grow to parity 2.

2023-03-06 20:00 UTC, JoeWaddell commented
To build on the comments here: looking through the graphics output, there's many places related to the bug in the total number of animals. I'm still troubleshooting, but wanted to add a couple example figures that should be instructive. 

Below is from this branch: not only does the number of animals increase, but so does the percentage! 40,000% is certainly not correct. 
![image](https://user-images.githubusercontent.com/109082924/223535638-b7f33a97-7506-4872-90bd-9ba385641513.png)

Related, is that the cull percentage is shrinking. Below is from this branch: 
![image](https://user-images.githubusercontent.com/109082924/223216387-80906abc-b868-4778-81d4-7276c1eb4741.png)
It seems like the value being referenced here for the denominator/total in the percent calculation is just constantly increasing, like the figures in Kristan's comment. 


Below is from the master branch. The reported ranges are percentages from 0-100% of the total culled animals, which is correct. 
![image](https://user-images.githubusercontent.com/109082924/223217089-20f39e6f-b66d-464c-bf03-f36010b77935.png)

Cow percent also reports reasonable values in the master branch: 
![image](https://user-images.githubusercontent.com/109082924/223535940-243c11f9-d866-4ab1-97e7-1d2625cbd0ce.png)

2023-03-09 16:46 UTC, JoeWaddell approved these changes
This looks great: with the new function that resets the animal numbers, fixing the bug reported in the comments, it looks ready to merge.

2023-03-10 18:09 UTC, merged