Refactor and test percolation.py in the Soil module
RuminantFarmSystems/RuFaS pull request #328
Opened 2023-02-03 20:02 UTC by Isgotkowitz

# Summary
This PR refactors the `Percolation` module (`percolation.py`) of the `Soil` module from SWAT 2:3.2. It is entirely comprised of `@staticmethods` except for the main routine (`percolate()`) that does the calculations and updates for an object instance. 

Every method in `Percolation` is tested, however `test_percolate_between_layers()` takes on a sequential format instead of the usual format: using multiple sets of parameters. `test_percolate_between_layers()` aims for full code coverage by testing 3 different cases, all of which are spelled out in its docstring.

# Other Changes
- `Infiltration` has been slightly refactored to use the new `temperature` attribute of `LayerData` objects instead of accepting a parameter in the main routine to determine if the top layer of soil is frozen or not. `test_infiltration.py` has also been updated to reflect these changes
-  `Infiltration` has had a missing docstring added to a static method
- the `LayerData` module has had several attributes and `@property` methods added that are used in `Percolation` (and possibly other modules), some attribute names have been changed, method signatures now have return types, and it now uses a `__post_init__` function to initialize mutable variables that are dependent upon other variables in the class
- `soil_water_content` inside the `LayerData` module has been modified so that it is now mutable. This has been achieved by changing it from being calculated by an `@property` method to initializing it as none, and adding a `__post_init__()` method to calculate its initial value as soon as a `LayerData` object is created.
- the `SoilData` module has two attributes added for use in `Percolation`: a `LayerData` object representing the vadose zone, and a time_step over which percolation occurs. There is a correction made to `profile_soil_water_content()` so it is now correctly lower bounded at 0. It now includes a `__post_init__` method that will initialize its `soil_layers` and `vadose_zone_layer` 
- `Soil` has had the initialization of its soil layers removed, because that is now done inside the `SoilData` class
- All files have had their units changed so they are displayed as `(...)` instead of `in ...`

2023-02-07 00:40 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +        for i in len(self.data.soil_layers):
I think you're missing a call to `range()`.

2023-02-08 16:30 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +        for i in len(self.data.soil_layers):
Yes

2023-02-08 23:36 UTC, morrowcj requested changes
This is a great start. I think one more round of revision will greatly improve it.
* All of the static methods look good to me
* Most of my comments involve `percolate`. Look over them and let me know what you think.
* I've added a file to the PR as a supplement to the comments, which should be deleted once you make a decision regarding its contents.

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/infiltration.py
> +        if self.data.soil_layers[0].temperature <= 0:
I wonder if we'll need to account for frozen soil elsewhere. If so, it might be nice to have a similar `SoilData.is_frozen` variable.

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +        (2:2.3.17)"""
```suggestion
        (SWAT 2:2.3.17)"""
```

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
>          """volume of water in layer when at wilting point"""
```suggestion
    def wilting_point_content(self) -> float:
        """amount of water in layer when at wilting point (mm)"""
```

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
>      """water concentration of soil layer at saturation point (mm)"""
Just to make this a bit clearer, since water is measured in a confusing unit:

```suggestion
    field_capacity_water_concentration: float = 0.3  # arbitrary
    """water concentration of soil layer at field capacity (mm water / mm soil)"""
    wilting_point_water_concentration: float = 0.2  # arbitrary
    """water concentration of soil layer at wilting point (mm water / mm soil)"""
    saturation_point_water_concentration: float = 0.5
    """water concentration of soil layer at saturation point (mm water / mm soil)"""
```

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
>          """volume of water in layer when saturated in mm"""
Let's stick to the unit style used elsewhere.

```suggestion
        """volume of water in layer when saturated (mm)"""
```

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +                """upper layer is not the bottom layer of the soil profile"""
Can we reserve quote comments for docstrings or multi-line standalone comment/note blocks?

```suggestion
        for i in range(len(self.data.soil_layers)):  # iterate through each layer of soil in the soil profile
            upper_layer = self.data.soil_layers[i]
            if i != (len(self.data.soil_layers) - 1):  # upper layer is not the very bottom layer of the soil profile
```

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +        for i in range(len(self.data.soil_layers)):
I also like to use `i` by default for iterators, but the team wants to move away from this. Use a short word to indicate what the iterator represents. `layer` or `layer_num` would be appropriate here.

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +class Percolation:
I think the logic in the `percolate()` method can be improved. See the file I added (`TMP_alternative_percolates.py`) and let's discuss externally.

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +                        has_seasonal_high_water_table):
```suggestion
                can_percolate = self._determine_if_percolation_allowed(
                        lower_layer.soil_water_content,
                        lower_layer.field_capacity_content,
                        lower_layer.saturation_content,
                        has_seasonal_high_water_table)
                if upper_layer.temperature > 0 and can_percolate:

```

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +                    if upper_layer.temperature > 0:
checking the same condition twice.

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +            return amount_to_percolate
bound to zero
```suggestion
            return max(0, amount_to_percolate)
```

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    soil_water_content:  Optional[float] = None
```suggestion
    water_content:  Optional[float] = None  
```

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +                        has_seasonal_high_water_table):
Furthermore, I'd recommend including the temperature check in `_determine_if_percolation_allowed()`

2023-02-08 23:36 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/tests_SC/TMP_alternative_percolates.py
> +
```suggestion
```

2023-02-09 15:40 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/infiltration.py
> +        if self.data.soil_layers[0].temperature <= 0:
I think `infiltration.py` is only dealing with how much of the water from the environment makes it into the soil, and `percolation.py` deals with how the water moves down once it is in the soil. So we only have to worry about frozen soil beneath the surface layer in `percolation.py`

2023-02-09 15:41 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +        (2:2.3.17)"""
Nice catch

2023-02-09 15:43 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
>      """water concentration of soil layer at saturation point (mm)"""
Whatever we can do to make the water units less confusing, I am all for it

2023-02-09 15:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
>          """volume of water in layer when saturated in mm"""
Ok

2023-02-09 16:11 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
>          """volume of water in layer when saturated in mm"""
All units in all files inside `Crop_and_Soil/soil/` have now been made consistent

2023-02-09 16:12 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +                """upper layer is not the bottom layer of the soil profile"""
Yes. Are quote comments the ones that are going to be automatically put in the documentation?

2023-02-09 16:17 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +                """upper layer is not the bottom layer of the soil profile"""
I believe all instances of this have now been corrected

2023-02-09 16:22 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +        for i in range(len(self.data.soil_layers)):
Ok, will do

2023-02-09 16:26 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +                    if upper_layer.temperature > 0:
Whoops

2023-02-09 16:29 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +                        has_seasonal_high_water_table):
I think it would be better to keep the temperature check out of `_determine_if_percolation_allowed()` because that method directly corresponds to logic in SWAT

2023-02-09 16:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/percolation.py
> +            return amount_to_percolate
Ok

2023-02-09 16:36 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    soil_water_content:  Optional[float] = None
Done

2023-02-09 21:02 UTC, morrowcj approved these changes

2023-02-09 21:02 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_percolation.py
> +        3: when the upper layer does not not have any water that can be percolated to the lower layer
I like this.

2023-02-10 19:22 UTC, morrowcj reviewed
I found a few documentation spots that could be improved while looking at #336.

2023-02-10 19:22 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    """volume of soil water in the layer (mm)"""
```suggestion
    """water present in the layer (mm)"""
```

2023-02-10 19:22 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    """temperature of soil layer (degrees Celsius)"""
```suggestion
    """current temperature of this soil layer (degrees Celsius)"""
```

2023-02-10 19:22 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    """available water capacity expressed as fraction of total soil volume (unitless)"""
```suggestion
    """available water capacity expressed as fraction of total soil volume [for this layer?] (unitless)"""
```

2023-02-10 19:22 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +        """This function initializes all attributes in the dataclass that depend on other attributes in the class"""
```suggestion
        """Initialize all attributes in the dataclass that depend on other attributes"""
```

2023-02-10 19:22 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    """Datalayer object that represents the vadose zone, arbitrary top and bottom depths, starts with no water"""
```suggestion
    """LaterData object that represents the vadose zone layer, arbitrary top and bottom depths [still true?], starts with no water"""
```

2023-02-10 19:22 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    """length of time step over which percolatigit adon occurs (hours) """
Is this what you meant?
```suggestion
    """length of time step over which percolation occurs (hours) """
```

2023-02-10 19:48 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    """available water capacity expressed as fraction of total soil volume (unitless)"""
Yeah I don't really understand this attribute either, it gets used for equation 2:3.1.6 but that is only in SWAT, and not the codebase. SWAT says it gets input by the user, but it never gets used in the `Percolation` module so I don't think we even need it.

2023-02-10 19:49 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    """Datalayer object that represents the vadose zone, arbitrary top and bottom depths, starts with no water"""
No, I will update it.

2023-02-10 19:51 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    """length of time step over which percolatigit adon occurs (hours) """
No, I will also update this

2023-02-10 19:53 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    """available water capacity expressed as fraction of total soil volume (unitless)"""
I deleted it and everything still works, so I guess we did not need it.

2023-02-11 00:54 UTC, matthew7838 reviewed
Except for one part that I figure it would be better for me to mention and double check, everything else looks good. Missing documentations in the test files earlier were fixed.

2023-02-11 00:54 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +                                           bottom_depth=10000000,    # bottom depth is 10,000 meters by default
Not sure if this is a mistake, but the number here does not match the 10,000 default value in the commetnts.

2023-02-11 01:03 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +                                           bottom_depth=10000000,    # bottom depth is 10,000 meters by default
Soil depth is in mm. 10k meters is 10M mm

2023-02-13 16:02 UTC, matthew7838 approved these changes

2023-02-13 16:10 UTC, merged