Refactor decomposition.py
RuminantFarmSystems/RuFaS pull request #329
Opened 2023-02-03 21:18 UTC by matthew7838

### **Summary**
This PR refactors the `Decomposition` sub-module (`decomposition.py`) of the `Soil` module from "pseudocode_soil" S.6.A.1 and "pseudocode_soil" S.6.A.2. All methods except the main routine are static methods.

Every method is tested covering possibly most edge cases.

### **Changes**

-  Except for the main routine `decompose`, all other methods are now static
-  Except for the main routine `decompose`, all methods do not rely on any external classes
-  Descriptive names modified and added
-  Tests added for all methods
-  Now only the main routine `decompose` updates and tracks attributes added in the `SoilData` class

### **Other Changes**

- Added property function in the `LayerData` class to calculate the correct water factor

2023-02-09 05:12 UTC, morrowcj approved these changes
# Summary
This looks good. I've requested a few minor changes, referenced in the review comments below. 
Excellent job, Matthew. Keep up the great work!

# Additional Notes
* Excellent job with the main comment on the pull request. It is very descriptive and easy to follow.
* Signatures look good, type hints are present
* The equations match the source documents
* Docstrings look good, everything is as well documented as it can be given the source material
* I appreciate how thoughtful you were with renaming variables.
* The tests all pass, look like the do what they are supposed to, and consider an adequate range of cases.
  - Note that, after updating the signatures of those methods, you'll need to update your tests too, but you
  only will need to update the lines that actually call the method.

2023-02-09 05:12 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +        normalizer = 20.80546
Can we move these variables into the signature as parameters? I think you can also simply the names a bit. You did a great job picking descriptive names, but they can be a bit cleaner. For example, "decomposition" is redundant, since this is the decomposition module and these variables don't get used outside it.

New signature example:

```python
def _calc_temp_factor(temperature: float, x_inflection: float = 15.4, y_inflection: float = 11.75, 
                      point_distance: float = 29.7, inflection_slope = 0.03, 
                      normalizer = 20.80546) -> float:
```

Do something similar for the other static method as well and don't forget update the docstrings.

2023-02-09 05:12 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +                           temp_average - decomposition_inflection_x))) / normalizer)
I know it is written this way in the old code, but I don't think this should be limited to be strictly positive.
I can't find anything in the pseudocode or the referenced excel models to suggest that it should be 
positive. Did you? The name "temperature effect on decomposition" implies that it can have a positive or negative effect. 

Otherwise, the math looks right.

2023-02-09 05:12 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +        return hold
What is "hold"? Also, there's no need to save this, just directly return:

```suggestion
            return (base_1 ** dimensionless_empirical_factor_e1) * (base_2 ** dimensionless_empirical_factor_e2)
```

2023-02-09 05:12 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +        dimensionless_empirical_factor_e2 = 3.22
just call these `a_term`, `b_term`, `c_term`, `first_exponent`, `second_exponent` for now.

2023-02-09 05:12 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +
I'm going to make a commit adding a TODO for future reference.

```suggestion
# TODO: the equations for this model, referenced in the soil psuedocode, are derived from the excel file
#   located on basecamp: https://3.basecamp.com/3486446/buckets/5296287/vaults/2740532358
#   but the meaning (and validity) of the terms is extremely unclear from either source. The 
#   documentation cannot be adequately completed without a better understanding of these methods.
```

2023-02-09 05:17 UTC, morrowcj requested changes
Sorry, I accidentally selected "approve" when I meant to request changes.

2023-02-09 07:36 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +                           temp_average - decomposition_inflection_x))) / normalizer)
I think it is reasonable to say that it will always be between 0 a 1.2 for two reasons. The first is provided by the graph in the excel file, and the second is that the function in S.6.A.1 involves the inverse of a tangent, therefore I think as temp get's lower it will get infinitely close to 0 and infinitely close to 1.2 as the temperature gets higher.

2023-02-09 15:56 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +                           temp_average - decomposition_inflection_x))) / normalizer)
@matthew7838, the graph for this function ("tfunc" tab in the excel sheet) is for the temperature ranges of -10 to 60 degrees C. Note that values $\leq$ -15 degrees C (5 degrees F) give negative results. These temperatures values occur in much of the midwest, so we can't discount them. Second, those values are based heavily on the parameter values other than temperature. The values that are hard-coded are only one parameterization of the model but we need to plan for other parameterizations as well.

The limits of arctan(x) are $(-\frac{\pi} { 2},~\frac{\pi}{2})$.

So, the only reason this function should have a lower-limit of 0 is if the equation returns the "actual rate of decomposition" and not the "effect of temperature on decomposition." I'm not positive which is true, since there's no documentation in the original model. But I'm inclined to believe it is the latter, since the title of the graph and the pseudocode reflect that.

2023-02-09 23:49 UTC, Isgotkowitz requested changes
Good first PR. There are a couple of formatting issues in the docstrings that need to corrected, and some changes need to be made in `_calc_moisture_factor()`, but other than that looks good.

2023-02-09 23:49 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +    def _calc_moisture_factor(soil_layers: List[LayerData]) -> float:
First, I think it would be better to have `_calc_moisture_factor()` only take the `water_factor` attribute instead of the entire `LayerData` object - in general it is good to only pass what is needed to a method.

Second (and this is less important), I prefer to pass one value at a time to methods and make the calling method handle the multiple return values. This would be helpful for someone in the future who wants to model something this method, but doesn't need to use it on a whole list of attributes.

2023-02-09 23:49 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +            hold = (base_1 ** dimensionless_empirical_factor_e1) * (base_2 ** dimensionless_empirical_factor_e2)
What is this method supposed to be doing? Because currently, it iterates through `soil_layers`, calculates stuff based on the current layer, then moves on to the next without doing anything with it. So the only value that gets returned is the `hold` of the bottom layer

2023-02-09 23:49 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +        Returns: unitless moisture effect
```suggestion
        Returns: moisture effect (unitless)
```
I know it is a pain but it is good to keep the style of documentation as consistent as possible across the codebase

2023-02-09 23:49 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +            temp_average: Average temperature
Needs units here

2023-02-09 23:49 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_decomposition.py
> +    decomp = Decomposition(data)
These objects are not necessary for an `@staticmethod` test

2023-02-09 23:49 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_decomposition.py
> +    assert decomp._calc_moisture_factor(layers) == hold
```suggestion
    assert Decomposition._calc_moisture_factor(layers) == hold
```

2023-02-09 23:49 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    decomposition_moisture_effect: Optional[float] = None
These should both have docstrings beneath them

2023-02-09 23:49 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +        """volume of water in layer when saturated in mm"""
I don't think that is what's being calculated here

2023-02-09 23:49 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +                        self.saturation_content - self.field_capacity_content)
If this comes from an equation in the documentation, there should be a reference to it

2023-02-15 22:02 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +            hold = (base_1 ** dimensionless_empirical_factor_e1) * (base_2 ** dimensionless_empirical_factor_e2)
@morrowcj Not sure what this method is supposed to be doing.

2023-02-16 18:00 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +            hold = (base_1 ** dimensionless_empirical_factor_e1) * (base_2 ** dimensionless_empirical_factor_e2)
@matthew7838, the old code calculates the moisture for each layer and saves the output as an attribute **of that layer's object**. 

You'll ultimately want to do the same thing, but break the functionality down:
* first make the `_calc_moisture_factor()` method act on a single layer.
* then, from the main method, apply it to *each layer*, saving the results within the layer. 

Here's a hint (simplified):

```python
class Decomposition:
    def decompose(self, temp_average): -> None:
        for layer in self.data.soil_layers:
            layer.moisture_decomposition_factor = self._calculate_moisture_factor(layer.water_factor)
    
    def _calculate_moisture_factor(water_factor, a=0.55, b=1.7, c=-0.007, e1=6.65, e2=3.22) -> float:
        return ((water_factor - b) / (a - b))**e1 * ((water_factor - c) / (a - c))**e2
```

2023-02-21 18:51 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +from SC_redesign.Crop_and_Soil.soil import soil_data
Is this import statement necessary?

2023-02-21 19:12 UTC, Isgotkowitz requested changes
Good stuff, getting very close to being finished. My comments are on how default values should be handled by methods, and some minor things in docstrings

2023-02-21 19:12 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +            temp_average: Average temperature to pass in the _calc_temp_factor(temp_average) function
In docstrings for main routines I don't think it is necessary to say what it is used for, just what it is. Also it should have units

2023-02-21 19:12 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +    def _calc_temp_factor(temp_average, x_inflection: float = 15.4, y_inflection: float = 11.75,
Why are these being declared as parameters? If they are the same for every layer of soil and work for all soil profiles then they should be hardcoded into the method. If they are features of a soil profile/layer and a user may want to modify them based on the data they are working with, they should be attributes in either `SoilData` or `LayerData` (set to the values used here as defaults) and passed to the main routine as parameters

2023-02-21 19:12 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +    def _calc_moisture_factor(water_factor, a_term: float = 0.55, b_term: float = 1.7,
Same as above comment, these should not just be declared as parameters in the method signature with no way for a user to modify them

2023-02-21 19:12 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    """moisture effect on decomposition factor (unitless) (pseudocode_soil S.6.A.2)"""
It is good style to group attributes used by the same module together and label them
```suggestion
    
    # --- Decomposition
    decomposition_moisture_effect: Optional[float] = None
    """moisture effect on decomposition factor (unitless) (pseudocode_soil S.6.A.2)"""
```
This is a pretty old version of `LayerData` so if you want to see more examples you should check the `SC_redesign` branch

2023-02-21 19:58 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +    def _calc_temp_factor(temp_average, x_inflection: float = 15.4, y_inflection: float = 11.75,
These were changes requested by Clay in previous requested changes, they were orginially hardcoded since I don't think they're suppose to be modified.

2023-02-21 19:58 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +    def _calc_moisture_factor(water_factor, a_term: float = 0.55, b_term: float = 1.7,
same as above

2023-02-21 20:16 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +    def _calc_temp_factor(temp_average, x_inflection: float = 15.4, y_inflection: float = 11.75,
Ok, I just asked Clay about it too. I think they are good for right now, maybe make an issue in the Soil and Crop Redesign project and mark it as a Future Issue so we don't forget about it?

2023-02-21 20:29 UTC, Isgotkowitz approved these changes
Nice

2023-02-21 21:14 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/decomposition.py
> +    def _calc_temp_factor(temp_average, x_inflection: float = 15.4, y_inflection: float = 11.75,
To follow up (@Isgotkowitz, @matthew7838), this is because this is just a single parameterize of the model (these values were selected because they best fit a specific dataset). Rather than being hard-coded, these methods should provide an option for alternative parameterizations of the model.

As an example, the moisture function `calc_moisture_factor` has three parameterizations in the excel file for different grades of soil:
![image](https://user-images.githubusercontent.com/25436787/220459981-5b2f2c6f-e360-4478-93a8-a73ba1f6188a.png)

2023-02-21 21:15 UTC, morrowcj approved these changes
Looks good to me. Thank you for your hard work, Matthew! You are free to merge.

2023-02-21 21:42 UTC, merged