Refactor and test `soil_temp.py`
RuminantFarmSystems/RuFaS pull request #336
Opened 2023-02-08 18:54 UTC by Isgotkowitz

# Summary
This PR refactors the `SoilTemp` module (`soil_temp.py`) in the `Soil` module based on section 1:1.3.3 of SWAT. It contains only `@staticmethods` except for `daily_soil_temperature_update()`, which is the main routine of this module. 

Every method is tested, and in the test for `daily_soil_temperature_update()` the method is run twice, to test that the method works initially (no previous day temperatures present) and for all calls after the first (when there is a temperature for the previous day recorded)
# Note
This PR should only be merged *AFTER* #328. All changes can be ignored in 
- `evapotranspiration.py`
- `infiltration.py` and `test_infiltration.py`
- `percolation.py` and `test_percolation.py`
# Changes
All of the below files have changes from both this PR and #328. For all changes that should be ignored, it should be assumed that they will be reviewed for #328
- `soil_data.py`: the only changes that need to be reviewed for this PR are the addition of the `@property` `profile_bulk_density()` method. All other changes should be ignored.
- `soil.py` has had an import statement and attribute added for `SoilTemp`. All other changes should be ignored.
- `layer_data.py` has had two attributes added, both under the comment `# ---- Temperature`. All other changes should be ignored.

2023-02-10 17:40 UTC, matthew7838 approved these changes
Looks pretty good to me, caught another missing comment in the tests, but other than that seems good. The reference is clear enough for me to double-check the calculations.

2023-02-10 20:46 UTC, morrowcj requested changes
# Summary
This looks great. I'm requesting some minor changes, mostly in reference to documentation. Hopefully we can merge these today.

# Other Comments
* I just noticed that the comment block on lines 5-8 of `layer_data.py` could be used as the main docstring for the class 
(i.e., move it right below `class LayerData:` [line 12]). What do you think?

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +        """depth beneath the surface of the center this layer (mm)"""
```suggestion
        """depth beneath the surface to the center of this layer (mm)"""
```

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    # TODO: check above definition with a SME because all I did to get it was google 'soil albedo'
This is correct, but I'd reword:

```suggestion
    albedo: float = 0.16
    """proportion of solar radiation that is reflected by the soil surface (unitless)"""
```

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    to 1, inclusive. SWAT sets the lag coefficient to 0.8 (paragraph between equations 1:1.3.3, 4) (unitless)
I know this is what SWAT calls this, but from a temporal modelling point-of-view, this is **not** a lag term. It is more closely related to an auto-regression parameter. Specifically, it is a proportional scalar that "determines the **_realtive_** magnitude of the effect of the previous day's temperature on the current day's temperature". `previous_temperature_effect` would be a better name.

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +        Returns: total amount of water contained in the soil profile at field capacity (but not saturated) (mm)
for emphasis:
```suggestion
        Returns: total amount of water contained in the entire soil profile at field capacity (but not saturated) (mm)
```

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +        """
You can document `@properties` as though they are regular attributes if it makes sense to do so.

```suggestion
        """average bulk density of the soil profile based on the bulk density of each soil layer, weighted by
            the thickness
        """
```

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +#     df = depth factor
Delete all of this commented stuff (through line 322), it is stale.

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +        self.data = soil_data or SoilData()
docstring for `soil_data`

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +            avg_annual_air_temp: average annual air temperature (degrees C)
from the perspective of the simulation:

```suggestion
            solar_radiation: solar radiation reaching the ground on the current day (MJ per square meter per day)
            avg_temp: average temperature of the current day (degrees C)
            min_temp: minimum temperature of the current day (degrees C)
            max_temp: maximum temperature of the current day (degrees C)
            plant_cover: total aboveground plant biomass and residue on the current day (kg per hectare)
            snow_cover: water content of the snow cover on the current day (mm)
            avg_annual_air_temp: average annual air temperature (degrees C)
```

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +            avg_annual_air_temp: average annual air temperature (degrees C)
Related: is `avg_annual_air_temp` the average for the entire calendar year, the current calendar year up to the current day (I hope not), or for the last 365 days?

This variable worries me for when we want the model to forecast into the future (not for v1).

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +            soil starts (it sets the previous days temperature equal to the current day's temperature)
Further elaborating:

```suggestion
        Important: SWAT does not specify how to start the simulation i.e. it does not specify what to do on day 0, when
            there is no previous day's temperature. Currently, the implementation just uses the temperature that the
            soil starts (it sets the previous days temperature equal to the current day's temperature). This assumption
            is fairly reasonable due to temporal auto-correlation, but does not account for the random fluctuations
            that can occur throughout the year.
```

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +                                                                             actual_soil_surface_temp)
Simplify?

```python
            if layer.previous_day_temperature is None:
                layer.previous_day_temperature = layer.temperature
            # Alternatively, store in variable and use conditional properties of None:
            # prev_temp = layer.previous_day_temperature or layer.temperature

            layer.temperature = self._determine_average_soil_temperature(self.data.lag_coefficient,
                                                                         layer.previous_day_temperature,  # or prev_temp
                                                                         layer_depth_factor,
                                                                         avg_annual_air_temp,
                                                                         actual_soil_surface_temp)
```

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +        SWAT Reference: 1:1.3.7
Right?
```suggestion
        SWAT Reference: 1:1.3.6
```

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +            albedo: the albedo of the soil (Google says "ratio of reflected to incident solar radiation") (unitless?)
Reflect my comments on albedo doc above.

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +        """calculates the temperature of the soil surface if it were bare
How about this?

```suggestion
        """calculates the temperature at the surface of bare soil.
```

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +            max_temp: maximum temperature of a given day (degrees C)
Change these to "the current day" as before, here and elsewhere that makes sense.

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +            the temperature of the surface soil if it were bare (degrees C)
```suggestion
            bare soil surface temperature (degrees C)
```

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +            lag_coefficient: coefficient that controls influence of previous day's temp on current day's temp (degrees C)
see previous comments about lag.

2023-02-10 20:46 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +            depth_factor: factor that quantifies the influence of depth below surface on soil temp (unitless)
```suggestion
            depth_factor: factor that quantifies the influence of depth below surface on soil temperature (unitless)
```

2023-02-10 22:06 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +#     df = depth factor
Whoops yes sorry about that

2023-02-10 22:22 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +            avg_annual_air_temp: average annual air temperature (degrees C)
I don't know. The most detail I have found about `avg_annual_air_temp` is "average annual air temperature is calculated from  the long-term monthly maximum and minimum temperatures reported in the weather generator input (.wgn) file" on page 42 of SWAT

2023-02-10 22:27 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +                                                                             actual_soil_surface_temp)
Yes, good thinking

2023-02-10 22:27 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +        SWAT Reference: 1:1.3.7
Yup, whoops

2023-02-10 22:29 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +            albedo: the albedo of the soil (Google says "ratio of reflected to incident solar radiation") (unitless?)
Done

2023-02-10 22:31 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    to 1, inclusive. SWAT sets the lag coefficient to 0.8 (paragraph between equations 1:1.3.3, 4) (unitless)
Agreed. I will change it to that. Do you think the docstring is ok as it is?

2023-02-10 22:40 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +        """
Yes that would be better. I was just going along with the docstrings that were being autogenerated for me

2023-02-10 22:49 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +            max_temp: maximum temperature of a given day (degrees C)
Done, I think I got all of them but may not have

2023-02-10 22:51 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_temp.py
> +        self.data = soil_data or SoilData()
I think I have taken care of this

2023-02-11 00:58 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    to 1, inclusive. SWAT sets the lag coefficient to 0.8 (paragraph between equations 1:1.3.3, 4) (unitless)
Yes

2023-02-11 01:20 UTC, matthew7838 reviewed
Looks good, just one reference I would recommend for improving readability.

2023-02-11 01:20 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    bulk_density: float = 1.4
In some of the above docstrings, there are references to where they are in the SWAT. I wonder if the same principle would apply here since unlike `previous_day_temperature`, this is a less intuitive attribute from my point of view. I was able to find reference on SWAT 2:3.1.1.

2023-02-11 01:51 UTC, morrowcj approved these changes

2023-02-13 16:06 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    bulk_density: float = 1.4
Usually I don't think it is necessary to include a docstring for an attribute that is assumed by SWAT to be given in the input and is actually included in some of our inputs. If you check out some of the example soil input files (there are a bunch in `MASM\input\soil\`) you'll see that each layer has a bulk density field. This is in contrast to attributes in `LayerData` like `soil_evaporation_compensation_coefficient`, where SWAT assumes that the user provides it as input but we do not have it in any of our soil data input files.

That said it's a good idea to give users a reference for how SWAT thinks this attribute should be calculated, in the case they want to check it against their own method for calculating bulk density.

2023-02-13 16:21 UTC, merged