Field Management (part 2)
RuminantFarmSystems/RuFaS pull request #346
Opened 2023-02-13 20:03 UTC by morrowcj

This PR is 2 of *N* focused on the management of individual fields. This PR primarily implements the new crop harvest methods. 

## Summary of changes:
* The `Yields` component class was refactored to the `CropManagement` class (crop_management.py) and its methods and attributes were also refactored to facilitate clarity with the new harvest operations.
* Two different harvest operation options were implemented
    - the `HarvestOperation` enum contains the supported operations
    - the logic is implemented in `harvest_crops()` (field.py)
* Dormancy routines have been implemented (PR #365)

## Notes: 
* Some methods are still placeholders as they have not been fully fleshed out
* Some `#TODO`s are notes to guide us in next set of PRs for the field manager. 
* Tests have been fully implemented, except for placeholder methods. In these cases, I have created placeholder tests which call `warnings.warn()` to alert users running `pytest` that the tests still need to be written (once the corresponding methods are complete).

2023-02-21 18:10 UTC, morrowcj commented
Issue #237 was discussed in a recent meeting with @KevinP-B and @KFosterReed. Based on this conversation, I am removing the place-holder method fro assessing feed quality in this PR, since this will be handled by the feed module.

2023-02-22 17:14 UTC, Isgotkowitz approved these changes
Looks like a good design overall. My only design comments are about how store harvest information and where to put water related processes, all other comments are related to workflow

2023-02-22 17:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +                                        adjusted_potential_evapotranspiration)  # TODO: call from Field instead?
Yes, I think it would be better to call this in `Field`

2023-02-22 17:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    cut_biomass: Optional[float] = None
Just to confirm, this should be equal to `yield_collected` + `yield_residue`?

2023-02-22 17:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/harvest_operations.py
> +    HARVEST_NOKILL = "no_kill"
I like the `enum` with different harvest operations, but is there a way to link each value (`HARVEST`, `HARVEST_NOKILL`, etc.) to a set of `bool`s, each corresponding to `cut`, `collect_yield`, and `kill`? Then the code for harvesting crops in `Field` could look more like

`for crop in self.crops:`
`    crop.crop_management.manage_harvest(`
`        cut=self.field_data.harvest_type.cut, `
`        collect=self.field_data.harvest_type.collect, `
`        kill=self.field_data.harvest_type.kill) `

I think this would be a lot cleaner that having an `if` statement for each harvest operation

2023-02-22 17:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/water_dynamics.py
> +    #    No water uptake yet?
Should this be made a priority over refactoring the nutrient cycling directories?

2023-02-22 17:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/heat_units.py
> +    # TODO: Heat scheduling? SWAT 5:1.1.1
Do these have GitHub issues?

2023-02-23 17:31 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    cut_biomass: Optional[float] = None
That is correct.

2023-02-23 17:32 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/field/harvest_operations.py
> +    HARVEST_NOKILL = "no_kill"
That's a really good idea. I think there is a way to do that.

2023-02-23 17:34 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/water_dynamics.py
> +    #    No water uptake yet?
@Isgotkowitz, yeah, I think they probably should. I think the design problems of the water stuff has been prolific enough in all our other PRs that we should get it out of the way.

That will also allow Peter Vadas some time to respond to your questions and for us to plan out the phosphorus sub-module a bit more.

2023-02-23 17:35 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/heat_units.py
> +    # TODO: Heat scheduling? SWAT 5:1.1.1
They do not but are small enough that I was going to do them in the next field management PR (or may even add them before merging this one).

2023-02-24 19:49 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/heat_units.py
> +    # TODO: Heat scheduling? SWAT 5:1.1.1
I've added PR and issue references after all.

2023-03-09 22:07 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +                in canopy in mm
```suggestion
                in canopy (mm)
```

2023-03-09 23:34 UTC, Isgotkowitz requested changes
Good PR. This review was particularly sensitive to extraneous comments and docstrings that may not have been properly formatted (also some that I wrote were pretty low quality and I had the itch to rewrite them). So most of the PR comments revolve around comments, docstrings, and general code clarity; all the logic and design aspects seem sound.

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    """
Have you gotten a chance to look into this at all?

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +This module is primarily based upon the "Crop Yield" (5:2.4) and "General Managmeent" (6:1) sections of the SWAT model
```suggestion
This module is primarily based upon the "Crop Yield" (5:2.4) and "General Management" (6:1) sections of the SWAT model
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +        """crop data object on which crop management operations will be conducted"""
```suggestion
    def __init__(self, crop_data: Optional[CropData] = None):
        self.data = crop_data or CropData() 
        """crop data object on which crop management operations will be conducted. Initialized with defaults if none given."""
```
This docstring should maybe refactored further so that is beneath the method declaration and talks more generally about what it does. I think that would make it more inline with what the NumPy style guide wants.

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +        #   (Not Used)
What is not used?

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +        # argument validation
Unnecessary comment

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +            raise ValueError("collected_fraction must be between 0 and 1 (inclusive)")
```suggestion
            raise ValueError(f"Expected collected_fraction to be between 0 and 1 (inclusive), received '{collected_fraction}'.")
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +    def cut_crop(self, collected_fraction: float = 0):
```suggestion
    def cut_crop(self, collected_fraction: float = 0) -> None:
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +        Returns: potential harvest index for the day
```suggestion
        Returns: potential harvest index for the day (unitless)
```
I think this is unitless.

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +            water_deficiency: water deficiency factor for the plant
Units for these args

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +        return max(adj_harvest_index, 0)  # bounded at zero
I think these inline comments are unnecessary, the variable names are clear so the code is very readable

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +This module is based on the "Dormancy" module of SWAT (5:1.2)
```suggestion
This module is based on the "Dormancy" section of SWAT (5:1.2)
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +        self.data = crop_data or CropData
```suggestion
    def __init__(self, crop_data: Optional[CropData] = None):
        """Sets data field to a crop data object on which Dormancy operations will be conducted. 
            Initialized with defaults if none given.
        """
        self.data = crop_data or CropData
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +        """Performs the actual transition from active to dormant in a crop.
```suggestion
        """Performs the transition from active to dormant in a crop.
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +            self.data.leaf_area_index = min(self.data.leaf_area_index, self.data.minimum_lai_during_dormancy)
```suggestion
            self.data.yield_residue += (self.data.biomass * self.data.dormancy_loss_fraction)
            self.data.biomass *= (1 - self.data.dormancy_loss_fraction)

            self.data.leaf_area_index = min(self.data.leaf_area_index, self.data.minimum_lai_during_dormancy)
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +        Returns: the dormancy threshold for this latitude
```suggestion
        Returns: the dormancy threshold for this latitude (hours)
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +        # check the schedule to see what needs to be done today
```suggestion
```
I think this comment is unnecessary, but if the code seems unclear maybe a better way to go would be to rename the method to `check_schedule_for_daily_tasks()`?

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +        if self.is_last_day_of_the_year:   # TODO: check if annual reset should be done
Can this TODO be removed?

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +                crop.data.is_dormant = False
```suggestion
        """Set all crops that can go dormant to being dormant

        Args:
            daylength: length of time from sunup to sundown on the current day (hours)

        Details:
            If the length of the current day is at or below the dormancy threshold length, all crops that can go dormant 
            should be put into dormancy. If the length is greater than the greater than the threshold length, all crops should
            be brought out of dormancy.
            
        """
        if daylength <= self.field_data.dormancy_threshold_daylength:
       
            for crop in self.crops:
                crop.dormancy.enter_dormancy()
        else:
            for crop in self.crops:
                crop.data.is_dormant = False
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_crop_data_and_species_factory.py
> +    # assert aspen.is_perennial is True
```suggestion
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_dormancy.py
> +    # Check everything
```suggestion
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_dormancy.py
> +    # Run method
```suggestion
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_dormancy.py
> +    # Initialize objects
```suggestion
    """Tests that crops are correctly set to be dormant, and when set to being dormant lose the correct 
         amount of biomass and have their leaf area index reset to the correct value.
    """
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_dormancy.py
> +    """Tests that _find_threshold_daylength() in Dormancy module works correctly"""
```suggestion
    """Tests that the dormancy threshold daylength is calculated correctly."""
```

2023-03-09 23:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_dormancy.py
> +    """Tests that _find_dormancy_threshold() in Dormancy module works correctly"""
```suggestion
    """Tests that the dormancy threshold is correctly calculated based on the latitude."""
```

2023-03-10 04:20 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    """
I did, yeah and I deleted part of the comment you wrote, electing to keep this part to alert users in the future. I think it is valid to use that 0.75 value as a default but let users change it from within the `CropData` class.

Leaf Area Index is an easily calculated metric that anyone who deals with plants should be able to get this info fairly easily.

2023-03-10 04:23 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +        #   (Not Used)
This entire method ATM, I'll be sure to make that clear.

2023-03-10 15:11 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    """
Awesome

2023-03-10 17:15 UTC, Isgotkowitz approved these changes

2023-03-13 20:04 UTC, merged