Implement features of old `soil.py` into new `soil.py` (in `SC_redesign`)and test
RuminantFarmSystems/RuFaS pull request #355
Opened 2023-02-15 16:12 UTC by Isgotkowitz

# Summary
This PR implements many of the functionalities from the old `Soil` module into the various modules within the `Crop_and_Soil/soil/` module. It also introduces new functionality for creating `SoilData` objects with the `SoilConfigFactory` module, based on the way `CropData` objects for specific species are created by the `CropSpeciesFactory` module.

# Main Changes
- `SoilData`:
    - several attributes have been added to track annual totals of or changes in profile attributes
    - there is now an optional `name` attribute that can be used to identify different `SoilData` objects
    - `second_moisture_condition_parameter` (used in the `Infiltration` module) is now an attribute of `SoilData`
    - `surface_runoff_volume` is now named consistently across `SoilData` and `SoilTemp` modules
    - `__post_init__()` has had a docstring added, checks that there is not a vadose zone `LayerData` object already initialized before initializing one, and sets some of the yearly totals
    - an `@property` method (`profile_nitrates_total()`) has also been added to calculate the total amount of nitrates in the soil profile
    - `SoilData` now takes keyword arguments only, and an import statement has been added to make this possible
    - there is an `annual_reset` method which resets yearly totals when called
    - the docstring for `profile_bulk_density` has been reformatted a little
- `LayerData`:
  - `layer_thickness()` now checks the validity of the data it is using, and throws a `ValueError` if it finds invalid attributes
  - `saturation_content()` has been moved up so it is now directly below the other `@property` methods that calculate water-related contents
- `Soil`:
    - `__init__()` now has a docstring, as well as docstrings for all the attributes in it
    - there are now two methods that are meant to be run daily, one to run water-related processes and one to run all other processes
- `SoilConfigFactory`:
  - this module lays the groundwork for more default soil configurations to be created and easily  used by the simulation/users. It is meant to follow `CropSpeciesFactory` as closely as is appropriate
- `test_soil_data_and_config_factory.py`:
  - this module functions as a test for all modules not associated with a specific section of SWAT
  - `SoilData` is now tested within this module, including configuring `SoilData` objects, `annual_reset()`, and all the `@property` methods within `SoilData`
  - `LayerData` is now tested within this module, including that `__post_init__()` works correctly, and all `@property` methods work correctly
- `Evapotranspiration` and test module:
    - `evapotranspirate()` now adjusts the annual totals for attributes that it calculates
    - the test for `evapotranspirate()` checks that totals have been updated correctly
    - the name of an attribute used has been updated to reflect how it is named in `LayerData`
    - `test_potential_evapotranspiration()` and `test_determine_soil_evaporation()` have been rewritten to use `patch` from `pytest`, which allows tests to be run independent of order within the module. `test_determine_latent_heat_vaporization()` and `test_determine_soil_cover_index()` have been moved down in the module.
- `Infiltration` and test module:
   - `infiltrate()` has had argument descriptions added to its docstring, gets `second_moisture_condition_parameter` from `SoilData` object, and updates annual totals for attributes it calculates
   - the test for `infiltrate()` has been updated to reflect the new method signature and checks that the annual totals that should be updated are getting updated correctly
- `SoilErosion` and test module:
   - the main routine, `erode()` now calculates the daily amount of sediment that gets eroded, stores it, and uses that value to update the annual total. It also updates a second annual total based on the surface runoff volume of a given day
   - the test for `erode()` now checks that updates to annual totals have been applied correctly

# Other Changes
- all tests for `Crop` modules are now in their own directory, `crop_tests`. Only the names of these files have been changed. The directory `crop_tests` also has an empty `__init__.py` file.
- `test_crop_data_and_species_factory.py` has had a small typo corrected in one of its comments
- `species_data_factory.py` has had a comment added that explains the purpose of an if condition
- `test_percolation.py` has been updated to work with `SoilData` now only taking keyword arguments

2023-02-22 07:57 UTC, matthew7838 requested changes
### Summary
Great PR, lots of things done. All the docstrings look right to me. I don't think I caught anything missing or many things things that are needed for changes. Comments are mostly just suggestions.

2023-02-22 07:57 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +        """Average bulk density of the soil profile based on the bulk density of each soil layer, weighted by the
Although it's straightforward, I think it is still less straightforward than calculating the total. Perhaps adding the reference to the definition of bulk density if possible?

2023-02-22 07:57 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
>          """thickness of soil layer (mm)"""
Just a suggestion, not sure if it's that helpful, but I wonder if there's a way to also check if more than one variable is invalid. Right now, the error message will only alert the first invalidity it encounters. 

My suggestion is perhaps setting a boolean for all three conditions and throwing a value error for all combinations of boolean values. There aren't too many variables to check so I think there will only be 6 combinations in total if implemented.

2023-02-22 07:57 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/soil.py
>      def make_from_config(cls, soil_config) -> Soil:
Might need docstring?

2023-02-22 07:57 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/soil_erosion.py
> +        self.data.annual_eroded_sediment_total += self.data.eroded_sediment
Is there a reason why not just `self.data.annual_eroded_sediment_total += self._determine_adjusted_sediment_yield(sediment_yield, self.data.snow_cover_water_content)` ?

2023-02-22 15:47 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil.py
>      def make_from_config(cls, soil_config) -> Soil:
You mean `make_from_config()` might need a docstring?

2023-02-22 15:54 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_erosion.py
> +        self.data.annual_eroded_sediment_total += self.data.eroded_sediment
At this point, no. At a future point though we will need to take the value from `self._determine_adjusted_sediment_yield()` and use it to actually remove mass from the top of layer of the soil profile (issue #351). I will add a `TODO` so that is clearer.

2023-02-22 16:12 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
>          """thickness of soil layer (mm)"""
That is a good idea. I think it would be good to talk to @morrowcj  first though because he might know more about how errors are going to be pushed back up to end users, and that will inform how complex the error handling should be

2023-02-22 16:17 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +        """Average bulk density of the soil profile based on the bulk density of each soil layer, weighted by the
What do you mean by "calculating the total"?

2023-02-22 19:43 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
>          """thickness of soil layer (mm)"""
talked to Pooya and he made a good suggestion for the best error message format, I think it should be up to snuff now

2023-02-22 20:48 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/soil.py
>      def make_from_config(cls, soil_config) -> Soil:
Yes, sorry for the confusion,

2023-02-22 20:50 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +        """Average bulk density of the soil profile based on the bulk density of each soil layer, weighted by the
I just mean that compare to other functions that are just looping and calculating the total, this one is less straightforward. Basically just suggesting a reference for bulk density. Sorry for the confusion.

2023-02-23 15:35 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +        """Average bulk density of the soil profile based on the bulk density of each soil layer, weighted by the
The reason it isn't calculating a simple total is because it is doing a weighted average, not a regular average. Also there is a reference to SWAT for the definition of bulk density in `layer_data.py` which I think is a better place to have it, because that is where users will be directly inputting their data.

2023-02-23 15:35 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil.py
>      def make_from_config(cls, soil_config) -> Soil:
Added

2023-02-23 17:24 UTC, morrowcj approved these changes
This looks really good. I have a few comments that I'd like you to consider addressing, but you are free to merge once you are happy with it. Great work!

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/evapotranspiration.py
> +        # Update annual totals
```suggestion
        # Update accumulated (annual) totals
```

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +            raise ValueError("Top depth of a soil layer cannot be at or below the bottom depth of the layer")
I don't know how I feel about validation taking place within a `@property`.

@ltp23, can you provide any thoughts on this?

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil.py
> +    def daily_soil_routine(self, solar_radiation: float, avg_temp: float, min_temp: float, max_temp: float,
I'd like to see these main methods utilized. 

Who is going to call them? The `Field` class? If so, add them where they should go.

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil.py
> +                                                     snow_cover, avg_annual_air_temp)
The only thing this method does is call another method? and pass the same arguments? That means this method is entirely unnecessary. Right? Just call `soil.soil_temp.daily_soil_temperature_update()` wherever you would call this method.

OR, are other methods going to be appended to this list? If so, add any method calls that exist and add placeholder (comments) otherwise.

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil.py
> +            plant_cover: total aboveground plant biomass and residue on the current day (kg per hectare)
```suggestion
            plant_cover: total above-ground plant biomass and residue on the current day (kg per hectare)
```

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil.py
> +    def daily_soil_water_routine(self, rainfall: float, weighting_coefficient: float,
Same question: where is this used?

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil.py
> +                TODO: better description
```suggestion
            solar_radiation: incoming solar, in MJ per square meter per day
```

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_config_factory.py
> +    GENERIC = "generic"
```suggestion
class SoilConfigurations(Enum):
    """Enum of all currently support soil configurations"""
    GENERIC = "generic"
    # TODO: implement additional soil types
```

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    """curve number for average moisture conditions (unitless)"""
```suggestion
    """'curve number' parameter for average moisture conditions equation (unitless)"""
```

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +            attributes in the object to be set before they can be set"""
```suggestion
        """This method initializes attributes that either cannot be set to a default above or depend on other
            attributes in the object to be set before they can be set"""
```

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    def annual_reset(self) -> None:
method names should start with verbs: `reset_annually()`, `do_annual_reset()`, `perform_annual_reset()`?

Also, where/how will this be called?

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_erosion.py
> +        # TODO: the soil profile needs to have mass removed from it as it gets eroded - Issue #351
```suggestion
        # TODO: does the soil profile needs to have mass removed from it as it gets eroded? - Issue #351
```

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_crop_data_and_species_factory.py
> +    CropSpeciesDataFactory.create_species_data() method.
Thank you!

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_soil_data_and_config_factory.py
> +    "indoor floor",
Nice!

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_config_factory.py
> +class SoilConfigurations(Enum):
I think this should be singular. The instantiated object is a single configuration. 

```suggestion
class SoilConfiguration(Enum):
```

2023-02-23 17:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_soil_data_and_config_factory.py
> +    assert generic == SoilData()
Is this `TODO` referring to the `assert generic == SoilData()` line? If so, I think it is good to have all the individual tests (above) because if one of them fails, we know where to look. It is probably a good idea to **also** include the test of overall equality, as you have done.

2023-02-23 20:03 UTC, matthew7838 approved these changes
Looks good.

2023-02-24 15:22 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil.py
> +                TODO: better description
I'm gonna miss this comment, it was my first comedic homerun as a software dev

2023-02-24 15:24 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_soil_data_and_config_factory.py
> +    "indoor floor",
Thanks, I try:)

2023-02-24 15:26 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_soil_data_and_config_factory.py
> +    assert generic == SoilData()
Yes, it is referring to the `assert generic == SoilData()`, I'll update the code comment based on your comment

2023-02-24 15:29 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil.py
> +                                                     snow_cover, avg_annual_air_temp)
I think other methods are going to be appended, to this list, but I am not sure. It depends on how we end up structuring the phosphorus, nitrogen, and carbon modules. I am going to leave it in here for now, but I will add a comment noting this.

2023-02-24 15:39 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_crop_data_and_species_factory.py
> +    CropSpeciesDataFactory.create_species_data() method.
You're welcome:)

2023-02-24 15:46 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_config_factory.py
> +class SoilConfigurations(Enum):
Done

2023-02-24 17:17 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil.py
> +    def daily_soil_routine(self, solar_radiation: float, avg_temp: float, min_temp: float, max_temp: float,
They have now been added into `Field`

2023-02-24 17:21 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil.py
> +    def daily_soil_water_routine(self, rainfall: float, weighting_coefficient: float,
Now it has been added as the only method within `cycle_water()` inside `Field`. Though I think it is likely that this method will go away at some point in the future and we will wind up calling all water methods directly.

2023-02-24 17:43 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    def annual_reset(self) -> None:
I added a method in `Field` that will handle all annual data collection and resetting, but I think we will need to change the design of our `Soil` objects (and `Crop` objects, it has all the same issues). This is because the `SoilData` object inside of the `Soil` object is not actually a field, so there is no way for the `Field` that contains the `Soil` object to read data from or perform operations on the `SoilData` object.

2023-02-24 17:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    def annual_reset(self) -> None:
An extremely simple solution that passes all the tests would be to change `data` in `Soil` to `self.data`. This is something that I think will be pretty necessary to analyze before going with it though

2023-02-24 17:59 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    def annual_reset(self) -> None:
And the names for annual reset methods have been changed

2023-02-24 18:16 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil.py
> +                                                     snow_cover, avg_annual_air_temp)
OK, that makes sense. I just wasn't sure.

2023-02-24 18:17 UTC, merged

2023-02-24 18:20 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    def annual_reset(self) -> None:
I agree that `self.data` should be used instead of `data` (not doing so was just an oversight, I think). I don't quite follow your first reply in this thread, though. Why would we need to redesign?

The field should be able to access the soil layer data with `self.soil.data.soil_layers`. Right?

2023-02-24 18:26 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    def annual_reset(self) -> None:
Because `SoilData` wasn't actually an attribute of `Soil`, there was no way to access it through `Soil`. So you're right, the field should be able to access the soil layer data with `self.soil.data.soil_layers` but it currently cannot

2023-02-27 15:12 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    def annual_reset(self) -> None:
Now resolved by #367

2023-02-28 19:45 UTC, ltp23 commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +            raise ValueError("Top depth of a soil layer cannot be at or below the bottom depth of the layer")
Style-wise, I think it's better to raise the errors the moment they occur, so in this case, when the variables become negative somewhere else. We can move those error checks inside the post_init() function, or write a class/static method for checking and call it from post_init(). Ideally, we want the code in property methods to be simple return statements.

2023-02-28 19:52 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +            raise ValueError("Top depth of a soil layer cannot be at or below the bottom depth of the layer")
I will add an issue to address this