Refactor pool_gas_partition.py
RuminantFarmSystems/RuFaS pull request #364
Opened 2023-02-22 22:38 UTC by matthew7838

### Summary
This PR refactors the Decomposition sub-module `pool_gas_partition.py` of the Soil module from "pseudocode_soil" S.6.C.1 to S.6.C.13. All methods except the main routine are static methods.

Every method is tested covering possibly most edge cases.

### Changes 

- Except for the main routine `partition`, all other methods are now static
- Except for the main routine `partition`, all methods do not rely on any external classes
- Descriptive names modified and added 
- Now only the main routine `partition `updates and tracks attributes added in the `SoilData` and `LayerData` class

### Other changes
- Added attributes in both the `SoilData` and `LayerData` class 
- Wordings of **above ground, AG, and Below ground, BG**, have been changed to plant and soil

### **NOTE**
Please also review if things match the `pseudo_soil.doc` documents, also see if there could be improvements in naming

2023-03-20 16:44 UTC, Isgotkowitz requested changes
There are a couple of things that need to be addressed across this PR, including unnecessary inline comments, use of percentages vs. fractions, test method signature type annotations and docstrings, and method signature names (all of these are described in more detail in comments). A big problem with this PR though is size, it is way too large. The Code Review section of the wiki says that the maximum size of a PR should be 200 lines, but because we are refactoring entire modules this number is extremely constraining. I have been trying to keep my PRs below 500 lines (although I should be aiming for lower), and once they get bigger split them into stacked PRs (Clay sent me [this ](https://blog.logrocket.com/using-stacked-pull-requests-in-github/) article, its quite helpful).

2023-03-20 16:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    """silt and clay content in the soil (%)"""
`layer_data.py` already contains attributes that track the soil and clay contents of each soil layer, so I think this should be replaced with an `@property` method that iterates through the soil layers and calculates a weighted average. I'm not sure what the best factor would be to weigh it by, @morrowcj what do you think?

2023-03-20 16:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +        # S.6.C.2
```suggestion
```
I think it is redundant to put the pseudocode reference above each method call, because they're already referenced in the method description.

2023-03-20 16:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +            passive_carbon_co2_lost_rate: passive carbon lost as CO2 during decomposition (%)
In SWAT they are unfortunately not great at clearly spelling out how they use fractions vs percentages, but in general when something is a percentage 1 = 1% and 100 = 100%, and when something is a fraction 0.01 = 1% and 1.0 = 100%. On top of that each new scientific model I've had to work with seems to do it a different way, but when we write code for RuFaS I think we should try to keep it consistent with SWAT. @morrowcj is this what you have been doing/should we be making this the SC team standard?

2023-03-20 16:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +                                                                                                            slow carbon
```suggestion
                                                                                                            slow carbon (unitless)
```

2023-03-20 16:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_pool_gas_partition.py
> +def test_soil_structural_slow_carbon_remaining(soil_structural_slow_carbon_usage):
```suggestion
def test_soil_structural_slow_carbon_remaining(soil_structural_slow_carbon_usage: float) -> None:
"""Tests that the amount of structural soil carbon decomposed is calculated correctly."""
```
Test method signatures should also be type annotated and have a docstring, but the docstrings can be really simple (No args description or pseudocode reference, just a one sentence test description.)

2023-03-20 16:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_pool_gas_partition.py
> +    # S.6.C.1 mocking
```suggestion
```
All of the "# \<pseudocode reference\> mocking" inline comments can be removed.

2023-03-20 16:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +
This module should have a top-level docstring description.

2023-03-20 16:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +    def _soil_passive_carbon_amount(passive_carbon_amount: float, slow_to_passive_carbon_amount: float,
All method names should start with a verb.

2023-03-20 20:16 UTC, morrowcj commented
Hey, @matthew7838, I agree with @Isgotkowitz about the size of this PR. From now on, try to make them smaller (by breaking the work into pieces). For example, the first few methods (and their tests) could be a PR. Then the next few methods could be a separate PR, and so on. Make sense?

2023-03-20 20:24 UTC, morrowcj approved these changes
I don't have much to add beyond @Isgotkowitz's comments. I agree with all of what he said. So address those items and you're good to go!

2023-03-20 20:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +    def partition(self):
What is this method partitioning?

2023-03-20 20:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +            passive_carbon_co2_lost_rate: passive carbon lost as CO2 during decomposition (%)
I think we should keep everything as a fraction (i.e., `passive_carbon_loss_rate: fraction of passive carbon lost as CO2 during decomposition (unitless)`

2023-03-20 20:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +            passive_carbon_co2_lost_rate: passive carbon lost as CO2 during decomposition (%)
I've suggested a change to this variable. Carbon and CO2 are redundant and this is the "loss rate" not "lost rate":

```suggestion
            passive_carbon_loss_rate: passive carbon lost as CO2 during decomposition (%)
```

2023-03-20 20:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +    def _soil_passive_carbon_amount(passive_carbon_amount: float, slow_to_passive_carbon_amount: float,
What he said.

2023-03-20 20:24 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    """silt and clay content in the soil (%)"""
Ooh, yes. let's not duplicate attributes.

2023-03-22 19:38 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +    """silt and clay content in the soil (%)"""
@morrowcj Any suggestion on the weight factor?

2023-03-24 21:37 UTC, Isgotkowitz approved these changes
Looks good. Only comments are for a name change if you feel its necessary and removal of a duplicate comment.

2023-03-24 21:37 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    def silt_clay_content(self):
```suggestion
    def silt_clay_ratio(self):
```
I think this is a better name for this quantity actually represents.

2023-03-24 21:37 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_pool_gas_partition.py
> +    # Checking values were set correctly by the main routine
```suggestion
```

2023-03-24 22:11 UTC, morrowcj approved these changes
LGTM, just a few small comments about docstrings.

2023-03-24 22:11 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +pseudocode soil documentation.
Add a reference to the relevant section(s) of the pseudo code

2023-03-24 22:11 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +    def __init__(self, soil_data: Optional[SoilData] = None):
Add class docstrings here and elsewhere:

```suggestion
class PoolGasPartition:
    """[Add description of what the class is for]
    
    Attributes
    ----------
    data : SoilData, optional
        a reference to the soil data object, which will be used and updated. If not given, a default SoilData
        object is created.
    """
    def __init__(self, soil_data: Optional[SoilData] = None):
```

2023-03-24 22:11 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/pool_gas_partition.py
> +        """
Formatting, and be more specific:
```suggestion
        """main routine to update variables [associated with gas partitioning?] in all layers

        Notes
        ------
        This method applies all the gas-partitioning sub routines to each layer of soil that is present in the soil `data` object.
        """
```

Try to add context like this, for any code you write, wherever it might not be clear.

2023-03-24 22:50 UTC, merged