Crop dormancy
RuminantFarmSystems/RuFaS pull request #365
Opened 2023-02-23 20:49 UTC by morrowcj

# Summary
This PR now implements and tests dormancy for plants, based on SWAT section 5:1.2. To achieve this it has introduced some changes to the structure of `CropData`. This PR also integrates crop dormancy (and tests it) at the `Crop` and `Field` levels.

# Main Changes
- `Dormancy` (and test module):
  - there is now a `Dormancy` module, which has two `@staticmethods` which calculate the parameters when dormancy begins, and a main routine that places a crop into dormancy and changes all necessary `CropData` attributes
  - all methods in `Dormancy` are tested in `test_dormancy.py`
- `Crop`:
  - this module now imports `Dormancy` and maintains a `Dormancy` object
  - a small typo is corrected at the bottom of the file
  - `assess_dormancy()` now calls the dormancy method on the crop instead of doing nothing
- `CropData`:
  - there is now the `PlantTypes` enum class that has all the supported types of plants. This was added to ensure the correct operations were performed on a crop when it goes into dormancy
  - the `plant_type` attribute (type is `PlantTypes` member) has replaced the `is_perennial` boolean attribute. All the child classes of `CropData` reflect this change. Note that `is_perennial` still exists in `CropData`, but now as an `@property` method based on the `plant_type` attribute
  - two attributes have been added to track dormancy-related properties of a plant. There are still some TODO's associated with them, but they will need to be implemented after researching how they are measured in the field and what some typical values are for them.
- `CropManagement` (and `test_crop_management.py`):
  - the main routine for this module now takes a member from the `HarvestOperation` enum rather than a couple of booleans
  - the tests for `cut_crop()`, `determine_harvest_index()`, `dry_down()`, `kill()`, and `manage_harvest()` have been commented out because they are not implemented yet.
- `Field` (and test module):
  - `manage_field()` now puts crops in or takes them out of dormancy depending on the length of the current day
  - the `start_dormancy` method has been added which iterates through all crops in the field and calls their dormancy methods
  - a small typo has been corrected
  - the test module now includes a test for the `start_dormancy()` method. The tests `test_grow_crops()` and `test_harvest_crops()` have been commented out because they are not implemented yet
- `test_crop_data_and_species_factory.py`:
  - `test_species_factory_defaults()` now checks that `plant_type` is initialized correctly instead of `is_perennial`
  - `test_manual_custom_crop_data()` sets and checks `plant_type` instead of `is_perennial`
  - `test_factory_alterations()` sets `plant_type` instead of `is_perennial`
  - there is now a test for the `is_perennial` method 
- `FieldData`:
  - docstring for `harvest_type` is now a comment, not a string
  - attributes have been added that are used to determine when crops in the field should go into dormancy
  - a `post_init` method has been added to initialize dormancy-related attributes that are based on other `FieldData` attributes, using `@staticmethods` from `Dormancy`
- `CurrentWeather`:
  - the `daylength` attribute has been added, which determines whether a crop goes into or gets out of dormancy on that day

# Other Changes
- `HeatUnits`:
  - TODO's have had references to related GitHub issues added
- `RootDevelopment` (and test module):
  - minor formatting issue has been fixed
  - test module now sets `plant_type` instead of `is_perennial`
- `SoilData`:
  - the `decomposition_temperature_effect` attribute has been moved to above the `post_init` method 
- added an `init` file to the `crop_tests` directory 
----
**Note** that this PR is merging into `field-manager_SCred` because it is a sub-branch of that branch.

2023-02-28 17:49 UTC, Isgotkowitz commented
Original top comment from @morrowcj 
---- 
This PR handles crop dormancy.

@Isgotkowitz, If you have time next week, would you finish up this PR for me? I don't think I'll have time tomorrow.

The ideal behavior would be:
* every day the field checks the weather to get the current day length
* If the current day length is less than the calculated threshold for the latitude, then the field goes dormant:
    - apply the `is_dormant` status to all crops that can go dormant in the field (perennials)
    - upon going dormant, transfer a fixed proportion of biomass from the crop to residue (`dormancy_loss_fraction` default to 10%)

----
**Note** that this PR is merging into `field-manager_SCred` because it is a sub-branch of that branch.

2023-02-28 21:18 UTC, PooyaHekmati requested changes
This is a big PR; I couldn't review the whole thing in one go. Please consider having smaller PRs. Generally speaking, we can have a cleaner code here.
This PR has 8 bullet points under "Main Changes"; which means we are actually looking at 8 PRs at once. Single responsibility applies to PRs as well. What is even more concerning, is the statement: "Note that this PR is merging into field-manager_SCred because it is a sub-branch of that branch." which means we are anticipating an even larger PR when merging field-manager_SCred to master.

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +        """Process component performing dormancy operations"""
Please aggregate all comments in one block, preferably in docstrings if it fits.

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +        """destroys the crop - Destructor class. This removes the crop instance from existence"""
No it does not; this function does nothing; the docstring is misleading and the whole purpose of having a function like this is unclear.

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +    def assess_dormancy(self):  # TODO: implement dormancy method - handled in CropData
Dangling TODO; what is the plan for getting this TODO done? What is CropData?

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    """Enum of all plant types supported by RuFaS. Listed for supported plant types in SWAT Appendix A, table A-1"""
Line too long, please break into multiple lines, preferably less than 89 chars each.

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    plant_type: PlantTypes = PlantTypes("cool_annual")
Please move the comments into docstring, respecting Numpy style.

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    """Fraction of biomass the crop loses when it goes dormant. Default 10% for perennials, 30% for trees
Unclear comment: what is the function for Fraction of biomass? Is it referring to the last line or the next line? Also it seems the default is 0.1 not 10%.

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    # TODO: implement __post_init__() to set default based on plant type
Dangling TODO

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    # TODO: SWAT Appendix-A section A.1.12 says that the default 0.75 is from pre-2009 versions of SWAT and users are
Dangling TODO + long lines

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +        """Returns whether the plant is perennial"""
Did you mean: "Returns True if the plant is perennial?

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +        if harvest_op == HarvestOperation.HARVEST:  # harvest and kill the crop
unnecessary comment; the code is clear enough.

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +        if harvest_op == HarvestOperation.HARVEST_NOKILL: # harvest but don't kill the crop
unnecessary comment; the code is clear enough.

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +        """This method performs the actual transition from active to dormant in a crop.
```suggestion
        """
        Performs the actual transition from active to dormant in a crop.
```
Does it mean that there is a 'non-actual' transition as well?

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +            return
```suggestion
        no_dormancy = self.data.plant_type == PlantTypes.WARM_ANNUAL or 
          self.data.plant_type == PlantTypes.WARM_ANNUAL_LEGUME or
          self.data.is_dormant
        if no_dormancy:
            return
```
I might be missing paranthesis

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +        # TODO: should is_growing be set here?
I don't know, you tell me

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +    # TODO: It might be better calculate the two values in FieldData (e.g., post_init), since they don't change?
Is this a thought or TODO?

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +            return (abs_latitude - 20.0) / 20.0
```suggestion
        is_near_pole = abs_latitude > 40
        if is_near_pole:
            return 1.0

        is_near_equator = abs_latitude < 20
        if is_near_equator:
            return 0.0

        is_middle = 20 <= abs_latitude <= 40
        if is_middle:
            return (abs_latitude - 20.0) / 20.0
```

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/crop/heat_units.py
> +    # TODO: Dormancy! SWAT 5:1.2 - GitHub PR #365
This is PR 365, doesn't make sense to plan something in the past.

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/field/field.py
> +            # put crops into dormancy if daylength is as or below dormancy daylength threshold
can you remove the comment using the technique that I used in earlier comments?

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/field/field.py
> +                # Bring all crops out of dormancy
maybe wrap it in a function?

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/field/field.py
> +            crop.assess_dormancy()
Lines 241 and 243 are not aligning; one of them is wrong. One says we are setting xyz; the other says we are assessing xyz. How is this possible?

2023-02-28 21:18 UTC, PooyaHekmati commented on SC_redesign/Crop_and_Soil/field/field_data.py
> +    """the HarvestOperation, specifying which harvest operation to use"""
Same as before, please put comments in one block

2023-02-28 21:43 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +        """Process component performing dormancy operations"""
Do you mean that you would prefer to see all the "Process Component ..." comments grouped together at the top, like
```
"""Process components for
                - controlling growth constraints, limits plant growth as a function of stressors
                - controlling allocation of plant biomass as a function of growth and photosynthesis
                - controlling plant water dynamics
                - etc.
"""
```

2023-02-28 22:02 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +    def assess_dormancy(self):  # TODO: implement dormancy method - handled in CropData
Not sure what I was thinking when I wrote `CropData`, should be `Dormancy`, also this TODO should be removed.

2023-02-28 22:18 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    """Enum of all plant types supported by RuFaS. Listed for supported plant types in SWAT Appendix A, table A-1"""
Is this the standard for all docstrings, or just certain ones? Also where does the 89 chars limit come from?

2023-02-28 22:20 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +        """Returns whether the plant is perennial"""
Yes

2023-02-28 22:32 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    plant_type: PlantTypes = PlantTypes("cool_annual")
Can you please leave a link to the style document and reference to the specific section that applies here please? I have been looking through the links in the README and the Numpy style guide (https://numpydoc.readthedocs.io/en/latest/format.html#) and I am still not sure what you want the comments here to look like

2023-02-28 22:35 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    """Fraction of biomass the crop loses when it goes dormant. Default 10% for perennials, 30% for trees
Always the last line. Will change the percents to fractions

2023-02-28 22:40 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    # TODO: implement __post_init__() to set default based on plant type
TODONE (wrote __post_init__ method, TODO is gone)

2023-02-28 22:41 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    # TODO: SWAT Appendix-A section A.1.12 says that the default 0.75 is from pre-2009 versions of SWAT and users are
Do you mean the upper or lower TODO?

2023-02-28 23:04 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +        """This method performs the actual transition from active to dormant in a crop.
Yeah, kind of. In `crop.py`, there is the `start_dormancy()` function that calls this function, and `field.py` contains the function `assess_dormancy()` that calls `start_dormancy()` on every crop in a field. So this makes it exceedingly clear where the transition from the non-dormant to the dormant state is happening. I can change the wording if you think it doesn't read well though.

2023-02-28 23:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +            return
I think it is better to have these two separate `if` statements because they make it easier to decipher the code, and it is easier to write clear comments for them (IMO). I will rewrite the second comment though because it should include a better reason for why it stops there.

2023-02-28 23:27 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +        # TODO: should is_growing be set here?
`is_growing` is another attribute of `CropData` (line 170) which is currently not being used, so I am not sure how/if it should be linked to dormancy status. In the case that it should be linked though, I don't want it to get missed here.

2023-02-28 23:29 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +    # TODO: It might be better calculate the two values in FieldData (e.g., post_init), since they don't change?
I'm not sure, because Clay wrote this TODO. I took it as a TODO and did it, but since it could be a thought I will update it to reflect the current state of the program

2023-02-28 23:33 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +            return (abs_latitude - 20.0) / 20.0
I'm curious, why do you prefer the suggested pattern?

2023-03-01 15:28 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +        """destroys the crop - Destructor class. This removes the crop instance from existence"""
I think there are a lot of features like this in the `crop_dormancy`/`field-manager_SCred` branches because there is still so much work to do before they can be merged into `SC_redesign`. For this PR I think it is better to leave this in here, because @morrowcj is doing the heavy lifting on `field-manager_SCred` and removing things that are just placeholders could mess up his workflow.

2023-03-01 15:32 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/heat_units.py
> +    # TODO: Dormancy! SWAT 5:1.2 - GitHub PR #365
TODO is removed, because `Dormancy` is implemented in this branch

2023-03-01 15:47 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +            crop.assess_dormancy()
`assess_dormancy()` was the name of the placeholder function that there when I took over this PR, I will change it.

2023-03-01 15:47 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +                # Bring all crops out of dormancy
Done

2023-03-01 15:51 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +        if harvest_op == HarvestOperation.HARVEST:  # harvest and kill the crop
Comment removed

2023-03-01 15:52 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_management.py
> +        if harvest_op == HarvestOperation.HARVEST_NOKILL: # harvest but don't kill the crop
Comment removed

2023-03-01 15:54 UTC, Isgotkowitz commented
> This is a big PR; I couldn't review the whole thing in one go. Please consider having smaller PRs. Generally speaking, we can have a cleaner code here. This PR has 8 bullet points under "Main Changes"; which means we are actually looking at 8 PRs at once. Single responsibility applies to PRs as well. What is even more concerning, is the statement: "Note that this PR is merging into field-manager_SCred because it is a sub-branch of that branch." which means we are anticipating an even larger PR when merging field-manager_SCred to master.

It should be noted that field-manager_SCred is going to be merged into SC_redesign, not master.

2023-03-01 20:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +        """Process component performing dormancy operations"""
Will be addressed by issue #371

2023-03-01 20:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    plant_type: PlantTypes = PlantTypes("cool_annual")
Will be addressed by #371

2023-03-01 20:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +            # put crops into dormancy if daylength is as or below dormancy daylength threshold
Will be addressed by #371

2023-03-01 20:15 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field_data.py
> +    """the HarvestOperation, specifying which harvest operation to use"""
Will be addressed by #371

2023-03-01 20:24 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    """Fraction of biomass the crop loses when it goes dormant. Default 10% for perennials, 30% for trees
Also this comment will eventually be reformatted to meet style standards #371

2023-03-01 21:27 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop_data.py
> +    """Fraction of biomass the crop loses when it goes dormant. Default 10% for perennials, 30% for trees
These are google style docstrings as demonstrated in the Google style guide. We were told to use Google style long before current numpy style, which we were told are identical.

2023-03-06 17:47 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +        """destroys the crop - Destructor class. This removes the crop instance from existence"""
This was an old placeholder. I've removed it.

2023-03-06 19:20 UTC, Isgotkowitz approved these changes

2023-03-06 19:26 UTC, merged