Crop planting methods
RuminantFarmSystems/RuFaS pull request #377
Opened 2023-03-08 23:08 UTC by morrowcj

Implement methods for specifying, configuring, and planting crops in a field.

## Notes
* some crop management methods were removed from `Crop` and moved to `Field`.

2023-03-10 20:13 UTC, Isgotkowitz requested changes
Looks really good. Particularly liked the way you organized `make_crop_from_config_dict()`, `make_supported_crop()`, and `make_custom_crop()`. Only found one typo in a docstring that needs to be changed

2023-03-10 20:13 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +            should be put into dormancy. If the length is greater than the greater than the threshold length, all crops
```suggestion
            should be put into dormancy. If the length is greater than the threshold length, all crops
```

2023-03-13 17:09 UTC, Isgotkowitz requested changes
I found that one of the cases in `test_add_crop()` that is designed to fail is not being reached. Also there are about 8 issues that `flake8` raises when run on the files that have been changed for this PR.

2023-03-13 17:09 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/field_tests/test_field.py
> +        new_field.add_crop(Crop(), 0.5)  # total is over 1
These test cases are not all being properly run. pytest does not make it to 
```
new_field.add_crop(Crop(), 0.5)
```
I suggest having only the "over 1" case in the first `with` statement, and adding a second `with` statement to test the "total is over 1" case.

2023-03-13 17:12 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/tests_SC/field_tests/test_field.py
> +        new_field.add_crop(Crop(), 0.5)  # total is over 1
Thanks for pointing this out! I had no idea that only one error would be recognized by `pytest.raises` I think I've done this in a few places. I'll change that.

2023-03-13 17:13 UTC, morrowcj commented
> Also there are about 8 issues that `flake8` raises when run on the files that have been changed for this PR.

@Isgotkowitz, this is super annoying since I must've spent like an hour and a half on linting. Haha

2023-03-13 17:17 UTC, Isgotkowitz commented
> > Also there are about 8 issues that `flake8` raises when run on the files that have been changed for this PR.
> 
> @Isgotkowitz, this is super annoying since I must've spent like an hour and a half on linting. Haha

Yeah I think it highly variable because of how configurable it is (plus there isn't a clear teamwide standard yet to make things), I will share my configuration so it is reproducible

2023-03-13 17:36 UTC, Isgotkowitz commented
# Configuring and running `flake8`
This is how I have been configuring and running `flake8` on new code to make sure it not adding to the list of pre-existing linter errors that the GitHub Action linting test finds.

# Configuration
Add a file to the top level directory of your project folder called `.flake8` containing the following lines:
```
[flake8]
count = True
show-source = True
statistics = True
max-line-length = 120
max-complexity = 10
```
This is a mash up of different flags found in the two different `flake8` calls that GitHub runs automatically on new code before it can be merged (See `.github/workflows/lint_flake8.yml`)

# Script
Running `flake8` on the entirety of RuFaS makes it so much harder to sort out which errors are actually in the files that you modified. The following script will run `flake8` only on the files that are different between the branch you are working on and the one you are going to merge your changes into.
Copy the following into a script called `runflake8onbranch.sh` in the top-level directory of your project (same place as `.flake8`):
```
#!/bin/bash
if [ $# -eq 0 ]; then
    base_branch="master"
else
    base_branch=$1
fi

flake8 $(git diff --name-only $(git merge-base ${base_branch} HEAD))
```
Then run the command `chmod +x runflake8onbranch.sh`
You should now be able to run the script with the command `./runflake8onbranch.sh`
Note: by default, it assumes the branch you will merge into is `master`, and currently something in `master` makes `flake8` crash. To run it on a different base branch, add the name as an argument to the script.
For example, for this PR, run `./runflake8onbranch.sh origin/field-manager_SCred`

2023-03-13 18:21 UTC, ew3361zh approved these changes
A few formatting notes from the Numpy docstrings section but really nice overall.

2023-03-13 18:21 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/field/field.py
> +        Args:
I believe with the numpy documentation style we're using "Parameters" in place of "Args" for docstrings with this style:

Parameters
----------
x : type
    Description of parameter `x`.
y
    Description of parameter `y` (with type not specified).

https://numpydoc.readthedocs.io/en/latest/format.html#parameters

2023-03-13 18:21 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/field/field.py
> +        Returns: a Crop object, initialized with the desired attribute values.
And same for returns:

Returns
-------
int
    Description of anonymous integer return value.

https://numpydoc.readthedocs.io/en/latest/format.html#returns

2023-03-13 18:21 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/field/field.py
>          Details:
Not sure if this would be "Notes" now?

https://numpydoc.readthedocs.io/en/latest/format.html#notes

2023-03-13 18:24 UTC, Isgotkowitz approved these changes

2023-03-13 18:52 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/field/field.py
> +        Args:
Yes, we've got an issue to track this (#371). We're not updating older modules yet, but files will contain Numpy style from now on. We'll go back and fix docstrings before merging into master.

2023-03-13 18:54 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/field/field.py
>          Details:
I think Numpy style has a section for extended explanation, right below the first line. We'll split this sort of thing up into either "Extended Summary" or `Notes` depending on the content.

2023-03-13 18:56 UTC, merged