Mini Design Doc: `phosphorus_cycling/`
RuminantFarmSystems/RuFaS pull request #412
Opened 2023-03-29 20:31 UTC by Isgotkowitz

This is a design doc for the phosphorus cycling submodule, though not a full one.

Note: 
- 2 todo's were removed, they were related to future issues so I created a GitHub issue and took them out
- accidentally wrote this on the wrong git branch, so it's now stacked on `add_P_to_soil_SCred` branch (that PR should be closed soon though)

2023-03-30 16:51 UTC, morrowcj requested changes
Ed, Kudos on this great work. This is a **totally** different skill set from programming and you've done a really fine job - your communication skills are good and improving constantly. In addition to wording/grammar suggestions, there are a few substantial points that I think we should address together. Hopefully my comments speak for themselves but please reach out for clarification or further discussion if needed.

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +Reviewers: [Add your names here!]
```suggestion
Reviewers: Clay Morrow
```

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +This document will detail how the redesigned Phosphorus Cycling (PC) submodule within the Soil module of RuFaS. The redesign
I think you're missing a verb in this sentence.

```suggestion
This document will detail how the redesigned Phosphorus Cycling (PC) submodule [works? fits?] within the Soil module of RuFaS. The redesign
```

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +surface in runoff. It was designed specifically to improve on the shortcomings of the SWAT model in this aspect.
```suggestion
The Phosphorus Cycling submodule is based largely on the SurPhos model for predicting the portions of phosphorus that are lost from the soil 
surface in runoff. It was designed specifically to improve on the shortcomings of the SWAT model in this aspect. 
```

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +here: [design-document_SC-redesign.md](design-document_SC-redesign.md).
double check this link. I think that it might be in the `Admin` sub-folder. This document should probably be in the same directory as the main design doc. Rename/reorganize stuff if you need to.

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +- methods used by multiple PC sub-modules
Is this revision accurate?

```suggestion
- calls to methods from multiple PC sub-modules
```

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +`@dataclass` specific to PC.
A few suggestions (check the link, please - I'm doing this in a browser):

```suggestion
It will be structured similar to other [Soil and Crop classes](design-document_SC-redesign.md#module-design-and-structure), with one notable difference:
all states related to phosphorus will be maintained in `SoilData` and `LayerData` instances, not in a 
`@dataclass` specific to PC.
```

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +via fertilizer (~1 time per year). This reflects real-world agricultural practices.
```suggestion
via fertilizer (~1 time per year). This reflects the most common real-world agricultural practices.
```

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +phosphorus than applying via fertilizer). When implementing this submodule, the original intent was to have everything
I like the pun, but let's church it up a little bit.

```suggestion
This submodule handles **applying** phosphorus from manure to a field (which is, arguably, a crappier way to apply 
phosphorus than applying via fertilizer). When implementing this submodule, the original intent was to have everything 
```

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +in the `Manure` module but the application operations became too complex, and necessitated having their own module.
```suggestion
in the `Manure` module but the application operations became too complex, and necessitated separate modules. 
```

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +the other is for manure applied by machine. Each type of manure has its own set of pools and factors that includes
```suggestion
There are two methods to be used by higher level modules. One is for manure applied by animals grazing in a field [grazing not yet implemented in RuFaS], and 
the other is for manure applied by machine. Each type of manure has its own set of pools and factors that includes
```

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +* Removing phosphorus from the surface pools as runoff occurs.
By my reading, almost all of the subsections under `##Requirements` aren't actually requirements *per se*. Rather, they are design details, which should go in the last section according to Pooya's template. 

For actual requirements, think higher level: what does the phosphorus module *need to do* within RuFaS and what are the tangible ways that we will know that these requirements have been met? This section does not need to be long. A single paragraph or short bulleted list is probably sufficient.

For example, the phosphorus module should:
* simulate the amount of phosphorus lost to runoff and the amount that remains in the field for other processes
* determine this process based on environmental factors (weather, topography/runoff, literature [for volatilization])
* discriminate between phosphorus added via manure or via fertilizer
* etc. 

Does that make sense?

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +potential ways that this requirement could be realized:
```suggestion
* Currently (Mar 29, 2023), the module does not maintain a top layer soil with a depth of 20 mm (as required by SurPhos), and there are many 
potential ways that this requirement could be realized:
```

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +## Open Questions
Let's make a decision and then move the things in this section to "Proposed Solution" and "Alternative Solutions".

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +
My suggestion (and by no means the last word): Why don't we simply subdivide the top layer into two pools (e.g., `top_twenty_phosphorus`, and `top_remainder_phosphorus`) within the phosphorus module, but continue treating the layer as a whole for everything else? This would simply involve summing the two pools before passing data outside of P cycling. Perhaps this is defeats the entire purpose, though. 

In that case, we could permanently subdivide the layer and treat the top 20mm as its own layer (with identical composition the the rest of the upper layer but with depths changed). Most soil methods already handle a variable number of layers (at least `Crop` does). The only place that I can see this needing additional attention is where the "top layer" attributes are explicitly used, in which case we need to aggregate the top 20 layer with the rest of the top layer. It shouldn't be too difficult to track those instances down though, right?

2023-03-30 16:51 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +## Beyond Version 1
excellent.

2023-03-30 17:00 UTC, Isgotkowitz commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +- methods used by multiple PC sub-modules
I don't think so, because all the method calls will be made in the other PC sub-modules, and the composite `PhosphorusCycling` class is the place where are those methods are defined. Is that clearer?

2023-03-30 17:01 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +- methods used by multiple PC sub-modules
OK, then disregard! Thanks.

2023-03-30 17:01 UTC, Isgotkowitz commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +phosphorus than applying via fertilizer). When implementing this submodule, the original intent was to have everything
Lol yes, sorry about that. I just couldn't dismiss the little voice in the back of my head saying "Pooya said to make it funny..."

2023-03-30 17:04 UTC, Isgotkowitz commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +* Removing phosphorus from the surface pools as runoff occurs.
Yes, it does

2023-03-30 17:06 UTC, Isgotkowitz commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +## Open Questions
Sounds good

2023-03-30 17:19 UTC, Isgotkowitz commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +
>My suggestion (and by no means the last word): Why don't we simply subdivide the top layer into two pools (e.g., top_twenty_phosphorus, and top_remainder_phosphorus) within the phosphorus module, but continue treating the layer as a whole for everything else? This would simply involve summing the two pools before passing data outside of P cycling. Perhaps this is defeats the entire purpose, though.

The problem with summing the pools (in my mind) is that there is a large loss of information as soon as we do so. If we were to sum them and then the data gets passed to the part of `Crop` that uptakes phosphorus (just one example), it will see only the one pool and uniformly draw phosphorus from it, then the next day the simulation gets back to P cycling and finds the top pool has significantly less phosphorus, or something like that. We should have a meeting about this to flush out details though

2023-03-30 17:20 UTC, Isgotkowitz commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +here: [design-document_SC-redesign.md](design-document_SC-redesign.md).
Will do.

2023-03-30 17:20 UTC, Isgotkowitz commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +This document will detail how the redesigned Phosphorus Cycling (PC) submodule within the Soil module of RuFaS. The redesign
Nice catch

2023-03-30 17:31 UTC, morrowcj commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +
Yeah, that's a very good point and sort of defeats the purpose. What do you think of my second point, then?

2023-03-30 18:39 UTC, Isgotkowitz commented on SC_redesign/docs_SC/phosphorus_design_doc.md
> +
I think it is a good one, and off the top of my head I can't think of any instances where the top layer attributes are used specifically

2023-03-31 16:32 UTC, morrowcj approved these changes
Looks good to me.

2023-03-31 16:32 UTC, morrowcj commented on SC_redesign/docs_SC/Admin/phosphorus_design_doc.md
> +[Beyond Version 1](#beyond-version-1)
I don't think this needs its own heading.

2023-03-31 16:32 UTC, morrowcj commented on SC_redesign/docs_SC/Admin/phosphorus_design_doc.md
> +This section will list the requirements of PC in order to be integrated with and used by other modules.
```suggestion
This section will list the features of PC required in order to be integrated with and used by other modules. 
```

2023-03-31 16:32 UTC, morrowcj commented on SC_redesign/docs_SC/Admin/phosphorus_design_doc.md
> +Some solutions considered when this design was being flushed out:
I'm not sure if this is a pun or a typo.
```suggestion
Some solutions considered when this design was being fleshed out:
```

2023-03-31 18:47 UTC, matthew7838 approved these changes
Looks good to me, again, this is really helpful documentation to help me understand other modules. Thanks.

2023-03-31 19:43 UTC, merged