Refactor residue_partition pt.2
RuminantFarmSystems/RuFaS pull request #426
Opened 2023-04-05 22:33 UTC by matthew7838

### Summary
This PR is the second part of refactoring `residue_partition.py` of the Soil module from "pseudocode_soil" S.6.B.I. As for this part, the PR cover methods from S.6.B.I.8 to S.6.B.I.11 and S.6.B.I.6. All methods created are static and will be used later in the main routine to update attributes that will be added in `Layer` and `Soil` class.

Every method is tested covering most edge cases.

### Changes

- All methods in this part are static
- Attribute and method names were changed to be more descriptive
- As for the current PR, there will be no attributes being modified directly

### Other changes
Fixed some errors in the original code that contradicted the pseudocode_soil according to @morrowcj 's clarification, as well as some issues that weren't addressed before...MORE MISMATCHES:(. TODOs have been added and issues have been created. Everything sticks to the pseudocode_soil.

### Note
This was originally planned to be separated into three PRs, but with the number of errors and contradictions in this PR, I expected the number of problems to grow exponentially in later parts. Therefore, I've decided to split it into 4-5 parts so each PR can be checked in a more detailed manner.

2023-04-06 17:14 UTC, Isgotkowitz requested changes
Nice PR, overall very clean. There is one spot where I think the code isn't doing the correct thing (see comment below). One comment relates to making sure issues are kept track of, and everything else is typo and wording suggestions.

2023-04-06 17:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/residue_partition.py
> +        #  #issue 425
I added this issue to the Soil and Crop Redesign project. Please make sure all issues you create related to the SC module are added to the project (and also marked appropriately w/ Todo status, Wait priority, notes etc.)

2023-04-06 17:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/residue_partition.py
> +        """Determines the amount of transfer of structural carbon during tillage
```suggestion
        """Determines the amount to transfer from structural carbon to <other carbon type?> during tillage
```
I think this is what this method is determining, but ignore if I am wrong

2023-04-06 17:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/residue_partition.py
> +            amount of dry matter residue at harvest (kg/ha)V
```suggestion
            amount of dry matter residue at harvest (kg/ha)
```

2023-04-06 17:14 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/residue_partition.py
> +        return structural_decomposition_factor * math.exp(-3) * 1 - plant_residue_metabolic_fraction
```suggestion
        return structural_decomposition_factor * math.exp(-3) * (1 - plant_residue_metabolic_fraction)
```
Pretty sure parentheses are needed here, otherwise it just multiplies by 1 and then subtracts `plant_residue_metabolic_fraction` which (I think) is not the fraction that should be used here.

2023-04-07 15:00 UTC, morrowcj approved these changes
I think this looks good. I had one small comment.

2023-04-07 15:00 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_residue_partition.py
> +    (2.2, 0)  # zeros
These comments are a bit confusing. If you're going to have comments on cases, make sure useful to the reader. It is also helpful to include more cases that change things one-at-a-time:

```suggestion
    (3, 0.4),  # default
    (50, 0.4),  # increased carbon
    (3, 1.0),  # increased tillage
    (1.8, 0.33),  # decreased carbon & tillage
    (0, 0.4),  # no carbon
    (3, 0),  # no tillage
    (0, 0),  # neither
```

Consider this in all your tests.

2023-04-07 21:13 UTC, Isgotkowitz approved these changes
Looks perfect

2023-04-07 21:19 UTC, merged