Refactor carbon_cycle.py
RuminantFarmSystems/RuFaS pull request #456
Opened 2023-04-20 20:22 UTC by matthew7838

### Summary
This PR is the last part of the carbon cycle module, it also aggregates some value calculated throughout other files as well as runs all the main routines. The aggregation was done by following the pseudocode_soil S.6.D.1 to S.6.D7.

### Changes
- All other methods to calculate aggregation are now static
- There is now a separate method aside from the main routine just to update the aggregated attributes

2023-04-24 16:22 UTC, morrowcj requested changes
The calculation of carbon mass needs some clarification. My other comments refer to the different carbon fractions and whether or not we actually need them.

2023-04-24 16:22 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +        return (layer_thickness * field_size * HECTARES_TO_SQUARE_MILLIMETERS) * CUBIC_MILLIMETERS_TO_CUBIC_METERS
Great job. This looks good.

2023-04-24 16:22 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +            soil volume (cubic meters)
Spell out the units here to avoid confusion (double-check that this is correct).

```suggestion
        bulk_density: float
            bulk density of the soil layer (Megagrams per cubic meter)
        soil_volume: float
            soil volume (cubic meters)
```

2023-04-24 16:22 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +            mass of soil (kg)
This can't be correct if the units given for inputs are correct: For example, if our bulk density is 5 $Mg / m^3$ and we have a soil volume of 10 $m^3$ then we have a total of 50 $Mg$ of soil:

$$ \frac{5~Mg}{m^3} \times \frac{10~m^3}{1} = 50~Mg$$ 

Note: the $m^3$ gets canceled out by the denominator of the first term and the numerator of the second term.

2023-04-24 16:22 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +        return active_carbon_amount/soil_mass
Something is wrong here as well. If we're trying to get the fraction of carbon in the soil, we need to divide the mass of carbon by the mass of soil. This equation has the *density* of carbon (kg/ha) divided by the mass of soil. 

On a more important level: are the any of these computed fractions (slow, active, passive, overall) actually used anywhere? If not, I don't think it is important to include them.

2023-04-24 16:22 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +        return active_carbon_amount + slow_carbon_amount + passive_carbon_amount
This is important to track, and it looks right to me.

2023-04-24 16:25 UTC, Isgotkowitz requested changes
Great job on carbon cycling! Some of the calculations need to have their units revisited, and I think some of the carbon attributes could be further integrated with `LayerData`/`SoilData`, but these will hopefully all be easy fixes

2023-04-24 16:25 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +        pseudoode_soil S.6.D.1
```suggestion
```
Generally unit conversion doesn't need references. I think it would only be appropriate in cases where really uncommon/novel/proprietary units are used, @morrowcj what do you think?

2023-04-24 16:25 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +        pseudoode_soil S.6.D.1
```suggestion
```

2023-04-24 16:25 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +        return active_carbon_amount/soil_mass
Active carbon needs to be multiplied by field size before being divided by the soil mass here (I think) because if that doesn't happen the units will be mismatched (kilograms per hectare divided by kilograms results in kilograms per hectare-kilogram)

2023-04-24 16:25 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +        return slow_carbon_amount/soil_mass
Same here as above method

2023-04-24 16:25 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    """the total fraction of carbon in the soil (unitless)"""
```suggestion
    soil_overall_carbon_fraction: Optional[float] = None
    """the total fraction of carbon in the soil by mass (unitless)"""
```

2023-04-24 16:25 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    """total amount of carbon lost as CO2 (kg/ha)"""
I think this should be an annual total, and then be reset once a year. An example of this process is `soil_data.py`, variables in lines 33 to 66 and the method `do_annual_reset()` at line 294. In fact if there winds up being an annual reset method in `LayerData`, a good place for it to be called on every layer would be `do_annual_reset()`

2023-04-24 16:25 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/soil_tests/test_carbon_cycle.py
> +    assert cycle.residue_partition.partition_residue.call_count == 1
```suggestion
    assert cycle.residue_partition.partition_residue.call_count == 1
    assert cylce._soil_carbon_aggregation.call_count == 1
```

2023-04-24 16:41 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +        pseudoode_soil S.6.D.1
Yeah, I agree.

2023-04-24 16:41 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +        return active_carbon_amount/soil_mass
Yeah, this is exactly what I was referring to in my comment here as well.

2023-04-24 16:41 UTC, morrowcj commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    """total amount of carbon lost as CO2 (kg/ha)"""
I'm indifferent to this. I think either way is fine, since this variable is purely for mass-balance checking (I'm pretty sure this, like many variables only exist so that they can be written to an output file). Whatever we decide to go with, let's change the name to clarify: something like `annual_accumulated_CO2_lost` for the annual reset case or `simulation_accumulated_CO2_lost` if it is a running tally.

2023-04-24 18:40 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    """total amount of carbon lost as CO2 (kg/ha)"""
Wouldn't CO2 lost be one of the numbers that the economics and emissions module would be really interested in? That was what I was thinking when I suggested tracking the annual amount lost, but if it's gonna be an insignificant amount than we can ignore it.

2023-04-26 19:44 UTC, morrowcj approved these changes
LGTM! Nice work!

2023-04-26 19:58 UTC, Isgotkowitz requested changes
Good changes. There is still one units error that can be quickly remedied, a refactor that could be done to turn 3 methods into one, and a typo in the annual reset method name.

2023-04-26 19:58 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +            soil_passive_carbon_fraction = self._determine_soil_passive_carbon_fraction(layer.passive_carbon_amount,
`soil_mass` here is in megagrams, but the three functions beneath it take the soil mass in kilograms.
I suggest adding a conversion factor in `_determine_soil_mass()` so that it returns kg instead of megagrams.

2023-04-26 19:58 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +        return passive_carbon_amount*field_size/soil_mass
`_determine_soil_active_carbon_fraction()`, `_determine_soil_slow_carbon_fraction()`, and `_determine_soil_passive_carbon_fraction()` do the same thing so they could be replaced by a single function, up to you though

2023-04-26 19:58 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/layer_data.py
> +    def do_annual_rest(self):
```suggestion
    def do_annual_reset(self):
```

2023-04-26 19:58 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/soil/soil_data.py
> +            layer.do_annual_rest()
```suggestion
            layer.do_annual_reset()
```

2023-04-26 20:14 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/soil/carbon_cycling/carbon_cycle.py
> +        return passive_carbon_amount*field_size/soil_mass
I agree that it's redundant, but I think that it does improve clarity this way. I think a more generalized function does bring a bit more ambiguity when others are reading this code.

2023-04-26 20:20 UTC, Isgotkowitz approved these changes
Nice

2023-04-26 20:21 UTC, merged