Pen Allocation Grouping Algorithm Pull request
RuminantFarmSystems/RuFaS pull request #54
Opened 2020-03-04 21:57 UTC by cvankerkhove

This pull request contains updates to the animal management system; specifically a file is added (found in routines/animal) that contains a lactating cow pen grouping by ration requirements. Furthermore, there are other small modifications to animal_management and cows in order to implement the algorithm. (Note that this can be tested for any number of inputs for pens, but the more pens, the longer the simulation)

2020-03-06 17:34 UTC, militsasotirova commented
I was able to run the simulation and everything looked fine, but could you add some documentation in the grouping() method in clustering_pen_grouping.py? I’m trying to follow what is happening, but I’m getting a little lost with the variable names and what they mean.

We should also change the installation instructions to include installing the “pandas”, “scipy”, and “xlsxwriter” modules.

2020-03-24 14:48 UTC, KFosterReed reviewed
Can you explain what all the pulp.sol and pulp.mps files are? Are they output functions? Are they part of a test? Just trying to figure out how I should be interpreting them. Thanks!

2020-03-24 14:50 UTC, KFosterReed commented on RUFAS/routines/animal/clustering_pen_grouping.py
> +def grouping(list):
I would like to add a formal function description to all functions.

2020-03-24 14:53 UTC, KFosterReed commented on RUFAS/routines/animal/clustering_pen_grouping.py
> +    ID = []
We need to define all of these variables

2020-03-24 20:55 UTC, KFosterReed commented on RUFAS/routines/animal/clustering_pen_grouping.py
> +    ##Size per pen category##
These look like hard-coded values for the size of pens? If they are, we should change them to be pen attributes

2020-03-24 20:55 UTC, KFosterReed commented on RUFAS/routines/animal/clustering_pen_grouping.py
> +    ##Size per pen category##
If they aren't pen sizes... then what are they?

2020-03-24 20:56 UTC, KFosterReed commented on RUFAS/routines/animal/clustering_pen_grouping.py
> +    ## 1=Fresh, 2=Early, 3=Pick, 4=Late##
```suggestion
    ## 1=Fresh, 2=Early, 3=Peak, 4=Late##
```

2020-03-24 22:23 UTC, cvankerkhove commented on RUFAS/routines/animal/clustering_pen_grouping.py
> +    ##Size per pen category##
Yes, those are hard-coded values; they are not sizes for the actual pens themselves, but rather values to measure the rank given to the cow and categorize them correctly. Regardless I agree they probably should not be hard-coded but those numbers were taken directly from Jorge's R code and I'm not exactly sure where we would pull those values from. I have reached out to him about setting up a meeting this week to work out a solution to this. Thanks for bringing this to my attention

2020-03-27 19:37 UTC, KFosterReed requested changes
SImplify algorithm as discussed

2020-03-30 19:12 UTC, merged