Create save_variable function in OM
RuminantFarmSystems/RuFaS pull request #541
Opened 2023-05-26 20:23 UTC by ew3361zh

This PR seeks to address issue #522 to create a save_variable function in OM that reads a filtered list of requested variables and saves this filtered pool of variables accordingly.

# To accomplish this, the PR:

1. Creates a new private function `_load_txt_file_to_list` in OM to read txt files and add them to a list.
2. Creates a new private function `_filter_variables_pool` to filter the variables_pool using the list of keys provided from the txt file.
3. Creates a new private function `_exclude_info_maps` which makes a copy of the given pool and removes info_maps from it.
5. Creates a new function `save_variables` which reads a text file containing the keys by which the user wants to filter the variables pool and saves the resulting filtered pool to a json file.
6. Calls `save_variables` from main's `execute_simulations_from_files` function.
7. Moved logic to exclude info_maps out of the dump_variables function and replaced it with the call to the new `_exclude_info_maps` function. It still then saves the all variables pool.
8. Adds unit testing for new functions and updates existing unit testing appropriately to cover new functionality.
9. Adds a dummy list of variables file to input folder which is not present in this PR but which was a list of variable names.
<img width="283" alt="Screenshot 2023-05-27 at 2 58 13 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/52361230-4efb-4bf5-9952-e5d45c7c9555">

<img width="498" alt="Screenshot 2023-05-31 at 9 51 07 AM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/59f981c4-8f4a-444e-9331-bcf8b9b596b7">

2023-05-27 19:04 UTC, ew3361zh commented
@PooyaHekmati would you please take a look?

2023-05-29 04:02 UTC, PooyaHekmati requested changes
Please take a look at the code suggestion.

When updating a significant amount of things that are not the main purpose of the PR (docstrings for example), it is a good practice to do them in a separate PR to make the review easier.

2023-05-29 04:02 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            self.keys_list = []
unclear and vague name, this is the list of what keys? what purpose does it serve? why is it needed? what happens if it gets changed as a side effect of another process?

2023-05-29 04:02 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _exclude_info_maps(self, pair: dict[str, Any]) -> bool:
The function name starts with an action verb, suggesting that it does something. Yet, the return value is bool, suggesting the function makes a decision of some sort. There is an inconsistency here.

2023-05-29 04:02 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            return True
```suggestion
    def _exclude_info_maps(self, pool:Dict[str, OutputManager.pool_element_type]) -> Dict[str, OutputManager.pool_element_type]:

        """ Makes a copy of the given pool and removes info_maps from it.

        Returns
        -------
        Dict[str, OutputManager.pool_element_type]
            A copy of the given pool with info_maps removed from it.

        """
  
        pool_copy = pool.copy()
            for key, value in pool_copy.items():
                if isinstance(value, dict) and "info_maps" in value:
                    value.pop("info_maps")
        return pool_copy 
```

2023-05-29 04:02 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            raise e
```suggestion
    def _load_txt_file_to_list(self, path: str) -> List[Str]:
        """ Reads a text file into a list.

        Parameters
        ----------
            path : str
                Path of the input file to be read.
                
         Returns
         -------
            TODO
            
         Raises
         -------
         TODO            

        """
        try:
            with open(path) as keys_doc:
                return keys_doc.read().splitlines()
        except Exception as e:
            raise e
```

2023-05-29 04:02 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            return False
```suggestion
    def _variables_pool_inclusion_filter(self, inclusion_key: str) -> bool:
        """returns True is inclusion_key has a match in variables_pool"""

        return True if inclusion_key in self.variables_pool.keys() else False
```

2023-05-29 04:02 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        self._dict_to_file_json(self.variables_pool, file_path)
```suggestion
        inclusion_keys = self._load_txt_file_to_list(keys_file_path)
        filtered_pool = dict(filter(self._variables_pool_inclusion_filter,self.variables_pool))
        final_pool = filtered_pool
        if exclude_info_maps:
            final_pool = self._exlude_info_maps(filtered_pool)
        file_path = os.path.join(path, self._generate_file_name("saved_variables", "json"))
        self._dict_to_file_json(final_pool, file_path)
```

2023-05-29 04:02 UTC, PooyaHekmati commented on RUFAS/output_manager.py
>          self._dict_to_file_json(self.variables_pool, file_path)
```suggestion
        file_path = os.path.join(path, self._generate_file_name("all_variables", "json"))
        self._dict_to_file_json(pool, file_path)
```

2023-05-29 04:02 UTC, PooyaHekmati commented on RUFAS/output_manager.py
>          if exclude_info_maps:
```suggestion
        pool=self.variables_pool
        if exclude_info_maps:
```

2023-05-29 04:02 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                self.variables_pool[name] = dict(filter(self._exclude_info_maps, variable_data.items()))
```suggestion
            pool =self._exclude_info_maps(self.variables_pool)
```

2023-05-29 04:02 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        self.save_variables(path, input_path, exclude_info_maps)
Let's not call this here. Instead, move it to execute_simulations_from_files in main.py

2023-05-29 14:11 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            self.keys_list = []
What do you think about this renaming and description for the docstring? (would also change every reference to match)

user_input_keys_list : List[str]
        Contains a list of user-input keys used to filter the
        variables_pool to keep only their requested data.

2023-05-29 15:50 UTC, ew3361zh commented on RUFAS/output_manager.py
> +        self._dict_to_file_json(self.variables_pool, file_path)
The issue I'm seeing here is with self._variables_pool_inclusion_filter being able to access the inclusion_keys returned from self._load_txt_file_to_list. The python filter function doesn't allow sending any additional arguments which was the original reason I added that keys_list attribute to the OM.

The two options I thought of when I was originally working on this were:
1. Call self._load_txt_file_to_list within self._variables_pool_inclusion_filter to check against but that seemed like poor design to have it load and read that file every time self._variables_pool_inclusion_filter was called.
2. Add that keys_list attribute to OM (would need to rename and add docstrings as noted above). We could then still call self._load_txt_file_to_list in self.save_variables where it is now to ensure it's available but then could have that list available in self._variables_pool_inclusion_filter as an attribute of OM.

2023-05-29 16:49 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        self._dict_to_file_json(self.variables_pool, file_path)
both of these approaches have design problems. Let's change _variables_pool_inclusion_filter to:
`def _filter_variables_pool(self, inclusion_keys: List[str]):
        """TODO"""
        return {
            key: self.variables_pool[key]
            for key in inclusion_keys
            if key in self.variables_pool.keys()
        }`
and not use filter().

2023-05-31 19:03 UTC, ew3361zh commented
@PooyaHekmati can you please review again to see if your requested changes have been addressed?

2023-05-31 19:29 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        List
```suggestion
        List[str]
```

2023-05-31 19:29 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            A list of keys the user has selected to filter the variables pool.
This is just a specific use case of this function. The functionality is broader and more general.

2023-05-31 19:29 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            with open(path) as keys_doc:
same as above, this function can be used for different purposes, keys_doc is too specific.

2023-05-31 19:29 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            A list of keys the user has selected to filter the variables pool.
Let's also make it clear that each line in the files ends up being an element in the list.

2023-05-31 19:29 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _filter_variables_pool(self, inclusion_keys: List[str]):
missing type annotation for the return value

2023-05-31 19:29 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            The variables_pool with only the values paired with the keys
I'm not sure if this is correct. It does not return the variables_pool, it makes a new dictionary; i.e., it has no side effect on the vars pool.

2023-05-31 19:29 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        path : str
can we rename this save_path?

2023-05-31 19:29 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        self._dict_to_file_json(final_pool, file_path)
I know I wrote this code, but now that I'm looking at it, the extra variable is not needed.
```suggestion
        if exclude_info_maps:
            filtered_pool = self._exclude_info_maps(filtered_pool)
        file_path = os.path.join(path, self._generate_file_name("saved_variables", "json"))
        self._dict_to_file_json(filtered_pool, file_path)
```

2023-05-31 19:29 UTC, PooyaHekmati commented on tests/test_misc.py
> +        "key2": {
how is it possible to not have info map?

2023-05-31 19:29 UTC, PooyaHekmati commented on tests/test_misc.py
> +    # Test case 3: Pool without info_maps
Same as above

2023-05-31 19:29 UTC, PooyaHekmati commented on tests/test_misc.py
> +    file_path = tmpdir.join("test_file.txt")
is my understanding correct that this test case is actually saving a file in tmp path?
If yes, then this is not the right approach because failure to save/open the file can make this test fail while the actual code can work; therefore, getting misleading signals. Instead, the open() function needs to be mocked. Also, since the function can raise an exception, that behavior needs to be tested as well (mock open() such that it raises an exception, then call _load_txt_file_to_list() and ensure it raises the exception.)

2023-05-31 19:29 UTC, PooyaHekmati commented on tests/test_misc.py
> +    mock_output_manager.dummy_keys_list = ['apple', 'orange', 'banana']
why is this needed?

2023-05-31 19:29 UTC, PooyaHekmati commented on tests/test_misc.py
> +    }
don't repeat yourself

2023-05-31 19:29 UTC, PooyaHekmati commented on tests/test_misc.py
> +    )
save_variables also makes calls to _load_txt_file_to_list and _filter_variables_pool and makes decision to either call _exclude_info_maps or not. These are not being tested.

2023-05-31 19:59 UTC, ew3361zh commented on tests/test_misc.py
> +        "key2": {
I was just trying to supply different possibilities of potential pools (even those outside the expected). I can delete this section if it seems extraneous.

2023-05-31 21:39 UTC, JoeWaddell requested changes

2023-05-31 21:39 UTC, JoeWaddell commented on RUFAS/output_manager.py
> +            A list of keys the user has selected to filter the variables pool.
For my own clarity: should this be explained in the short summary, or better in the Returns section so that the user has a better idea of the list structure in relation to the input? Or both?

2023-05-31 21:39 UTC, JoeWaddell commented on main.py
> +        output_manager.save_variables(r"output", r"input/list_of_keys.txt", exclude_info_maps)
Running this branch fails because `input/list_of_keys.txt` doesn't exist (you noted that it won't be in this PR in the description, but should this method simply save a single JSON with everything if no keys are specified?).

Also, the idea here is that we'll add a new line for each output, specifying a different list of keys each time? Will this be handled differently in future OM PRs, or in the Input Manager PR? Alternatively, could/should this be all done in one JSON, to reduce the times that a user needs to modify the code itself?

Also to check that I'm understanding  the workflow as it is: if we want some general analysis with all keys, but also a pair of smaller analyses, we would have three calls to `output_manager.save_variables` using e.g. `general_analysis_keys.txt`, `methane_analysis_keys.txt`, and a `ration_analysis_keys.txt`
It then saves the three different output JSONs with the name as defined in the `_generate_file_name` method, correct?

2023-06-01 01:38 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            A list of keys the user has selected to filter the variables pool.
My thought - based on the description of what the short summary should be ("A one-line summary that does not use variable names or the function name") - is that this type of info should be in the returns section.

2023-06-01 01:53 UTC, ew3361zh commented on main.py
> +        output_manager.save_variables(r"output", r"input/list_of_keys.txt", exclude_info_maps)
> Running this branch fails because `input/list_of_keys.txt` doesn't exist (you noted that it won't be in this PR in the description, but should this method simply save a single JSON with everything if no keys are specified?).

Maybe I should have better explained - this is the 2nd of 5 parts to the filtering variables functionality of save_variables. I didn't add this because the next couple PRs expand the capabilities of the save_variables function.

I provided the example images so the tester could run the simulation successfully by adding a similar txt file (but with the same name) to the inputs folder.

Not sure if this was a good practice but I didn't want to add files that we would be deleting in the next PR. Sorry for the confusion.

> Also, the idea here is that we'll add a new line for each output, specifying a different list of keys each time? Will this be handled differently in future OM PRs, or in the Input Manager PR? Alternatively, could/should this be all done in one JSON, to reduce the times that a user needs to modify the code itself?

> Also to check that I'm understanding the workflow as it is: if we want some general analysis with all keys, but also a pair of smaller analyses, we would have three calls to `output_manager.save_variables` using e.g. `general_analysis_keys.txt`, `methane_analysis_keys.txt`, and a `ration_analysis_keys.txt` It then saves the three different output JSONs with the name as defined in the `_generate_file_name` method, correct?

Yes, the next few PRs will expand the capabilities of the save_variables function to: 
1. Handle multiple input variable filter files, use them to filter the variables_pool accordingly, and then save each resulting filtered_pool.
2. Differentiate between whether each file wants save_variables to be inclusive or exclusive of the list of variables provided. Inclusive is what we have currently and the exclusive version will save everything in the variables_pool EXCEPT for the variables listed in the file.

If you're interested, you can take a peek at draft PR #544 which is the next step (handling multiple files) and I have a draft of the step after that I should get to Github tonight (both of which were branched off of this branch before today's changes requested from Pooya).

Let me know if you have any other questions and thanks for the great feedback and questions!

2023-06-01 02:35 UTC, PooyaHekmati commented on tests/test_misc.py
> +        "key2": {
It is a good idea to have more comprehensive test cases. My concern is that someone may read this in the future and assume it is ok to not have info maps. Maybe we can fix it by adding a comment to emphasize that info map is expected to exist, we are just being extra cautious here.

2023-06-01 02:41 UTC, PooyaHekmati commented on main.py
> +        output_manager.save_variables(r"output", r"input/list_of_keys.txt", exclude_info_maps)
I think Joe has a point: what is the expected behavior if the user doesn't provide the file containing the list of keys? I would say in that case the save_variables shouldn't do anything because it is possible that the user is only interested in the dumps. However, I wouldn't add an if condition here to check if the file exists or not because in the next PR, there will be a for loop which runs for each file in the directory. If there are no files, then that for loop will not do anything. In other words, the non-existing file is temp issue.

2023-06-01 12:06 UTC, ew3361zh commented on main.py
> +        output_manager.save_variables(r"output", r"input/list_of_keys.txt", exclude_info_maps)
I think we can do a couple things:

1. Add a temporary file so to prevent crashes for the period where this is merged into master before the next PR.
2. Merge the next PR into this PR before merging this PR into master.

It is a reminder to me though that I need to add a .keep file to each of the directories containing these files.

2023-06-01 12:28 UTC, JoeWaddell commented on main.py
> +        output_manager.save_variables(r"output", r"input/list_of_keys.txt", exclude_info_maps)
Thanks for the feedback/answers, and I think your two suggestions here sound good. I'll look ahead at your other PRs, as well, to have a better sense of where you're headed with this. Nice work!

2023-06-01 12:58 UTC, ew3361zh commented on main.py
> +        output_manager.save_variables(r"output", r"input/list_of_keys.txt", exclude_info_maps)
I'll go ahead and add the temp txt file which, even if we decide to merge everything into this PR before merging into master, we can delete later. It seems like a small enough thing not to need to set up an issue for but I know that can get us in trouble so I'll make a quick issue to delete it later as well.

2023-06-01 14:18 UTC, ew3361zh commented on RUFAS/output_manager.py
> +        self._dict_to_file_json(self.variables_pool, file_path)
Implemented

2023-06-01 14:19 UTC, ew3361zh commented on RUFAS/output_manager.py
> +        self.save_variables(path, input_path, exclude_info_maps)
Moved to main.py

2023-06-01 14:20 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            with open(path) as keys_doc:
Updated to "with open(path) as text_file:"

2023-06-01 14:21 UTC, ew3361zh commented
@PooyaHekmati I've addressed the changes requested, please take another look and let me know if you have any other thoughts/feedback

2023-06-01 17:07 UTC, JoeWaddell commented
I've tested it after the updates and example keys.txt file, and it works well! Nice job.

2023-06-01 18:23 UTC, JoeWaddell approved these changes

2023-06-01 22:01 UTC, PooyaHekmati approved these changes

2023-06-02 13:52 UTC, merged