Filter_variables_pool Pattern Matching
RuminantFarmSystems/RuFaS pull request #549
Opened 2023-06-01 18:58 UTC by ew3361zh

This PR seeks to address issue #525 to implement pattern matching by variables read from the filter keys text files in the `_filter_variables_pool` function in OM. 

# To accomplish this, the PR:
1. Adapts the existing dictionary comprehension filters in the `_filter_variables_pool` to filter by partial matches and ignores case.
2. Updates testing for `_filter_variables_pool` to test new functionality.

2023-06-09 17:27 UTC, JoeWaddell approved these changes
Looks good to me

2023-06-09 17:27 UTC, JoeWaddell commented on tests/test_misc.py
> +    # Test case 6: filter_keys with partial matches
Nice test, and brings to mind that we'll need to be careful about writing variable names that are partial matches for other variable names. We can of course simply *exclude* the unwanted names, as long as those exclusions aren't partial matches for _another_ name.

2023-06-12 14:08 UTC, ew3361zh commented on tests/test_misc.py
> +    # Test case 6: filter_keys with partial matches
Agreed. I think this may influence how we name variables added to the variables pools as well. I will be adding notes on all these changes to the OM wiki page that will provide an overview with some examples to highlight how it works and hopefully show people how the naming can influence the filtering.

2023-06-12 16:40 UTC, PooyaHekmati requested changes
The implemented logic works by finding substrings in keys. Issue #525 explicitly asks for pattern matching using regex, which is different from checking if a substring exists in a key. For instance, `LifeCycleManager.daily_update.life_cycle_daily_herd_update` is a match for pattern `^LifeCycleManager.*update$` while `Cow.milking_update.milk_data_at_milk_update` is not a match for this pattern. This also addresses @JoeWaddell 's concern/question.

- Python's Regex doc can be found [here](https://docs.python.org/3/library/re.html)
- A sample Regex tutorial can be found [here](https://www.geeksforgeeks.org/regular-expression-python-examples-set-1)
- [Regex Cheatsheet](https://www.debuggex.com/cheatsheet/regex/python)

2023-06-14 02:57 UTC, PooyaHekmati approved these changes

2023-06-14 02:57 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        filter_by_exclusion = filter_patterns and filter_patterns[exclude_keyword_location] == exclude_keyword
In the next PR, if filter_patterns is empty, we should log it. Also, if it only contains 'exclude' we should log it. Generally speaking, we should log how many filters are provided.

2023-06-14 02:57 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                    any(re.match(pattern, key) for pattern in filter_patterns)}
In the next PR, where you are adding logs, you can create a variable and assign these dics to it (instead of directly returning them). This way you log the number of keys that are matched.

2023-06-14 02:57 UTC, PooyaHekmati commented on tests/test_misc.py
> +        "DummyClass4.dummy_fun2.dummy_var5": "value7"   # new class, same fun name as 3rd entry, new var
I like this

2023-06-14 02:57 UTC, PooyaHekmati commented on tests/test_misc.py
> +    }
We don't need to hold this PR for this issue, but this is duplicated code. Also, I see similar structures. This can be greatly improved using fixtures and data providers.

2023-06-14 13:29 UTC, merged