Output gatherer annual
RuminantFarmSystems/RuFaS pull request #552
Opened 2023-06-02 18:04 UTC by matthew7838

### Summary
This PR extends the output manager function with a `send_annual_variable` method. It is almost identical to PR# 527.

2023-06-05 23:00 UTC, Isgotkowitz requested changes
Great start Matthew, only noticed a couple things. The changes in water content and nitrates, and some extra assertions in the test. Lmk if you're unsure of how the water and nitrate changes should be recorded.

2023-06-05 23:00 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/manager/output_gatherer.py
> +            self.om.add_variable("annual_irrigation_water_use_total",
Changes in water content and total nitrates should be recorded as well.
These will need to be calculated (`self.initial_water_content - self.profile_soil_water_content`, and likewise for nitrates) and initialized in `post_init()` of `SoilData` because I must have forgotten to add them.

2023-06-05 23:00 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/manager_tests/test_output_gatherer.py
> +    assert 'field name 2  layer index 3.annual_denitrified_nitrogen_total' in pool.keys()
These are unnecessary, they are tested implicitly in the assertions below.

2023-06-07 15:26 UTC, Isgotkowitz approved these changes
Nice job Matthew. Other than the `filter_specs` I think it looks good.

2023-06-07 15:26 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/manager/output_gatherer.py
> +    def send_annual_variables(self, filter_specs: Optional[List] = None) -> None:
```suggestion
    def send_annual_variables(self) -> None:
```
I think we are good to not include any kind of filter because `OutputManager` will handle all filtering for us.

2023-06-09 14:42 UTC, ew3361zh approved these changes
Looks good! I had a couple minor questions but seems to be working as designed and has good unit test coverage!

2023-06-09 14:42 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/manager/output_gatherer.py
> +            info_map["prefix"] = "field:'" + field.field_data.name + "'"
I'm curious about the single quotes added here. Can you explain a little on what they're doing?

2023-06-09 14:42 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/tests_SC/manager_tests/test_output_gatherer.py
> +    field_data_1 = FieldData(name=" name 1 ")
any reason to add the extra spaces here when they weren't added on the daily variables version of the field name?

2023-06-09 16:15 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/manager/output_gatherer.py
> +            info_map["prefix"] = "field:'" + field.field_data.name + "'"
We think that it might make it easier for whoever's accessing to identify the actual "data" from a string.

2023-06-09 16:16 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/tests_SC/manager_tests/test_output_gatherer.py
> +    field_data_1 = FieldData(name=" name 1 ")
Yea, that's something I missed. Good catch, thanks a lot.

2023-06-13 19:34 UTC, merged