Field manager routine and current weather implementation
RuminantFarmSystems/RuFaS pull request #582
Opened 2023-06-20 16:11 UTC by matthew7838

### Summary
This PR deals with an annual and daily routine in the `FieldManager` and the current object that will be be transformed and passed in during the routine.
### Changes

**FieldManager**
- `daily_update_routine` runs the manage field method with the provided time and weather in every field and sends the result to the output manager after the run.
- `annual_update_routine` simply runs `perform-annual_reset` on every field and sends the result to output manager after the run.
- `_date_conversion_month` converts the day number of the time object into the month of the year
- `_date_conversion_day` converts the day number of the time object into the day of the month

**CurrentWeather**
- `check_current_weather`  construct the values for the CurrentWeather class
- `_determine_daylength` is another classless helper method that helps determine day length and will be called in `check_current_weather`

### NOTES
**CurrentWeather**

- `snowfall` will not be used since it does not exist in our data at this stage.
- The original `_determine_daylength` are no longer in use due to its inaccuracy is not enough to produce a difference in day length in a matter of hours, it will now use the data of Madison's day length on the first day of each month to approximate the day length as a temporary solution.

2023-06-23 16:19 UTC, Isgotkowitz requested changes
Great start on the `FieldManager`. Left comments on some areas where things need to be added or cleaned up.

2023-06-23 16:19 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/manager/current_weather.py
> +        cls.daylength = _determine_daylength(latitude=latitude, year=year, month=month, day=day)
The `irrigation` field should be added here.

2023-06-23 16:19 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/manager/current_weather.py
> +    sin_delta = _deg_trig(lamb) * _deg_trig(maximum_tilt)
There should be a proper docstring here. Also, all the inline comments should be moved to the notes section.

2023-06-23 16:19 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/manager/field_manager.py
> +        Converts the day number into the corresponding day of the month.
```suggestion

        Converts the day number into the corresponding day of the month.
```

2023-06-23 16:19 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/manager/field_manager.py
> +        corresponding day of the month
```suggestion
            Corresponding day of the month.
```

2023-06-23 16:19 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/manager_tests/test_current_weather.py
> +    patch_determine_daylength = mocker.patch('SC_redesign.Crop_and_Soil.manager.current_weather._determine_daylength',
Nice

2023-06-23 16:19 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/manager/field_manager.py
> +        self.om = OutputGatherer(fields=self.fields)
```suggestion
        self.fields: List[Field] = []
        self.output_gatherer = OutputGatherer(fields=self.fields)
```
These attributes should have docstrings below them describing what they are.
Also `om` would not be a good name here because that is the abbreviation for the `OutputManager`, so using it here for the `OutputGatherer` would lead to a lot of confusion for someone looking at this code who hadn't already spent a bunch of time working with it.

2023-06-23 16:19 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/manager/current_weather.py
> +def _deg_trig(degree, fun=numpy.sin):
Return type annotation

2023-06-23 16:19 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/manager_tests/test_current_weather.py
> +
`_determine_daylength()` needs to be tested here. It seems unlikely that it will be super accurate, but it should demonstrate that the lengths of days changes over the course of the year.

2023-06-23 16:19 UTC, Isgotkowitz commented on SC_redesign/docs_SC/Admin/finish_line_doc.md
>    - [ ] Replace calls to old annual fields routine with calls to new one in `SimulationEngine`. - 1 point
In the `OutputGatherer` section, you can check the box for output gatherer being implemented in FieldManager

2023-06-23 16:19 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/manager_tests/test_field_manager.py
> +    setattr(mocked_time, "day", 5)
```suggestion
```
`mocked_time` is never used so it doesn't need to be included.

2023-06-23 16:25 UTC, Isgotkowitz commented
> ### Summary
> This PR consist of two different parts, one is annual and daily routine in the `FieldManager`, another is about transfoming`weather` object into a CurrentWeather object.
> 
> ### Changes
> **FieldManager**
> 
> * `daily_update_routine` runs the manage field method with the provided time and weather in every field and send the result to ouputmanager after the run.
> * `annual_update_routine` simply runs `perform-annual_reset` on every field and send the result to ouputmanager after the run.
> * `_date_conversion_month` converts the day number of the time object into the month of the year
> * `_date_conversion_day` converts the day number of the time object into the day of the month
> 
> **CurrentWeather**
> 
> * `check_current_weather`  construct the values for the CurrentWeather class
> * `_deg_trig` is just a classless helper method to turn radians to degrees
> * `_determine_daylength` is another classless helper method that helps determine day length and will be called in `check_current_weather`
> 
> ### NOTES
> **CurrentWeather**
> 
> * `snowfall` will not be used since it does not exist in our data at this stage.
> * `_deg_trig` and `_determine_daylength` is more of an approximate estimate for now and will be revisisted post v1 when we includes elevation in our data
> * `_deg_trig` and `_determine_daylength` are classless because `juliandate.__h_m_s(JSet-JRise)` will somehow break if it belongs to a class, and since this is a approximate method that will be revisited in post v1, we'll leave it classless for now as long as it's working.

I think there is an appropriate amount of functionality here for a single PR and this description is by no means inaccurate, but the way it is written frames it as a dual-purpose PR and not a single-purpose one. So it would not be unreasonable for reviewers to look at this description and request that it be broken up into two PRs without looking at the code at all.

2023-06-23 19:44 UTC, Isgotkowitz approved these changes
Nice job Matthew. Just noticed a few small things, otherwise looks great.

2023-06-23 19:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/manager/current_weather.py
> +            Month of the eyar
```suggestion
            Month of the year.
```

2023-06-23 19:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/manager/current_weather.py
> +            day length of the month (hour)
```suggestion
    int
            Day length of the month (hour)
```

2023-06-23 19:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/manager/field_manager.py
> +
```suggestion
```

2023-06-23 19:44 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/manager_tests/test_current_weather.py
> +                               mocker) -> None:
```suggestion
                               ) -> None:
```

2023-06-26 17:38 UTC, JoeWaddell approved these changes
Looks good to me, just a couple minor formatting requests/question

2023-06-26 17:38 UTC, JoeWaddell commented on SC_redesign/Crop_and_Soil/manager/current_weather.py
> +"""
Should this all go in the class' docstring?

2023-06-26 17:38 UTC, JoeWaddell commented on SC_redesign/Crop_and_Soil/manager/current_weather.py
> +    irrigation: float = 0
This and others (above/below) should be 0.0, instead of 0, since they're floats

2023-06-27 15:31 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/manager/current_weather.py
> +"""
Good catch.

2023-06-27 15:41 UTC, merged