Updating housing ammonia emission calculations in manure handlers
RuminantFarmSystems/RuFaS pull request #600
Opened 2023-06-26 21:57 UTC by ltp23

This PR updates the calculations of housing ammonia emissions in the manure handlers.

The main changes happen in the two files manure_handler_classes.py and gas_emission.py.

2023-06-28 14:40 UTC, varrma approved these changes
Looks good Loi, couple of comments about the variable description and units.

2023-06-28 14:40 UTC, varrma commented on RUFAS/routines/manure/constants/gas_emission_constants.py
> +    """Achievable emission of :math:`CH_4` during anaerobic digestion (#TODO: units?)."""
Bo = achievable emission of CH4 during anaerobic digestion, kg CH4/kg VS

2023-06-28 14:40 UTC, varrma commented on RUFAS/routines/manure/constants/gas_emission_constants.py
> +    """#TODO"""
0.67 = conversion factor of m3 CH4 to kg CH4

2023-06-28 14:59 UTC, JoeWaddell requested changes
Looks good to me: my only comments overlap a little with those of Varma, as they're mostly about documentation.

2023-06-28 14:59 UTC, JoeWaddell commented on RUFAS/routines/manure/constants/gas_emission_constants.py
>      MCF = 0.79
Should these names be extended for clarity, e.g. for this case `methane_conversion_factor`, or does that lead to excessive line length in some areas?

2023-06-28 14:59 UTC, JoeWaddell commented on RUFAS/routines/manure/gas_emissions/gas_emissions.py
> +        pH : float, optional
Since these are labeled optional here, should the typing hint in the args be something like `ph: Optional[float] = GasEmissionConstants.DEFAULT_PH_FOR_HOUSING_AMMONIA`? Or is it simply a style choice?

2023-06-28 14:59 UTC, JoeWaddell commented on RUFAS/routines/manure/gas_emissions/gas_emissions.py
> +        loss = (TAN * c * p) / (r * M * Q)
Should these variables be given longer names, or listed with their definitions in a Notes section in the docstring? Just thinking ahead when folks might later tweak or add to these equations. If they come directly from the literature, maybe just adding that to a References section would be a good thing for documentation

2023-06-28 14:59 UTC, JoeWaddell commented on RUFAS/routines/manure/pen_manure/pen_manure.py
> +        # TODO: This is a temporary fix. Need to find out why negative values are being generated
Could you make an issue with what inputs/conditions generate a negative value?

2023-06-28 16:09 UTC, ltp23 commented on RUFAS/routines/manure/constants/gas_emission_constants.py
>      MCF = 0.79
Thanks Joe.  I can change MCF to METHANE_CONVERSION_FACTOR.

2023-06-28 16:14 UTC, ltp23 commented on RUFAS/routines/manure/gas_emissions/gas_emissions.py
> +        pH : float, optional
That's a good point, Joe. But conveniently, when a parameter is written like that`param=default_value`, the parameter will assume the type of `default_value_type | None` (alternative notation for Optional). In this case, it would be `float | None`.

2023-06-28 19:23 UTC, ltp23 commented on RUFAS/routines/manure/gas_emissions/gas_emissions.py
> +        loss = (TAN * c * p) / (r * M * Q)
I think a good trade-off would be this: In the Notes section of the docstring, I would state the original formula as presented in the literature, but then in the code, I would replace the symbols in the formula with descriptive names.

2023-06-28 20:44 UTC, ltp23 commented on RUFAS/routines/manure/pen_manure/pen_manure.py
> +        # TODO: This is a temporary fix. Need to find out why negative values are being generated
Ok Joe. I made a git issue for this ([#609](https://github.com/RuminantFarmSystems/MASM/issues/609)).

2023-06-29 14:05 UTC, JoeWaddell approved these changes
Thanks for the informative replies and relevant modifications: looks great!

2023-06-29 19:25 UTC, merged