test coverage for SC_redesign branch  (1/3)
RuminantFarmSystems/RuFaS pull request #605
Opened 2023-06-28 03:40 UTC by matthew7838

### Summary
This PR covers the first half of any files that were uncovered while running the coverage tool, some tests were added and some were patched with conditions that did not meet and led to insufficient coverage. The next related PR will be solely focusing on rewriting tests for `water_uptakes.py` since it's missing a significant amount of tests and might requires a major rewrite on testing.

### Changes
- Tests for the crop.py is added, it's missing completely
- Fixed `crop_data.py` and `dormancy.py` bugs that are related to the same syntax error and were never tested.
- In `test_crop_data.py`, fixed testing for `test_in_growing_season_property`, now the `growing` variable is used
- In `cropdata.py`, deleted post init part that checks for type `TREE` since it wasn't part of any crop and was never used
- Added tests to test extend_phosphate_uptakes_to_full_profile in `phosphorus_incorporation.py`
- In `test_crop_management.py`, `cut_crop` is now properly tested
- In `test_dormacy.py` and `test_nitrogen_incorporation.py` new parameters were passed in to make sure errors are caught

### **Notes**
!!**Ignore**  anything to `test_water_uptake.py` since it is merged from a preapproved PR.!!

2023-06-29 20:45 UTC, Isgotkowitz requested changes
Nice start Matthew, the Crop test suite is looking much better. I've requested changes on the way that errors are being tested, other comments are small typos and formatting issues.

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/crop.py
> +            self.biomass_allocation.allocate_biomass(incoming_light)
Nice

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/dormancy.py
> +        if self.data.plant_category == PlantCategory.WARM_ANNUAL or self.data.plant_category ==\
```suggestion
        if self.data.plant_category == PlantCategory.WARM_ANNUAL or self.data.plant_category == \
```

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_crop_data.py
> +    """A seperate test to check the dormacy loss for future use of TREE"""
```suggestion
def test_tree_dormancy_loss() -> None:
    """A seperate test to check the dormancy loss for future use of TREE"""
```

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_crop_management.py
>      """ensure that the crop cutting routines are properly executed"""
```suggestion
    """ensure that the crop cutting routines are properly executed"""
```
I think it would be good to add here that this method also tests for errors being raised properly.

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_crop_management.py
>      """ensure that the crop cutting routines are properly executed"""
```suggestion
    """ensure that the crop cutting routines are properly executed"""
```
I think it would be good to add here that this method also tests for errors being raised properly.

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_crop_management.py
> +        return
This is a problematic way to test error raising, because there isn't strong indication of whether or not an error should be raised here. So it is possible, though unlikely, that a test case which should throw an error runs the method correctly and the test case does not fail. The assertion of `not 0 <= efficiency <= 1.0` is good because it prevents the opposite case from happening, but it is duplicates logic from the method inside the test which should be avoided as much as possible.

There are two ways I can think of that would enhance testing for errors:
1) Include a bool parameter `should_fail` in the test method signature, and include it in each test case. If `should_fail` is true, then check that an error is thrown. Otherwise, check that the method is run correctly.
2) Write a second test method that exclusively tests for errors, while this method exclusively tests that the method is running correctly. This would be the preferred way, because it is how other methods are tested for error raising.

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_dormancy.py
> +        if incorp.data.plant_category == PlantCategory.PERENNIAL or\
```suggestion
        if incorp.data.plant_category == PlantCategory.PERENNIAL or \
```

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_leaf_area_index.py
> +def test_grow_canopy(heatfrac, previous_leaf_area_index: int, previous_optimal_leaf_area_fraction: int):
```suggestion
def test_grow_canopy(heatfrac: float, previous_leaf_area_index: float, previous_optimal_leaf_area_fraction: float) -> None:
```

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_leaf_area_index.py
> +        print(str(data.previous_leaf_area_index) + "a")
```suggestion
```

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_leaf_area_index.py
> +            assert data.leaf_area_index == 0 + added
```suggestion
            assert data.leaf_area_index == added
```

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_nitrogen_incorporation.py
> +                                                                        mature)
Same as above

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_nitrogen_incorporation.py
> +        return
Same as above

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_nitrogen_incorporation.py
> +        return
Same as above

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_nitrogen_incorporation.py
> +        return
Same as above

2023-06-29 20:45 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_phosphorus_incorporation.py
> +    data = CropData(actual_phosphorus_uptakes=[1.0, 2.0, 3.0], inaccessible_soil_layers=layers)
Docstring here

2023-06-30 15:05 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_crop_management.py
> +        return
Great suggestions, thanks.

2023-06-30 16:22 UTC, Isgotkowitz requested changes
Please execute the suggested changes.

2023-06-30 16:22 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_leaf_area_index.py
> +        print(str(data.previous_leaf_area_index) + "a")
What is this print statement, and why does it need to be here?

2023-06-30 16:22 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_leaf_area_index.py
> +            assert data.leaf_area_index == 0 + added
Why is 0 being added here?

2023-06-30 16:22 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_leaf_area_index.py
> +def test_grow_canopy(heatfrac, previous_leaf_area_index: int, previous_optimal_leaf_area_fraction: int):
Please add these docstring changes

2023-06-30 16:22 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_crop_data.py
> +    """A seperate test to check the dormacy loss for future use of TREE"""
Why was this marked resolved?

2023-06-30 21:20 UTC, Isgotkowitz approved these changes
Looks good Matthew, nice job. Only comments are a small typo and some missing return types

2023-06-30 21:20 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_crop_data.py
> +    """A saperate test to check the dormancy loss for future use of TREE"""
```suggestion
    """A separate test to check the dormancy loss for future use of TREE"""
```

2023-06-30 21:20 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_nitrogen_incorporation.py
> +                                             near: float, mature: float, should_fail: bool):
```suggestion
                                             near: float, mature: float, should_fail: bool) -> None:
```

2023-06-30 21:20 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_nitrogen_incorporation.py
> +def test_determine_shape_log(heatfrac: float, current: float, mature: float, emergence: float, should_fail: bool):
```suggestion
def test_determine_shape_log(heatfrac: float, current: float, mature: float, emergence: float, should_fail: bool) -> None:
```

2023-06-30 21:20 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_nitrogen_incorporation.py
> +                                         should_fail: bool):
```suggestion
                                         should_fail: bool) -> None:
```

2023-07-18 19:28 UTC, ew3361zh approved these changes
LGTM - running smoothly - be interested to know the test coverage jump this provided. Tried comparing current methods with current coverage and didn't find any glaring gaps. Nice work!

2023-07-19 05:02 UTC, merged