Add timestamps to the OutputManager's info_map data when adding logs, errors, and warnings.
RuminantFarmSystems/RuFaS pull request #610
Opened 2023-06-28 23:18 UTC by michaelRichards99

Added timestamp info to the OutputManager when adding logs, errors, and warnings. Consolidated file timestamp creation to use the same method. Added checks to the existing unit tests to check that the timestamp information is present.

Fixes #598.

2023-06-29 03:43 UTC, PooyaHekmati requested changes
Nice work! It's good to have functions with clear responsibilities. The newly developed functions need to have test cases as well.

2023-06-29 03:43 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        base_timestamp_str: str = "%d-%b-%Y_%a_%H-%M-%S"
Can you add an example in the docstring to show what this looks like?

2023-06-29 03:43 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        """Produce the current system time as a timestamp string."""
```suggestion
        """Produces the current system time as a timestamp string."""
```

2023-06-29 03:43 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        """Add the current system time to the info_map."""
```suggestion
        """Adds the current system time to the info_map."""
```

2023-06-29 03:43 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _add_timestamp_to_info_map(self, info_map: Dict[str, Union[str, bool]]) -> None:
```suggestion
    def _add_timestamp_to_info_map(self, info_map: Dict[str, Any]) -> None:
```
Why Union[str, bool]?

2023-06-29 03:43 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        timestamp: str = self._get_timestamp()
```suggestion
        timestamp: str = self._get_timestamp(include_millis=False)
```

2023-06-29 03:43 UTC, PooyaHekmati commented on tests/test_misc.py
> +    assert info_map["timestamp"] is not None
Let's also check for the correctness of the value. You'd need to mock datetime.datetime.now() and manually set its return value.

2023-06-29 03:43 UTC, PooyaHekmati commented on tests/test_misc.py
> +    assert info_map["timestamp"] is not None
Same

2023-06-29 03:43 UTC, PooyaHekmati commented on tests/test_misc.py
> +    assert info_map["timestamp"] is not None
Same

2023-06-29 03:43 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _add_timestamp_to_info_map(self, info_map: Dict[str, Union[str, bool]]) -> None:
Maybe this function is overkill and not needed?

2023-06-29 03:43 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        self._add_timestamp_to_info_map(info_map)
```suggestion
        info_map["timestamp"] = self._get_timestamp(include_millis=True)
```

2023-06-29 18:36 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        self._add_timestamp_to_info_map(info_map)
done

2023-06-29 18:36 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +    def _add_timestamp_to_info_map(self, info_map: Dict[str, Union[str, bool]]) -> None:
yeah it's not really necessary. removed.

2023-06-29 18:36 UTC, michaelRichards99 commented on tests/test_misc.py
> +    assert info_map["timestamp"] is not None
done.

2023-06-29 18:36 UTC, michaelRichards99 commented on tests/test_misc.py
> +    assert info_map["timestamp"] is not None
done.

2023-06-29 18:37 UTC, michaelRichards99 commented on tests/test_misc.py
> +    assert info_map["timestamp"] is not None
It's tricky to directly mock python built-ins such as as DateTime without adding a new 3rd party library or manually mocking with some sort of reflection. I've mocked _get_timestamp from the OutputManager class instead.

2023-06-29 18:37 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        timestamp: str = self._get_timestamp()
done.

2023-06-29 18:37 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +    def _add_timestamp_to_info_map(self, info_map: Dict[str, Union[str, bool]]) -> None:
I copied the type from another method in the OutputManager. I removed the method completely so no longer applies.

2023-06-29 18:38 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        """Add the current system time to the info_map."""
method removed.

2023-06-29 18:38 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        """Produce the current system time as a timestamp string."""
done.

2023-06-29 18:38 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        base_timestamp_str: str = "%d-%b-%Y_%a_%H-%M-%S"
done.

2023-06-30 03:31 UTC, PooyaHekmati approved these changes
[![LGTM](https://lgtm.lol/p/718)](https://lgtm.lol/i/718)

2023-07-03 17:56 UTC, Isgotkowitz requested changes
Nice PR Michael, looks very good overall. First comment is on some missing sections in the `_get_timestamp()` docstring, and the second has some minor formatting corrections to the `Examples` section of the same docstring.

2023-07-03 17:56 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +        Example
There should be `Parameters` and `Returns` sections here

2023-07-03 17:56 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +            28-Jun-2023_Wed_15-48-21
```suggestion
        Examples
        --------
        >>> self._get_timestamp(include_millis=True)
        28-Jun-2023_Wed_15-48-21.406585
        >>> self._get_timestamp(include_millis=False)
        28-Jun-2023_Wed_15-48-21
```

2023-07-03 19:32 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +            28-Jun-2023_Wed_15-48-21
Done.

2023-07-03 19:32 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        Example
Done.

2023-07-03 21:31 UTC, Isgotkowitz approved these changes
Nice

2023-07-03 22:02 UTC, merged