Create Input Manager Load Data Function
RuminantFarmSystems/RuFaS pull request #615
Opened 2023-06-29 21:33 UTC by ew3361zh

This PR tries to address issue #608 to create a new function `load_data()` in the Input Manager that will load data from a JSON or CSV file and parse it as instructed by the metadata.

Notes:
1. I'm unsure if there is additional parsing that should be done on the data read from the files.
2. I don't know about the best format for the CSV data. It seemed like a list of rows as dictionaries was one of the standard options but I'm not sure if there's something else that would work better for RuFaS's needs.

2023-07-03 04:28 UTC, PooyaHekmati reviewed
And don't forget about logging :)

2023-07-03 04:28 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        data_files = self.__metadata[metadata_files_key]
```suggestion
        files_details = self.__metadata["files"]
```
I think this is an overkill.
Also changed the name to a more descriptive one.

2023-07-03 04:28 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                if value["type"] == "csv":
```suggestion
                elif value["type"] == "csv":
```

2023-07-03 04:28 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            file_path = value[path_key]
```suggestion
        for key, details in files_details.items():
            file_path = details[path_key]
```

2023-07-03 04:28 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                                   f" added to data pool", info_map)
I think a "be" verb is missing in this sentence. Also, it is a good idea to mention the key. The if statement works on the type that is provided in the metadata, not the file_path.

2023-07-03 13:48 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                                   f" added to data pool", info_map)
Addressed! Good call, thank you.

2023-07-03 15:51 UTC, PooyaHekmati requested changes
I was going to go for LGTM, but lines 86 and 87 don't look correct.

2023-07-03 15:51 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        """Loads data from JSON or CSV fileRaises
typo?

2023-07-03 15:51 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                        self.__pool[key] = data
```suggestion
                        self.__pool[key] = data
                        om.add_log("load_data_successful", f"Successfully loaded data for {key} from {file_path}.",
                                   info_map)
```
Not a big deal but better safe than sorry.

2023-07-03 15:51 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                        self.__pool[key] = list(data_reader)
```suggestion
                        self.__pool[key] = list(data_reader)
                        om.add_log("load_data_successful", f"Successfully loaded data for {key} from {file_path}.",
                                   info_map)
```

2023-07-03 15:51 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                                   f" {file_path} was not a csv nor json file and was not added to data pool", info_map)
is this correct?

2023-07-03 15:55 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                        self.__pool[key] = data
I was wondering if we'd wanted to keep that separate in case there was some issue with adding the data to the pool separate from just loading the data but can certainly go along with this suggestion.

2023-07-03 15:59 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                                   f" {file_path} was not a csv nor json file and was not added to data pool", info_map)
Do you mean the part about it being a warning vs. error? 
Or about taking the action of adding a warning as the main action if this else statement is reached?
Or the message itself?

2023-07-03 16:00 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        """Loads data from JSON or CSV fileRaises
Yep! Addressed.

2023-07-03 16:18 UTC, Isgotkowitz approved these changes
Looks good Niko, only had one comment about how one of the tests could be expanded.

2023-07-03 16:18 UTC, Isgotkowitz commented on tests/test_input_manager.py
> +    assert mock_input_manager._InputManager__pool == {}
Should the `OutputManager` be checked to make sure the correct warning was raised?

2023-07-03 17:33 UTC, ew3361zh commented on tests/test_input_manager.py
> +    assert mock_input_manager._InputManager__pool == {}
It's an interesting idea - we haven't really been testing individual calls to OM methods. I'd be curious what @PooyaHekmati thinks.

2023-07-03 17:43 UTC, PooyaHekmati commented on tests/test_input_manager.py
> +    assert mock_input_manager._InputManager__pool == {}
In an ideal world, yes! Since that is concerning a requirement, it needs to be checked.

2023-07-03 19:12 UTC, ew3361zh commented on tests/test_input_manager.py
> +    assert mock_input_manager._InputManager__pool == {}
Sounds good, I updated the test!

2023-07-06 02:23 UTC, PooyaHekmati approved these changes

2023-07-06 13:08 UTC, merged