Water uptake test rework
RuminantFarmSystems/RuFaS pull request #625
Opened 2023-07-05 05:39 UTC by matthew7838

### Summary
This PR's purpose is to patch up missing tests in `water_uptake.py`, it is stacked on #605  and is part of the work to reach 100% test coverage progress. It's separated as an independent PR due to the fact that most of the functions were not tested.

### Changes
- Added another set of values that tests conditions that were not tested in `test_correct_layer_for_efficiency`
- Added `test_extract_water_from_soil` to test `extract_water_from_soil`
- Added `test_reduce_efficiency_of_uptake` to test `reduce_efficiency_of_uptake`
- Added `test_adjust_water_uptakes` to test `adjust_water_uptakes`
- Added `test_find_stratified_max_water_uptakes` to test `find_stratified_max_water_uptakes`
- Added `test_determine_max_water_uptake_to_depth` to test `determine_max_water_uptake_to_depth`
- Added `test_take_up_water` to test `_take_up_water`

2023-07-05 19:23 UTC, Isgotkowitz requested changes
This is a good start on filling out the test suite, but I noticed some underlying issues with a lot of the tests that need to be addressed. The 2 main things that need changing is the use of `pytest.raises` instead of try-except blocks, and not reproducing logic inside the code.

2023-07-05 19:23 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +            assert str(e) == "actual_water_uptakes should be the same length as the number of soil layers"
I should have mentioned this before but when testing for errors the `pytest.raises()` context manager should be used. In this case, when using that method, this test would be 
```python
with pytest.raises(Exception) as e:
    uptake.extract_water_from_soil(soil_data)
assert str(e.value) == "expected error message"
```

2023-07-05 19:23 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +            assert str(e) == "potential_uptakes, water_availabilities, and available_capacities must be of equal length"
pytest.raises

2023-07-05 19:23 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +        assert expected == WaterUptake._reduce_efficiency_of_uptake(potential_uptakes, water_availabilities,
It would be better to have `_correct_layer_for_efficiency()` mocked and test that it is being called with the expected combinations from the input. Because as this test is now, it is duplicating the exact same logic as what is supposed to be tested.

2023-07-05 19:23 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +            assert str(e) == "potential_uptakes and unmet_demands must be the same length."
pytest.raises

2023-07-05 19:23 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +                              unmet_demands: List[float], uptake_compensation: float, should_fail: bool) -> None:
Because it isn't used at all in the actual method, it may be appropriate to remove the `water_availabilities` parameter from the method. However, before removing it, it should be carefully checked how this method is being used, because it also may be possible that `water_availabilities` should be used here and there was an oversight that lead to it not being used.

2023-07-05 19:23 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +        expected = [uptake + (demand * uptake_compensation) for uptake, demand in zip(potential_uptakes, unmet_demands)]
`expected` should be pre-computed and included with the test case.

2023-07-05 19:23 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +            assert str(e) == "upper_depths and lower_depths must be the same length"
pytest.raises

2023-07-05 19:23 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +
`expected` should be pre-computed and included with each test case

2023-07-05 19:23 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +        expected = term1 * term2
This is a case where pre-computing the expected value is (IMO) not the best strategy for effective testing, because the equation that is at the heart of what is being tested has multiple layers and the result has a lot of decimals. However, word-for-word duplication still renders this test case inconsequential.

So what I to do in cases like these is to move the actual implementation off of my screen so I can't look at it, look at the original equation (in this case, SWAT eqn. 5:2.2.1) and reimplement the equation in the test in a way that differs from the original. This could mean implementing the whole equation in one-line, adding in parentheses that are not strictly necessary, changing the order of terms when possible, ideally all of the above and more. Usually the test logic and the actual method logic produce the same results, but sometimes they will be different and this forces you to recheck both implementations against the equation in the documentation, which helps to catch a lot of bugs.

Also an important thing to know, the `pytest.approx()` feature is really useful when doing this because if two different implementations produce results that are just slightly different then can use `approx` to check that the results are approximately equal.

2023-07-05 19:23 UTC, Isgotkowitz commented on .coverage
This file should not be included in the PR.

2023-07-06 07:11 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +                              unmet_demands: List[float], uptake_compensation: float, should_fail: bool) -> None:
good catch, looking at the reference I think it's not needed.

2023-07-06 16:31 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +from mock import call
```suggestion
from unittest.mock import MagicMock, patch, call
```

2023-07-06 17:18 UTC, Isgotkowitz requested changes
This is a much more robust test suite, thank you Matthew. I still found some duplicated logic and added suggestions for how they could be addressed. Also, the floor function isn't actually used in equation 5:2.2.1 - the pdf is just really poorly formatted.

2023-07-06 17:18 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +        expected = [WaterUptake._correct_layer_for_efficiency(pot, avail, cap) for pot, avail, cap in zipped]
```suggestion
        WaterUptake._correct_layer_for_efficiency = MagicMock(return_value=0.5)
        result = WaterUptake._reduce_efficiency_of_uptake(potential_uptakes, water_availabilities, available_capacities)
        expected_calls = []
        for i in range(len(potential_uptakes)):
            expected_calls.append(call(potential_uptakes[i], water_availabilities[i], available_capacities[i]))
        WaterUptake._correct_layer_for_efficiency.assert_has_calls(expected_calls)
        expected = [0.5] * len(potential_uptakes)
```

2023-07-06 17:18 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +        assert pytest.approx(expected, abs=0.0001) == WaterUptake._find_stratified_max_water_uptakes(
```suggestion
        assert pytest.approx(expected) == WaterUptake._find_stratified_max_water_uptakes(
```

2023-07-06 17:18 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +        assert pytest.approx(expected, abs=0.0001) == WaterUptake._find_stratified_max_water_uptakes(
We should stick with the default absolute tolerance for approx

2023-07-06 17:18 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +        assert expected == result
Same comment here as for `test_reduce_efficiency_of_uptake()`

2023-07-06 17:18 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/water_uptake.py
> +        term2 = math.floor(1 - exp(-water_distro_parameter * depth / root_depth))
I thought the same thing when I was working on some SWAT equations, I had to ask Clay about it. The floor function isn't actually called on `term2`, the formatting of the SWAT theoretical documentation pdf is just really bad so the tops of square brackets have been cutoff.

2023-07-06 17:18 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +    """Tests that the reduced efficiency of uptake is calculated correctly and correct exceptions are thrown"""
In the future, it would be good to write the descriptions of these tests without using 'and'. These descriptions are accurate and easy to read (and so are the tests), but by including 'and' the docstrings make it sound like the tests are dual-purpose.

2023-07-06 18:42 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +        expected = [WaterUptake._correct_layer_for_efficiency(pot, avail, cap) for pot, avail, cap in zipped]
That looks like a way better way to get expected, thanks!

2023-07-06 19:27 UTC, Isgotkowitz approved these changes
Nice, thanks Matthew

2023-07-07 14:32 UTC, ew3361zh approved these changes
Looks good! Nice work, Matthew.

A couple small flake8 checks/changes and then a suggestion about splitting the tests up into more specifically-named scenario tests to get a clearer understanding to future devs for if something fails.

2023-07-07 14:32 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +import math
vs_code is showing `math` as imported but never accessed.

2023-07-07 14:32 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +def test_determine_max_water_uptake_to_depth(root_depth: float, depth: float, max_plant_transpiration: float,
Getting a duplicated test name flake8 violation with this one and what looks like a placeholder test function on line 42.

2023-07-07 14:32 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +    if should_fail:
I think it's usually a good practice to split these types of if/else scenarios into separate tests. This still supplies good coverage but I think it's helpful to have the individual test (e.g. test_extract_water_from_soil fails_when_xyz, and test_extract_water_from_soil_passes_when_xyz) so if/when it fails, you know immediately what's failing based on the name of the test.

2023-07-07 14:32 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/tests_SC/crop_tests/test_water_uptake.py
> +    else:
similar comment on splitting these up. Not a requirement necessarily but I think a better practice.

2023-07-07 15:10 UTC, merged