IM fix_data()
RuminantFarmSystems/RuFaS pull request #646
Opened 2023-07-11 18:40 UTC by allisterakun

# #621  `_fix_data()` in `RUFAS.input_manager`:

> Note: this PR implements the `fix_data()` function in the Input Manager and the related unit tests. All changes to other parts of the code are due to resolving conflicts of merging to the base branch `im_refactor`. Please ignore all unrelated changes and only review the relevant ones.

## `_fix_data() -> bool:`

This function attempts to fix the invalid data with the provided default value. 

It takes in the path to the data, and checks if the variable of interest is critical data by checking if a default value is provided for this variable in the metadata. If the data is fixable (not critical data), this function will replace the value of the variable of interest in the IM variable pool with the provided default value; else, it will return False, indicating critical data (data unfixable).

### Inputs

#### `variable_properties: Dict[str, Any]`
The properties for the variable of interest.

#### `element_hierarchy : List[str]`
A list of strings indicating the path to reach the variable of interest in `self.__metadata` and `self.__pool`.

#### `input_data: Dict[str, Any]`
A buffer dictionary that holds the input data for validation and fixing.

### Returns
#### bool

- **False** If no default value is found (aka critical data), the data is unfixable. 
- **True** If the data is successfully fixed with the provided default value.

2023-07-12 05:06 UTC, allisterakun commented
@ew3361zh As I was implementing the fix_data() function, I found that `self.__pool[module_key][variable_name]` (for example, `self.__pool["animal"]["herd_information"]`) is a nested structure. Will speak to you about this later Wednesday at the work-together session.

2023-07-13 02:38 UTC, allisterakun commented
- [x] Feature Implementation
- [ ] Docstring
- [ ] Logging
- [ ] Unit tests

2023-07-13 03:13 UTC, allisterakun commented
- [x] Feature Implementation
- [x] Docstring
- [x] Logging
- [ ] Unit tests

2023-07-19 17:52 UTC, allisterakun commented
- [x] Feature Implementation
- [x] Docstring
- [x] Logging
- [x] Unit tests

2023-07-19 18:17 UTC, PooyaHekmati requested changes
The logic seems to be correct; however, the docstring is not correct. Also, the variable names can be improved both in the function signature and inside the function body. You have also _validate_string_type_element but there is no mention of it in the PR title or description.

2023-07-19 18:17 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        variable_path : List[str]
This doesn't exist in the function signature.
Please add the args to docstring.

2023-07-19 18:17 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +    def _fix_data(self, module_key: str, property_map_key: str, element_hierarchy: List[str]) -> bool:
Can you come up with better names? These names are not clear, even to me.

2023-07-19 18:17 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +    def _validate_string_type_element(self, variable_to_check: Dict[str, Any], var_name: str,
Isn't this PR about fix_data? What is this function doing here?

2023-07-19 18:17 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            True if the data is fixed, False for critical data.
Let's not use critical data because then we have to define what it means. This terminology was used in the design phase to differentiate the cases, but I don't think it is necessary here. We know what it means today, but those who join later have to figure it out. Let's be kind to them.

2023-07-20 01:05 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                                     self.__pool[module_key])
The variable parent will need to come from the temporary variable holding the data loaded from the file, not the `self.__pool`. With the way I was asked to refactor `_validate_data()`, a variable won't get added to the pool until after it's shown to be valid (or is fixed). 
So `_validate_element()` now takes the full data loaded from each file which you can use in `_fix_data()`.

2023-07-20 16:15 UTC, ew3361zh requested changes
Looks really good, Allister! I have a couple notes about docstrings to update and then it looks like there's some conflicts to resolve based on changes to the im_refactor branch from this morning.

Also I think in one of the previous resolved conflicts it looks like the conflicting `_validate_string_type_element` didn't get removed so it's in the code twice which is why it's showing up as new code here.

<img width="843" alt="Screenshot 2023-07-20 at 12 15 00 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/50427026-6f2e-4ee6-b0d9-233142261413">

2023-07-20 16:15 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        Return True if the data is fixed, False for critical data
Is there a reason this isn't in the Returns section of the docstrings? Seems like it could be confusing to have to separate statements about what this method returns that aren't the same. I think this return statement is a better of the two.

2023-07-20 16:15 UTC, ew3361zh commented on RUFAS/input_manager.py
add docstring for input_data

2023-07-20 17:55 UTC, ew3361zh approved these changes
Nice work, Allister. LGTM.

2023-07-20 17:55 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            A buffer dictionary that holds the input data for validation and fixing.
Nice! I like this, I may update im_refactor `_validate_element` docstrings with this definition as well.

2023-07-21 13:53 UTC, PooyaHekmati approved these changes

2023-07-21 13:53 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            True if the data is fixed, False if there is no default value found.
I think this is too specific, we will change this function down the road and this description won't be true anymore. Can we do something like this to satisfy that as well?
```suggestion
            True if the data is fixed, False otherwise.
```

2023-07-21 13:53 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            The module where data of interest belongs to.
What does module mean here?

2023-07-21 14:52 UTC, michaelRichards99 requested changes

2023-07-21 14:52 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +        variable_metadata: Dict = reduce(lambda d, key: d[key], element_hierarchy,
```suggestion
        variable_metadata: Dict[str, Any] = reduce(lambda d, key: d[key], element_hierarchy,
```
Adds more clarity.

2023-07-21 14:52 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +        if 'default' in variable_metadata.keys():
```suggestion
        if 'default' not in variable_metadata.keys():
            return False
        variable_parent = reduce(lambda d, key: d[key], element_hierarchy[:-1],
                                     input_data[module_key])
        variable_parent[element_hierarchy[-1]] = variable_metadata['default']
        om.add_warning("Data fixed",
                           f"Invalid data fixed: {element_hierarchy[-1]} => {variable_metadata['default']}",
                           info_map)
        return True
```
Do the error check first to remove indentation.

2023-07-21 14:52 UTC, michaelRichards99 commented on RUFAS/input_manager.py
>          Attempt to fix the invalid data.
```suggestion
        Attempt to fix the invalid non-critical data.
```
Should we mention that `_fix_data` only fixes non-critical data and that it doesn't fix critical data?

2023-07-21 15:23 UTC, michaelRichards99 approved these changes

2023-07-21 19:22 UTC, merged