Save simulation variables and the values into a CSV file.
RuminantFarmSystems/RuFaS pull request #650
Opened 2023-07-12 17:46 UTC by michaelRichards99

This address part 1 of the CSV generation for the OutputManager: issue #641.

It pads the values with None, which are inserted into the csv file as nothing instead of the string "None".

2023-07-13 16:48 UTC, ltp23 approved these changes
Thanks Michael. The code's functionality works as expected. I have a few comments for improvement along the way. Thank you for teaching me a few things too.

2023-07-13 16:48 UTC, ltp23 commented on RUFAS/output_manager.py
> +            return
I think we should add a check to make sure we have a `values` field for each key-value pair. It is ok to not create a file at all if we have no data.

2023-07-13 16:48 UTC, ltp23 commented on RUFAS/output_manager.py
> +            writer.writerows(rows)
Although the current implementation works correctly, I would suggest handling the data in a column-oriented fashion instead of a row-oriented one. Most data analysis libraries like `pandas` are optimized for columnar operations through vectorization. For example, here's an alternative way to implement the function:

```python
df = pd.DataFrame({k: pd.Series(v['values']) for k, v in data_dict.items()})
df.to_csv(path, index=False)
```

With this code, pandas automatically handles the variations in the lengths of the value lists by filling in NaN for any missing values, and it also manages the writing of the CSV file.

2023-07-13 16:48 UTC, ltp23 commented on RUFAS/output_manager.py
> +    def dump_variables(self, path: str, format: OutputFormat, exclude_info_maps: bool = False) -> None:
Can you update the docstring this extra parameter?

2023-07-13 16:48 UTC, ltp23 commented on RUFAS/output_manager.py
> +                self._save_variables_to_csv(pool, file_path)
This looks good. I would also add a default case (`case _:`) and handle it (e.g., add a warning, raise an error, do nothing). You could also set a default option and put it at the back of the list. It looks like you want it to be an optional parameter.

2023-07-13 16:48 UTC, ltp23 commented on tests/test_misc.py
> +
I see that you're using `tempfile` to handle throwaway file data, which I think is a nice approach, but in the context of unit testing, we might want to avoid actual I/O operations where possible.

I would suggest using pytest's parametrization feature to test various scenarios and edge cases more concisely (The two provided test cases are good here, but I think you can come up with more.) and also use more mocking to mock out external functions, which helps with focusing on the logic of the function being tested.

2023-07-13 16:53 UTC, PooyaHekmati requested changes
For each entry in the vars pool save a CSV file. To deal with nested structures, use str() for now.

2023-07-13 16:53 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        Enumeration that represents valid output encodings for OutputManger pools
1. These are data formats not encoding.
2. Right now it is only for the vars pool (not pools)

2023-07-13 16:53 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _save_variables_to_csv(self, data_dict: Dict[str, Any], path: str) -> None:
So it should be save dict to csv, not save vars to dict

2023-07-13 16:53 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                file.truncate(0)
why do you need to truncate the file here?

2023-07-13 16:53 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        # Determine the maximum length of values to account for uneven lengths
comments are bad, don't use them.

2023-07-13 16:53 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +                self._save_variables_to_csv(pool, file_path)
isn't this function's responsibility to generate names? why is it not doing it and instead calling save functions?

2023-07-13 16:53 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            If an error occurs while writting to the file
i don't see any exceptions being caught in this function.

2023-07-13 16:53 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def dump_variables(self, path: str, format: OutputFormat, exclude_info_maps: bool = False) -> None:
don't modify this function

2023-07-13 16:53 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            row = [d['values'][i] if i < len(d['values']) else None for d in values]
unreadable, add clarity

2023-07-13 16:53 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        # Determine the maximum length of values to account for uneven lengths
besides, how is it possible to have "uneven" lengths?

2023-07-13 16:53 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    class OutputFormat(Enum):
I don't think this is necessary.

2023-07-13 17:33 UTC, ltp23 commented on RUFAS/output_manager.py
> +        # Determine the maximum length of values to account for uneven lengths
I think uneven lengths in values lists happen when somewhere in the codebase the add_variables() only runs when certain local conditions are met.

2023-07-13 20:03 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +            If an error occurs while writting to the file
They weren't being caught because in the _dict_to_file_json they were being caught just to be thrown again without any additional computation done on the exception. Therefore, I did not wrap the IO operations in a try/catch block. I modified `_dict_to_file_csv` resemble the existing `_dict_to_file_json` method to add clarity as to where the exception may occur.

2023-07-13 20:05 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +                self._save_variables_to_csv(pool, file_path)
The `dump_variables` method needs to create a unique file name for the json and csv files and then write the variable pool to those files. the `_generate_file_name` method's responsibility is to generate the names.

2023-07-13 20:05 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        # Determine the maximum length of values to account for uneven lengths
removed with most recent commit.

2023-07-13 20:06 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +                file.truncate(0)
Removed with most recent commit. I had this originally for unit testing purposes, which is admittedly a poor reason to add this. It's been removed in the most recent commit and the unit tests now mock I/O operations.

2023-07-13 20:07 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +    def _save_variables_to_csv(self, data_dict: Dict[str, Any], path: str) -> None:
renamed to `_dict_to_file_csv`

2023-07-13 20:07 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        Enumeration that represents valid output encodings for OutputManger pools
Removed.

2023-07-13 20:09 UTC, michaelRichards99 commented on tests/test_misc.py
> +
That's a really good idea. I've removed all filesystem trips by mocking `open()` in this unit test.

I've used pytests `parametrization` feature to reuse the function and add more data concisely.

2023-07-13 20:10 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +            writer.writerows(rows)
Using pandas is much more concise and much more readable. I've removed the csv library and am using your suggestion to generate the csv file from the dictionary.

2023-07-13 20:10 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +            return
done.

2023-07-13 21:03 UTC, PooyaHekmati requested changes

2023-07-13 21:03 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        Dumps variables_pool into a json file and a csv file in the given path to a directory.
As I mentioned in my comment in the last review, you shouldn't be saving just a single CSV file. I think that is why you were concerned about varying lengths. Instead, for each entry in the vars pool, create a CSV file. Since we are assuming data types are primitive (or flattened using `str()`) you will end up with multiple CSV files each having a single column (it would be nice to add an id column if possible). Also, `dump_variables` should not be modified. Instead, create a function and call it, we will later expand it.

2023-07-13 21:30 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        Dumps variables_pool into a json file and a csv file in the given path to a directory.
I forgot the comment containing all code change requests can itself contain code change requests. I'll create a csv file for each variable in the vars pool and will keep `dump_variables` unmodified, extracting csv generation to its own method.

2023-07-13 22:32 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        Dumps variables_pool into a json file and a csv file in the given path to a directory.
Thanks :)

2023-07-14 00:01 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        Dumps variables_pool into a json file and a csv file in the given path to a directory.
I've added the functionality to create 1 csv per variable in the variables pool. 

I wasn't sure where to place the creation of the directory where these csv files go. Looks like currently both the `SimulationEngine` and `OutputHandler` [create directories](https://github.com/RuminantFarmSystems/MASM/blob/2af2ab10da382dbffb7434f38060740cd8fef121/RUFAS/simulation_engine.py#L181C13-L181C13)in the `output` directory, but the `OutputManager` doesn't create anything on its own. Do you think this logic could be consolidated into the `OutputManager`'s constructor?

2023-07-14 00:01 UTC, ltp23 commented
Thank you, Pooya, for the clarifications. I misunderstood our objectives initially. I now understand that we want to save each variable in a separate CSV file, and this should happen right after the simulation ends, not later. I've updated the git issue description to reflect these points. Sorry Michael for the rework.

2023-07-17 18:42 UTC, PooyaHekmati requested changes

2023-07-17 18:42 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        """Saves a variable and its values to a csv file.
what does `variable and its values` mean? How can a variable have values? Why not explicitly stating `saves a dict to a csv file`?

2023-07-17 18:42 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            The variable dictionary to be saved
```suggestion
            The dictionary to be saved
```

2023-07-17 18:42 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        if len(data_dict) != 1 or all("values" not in v for v in data_dict.values()):
why `len(data_dict) != 1`? What is the reason and significance of 1?

2023-07-17 18:42 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        variables_csv_path = Path(path) / "CSVs" / "om" / "variables"
avoid hardcoding values. Assume the whole path (except for the file name) is being passed to the function.

2023-07-17 18:42 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            self._dict_to_file_csv({key: value}, csv_file_path)
I think this is more efficient.
```suggestion
        for key in pool.keys():
            csv_file_path = os.path.join(variables_csv_path, self._generate_file_name(key, "csv"))
            self._dict_to_file_csv(pool[key], csv_file_path)
```

2023-07-17 18:42 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def dump_variables_to_csv_files(self, path: str) -> None:
I agree that this function is dumping right now, but in future PRs it will change to saving. I leave it to you to decide if you want to want to keep its current name and rename it later or if you want to call it save in this PR.

2023-07-17 19:07 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        variables_csv_path = Path(path) / "CSVs" / "om" / "variables"
This goes back to [this comment](https://github.com/RuminantFarmSystems/MASM/pull/650#discussion_r1263150030) I left on your previous review. The OM does not create the output directories, the output handler does. I'll create a helper method for this for now.

2023-07-17 19:36 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        """Saves a variable and its values to a csv file.
Since we were only saving the variables pool and are making sure each dictionary has the `values`, I used this name to signify that it was saving any python dicitonary but a dictionary from the variable pool.

I've renamed it to _dict_to_file_csv

2023-07-17 19:37 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        if len(data_dict) != 1 or all("values" not in v for v in data_dict.values()):
This was to ensure only 1 variable was being saved. Since this is renamed to `_dict_to_file_csv`, it no longer makes sense for this check to be here.

2023-07-17 19:38 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +            self._dict_to_file_csv({key: value}, csv_file_path)
done.

2023-07-17 19:38 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +    def dump_variables_to_csv_files(self, path: str) -> None:
done. I've updated the name to use save.

2023-07-18 16:58 UTC, ew3361zh requested changes
I think this looks good. Nice work! 

I had some questions about the function names that look like they were already addressed in previous reviews/conversations.

I do a have a few requested changes on flake8 violations:
- 2 blank lines between test functions on both sides
- whitespace after commas in lists [1,2,3] -> [1, 2, 3]
- remove unused import statements

<img width="678" alt="Screenshot 2023-07-18 at 12 59 53 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/7dcec2d6-04c1-44bd-b5e4-dea21048cb4d">

2023-07-18 16:58 UTC, ew3361zh commented on tests/test_misc.py
> +    om = OutputManager()
I think it would fix some of the singleton testing issues you were running into if you used the mock_output_manager fixture similar to other OM test functions rather than instantiating OM anew here.

2023-07-18 16:58 UTC, ew3361zh commented on tests/test_misc.py
> +def test_save_variables_to_csv_files(
Add extra blank line before and after test funs (gets a flake8 violation without two spaces between test funs)

2023-07-18 16:58 UTC, ew3361zh commented on tests/test_misc.py
> +from pathlib import Path
showing up as "imported but unused."

2023-07-18 16:58 UTC, ew3361zh commented on tests/test_misc.py
> +from mock.mock import MagicMock, call
Also showing up as imported but unused. The only reference is showing up in the test_dict_to_csv but as flake8 violation of redefining call from this import.

2023-07-18 17:41 UTC, michaelRichards99 commented
Thanks for bringing the Flake8 errors to my attention. I'll add this check to my commits to ensure that I am not adding more formatting errors to the code base from now on.

2023-07-18 17:52 UTC, ew3361zh approved these changes
Excellent, LGTM

2023-07-18 20:56 UTC, PooyaHekmati approved these changes

2023-07-18 21:12 UTC, merged