Im refactor
RuminantFarmSystems/RuFaS pull request #660
Opened 2023-07-15 20:12 UTC by ew3361zh

This PR tries to address issue #617 to create a new function validate_element() in the IM that will validate each input data element based on the metadata guidelines.

To achieve this, the PR:

1. Creates a `start_data_processing()` method to organize metadata and input data processing. This method will eventually be called from and return a boolean to `main()`. I thought it was helpful here to see the IM processing pipeline laid out and have laid out a proposal for how IM will be incorporated into `main.py` in issue #679.
2. Switches to using the metadata as the guideline to looping through what data to validate.  
3. To accomodate input data only being added to the IM pool after it has been validated, `validate_data()` is the second function to be called after `_load_metadata()` in the `start_data_processing()` pipeline. `validate_data()` loops through the file paths outlined by the metadata and opens and loads those files one at a time to a temporary data buffer dictionary which is used to validate and fix the data from each input file. Once the data has been validated and/or fixed, it will be added to the IM pool. 
4. Creates `validate_element()` method to recursively check each element expected to be in the input data file based on metadata guidelines which calls `fix_data()` to attempt to fix any invalid data found. 
5. Creates 3 separate functions (`_validate_string_type_element()`, `_validate_array_type_element()`, and `_validate_number_type_element()`) to validate by data type based on metadata guidelines.
6. Updates unit testing.

Notes:
-`get_data()` and `_fix_data()` are being added in PRs #675 and #646 respectively.
- `main()` was not updated with any expected behavior based on results of the new `start_data_processing()` function. That felt like a separate PR and something to do once we've got a validatable metadata in place.

2023-07-18 19:54 UTC, Isgotkowitz requested changes
Good start on the data validation Niko. Requested changes on the three validation methods for arrays, numbers, and strings - there is an edge case that breaks them. Also some suggestions on small stuff mostly type annotations

2023-07-18 19:54 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +    def start_data_processing(self, metadata_path,
```suggestion
    def start_data_processing(self, metadata_path: str,
```

2023-07-18 19:54 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        eager_termination : bool, optional, default=True
```suggestion
        eager_termination : bool, default=True
```

2023-07-18 19:54 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +    def _load_metadata(self, metadata_path) -> None:
```suggestion
    def _load_metadata(self, metadata_path: str) -> None:
```

2023-07-18 19:54 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        return True
```suggestion
        minimum_value = variable_to_check.get("minimum")
        maximum_value = variable_to_check.get("maximum")
        is_in_range = True
        if minimum_value is not None and maximum_value is not None:
            is_in_range = minimum_value <= input_data_value <= maximum_value
            warning_string = f"Value not in range [{minimum_value}, {maximum_value}]."
        elif minimum_value is not None:
            is_in_range = minimum_value <= input_data_value
            warning_string = f"Value less than {minimum_value}."
        elif maximum_value is not None:
            is_in_range = input_data_value <= maximum_value
            warning_string = f"Value greater than {maximum_value}."
            
        if not is_in_range:
            om.add_warning(warning_string, f"{var_name=}", info_map)
            
        return is_in_range
```
I think adding the values checked against to the warning would make them a little bit more helpful. Also there is a lot of repeated repeated calls to the OutputManager and `variable_to_check`, by reducing their numbers I think the code becomes more readable.

2023-07-18 19:54 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        if is_minimum_check and is_maximum_check:
This breaks if either "minimum" or "maximum" is 0, because 0 and None both evaluate to False.

2023-07-18 19:54 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                return is_valid_string
Same comments here as `_validate_num_type_element()`

2023-07-18 19:54 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                return is_in_range
Same comments here as `_validate_num_type_element()`

2023-07-18 19:54 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            module_properties = self.__metadata["properties"][property_map_key]
Should either of these get wrapped to in `try except` blocks for `KeyErrors`?

2023-07-18 20:17 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            module_properties = self.__metadata["properties"][property_map_key]
It's a good question - I don't think so... 

The module_keys in the `__pool` will be set from `_load_data` method where it loops through the keys of metadata['files'] (config, animal, crop, etc) and sets those as the key for the `__pool` data loaded from the file. 

Only keys present in the `metadata['files'].keys()` will be set as `module_keys` for the `__pool` so it should be expected we'd find them again in the metadata as we loop through to get the nested properties keyword.

Let me know if you agree or if I'm missing something.

2023-07-18 20:31 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        return True
Good call.

2023-07-18 20:45 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        if is_minimum_check and is_maximum_check:
I remember that crossing my mind at some point and forgot to come back to it. Nice catch!

2023-07-18 20:56 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        eager_termination : bool, optional, default=True
This was interestingly generated by my autoDocstring vs code plug-in which I finally updated to numpy style. I checked out the numpy docstring documentation and it says: "If the default value would not be used as a value, optional is preferred." So I think getting rid of it is correct here.

2023-07-18 20:56 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                return is_valid_string
updated

2023-07-19 13:12 UTC, PooyaHekmati requested changes
The implemented logic is wrong. As we discussed on July 13th, we add an element to the pool after checking its validity and trying to fix it if it was invalid. Please use the code that I wrote and shared with you that day on Slack (new 12.py) as the guideline for the logic.
This implementation has gone well beyond its expected delivery date. Please make sure it is implemented, reviewed, and merged by EOW.

2023-07-19 13:12 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        Organize metadata and input data processing pipeline.
```suggestion
        Starts the pipeline for organizing metadata and input data processing.
```

2023-07-19 13:12 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            If true, the process will be terminated upon finding invalid data.
```suggestion
        eager_termination : bool, default=True
            If True, the process will be terminated as soon as finding invalid data and failing to fix it.
            If False, the process will be terminated after going through and validating the entire data.
```

2023-07-19 13:12 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            Flag indicating whether input data is valid.
```suggestion
            True if data is valid, otherwise False.
```

2023-07-19 17:23 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            module_properties = self.__metadata["properties"][property_map_key]
Ok, that sounds good to me. And even if there were `try except` blocks added, it seems like there wouldn't be anything better to do than create a slightly more detailed error message and raise an error anyways

2023-07-20 05:04 UTC, allisterakun requested changes

2023-07-20 05:04 UTC, allisterakun commented on RUFAS/input_manager.py
> +                total_elements_counter += 1
I think this counter is inaccurate: it only keeps track of the top-level elements; it does not account for all the nested variables.

I am unsure if this is the intention, but instead of counting the top module elements, would it make more sense to keep track of the status (total/valid/invalid) of all the variables?

2023-07-20 05:04 UTC, allisterakun commented on RUFAS/input_manager.py
> +                total_elements_counter += 1
The same goes for the other counters: `valid_elements_counter` and `invalid_critical_elements_counter`:
    One invalid variable would make the entire module invalid, and there may be more than one invalid variables in the same module.

2023-07-20 05:04 UTC, allisterakun commented on RUFAS/input_manager.py
> +                whole_key = f"{element}.{nested_key}"
Why do we need to pass the variable path as a string? Can we simply pass the `element_hierarchy` list?

2023-07-20 05:04 UTC, allisterakun commented on RUFAS/input_manager.py
> +                child_status = self._validate_element(self, whole_key, property_map_key, eager_termination)
The inputs here are incorrect. You are missing the `module_key` and `input_data`
Your input                             |    Expected
`self: InputManager`            => `module_key: str`
`whole_key: str`                    => `element: str` (which is the variable path)
`property_map_key: str`       => `property_map_key: str`
`eager_termination: bool`    => `input_data: Dict[str, Any]`
None                                    => `eager_termination: bool = True`

2023-07-20 05:04 UTC, allisterakun commented on RUFAS/input_manager.py
> +        variable_to_check = reduce(lambda d, key: d[key], element_hierarchy,
Maybe rename it to `"variable_properties"`?

2023-07-20 05:04 UTC, allisterakun commented on RUFAS/input_manager.py
> +                                   input_data_value: int) -> bool:
Maybe change the `input_data_value` type to float to handle decimal data?

2023-07-20 05:04 UTC, allisterakun commented on RUFAS/input_manager.py
> +                is_fixed = self._fix_data(module_key, element_hierarchy)
`(module_key, property_map_key, element_hierarchy, input_data)`

2023-07-20 05:04 UTC, allisterakun commented on RUFAS/input_manager.py
> +        """Validates a __pool element of type array."""
Technically, the element/variable is not yet in self.__pool

2023-07-20 05:04 UTC, allisterakun commented on RUFAS/input_manager.py
> +            if not is_valid_string:
I think you can do the warning altogether at the end and use `&=` for the length checks to update `is_valid_string`. So the code would be something like this:
```
        info_map = {"class": self.__class__.__name__,
                    "function": self._validate_string_type_element.__name__,
                    }
        pattern_check = variable_to_check.get("pattern")
        is_valid_string = True
        warning_string = ""
        if pattern_check is not None:
            is_valid_string = bool(re.match(pattern_check, input_data_value))
            warning_string += f"String variable must match pattern {variable_to_check['pattern']}. "

        minimum_length = variable_to_check.get("minimum_length")
        maximum_length = variable_to_check.get("maximum_length")
        if minimum_length is not None and maximum_length is not None:
            is_valid_string &= variable_to_check["minimum_length"] <= len(input_data_value) <= \
                variable_to_check["maximum_length"]
            warning_string += f"String out length range [{minimum_length}, {maximum_length}]."
        elif minimum_length is not None:
            is_valid_string &= variable_to_check["minimum_length"] <= len(input_data_value)
            warning_string += f"String length less than {minimum_length}."
        elif maximum_length is not None:
            is_valid_string &= len(input_data_value) <= variable_to_check["maximum_length"]
            warning_string += f"String length more than {maximum_length}."

        if not is_valid_string:
            om.add_warning(warning_string, f"{var_name=}", info_map)

        return is_valid_string
```

2023-07-20 12:03 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                whole_key = f"{element}.{nested_key}"
I think we need the new nested key at each level down in the hierarchy.

Say the metadata is {'animal_properties': {'herd_data': {'type': 'object', 'calf_num': {'type': 'number', 'minimum': 2}, 'cow_num': {'type': etc...

So the first time the element may just be 'herd_data' so the element_hierarchy will just be that element. This is an object type so it will trigger the recursive loop.
The first time through that loop the whole_key will now be {'herd_data'}.{'calf_num'} and it will be sent as the new element to the recursive call to 'validate_element'.
The second time through that loop the whole_key will now be {'herd_data'}.{'cow_num'} and so each time the element_hierarchy changes.

Maybe I'm missing your point here but I think it is set up correctly as is. I'm not sure we'd know which nested element we're on otherwise.

2023-07-20 12:07 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                child_status = self._validate_element(self, whole_key, property_map_key, eager_termination)
Good catch, thank you. Updating that and will push with other changes.

2023-07-20 12:14 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        """Validates a __pool element of type array."""
Good catch! Updating.

2023-07-20 12:39 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            if not is_valid_string:
I like this. I think the initial idea was to break out of this validation as soon as the first violation is found but maybe because there are multiple possible combinations of violations, it would be helpful to get all the warnings at once so the user isn't rerunning the code after fixing the pattern violation just to get back a length violation.

However, I think the value returned by each individual check would need to inform whether we're adding the warning string which I think would create different booleans we'd need to check and then do a more cumbersome check at the end of whether any of the checks is False.

The other possibility Pooya and I talked about was writing the length min and max into the regex pattern but I think he didn't like that idea in the end so I'm going to keep things as is for now. There's a good idea in here though.

2023-07-20 13:07 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                total_elements_counter += 1
Definitely. Do you have any thoughts on how to get the actual nested numbers? I tried within the validate_element function but it became complicated to bring that back to validate_data and I don't know that we want to create global variables for the counters. I can rename these for now and maybe create an issue to try to find a way to accurately get the statuses of all the nested elements. I think it's still useful to get the top level object validity statuses and report those to OM.

2023-07-20 13:25 UTC, allisterakun commented on RUFAS/input_manager.py
> +                whole_key = f"{element}.{nested_key}"
Right, I understand the current logic. My question is: if we need to parse the `variable_path: str` into a list of strings `element_hierarchy: List[str]` eventually, why don't we just pass the List[str] instead?

So it would take in `_validate_element(...args, element_hierarchy: List[str], ...args)`. In that case, the first time `["herd_data"]`, and it triggers the recursive loop: it calls itself with  `["herd_data", "calf_num"]` and `["herd_data", "cow_num"]`, respectively.

By doing that, we can skip unnecessary string parsing and string manipulation for each iteration of the recursive loop.

2023-07-20 13:53 UTC, allisterakun commented on RUFAS/input_manager.py
> +                total_elements_counter += 1
Right, I have some ideas for the actual nested counter beside the global counter. Since we are using a buffer dictionary `input_data`, we can set up a `["metrics"/"counters"]` attribute (needs a better name) in the parent function `_validate_data`, and have all the children functions update this field correspondingly.

So in `_validate_data()`, you would do something like `input_data["metrics"] = {"total_element": 0, "valid_element": 0, "invalid_element": 0}`. 

Not sure if this would be something we can do.

2023-07-20 14:40 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                total_elements_counter += 1
I have added this possible solution to the issue #677.

2023-07-20 15:11 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                whole_key = f"{element}.{nested_key}"
Implemented.

2023-07-20 15:14 UTC, allisterakun requested changes

2023-07-20 15:14 UTC, allisterakun commented on RUFAS/input_manager.py
> +                element_hierarchy.append(nested_key)
After appending to the list `element_hierarchy`, you should pop the last element at the end of the for loop.

2023-07-20 15:26 UTC, allisterakun approved these changes

2023-07-20 16:02 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +            If False, the process will be terminated after going through and validating the entire data.
```suggestion
            If False, the process will be terminated after going through and validating the entire data, if invalid data is found.
```

2023-07-20 16:02 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +            return True
```suggestion
            return invalid_critical_items_counter == 0
```

2023-07-20 16:02 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +        element : str
```suggestion
        element_hierarchy : List[str]
```

2023-07-20 16:02 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +        eager_termination : bool, default=True
```suggestion
        eager_termination : bool
```

2023-07-20 16:02 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +                raise Exception("Element must be type number, array, string, or bool")
```suggestion
                raise Exception(f"Invalid type {var_type}: Element must be type number, array, string, or bool")
```
I think more information about the exception would be useful.

2023-07-20 17:51 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                raise Exception("Element must be type number, array, string, or bool")
Agreed.

2023-07-20 21:04 UTC, michaelRichards99 requested changes
Hi Niko. This looks great to me, good job!

I have 1 more requested change.

2023-07-20 21:04 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +            is_valid = type_validation_dict.get(var_type)
Instantiating this dictionary will result in all 3 validation methods being called on the variable, which is only 1 of the 3 types. 
```suggestion
match var_type:
    case "string": 
        is_valid = self._validate_string_type_element(variable_properties, var_name, input_data_value)
      case "number":
          is_valid = self._validate_num_type_element(variable_properties, var_name, input_data_value)
      case "array":
           is_valid = self._validate_array_type_element(variable_properties, var_name, input_data_value)
    case "bool":
        is_valid = True
```

2023-07-20 21:07 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +            is_valid = type_validation_dict.get(var_type)
A catch-all case `case _:` can also be added after all other cases and can raise an `error` for even more validation.

2023-07-20 21:37 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            is_valid = type_validation_dict.get(var_type)
Thanks, Michael, nice catch! I added your suggested change as well as a catch-all for the final case if the var_type doesn't match any of the given cases.

2023-07-20 21:48 UTC, michaelRichards99 approved these changes

2023-07-21 14:40 UTC, PooyaHekmati requested changes

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +    def _validate_data(self, eager_termination: bool) -> bool:
As discussed on July 13th, this function is now doing more than validation and needs an appropriate name.

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        total_items_counter = 0
why is `fixed_elements_counter` removed? It is helpful to have it.

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        for module_key, details in self.__metadata["files"].items():
`module_key` is not the correct name. The file blobs don't necessarily map to modules. `file_blob_key` is probably a better name.
Also `details` is not specific enough. Details of what? use `file_details` or `file_description`.

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                continue
As discussed on July 17th, avoid using `elif` structure for routing the flow to functions. 
```suggestion
            data_type_to_loadder_map = {
                "json": self._load_data_from_json(file_path),
                 "csv": self._load_data_from_csv(file_path),
            }
            try:
                data_type_to_loadder_map.get(details["type"])
            except:
               raise KeyException(f"Faulty data type in {module_key}, only CSV and JSON are supported."}
```

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            property_map_key = details["properties"]
`property_map_key` is misleading. We don't have a mapping here. Use `associated_properties` or `corresponding_properties` or `properties_blob_key`.

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            module_properties = self.__metadata["properties"][property_map_key]
Same as above, `module_properties` is not correct. Use `properties` or `blueprint`.

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            for element in module_properties.keys():
nit. when iterating through an iterable with plural name, individual items in it are singular:
```suggestion
            for property in module_properties.keys():
```

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                    return False
```suggestion
                if is_valid_element:
                    valid_items_counter += 1
                    self.__pool[module_key] = data
                else:
                    if not eager_termination:                        
                        invalid_items_counter +=1
                     else:
                        return False
                        
```

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
>                  else:
```suggestion
```

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                self.__pool[module_key] = data
```suggestion
```

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +    def _validate_element(self, module_key: str, element_hierarchy: List[str],
why this function needs module_key? At this point, we have read the file and we are done with it. All we need is the property's entry.

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            match var_type:
use dict instead. (discussed on July 17th)

2023-07-21 14:40 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        if maximum_length is not None and minimum_length is not None:
don't mix different constraints in the same if statement (discussed on July 17th)

2023-07-21 14:58 UTC, ew3361zh commented on RUFAS/input_manager.py
> +    def _validate_data(self, eager_termination: bool) -> bool:
How about `_validate_data_and_add_to_pool()`. Please let me know if you have any other suggestions.

2023-07-21 15:06 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        total_items_counter = 0
The elements `_validate_data()` sends to `_validate_element()` are potentially nested dictionaries and with the fixing happening in `_validate_element()`, it became too complicated to try and track and report back the individual data fixing numbers to `_validate_data()`. I've documented this in issue #677.

2023-07-21 15:07 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +            match var_type:
The expressions in python dictionaries are not lazily evaluated, so all the values in the dictionary are created when the dictionary is instantiated.

In this case, it will result in all 3 of the _validate... methods being called on the data. This could pollute the OM's logs if one of these causes an error.

We could write a [custom dictionary implementation](https://stackoverflow.com/questions/16669367/setup-dictionary-lazily) that decouples the method from the data, and executes the method when `__getitem__` is called or use a control flow construct.

2023-07-21 15:11 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        for module_key, details in self.__metadata["files"].items():
Updated.

2023-07-21 15:17 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                continue
In conversations and testing with @michaelRichards99, instantiating a dictionary with multiple function calls as values will cause all functions to be called at instantiation (in this case with the `file_path` argument). This will lead to a number of unintended consequences so this isn't a good approach.
![image (1)](https://github.com/RuminantFarmSystems/MASM/assets/70217952/0d03a5d7-7a0a-49eb-b648-270fd07bf86c)
![image (2)](https://github.com/RuminantFarmSystems/MASM/assets/70217952/dc3a78a0-8800-47ce-902b-19cf1982c738)

2023-07-21 15:19 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            property_map_key = details["properties"]
Updated to properties_blob_key.

2023-07-21 15:21 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            module_properties = self.__metadata["properties"][property_map_key]
Updated to properties.

2023-07-21 15:22 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            for element in module_properties.keys():
Updated.

2023-07-21 15:28 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                    return False
This would add the full input data loaded from the file to the pool each time through the loop which could be a number of times. I think the it's better to wait until we've completed the full inner `for property in properties.keys():` loop to then add the data (if we haven't gotten back any invalid elements).

2023-07-21 15:43 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                continue
simply move the arg from lines 162 and 163 to line 166.
Running 
```
print("Start")
class foo():
    def __init__(self):
        print("init, creating func mapping dict")
        d={
            "bar1": self.bar1,
            "bar2": self.bar2,
            "bar3": self.bar3,
            "bar4": self.bar4,
        }
        print("dict is created")
        x=1
        for k,v in d.items():
            if k=="bar2":
                continue
            print(f"calling {k}")
            v(x)
            x+=1
    def bar1(self, x):
        print(f"bar1 {x=}")
    def bar2(self, x):
        print(f"bar2 {x=}")
    def bar3(self, x):
        print(f"bar3 {x=}")
    def bar4(self, x):
        print(f"bar4 {x=}")
print("creating foo object")
f=foo()
```
Generates
```
Start
creating foo object
init, creating func mapping dict
dict is created
calling bar1
bar1 x=1
calling bar3
bar3 x=2
calling bar4
bar4 x=3
```
As you see, bar2 is not called.
CC @michaelRichards99

2023-07-21 15:59 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +                continue
That works cleanly in this instance because the function's arity is the same.

It does become more difficult for variadic functions as is the case for the 2nd instance of this in this PR. In that case, the types `string`, `array`, and `number` all have functions with 3 parameters and the `bool` type needs a function that always returns true. @ew3361zh An additional `self._validate_bool_type_element(variable_properties, var_name, input_data_value)` that always returns `True` would remove this complexity and then the dictionary that stores function pointers works as planned.

2023-07-21 16:06 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                continue
Can you write a piece of code that shows your point?

2023-07-21 16:19 UTC, michaelRichards99 commented on RUFAS/input_manager.py
> +                continue
We had the following dictionary. (I've taken out the parameters so it doesn't call the functions and replaced True with bool().
```
func_map = {
    "string": self._validate_string_type_element,
    "number": self._validate_num_type_element,
    "array": self._validate_array_type_element,
    "bool": bool
}
```
bool() takes 1 arg while the others have 3 (variable_properties, var_name, input_data_value). when you get the function with `func_map(var_type)`, you'd need to check if the type was a `bool` so you can pass the proper arguments to avoid a TypeError.

Instead of special-casing the `bool` type, we could introduce `self._validate_bool_type_element(variable_properties, var_name, input_data_value)` which removes the complexity.

2023-07-21 16:26 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                continue
Yes, bool can have a function. It will do nothing right now but allows adding validation for bool down the road.

2023-07-21 17:27 UTC, ew3361zh commented on RUFAS/input_manager.py
> +    def _validate_element(self, module_key: str, element_hierarchy: List[str],
Good catch. I think we had it here because we mistakenly thought fix_data() needed it but @allisterakun have resolved this and will make the adjustments here and in the fix_data() branch.

2023-07-21 19:19 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                continue
Updated.

2023-07-21 19:51 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        if maximum_length is not None and minimum_length is not None:
Addressed.

2023-07-21 19:51 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            match var_type:
Addressed as well. Dicionary method implemented.

2023-07-21 19:52 UTC, ew3361zh commented on RUFAS/input_manager.py
>                  else:
Implemented.

2023-07-21 19:52 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                    return False
I have implemented this as requested.

2023-07-21 19:53 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                self.__pool[module_key] = data
Removed from code as requested.

2023-07-22 18:48 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        total_items_counter = 0
I have addressed this now and it will report the total items checked, total invalid items, total valid items, and total fixed items.

2023-07-23 01:19 UTC, PooyaHekmati approved these changes
Please address comments before merging.

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        Validates data from input files and adds data to pool if valid.
I don't think this statement is accurate. It first loads the files, then runs the validations, for invalid ones it attempts to fix them, then adds them to the pool.
Also `_populate_pool` is probably a better name for this function.

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                                       "csv": self._load_data_from_csv}
Doesn't need to be in the for-loop.
```suggestion
        data_type_to_loader_map = {"json": self._load_data_from_json,
                                   "csv": self._load_data_from_csv}
        for file_blob_key, file_details in self.__metadata["files"].items():
            file_path = file_details["path"]
```

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                raise KeyError(f"Faulty data type in {file_blob_key}, only CSV and JSON are supported.")
I know I wrote this error message in an earlier comment, but now with the additional context I think this is better. So later on when we want to add new types we just need to implement its function and add its handle to the dict.
```suggestion
                raise KeyError(f"Faulty data type in {file_blob_key}, supported types are: {data_type_to_loader_map.keys()}.")
```

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                is_valid_element = self._validate_element([property], properties_blob_key, data,
not a biggie, but `is_element_valid` sounds better.

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                                                          eager_termination, counter_dict)
If I'm understanding correctly, `counter_dict` is being passed so it can be used to retrieve the values. This is a bad practice. It is so bad that a whole language (Rust) is developed around the ownership and borrowing concepts to prevent something like this. Instead, instantiate a dictionary or named tuple (both are fine for this use case, choose whichever you think fits better), add all the counters and the bool flag that is currently used in line 174 to it. So instead of returning a bool, `self._validate_element()` now returns a package (a complex data structure either dict or named tuple).
There are two reasons why this is bad practice: 
1. Memory management, two actors are sharing the same resource when they don't have to. 
2. Readability and clean code: When someone sees the signature of a function, the args are what the function needs to be able to do its job. In here, element validation is not dependent on having the counters.

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
>          Perform data validation checks.
can we add more details here?

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                element_hierarchy.append(nested_key)
I'm happy to see how you guys are working together :)

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                child_status = self._validate_element(element_hierarchy, properties_blob_key,
[![Recursion](https://i0.wp.com/miro.medium.com/max/640/1*__jhoWXEa_INM44V5jx30w.jpeg?resize=831%2C592&ssl=1)](https://i0.wp.com/miro.medium.com/max/640/1*__jhoWXEa_INM44V5jx30w.jpeg?resize=831%2C592&ssl=1)

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                                                      input_data, eager_termination)
Don't we need to pass `counter_dict`?

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                if eager_termination and not child_status:
rename it in line 234 as well
```suggestion
                if eager_termination and not is_child_valid:
```

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                invalid_child_vars = [key for key, value in children_status.items() if value is False]
If we keep track of these right after line 239 then we don't need to scan the children_status again to find them. i.e. we can trade time complexity for space complexity, which I think is worth it.

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                raise KeyError(f"Invalid type {var_type}: Element must be type number, array, string, or bool")
1. Adding dict at the end of a name doesn't provide more info, we can see that we have dict here. That's why we generally choose names based on functionality and behavior. In this case, we have a map because we are mapping one domain to another.
2. `validator` is shorter than `validity_checker`. It is also used in other codebases as well. [See this](https://en.wikipedia.org/wiki/Validator)
3. Let's be programmatic in the error message to reduce the needed maintenance down the road.
4. The function call doesn't need to be in the try block.

```suggestion
            data_type_to_validator_map = {"string": self._validate_string_type_element,
                                    "number": self._validate_num_type_element,
                                    "array": self._validate_array_type_element,
                                    "bool": self._validate_bool_type_element, }
            try:
                validator = data_type_to_validator_map [var_type]
            except KeyError:
                raise KeyError(f"Invalid type {var_type}: Element must be type {data_type_to_validator_map.keys()}")
            is_valid = validator (variable_properties, var_name, input_data_value)
```

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        return is_in_range
The same applies to other validation functions as well. There is no reason to obfuscate the behavior by `is_in_range`. Explanatory variables should not be used in the logic.
```suggestion
        if minimum_length is not None:
            is_in_range = variable_properties["minimum_length"] <= len(input_data_value)
            if not is_in_range:
                warning_string = f"Array length less than {minimum_length}."
                om.add_warning(warning_string, f"{var_name=}", info_map)
                return False
        if maximum_length is not None:
            is_in_range = len(input_data_value) <= variable_properties["maximum_length"]
            if not is_in_range:
                warning_string = f"Array length more than {maximum_length}."
                om.add_warning(warning_string, f"{var_name=}", info_map)
                return False

        return True
```

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +    def _validate_array_type_element(self, variable_properties: Dict[str, Any], var_name: str,
what about?
```suggestion
    def _array_type_validator(self, variable_properties: Dict[str, Any], var_name: str,
```
and for other similar functions.

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                                   input_data_value: float) -> bool:
```suggestion
                                   input_data_value: union[int, float]) -> bool:
```

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +    def get_data(self, data_address: str) -> Optional[Any]:
I think type `Any` includes type `None` so `Optional` is unnecessary.

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        >>> InputManager.get_data('animal.herd.calf_num')
I don't think this example is correct. `get_data` is not a static function, so it can't be called without calling the constructor first.
```suggestion
        >>> IM=InputManager()
        >>> IM.get_data('animal.herd.calf_num')
```
or
```suggestion
        >>> InputManager().get_data('animal.herd.calf_num')
```

2023-07-23 01:19 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            om.add_warning("Data not found:", f"Cannot find \"{data_address}\", "
we are literally talking about an error here, so an error should be added to the pool, not a warning.

2023-07-24 11:23 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        Validates data from input files and adds data to pool if valid.
Updated docstrings and I like _populate_pool, thank you!

2023-07-24 11:26 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                                       "csv": self._load_data_from_csv}
moved outside for-loop.

2023-07-24 11:29 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                raise KeyError(f"Faulty data type in {file_blob_key}, only CSV and JSON are supported.")
I like it.

2023-07-24 11:39 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                if eager_termination and not child_status:
updated

2023-07-24 11:48 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                invalid_child_vars = [key for key, value in children_status.items() if value is False]
That makes sense. I realize we're essentially adding these to OM twice with what's already happening after 239 and here.

2023-07-24 11:52 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                raise KeyError(f"Invalid type {var_type}: Element must be type number, array, string, or bool")
updated, thank you.

2023-07-24 11:54 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        return is_in_range
Updated

2023-07-24 12:02 UTC, ew3361zh commented on RUFAS/input_manager.py
> +    def _validate_array_type_element(self, variable_properties: Dict[str, Any], var_name: str,
I like this!

2023-07-24 12:03 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                                   input_data_value: float) -> bool:
Updated

2023-07-24 12:04 UTC, ew3361zh commented on RUFAS/input_manager.py
> +    def get_data(self, data_address: str) -> Optional[Any]:
Updated.

2023-07-24 12:06 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        >>> InputManager.get_data('animal.herd.calf_num')
I think the first way will be more helpful.

2023-07-24 12:06 UTC, ew3361zh commented on RUFAS/input_manager.py
> +            om.add_warning("Data not found:", f"Cannot find \"{data_address}\", "
Updated

2023-07-24 12:29 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                                                      input_data, eager_termination)
Right! Will make sure the arguments sent and returned will be correct with the updates to where counter_dict is instantiated per your comments above.

2023-07-24 12:54 UTC, ew3361zh commented on RUFAS/input_manager.py
> +                                                          eager_termination, counter_dict)
Thank you for the explanation and background! I've updated to instantiate the dictionary in `_validate_element()` (with the 'is_valid' bool added) and return it to `_populate_pool()`

2023-07-24 14:12 UTC, PooyaHekmati commented
Bypassing branch protection as a change was requested by @Isgotkowitz , however, he is not available to re-review. His comments are addressed and the PR has got 3 approvals out of the needed 2.

2023-07-24 14:13 UTC, merged