Soil and crop metadata
RuminantFarmSystems/RuFaS pull request #665
Opened 2023-07-17 22:25 UTC by Isgotkowitz

This PR fills in the metadata for the crop, soil, field management, and field configurations. 

There is also an example of what a field configuration file would look like following the properties specified in the metadata, I thought it would be helpful to have it here so that it makes clear one of the notes I added at the bottom of issue #668.

Also, there are comments on the files pointing out specific ways the metadata might be improved.

2023-07-17 22:31 UTC, Isgotkowitz commented on input/example_metadata.json
> +        "description": "This represents a single soil layer.",
@ew3361zh @PooyaHekmati I am tagging you both to alert you to this situation. One of the inputs for soil is an array of objects, each object representing a soil layer. As you can see from the soil_layer_properties description, it is an involved and complex object, so some level of input validation would be ideal.

2023-07-17 22:36 UTC, Isgotkowitz commented on input/example_metadata.json
> +          "default": null
@ew3361zh @PooyaHekmati I am also curious if this would be an acceptable specification for within a property?

2023-07-17 22:54 UTC, PooyaHekmati commented on input/example_metadata.json
> +        "description": "This represents a single soil layer.",
Hi @Isgotkowitz , let's meet and talk about this.

2023-07-19 18:36 UTC, Isgotkowitz commented on input/example_ARL_field.json
> +  "field_management_specification": "field_management/ARL_field_management_1.json",
An alternative here would be to specify the name of the blob that contains the file with specification data, instead of specifying the file path.

2023-07-19 18:46 UTC, Isgotkowitz commented on input/example_metadata.json
> +       }
Currently, the field management properties contains 3 objects, one each for fertilizer, manure, and tillage applications. This could easily be flattened would just result in 3 blobs instead of one, which would not be a big deal to handle. Just let me know if you would like me to make this change.

Edit: I flattened these into 3 different properties.

2023-07-20 14:31 UTC, allisterakun commented on input/example_metadata.json
> +    "field_management": {
Just a question I had, you mentioned in #668 that we should "allow users to specify multiple fields to be simulated for a single simulation." I am wondering if each field needs its own `field_management` or if this applies to all fields.

2023-07-20 15:06 UTC, allisterakun approved these changes

2023-07-20 15:06 UTC, allisterakun commented on input/example_metadata.json
> +          "type": "object",
Should this be an array if you're listing all the available fertilizer mixes?

2023-07-27 14:46 UTC, Isgotkowitz commented on input/example_metadata.json
> +    "field_management": {
Good question. Both of the scenarios you have described are possible - two different fields may use the same field management, and they may use different field management specifications (same with crop and soil specifications). So when we get to using metadata files to actually run the simulation, there will sometimes be multiple blobs with the same properties that specify different files.

2023-07-27 14:50 UTC, Isgotkowitz commented on input/example_metadata.json
> +          "type": "object",
No, because each available fertilizer mix is specified as a key value pair, where the key is the name of the mix as a string and the value is another dictionary containing the keys `N`, `P`, and `K`, so the more appropriate structure for this is a dictionary.

2023-07-27 18:47 UTC, ew3361zh commented on input/example_metadata.json
> +          "default": null
I forgot to ask if this was addressed already - I do think because we're using json.load it should be able to work. Is it important to have null/None instead of 0.0 as a default?

2023-07-27 19:35 UTC, ew3361zh requested changes
I think this looks really good overall. I have a few concerns and questions I've added and want to make sure we're all on the same page as far as expectations for how this data will be processed by IM. In particular the paths to other files within the "field_properties" section.

2023-07-27 19:35 UTC, ew3361zh commented on input/example_ARL_field.json
> +}
Can you explain again what this is and how it relates to the metadata?

2023-07-27 19:35 UTC, ew3361zh commented on input/example_metadata.json
> +      "description": "Fertilizer is like butter, you can never have too much.",
these are all very funny.

2023-07-27 19:35 UTC, ew3361zh commented on input/example_metadata.json
> +        "default": {}
Right now we're not doing defaults for object types because we're only validating the data within the object. So this can probably be removed.

2023-07-27 19:35 UTC, ew3361zh commented on input/example_metadata.json
> +        "pattern": "^(BARE|RESIDUE_COVER|GRASSED)$",
I wondered what you thought about the capitalization here - right now this would turn back a false match on "residue_cover". We could try to make the pattern checker a little more flexible, or I guess in the DCA we could ensure that it's a drop-down menu/radio button that has this exact capitalization. Probably the latter is the preferred since we don't want to make the pattern checker too lenient.

2023-07-27 19:35 UTC, ew3361zh commented on input/example_metadata.json
> +        "pattern": "*.json$"
Sorry if I misunderstood in our meeting with Allister but can you explain this section again and why these aren't treated as other metadata files (i.e. what differentiates them from other files in the files section and what goal is putting them here trying to achieve)? Is the thought these paths would be validated by the Input Manager and then followed after they're validated and loaded into the input data?

2023-07-27 19:37 UTC, Isgotkowitz commented on input/example_metadata.json
> +          "default": null
I do not think it has been addressed. Is it important - yes, because there are some `post_init` functions which use internal methods to initialize variables, but only in cases when the user does not provide any value (as indicated by `None`).

2023-07-27 19:45 UTC, Isgotkowitz commented on input/example_ARL_field.json
> +}
So this `example_ARL_field.json` file is not related to the metadata - I wrote it up because the input system for the Crop and Soil module is changing very significantly with the incorporation of the metadata and `InputManager` and I wanted to give a tangible example of what the new field input files will look like; the field configuration files are totally novel so I thought it important to have their design looked at too. This example does not necessarily need to be merged into `master` though.

2023-07-27 19:50 UTC, Isgotkowitz commented on input/example_metadata.json
> +        "pattern": "^(BARE|RESIDUE_COVER|GRASSED)$",
I matched it to what is used internally in the Crop and Soil module (i.e., it will only accept those three values). However it would be easy to make these all lower case - if that is the best practice then I can do that.

2023-07-27 20:18 UTC, Isgotkowitz commented on input/example_metadata.json
> +        "pattern": "*.json$"
> why these aren't treated as other metadata files (i.e. what differentiates them from other files in the files section

The soil specification files are treated the same as other metadata files - but only when they are specified in the `files` section of the metadata. 

> what goal is putting them here trying to achieve)?

This `"soil_specification"` property is verifying and validating that a field configuration file has a reference to a soil profile. 

>  Is the thought these paths would be validated by the Input Manager and then followed after they're validated and loaded into the input data?

No. Only paths specified in the `path` of a blob will be loaded and validated. The pattern here is verifying that the path contained by a field configuration file is formatted correctly, but it does not load or open any files based on that. 

So the order of execution will be:
- The `InputManager` loads and validates every file specified in blobs in the `files` section of the metadata.
- The Crop and Soil module pulls the data for one field (at a time) from `InputManager`
- After getting the path to the configuration files associated with the field it is currently setting up, Crop and Soil module will pull the data from the `InputManager` that is associated with the blob that contains the same `path` as the one specified in data for the field that is being set up.

Note that if a field configuration file contains the path to a file that is not specified in any of the other blobs, the simulation should throw an error and terminate.

Another open question is how the Crop and Soil module will pull data from the `InputManager` based on the file that the data originated from - this is noted at the bottom of issue #668.

This was a pretty long-winded explanation and may not be very clear, so please let me know if you want/need to talk about it more.

2023-07-27 20:20 UTC, Isgotkowitz commented on input/example_metadata.json
> +        "default": {}
ACK'd

2023-07-27 20:22 UTC, Isgotkowitz commented on input/example_metadata.json
> +      "description": "Fertilizer is like butter, you can never have too much.",
Thanks:) I am trying to work up to Pooya's level of engineering humor.

2023-07-27 20:22 UTC, ew3361zh commented on input/example_metadata.json
> +        "pattern": "^(BARE|RESIDUE_COVER|GRASSED)$",
I think it's okay to keep as is. We can certainly account for it in the DCA. If someone wrote their own soil input file though and didn't capitalize it would return a warning and would sub in the default. I'm not sure how great the difference would be and what effects the user would see between these results and they could check the OM warnings log and see that the pattern for this element wasn't properly matched.

2023-07-27 20:25 UTC, ew3361zh commented on input/example_metadata.json
> +        "pattern": "*.json$"
I think this makes sense now and if I'm understanding it correctly, would work. Thank you for the longer explanation, it's helpful.

2023-07-27 20:34 UTC, ew3361zh commented on input/example_metadata.json
> +          "default": null
I think the issue I see here is our num type validator in IM validates the value as if it's a num. So if someone didn't enter a value and we sent this through the num_type_validator, it would crash. Same for if someone entered "six" for this field labeled as "type": number. I'm not sure the best way to address these types of differences - right now we're relying on the type being representative of the value being sent to the type validator. We could do a check on type or just a check for None but curious what you think.

2023-07-27 20:40 UTC, ew3361zh approved these changes
I think we may need to come back to this structure once we've settled on the best way to validate array element data (object and primitive types) and will need to figure out in IM how to address non-matching type data when the data type is labeled in a specific way. But that feels like an IM decision and not necessarily a metadata decision.

2023-07-27 21:35 UTC, Isgotkowitz commented on input/example_metadata.json
> +          "default": null
Maybe just add a rule that if a number is `None` it is acceptable? Or add a flag that indicates `None` is acceptable along with the min, max, and default, but that would necessitate a lot more change in `InputManager`

2023-07-27 21:46 UTC, Isgotkowitz commented on input/example_metadata.json
> +        "pattern": "^(BARE|RESIDUE_COVER|GRASSED)$",
It probably would not make a big difference, and since the cover type is dynamic the value the user provides is just an initial input. I will leave it as is for now.

2023-07-27 22:02 UTC, ew3361zh commented on input/example_metadata.json
> +          "default": null
I think we'd want to catch the cases where someone just left it blank and they want the default to be subbed in (and then the default could be None or any number as outlined in the metadata).

2023-07-28 14:46 UTC, Isgotkowitz commented on input/example_metadata.json
> +          "default": null
Catching blank values and subbing the default in sounds good - what about applying the same solution to the case when the user provides an incorrect type for a value? It would be a little clunky in this case for `InputManager` to see `null` in a number input, say that it's the wrong type, then replace it with the default `None`. But it would hopefully be pretty simple and could be applied pretty universally

2023-07-28 14:51 UTC, ew3361zh commented on input/example_metadata.json
> +          "default": null
The json.load() method we're using to read the data from the input json file will convert the json null to None so I believe we could handle a blank entry and the null in a json file in the same fashion.

2023-07-31 14:06 UTC, ew3361zh commented on input/example_metadata.json
> +        }
If I'm reading these correctly, the `default` in the `properties` section is for the array itself while the max/min/type are for the data in the array, is that right?

I'm curious what your thinking was here because it does raise an interesting question:

If the array's `maximum_length` or `minimum_length` guidelines were violated, we'd want the `default` empty array to be substituted in at that point to fix the data. But if the guidelines of the array's elements were violated (in this case if a Julian day number were supplied that were outside the 1-366 range), would we want to sub in the `default` empty array then as well?

2023-07-31 14:45 UTC, ew3361zh commented on input/example_metadata.json
> +        }
Are there default harvest Julian days you'd want subbed in? Or is that handled in the code if the crop receives a blank array?

2023-07-31 14:48 UTC, Isgotkowitz commented on input/example_metadata.json
> +        }
You raise a good point - this section is not well written. If the days are outside the range 1 - 366, there should be no default so the program should stop running. Will make that change now

2023-07-31 15:04 UTC, Isgotkowitz commented
@ew3361zh @allisterakun I wanted to let you know after talking with Pooya I changed the properties of field input files - instead of containing the path to the file with the soil, crop, etc specification, it contains the name of the blob that contains the associated specification data instead. This will not require any significant or structural changes in the metadata, and the implications for the `InputManager` are largely unchanged.

2023-07-31 19:34 UTC, merged