Dt mass balance
RuminantFarmSystems/RuFaS pull request #67
Opened 2020-06-26 13:42 UTC by wmaxdonovan

This branch implements a restructuring/reorganization of the output handler to minimize redundancy in the code by taking advantage of class hierarchy. Reports fall into a few categories outlined in the JSON file: pen reports, field reports, mass balance reports, a feed storage report, and a custom report. These reports are organized by the model object that they operate on / by a unique functionality (e.g. mass balance).
output_handler.py creates a pen report, a field report, a mass balance report, a feed storage report, and a custom report. Each of those report drivers have a base report class that inherits its methods from the base report superclass defined in base_report.py (e.g. BaseFieldReport is a BaseReport). Every sub-report then inherits its methods from the base report of the group which it is a part of (e.g. SoilReport is a BaseFieldReport is a BaseReport). All sub-reports are now grouped in the same file as their super-report. This allows us to minimize lines of code (in most cases, each report is now uniquely defined solely by the output in that specific report) and implement methods as needed for more or less sophisticated reports.
We also implemented a general format for conducting mass balance that preserves the water balance already being conducted, but allows us to perform mass balances on other components of the model. A mass balance report is special in that it requires 5 inputs labeled as such:

"year": the calendar year
"actual": the actual input mass of whatever variable the mass balance is being conducted on (e.g. precipitation for the water balance)
"calculated": the mass of the component that is calculated/tracked by the model
"difference": the discrepancy between actual and calculated (can be determined without definition in the output handler but definition here resolves arithmetic errors that result from rounding)
"delta": change in mass over time (daily for the daily report, annually for the annual report)

From there, the mass balance output handler interprets any remaining input as sub-divisions of "calculated" in order to provide the user with a graphic representation of the components of the variable on which mass balance is being conducted.

e.g. the water balance report defines runoff, erosion, evaporation, transpiration, and drainage as out-fluxes for precipitation and produces the following graphic:

![annual_water_balance_report](https://user-images.githubusercontent.com/43965615/85862705-beeea400-b787-11ea-840c-4748cb14277f.png)

The colors are randomly selected from a color-blind friendly pallet as necessary for the number of variables.

The following video is a basic walkthrough for using and understanding the output handler in its current iteration:
https://drive.google.com/file/d/1x-g0ULKeJ_YP_Ui1gsOH_-sEVomuSyOp/view?usp=sharing

One hot-button issue during development was the renaming of a few important files:

Inputs -> input
Outputs -> output
Sample_Farm_Outputs -> CSVs
diagnostics -> graphics
RUFAS/outputs -> output_handler

Input and output are mass nouns, meaning if they are countable, the plural form would be inputs/outputs, but if they are of an indeterminate quantity, the plural form would be input/output. As in: "the method takes 5 inputs" v. "I would love to hear whatever input you have on this topic". Sample_Farm_Outputs felt like a no-brainer to me, as well as (unfortunately) diagnostics, which was a vestige of a phrase Missy used once that she later recanted after Jacob and I had become too attached. output_handler is a more descriptive name that disambiguates from output/s. I also added a "save_directory" which is just an empty folder for you to move model output to so that it doesn't get overwritten by individual model runs. Anything in that folder should be safely deletable.

2020-06-29 20:45 UTC, militsasotirova commented on RUFAS/output_handler/output_handler.py
> +        # TODO: Would really love to generalize directory creation for nested reports
An idea for directory creation for nested reports is to have PenReport, MassBalanceReport, and FieldReport inherit from some NestedReport "base" class (that contains an empty/basic initialize_csv_dir() function which those three nested reports overwrite) and the OutputHandler would have two dictionaries of reports: nested_reports & non_nested_reports (or something along those lines). Then the for loop following this TODO would only iterate through the nested_reports and call their initialize_csv_dir() functions. I think this could also simplify the initialize_graphic_dir() function and allows for easier creation of other nested reports.

2020-06-29 20:49 UTC, wmaxdonovan commented on RUFAS/output_handler/output_handler.py
> +        # TODO: Would really love to generalize directory creation for nested reports
Yes! Great idea. Possibly not too hard to implement either... I will check it out.

2020-06-29 20:51 UTC, HectorMM3 requested changes

2020-06-29 20:51 UTC, HectorMM3 commented on RUFAS/routines/soil/nitrogen_cycling/nitrogen_cycling.py
> +    org_C = Organic carbon in a soil layer (%, user input)
Does this conflict with the definition of org_C directly below? In the json there is org_C% and OM%.

2020-06-29 21:25 UTC, wmaxdonovan commented on RUFAS/routines/soil/nitrogen_cycling/nitrogen_cycling.py
> +    org_C = Organic carbon in a soil layer (%, user input)
Yes! Good catch– it was doubly defined and the lower one was incorrect.

2020-06-30 16:38 UTC, HectorMM3 approved these changes
Max, I have re-run the mass balance today (06/30/2020). The csv and graphical output are working as expected. We still need to find the errors for N and P but we can change this later.

2020-06-30 18:13 UTC, militsasotirova approved these changes
Looks good to me! I like the simplification with the BaseReportDriver. Also, I’m currently working on adding a life cycle output and I appreciate how this structure makes it really easy to add reports.

2020-07-01 15:22 UTC, Jacob8399 reviewed
The branch looks good. The colors for the graphs aren't actually picked from a random colorblind palette, they are hardcoded and limited to five colors as that was the necessary amount for water balance. For mass balance graphs with more values, I think we should have a larger color palette possibly kept in the database and then pulled from based on the amount of values.

Michael and I both think that someone else should be consulted about the Inputs/Outputs/input/output disagreement, probably Hector or Kristan. We both think Inputs/Outputs makes more sense. Even with the definition you gave the number of input files is countable within the folder, there are two possible inputs, animal_management.json, and barnyard.json.

@HectorMM3 @KFosterReed @tangswm

2020-07-02 20:58 UTC, militsasotirova reviewed
I like the simplification the tiered JSON provides! I was thinking that maybe we should change the name of the 'databases' folder in 'input' because Joseph is working on transferring the weather files to a database so it might get confusing (maybe the new name could be something like 'feed_library'). Also there is an empty 'feeds.sqlite' in the 'input' folder - do we need that file?

2020-07-07 13:12 UTC, merged