OM CSV Task #2: info_map csv files.
RuminantFarmSystems/RuFaS pull request #676
Opened 2023-07-19 19:37 UTC by michaelRichards99

Adds the info_map field from each variale in the `OutputManager`'s variable_pool to the csv file. Saves these csv files in the `/output/CSVs/om/variables` directory.

This PR addresses issue #642, which has a more detailed explanation of the requested changes.

2023-07-20 17:41 UTC, ew3361zh requested changes
I think this looks good, Michael. I have a couple small comments about spelling and a flake8 violation.

I think it would be good to expand test coverage for the exceptions being raised in `save_variables_to_csv_files` and `dict_to_file_csv`. If those are coming in a later PR, please just let me know as I think you mentioned this is part of a series of 3-4 PRs all related to this functionality.

2023-07-20 17:41 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            Flag for whether or not the user wants to inlcude info_maps data in their results files.
```suggestion
            Flag for whether or not the user wants to include info_maps data in their results files.
```

2023-07-20 17:41 UTC, ew3361zh commented on RUFAS/output_manager.py
> +                info_maps_file_path = os.path.join(str(info_map_path), self._generate_file_name(f"{key}_info_maps", "csv"))
getting a line too long error here. I think even though we've got the flake8 line length violation at 127 in github we're still trying to be below 120 when possible.

2023-07-20 17:41 UTC, ew3361zh commented on RUFAS/output_manager.py
>          except Exception as e:
write unit test to cover this exception correctly being raised.

2023-07-20 17:41 UTC, ew3361zh commented on RUFAS/output_manager.py
> +                info_map_path.mkdir(parents=True, exist_ok=True)
similarly I'd add a test to cover this exception being raised properly.

2023-07-20 22:12 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +                info_maps_file_path = os.path.join(str(info_map_path), self._generate_file_name(f"{key}_info_maps", "csv"))
Thanks. I'll use 120 from now on.

2023-07-20 22:12 UTC, michaelRichards99 commented on RUFAS/output_manager.py
>          except Exception as e:
Done.

2023-07-21 14:15 UTC, ew3361zh approved these changes
Looks good to me!

2023-07-26 20:30 UTC, ew3361zh approved these changes
Looks good, Michael. I think this addresses the requested changes as I understand them. Testing looks improved as well.

2023-07-26 20:30 UTC, ew3361zh commented on RUFAS/output_manager.py
> +        if not all(key in data_dict[variable_name].keys() for key in mandatory_fields):
Nice, this is an improvement over the previous version. More clear to understand.

2023-07-26 20:40 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        if not all(key in data_dict[variable_name].keys() for key in mandatory_fields):
Thanks Niko! I agree, much cleaner this time.

2023-07-27 02:38 UTC, PooyaHekmati requested changes
I think a little bit of over-engineering is happening here. Are all these complications needed? Are they justified?

2023-07-27 02:38 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        if not all(key in data_dict[variable_name].keys() for key in mandatory_fields):
Why is this needed? How is it possible to have missing values or info_maps?

2023-07-27 02:38 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _dict_to_csv_column_list(self, data_dict: Dict[str, List[Any]], mandatory_fields: List[str]
I don't think this function is needed, this is an aggressive application of SRP. Preparing the content fits well in the responsibility domain of `_dict_to_file_csv()`.

2023-07-27 02:38 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        variable_name = next(iter(data_dict))
why?

2023-07-27 02:38 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        data[variable_name] = data.pop("values")
I think this leads to side effects.

2023-07-27 03:34 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        if not all(key in data_dict[variable_name].keys() for key in mandatory_fields):
assuming the variable pool is valid then this check is not. I have this check here because the method name `_dict_to_file_csv` mentions nothing about the structure of the dictionary.

That being said, the rest of the method does assume some predefined structure. This can be removed if we assume all dictionaries have values and info_maps.

2023-07-27 03:34 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        data[variable_name] = data.pop("values")
Good catch, I'll remove this.

2023-07-27 03:34 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +        variable_name = next(iter(data_dict))
`data_dict` is dictionary with a single key value pair. 
```json
{
    "simple_key": {
        "values": ["Hi", "How", "Are", "You"],
        "info_maps": [
            {"map1": "value1", "map2": "value2", "map3": "value3"},
            {"map1": "value4", "map2": "value5", "map3": "value6"}
        ]
    }
}
```
`next(iter(data_dict))` was the cleanest way to get the key. I implemented this to produce this csv:

```csv
simple_key,info_maps
hi,"{'map1': 'value1', 'map2': 'value2', 'map3': 'value3'}"
how,"{'map1': 'value4', 'map2': 'value5', 'map3': 'value6'}"
are,
you,
```

Looking back at the design, the name of the variable is not actually needed here, I should just use the string "values".

```csv
values,info_maps
hi,"{'map1': 'value1', 'map2': 'value2', 'map3': 'value3'}"
how,"{'map1': 'value4', 'map2': 'value5', 'map3': 'value6'}"
are,
you,
```

I'll remove this.

2023-07-27 03:34 UTC, michaelRichards99 commented on RUFAS/output_manager.py
> +    def _dict_to_csv_column_list(self, data_dict: Dict[str, List[Any]], mandatory_fields: List[str]
For this specific PR, I agree. 

The next task for output manager csv file generation includes flattening complex data structures. This will result in 1 object being split into multiple csv columns. In that case, the logic in this method will be more complex, which is why I'm adding this helper method.

I can remove this from it's own function for this specific PR but I think I'll add it back when the logic becomes more complex in the following PR.

2023-07-28 01:13 UTC, PooyaHekmati approved these changes

2023-07-28 01:13 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _dict_to_csv_column_list(self, data_dict: Dict[str, List[Any]], mandatory_fields: List[str]
Well in that case I think it can stay.

2023-07-28 06:15 UTC, merged