Irrigation backward compatibility
RuminantFarmSystems/RuFaS pull request #680
Opened 2023-07-21 15:49 UTC by matthew7838

### Summary
This draft is to make the method `_determine_watering_amount()` backward compatible with the hard-coded irrigation in weather data. With this PR, it will add a condition to simply return the irrigation data straight from the provided weather data. Also, there is a method added to record the amount and time. All changes are tested to ensure full coverage. 

### Changes
- In `field.py`, `_determine_watering_amount` has added a field to take in irrigation, if the new irrigation field is provided it will simply use that as the watering amount
-  In `field.py`, `_determine_watering_amount` will now record the time and amount of watering when the old or new method is used.
- In `field.py`,  `_execute_daily_processes` and `_cycle_water` will now take in extra time parameters to help record the watering amount.
-  In `field.py`,  `_record_field_watering` is created to record the time and amount of watering occurrences..
- All changes are covered and tested

2023-07-27 21:28 UTC, Isgotkowitz requested changes
Excellent start Matthew, this PR is most of the way there. Only one significant piece of method behavior should be changed, everything else is minor tweaks and clarity related.

2023-07-27 21:28 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +            raise ValueError("Expected to use hardcoded irrigation data or specified amount, but tried to use both")
This should behavior should not throw an error, and instead default to the new method of watering over the hard-coded irrigation values.

2023-07-27 21:28 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +        # Old method that uses hard coded irrigation amount from the weather data
Instead of an in-line comment, it would be more appropriate to append to the `Notes` section a description of how this method checks for the multiple ways of watering, how it decides between them, etc.

2023-07-27 21:28 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +        irrigation
Irrigation needs description.

2023-07-27 21:28 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +    def _determine_watering_amount(self, rainfall: float, year: int, day: int, irrigation=0.0) -> float:
irrigation should  be type annotated. Also I'm curious, why default to 0.0?

2023-07-27 21:28 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +                    "field_size": self.field_data.field_size}
```suggestion
                    "prefix": f"field:'{self.field_data.name}'", "date": {"year": year, "day": day},
                    "field_size": self.field_data.field_size, "units": "mm"}
```

2023-07-27 21:28 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +        """Records a watering event to the OutputManager."""
Proper docstring

2023-07-27 21:28 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +    def _record_field_watering(self, year: int, day: int, watering_amount: float):
Return type annotation

2023-07-27 21:28 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +        value = {"watering_amount": watering_amount}
This doesn't need to be in a dictionary; you can just pass the value in directly.

2023-07-28 08:10 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/field/field.py
> +    def _determine_watering_amount(self, rainfall: float, year: int, day: int, irrigation=0.0) -> float:
There's no need for that after checking all conditions, I forgot to remove it.

2023-07-28 08:45 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/field/field.py
> +        value = {"watering_amount": watering_amount}
I don't really understand this, might need more clarifications or examples.

2023-07-28 08:50 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/field/field.py
> +            raise ValueError("Expected to use hardcoded irrigation data or specified amount, but tried to use both")
Yea, I was trying to ask for clarification on this case while you're away. Thanks for the clarification, Ed.

2023-07-28 15:34 UTC, Isgotkowitz approved these changes
Looks great Matthew, nice job

2023-07-28 15:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +        value = {"watering_amount": watering_amount}
```suggestion
        value = watering_amount
```

2023-07-28 15:34 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +        # Old method that uses hard coded irrigation amount from the weather data
```suggestion
```

2023-07-31 18:42 UTC, JoeWaddell approved these changes
Looks great, and nice work on the tests - they're very straightforward.

2023-07-31 18:48 UTC, merged