Create metadata
RuminantFarmSystems/RuFaS pull request #685
Opened 2023-07-24 19:48 UTC by allisterakun

2023-07-24 23:00 UTC, allisterakun commented
Current Status: 
- [x] Animal Module
    - [ ] Feeds Module
- [ ] Manure Module
- [ ] Field Management Module
    - [ ] Crop Specification: to be added (from @Isgotkowitz 's #665)
    - [ ] Soil Profile: to be added (from @Isgotkowitz 's #665)
    - [ ] Fertilizer Management
    - [ ] Manure Management
    - [ ] Tailage Management

2023-07-25 17:40 UTC, tomhuhh commented
Thanks for adding me to this PR Pooya! I also added Dr. Edward Garcia to keep him in the loop. I reviewed the section for methane mitigation strategies and they look reasonable to me. Thank you! Keep up the good work guys!

2023-07-25 17:53 UTC, allisterakun commented
Current Status: 
- [x] Animal Module
    - [ ] Feeds Module
- [ ] Manure Module ( **_IN PROGRESS_** )
- [ ] Field Management Module
    - [ ] Crop Specification: to be added (from @Isgotkowitz 's #665)
    - [ ] Soil Profile: to be added (from @Isgotkowitz 's #665)
    - [ ] Fertilizer Management
    - [ ] Manure Management
    - [ ] Tailage Management

2023-07-27 08:56 UTC, allisterakun commented
Current Status: 
- [x] Animal Module 
- [ ] Feeds Module
- [x] Manure Module
- [ ] Field Management Module
    - [ ] Crop Specification: to be added (from @Isgotkowitz 's #665)
    - [ ] Soil Profile: to be added (from @Isgotkowitz 's #665)
    - [ ] Fertilizer Management
    - [ ] Manure Management
    - [ ] Tailage Management

2023-07-31 17:14 UTC, ew3361zh commented on input/metadata.json
> +          "description": "Number of Cows (head) -- The the initial number of dry and lactating cows (all parities, default is ~51% of herd number).",
```suggestion
          "description": "Number of Cows (head) -- The initial number of dry and lactating cows (all parities, default is ~51% of herd number).",
```

2023-07-31 17:19 UTC, ew3361zh commented on input/metadata.json
> +          "description": "Breed (select one Holstein/Jersey) -- The predominant breed of the herd (Holstein or Jersey)"
```suggestion
          "type": "string",
          "default": "HO",
          "pattern": "^{HO|JE}$"
          "description": "Breed (select one Holstein/Jersey) -- The predominant breed of the herd (Holstein or Jersey)"
```

2023-07-31 17:25 UTC, ew3361zh commented on input/metadata.json
> +              "description": "Milk Type (select one) -- The type of milk that is used to feed calves (Whole or Replacer)"
```suggestion
              "type": "string",
              "default": "whole",
              "pattern": "^{whole|replacement}$",
              "description": "Milk Type (select one) -- The type of milk that is used to feed calves (Whole or Replacer)"
```

2023-07-31 17:29 UTC, ew3361zh commented on input/metadata.json
> +                "description": "Heifer TAI (Timed Artificial Insemination) Protocol (select one) -- The breeding protocol for heifers (md5CG2P or md5CGP)"
```suggestion
                "type": "string",
                "default": "md5CG2P",
                "pattern": "^{md5CG2P|md5CGP}$",
                "description": "Heifer TAI (Timed Artificial Insemination) Protocol (select one) -- The breeding protocol for heifers (md5CG2P or md5CGP)"
```

2023-07-31 17:29 UTC, ew3361zh commented on input/metadata.json
> +            "description": "Semen Type (select one) -- Please choose whichever semen selection type makes up a majority of your breedings"
```suggestion
            "type": "string",
            "default": "sexed",
            "pattern": "^{sexed|conventional}$",
            "description": "Semen Type (select one) -- Please choose whichever semen selection type makes up a majority of your breedings"
```

2023-07-31 17:30 UTC, ew3361zh commented on input/metadata.json
> +          "description": "Initialize Herd? -- Only check box if cow body weight and milk production exceedingly abnormal"
```suggestion
          "type": "boolean",
          "default": false,
          "description": "Initialize Herd? -- Only check box if cow body weight and milk production exceedingly abnormal"
```

2023-07-31 17:31 UTC, ew3361zh commented on input/metadata.json
> +                "description": "Heifer SynchED Protocol (select one) -- 2P: two injections of PGF (prostaglandin), watch for estrus after each injection with insemination upon heat detection; CP: 7 d
```suggestion
                "type": "string",
                "default": "2P",
                "pattern": "^{2P|CP}$",
                "description": "Heifer SynchED Protocol (select one) -- 2P: two injections of PGF (prostaglandin), watch for estrus after each injection with insemination upon heat detection; CP: 7 days CIDR implements, inject PGF upon removal, insemination upon heat detection"
```

2023-07-31 17:32 UTC, ew3361zh commented on input/metadata.json
> +                "description": "Estrus Detection Rate -- The % of in-heat animalss that would be detected in the ED (Estrus Detection) programs (default is 0.65)",
```suggestion
                "description": "Estrus Detection Rate -- The % of in-heat animals that would be detected in the ED (Estrus Detection) programs (default is 0.65)",
```

2023-07-31 17:44 UTC, ew3361zh commented on input/metadata.json
> +          "pattern": "^{None|3-NOP|monensin|essential_oils|seaweed}$"
I'm not sure if json.load will correctly translate "None" from a json file. I think the way None is used in the regex pattern would still work but I will think about that a little longer as well.

```suggestion
          "default": null,
          "pattern": "^{None|3-NOP|monensin|essential_oils|seaweed}$"
```

2023-07-31 17:46 UTC, ew3361zh commented on input/metadata.json
> +            "pattern": "^{screw_press|sand_lane|rotary_screen|none|other}$"
Not sure if it should be `None` here instead of `none`.

2023-07-31 19:40 UTC, Isgotkowitz commented
@allisterakun all boxes for the Crop and Soil module can be ticked

2023-08-02 08:56 UTC, YijingGong requested changes
Good job Allister! I have reviewed the animal life-cycle-related part, and left some minor comments as below. 
Btw, I also added to the Google doc (https://docs.google.com/document/d/1UEIEF24KZV6wlXul2hFZ0LSrvGFHlF7UaVWc1EtJL1g/edit?pli=1) the metadata for the 6 variables in the 'from_literature' section per Kristan's request.

2023-08-02 08:56 UTC, YijingGong commented on input/metadata.json
> +          "description": "Number of Calves (head) -- The average number of pre-weaned calves (default is ~4% of herd number)",
8/100 = 8%, so I guess "default is ~8% of herd number"

2023-08-02 08:56 UTC, YijingGong commented on input/metadata.json
> +          "description": "Number of HeiferIs (head) -- HeiferI is the number of youngstock post-weaning and before breeding (default is ~23% of herd number)",
Why is this ~23%? 44/100 = 44%. 
Maybe you've discussed this with Kristan and have a reason for it.

2023-08-02 08:56 UTC, YijingGong commented on input/metadata.json
> +          "description": "Initialize Herd? -- Only check box if cow body weight and milk production exceedingly abnormal"
Agree with above, default should be false. And description can be "whether to re-initialize the animal database, where the herd animals are selected from"

2023-08-02 08:56 UTC, YijingGong commented on input/metadata.json
> +              "description": "Voluntary Waiting Period (days) -- If 'TAI' (Timed Artificial Insemination) is chosen for cow, it is days after parturition when the 1st hormonal injection is made in TA
description can be "Voluntary Waiting Period (days) -- If 'TAI' (Timed Artificial Insemination) is chosen for cow, it is days after parturition when the 1st hormonal injection is made in TAI programs. If 'ED' or 'ED-TAI' is chosen for cow, it is days after parturition when estrus is started to be monitored"

2023-08-02 08:56 UTC, YijingGong commented on input/metadata.json
> +            "num_21_days_repro": {
this should be deleted. I mentioned this under the DCA topic. So I guess we need to need them consistent.

2023-08-02 08:56 UTC, YijingGong commented on input/metadata.json
> +                "description": "Estrus Detection Rate -- The % of in-heat animalss that would be detected in the ED (Estrus Detection) programs (default is 0.65)",
typo of "animalss"

2023-08-02 08:56 UTC, YijingGong commented on input/metadata.json
> +              "description": "Pregnancy Check Day 1 (days) -- Days Since Last Heat of pregnancy check 1 (default is 32)",
"description": "Pregnancy Check Day 1 (days) -- Days since last insemination to check whether the animal is pregnant or not for the first time (default is 32)".

2023-08-02 08:56 UTC, YijingGong commented on input/metadata.json
> +              "description": "Pregnancy Check Day 2 (days) -- Days Since Last Heat of pregnancy check 2 (default is 60)",
"description": "Pregnancy Check Day 2 (days) -- Days since last insemination to check whether the animal is pregnant or not for the second time if the animal pass the first pregnancy check (default is 60)".

2023-08-02 08:56 UTC, YijingGong commented on input/metadata.json
> +              "description": "Pregnancy Check Day 3 (days) -- DCC of pregnancy check 3 (default is 172)",
"description": "Pregnancy Check Day 3 (days) -- Days since last insemination to check whether the animal is pregnant or not for the third time if the animal passes the second pregnancy check (default is 200)". 
The default number should be 200. refer to https://docs.google.com/document/d/1UEIEF24KZV6wlXul2hFZ0LSrvGFHlF7UaVWc1EtJL1g/edit?pli=1

2023-08-02 08:57 UTC, YijingGong submitted a review, later dismissed
Good job Allister! I have reviewed the animal life-cycle-related part, and left some minor comments as below.
Btw, I also added to the Google doc (https://docs.google.com/document/d/1UEIEF24KZV6wlXul2hFZ0LSrvGFHlF7UaVWc1EtJL1g/edit?pli=1) the metadata for the 6 variables in the 'from_literature' section per Kristan's request.

2023-08-02 13:08 UTC, allisterakun commented on input/metadata.json
> +            "pattern": "^{screw_press|sand_lane|rotary_screen|none|other}$"
I will change it to None just in case

2023-08-02 13:14 UTC, allisterakun commented on input/metadata.json
> +          "description": "Number of HeiferIs (head) -- HeiferI is the number of youngstock post-weaning and before breeding (default is ~23% of herd number)",
This was from the original Data Collection App, I am not sure if anything changed from then. What value should I put for default?

2023-08-02 13:31 UTC, ew3361zh commented on input/metadata.json
> +          "description": "Number of HeiferIs (head) -- HeiferI is the number of youngstock post-weaning and before breeding (default is ~23% of herd number)",
This was something I did in the DCA because I was confused between cow_num and herd_num (I thought herd_num was the sum of the calf_num, the 3 heifer nums, and the cow_num). So after adding those numbers together, I got 187, and I determined it's ~23% of that.

2023-08-02 14:05 UTC, YijingGong commented on input/metadata.json
> +          "description": "Number of HeiferIs (head) -- HeiferI is the number of youngstock post-weaning and before breeding (default is ~23% of herd number)",
I see. But actually, cow_num is the "current", or say "initial" adult cow number when the simulation starts, while the herd_num is the "target" size of the herd (number of adult cows). By default, they are the same (either both 100, or both 1000). But there are cases where some farmers want to expand their herd, or something, so they can have two different values. 
So I think maybe we can just delete "(default is ~23% of herd number)" to avoid confusion.

2023-08-02 14:32 UTC, allisterakun commented
Current Status: 
- [x] Animal Module 
- [x] Feeds Module
- [x] Manure Module
- [x] Field Management Module
    - [x] Crop Specification: to be added (from @Isgotkowitz 's #665)
    - [x] Soil Profile: to be added (from @Isgotkowitz 's #665)
    - [x] Fertilizer Management (from @Isgotkowitz 's #665)
    - [x] Manure Management (from @Isgotkowitz 's #665)
    - [x] Tailage Management (from @Isgotkowitz 's #665)

2023-08-02 14:49 UTC, ew3361zh reviewed
Looking good, Allister. Just some small fixes from me.

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +            "description": "Semen Type (select one) -- Please choose whichever semen selection type makes up a majority of your breedings"
```suggestion
            "description": "The semen type that makes up a majority of the farm's breedings"
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +              "pattern": "^{whole|replacement}$",
Sorry, got this wrong before, it should be `whole` or `replacer`.
```suggestion
              "pattern": "^{whole|replacer}$",
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +        "description": "Pen Information -- Add as many different pens as needed.",
```suggestion
        "description": "Pen Information.",
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +        "description": "Calf Feeds (raised off farm - 24 hrs of age) -- Add as many calf feeds as needed",
```suggestion
        "description": "Calf Feeds (raised off farm - 24 hrs of age).",
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +        "description": "Growing Feeds (HeiferI and HeiferII - return at 20 months) -- Add as many growing feeds as needed. HeiferI is the number of youngstock post-weaning and before breeding. Heifer
```suggestion
        "description": "Growing Feeds (HeiferI and HeiferII - return at 20 months) -- HeiferI is the number of youngstock post-weaning and before breeding. Heifer II is the number of heifers eligible for breeding and in early pregnancy.",
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +        "description": "Close Up Feeds (HeiferIII and Dry Cows) -- Add as many close feeds as needed. HeiferIII is the number of close-up heifers and Dry Cows are non-lactating cows.",
```suggestion
        "description": "Close Up Feeds (HeiferIII and Dry Cows) -- HeiferIII is the number of close-up heifers and Dry Cows are non-lactating cows.",
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +        "description": "Lactating Cow Feeds -- Add as many lactating cow feeds as needed",
```suggestion
        "description": "Lactating Cow Feeds",
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +        "description": "Purchased Feeds -- Select one purchased feed at a time and add the cost per kg of dry matter",
```suggestion
        "description": "Purchased Feeds.",
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +        "description": "Storage Options -- Add as many storage options as needed",
```suggestion
        "description": "Storage Options.",
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +            "description": "Ventilation -- True if the storage unit has appropriate ventilation."
```suggestion
            "type": "boolean",
            "description": "Ventilation -- True if the storage unit has appropriate ventilation.",
            "default": true
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +            "pattern": "^{None|heterofermentative|homofermentative}$"
It looks like none of the radio fields are generating the auto-default. Because there are "defaults" in the DCA feeds section, I think it could be helpful to have the same default here as well.
```suggestion
            "type": "string",
            "description": "Inoculation",
            "pattern": "^{None|heterofermentative|homofermentative}$",
            "default": null
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +          "description": "Calf",
```suggestion
          "description": "Calf Feeds.",
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +          "description": "Growing Heifers",
```suggestion
          "description": "Growing Heifers Feeds.",
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +          "description": "Close UP",
```suggestion
          "description": "Close UP Feeds.",
```

2023-08-02 14:49 UTC, ew3361zh commented on input/metadata.json
> +          "description": "Lactating Cow",
```suggestion
          "description": "Lactating Cow Feeds.",
```

2023-08-02 14:56 UTC, allisterakun commented on input/metadata.json
> +            "pattern": "^{None|heterofermentative|homofermentative}$"
I think maybe we should default to the None option?
But good point! I will make sure all enums have a default.

2023-08-03 19:56 UTC, ew3361zh commented on input/metadata.json
> +              "default": 43.9,
This one is 32 from the json you shared with me from Yijing.
```suggestion
              "default": 32,
```

2023-08-04 17:25 UTC, Isgotkowitz reviewed
Got the fixes in, thank you Allister

2023-08-04 17:25 UTC, Isgotkowitz commented on input/example_metadata.json
>          "pattern": "^{generic|corn|spring_wheat|winter_wheat|cereal_rye|spring_barley|fall_oats|tall_fescue|alfalfa|soybean|sugar_beet|potato}$"
```suggestion
        "pattern": "^{generic|corn|silage_corn|spring_wheat|winter_wheat|cereal_rye|spring_barley|fall_oats|tall_fescue|alfalfa|soybean|sugar_beet|potato|triticale}$"
```

2023-08-04 17:25 UTC, Isgotkowitz commented on input/example_metadata.json
>          "description": "List of years in which manure will be applied.",
```suggestion
        "description": "List of years in which tilling will occur.",
```

2023-08-04 17:25 UTC, Isgotkowitz commented on input/example_metadata.json
>          "description": "List of days on which manure will be applied.",
```suggestion
        "description": "List of days on which tilling will occur.",
```

2023-08-06 18:02 UTC, KFosterReed commented on input/example_metadata.json
>          "description": "List of years in which manure will be applied.",
@Isgotkowitz in reviewing PR# 714 it looks like there are two different year variables in the field management json files. For example, fertilizer, manure, and tillage have an input called "rotation_years" as well as an input called "year". Depending on the json file, one or the other is used but not both that I see. Can you please clarify if there are supposed to be two? If there are, can you please share the definitions with @allisterakun and make sure they are added to the metadata? Thnx!

2023-08-06 18:18 UTC, KFosterReed approved these changes
This looks great to me! There is the one question about the year inputs for the field management practices that I have right now. I expect a few small updates will need to be made but it looks fairly complete to me and it makes sense to me to merge soon and put the polishing touches on afterwards

2023-08-07 14:45 UTC, Isgotkowitz commented on input/example_metadata.json
>          "description": "List of years in which manure will be applied.",
@KFosterReed and @allisterakun "rotation_years" should not be used at all. I am not sure what its intended purpose was, but they are seemingly unused in the old code so I think it is safe to remove them entirely from the new input.

2023-08-07 15:05 UTC, ew3361zh approved these changes
I agree with Kristan here that there are likely things we will need to fix as this gets implemented and integrated but I think it is in good shape now. I think we're at the stage with it where merging it will help us most quickly get to the other issues it may have.

From conversations with Ed, I wonder if a better name for the file would be `default_metadata` since I think that's what this has become but again, not something I'd hold up merging this to discuss. It's an easy change if we decide it's helpful down the line.

2023-08-07 17:08 UTC, merged

2023-08-08 13:49 UTC, YijingGong reviewed
Hey Allister, good job adding all the new variables. I just had several minor comments. In addition, I found it seems we do not have "avg_estrus_cycle_heifer" and "std_estrus_cycle_heifer" in the metadata. Did we delete them on purpose?

2023-08-08 13:49 UTC, YijingGong commented on input/example_metadata.json
> +          "description": "Number of HeiferIIs (head) -- HeiferII is the number of heifers eligible for breeding and in early pregnancy (default is ~20% of herd number)",
Could you delete the "(default is ~20% of herd number)", also for the heiferIII description, and cow description.

2023-08-08 13:49 UTC, YijingGong commented on input/example_metadata.json
> +              "description": "Average days between calving and first estrus after calving.",
I am not sure if you want to keep consistency with above descriptions by adding "(default is ...)".

2023-08-08 13:49 UTC, YijingGong commented on input/example_metadata.json
> +                  "minimum": 0
I am just curious that why we do not have default values for wood_l, and below wood_m, wood_n, etc.?

2023-08-08 13:49 UTC, YijingGong commented on input/example_metadata.json
> +                "maximum": 1
From wood's parameters up to here still_birth_rate, we do not have default values. Is it this way intentionally?