Negative water evaporation bug draft
RuminantFarmSystems/RuFaS pull request #710
Opened 2023-08-02 03:42 UTC by matthew7838

### Summary
This small PR is to find out what causing the negative water_evporation value in the output and fix it. This will solve issue #643.

### Changes

- In `field.py`, `_determine_potential_evapotranspiration` will now set a minimum return value to 0.0 if `avg_air_temp` was too small.
- A few changes to condition statements in `evaporation.py`.
### Notes
These values might need to be re-evaluated again by science experts.

2023-08-03 16:46 UTC, Isgotkowitz requested changes
Nice fix Matthew. Requested changes on some docstrings, and also want to make sure that changes are being properly tested.

2023-08-03 16:46 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/crop/water_uptake.py
> +        """adjusts the potential water uptakes from each layer based by drawing from deeper layers when possible.
```suggestion
        """Adjusts the potential water uptakes from each layer based by drawing from deeper layers when possible.
```

2023-08-03 16:46 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +        nonsense negative evapotranspirative demand.
```suggestion
        method. This method lower-bounds the potential evapotranspiration at 0.0 mm.
```

2023-08-03 16:46 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +            raise Exception
This should either have a much more descriptive error raised, or it should be removed. If there is a problem with the weather data it should be caught and dealt with at a much higher level than the `Field` module, but on the other hand, if having invalid min and max air temps will really wreck the result of this function then its a good idea to check them.

2023-08-03 16:46 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +                           * (calculated_avg_air_temp + 17.8)) / latent_heat_vaporization)
```suggestion
            potential_evapotranspiration = (0.0023 * extra_terrestrial_radiation * ((max_air_temp - min_air_temp) ** (-0.5))
                           * (calculated_avg_air_temp + 17.8)) / latent_heat_vaporization
            return max(0, potential_evapotranspiration)
```
I think this would improve readability.

2023-08-03 16:46 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +                           * (avg_air_temp + 17.8)) / latent_heat_vaporization)
Same as above

2023-08-03 16:46 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
>          if avg_air_temp is None:
Is the lower bounding in this function tested?

2023-08-03 17:45 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/crop/water_uptake.py
> +        """adjusts the potential water uptakes from each layer based by drawing from deeper layers when possible.
This sentence is still a little confusingly worded. I think it's something in the "...from each layer based by drawing from..." construction. 

```suggestion
        """Adjusts the potential water uptakes from each layer by drawing from deeper layers when possible.
```

Are there multiple potential water uptakes for each layer?

2023-08-03 17:59 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/field/field.py
> +        if max_air_temp - min_air_temp < 0:
With the check on avg_air_temp below being None, is it worth doing a similar check on these two? I guess at least you can do something to address avg_air_temp  is None whereas there's not as easy a solution for either of these being None.

2023-08-03 18:13 UTC, ew3361zh commented on SC_redesign/Crop_and_Soil/field/field.py
>          if avg_air_temp is None:
I think testing should be appropriately expanded to show any potentially negative water evaporation is caught now.

2023-08-03 18:40 UTC, ew3361zh reviewed
Looks good! Added a few comments, I agree with the changes requested from Ed and will approve once everything's addressed.

2023-08-04 03:46 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/crop/water_uptake.py
> +        """adjusts the potential water uptakes from each layer based by drawing from deeper layers when possible.
Honestly, I'm not sure either. I did not write that, let me look into it.

2023-08-04 03:47 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/field/field.py
> +        nonsense negative evapotranspirative demand.
Thanks.

2023-08-04 03:48 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/field/field.py
> +            raise Exception
Sorry, this is just used to find the bugs, there's no actual use, so I'll delete it. Good catch.

2023-08-04 03:48 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/field/field.py
> +                           * (calculated_avg_air_temp + 17.8)) / latent_heat_vaporization)
Good suggestion.

2023-08-04 03:49 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/field/field.py
>          if avg_air_temp is None:
Good suggestion.

2023-08-04 03:51 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/field/field.py
> +        if max_air_temp - min_air_temp < 0:
I think that the validation of min and max temperature will be something checked on a higher level when dealing with input files. There's not much to do with these value's sanity checks in this scope.

2023-08-04 05:23 UTC, matthew7838 commented on SC_redesign/Crop_and_Soil/crop/water_uptake.py
> +        """adjusts the potential water uptakes from each layer based by drawing from deeper layers when possible.
Now I looked into it. No, there's only 1 uptake for each layer.

2023-08-04 14:36 UTC, Isgotkowitz approved these changes
Looks good, thanks for making those changes Matthew

2023-08-04 14:36 UTC, Isgotkowitz commented on SC_redesign/Crop_and_Soil/field/field.py
> +        method.This method lower-bounds the potential evapotranspiration at 0.0 mm.
```suggestion
        method. This method lower-bounds the potential evapotranspiration at 0.0 mm.
```

2023-08-04 14:39 UTC, ew3361zh approved these changes
LGTM!

2023-08-04 14:40 UTC, merged