IM Validate CSV Input
RuminantFarmSystems/RuFaS pull request #724
Opened 2023-08-09 14:06 UTC by ew3361zh

This PR seeks to address issue #723 to ensure Input Manager can validate and fix input data loaded from CSV files.

To accomplish this, the PR:
1. Creates a new function `_validate_csv_element()` which validates each row of data under a particular column until all columns have been validated and/or fixed.
2. Renames `_validate_element()` to `_validate_json_element()` to follow the pattern of the new `_validate_csv_element()` and distinguish the type of file data it validates.
3. Creates a helper function `_get_validity()` which reduces duplicate code in both `_validate_csv_element()` and `_validate_json_element()`
4. Updates the _populate_pool() method to route elements by file type to the correct element validation functions.
5. Updates the _fix_data() function's argument types to allow for it to receive a csv array element index to fix.
6. Expands unit testing to show functionality of new features.

2023-08-09 14:31 UTC, allisterakun approved these changes
Logic looks good to me!

2023-08-10 05:27 UTC, PooyaHekmati commented
I haven't reviewed the PR fully yet, but from the logs, I can see that lines 192, 276, 343-344, 356-357 don't have test coverage. We achieved 100% test coverage for IM in PR #726. This PR is reducing it to 98%.

2023-08-10 15:27 UTC, ew3361zh commented
> I haven't reviewed the PR fully yet, but from the logs, I can see that lines 192, 276, 343-344, 356-357 don't have test coverage. We achieved 100% test coverage for IM in PR #726. This PR is reducing it to 98%.

I've updated testing to have 100% coverage.

2023-08-11 17:34 UTC, PooyaHekmati requested changes

2023-08-11 17:34 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        return validator(variable_properties, var_name, input_data_value)
Check for correctness before accepting the change.
```suggestion
    def validate_input_type_dynamic(self, variable_properties, var_name, input_data_value):
    """
    Validates the input data value based on its specified dynamic type.

    Parameters
    ----------
    variable_properties : dict[str, Any]
        A dictionary containing properties relevant to the validation.
    var_name : str
        The name of the variable being validated.
    input_data_value : any
        The input data value to be validated.

    Returns
    -------
    bool
        True if the input data value is valid for the specified type, False otherwise.

    Raises
    ------
    KeyError
        If an invalid type is provided in the variable_properties or if "type" key is missing.

    Notes
    ------
    This function determines the type of validation needed based on the 'type' property in variable_properties.
    It dynamically selects the appropriate validator based on the determined type and delegates the validation
    process to that validator function. If the determined type is not recognized or if "type" key is missing,
    a KeyError is raised.

    Example
    --------
    variable_properties = {"type": "string", "min_length": 3, "max_length": 10}
    var_name = "name"
    input_data_value = "John Doe"
    is_valid = validate_input_type_dynamic(variable_properties, var_name, input_data_value)
    if is_valid:
        print(f"{var_name} is a valid {variable_properties['type']}.")
    else:
        print(f"{var_name} is not a valid {variable_properties['type']}.")
    """
    if "type" not in variable_properties:
        raise KeyError("Missing 'type' key in variable_properties")

    var_type = variable_properties["type"]
    data_type_to_validator_map = {
        "string": self._string_type_validator,
        "number": self._num_type_validator,
        "array": self._array_type_validator,
        "bool": self._bool_type_validator,
    }

    try:
        validator = data_type_to_validator_map[var_type]
    except KeyError:
        raise KeyError(
            f"Invalid type {var_type}: Element must be type {data_type_to_validator_map.keys()}"
        )

    return validator(variable_properties, var_name, input_data_value)
```

2023-08-11 17:34 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        var_type = variable_properties["type"]
```suggestion
```

2023-08-11 17:34 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        property : str
var_name?

2023-08-21 14:44 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        var_type = variable_properties["type"]
Removed.

2023-08-21 14:44 UTC, ew3361zh commented on RUFAS/input_manager.py
> +        return validator(variable_properties, var_name, input_data_value)
Incorporated!

2023-08-24 03:53 UTC, PooyaHekmati approved these changes
Please address the comment before merging.

2023-08-24 03:53 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +    def _fix_data(self, variable_properties: Dict[str, Any], element_hierarchy: list,
Please specify element_hierarchy is a list of what? str?

2023-08-25 13:14 UTC, ew3361zh commented on RUFAS/input_manager.py
> +    def _fix_data(self, variable_properties: Dict[str, Any], element_hierarchy: list,
Updated.

2023-08-25 13:16 UTC, merged