Ration refactor m2
RuminantFarmSystems/RuFaS pull request #751
Opened 2023-09-06 19:28 UTC by JoeWaddell

This is intended to reflect goals of Milestone 2 in this design doc: https://docs.google.com/document/d/1AvB1Lee54gf_6vsOo03BolMJ4qabZWoqJP9QkDD-yig/edit

Note that expanding test coverage and adding docstrings is one of the subsequent stacked PRs, as outlined in this Design Doc. Here we've removed the use of globals, and instead have instituted a RationConfig class. We've also renamed the ration_NLP file to avoid confusion, and coincide with the Class name itself. Any and all variable names are up for change, but we elected to change those in a later milestone, to avoid issues where incomplete name changes in the code led to errors.

2023-09-07 19:38 UTC, JoeWaddell commented
@ltp23 has opened a parallel branch that may provide an alternate solution to the issue of reliance on globals: see https://github.com/RuminantFarmSystems/MASM/pull/754
NOTE: that PR was merged in here

2023-09-28 14:27 UTC, ancheypeng commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +    def total_energy(self, x: np.ndarray, ration_config: RationConfig) -> None:
Is there a reason why all the `ration_optimizer` functions have return type `None` even though they are returning something? Also, is the variable name `x` a standard for decision vectors or could it be named something more meaningful?

2023-09-28 14:34 UTC, JoeWaddell commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +    def total_energy(self, x: np.ndarray, ration_config: RationConfig) -> None:
None type: mistake on my part! They should all return floats. I'll update those, though also note that most of the docstrings are still out of date. The plan is that we'll reformat those (in full) in a different PR, Milestone 5, just to keep the changes here minimal. 

Renaming `x` to decision_vector or something more descriptive sounds great. Those were the types of things I had slated for Milestone 5, but we can do them here if it makes it easier to review, too.

2023-09-28 14:39 UTC, ancheypeng commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +    def total_energy(self, x: np.ndarray, ration_config: RationConfig) -> None:
Ah ok, that makes sense! I just thought because the function headers were already being changed, the return type and `x` would be simple changes to clean it up.

2023-09-28 14:43 UTC, ancheypeng approved these changes
LGTM!

2023-10-03 07:20 UTC, Fjordrunner requested changes
Most of these are nitpicky. A last observation that I see is the usage of the name `x`, assigned to the decision vector argument for many functions within the NLP file. If this is convention, please ignore my comment, but if not, then maybe a more informative name like `decision_vector` might be better. A lot of my comments are repeated nitpicks: please feel free to ignore if this would cause too much work.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    price : list
This should be a plural at the very least, or something around the lines of `price_list` to imply that it is not a singular price. This occurs in a few other places , from now on I'll just say "refer to first comment" if there is a similar case regarding variable naming.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    is_fat : list of bool
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    calcium : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_driver.py
> +           Joseph Waddell, jw2574@cornell.edu
Is this here twice now?

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_driver.py
> +ration_optimizer = RationOptimizer()
Is this duplicating the line above it?

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_driver.py
> +                reduction = 0.25
This is looking like a magic value. Unless there is some domain expertise that I'm missing here, I think we should either rename this variable or add it to the constants file we have.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +        ration_config.DEact = DEact
This is a bit redundant, we don't need to create DEact before assigning it to ration_config.DEact. The one line of code could be `ration_config.DEact = np.multiply(ration_config.DE, Discount)`

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +            if ration_config.is_fat[i] == 1:
This is a good example of why `is_fat` should have a better name, it doesn't make much sense to index it given its current name.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +            ration_config.Discount = 1
Should this be a constant? Not 100% sure what the 1 means in this context.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    TDN : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    DE : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    EE : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    phosphorus : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    NDF : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    type : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    is_wetforage : list of bool
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    Kd : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    N_A : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    N_B : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    CP : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    dRUP : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    limit : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    MEact : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    NEgact : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    NEm_act : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    is_forage : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    MPbact : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    RUP_diet : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    dP : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +    TDNact : list
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        limit_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        dRUP_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        CP_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        N_B_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        N_A_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        Kd_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        is_wetforage_ : list of bool, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        type_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        NDF_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        phosphorus_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        calcium_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        is_fat_ : list of bool, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        EE_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        DE_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        TDN_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_config.py
> +        price_ : list, optional
Refer to first comment.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +    def list_reconfig(list: List) -> List:
I think that the name of the function here could be improved, maybe something around the lines of `triple_values_in_list`? In general, I think it's best practice to make the first word of a function name to be a verb?

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +    def total_energy(self, x: np.ndarray, ration_config: RationConfig) -> float:
Does this function calculate the total energy still? The docstring doesn't directly point to it doing so, unless I am being ignorant from an animal science perspective.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +        x : numpy.ndarray
Is it best practice or commonplace to label the decision vector as `x`? If not, naming it as `decision_vector` here and elsewhere might be a good idea.

2023-10-03 07:20 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_optimizer.py
> +            if ration_config.type[i] == 'Forage':
Potentially a good place to use constants?

2023-10-03 18:28 UTC, Fjordrunner approved these changes
I found one last nitpicky issue. Other than that, and the potential decision vector renaming we discussed, I think this looks good. Thanks for being patient with my review!

2023-10-03 18:28 UTC, Fjordrunner commented on RUFAS/routines/animal/ration/ration_driver.py
> +        if pen.animal_combination.name in ['LAC_COW']:
Can't we just check if the name is 'LAC_COW' directly?

2023-10-03 19:04 UTC, merged