Output Graph Generation
RuminantFarmSystems/RuFaS pull request #779
Opened 2023-09-15 19:14 UTC by allisterakun

This PR implements issue #777. We do so by introducing a new class GraphGenerator. This class serves the purpose of generating plots and graphs from the simulation results.

To use this class to generate a graph, the user should create a `JSON` file (please use `png_default_filter.json` as an example) and place it under the `output/output_filter/` folder. The file name start should start with the `"png_"` prefix, which is used in `output_handler.py` to identify the desired output file type.

The `JSON` file should contain the following information:
1. Graph Type (line graph, bar graph)
2. RegEx filter(s) to filter the output to get the desired variables for the graph
3. (Optional) Other information (title, x-axis and y-axis label): all other information is optional. If there are any other customizations that you need, please contact me via Slack

Currently, the GraphGenerator class supports two types of graphs: line graphs and bar graphs, as they are the most commonly used types. If you ever need to generate a graph of any other type, please contact me via Slack.

--------------------------------
Edit and updates from Pooya
--------------------------------
This PR implements issue #777. We do so by introducing a new class GraphGenerator. This class serves the purpose of generating plots and graphs from the simulation results.

This PR introduces new filter files for the output manager which are needed for graph generation. Therefore, the names of these filters start with `graph_`. Since they need to contain more information, they are JSON rather than text. These JSON filter files contain:
1. `type`: the type of the graph. While many types are being introduced, only plot and stackplot are tested in this PR. It is likely that other graph types fail. In that case, please reach out to the dev team and we will address the issue in future PRs.
1. `filters`: the good old regex-based filters. A list of regex filters is expected here. Any matching variable in the OM pool will be plotted on the same graph.
1. `variables`: When the data is stored in dictionaries (i.e., when reporting the variable to the output manager using `OutputManager.add_variable()`, a dict was passed), the `variables` entry allows selecting which variables in the dictionary are being plotted.
1. other details: including legend, title, etc... The following list is currently implemented:
```
align_labels
aspect
canvas
constrained_layout
dpi
edgecolor
facecolor
figheight
figsize
figwidth
frameon
grid
legend
snap
subplot_adjust
tight_layout
title
transform
xlabel
xticklabels
xticks
xlim
ylabel
yticklabels
yticks
ylim
yscale
xscale
zorder
```

An example JSON filter is provided in this PR:
```
{
  "type": "plot",
  "filters": [
    "Pen\\.calc_total_manure\\.daily_aggregate_calf_(degradable|non_degradable)_volatile_solids"
  ],
  "title": "Daily Aggregate Calf Degradable Volatile Solids",
  "legend": ["Degradable Volatile Solids", "Non-degradable Volatile Solids"]
}
```

Another example for cases that data is reported in dictionaries is:
```
{
  "type": "plot",
  "filters": [
    "AnimalManager\\._calc_ration_at_interval\\.ration_per_animal_for_pen_3"
  ],
  "title": "ration per animal for pen 3",
  "variables": ["43", "51", "104", "121", "167", "231", "234"],
  "legend": ["43", "51", "104", "121", "167", "231", "234"]
}

```

In this PR we also brush up the GNU args as well introducing a new GNU arg to let the user choose where should the plots be saved.

I added this wiki: https://github.com/RuminantFarmSystems/MASM/wiki/Graph-Generator

2023-09-21 14:34 UTC, PooyaHekmati requested changes
Please provide a description for this PR.

2023-09-21 14:35 UTC, allisterakun commented
> Please provide a description for this PR.

Will do, fixing conflicts right now!

2023-09-21 16:03 UTC, PooyaHekmati requested changes
The PR is in the right direction. However, in addition to the comments I left in the code, some docstrings and type annotations are missing. Also, .gitignore needs to be modified to capture the changes in this PR.
Please see https://github.com/RuminantFarmSystems/MASM/wiki/Onboarding-New-Team-Members#type-checking and https://github.com/RuminantFarmSystems/MASM/wiki/Onboarding-New-Team-Members#sphinx-documentation-docstrings .

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +    def generate_graph(self, filtered_pool: dict, graph_info: dict, graph_path: str, **kwargs):
Please type annotate the dict correctly, this applies to other functions in this PR as well. 
see [dict typing doc](https://docs.python.org/3/library/typing.html#typing.Dict).

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +class GraphGenerator:
Add docstrings

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +            self._bar_graph(filtered_pool, graph_info, graph_path)
This structure avoids code duplication and makes it easier down the road to add new graph types.
```suggestion
        graph_type_funcs={
        "Line Graph": self._line_graph,
        "Bar Graph": self._bar_graph,
        }
        graph_type_funcs[graph_info["graph_type"]](filtered_pool, graph_info, graph_path)
```

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +        # TODO: add more functionalities
Unnecessary
```suggestion
```

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +        plt.savefig(graph_path)
What if saving fails?
This operation (saving) seems to be repeated, can we have a wrapper function for it which also catches exceptions?

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            raise e
At this point, we have run the simulation and have the results ready. If we can't make the directory, we still can save the the result as JSON or CSV. Raising the exception here halts the execution. Instead, let's report the error to OM.errors_pool and move on (use self.add_error() )

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _load_filter_file_to_list(self, path: str):
What is the return type?

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/output_manager.py
>          """ Reads a text file into a list.
Does it?

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _load_filter_file_to_list(self, path: str):
I'm not sure about the change to this function. This function is developed to handle multiple filters in a txt file. Are you going to implement multiple filters in a json file as well? (I think that should be the case.) Extend the example given example json filter to reflect this so we can evaluate the correctness of this function.

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        gg = GraphGenerator()
avoid using unpronounceable and vague names.
```suggestion
        graph_generator = GraphGenerator()
```

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            elif filter_file.startswith("png_"):
png is a very specfic case. What if we want to save in other formats as well? Let's change it to vis_ or grp_ or even graph_ to make it generic.

2023-09-21 16:03 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _generate_graph_path(self, save_path: str, graph_info: dict, filter_file: str) -> str:
can we move this function to the GraphGenerator class? If that class is saving the graph, then it should be able generate its path as well.

2023-09-21 16:03 UTC, PooyaHekmati commented on output/output_filters/png_default_filter.json
> +{
Why is this file named default? What it is the significance of this graph to be the default?

2023-09-21 16:14 UTC, allisterakun commented on RUFAS/output_manager.py
> +    def _load_filter_file_to_list(self, path: str):
I think the Graph_generator can handle multiple variables as well, I will extend the example!

2023-09-21 16:50 UTC, allisterakun commented on RUFAS/output_manager.py
> +            raise e
If I move this function `generate_graph_path` into the GraphGenerator class, then I cannot add do `om.add_error()`. This would be a circular import. (OM is importing graph_generator.py).

2023-09-21 16:52 UTC, allisterakun commented on RUFAS/output_manager.py
> +            raise e
I guess I can extract the highlighted part (the part for making the directory) and move it into `utils.py` as a util function. How does this sound? @PooyaHekmati

2023-09-22 14:34 UTC, PooyaHekmati commented
Allister, please let me know when this is ready for review.
The merge conflict seems to be due to formatting, shouldn't be hard to resolve.
There are some coverage and linting issues with this PR, you can see them in the checks. Here they are for your reference as well:
Current test coverage:
`76%`
Missing lines:
> 47-48, 54-61, 70-71,  79

Linting issues:
>  ./RUFAS/graph_generator.py:9:1: E402 module level import not at top of file
> ./RUFAS/graph_generator.py:10:1: E402 module level import not at top of file
> ./RUFAS/graph_generator.py:21:128: E501 line too long (154 > 127 characters)
> ./RUFAS/graph_generator.py:73:59: F541 f-string is missing placeholders

2023-09-22 16:03 UTC, allisterakun commented
> Allister, please let me know when this is ready for review.
> 
> The merge conflict seems to be due to formatting, shouldn't be hard to resolve.
> 
> There are some coverage and linting issues with this PR, you can see them in the checks. Here they are for your reference as well:
> 
> Current test coverage:
> 
> `76%`
> 
> Missing lines:
> 
> > 47-48, 54-61, 70-71,  79
> 
> 
> 
> Linting issues:
> 
> >  ./RUFAS/graph_generator.py:9:1: E402 module level import not at top of file
> 
> > ./RUFAS/graph_generator.py:10:1: E402 module level import not at top of file
> 
> > ./RUFAS/graph_generator.py:21:128: E501 line too long (154 > 127 characters)
> 
> > ./RUFAS/graph_generator.py:73:59: F541 f-string is missing placeholders

Thank you! Will work on this in a second, and I'll message you when it's ready!

2023-09-27 16:40 UTC, PooyaHekmati commented
Will run into merge conflict with PR #810 ; waiting for that to clear up first.

2023-10-10 21:00 UTC, PooyaHekmati commented
TODOs:
1. _generate_graph_path() violates SRP
1. Hard coded graph directory in _generate_graph_path()
1. Probably move path generation to util and combine the logic with OM
1. use GNU args
1. docstrings
1. tests
1. reduce the scope of args

2023-11-02 17:58 UTC, KFosterReed commented
A first look at this PR and within 10 min I made a graph! AMAZING! I do have one question, it is not clear to me if we need a separate file for each graph or if we can include specification for multiple graphs in each filter file. I have to jump on a meeting now but some clarity on that would be helpful and I plan to test more graphs and options in this PR

2023-11-02 18:01 UTC, PooyaHekmati commented
> A first look at this PR and within 10 min I made a graph! AMAZING! I do have one question, it is not clear to me if we need a separate file for each graph or if we can include specification for multiple graphs in each filter file. I have to jump on a meeting now but some clarity on that would be helpful and I plan to test more graphs and options in this PR

I would like to have the capability of defining multiple graphs in one single file, but that is not the case in this PR. Right now, for each graph you need a separate file. Let's roll this out, we can add that functionality in the (near?) future.

2023-11-02 18:02 UTC, KFosterReed commented
> > A first look at this PR and within 10 min I made a graph! AMAZING! I do have one question, it is not clear to me if we need a separate file for each graph or if we can include specification for multiple graphs in each filter file. I have to jump on a meeting now but some clarity on that would be helpful and I plan to test more graphs and options in this PR
> 
> I would like to have the capability of defining multiple graphs in one single file, but that is not the case in this PR. Right now, for each graph you need a separate file. Let's roll this out, we can add that functionality in the (near?) future.

Yes, that sounds good and I think we can easily work with that. I just wasn't sure so perhaps a small addition to the Wiki to make that explicit

2023-11-02 18:32 UTC, PooyaHekmati commented
I updated the wiki.

2023-11-02 19:27 UTC, JoeWaddell reviewed
Nice work, this is extensive! The test coverage is great, and the wiki does a nice job of explaining how to set up new files/filters. 

Only request is outside the scope of this PR, see Issue #899.

2023-11-02 19:27 UTC, JoeWaddell approved these changes
Nice work, this is extensive! The test coverage is great, and the wiki does a nice job of explaining how to set up new files/filters. 

Only request is outside the scope of this PR, see Issue #899.

2023-11-02 19:27 UTC, JoeWaddell approved these changes
Nice work, this is extensive! The test coverage is great, and the wiki does a nice job of explaining how to set up new files/filters. 

Only request after review is outside the scope of this PR, see Issue #899. 

EDIT: apologies for the duplicate comments, I somehow managed to leave a review in triplicate in VS Code.

2023-11-02 22:16 UTC, Isgotkowitz approved these changes
Code looks great, and graph production works well. Many comments, but all are minor (related to docstrings, names, and TODOs).

One small thing I noticed while testing out this feature is that when a graph filter file does start with "graph_" the warning message recorded to the OutputManager is "<graph filter name>.json must be prefixed with csv_ or json_". It would be good to get this updated to "... prefixed with csv_, json_, or graph_".

A future feature that I think would be really useful to include is a way to set the x axis to be the simulation time - will make an issue for this.

2023-11-02 22:16 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +    NOTE: This class is not multi-thread safe!!!
```suggestion
    
    Notes
    -----
    This class is not multi-thread safe!!!

```

2023-11-02 22:16 UTC, Isgotkowitz commented on RUFAS/graph_generator.py
> +        """Draw a plot using the provided data and selected variables where the data is tuple"""
Expand docstring

2023-11-02 22:16 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +    def _list_txt_and_json_files_in_dir(self, dir_path: str) -> List[str]:
What about naming this `_list_filter_files_in_dir()`? I think this method follows the single responsibility principle well, but the current name makes it sound like it dual-purpose.

2023-11-02 22:16 UTC, Isgotkowitz commented on RUFAS/output_manager.py
> +        """Returns the list of txt and json files in the given path"""
```suggestion
        """
        Returns the list of filter files in the given path.
        
        Parameters
        ----------
        dir_path : str
            Path to the directory of filter files.
            
        Returns
        -------
        List[str]
            List of filter file names.
            
        Raises
        ------
        NotADirectoryError
            If the path argument does not point to a directory.
        
        """
```

2023-11-02 22:16 UTC, Isgotkowitz commented on RUFAS/util.py
> +        """
```suggestion

        Parameters
        ----------
        list_of_dicts : List[Dict[str, Any]]
            A list of dictionaries with string keys and integer values.

        Returns
        -------
        Dict[str, List[Any]]
            A dictionary where keys are unique keys from input dictionaries,
            and values are lists of corresponding values from input dictionaries.
        """
```

2023-11-02 22:16 UTC, Isgotkowitz commented on main.py
> +            The directory for saving graphics.
```suggestion
    graphics_dir : Path, optional
        The directory for saving graphics.
```

2023-11-02 22:16 UTC, Isgotkowitz commented on main.py
>          verbose  # TODO: this is currently unimplemented - GitHub Issue #211
Can/should this TODO be removed?

2023-11-02 22:16 UTC, Isgotkowitz commented on config/global_variables.py
Can the TODOs in this file be removed?

2023-11-02 22:16 UTC, Isgotkowitz commented on main.py
>          format_option: format for variable_names.txt output file
Update docstring format to NumPy style.

2023-11-02 22:16 UTC, Isgotkowitz commented on main.py
>      """Sets values of global variables in config/global_variables.py"""
Docstring

2023-11-02 22:16 UTC, Isgotkowitz commented on main.py
> +def parse_gnu_args() -> argparse.Namespace:
Docstrings added/updated here.

2023-11-02 22:16 UTC, Isgotkowitz commented on main.py
> +    def __call__(self, parser, namespace, values, option_string=None):
```suggestion
    def __call__(self, parser, namespace, values, option_string=None) -> None:
```

2023-11-02 22:16 UTC, Isgotkowitz commented on tests/test_main.py
> +    with patch("main.parse_gnu_args") as mock_parse_gnu_args:
```suggestion
    with patch("main.parse_gnu_args") as mock_parse_gnu_args, \
            patch("main.run_rufas") as mock_run_rufas:
```
It is possible to have multiple patches in the same context manager, instead of nesting them. It isn't really needed here, but might be helpful in the future if more patches need to be added.

2023-11-03 13:58 UTC, PooyaHekmati approved these changes

2023-11-03 13:58 UTC, PooyaHekmati commented on RUFAS/graph_generator.py
> +    NOTE: This class is not multi-thread safe!!!
This is a one-liner; it doesn't need to adhere to docstring styles.

2023-11-03 13:58 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +    def _list_txt_and_json_files_in_dir(self, dir_path: str) -> List[str]:
Yes, it follows SRP because it does one thing and one thing only which is the act of listing files. I think `_list_txt_and_json_files_in_dir` better describes what this function actually does. `_list_filter_files_in_dir` has the implicit assumption that this function will only be used for filter files (maybe we need it for other use cases as well)

2023-11-03 13:58 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        """Returns the list of txt and json files in the given path"""
We don't need extensive docstrings for every function. For functions that are deep in the call stack and work really under the hood, usually a single-liner is enough (assuming the name and the logic of the function are clear enough). In this case, it is pretty clear that this function gets a directory path and returns the list of txt and json files in it.

2023-11-03 13:58 UTC, PooyaHekmati commented on main.py
>          format_option: format for variable_names.txt output file
Let's do it in issue #902

2023-11-03 13:58 UTC, PooyaHekmati commented on main.py
>      """Sets values of global variables in config/global_variables.py"""
This function is being removed today.

2023-11-03 13:58 UTC, PooyaHekmati commented on main.py
>          verbose  # TODO: this is currently unimplemented - GitHub Issue #211
This function is being removed today.

2023-11-03 13:58 UTC, PooyaHekmati commented on main.py
> +    def __call__(self, parser, namespace, values, option_string=None):
Good catch

2023-11-03 13:58 UTC, PooyaHekmati commented on tests/test_main.py
> +    with patch("main.parse_gnu_args") as mock_parse_gnu_args:
I think it is, but I'm to keep the code as it is here.

2023-11-03 14:01 UTC, merged