Ration_refactor_m4
RuminantFarmSystems/RuFaS pull request #803
Opened 2023-09-25 14:51 UTC by JoeWaddell

Ration Refactor Milestone 4 (see [Ration Refactor Design Doc](https://docs.google.com/document/d/1AvB1Lee54gf_6vsOo03BolMJ4qabZWoqJP9QkDD-yig/edit#heading=h.b2q5gxknb0hn)), adding ration_supply method for reporting to output manager, and adds other incremental improvements to ration formulation methods. 

The new methods are essentially rewrites of the existing constraint methods in ration_optimizer.py, but report results for individual feed items (with the exception of calculating metabolizable protein, which requires the whole ration information).

For SMEs: please comment if any of the intermediate steps in calculating metabolizable protein (or any other intermediate values) should also be reported in ration_supply. Any and all of these can be removed from the report, as well. This is primarily for assessing nutrient and energy content of feed supply, for evaluation and ration comparison purposes.

2023-10-11 18:44 UTC, Isgotkowitz requested changes
Requesting changes only for two things: the noqa used on line 467, and TODOs on lines 693, 726, 758, 808, and 836 (all units related). For the noqa, it should only be used when there are no other ways to get around the issue without major changes. For the TODOs I just want to verify that there is a plan to add/figure out the units.

Otherwise code looks really good. Most comments are on minor things, mostly docstrings and method signatures, all take it or leave it. Once I hear back about the noqa and TODOs I'll approve.

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +              of fed dry matter)
```suggestion
        Parameters
        ----------
        ration : Dict
            A dictionary of the calculated ration.
        available_feeds : Dict
            Available feeds dictionary from the Feed class object.

        Returns
        -------
        Tuple[Dict, Dict]
            Tuple of two dictionaries: one of nutrient amounts, the other of nutrient concentration (as a percentage
              of fed dry matter).
```

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            Dictionary of nutrients and energy supplied by a formulated ration
```suggestion
        Nutrient and energy supply of a formulated ration.
        Different from the report_ration method, since this takes into account digestibility and other factors.

        Parameters
        ----------
        ration : Dict
            Dictionary of formulated ration, with keys as feed IDs, values as kg fed.
        available_feeds : Dict
            feed.available_feeds
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        Dict
            Dictionary of nutrients and energy supplied by a formulated ration.
```

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            feed.available_feeds
This should be a little more descriptive.

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +                feed_item_info = available_feeds[key]  # noqa
Instead of having `# noqa` here, can this line either be commented out or deleted?

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            Animal body weight in kg
```suggestion
            Animal body weight (kg).
```
This is the format we have been using in the Soil and Crop module, and it would be nice to make the modules consistent. However if this is the way the Animal module has units formatted in docstrings, then I think it would be better to keep it like this until we have time to go through all the modules and make them consistent.

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +
```suggestion
        Crucial step to take into account Total digestible nutrient (TDN)
        digesitbility (% of DM).
        Initial step in net energy (NE) and metabolizable energy (ME) calculations.

        Parameters
        ----------
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Total digestible nutrient (% of DM) discount, which is TDN digestibility decrease that is a result of
            TDN amount relative to TDN concentration.

        Notes
        -----
        See the following pseudocode for all equations
        [A.Cow.E.3]-[A.Heifer.E.3]

```

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +             TDN amount relative to TDN concentration
It may be good to verbosely state exactly how this % is represented i.e. saying that a value of 1.0 = 1% and 100.0 = 100%, not 1.0 = 100%. It seems like terms are generally standardized: percent means 1 = 1%, fraction means 0.01 = 1%, but there is always some ambiguity.

This is an issue that has come up a lot in Crop and Soil, we should explicitly state these assumptions somewhere in the RuFaS documentation so everyone can variables consistently.

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            actual digestible energy of feed item, Mcal/kg
```suggestion
        Returns actual digestible energy of feed item, Mcal/kg.
        Calculation is performed on a per feed item basis.

        Parameters
        ----------
        kg_fed : float
            Kilograms of feed item in ration.
        feed_item_info : Dict
            Dictionary of nutrient and energy information of feed item.
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Actual digestible energy of feed item, Mcal/kg.
```

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +
```suggestion
        Returns metabolizable energy of feed item.

        Parameters
        ----------
        kg_fed : float
            Kilograms of feed item in ration.
        feed_item_info : Dict
            Dictionary of nutrient and energy information of feed item.
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Metabolizable energy of feed i, Mcal/kg.

```

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            Net energy of feed i, Mcal/kg
```suggestion
        """
        Returns net energy of feed item available for maintenance requirements.

        Parameters
        ----------
        kg_fed : float
            Kilograms of feed item in ration.
        feed_item_info : Dict
            Dictionary of nutrient and energy information of feed item.
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Net energy of feed i, Mcal/kg.
```

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +        # turn ME into NEm
```suggestion
```
I think this is unnecessary

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            Net energy of feed i, Mcal/kg
```suggestion
        Returns net energy of feed item available for lactation requirements.

        Parameters
        ----------
        kg_fed : float
            Kilograms of feed item in ration.
        feed_item_info : Dict
            Dictionary of nutrient and energy information of feed item.
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Net energy of feed i, Mcal/kg.
```

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            Net energy of feed i, Mcal/kg
```suggestion
        Returns net energy of feed item available for growth requirements.

        Parameters
        ----------
        kg_fed : float
            Kilograms of feed item in ration.
        feed_item_info : Dict
            Dictionary of nutrient and energy information of feed item.
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Net energy of feed i, Mcal/kg.
```

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            Calcium supply of feed item, kg TODO: check units
```suggestion
        Returns calcium supply of feed item.

        Parameters
        ----------
        kg_fed : float
            Kilograms of feed item in ration.
        feed_item_info : Dict
            Dictionary of nutrient and energy information of feed item.
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Calcium supply of feed item, kg TODO: check units.
```

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            Calcium supply of feed item, kg TODO: check units
Is this TODO going to be addressed before this PR is merged?

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +
```suggestion
        Returns phosphorus supply of feed item.

        Parameters
        ----------
        kg_fed : float
            Kilograms of feed item in ration.
        feed_item_info : Dict
            Dictionary of nutrient and energy information of feed item.
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Phosphorus supply, kg TODO: check units.

```
Same question with the TODO here as above.

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            Fat supply of feed item, g TODO: check units
```suggestion
        Returns fat supply of feed item.

        Parameters
        ----------
        kg_fed : float
            Kilograms of feed item in ration.
        feed_item_info : Dict
            Dictionary of nutrient and energy information of feed item.
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Fat supply of feed item, g TODO: check units.
```
Same comment on TODO here as above

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            Dry matter fat percentage of feed item
```suggestion
        Returns fat content percentage of feed item.

        Parameters
        ----------
        kg_fed : float
            Kilograms of feed item in ration.
        feed_item_info : Dict
            Dictionary of nutrient and energy information of feed item.
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Dry matter fat percentage of feed item.
```
Same comment as above on how percentage is specified.

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +
```suggestion
        Calculates the forage neutral detergent fiber content of feed item.

        Parameters
        ----------
        kg_fed : float
            Kilograms of feed item in ration.
        feed_item_info : Dict
            Dictionary of nutrient and energy information of feed item.
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Forage neutral detergent fiber content of feed item, TODO: check units.

```
I think it is better to specify what the method does in the top level docstring, then be more specific about what is returned in the "Returns" section. Otherwise the top level docstring is super redundant.

Also same comment as above for the TODO here.

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +    def get_fat(cls, kg_fed, feed_item_info, ration_report, body_weight):
Type annotations for args and return value

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +    def get_fat_percentage(cls, kg_fed, feed_item_info, ration_report, body_weight):
Type annotations for args and return value

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +    def get_forage_NDF(cls, kg_fed, feed_item_info, ration_report, body_weight):
Type annotations for args and return value

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +    def get_metabolizable_protein(cls, ration, available_feeds, ration_report, body_weight):
Type annotations for args and return value

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            Metabolizable protein supply of feed item, TODO: check units
```suggestion
        Returns metabolizable protein supply  of feed item, TODO: check units.

        Parameters
        ----------
        kg_fed : float
            Kilograms of feed item in ration.
        feed_item_info : Dict
            Dictionary of nutrient and energy information of feed item.
        ration_report : Dict
            Dictionary of nutrient amount and concentrations.
        body_weight : float
            Animal body weight in kg.

        Returns
        -------
        float
            Metabolizable protein supply of feed item, TODO: check units.
```
Same comments as above for TODO and top level docstring.

2023-10-11 18:44 UTC, Isgotkowitz commented on RUFAS/routines/animal/ration/ration_driver.py
> +            counter += 1
This method is doing a lot - creating some subroutines that split things up would make it more digestible. Would it be possible to create one subroutine each for KP, RDP, and RUP calculations?

2023-10-11 18:51 UTC, JoeWaddell commented
> Requesting changes only for two things: the noqa used on line 467, and TODOs on lines 693, 726, 758, 808, and 836 (all units related). For the noqa, it should only be used when there are no other ways to get around the issue without major changes. For the TODOs I just want to verify that there is a plan to add/figure out the units.

Wonderful: I'll refactor so the noqa on 467 isn't necessary: it was because of the use of `eval`, and how `feed_item_info` is defined outside of it (easy fix).

For the TODOs on the units I need to ask @Ed731551 to review each of those, to ensure they're correct, and that we also have the units in the Pseudocode.

I'll reach out on Slack as soon as I've handled both.

2023-10-11 19:23 UTC, Isgotkowitz commented
> I'll reach out on Slack as soon as I've handled both.

Thanks Joe

2023-10-12 14:53 UTC, ancheypeng commented on tests/test_animal.py
> +def test_report_ration_supply(mocker):
The type annotations are a bit inconsistent for the tests, some have annotations and some don't

2023-10-12 15:52 UTC, JoeWaddell commented on RUFAS/routines/animal/ration/ration_driver.py
> +            counter += 1
Good call: this is something we're going to tackle with Issue [#834](https://github.com/RuminantFarmSystems/MASM/issues/834), since the current methods will eventually be deprecated (NRC equations).

2023-10-12 16:25 UTC, Ed731551 commented
@JoeWaddell I have checked the units and they are correct in the present version of the code. Units are also included in the Pseudocode but now I have added the following sentence for the case of total MP (metabolizable protein) calculation: "Total MP requirements are expressed in grams per day. This corresponds to the sum of maintenance and other physiological functions".

2023-10-12 17:07 UTC, JoeWaddell commented on tests/test_animal.py
> +def test_report_ration_supply(mocker):
Good note: updated!

2023-10-12 18:10 UTC, Isgotkowitz approved these changes
Noice work Joe

2023-10-12 18:13 UTC, ancheypeng approved these changes
Looks good!

2023-10-12 18:30 UTC, merged