Percolation patch
RuminantFarmSystems/RuFaS pull request #818
Opened 2023-10-02 15:36 UTC by ew3361zh

This PR seeks to address issue #805 by:

1. Rearranging the logic in the `Percolation.percolate()` method so that the the percolated water is added to the layer below the day after it's percolated from the layer above rather than the same day (comments added for clarity in comment but removed in actual code):
![Screenshot 2023-10-02 at 11 10 19 AM](https://github.com/RuminantFarmSystems/MASM/assets/70217952/59b1407b-3101-44a8-8281-7b8ff196bfd2)
2. Updating unit testing for the `percolate()` method.

Notes:
There was previously only integration testing for the `percolate()` method and while @Isgotkowitz and I tried to dissect the logic, we couldn't quite figure it out. I wrote a new unit test more specifically for the `percolate()` method and tested whether it achieved the same level of coverage for percolation.py if the integration test was removed and coverage held steady at 100%. I don't know what other .py files the `test_percolate()` integration test may affect though so I am leaving it in place for the time being. If reviewers would prefer it be removed because it's not certain what it's testing, please comment that.

2023-10-02 19:03 UTC, Isgotkowitz requested changes
This is a good start but the vadose zone layer needs to be percolated into.

2023-10-02 19:03 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/percolation.py
> +                    current_layer.water_content += layer_above.percolated_water
This works for all the soil layers contained in `self.data.soil_layers`, but water doesn't percolate into the vadose zone layer.

2023-10-02 19:09 UTC, Isgotkowitz commented
> Notes:
There was previously only integration testing for the percolate() method and while @Isgotkowitz and I tried to dissect the logic, we couldn't quite figure it out. I wrote a new unit test more specifically for the percolate() method and tested whether it achieved the same level of coverage for percolation.py if the integration test was removed and coverage held steady at 100%. I don't know what other .py files the test_percolate() integration test may affect though so I am leaving it in place for the time being. If reviewers would prefer it be removed because it's not certain what it's testing, please comment that.

@ew3361zh thank you for writing this test. I am working on another bug in percolation right now, and when I finalize the PR for it I will update `test_percolate()` to work in a correct and understandable manner.

2023-10-02 19:13 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/percolation.py
> +                    current_layer.water_content += layer_above.percolated_water
I think just adding `self.data.vadose_zone_layer.water_content += self.data.soil_layers[-1].percolated_water` after the for loop has finished executing would work.

2023-10-03 14:33 UTC, ew3361zh commented on RUFAS/routines/field/soil/percolation.py
> +                    current_layer.water_content += layer_above.percolated_water
I tried it with the line after the loop but the testing wasn't behaving as expected so added the line within the loop based on some conditional logic which I think does very close to what it does outside the loop but behaves more as expected with water_content and percolated_water amounts by layer.

2023-10-03 16:06 UTC, Isgotkowitz approved these changes
LGTM. Thank you Niko

2023-10-03 21:53 UTC, matthew7838 approved these changes
Niko, nice change and good coverage on the tests.

2023-10-04 13:55 UTC, merged