Snow in Soil
RuminantFarmSystems/RuFaS pull request #848
Opened 2023-10-12 14:48 UTC by allisterakun

This PR solves the following in[ Implement snow in RuFaS #317](https://github.com/RuminantFarmSystems/MASM/issues/317):
- [x] Add a snow content variable to `SoilData`. XS
- [x] Add snow to snow content in `SoilData` when snowfall occurs. S
  - _Note_: do not worry about areal depletion when adding snow to a field. Assume the fraction of field area that is covered by snow is always 1 when snow is present.
- [x] Implement snow melting. L
  - Implement `Snow` class in `soil/`
  - Determine snow temperature (eqn. 1:2.5.1)
  - Determine snow melt amount (eqn.'s 1:2.5.2, 3)

2023-10-17 20:08 UTC, Isgotkowitz commented on RUFAS/routines/field/field/field.py
> +        self.snow = Snow(soil_data=self.soil.data, field_size=self.field_data.field_size)
Snow is actually going to be contained in `Soil`. Good thought to add it here though. If you want, you can leave the integration of `Snow` as a task for subsequent PRs.

2023-10-17 20:08 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        return (mlt6 + mlt12) / 2 + ((mlt6 - mlt12) / 2 * (math.sin(2 * math.pi / 365) * (day - 81)))
All protected methods in here should be `@staticmethods`.

2023-10-17 20:08 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        return sno_ratio * (sno_ratio + math.exp(cov1 - cov2 * sno_ratio)) ** -1
The snow coverage fraction does not need to be calculated. It can be assumed that it is equal to 1.0 whenever there is snow on the ground.

2023-10-17 20:08 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        self.soil_data.snow_content -= self._melt_snow(current_day_weather, day)
The amount of snow melt that occurs everyday should also be recorded to `soil_data`.

2023-10-17 20:08 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/soil_data.py
> +    """Snow pack temperature on the previous day, T_snow_day_(n-1), (ºC)"""
How do you type the degree sign?!

2023-10-17 20:17 UTC, allisterakun commented on RUFAS/routines/field/soil/snow.py
> +        self.soil_data.snow_content -= self._melt_snow(current_day_weather, day)
Will add that!

2023-10-17 20:19 UTC, allisterakun commented on RUFAS/routines/field/soil/snow.py
> +        return sno_ratio * (sno_ratio + math.exp(cov1 - cov2 * sno_ratio)) ** -1
Now that I think about it, this does make sense. Will update!

2023-10-17 20:19 UTC, allisterakun commented on RUFAS/routines/field/soil/soil_data.py
> +    """Snow pack temperature on the previous day, T_snow_day_(n-1), (ºC)"""
Copy and paste from Google lollll

2023-10-18 13:03 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        return sno_ratio * (sno_ratio + math.exp(cov1 - cov2 * sno_ratio)) ** -1
Thanks:)

2023-10-18 13:04 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/soil_data.py
> +    """Snow pack temperature on the previous day, T_snow_day_(n-1), (ºC)"""
Nice, gonna have to start writing my docstrings with that

2023-10-19 18:06 UTC, allisterakun commented
![image](https://github.com/RuminantFarmSystems/MASM/assets/39185942/c3e8e830-9e54-43a3-b2af-b7b58e098171)
The test coverage is currently at 97% because the placeholder `sublimation()` function is not being implemented.
![image](https://github.com/RuminantFarmSystems/MASM/assets/39185942/ce20bbc1-1d9a-4309-8f40-09553804b94a)

2023-10-19 20:00 UTC, Isgotkowitz requested changes
Changes requested mostly on changing docstrings. Also a couple design questions I think we should talk through.

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/field/field.py
>          # TODO: implement snow addition, melting, and sublimation - issue #317
```suggestion
```

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/field/field.py
> +
The test for this method should be updated as well.

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        """
```suggestion
    """
    Class representing snow-related calculations and data management.

    This class provides methods for calculating snow pack temperature, snow melting, and
    updating snow-related data based on the Soil and Water Assessment Tool (SWAT) documentation.

    Methods
    -------
    _calc_snow_temp(current_day_weather: CurrentWeather) -> float:
        Calculate the snow pack temperature for the current day.

    _melt_snow(current_day_weather: CurrentWeather, day: int):
        Calculate the snow melt for the current day.

    _melt_factor(day: int) -> float:
        Calculate the snow melt factor for a given day, b_mlt.

    sublimation():
        Placeholder function for sublimation calculations.

    update_snow(current_day_weather: CurrentWeather, day: int) -> None:
        Update snow-related data including snow content and temperatures.
    """
```

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +
Should include an attributes section

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +            """Update snow content with melted snow"""
These variable and method names are really clear, so the inline comments are not necessary.

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +            The calculated snow pack temperature for the current day in Celsius.
```suggestion
        """
        Calculate the snow pack temperature for the current day.

        Parameters
        ----------
        current_day_weather :CurrentWeather
            The current day weather data.

        Returns
        -------
        float
            The calculated snow pack temperature for the current day in Celsius.
            
        References
        ----------
        SWAT Theoretical Documentation eqn. 1:2.5.1
        
```
This is an excellent docstring, but it contains a little too much information. It is sufficient to just put a reference to the corresponding SWAT equation.

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        current_day_weather : CurrentWeather
Missing `soil_data` description here.

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +            The current day weather data.
Missing `soil_data` description here.

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        """
Same comment on this docstring as above.

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        Calculate the snow melt factor for the current day.
Same comment on this docstring as above.

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +    def _calc_snow_temp(soil_data: SoilData, current_day_weather: CurrentWeather) -> float | None:
I don't think this method should ever return None.

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/soil_data.py
> +    """
These variable names are all really good, but their docstrings do not need to contain what they are called in the SWAT equation. Like the docstring for snow content can just be "The water content of the snow pack (mm H2O)."

Variables that are constants and have descriptions in SWAT input documentation files should have explicit references to those descriptions. For example:
```
snow_melt_base_temperature: float = 0.5
"""
Snow melt base temperature (ºC).
Reference: SWAT Input .BSN file, see "TIMP" on page 92.
"""
```

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        if self.soil_data.snow_content <= 0.0:
Can snow content be less than 0?

2023-10-19 20:00 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        return (mlt6 + mlt12) / 2 + ((mlt6 - mlt12) / 2 * (math.sin(2 * math.pi / 365) * (day - 81)))
For this method, what are the benefits and drawbacks of passing in a full `SoilData` object instead of just minimum and maximum snow melt factors? Same question for the other static methods

2023-10-19 20:00 UTC, Isgotkowitz commented on tests/soil_crop_tests/soil_tests/test_snow.py
> +def test_calc_snow_temp(soil_data: SoilData, current_day_weather: CurrentWeather):
Tests should have docstrings, even if they're as simple as "Tests that current snow temperature is calculated correctly."

2023-10-19 20:08 UTC, allisterakun commented on RUFAS/routines/field/field/field.py
> +
Will do!

2023-10-19 20:08 UTC, allisterakun commented on RUFAS/routines/field/soil/snow.py
> +            """Update snow content with melted snow"""
Will remove the in-lin comments

2023-10-19 20:09 UTC, allisterakun commented on RUFAS/routines/field/soil/snow.py
> +        current_day_weather : CurrentWeather
Will update!

2023-10-19 20:09 UTC, allisterakun commented on RUFAS/routines/field/soil/snow.py
> +            The current day weather data.
Will update!

2023-10-19 20:09 UTC, allisterakun commented on RUFAS/routines/field/soil/snow.py
> +        """
Will update!

2023-10-19 20:09 UTC, allisterakun commented on RUFAS/routines/field/soil/snow.py
> +        Calculate the snow melt factor for the current day.
Will update!

2023-10-19 20:10 UTC, allisterakun commented on RUFAS/routines/field/soil/snow.py
> +    def _calc_snow_temp(soil_data: SoilData, current_day_weather: CurrentWeather) -> float | None:
Yes, I forgot to take this out. Will update!

2023-10-19 20:10 UTC, allisterakun commented on RUFAS/routines/field/soil/soil_data.py
> +    """
Will update!

2023-10-19 20:11 UTC, allisterakun commented on RUFAS/routines/field/soil/snow.py
> +        if self.soil_data.snow_content <= 0.0:
I don't believe so, will update!

2023-10-19 20:11 UTC, allisterakun commented on tests/soil_crop_tests/soil_tests/test_snow.py
> +def test_calc_snow_temp(soil_data: SoilData, current_day_weather: CurrentWeather):
Will update!

2023-10-24 17:48 UTC, Isgotkowitz approved these changes
Looks good. All comments are minor docstring things.

2023-10-24 17:48 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        The field size in ha.
```suggestion
        The field size (ha).
```

2023-10-24 17:48 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +    _melt_snow(current_day_weather: CurrentWeather, day: int):
```suggestion
    _melt_snow(current_day_weather: CurrentWeather, day: int) -> float:
```

2023-10-24 17:48 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +            The calculated snow pack temperature for the current day in Celsius.
```suggestion
            The calculated snow pack temperature for the current day (Celsius).
```

2023-10-24 17:48 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/snow.py
> +        Note:
```suggestion
        Notes
        -----
```

2023-10-24 17:48 UTC, Isgotkowitz commented on tests/soil_crop_tests/soil_tests/test_snow.py
> +def test_calc_snow_temp(soil_data: SoilData, current_day_weather: CurrentWeather):
Tests still need docstrings

2023-10-24 18:03 UTC, Isgotkowitz commented
@allisterakun I forgot, `field.py` still needs to have its test updated.

2023-10-24 18:26 UTC, ew3361zh commented
@allisterakun can you write a description of this and (if it applies) link it to the issue it solves? Would be helpful to be able to evaluate it against that.

2023-10-24 20:56 UTC, allisterakun commented
> @allisterakun I forgot, `field.py` still needs to have its test updated.

Will do!

2023-10-25 13:07 UTC, Isgotkowitz approved these changes

2023-10-25 13:57 UTC, ew3361zh approved these changes
Looks good - I just have some grammar suggestions and then the tests look like they still need docstrings. Nice work, Allister! Thanks for adding the description and linking the issue.

2023-10-25 13:57 UTC, ew3361zh commented on RUFAS/routines/field/soil/snow.py
> +        The object that tracks all soil variable throughout the simulation.
```suggestion
        The object that tracks all soil variables throughout the simulation.
```

2023-10-25 13:57 UTC, ew3361zh commented on RUFAS/routines/field/soil/snow.py
> +        """object that tracks all soil variable throughout the simulation"""
```suggestion
        """object that tracks all soil variable throughout the simulation"""
        self.soil_data = soil_data or SoilData(field_size=field_size)
```

2023-10-25 13:57 UTC, ew3361zh commented on RUFAS/routines/field/soil/snow.py
> +            The object that tracks all soil variable throughout the simulation
```suggestion
            The object that tracks all soil variables throughout the simulation.
```

2023-10-25 13:57 UTC, ew3361zh commented on RUFAS/routines/field/soil/snow.py
> +            The object that tracks all soil variable throughout the simulation
```suggestion
            The object that tracks all soil variables throughout the simulation.
```

2023-10-25 13:57 UTC, ew3361zh commented on RUFAS/routines/field/soil/snow.py
> +            The current day weather data
```suggestion
            The current day weather data.
```

2023-10-25 14:43 UTC, merged