Djt carbon
RuminantFarmSystems/RuFaS pull request #85
Opened 2020-09-16 22:05 UTC by Jacob8399

This is the merge to include the carbon cycle in the master branch. Almost all of the changes happen in carbon_cycle.py, soil.py, and the output files for carbon. Carbon takes in residue from yield and outputs org_C% for RuFaS to use.

The model for carbon is fully functional and has room for advancements to be made. Certain variable changes will need to be addressed at a different time, whether they need to come from a database (silt clay), or they need to be reassed for carbon (fr_N). There are TODOs marking these variables.

2020-09-18 00:53 UTC, wmaxdonovan commented on RUFAS/output_handler/reports/field_report.py
> +                                    # 'structural_BG_L3': ['soil.soil_layers[2].structural_BG', 'kg/ha', []],
This was part of the inspiration for the layer report structure in dm_manure. Do we want to consolidate this?

2020-09-18 01:00 UTC, wmaxdonovan requested changes
I think we should finish the pseudocode and consolidate variable names in accordance with RuFaS conventions / further break up some of these methods into smaller sections for readability prior to merging.

2020-09-20 18:39 UTC, Jacob8399 commented on RUFAS/output_handler/reports/field_report.py
> +                                    # 'structural_BG_L3': ['soil.soil_layers[2].structural_BG', 'kg/ha', []],
I'm actually not sure what you're talking about so if you think it should be consolidated then that should be fine. I'm definitely not too attached to the carbon output file haha.

2020-09-20 18:44 UTC, Jacob8399 commented
> I think we should finish the pseudocode and consolidate variable names in accordance with RuFaS conventions / further break up some of these methods into smaller sections for readability prior to merging.

Yeah that was the original goal but splitting everything up started to get messy and cause problems and I didn't want to change anything essential around the annual meeting. Personally, I agree it should be done but think we should do it in the patches branch just so we can get carbon and then dm_manure into master.

2020-09-21 21:43 UTC, HectorMM3 requested changes
Jacob, I left 2-3 years. about these commits. Can you please comment?

2020-09-21 21:43 UTC, HectorMM3 commented on RUFAS/routines/soil/carbon_cycle/carbon_cycle.py
> +        #TODO: Not yet implemented
I don't understand why this has not been implemented yet?

2020-09-21 21:43 UTC, HectorMM3 commented on RUFAS/routines/soil/soil.py
> +    # TODO: Not currently implemented
@Jacob8399 what is the significance of this "TO DO?"

2020-09-21 21:45 UTC, HectorMM3 commented on RUFAS/output_handler/reports/field_report.py
> +                                    # 'structural_BG_L3': ['soil.soil_layers[2].structural_BG', 'kg/ha', []],
Let's discuss this on Th.

2020-09-21 21:53 UTC, Jacob8399 commented on RUFAS/routines/soil/carbon_cycle/carbon_cycle.py
> +        #TODO: Not yet implemented
I believe you're looking at outdated code.

2020-09-21 21:54 UTC, Jacob8399 commented on RUFAS/routines/soil/soil.py
> +    # TODO: Not currently implemented
Same as the above comment.

2020-09-23 21:03 UTC, HectorMM3 requested changes
Hi Jacob, I think in total things look good we need to go ahead and get rid of all "DM" designations since that needs to be removed from crop and the corresponding carbon code and pseudocode. Additionally, the mm to cm conversion we were using was 0.01. I know that you and I had decided to go with this value because it allowed us to match the vensim model. However, the true conversion is 0.1. A change in this conversion factor causes the below ground lignin adjustment to go negative. This needs to be capped at a zero min value. This will allow the Python model to work.  Please reach out if you have any questions. After we submit this I would like to make sure that Michael condenses the pseudocode, per Max's comments through DJT PATCHES are the merge. Also, this will set us up for the additional structures you will need to add in this semester.

2020-09-23 21:03 UTC, HectorMM3 commented on RUFAS/routines/field/crop/yields.py
> +    soil.lignin_residue_percent = 17
Eventually, this "17" will be removed.

2020-09-23 21:03 UTC, HectorMM3 commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +    d_lignin_residue_percent = 0.12 * weather.rainfall[time.year - 1][time.day - 1] * 0.01
0.01 should be 0.1, i.e., there is 0.1 mm per 1 cm. I rechecked the models and my vensim model had it wrong.

2020-09-23 21:03 UTC, HectorMM3 commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +        residue_DM_incorp = layer.fr_tillage * soil.residue_DM_harvest
residue_DM_incorp name should be changed to residue_incorp

2020-09-23 21:03 UTC, HectorMM3 commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +        soil.lignin_residue_BG_percent = soil.lignin_residue_BG_percent - 0.15 \
Change 0.01 to 0.1

2020-09-23 21:03 UTC, HectorMM3 commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +        soil.lignin_residue_BG_percent = soil.lignin_residue_BG_percent - 0.15 \
This S.6.A.15 should not be allowed to go below zero.

2020-09-23 21:03 UTC, HectorMM3 commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +            fr_lignin_residue_DM = residue_DM_incorp / (residue_DM_incorp + crop_type.bio_BG)
Get rid of "DM"

2020-09-23 21:03 UTC, HectorMM3 commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +            LN_ratio_BG = LN_ratio_AG * fr_lignin_residue_DM + ((soil.lignin_residue_percent / 100) / crop_type.fr_N) \
get rid of DM

2020-09-23 21:03 UTC, HectorMM3 commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +        K5 = 0.14
There should probably be a heading for K5 through K7 indicating that it is the active, slow, and passive carbon decomposition.

2020-09-23 21:03 UTC, HectorMM3 commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +        soil_volume = depth * 10 * soil.area
Hi Jacob, where is this "10" coming from? meters*10*hectares...?

2020-09-28 18:26 UTC, wmaxdonovan commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +        K5 = 0.14
Added note in pseudocode.

2020-09-28 18:30 UTC, wmaxdonovan commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +        soil_volume = depth * 10 * soil.area
@Jacob8399 this is the only unresolved comment

2020-09-28 18:38 UTC, wmaxdonovan approved these changes

2020-09-28 20:57 UTC, Jacob8399 commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +        soil_volume = depth * 10 * soil.area
From carbon pseudocode:
soil volume = depth of soil layer*10,000*area
Where depth of a soil layer (meters) and 10,000 is the square meters per hectare (m2 ha-1).

Depth of soil layer needs to be in meters but rufas depth is in mm, so to get it to meters the equation then needs to be:
soil volume = (depth(mm) / 1000) * 10000 * area
Then I just simplified it to the 10

2020-09-29 13:14 UTC, HectorMM3 commented on RUFAS/routines/field/soil/carbon_cycling/carbon_cycle.py
> +        soil_volume = depth * 10 * soil.area
Okay please make sure this is noted @Jacob8399 in the pseudocode. Thanks! :)

2020-09-29 13:16 UTC, HectorMM3 approved these changes

2020-09-29 15:08 UTC, merged