Ration optimizer unit tests
RuminantFarmSystems/RuFaS pull request #852
Opened 2023-10-12 21:42 UTC by ancheypeng

Adds some unit tests for the RationOptimizer functions.

Redo of https://github.com/RuminantFarmSystems/MASM/pull/811 because too many merge conflicts

2023-10-16 15:40 UTC, JoeWaddell approved these changes
These look great, and bring the ration_optimizer coverage up substantially! Nice work

2023-10-18 17:42 UTC, Fjordrunner requested changes
Looks good overall, added some nitpicky comments that could be implemented or discussed.

2023-10-18 17:42 UTC, Fjordrunner commented on tests/test_animal.py
> +        cow_a: dict, cow_b: dict, heifer_a: dict, heifer_b: dict
A nitpick here which pertains to places later in code: `cow_a` is introduced as a dict, but we don't know what types of information is held within it. Maybe making these variable names slightly more descriptive might make future work on these tests easier.

2023-10-18 17:42 UTC, Fjordrunner commented on tests/test_animal.py
> +    assert ration_optimizer.heifer_cons == [cons for cons in ration_optimizer.cow_cons if
This is also nitpicky but if we're working with numpy arrays using np.where might be preferred to the somewhat long list comprehension.

2023-10-18 17:42 UTC, Fjordrunner commented on tests/test_animal.py
> +@pytest.mark.parametrize("udr_or_not, animal_combination, expected_x0, expected_bounds, expected_constraints", [
`is_udr` makes more sense than `udr_or_not` since Boolean values answer that question.

2023-10-18 18:30 UTC, ancheypeng commented on tests/test_animal.py
> +@pytest.mark.parametrize("udr_or_not, animal_combination, expected_x0, expected_bounds, expected_constraints", [
`udr_or_not` is the variable name used in the function, in a different PR both can be changed to clean it up

2023-10-18 18:32 UTC, ancheypeng commented on tests/test_animal.py
> +    assert ration_optimizer.heifer_cons == [cons for cons in ration_optimizer.cow_cons if
They are not numpy arrays, `cow_cons` and `heifer_cons` are just lists. I don't think it would make sense to make them numpy arrays because they are holding a list of dictionaries that contain functions.

2023-10-18 18:33 UTC, ancheypeng commented on tests/test_animal.py
> +        cow_a: dict, cow_b: dict, heifer_a: dict, heifer_b: dict
I think they are just meant to be mock cows to use for unit testing

2023-10-20 04:34 UTC, Fjordrunner commented on tests/test_animal.py
> +@pytest.mark.parametrize("udr_or_not, animal_combination, expected_x0, expected_bounds, expected_constraints", [
I would make a note of this and then change them both in the future if possible, but nothing major.

2023-10-20 04:35 UTC, Fjordrunner commented on tests/test_animal.py
> +        cow_a: dict, cow_b: dict, heifer_a: dict, heifer_b: dict
I think it's a bit unintuitive to have `cow_a` be a dictionary given that we have Cow objects in the model, but this is something that can and I think should be fixed in a future PR.

2023-10-20 04:35 UTC, Fjordrunner approved these changes

2023-10-20 04:40 UTC, merged