Change access to `Weather`
RuminantFarmSystems/RuFaS pull request #860
Opened 2023-10-16 13:44 UTC by Isgotkowitz

This PR changes the way that `Weather` can be accessed by introducing the method `get_current_day_weather()`, which returns a `CurrentDayWeather` object. The `CurrentDayWeather` module and related methods have been moved out of the `Field` module (where the module was named `CurrentWeather`), as well as all associated tests.

2023-10-18 19:44 UTC, ew3361zh approved these changes
LGTM - curious how this will fit in with long-term plans around weather in the model. Nice work.

2023-10-18 19:59 UTC, Isgotkowitz commented
> LGTM - curious how this will fit in with long-term plans around weather in the model. Nice work.

Thanks Niko:)
The idea with this PR (and the one stacked on top of it) is to force every non-`Weather` module to access `Weather` in a controlled way (i.e. use a getter). Once this is done, we can freely modify and update the way `Weather` handles data internally without making any changes to other parts of the model.

2023-10-26 15:10 UTC, PooyaHekmati requested changes
Overall looks good, but there are some comments that need to be addressed.

2023-10-26 15:10 UTC, PooyaHekmati commented on RUFAS/current_weather.py
> +    max_air_temperature: float, optional, default=None
How can "current" weather have min and max values? Current refers to a single point in time which gives scalar values for each parameter, min and max are defined over a set of data points.

2023-10-26 15:10 UTC, PooyaHekmati commented on RUFAS/current_weather.py
> +    precipitation: float = 0.0
why are these not in __init__ ?

2023-10-26 15:10 UTC, PooyaHekmati commented on RUFAS/current_weather.py
> +            self.snow_fall = self.precipitation
```suggestion
        is_freezing = self.mean_air_temperature < 0:
        if is_freezing:
            self.snow_fall = self.precipitation
        else:
            self.rainfall= self.precipitation
```

2023-10-26 15:10 UTC, PooyaHekmati commented on RUFAS/current_weather.py
> +    rainfall: float, default=0.0
inconsistent naming; either rain_fall + snow_fall or rainfall + snowfall

2023-10-26 15:10 UTC, PooyaHekmati commented on RUFAS/current_weather.py
> +        return daylength[month-1]
This has to come from inputs.

2023-10-26 15:10 UTC, PooyaHekmati commented on RUFAS/current_weather.py
> +                prev_month = day
The code can be written more clearly. The name of the function is vague. This function has nothing to do with the weather; it belongs to utils.
```suggestion
  @staticmethod
  def day_to_month_conversion(time: Time) -> int:
      """
      Converts the day number into the corresponding month of the year.
      
      Parameters
      ----------
      time: Time
          Time object containing the current time of the simulation.
      
      Returns
      -------
      int
          The corresponding month of the year (1 for January, 2 for February, etc.).
      """
      # Define the cumulative day counts for non-leap and leap years
      non_leap_cumulative_days_in_months = [31, 59, 90, 120, 151, 181, 212, 243, 273, 304, 334, 365]
      leap_cumulative_days_in_months = [31, 60, 91, 121, 152, 182, 213, 244, 274, 305, 335, 366]
      
      cumulative_days_in_months = leap_cumulative_days_in_months if is_leap_year(time.calendar_year) else non_leap_cumulative_days_in_months 
      
      for month, day_count in enumerate(cumulative_days_in_months ):
          if time.day <= day_count:
              return month + 1 

```

2023-10-26 16:21 UTC, Isgotkowitz commented on RUFAS/current_weather.py
> +    max_air_temperature: float, optional, default=None
In this context, minimum and maximum refer to single points which are the lowest and highest temperatures reached on a single day respectively.

2023-10-26 16:48 UTC, Isgotkowitz commented on RUFAS/current_weather.py
> +    precipitation: float = 0.0
Because `@dataclass`es have their `init` methods generated by Python (described [here](https://docs.python.org/3.10/library/dataclasses.html)). There is a way to add a custom `init` (see [PEP 557](https://peps.python.org/pep-0557/#custom-init-method)), but I think that is not necessary in this use case.

That said, the base initialization method for dataclasses is very loose. Do you think it would be a good idea to have `CurrentWeather` initialization fail if it is passed an unexpected or non-keyword argument?

2023-10-26 17:23 UTC, Isgotkowitz commented on RUFAS/current_weather.py
> +    rainfall: float, default=0.0
Consistent now

2023-10-26 17:46 UTC, Isgotkowitz commented on RUFAS/current_weather.py
> +                prev_month = day
Suggested code changes have been added, and method has been moved to `Utility`.

Important note: I moved the test for this method to a new file `test_util.py`. In order to avoid creating more issues in the same vein as #649, I moved all the other existing tests for `Utility` from `test_misc.py` to `test_util.py`. If this change is undesirable it can be reverted.

2023-10-26 17:58 UTC, Isgotkowitz commented on RUFAS/current_weather.py
> +        return daylength[month-1]
What has to come from inputs? The list of average daylengths for each month, or the daylengths for every single day, something else?

A potential solution that eliminates the problem of Wisconsin daylength values being hardcoded without necessitating a change in the API would be to rewrite this function to calculate the daylength of any given day based on the latitude of one of the fields provided in the input data. There are numerous equations to do this, including SWAT equation 1:1.1.6 ((here)[https://swat.tamu.edu/media/99192/swat2009-theory.pdf]).

2023-10-26 20:22 UTC, PooyaHekmati commented on RUFAS/current_weather.py
> +        return daylength[month-1]
Determining day length is not something that is related to weather. We either want to dynamically calculate it based on lat, long, and day of year (which won't be a function in weather data class, it sounds more like a utility) or we want to receive the day length from the input. Either way, hardcoding the day lengths of a particular geographical region in an unrelated part of the code base doesn't sound right.

2023-10-26 20:23 UTC, PooyaHekmati commented on RUFAS/current_weather.py
> +                prev_month = day
Sounds good, `test_misc.py` needed to be broken down anyways.

2023-10-26 20:41 UTC, Isgotkowitz commented on RUFAS/current_weather.py
> +        return daylength[month-1]
> Either way, hardcoding the day lengths of a particular geographical region in an unrelated part of the code base doesn't sound right.

Agreed. To unblock this PR can an issue be written for it with the understanding that this is a mid to high priority, or should a different method of calculation be implemented in this PR? I think it would be better write an issue because it is not a super trivial task, and merits its own PR.

And because daylength is not actually a weather condition, should `CurrentDayWeather` be renamed to `CurrentDayConditions` (or something similar) to better reflect its purpose?

2023-10-27 19:58 UTC, Isgotkowitz commented on RUFAS/current_weather.py
> +        return daylength[month-1]
Issue #881 has been written for calculating daylength with better resolution, and `CurrentDayWeather` is now `CurrentDayConditions`.

2023-10-27 21:31 UTC, PooyaHekmati approved these changes

2023-10-28 01:06 UTC, merged