Animal DB Removal
RuminantFarmSystems/RuFaS pull request #878
Opened 2023-10-26 17:36 UTC by allisterakun

This PR addresses #897.
In this PR:
1. `input/data/animal/animals.sqlite` is removed, along with `RUFAS/routines/animal/life_cycle/animal_initialization.py`, which contains the `AnimalInitialization` class that handles the database communication and animal herd generation. (Note: the herd generation functions in `AnimalInitialization` are outdated because they are rarely used; I had to fix some logic.)
2. All six tables in the database `animals.sqlite` are exported into JSON file `input/data/animal/animal_population.json`. The structure of the files looks like this: 
```json
{
  "calves": [
    {
      "id": 1,
      "other_attributes": ""
    }, 
    {
      "id": 2,
      "other_attributes": ""
    }
  ],
  "heiferIs": [
    {
      "id": 3,
      "other_attributes": ""
    }, 
    {
      "id": 4,
      "other_attributes": ""
    }
  ],
  "heiferIIs": [
    {
      "id": 5,
      "other_attributes": ""
    }, 
    {
      "id": 6,
      "other_attributes": ""
    }
  ],
  "heiferIIIs": [
    {
      "id": 7,
      "other_attributes": ""
    }, 
    {
      "id": 8,
      "other_attributes": ""
    }
  ],
  "cows": [
    {
      "id": 9,
      "other_attributes": ""
    }, 
    {
      "id": 10,
      "other_attributes": ""
    }
  ],
  "replacement": [
    {
      "id": 11,
      "other_attributes": ""
    }, 
    {
      "id": 12,
      "other_attributes": ""
    }
  ]
}
```
3. As an alternative to  `AnimalInitialization`,  `HerdFactory` is created at `RUFAS/routines/animal/life_cycle/herd_factor.py` to handle the generation of the herd from simulation, and the initialization of the AnimalPopulation object, either from the input data or from simulation. It also has the option to save the generated animals. All initialized animals with go through random sampling with replacement before being added to the InputManager variable pool. It can be later referenced with `im.get_data("runtime_animal_population")`.
4. As an alternative to the database `animals.sqlite`, `AnimalPopulation` is created at `RUFAS/routines/animal/life_cycle/animal_population.py` to store all the animal objects.
5. `herd_information.herd_init` in animal input JSONs are removed and changed to a GNU argument (`"-I"` or `"--init_herd"`). All metadata are also updated to sync with the change.
6. Introduced a `herd_initialization` section in animal input JSON files that defines parameters for herd initialization simulation: 
    - initial_animal_num
        - The initial number of animals the simulation starts with for generating the herd. Default to 10,000.
    - simulation_days
        - The number of days to simulate for generating the herd. Default to 5,000.
8. Introduced four new GNU args: 
    - `init_herd`
        - `"-I"` or `"--init_herd"
        - User input indicating whether to generate animals through simulation. True for generating animals; otherwise, the herd will be initialized from input data.
    - `save_animals`
        - `"-s"` or `"--save_animals"`
        - User input indicating whether to save the generated animals to JSON files.
    - `save_animals_dir`
        - `"-S"` or `"--save_animals_dir"`
        - The directory for the output animal population JSON file.
    - `terminate_simulation_post_herd_generation`
        - `"-t"` or `"--terminate_simulation_post_herd_generation"`
        - User input indicating whether to terminate the simulation after herd generation.
9. Removed the `num` and `breed` arguments in all get_animals methods.
10. Changed `OutputManager._dict_to_file_json()` method to a public `OutputManager.dict_to_file_json()` function. Also added a `minify_output_file: bool=False` input to optionally minify the output JSON file by setting the separator.
11. The herd initialization process is moved into `main.py` from `AnimalManager`. The initialized AnimalPopulation object will be added to the InputManager pool as a dictionary; it can be later referenced with 
`im.get_data("runtime_animal_population")`, 
12. Added `get_cow_values()` and `get_replacement_values()` in `Cow` class.
13. Updated all other tests accordingly.
    - Also updated some tests in `tests/soil_crop_tests/manager_tests/test_field_manager.py` that are caused by mocking InputManager methods.

## Animal Generation Logic Diagram:
![Animal_generation (1)](https://github.com/RuminantFarmSystems/MASM/assets/39185942/3b4895e4-1cfa-4e8d-9801-bcb1b16c9743)

## Animal Generation Time:
It takes about 5 minutes on my laptop (2018 MacBook Pro 2.2GHz 6-core Intel Core i7-8750H CPU, 16GB 2400MHz DDR4 RAM), and about 3 minutes on my PC (4.5GHz 8-core AMD Ryzen 5800X CPU, 64GB 3200MHz DDR4 RAM) to simulate an initial 10,000 animals over 5,000 days.

2023-11-21 08:08 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +            'breed': 'HO',  # THIS IS HARD-CODED?
Just a note here

2023-12-06 17:36 UTC, JoeWaddell commented on main.py
> +        f"Initializing herd data...\n",
This and below are throwing flake8 errors in my IDE since there aren't placeholders with '{'.

2023-12-06 17:41 UTC, allisterakun commented on main.py
> +        f"Initializing herd data...\n",
Will fix this

2023-12-06 18:54 UTC, JoeWaddell commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +            'breed': 'HO',  # THIS IS HARD-CODED?
This should definitely be dynamic e.g. whatever is in `['herd_information']['breed']` in the animal data json.

2023-12-11 13:59 UTC, KFosterReed commented
This is looking really good so far! I was able to run the simulation and initialize a new herd and realize differences in the herd bodyweight with the newly initialized herd. Extra bonus points because it only took 4 minutes to initialize the herd!!

I got the following error when trying to run the terminate or save GNU args with the herd initialization though: 

![image](https://github.com/RuminantFarmSystems/MASM/assets/41019131/7a001233-14d8-4b4a-88e3-0f93e5a2c12e)

Could very much be a user error - any suggestions?

2023-12-11 14:37 UTC, allisterakun commented
> This is looking really good so far! I was able to run the simulation and initialize a new herd and realize differences in the herd bodyweight with the newly initialized herd. Extra bonus points because it only took 4 minutes to initialize the herd!!
> 
> 
> 
> I got the following error when trying to run the terminate or save GNU args with the herd initialization though: 
> 
> 
> 
> ![image](https://github.com/RuminantFarmSystems/MASM/assets/41019131/7a001233-14d8-4b4a-88e3-0f93e5a2c12e)
> 
> 
> 
> Could very much be a user error - any suggestions?

Will figure out why!

2023-12-11 15:22 UTC, allisterakun commented
> This is looking really good so far! I was able to run the simulation and initialize a new herd and realize differences in the herd bodyweight with the newly initialized herd. Extra bonus points because it only took 4 minutes to initialize the herd!!
> 
> I got the following error when trying to run the terminate or save GNU args with the herd initialization though:
> 
> ![image](https://private-user-images.githubusercontent.com/41019131/289558598-7a001233-14d8-4b4a-88e3-0f93e5a2c12e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDg0MDEsIm5iZiI6MTcwMjMwODEwMSwicGF0aCI6Ii80MTAxOTEzMS8yODk1NTg1OTgtN2EwMDEyMzMtMTRkOC00YjRhLTg4ZTMtMGY5M2U1YTJjMTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE1MjE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ODVmMDYxODU1NTk2MTFkZjk3Y2JiNmE5N2Y1ZjJhMDhlZDUzYmIzZjVmZWEyYTBjMmQ4YzlhOWY4YzYwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pdfGqQdPwglKAGMlXVnNDyD0OFqadTghPZD_ZJMWjy8)
> 
> Could very much be a user error - any suggestions?

I don't seem to be able to recreate the error... Let me finish with the unit tests, I will get back to this!

![image](https://github.com/RuminantFarmSystems/MASM/assets/39185942/6d5bc2a4-578f-410d-a362-5eb5ba8a0149)

2023-12-11 18:00 UTC, KFosterReed commented
> > This is looking really good so far! I was able to run the simulation and initialize a new herd and realize differences in the herd bodyweight with the newly initialized herd. Extra bonus points because it only took 4 minutes to initialize the herd!!
> > I got the following error when trying to run the terminate or save GNU args with the herd initialization though:
> > ![image](https://private-user-images.githubusercontent.com/41019131/289558598-7a001233-14d8-4b4a-88e3-0f93e5a2c12e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMDg0MDEsIm5iZiI6MTcwMjMwODEwMSwicGF0aCI6Ii80MTAxOTEzMS8yODk1NTg1OTgtN2EwMDEyMzMtMTRkOC00YjRhLTg4ZTMtMGY5M2U1YTJjMTJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE1MjE0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc0ODVmMDYxODU1NTk2MTFkZjk3Y2JiNmE5N2Y1ZjJhMDhlZDUzYmIzZjVmZWEyYTBjMmQ4YzlhOWY4YzYwNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.pdfGqQdPwglKAGMlXVnNDyD0OFqadTghPZD_ZJMWjy8)
> > Could very much be a user error - any suggestions?
> 
> I don't seem to be able to recreate the error... Let me finish with the unit tests, I will get back to this!
> 
> ![image](https://private-user-images.githubusercontent.com/39185942/289583139-6d5bc2a4-578f-410d-a362-5eb5ba8a0149.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzMTc4MTMsIm5iZiI6MTcwMjMxNzUxMywicGF0aCI6Ii8zOTE4NTk0Mi8yODk1ODMxMzktNmQ1YmMyYTQtNTc4Zi00MTBkLWEzNjItNWViNWJhOGEwMTQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjExVDE3NTgzM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkYTE1YWM1MWZiN2M5NTU3NWU5MjdiN2Y3NWIxODk5YjhkMjI4M2UyYTVkOGE0NTJiZDYzNTk4NzAxOTA3OGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ax6EWA4la7vGoj19E-uqtkOXn-aLROt-3CQ_zkwelAs)

So I just tried it again and it works fine! Not sure what was going on? I was at a coffee shop this morning so maybe that had something to do with it?

2023-12-13 17:04 UTC, PooyaHekmati commented
I minified animal_population.json using this code:
```python
import json


def minify_json_file(input_file_name, output_file_name):
    try:
        with open(input_file_name, "r") as input_file:
            parsed_json = json.load(input_file)

        minified_json = json.dumps(parsed_json, separators=(",", ":"))

        with open(output_file_name, "w") as output_file:
            output_file.write(minified_json)

        print(f"Minified JSON has been written to {output_file_name}")

    except json.JSONDecodeError:
        print("Invalid JSON input")
    except FileNotFoundError:
        print("Input file not found")
    except Exception as e:
        print(f"An error occurred: {e}")


minify_json_file(r"animal_population.json", r"animal_population_min.json")
```
The benefit of this is that it reduces the file size (in terms of MB); and more importantly, it brings the PR stats back to reasonable ranges. Please consider using a similar approach in the code, so this will happen automatically in future.

2023-12-13 17:08 UTC, PooyaHekmati commented
Oh, and since I renamed `animal_population.json` to `animal_population_min.json` we may need to rename it back.

2023-12-13 17:14 UTC, PooyaHekmati commented on main.py
> +    )
I think these GNU args, especially their help can be written more clearly. Right now, they don't capture the context. Consider adding something like: when init herd is selected, choose the save dir, etc...

2023-12-13 17:14 UTC, PooyaHekmati commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +            'breed': 'HO',  # THIS IS HARD-CODED?
maybe make an issue and mention it here?

2023-12-14 07:11 UTC, allisterakun commented
> I minified animal_population.json using this code:
> 
> ```python
> import json
> 
> 
> def minify_json_file(input_file_name, output_file_name):
>     try:
>         with open(input_file_name, "r") as input_file:
>             parsed_json = json.load(input_file)
> 
>         minified_json = json.dumps(parsed_json, separators=(",", ":"))
> 
>         with open(output_file_name, "w") as output_file:
>             output_file.write(minified_json)
> 
>         print(f"Minified JSON has been written to {output_file_name}")
> 
>     except json.JSONDecodeError:
>         print("Invalid JSON input")
>     except FileNotFoundError:
>         print("Input file not found")
>     except Exception as e:
>         print(f"An error occurred: {e}")
> 
> 
> minify_json_file(r"animal_population.json", r"animal_population_min.json")
> ```
> 
> The benefit of this is that it reduces the file size (in terms of MB); and more importantly, it brings the PR stats back to reasonable ranges. Please consider using a similar approach in the code, so this will happen automatically in future.

This is added as an option in `OutputManager.dict_to_file_json`

2023-12-14 07:11 UTC, allisterakun commented on main.py
> +    )
Done!

2023-12-14 07:12 UTC, allisterakun commented
> Oh, and since I renamed `animal_population.json` to `animal_population_min.json` we may need to rename it back.

Renamed it back!

2023-12-14 07:22 UTC, allisterakun commented
#1047 mentions the hard-coded values that I have found in the animal module so far.

2023-12-14 15:39 UTC, ew3361zh commented on RUFAS/output_manager.py
>          """Saves a dictionary into a JSON file
Do you want to add something to the main description about this function minifying or is the flag argument description enough of an explanation?

2023-12-14 16:08 UTC, allisterakun commented on RUFAS/output_manager.py
>          """Saves a dictionary into a JSON file
Right! I should! I will also update the docstring.

2023-12-14 16:26 UTC, JoeWaddell approved these changes
Before losing internet access, wanted to throw in my approval for this PR (though officially pending resolution of the issues raised by the SWEs). I tested it prior to the unit tests under a number of different conditions, and it appears to function properly. This should be a big help for testing purposes, and herd dynamics after initialization. Nice work!

2023-12-14 16:41 UTC, allisterakun commented on RUFAS/output_manager.py
>          """Saves a dictionary into a JSON file
Done!

2023-12-14 16:59 UTC, ew3361zh commented
Still reviewing but wanted to note that it would be helpful when this gets merged to send a note out to the general and/or dev-team channels that people will need to run `pip install -r requirements.txt` (or whatever they use to ensure they've updated to the latest requirements).

2023-12-14 17:02 UTC, KFosterReed approved these changes
I tested a few more scenarios and all the GNU arguments so looks good from the SME POV :)

2023-12-14 17:25 UTC, Isgotkowitz requested changes
Looks really good Allister. I have put in a bunch of suggestions that fix typos in docstrings, also some places where I think the code could be made a bit more readable.

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_manager.py
>          Parameters
```suggestion
        Parameters
        ----------
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_manager.py
> +    def init_animals(self, herd_data: Dict[str, Any]):
```suggestion
    def init_animals(self, herd_data: Dict[str, Any]) -> None:
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/animal_manager.py
> +        Returns: a dictionary which is the summary of the initial herd
```suggestion
        Returns
        -------
        dict
            A dictionary which is the summary of the initial herd.
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +        Default is True.
```suggestion
    current_animal_id : int, default=0
        The highest ID number among all animals in the herd.
    order_by_random : bool, default=0
        A flag to indicate whether the animals should be ordered randomly.

```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +              [i.id for i in self.heiferIIIs] + [i.id for i in self.cows] + [i.id for i in self.replacement]
```suggestion
        ids = [i.id for i in self.calves + self.heiferIs + self.heiferIIs + self.heiferIIIs + self.cows + 
               self.replacement]
```
Slightly more pythonic IMO, but doesn't actually reduce the number of lines.

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +       Increment and return the next unique identifier for an animal.
```suggestion
       """
       Increment and return the next unique identifier for an animal.
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +    def next_id(self):
```suggestion
    def next_id(self) -> int:
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +    def get_calves(self):
```suggestion
    def get_calves(self) -> List[Calf]:
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +    def get_heiferIs(self):
```suggestion
    def get_heiferIs(self) -> List[HeiferIs]:
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +    def get_heiferIIs(self):
```suggestion
    def get_heiferIIs(self) -> List[HeiferIIs]:
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +       --------
```suggestion
       Returns
       -------
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +        --------
```suggestion
        Returns
        -------
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +        --------
```suggestion
        Returns
        -------
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +        --------
```suggestion
        Returns
        -------
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +        """
```suggestion
    def get_heiferIIIs(self) -> List[HeiferIII]:
        """
        Retrieve a list of HeiferIII instances.

        Returns
        -------
        List[HeiferIII]
            A list of HeiferIII instances.
        """
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +        """
```suggestion
    def get_cows(self) -> List[Cow]:
        """
        Retrieve a list of Cow instances.

        Returns
        -------
        List[Cow]
            A list of Cow instances.
        """
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +        """
```suggestion
    def get_replacement_cows(self) -> List[Cow]:
        """
        Retrieve a list of replacement Cow instances.

        Returns
        -------
        List[Cow]
            A list of replacement Cow instances.
        """
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +        --------
```suggestion
        Returns
        -------
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +        cow_avg_CI = sum(cow.CI for cow in self.cows) / num_cow if num_cow else 0
There could be a subroutine written that handles all this averaging. I think it would help readability, but is not strictly necessary.

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/cow.py
> +        }
I don't know how the encapsulation needs to work for `Cow`, but all tests pass when this suggestion is applied. I think it is also a little more future-proof, in case the attributes in `Cow` change.
```suggestion
        return self.__dict__
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/cow.py
> +        return {
Same comment as above

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/herd_factory.py
> +            save_animals is True. Default is "output/".
```suggestion
        init_herd : bool, default=False
            A flag to indicate whether to initialize through simulation or from input data.
        save_animals : bool, default=False
            Indicates whether to save the generated animals to JSON files.
        save_animals_path : Path, default=Path("output/")
            The directory path where the animal data JSON files will be saved if
            save_animals is True.
```

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/herd_factory.py
> +        self.pre_animal_population.cows = remaining_cows
Two comments that apply to all the update methods:
1. Adding more verbose docstrings here would be beneficial.
2. Changing the name of `update()` methods to something like `update_growth()` or `update_life_cycle_stage()` would be good, because it was not very obvious what they are updating. Revisiting those issues might be better left for a different issue/PR though.

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/herd_factory.py
> +                                               birth_weight=0)
I am curious, why is the birth weight for a calf 0? This seems very low.

Edit: this is just a random question for the SMEs.

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +            User input indicating whether to terminate the simulation after herd generation.
So `herd_data` contains data for initialization _and_ indicates if the simulation should be terminated after herd generation?

2023-12-14 17:25 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/life_cycle.py
Since you are modifying it, can you please change this docstring for use NumPy style?

2023-12-14 17:25 UTC, Isgotkowitz commented on input/data/animal/animal_user_defined_ration_md.json
>  	"animal_config": {
```suggestion
	},
        "herd_initialization": {
          "initial_animal_num": 10000,
          "simulation_days": 5000
        },
	"animal_config": {
```

2023-12-14 17:25 UTC, Isgotkowitz commented on input/data/animal/no_animal.json
> +  },
```suggestion
      "herd_initialization": {
        "initial_animal_num": 10000,
        "simulation_days": 5000
      },
```

2023-12-14 17:25 UTC, Isgotkowitz commented on main.py
> +    to a specified directory.
I think this should be made a seperate paragraph in the notes section.

2023-12-14 18:15 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/life_cycle.py
> +            User input indicating whether to terminate the simulation after herd generation.
This line shouldn't be here, I must have missed this line when removing the `terminate_simulation_post_herd_generation` flag. Thank you for catching this!

2023-12-15 07:09 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +        cow_avg_CI = sum(cow.CI for cow in self.cows) / num_cow if num_cow else 0
After some conversation with @Isgotkowitz, he suggested using a pre-existing function (either `numpy.average` or `statistics.mean`) for the get-average operation. However, after testing out both recommended methods, I have decided to write a custom `AnimalPopulation._average()` static method because neither of the recommended methods expects an empty list as input, and both would result in an exception.

2023-12-15 07:44 UTC, allisterakun commented on RUFAS/routines/animal/life_cycle/herd_factory.py
> +        self.pre_animal_population.cows = remaining_cows
#1051

2023-12-15 09:21 UTC, allisterakun commented
In PR #877, `animal.animal_config.heifer_repro_programs.heifer_TAI_protocol` and `animal.animal_config.heifer_repro_programs.heifer_synchED_protocol` are combined into a single variable `animal.animal_config.heifers.repro_sub_protocol`. 

However, the `HeiferII` class is not updated. It is still expecting `tai_method_h` and `synch_ed_method_h` as arguments upon initialization. 

To adapt to this change, I had to make the following change:
```python
    args = heiferI.get_heiferI_values()

    args.update(id=self.pre_animal_population.next_id())
    args.update(repro_program=AnimalBase.config['heifer_repro_method'])
    args.update(tai_method_h=AnimalBase.config['heifer_repro_programs']['heifer_TAI_protocol'])
    args.update(synch_ed_method_h=AnimalBase.config['heifer_repro_programs']['heifer_synchED_protocol'])

    heiferII = HeiferII(args)
```
||
\\/

```python
    args = heiferI.get_heiferI_values()

    args.update(id=self.pre_animal_population.next_id())
    args.update(repro_program=AnimalBase.config['heifer_repro_method'])
    args.update(tai_method_h=AnimalBase.config['heifers']['repro_sub_protocol'])
    args.update(synch_ed_method_h=AnimalBase.config['heifers']['repro_sub_protocol'])

    heiferII = HeiferII(args)
```

2023-12-15 09:23 UTC, allisterakun commented
> In PR #877, `animal.animal_config.heifer_repro_programs.heifer_TAI_protocol` and `animal.animal_config.heifer_repro_programs.heifer_synchED_protocol` are combined into a single variable `animal.animal_config.heifers.repro_sub_protocol`.
> 
> However, the `HeiferII` class is not updated. It is still expecting `tai_method_h` and `synch_ed_method_h` as arguments upon initialization.
> 
> To adapt to this change, I had to make the following change:
> 
> ```python
>     args = heiferI.get_heiferI_values()
> 
>     args.update(id=self.pre_animal_population.next_id())
>     args.update(repro_program=AnimalBase.config['heifer_repro_method'])
>     args.update(tai_method_h=AnimalBase.config['heifer_repro_programs']['heifer_TAI_protocol'])
>     args.update(synch_ed_method_h=AnimalBase.config['heifer_repro_programs']['heifer_synchED_protocol'])
> 
>     heiferII = HeiferII(args)
> ```
> 
> || \/
> 
> ```python
>     args = heiferI.get_heiferI_values()
> 
>     args.update(id=self.pre_animal_population.next_id())
>     args.update(repro_program=AnimalBase.config['heifer_repro_method'])
>     args.update(tai_method_h=AnimalBase.config['heifers']['repro_sub_protocol'])
>     args.update(synch_ed_method_h=AnimalBase.config['heifers']['repro_sub_protocol'])
> 
>     heiferII = HeiferII(args)
> ```

#1052

2023-12-15 18:47 UTC, Isgotkowitz approved these changes
LGTM. Two minor improvements that can be made to docstrings.

2023-12-15 18:47 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/animal_population.py
> +       """
```suggestion
        """
```

2023-12-15 18:47 UTC, Isgotkowitz commented on RUFAS/routines/animal/life_cycle/life_cycle.py
>              animal_type: The type of animal to get.
```suggestion
        animal_type : Type[GenericAnimal]
            The type of animal to get.
```

2023-12-15 20:08 UTC, merged