Reload om pool
RuminantFarmSystems/RuFaS pull request #896
Opened 2023-11-01 21:59 UTC by ew3361zh

This PR seeks to address issue #856 which creates a function to reload the data from the all_variables.json file produced from a simulation into a variable for the user to process further at their leisure.

- [x] function to search output folder for all_variables.json file
- [x] function to open this file and load it to a variable
- [x] unit testing
- [x] remove print statements
- [x] remove pandas import in main.py
- [x] remove call to function in main.py (only used for testing purposes)  

Questions:
1. What if there are multiple all_variables files in the output folder from multiple simulations? Always select most recent? This is the current behavior.
2. What if there are no all_variables files in the output folder? Currently returning `None`.

2023-11-02 20:07 UTC, ew3361zh commented
Interesting that this test is failing here but passing locally. I think it has to do with the os.path.getctime which isn't showing the 2nd file mocked as being created after the first one. Going to look into this further:

Failing in GitHub:
<img width="1086" alt="Screenshot 2023-11-02 at 4 04 02 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/56a6aca1-64fa-43f5-a4c0-1f014fcd97e1">

Passing locally:
<img width="746" alt="Screenshot 2023-11-02 at 4 07 24 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/c4e71d50-4a75-40d1-82c0-74755168639c">

2023-11-03 14:32 UTC, Isgotkowitz approved these changes
Looks great, only comments are suggestions for adding defaults to docstrings.

2023-11-03 14:32 UTC, Isgotkowitz commented on main.py
> +    file_pattern : str, optional
```suggestion
    directory_path : str, optional, default="output/"
        The path to the directory to be searched.
    file_pattern : str, optional, default="*all_variables*"
```

2023-11-03 14:32 UTC, Isgotkowitz commented on main.py
> +    file_pattern : str, optional
```suggestion
    directory_path : str, optional, default="output/"
        The path to the directory to be searched.
    file_pattern : str, optional, default="*all_variables*"
```

2023-11-03 18:13 UTC, PooyaHekmati commented
> Questions:
> 
> 1. What if there are multiple all_variables files in the output folder from multiple simulations? Always select most recent? This is the current behavior.
> 2. What if there are no all_variables files in the output folder? Currently returning `None`.

Why not getting the path to the file from the user? That way there are no confusion about how to handle missing or multiple files.
Also, I believe these functions belong to the output manager. Why are they in main.py?

2023-11-04 13:13 UTC, ew3361zh commented
> > Questions:
> > 
> > 1. What if there are multiple all_variables files in the output folder from multiple simulations? Always select most recent? This is the current behavior.
> > 2. What if there are no all_variables files in the output folder? Currently returning `None`.
> 
> Why not getting the path to the file from the user? That way there are no confusion about how to handle missing or multiple files. 

I think that would be ideal. From our initial discussion on this it sounded like it wasn't clear exactly where/how this functionality would be implemented.

> Also, I believe these functions belong to the output manager. Why are they in main.py?

I think I wasn't sure if we needed/wanted to reinstantiate OM for just the purpose of reloading the data from the variables pool but I can/will move them to OM.

2023-11-04 14:37 UTC, PooyaHekmati commented
> > > Questions:
> > > 
> > > 1. What if there are multiple all_variables files in the output folder from multiple simulations? Always select most recent? This is the current behavior.
> > > 2. What if there are no all_variables files in the output folder? Currently returning `None`.
> > 
> > 
> > Why not getting the path to the file from the user? That way there are no confusion about how to handle missing or multiple files.
> 
> I think that would be ideal. From our initial discussion on this it sounded like it wasn't clear exactly where/how this functionality would be implemented.

Yes, it wasn't clear and it still is not. In cases like this, we need to deliver something that has minimum implicit assumptions and it works, then based on the feedback that we get from users/SMEs, we can work on making it more user-friendly (similar to MVP vs V1). 
> > Also, I believe these functions belong to the output manager. Why are they in main.py?
> 
> I think I wasn't sure if we needed/wanted to reinstantiate OM for just the purpose of reloading the data from the variables pool but I can/will move them to OM.

Generally speaking, when you don't want to reinstantiate a class, you can define the functions using `@staticmethod` decorator. But here, you need to reinstantiate OM anyway, because how can you load data to the pool if there is no pool? Also, while trying reinstantiate and load the file, you can report the logs to OM itself.

2023-11-06 19:51 UTC, ew3361zh commented on main.py
> +    file_pattern : str, optional
thanks, Ed, we've updated these functions so they don't take these args anymore.

2023-11-06 19:52 UTC, ew3361zh commented on main.py
> +    file_pattern : str, optional
same as above

2023-11-08 15:47 UTC, PooyaHekmati requested changes

2023-11-08 15:47 UTC, PooyaHekmati commented on main.py
> +    vars_file_path: str = None,
use Path instead of str

2023-11-08 15:47 UTC, PooyaHekmati commented on main.py
> +        return
move this block to after `sys.stdout.write("RuFaS: Ruminant Farm Systems Model 2023\n")` in line 76

2023-11-08 15:47 UTC, PooyaHekmati commented on main.py
> +    metadata_files: List[MetadataPaths] = METADATA_PATHS
why?

2023-11-08 15:47 UTC, PooyaHekmati commented on main.py
> +def reload_var_pool(vars_file_path: str) -> None:
use Path instead of str

2023-11-08 15:47 UTC, PooyaHekmati commented on main.py
> +    output_manager.reload_pool(vars_file_path)
Don't modify `vars_file_path` here. This code assumes/forces the file is always in `output` dir. What if the user wants to have the file in somewhere else?
Also, we need to trigger some actions after loading the pool.
```suggestion
    output_manager.set_metadata_prefix("reloaded_data") #or something similar
    output_manager.reload_pool(vars_file_path)
    output_manager.dump_all_nondata_pools(
            r"output", exclude_info_maps, format_option
        )
        output_manager.save_variables(
            Path(r"output"),
            Path(r"output/output_filters/"),
            exclude_info_maps,
            produce_graphics,
            graphics_dir,
        )
```

2023-11-08 15:47 UTC, PooyaHekmati commented on main.py
> +        help="Reload the output manager's variables pool from provided path",
what do you think about `-l` for load instead of reload?

2023-11-08 15:47 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        file_path : str
```suggestion
        file_path : Path
```

2023-11-08 15:47 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            raise e
1. when you are not doing anything with the exception and you just re-raise it, you don't need to make an object for it.
2. `reload_var_pool` in main.py does not have a try-catch block. Raising an exception here makes the program crash without letting the user know why that happens. Instead of raising, add an error to the errors pool.
3. Avoid generic exceptions as much as possible. The exceptions that `open` and `json.load` can raise is documented, catch them specifically. 
```suggestion
        except Exception:
            raise
```

2023-11-08 16:18 UTC, ew3361zh commented on main.py
> +    vars_file_path: str = None,
The reason I did this was Path objects aren't falsy. It seemed cleaner to check the string path provided vs the Path object against Path("") if the user didn't provide anything. 

I can change the `if vars_file_path:` to either `if vars_file_path != Path(""):` 
or we could try `if vars_file_path.is_file()`

2023-11-08 16:20 UTC, ew3361zh commented on main.py
> +        return
If we move it there we could have a scenario where the user accidentally clears the output folder containing the variables file they want to reload though.

2023-11-08 16:21 UTC, ew3361zh commented on main.py
> +    metadata_files: List[MetadataPaths] = METADATA_PATHS
It seemed redundant to call it a list with the type annotation immediately after specifying it was a list.

2023-11-08 16:22 UTC, ew3361zh commented on main.py
> +    output_manager.reload_pool(vars_file_path)
I've got these added. Was making changes as you did this review.

2023-11-08 16:23 UTC, ew3361zh commented on main.py
> +        help="Reload the output manager's variables pool from provided path",
I like that.

2023-11-08 16:41 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            raise e
I will add more specific exceptions for open and json.load.

2023-11-08 21:08 UTC, PooyaHekmati commented on main.py
> +    vars_file_path: str = None,
The information that `vars_file_path` is meant to carry is the path to the variables file. The answer to the question: should we even do this? is not a path to the variables file. Therefore, using `vars_file_path` as the trigger to call `reload_var_pool` is not correct.

2023-11-08 21:11 UTC, PooyaHekmati commented on main.py
> +        return
```if clear_output:
    if reload_vars and vars_file_path is the same as output:
        om.add_error("can't clear the output")
    else:
        clear_output()
```

2023-11-08 22:15 UTC, ew3361zh commented on main.py
> +    vars_file_path: str = None,
To clarify: if we use the load_pool gnu arg to hold the vars_file_path, it's not good practice to also use it as a boolean. So how about if I switched the load_pool gnu arg to a boolean and then if it's True, getting the vars_file_path from the user at that point?

<img width="772" alt="Screenshot 2023-11-08 at 5 14 04 PM" src="https://github.com/RuminantFarmSystems/MASM/assets/70217952/f67cc21f-7b56-4603-ab33-1ff64fdffa9d">

2023-11-09 20:59 UTC, ew3361zh commented on main.py
> +def reload_var_pool(vars_file_path: str) -> None:
Updated

2023-11-09 21:44 UTC, ew3361zh commented
Updates:

- [x] Addresses issue #902 (seemed like a good quick fit with other work done in PR)
- [x] Converts `clear_output` code into a function
- [x] Adds `is_file_in_dir` function to check if the provided file path from the user is in the output directory in cases where the user selects both the -c and -l gnu args.
- [x] Updates unit testing and docstrings accordingly

2023-11-10 15:44 UTC, PooyaHekmati approved these changes
Please address comments before merging.

2023-11-10 15:44 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        """Reloads the Output Manager variables pool from file path provided by user in gnu arg.
```suggestion
    def load_variables_pool_from_file(self, file_path: Path) -> None:
        """Loads the Output Manager variables pool from the file path provided by the user in gnu arg.
```

2023-11-10 15:44 UTC, PooyaHekmati commented on main.py
> +    is_in_dir = is_file_in_dir(output_dir, vars_file_path)
can we give a better name to this variable to indicate is what in the directory?

2023-11-10 15:44 UTC, PooyaHekmati commented on main.py
> +    """Checks if a file path is in the provided directory.
if this function checks "a" file path, then why is the name of the arg specific to vars?

2023-11-10 15:44 UTC, PooyaHekmati commented on main.py
> +        )
`save_variables` generates some logs and warnings as well, so it should be called before `dump_all_nondata_pools`.

2023-11-10 19:16 UTC, merged