Ignore tracked files
RuminantFarmSystems/RuFaS pull request #911
Opened 2023-11-06 20:13 UTC by ew3361zh

This PR seeks to address issue #857. 
As is stated in the issue conversation, .gitignore is working as intended but is not the right tool for this specific job. 

Summed up: there are specific files that we want tracked in GitHub but for which we want to prevent users from pushing local changes accidentally. These are files like scenario_manager.py, metadata files, output filter files. For some of these cases, like the output filter files, it makes more sense to remove the files from being tracked in GitHub rather than having them protected.

Because there isn't a built-in access-control method to allow people to make untracked local changes, this PR develops a workaround:

- [x] Adds git action to list protected file paths and tells github actions to fail linting if any of these file paths is changed (at all).
- [x] Removes all output filter files from output_filters folder. 
- [x] Adds 1 file to protected list to start: scenario_manager.py. If there are others, please comment here and we can add them. Note: the default metadata and default input files will eventually be good candidates for being on the protected list but with incoming changes in the next few weeks, it does not make sense to add them now. If this PR's solution to the issue is approved, I will make an issue to add these input files at an appropriate future date.
- [x] Write a quick-start Output Manager section in the wiki which has some easy set-up steps for capturing and filtering output.

2023-11-07 19:53 UTC, Isgotkowitz requested changes
Looks good. I have two questions re. which files should be checked, which I'd like to discuss then will approve.

2023-11-07 19:53 UTC, Isgotkowitz commented on .github/workflows/lint_flake8.yml
> +          'input/metadata/default_metadata.json'
I don't think the default metadata file should be included here. Even though we really don't want people accidentally changing it, it seems that there will still be some deliberate and necessary changes to it in the next couple weeks.

2023-11-07 19:53 UTC, Isgotkowitz commented on .github/workflows/lint_flake8.yml
> +                        grep -E "\.txt$|\.json$"  |
Should CSVs be looked for here too?

2023-11-07 19:58 UTC, ew3361zh commented on .github/workflows/lint_flake8.yml
> +          'input/metadata/default_metadata.json'
That's a fair point. After those changes are implemented, do you think it's a helpful file to have on this list? It seems like a file we don't want alterations to in general.

2023-11-07 19:58 UTC, ew3361zh commented on .github/workflows/lint_flake8.yml
> +                        grep -E "\.txt$|\.json$"  |
Good call. I can add those.

2023-11-07 21:39 UTC, ew3361zh commented
> Looks good. I have two questions re. which files should be checked, which I'd like to discuss then will approve.

@Isgotkowitz Wondered if you had any additional specific files you thought of that should be included in this protected files category?

2023-11-08 02:22 UTC, Isgotkowitz commented on .github/workflows/lint_flake8.yml
> +          'input/metadata/default_metadata.json'
> After those changes are implemented, do you think it's a helpful file to have on this list? It seems like a file we don't want alterations to in general.

Yes, after the changes have been made I think so. When we get to that point it might be important to include the default files that it uses too.

2023-11-08 02:28 UTC, Isgotkowitz commented
> > Looks good. I have two questions re. which files should be checked, which I'd like to discuss then will approve.
> 
> @Isgotkowitz Wondered if you had any additional specific files you thought of that should be included in this protected files category?

@ew3361zh if the default metadata is protected, it may be good to have all the input files used by the default metadata also be protected.

2023-11-08 02:31 UTC, Isgotkowitz approved these changes

2023-11-10 15:46 UTC, PooyaHekmati approved these changes

2023-11-10 18:26 UTC, merged