Updating the descriptions in the default metadata file
RuminantFarmSystems/RuFaS pull request #921
Opened 2023-11-08 18:15 UTC by ltp23

In this PR, everyone is welcome to improve the descriptions in the `default_metadata.json` related to their work in RuFaS.

2023-11-08 21:53 UTC, Isgotkowitz reviewed
Made changes to Crop and Soil related descriptions. Can come back and approve when everyone is finished making their changes.

2023-11-15 04:38 UTC, YijingGong commented
I made some changes to the metadata description. Another thing I noticed is that "cow_presynch_protocol", currently, "pattern": "^(Double OvSynch|Presynch|G6G)$". But I think it should also take 'None'/'null' because the "cow_presynch_protocol" is optional (see cow.py line 942).  But I don't know how to make the changes to the pattern. Could you help me change that? @ltp23

2023-11-29 22:30 UTC, elle-andreen approved these changes
All changes look appropriate to me!

2024-01-17 19:23 UTC, JoeWaddell requested changes
Looks good! I have a few suggestions that (if you agree) should be copy/pasted across metadata jsons.

2024-01-17 19:23 UTC, JoeWaddell commented on input/metadata/default_metadata.json
> +      "description": "The configuration file for the simulation.",
Maybe something like: "The configuration file for general simulation parameters."

(this, and all others, would apply to all metadata files)

2024-01-17 19:23 UTC, JoeWaddell commented on input/metadata/default_metadata.json
> +      "description": "Contains a crop rotation specification.",
For consistency, maybe: "The configuration file for crop rotation details."

2024-01-17 19:23 UTC, JoeWaddell commented on input/metadata/default_metadata.json
> +      "description": "The configuration file for the user feed module.",
The final bit should be something more like: "for user feed input."

2024-01-18 16:50 UTC, JoeWaddell approved these changes
LGTM!

2024-01-18 18:48 UTC, merged