fix day length calculation
RuminantFarmSystems/RuFaS pull request #960
Opened 2023-11-14 23:04 UTC by matthew7838

### Summary
This PR will address issue #881 regarding how day length is calculated.

### Changes

- Calculations are now based on SWAT 1:1.1.6
- Added a helper method to calculate solar declination radians based on 1:1.1.2
- Fixed how the `determine_daylength` is called in `weather.py`

### Note
The current call of `determine_daylength` in `weather.py` has the latitude **hard-coded** to Madison, WI. This will only be a **temporary value** until the method to retrieve latitude is resolved.

2023-11-21 15:30 UTC, Isgotkowitz requested changes
Good start Matthew. Changes requested on the method signature and test cases of `determine_daylength()`

2023-11-21 15:30 UTC, Isgotkowitz commented on RUFAS/current_day_conditions.py
> +                            angular_velocity=0.2618) -> float:
The API for this method should be changed. It is redundant and gives callers the option to change things that shouldn't be changed.

- Latitude should be passed as degrees, not radians, and converted with either a subroutine or inside the method body.
- Taking in the month and the day is redundant. Just the day number should be taken in, and used to either determine the month or used directly to determine whether there is no sunset or sunrise.
- Angular velocity should be hardcoded in the method body.

2023-11-21 15:30 UTC, Isgotkowitz commented on RUFAS/current_day_conditions.py
> +                          / angular_velocity)
```suggestion
        solar_declination_radians = CurrentDayConditions.calculate_solar_declination_radians(day_number)
        tangent_product = -math.tan(solar_declination_radians) * math.tan(geographic_latitude_radians)
        is_polar_solstice = math.abs(tangent_product) > 1
        if is_polar_solstice:
            is_summer = 6 <= month <= 9
            in_northern_hemisphere = geographic_latitude_radians > 0
            if is_summer and in_northern_hemisphere:
                return 24
            elif not is_summer and in_northern_hemisphere:
                return 0
            elif is_summer and not in_northern_hemisphere:
                return 0
            else:
                return 24
        else:
            day_length = (2 * math.acos(tangent_product) / angular_velocity
```

2023-11-21 15:30 UTC, Isgotkowitz commented on RUFAS/current_day_conditions.py
> +        """
```suggestion
        Helper method to determine the solar declination in radians.

        Parameters
        ----------
        day_number : int
            Day number of the year.

        Returns
        -------
        float
            Solar declination (radians).

        References
        ----------
        SWAT 1:1.1.2

        """
```

2023-11-21 15:30 UTC, Isgotkowitz commented on RUFAS/current_day_conditions.py
> +            month of the simulation
```suggestion
        day_number : int
            Day number of the year.
        geographic_latitude_radians : float
            Geographic latitude in radians.
        angular_velocity: float default = 0.2618
            Angular velocity of earth (radians / hour).
        month : int
            Month of the simulation.
```

2023-11-21 15:30 UTC, Isgotkowitz commented on RUFAS/current_day_conditions.py
> +        Calculates the day length for the field based on its day and latitude
```suggestion
        Calculates the day length for the field based on its day and latitude.
```

2023-11-21 15:30 UTC, Isgotkowitz commented on tests/test_current_day_conditions.py
> +    (180, -1.222, 8, True, False),  # Sumer in polar circle (south hemisphere)
Expected daylength should be defined in the test cases. They will have to be pretty heavily approximated because the SWAT equation is not particularly precise. You can find the actual daylengths for different times and places [here](https://sunrise-sunset.org/us/madison-wi/2023/11)

2023-11-21 15:30 UTC, Isgotkowitz commented on RUFAS/current_day_conditions.py
> +            The day length of  the field on specific day
```suggestion
            The length of the current day (hours).
```
This day length is not specific to any field.

2023-11-21 16:16 UTC, matthew7838 commented on RUFAS/current_day_conditions.py
> +                            angular_velocity=0.2618) -> float:
Thanks. I forgot about the existence of that day-mont conversion method.

2023-11-21 20:23 UTC, ew3361zh commented on RUFAS/current_day_conditions.py
> +        angular_velocity = 0.2618
Is this a constant?

2023-11-21 20:47 UTC, matthew7838 commented on RUFAS/current_day_conditions.py
> +        angular_velocity = 0.2618
yes as long as the farm's on earth.

2023-11-21 21:04 UTC, ew3361zh commented on RUFAS/current_day_conditions.py
> +        angular_velocity = 0.2618
Haha...then should it go in and come from the C&S (earth) constants file?

2023-11-21 21:07 UTC, matthew7838 commented on RUFAS/current_day_conditions.py
> +        angular_velocity = 0.2618
Good point and I agree. I'm not quite aware of the existence of the file, could you point me to it? Thanks.

2023-11-22 14:52 UTC, Isgotkowitz approved these changes
Looks good Matthew. Approving, but there are some suggested changes. Only thing that actually needs to be changed is the hardcoded value for Madison's latitude.

2023-11-22 14:52 UTC, Isgotkowitz commented on RUFAS/current_day_conditions.py
> +            Year of the current simulation.
```suggestion
            Calendar year of the current simulation.
```

2023-11-22 14:52 UTC, Isgotkowitz commented on tests/test_current_day_conditions.py
> +                    day_number, geographic_latitude, year), 0.1)
The suggested code should work for all non-polar tests and all summer/winter polar tests, but not polar tests outside of the extremes. Being able to handle any arbitrary, valid test case is a nice to have so it is up to you if you want to make that change.
```suggestion
            observed = CurrentDayConditions.determine_daylength(day_number, geographic_latitude, year)
            tolerance = 0.1 if not polar_location else 0.0
            assert expected == pytest.approx(CurrentDayConditions.determine_daylength(
                    day_number, geographic_latitude, year), tolerance)
```

2023-11-22 14:52 UTC, Isgotkowitz commented on tests/test_current_day_conditions.py
> +                   wraps=Utility.day_to_month_conversion) as mocked_month_conversion:
What is the `wraps` doing? I haven't seen it before.

2023-11-22 14:52 UTC, Isgotkowitz commented on RUFAS/weather.py
> +        daylength = CurrentDayConditions.determine_daylength(day, 0.752, month)
This be changed to 43.0723

2023-11-22 14:52 UTC, Isgotkowitz commented on RUFAS/current_day_conditions.py
> +        angular_velocity = 0.2618
It should go in the `general_constants.py` file, located in the `RUFAS` directory. Units and origin should be noted in it as well

2023-11-22 15:27 UTC, ew3361zh approved these changes
Very nice work, just a few comments, questions, suggestions but otherwise looks close to ready!

2023-11-22 15:27 UTC, ew3361zh commented on RUFAS/current_day_conditions.py
> +            Day number of the year.
Looking at other feedback - should we specify whether this is day number of the calendar year (and not of the simulation year)? Or even if a simulation starts on a day other than Jan 1, is the day number always the calendar day number?

2023-11-22 15:27 UTC, ew3361zh commented on RUFAS/current_day_conditions.py
> +            Day number of the year.
Same as above - is it self-evident that day number of the year refers to calendar year? Or should we specify that in case it gets confused with day of the simulation year?

2023-11-22 15:27 UTC, ew3361zh commented on tests/test_current_day_conditions.py
> +                            day_number, geographic_latitude, year) == expected
If you decide to keep this block (i.e. not make the change Ed suggested below), I'd switch these two around to avoid the if not and then kept it to just if/else. Seems simpler unless there's another condition we're leaving this open for (not being facetious). 
```suggestion
                if is_winter:
                    if northern_hemisphere:
                        assert CurrentDayConditions.determine_daylength(
                            day_number, geographic_latitude, year) == expected
                    else:
                        assert CurrentDayConditions.determine_daylength(
                            day_number, geographic_latitude, year) == expected
                else:
                    if northern_hemisphere:
                        assert CurrentDayConditions.determine_daylength(
                            day_number, geographic_latitude, year) == expected
                    else:
                        assert CurrentDayConditions.determine_daylength(
                            day_number, geographic_latitude, year) == expected
```

2023-11-22 15:27 UTC, ew3361zh commented on tests/test_current_day_conditions.py
> +                    day_number, geographic_latitude, year), 0.1)
Should it be:
```suggestion
            observed = CurrentDayConditions.determine_daylength(day_number, geographic_latitude, year)
            tolerance = 0.1 if not polar_location else 0.0
            assert expected == pytest.approx(observed, tolerance)
```

2023-11-22 15:44 UTC, matthew7838 commented on tests/test_current_day_conditions.py
> +                   wraps=Utility.day_to_month_conversion) as mocked_month_conversion:
It basically mocks the function without affecting its return value since I want to simply check these functions were called.

2023-11-22 15:45 UTC, matthew7838 commented on RUFAS/weather.py
> +        daylength = CurrentDayConditions.determine_daylength(day, 0.752, month)
Good catch

2023-11-22 16:07 UTC, Isgotkowitz commented on RUFAS/current_day_conditions.py
> +            Day number of the year.
I agree with being more explicit in the documentation - this day number should be documented as the "ordinal day", which is the fancy term for cumulative day number of the year.

> day number of the calendar year (and not of the simulation year)

The `Time` module only has one day counter and it is the same for both the calendar year and the simulated year. Right now, the simulation year and calendar year change at the same time.

2023-11-22 16:09 UTC, matthew7838 commented on tests/test_current_day_conditions.py
> +                    day_number, geographic_latitude, year), 0.1)
Thanks, Ed your suggestions are way cleaner. @ew3361zh I think you're right, that's how I'll adapt to this.

2023-11-22 16:10 UTC, matthew7838 commented on RUFAS/current_day_conditions.py
> +            Day number of the year.
Sure, that should better be specified.

2023-11-22 16:45 UTC, merged