Updates to soil carbon init method and testing
RuminantFarmSystems/RuFaS pull request #961
Opened 2023-11-15 16:22 UTC by ew3361zh

PR to address issue #944.

1. Updates calculations in `_initialize_carbon_pools()`
2. Adds residue to `_initialize_carbon_pools()` args
3. Updates testing.

Note:
- [x] Not sure if a different approach to testing whether residue is being accurately split between the structural and metabolic litter pools is necessary. Would need to think about how to mock the post_init with specific residue values. If you have any suggestions/thoughts, that would be helpful.
- [x] Also could use some help in how to update the Notes docstring section of the `_initialize_carbon_pools()` method. Seems like from the description in #944, this enhancement still isn't entirely precise but is at least a step in the right direction.

2023-11-15 17:06 UTC, Isgotkowitz requested changes
Excellent start Niko. Changes requested for checking that the litter pools are init'ed correctly in the test, and adding a comment noting where the numbers we used came from. Then I think it will be ready to go

2023-11-15 17:06 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/layer_data.py
```suggestion
            self.passive_carbon_amount = 0.44 * total_soil_carbon_amount
            self.structural_litter_amount = 0.0
            self.metabolic_litter_amount = 0.0
```
We want to really be explicit in making sure there is no belowground litter (for now) because some layers get post_init called on them once when they get initialized, then get modified, then get post_init called on them again.

2023-11-15 17:06 UTC, Isgotkowitz commented on tests/soil_crop_tests/soil_tests/test_layer_data.py
> +    actual = LayerData(field_size=field_size, top_depth=top_depth, bottom_depth=750.0, bulk_density=1.5,
```suggestion
    actual = LayerData(field_size=field_size, residue=residue, top_depth=top_depth, bottom_depth=750.0, bulk_density=1.5,
```
If residue is passed into the constructor it will be passed into `_intialize_carbon_pools()` and the results can be observed by looking at the structural and metabolic litter amounts.

2023-11-15 17:06 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/layer_data.py
>          -----
The notes section should contain a brief message stating that the splits for the initialization of carbon pools are not empirical but generally are the same as values used by other models, and the 50/50 split between litter pools is a heavy abstraction but a more accurate split cannot be predicted without knowing management practices prior to initialization.

2023-11-15 20:03 UTC, ew3361zh commented on tests/soil_crop_tests/soil_tests/test_layer_data.py
> +    actual = LayerData(field_size=field_size, top_depth=top_depth, bottom_depth=750.0, bulk_density=1.5,
What are some good typical residue #s to use (or does it matter)?

2023-11-15 21:02 UTC, ew3361zh commented on tests/soil_crop_tests/soil_tests/test_layer_data.py
> +    actual = LayerData(field_size=field_size, top_depth=top_depth, bottom_depth=750.0, bulk_density=1.5,
Added 5, 10, and 19.5

2023-11-15 21:32 UTC, Isgotkowitz approved these changes
LG8TM nice job Niko

2023-11-15 21:33 UTC, Isgotkowitz commented on tests/soil_crop_tests/soil_tests/test_layer_data.py
> +    actual = LayerData(field_size=field_size, top_depth=top_depth, bottom_depth=750.0, bulk_density=1.5,
Any numbers work.

2023-11-18 17:25 UTC, matthew7838 approved these changes
LGTM, a minor comment that I do think it's better to be addressed in this PR, but that's not stopping the approval.

2023-11-18 17:25 UTC, matthew7838 commented on RUFAS/routines/field/soil/layer_data.py
> +        total_soil_carbon_amount = (soil_mass_in_kg * (self.percent_organic_carbon_content / 100) / field_size)
`self.percent_organic_carbon_content ` is the only part that is still using percent instead of a fraction. I think we can convert them in this PR, there should be just some minor work.

2023-11-20 16:00 UTC, ew3361zh commented on RUFAS/routines/field/soil/layer_data.py
> +        total_soil_carbon_amount = (soil_mass_in_kg * (self.percent_organic_carbon_content / 100) / field_size)
Thanks, Matthew. I'm not as familiar with the C&S module - can you explain a little more what you are asking to happen here?

2023-11-20 16:57 UTC, Isgotkowitz commented on RUFAS/routines/field/soil/layer_data.py
> +        total_soil_carbon_amount = (soil_mass_in_kg * (self.percent_organic_carbon_content / 100) / field_size)
@matthew7838 `LayerData` is still using clay, sand, silt, and rock contents as percents and not fractions, so I think any changes that need to be made would be in the soil input files (looks like there are some that need updating though). Seems like it would be better to leave those for another PR though, because it is not always easy to determine if those inputs are off or not.

2023-11-20 18:14 UTC, ew3361zh commented on RUFAS/routines/field/soil/layer_data.py
> +        total_soil_carbon_amount = (soil_mass_in_kg * (self.percent_organic_carbon_content / 100) / field_size)
@Isgotkowitz will make an issue about this to ensure it is handled

2023-11-20 18:14 UTC, merged