moves funs into OM and fixes testing
RuminantFarmSystems/RuFaS pull request #967
Opened 2023-11-16 19:42 UTC by ew3361zh

PR to address issues #941, #975, and updates wiki gnu args a la #934

- [x] adds output dir, output filters dir, and csvs dirs to gnu args and passes them to OM funs
- [x] moves functionality of `_save_variables_to_csv_files` to `_route_save_functions` (which matches behavior with json files) #975
- [x] moves `clear_output_dir` and `is_file_in_dir` functions from main.py to output_manager.py #941
- [x] updates unit testing & docstrings
- [x] adds `create_directory()` function in OM to more uniformly create dirs specified by gnu args

2023-11-17 15:12 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        output_dir = Path(config.global_variables.OUT_DIR)
can we get this from GNU args to address part of issue #838 as well?

2023-11-17 15:38 UTC, ew3361zh commented on RUFAS/output_manager.py
> +        output_dir = Path(config.global_variables.OUT_DIR)
Definitely.
Another dir path that gets set automatically within OM is the CSVs save dir. Should I try and add that one to GNU args as well?

2023-11-17 17:11 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +        output_dir = Path(config.global_variables.OUT_DIR)
yes please

2023-11-21 18:25 UTC, ew3361zh commented
- [x] adds output dir to gnu args and passes it to OM funs
- [x] adds output filters dir to gnu args and passes it to OM funs
- [x] adds csvs dir to gnu args and passes it to OM funs
- [x] moves functionality of _save_variables_to_csv_files to _route_save_functions (which matches behavior with json files)
- [x] moves clear_output_dir and is_file_in_dir functions from main.py to output_manager.py
- [x] updates unit testing
- [x] addresses issues #941, #975, and updates wiki gnu args a la #934

2023-11-27 16:18 UTC, allisterakun approved these changes

2023-11-27 16:18 UTC, allisterakun commented on main.py
> +        output_manager = OutputManager()
output_manager is already declared on line 87

2023-11-27 21:00 UTC, ew3361zh commented on main.py
> +        output_manager = OutputManager()
Thank you, removed the dupe!

2023-11-28 18:19 UTC, PooyaHekmati requested changes
In addition to the comment I left in the code, args such as `save_path`, `graphics_dir`, etc... are redundantly set to default values. This is not good for multiple reasons. Set the default value as upstream as possible (GNU args) and let it flow downstream. Not every single function needs to have a default value.

2023-11-28 18:19 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            raise
```suggestion
        except PermissionError as e:
            self.add_error("Permission Error",f"{path=}; Exception: {str(e)}",info_map)
        except Exception as e:
            self.add_error("mkdir failure", ,f"{path=}; Exception: {str(e)}",info_map)
```

2023-11-28 18:19 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            self.add_log("New directory successfully create.",
```suggestion
            self.add_log("Directory successfully created.",
```

2023-11-28 18:19 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            The path where the directorygit a will be created if it does not already exist.
what is `directorygit`?

2023-11-28 18:19 UTC, PooyaHekmati commented on RUFAS/output_manager.py
> +            self.add_log("Output directory cleared", "No conflicts to clearing output directory.", info_map)
what does `"No conflicts to clearing output directory."` mean?

2023-11-28 18:19 UTC, PooyaHekmati commented on main.py
> +        "--csvs-dir",
does this need to be plural? Applies to other cases as well.

2023-11-28 19:58 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            The path where the directorygit a will be created if it does not already exist.
It's where I think I'm in the command line and start typing a git command and then don't notice that I've accidentally typed that in the docstrings and added it to commit :).

2023-11-28 20:02 UTC, ew3361zh commented on RUFAS/output_manager.py
> +            self.add_log("Output directory cleared", "No conflicts to clearing output directory.", info_map)
It means the file was not in a directory or subdirectory of the output dir. I can rewrite it to be more explicit.

2023-11-28 20:19 UTC, ew3361zh commented on main.py
> +        "--csvs-dir",
Right - I did this because the dirs themselves were called "output_filters", "CSVs", "graphics"...I think it makes grammatical sense to keep them aligned but don't feel too strongly about it. I'll change them and you can let me know if it looks better to you.

2023-12-04 19:53 UTC, PooyaHekmati approved these changes
Please update docstrings before merging, I fixed one as an example.

2023-12-04 19:53 UTC, PooyaHekmati commented on main.py
> +    graphics_dir : Path, optional, default=Path("output/graphics/")
```suggestion
    graphics_dir : Path, optional

2023-12-04 19:53 UTC, PooyaHekmati commented on main.py
> +    filters_dir : Path, optional, default=Path("output/output_filters/")
```suggestion
    filters_dir : Path, optional
```

2023-12-04 19:53 UTC, PooyaHekmati commented on main.py
> +    csv_dir : Path, optional, default=Path("output/CSVs/")
```suggestion
    csv_dir : Path, optional
```

2023-12-04 20:39 UTC, merged