IM runtime populate pool
RuminantFarmSystems/RuFaS pull request #984
Opened 2023-11-20 20:21 UTC by allisterakun

This PR: 
1. Added two public methods `add_dict_variable_to_pool()` and `add_tabular_variable_to_pool()`  and two private methods `_add_variable_to_pool()` and `_metadata_properties_exists` in `InputManager`:
    - `add_dict_variable_to_pool()`
        
            Adds a dictionary variable to the InputManager's pool after validating it against metadata.

            This function takes in a variable along with its name and a key to access its validation metadata.
            It validates the data against the provided metadata and adds the data to the InputManager pool if it is valid.
    
            Parameters
            ----------
            variable_name: str
                The name of the dictionary variable to be added.
            data : Dict[str, Any]
                The data of the variable, structured as a dictionary.
            properties_blob_key : str
                A key used to locate the metadata for validation of the variable.
            eager_termination : bool
                If True, raises a RuntimeError when the variable is invalid.
                If False, the function returns False without raising an error.
    
            Returns
            -------
            bool
                True if the variable is successfully validated and added to the pool.
                False if the variable is invalid and not added to the pool.
    
            Raises
            -------
            TypeError
                If `data` is not the expected type of Dict[str, Any].

    - `add_tabular_variable_to_pool()`
            
           Adds a tabular variable to the InputManager's pool after validating it against metadata.
    
            This function takes in a variable along with its name and a key to access its validation metadata.
            It validates the data against the provided metadata and adds the data to the InputManager pool if it is valid.
    
            Parameters
            ----------
            variable_name: str
                The name of the variable to be added.
            data : Dict[str, List[Any]] | List[Any]
                The data of the tabular variable, structured as a dictionary of lists or a list.
            properties_blob_key : str
                A key used to locate the metadata for validation of the variable.
            eager_termination : bool
                If True, raises a ValueError when the variable is invalid.
                If False, the function returns False without raising an error.
    
            Returns
            -------
            bool
                True if the variable is successfully validated and added to the pool.
                False if the variable is invalid and not added to the pool.
    
            Raises
            -------
            TypeError
                If `data` is not the expected type of Dict[str, List[Any]] | List[Any].
    - `_add_variable_to_pool()`
            
            Adds a variable to the pool after validating its data against specified metadata properties.
    
            Notes
            -----
            This function processes and validates the input data for a variable based on
            its metadata properties. It then adds the validated data to a pool. The function
            also provides an option for eager termination in case of invalid data.
    
            Parameters
            ----------
            variable_name : str
                The name of the variable to be added to the pool.
            data : Dict[str, Any]
                The data associated with the variable that needs validation and addition to the pool.
            properties_blob_key : str
                The key in the metadata properties against which the data is validated.
            eager_termination : bool
                Flag indicating whether the function should return early in case of invalid data.
            is_variable_dict : bool
                Weather the variable is a dictionary variable (rather than tabular).
    
            Returns
            -------
            bool
                 True if the variable is successfully added, False otherwise.
    
            Raises
            -------
            ValueError
                If eager_termination is True and the variable failed validation.
            
    - `_metadata_properties_exists()`
           
            Checks if specific properties exist in the metadata for a given variable.
    
            Notes
            -----
            This function is designed to verify the existence of specified properties
            within the metadata of a particular variable. It returns a boolean indicating
            the existence of the properties, and a KeyError in case of missing metadata
            or properties.
    
            Parameters
            ----------
            variable_name : str
                The name of the variable for which the metadata is to be checked.
            properties_blob_key : str
                The key representing the specific properties blob in the metadata to check.
    
            Returns
            -------
            bool
                True if the properties exist, False otherwise.
    
            Raises
            -------
            ValueError
                If no metadata is loaded in InputManager.__metadata.
            KeyError
                If no metadata properties can be found with the given `properties_blob_key`.
       

3. Wrote unit tests for all new functions.
4. Renamed the following methods in `InputManager`:
    - `_validate_json_element()` => `_validate_dict_element()`
    - `_validate_csv_element()` => `_validate_tabular_element()`

2023-11-21 18:15 UTC, PooyaHekmati requested changes

2023-11-21 18:15 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            self.__pool[variable_name] = data
The variable has to be validated using metadata before being added to the pool. This is why we said we should rename the `_validate_json_element` and `_validate_csv_element` functions.

2023-11-21 18:28 UTC, allisterakun commented on RUFAS/input_manager.py
> +            self.__pool[variable_name] = data
Got it! Will update!

2023-11-29 17:02 UTC, PooyaHekmati reviewed
The PR seems to be on the right direction; however, the description states: `Updates InputManager._populate_pool to a public method InputManager.populate_pool.`; But I still see `_populate_pool` in the code. Also, the newly added function `add_variable_to_pool` is not mentioned in the description, is missing unit tests and docstring.

2023-11-29 17:02 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        data_type_to_loader_map: Dict[str, Callable] = {"json": self._load_data_from_json,
thanks for adding type hints

2023-11-29 17:02 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                    # POTENTIAL ISSUE!!!
do you want to elaborate more?

2023-11-29 17:02 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +    def add_variable_to_pool(self, variable_name: str, data: Dict[str, Any], properties_blob_key: str,
what does this do?
add docstring, even if it is a one-liner

2023-11-29 17:02 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            element_counter_and_validity = self._validate_dict_element([metadata_property], properties_blob_key,
what if data is not in dict?

2023-12-01 18:23 UTC, allisterakun commented on RUFAS/input_manager.py
> +            element_counter_and_validity = self._validate_dict_element([metadata_property], properties_blob_key,
It now can take in either a Dict or a List

2023-12-01 18:23 UTC, allisterakun commented on RUFAS/input_manager.py
> +    def add_variable_to_pool(self, variable_name: str, data: Dict[str, Any], properties_blob_key: str,
Done

2023-12-01 18:24 UTC, allisterakun commented on RUFAS/input_manager.py
> +                    # POTENTIAL ISSUE!!!
Will make a Git issue

2023-12-01 18:24 UTC, allisterakun commented
> The PR seems to be on the right direction; however, the description states: `Updates InputManager._populate_pool to a public method InputManager.populate_pool.`; But I still see `_populate_pool` in the code. Also, the newly added function `add_variable_to_pool` is not mentioned in the description, is missing unit tests and docstring.

All updated

2023-12-01 19:23 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                    # POTENTIAL ISSUE!!!
#1014

2023-12-01 19:23 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        RuntimeError:
Maybe value error is a better choice here?
https://docs.python.org/3/library/exceptions.html#ValueError

2023-12-01 19:23 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        The function logs the count of total, valid, fixed, and invalid elements of the variable during validation.
Either move this line to the beginning of the docstring or add it under Notes

2023-12-01 19:23 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                "is_valid": True
maybe it's better to initialize it with False?

2023-12-01 19:23 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            )
```suggestion
            if isinstance(data, Dict):
              element_counter_and_validity = self._validate_dict_element(
                  element_hierarchy=[metadata_property],
                  properties_blob_key=properties_blob_key,
                  input_data=data,
                  eager_termination=False,
                  element_counter_and_validity=element_counter_and_validity
              ) 
            elif isinstance(data, List):
              element_counter_and_validity = self._validate_tabular_element(
                  var_name=variable_name,
                  properties_blob_key=properties_blob_key,
                  input_data={variable_name: data},
                  eager_termination=False,
                  element_counter_and_validity=element_counter_and_validity
              )
           else:
             raise TypeError with a clear message, don't forget to update the docstring accordingly
```

2023-12-01 19:23 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            self.__pool[variable_name] = data
maybe first check if `self.__pool[variable_name]` has a value, if does, then add a warning that we are overwriting it.

2023-12-01 21:37 UTC, Isgotkowitz approved these changes
Code looks great, two comments on checking/testing edge cases and one on a docstring typo.

2023-12-01 21:37 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        RuntimeError:
```suggestion
        RuntimeError
```

2023-12-01 21:37 UTC, Isgotkowitz commented on tests/test_input_manager.py
> +    assert variable_name not in mock_input_manager._InputManager__pool
If the variable name was already in the pool, maybe it would be worthwhile to add a check that the old data is still present.

2023-12-01 21:37 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        metadata_properties = self.__metadata["properties"][properties_blob_key]
Would it be worthwhile to add a check here to make sure that metadata has actually been loaded before trying to add a variable on the fly?

2023-12-01 21:39 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        metadata_properties = self.__metadata["properties"][properties_blob_key]
yes, also check if `properties_blob_key` does exist.

2023-12-02 01:53 UTC, allisterakun commented on tests/test_input_manager.py
> +    assert variable_name not in mock_input_manager._InputManager__pool
Good catch!

2023-12-02 01:53 UTC, allisterakun commented on RUFAS/input_manager.py
> +        RuntimeError:
Will do!

2023-12-02 03:03 UTC, allisterakun commented on RUFAS/input_manager.py
> +            self.__pool[variable_name] = data
Done

2023-12-02 03:03 UTC, allisterakun commented on RUFAS/input_manager.py
> +                "is_valid": True
Done

2023-12-02 03:03 UTC, allisterakun commented on RUFAS/input_manager.py
> +        The function logs the count of total, valid, fixed, and invalid elements of the variable during validation.
Done

2023-12-02 03:03 UTC, allisterakun commented on RUFAS/input_manager.py
> +        RuntimeError:
Done

2023-12-02 03:03 UTC, allisterakun commented on RUFAS/input_manager.py
> +        metadata_properties = self.__metadata["properties"][properties_blob_key]
Done

2023-12-02 04:00 UTC, allisterakun commented on tests/test_input_manager.py
> +    assert variable_name not in mock_input_manager._InputManager__pool
Done!

2023-12-05 14:42 UTC, Isgotkowitz reviewed
@allisterakun I think the way that tabular data is accepted and parsed by `add_variable_to_pool()` needs to be changed, but I will follow up and talk through this with you cause I might just be missing something.

2023-12-05 14:42 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                             eager_termination: bool) -> bool:
Will this work for more complex tabular data i.e. data from a CSV that has multiple tables? The way it is set up now, it could only accept a single "column" of data, which is problematic because that isn't the way most of the properties for tabular data are set up.

For example let's say I wanted to added another set of weather data, with the name "new_weather_data", properties blob key "weather_properties", and the actual data being `{"year": [1, 1, ...], "precip": [1.3, 0.0, 4.1, ...], ...}`. I think the method would accept this data, but would route the validation through `_validate_dict_element()` instead of `_validate_tabular_element()`, which would ultimately fail I think.

To work through another example, let's say that I only wanted to add a set of precipitation data. We'll call it "new_precip_data", with the properties key "weather_properties", and the actual data being `[0.0, 1.1, 3.55, ...]`. This adheres to all the type hints, but would fail because "weather_properties" expects there to be a "year" column, "jday" column, etc. And there isn't a way to specify a sub-property, like specifying the properties as "weather_properties.precip" would result in a KeyError.

2023-12-05 15:15 UTC, allisterakun commented on RUFAS/input_manager.py
> +                             eager_termination: bool) -> bool:
After conversation with @Isgotkowitz over Slack messages, I have decided to separate the current `add_variable_to_pool()` function into `add_dict_vairable_to_pool()` and `add_tabular_variable_to_pool()`. 
I am also looping in @PooyaHekmati for the information.

-------------------------------------------------------------------------------------------------------------------------------
Here is the conversation for documentation:
> **Ed Hansen**
  [9:44 AM](https://ruminantfarmsystems.slack.com/archives/D05KG2KPVJ5/p1701787461962509)
Hey Allister, I just reviewed #984 and I think I found a problem with the way tabular data is handled by add_data_to_pool(). I wrote it up in a comment, but let me know if you would like to meet and discuss it.
[9:44 AM](https://ruminantfarmsystems.slack.com/archives/D05KG2KPVJ5/p1701787494988279)
Also I will test it out quickly right now to actually verify that there is actually a problem - I might just be imagining things.

-------------------------------------------------------------------------------------------------------------------------------

> **Allister Liu**
  [9:45 AM](https://ruminantfarmsystems.slack.com/archives/D05KG2KPVJ5/p1701787544223749)
I think for complex tabular data, isn't it just the same as dictionary?
[9:46](https://ruminantfarmsystems.slack.com/archives/D05KG2KPVJ5/p1701787564996769)
b/c it will be a Dict[str, List[Any]]]

-------------------------------------------------------------------------------------------------------------------------------

> **Ed Hansen**
  [9:47 AM](https://ruminantfarmsystems.slack.com/archives/D05KG2KPVJ5/p1701787646397839)
Yes, but the issue is that it would get routed through the wrong validation method

-------------------------------------------------------------------------------------------------------------------------------

> **Allister Liu**
  [9:49 AM](https://ruminantfarmsystems.slack.com/archives/D05KG2KPVJ5/p1701787773313419)
Hmmmm I am wondering if the _validate_dict function can handle those Dict[str, List[Any]] data. If not, then I guess there is no way for us to distinguish a dict or a tabular without introducing an extra parameter. I guess I will have to make a new function for that?

-------------------------------------------------------------------------------------------------------------------------------

> Ed Hansen
  [9:56 AM](https://ruminantfarmsystems.slack.com/archives/D05KG2KPVJ5/p1701788180577269)
Probably. Unless it would be an acceptable solution to change the metadata in some way. For example the properties could be changed so that the tabular properties go from
```
"precip": {
        "description": "Amount of precipitation (mm H2O).",
        "type": "number",
        "minimum": 0,
        "default": 0
}
```
> to
```
"precip": {
  "description": "Amount of precipitation (mm H2O).",
  "type": "array",
  "properties": {
      "type": "number",
      "minimum": 0,
      "default": 0
}
```
> [9:58 AM](https://ruminantfarmsystems.slack.com/archives/D05KG2KPVJ5/p1701788280016779)
Or for each top level property, you could add a "type" - like this:
```
    "field_properties": {
      "format": "dict"
      "soil_specification": {...},
      "crop_specification": {...},
      ...
    },
    "weather_properties": {
      "format": "tabular"
      "year": {...},
      "jday": {...},
      ...
    },
```
>(edited)

>[9:58 AM](https://ruminantfarmsystems.slack.com/archives/D05KG2KPVJ5/p1701788327425139)
That might be well outside the scope of #984 though

-------------------------------------------------------------------------------------------------------------------------------

>Allister Liu
  [10:02 AM](https://ruminantfarmsystems.slack.com/archives/D05KG2KPVJ5/p1701788532152789)
Hmmm.... That's quite a big change actually. For this PR, I guess I will make a separate function add_tabular_variable_to_pool  and rename the current function to add_dict_variable_to_pool.
I do think treating everything as a dictionary and modifying the metadata for CSVs to add a "type": "array" would make sense. b/c at the end of the day when those CSVs are imported into IM, they are stored as Dict[str, List[Any]]. I will speak to Pooya about this and see what he thinks about it.

2023-12-11 20:29 UTC, Isgotkowitz requested changes
Looks really good Allister. Changes requested on docstring formatting and making type hints a little more detailed. Also had some questions/suggestions in the code.

2023-12-11 20:29 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            """
Shift docstring to the left by 1 tab.

2023-12-11 20:29 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            or properties.
This should be housed in the "Notes" section of the docstring

2023-12-11 20:29 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            return False, KeyError("No metadata loaded.")
I think this is more of a `TypeError` or `ValueError` - maybe a good fix would be to return one of those error types here and make the return type hint be `(bool, TypeError | KeyError)` (or ValueError if that is more appropriate).

2023-12-11 20:29 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            """
Shift docstring 1 tab to the left.

2023-12-11 20:29 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            also provides an option for eager termination in case of invalid data.
This should go in the "Notes" section of the docstring.

2023-12-11 20:29 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                The type of the variable (e.g., 'dict', 'tabular') to determine the validation method.
If `dict` and `tabular` are the only types that need to be worried about, maybe it would be better to make this input a boolean and call it `is_dict` or something.

2023-12-11 20:29 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                )
What happens if the variable_type is neither `tabular` nor `dict`?

2023-12-11 20:29 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +    def _metadata_properties_exists(self, variable_name: str, properties_blob_key: str) -> (bool, KeyError):
```suggestion
    def _metadata_properties_exists(self, variable_name: str, properties_blob_key: str) -> (bool, KeyError | None):
```
Directly denoting that the error value might be None would be good because that is one of the expected cases.

2023-12-11 20:29 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                              eager_termination: bool, variable_type: str) -> (bool, ValueError):
```suggestion
    def _add_variable_to_pool(self, variable_name: str, data: Dict[str, Any], properties_blob_key: str,
                              eager_termination: bool, variable_type: str) -> (bool, ValueError | None):
```

2023-12-11 20:29 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                    eager_termination=False,
Why `eager_termination=False` instead of `eager_termination=eager_termination`?

2023-12-11 20:29 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +                    # ISSUE #1014 !!!
```suggestion
```

2023-12-11 23:41 UTC, allisterakun commented on RUFAS/input_manager.py
> +            return False, KeyError("No metadata loaded.")
I believe `ValueError` would be more appropriate, I will change it to `ValueError`

> **exception TypeError**
Raised when an operation or function is applied to an object of inappropriate type. The associated value is a string giving details about the type mismatch.
...
Passing arguments of the wrong type (e.g. passing a [list](https://docs.python.org/3/library/stdtypes.html#list) when an [int](https://docs.python.org/3/library/functions.html#int) is expected) should result in a [TypeError](https://docs.python.org/3/library/exceptions.html#TypeError), but passing arguments with the wrong value (e.g. a number outside expected boundaries) should result in a [ValueError](https://docs.python.org/3/library/exceptions.html#ValueError).

2023-12-11 23:47 UTC, allisterakun commented on RUFAS/input_manager.py
> +                The type of the variable (e.g., 'dict', 'tabular') to determine the validation method.
This would be better!

2023-12-11 23:47 UTC, allisterakun commented on RUFAS/input_manager.py
> +                )
Changing `variable_type: str` to `is_dict: bool`

2023-12-11 23:50 UTC, allisterakun commented on RUFAS/input_manager.py
> +                    eager_termination=False,
Initially, I did this because `eager_termination` would be handled differently during runtime from the data-processing before the simulation. But giving it a second thought and looking at how `_validate_dict_element()` and `_validate_tabular_element()` handle `eagter_termination`, I do believe this (passing `eager_termination` to the validation functions rather than hard-coding it to `False`) would be a better solution.

2023-12-12 14:51 UTC, Isgotkowitz requested changes
I found that a number of statements in the tests were not being executed, and also the calls to `_add_variable_to_pool()` need to have arguments updated so that the string arguments for `dict` and `tabular` are changed to bools.

2023-12-12 14:51 UTC, Isgotkowitz commented on RUFAS/input_manager.py
>              """
```suggestion

        """
```

2023-12-12 14:51 UTC, Isgotkowitz commented on tests/test_input_manager.py
There are a lot of statements in these tests that are not being run, which I think is at the root of why test coverage is going down overall in the README. Of those, I don't know exactly how many are being introduced in this PR, but the tests should be changed so that they are running fully.

2023-12-12 14:51 UTC, Isgotkowitz commented on RUFAS/input_manager.py
>              """
```suggestion
        
        """
```

2023-12-12 14:51 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            variable_type='dict')
Needs to be updated to a bool argument

2023-12-12 14:51 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            variable_type='tabular')
Needs to be updated to a bool argument

2023-12-12 14:51 UTC, Isgotkowitz commented on tests/test_input_manager.py
> +            mock_input_manager._add_variable_to_pool = input_manager_original_method_states["_add_variable_to_pool"]
```suggestion
        with pytest.raises(TypeError):
            mock_input_manager.add_dict_variable_to_pool(
                variable_name=variable_name,
                data=data,
                properties_blob_key=properties_blob_key,
                eager_termination=False
            )

        assert mock_om_add_error.call_count == 1
        mock_input_manager._metadata_properties_exists.assert_not_called()
        mock_input_manager._add_variable_to_pool.assert_not_called()

        mock_input_manager.add_dict_variable_to_pool = \
            input_manager_original_method_states["add_dict_variable_to_pool"]
        mock_input_manager._metadata_properties_exists = \
            input_manager_original_method_states["_metadata_properties_exists"]
        mock_input_manager._add_variable_to_pool = input_manager_original_method_states["_add_variable_to_pool"]
```
Nothing is returned when an error is raised

2023-12-12 14:51 UTC, Isgotkowitz commented on tests/test_input_manager.py
> +def test_add_dict_variable_to_pool_metadata_error(variable_name: str,
Same comment from `test_add_dict_variable_to_pool_type_error`

2023-12-12 14:51 UTC, Isgotkowitz commented on tests/test_input_manager.py
> +            mock_input_manager._add_variable_to_pool = input_manager_original_method_states["_add_variable_to_pool"]
Same comment from `test_add_dict_variable_to_pool_type_error`

2023-12-12 14:51 UTC, Isgotkowitz commented on tests/test_input_manager.py
> +            mock_input_manager._add_variable_to_pool = input_manager_original_method_states["_add_variable_to_pool"]
Same comment from `test_add_dict_variable_to_pool_type_error`

2023-12-12 14:51 UTC, Isgotkowitz commented on tests/test_input_manager.py
> +            mock_input_manager._add_variable_to_pool = input_manager_original_method_states["_add_variable_to_pool"]
Same comment from `test_add_dict_variable_to_pool_type_error`

2023-12-12 14:51 UTC, Isgotkowitz commented on tests/test_input_manager.py
> +            mock_input_manager._add_variable_to_pool = input_manager_original_method_states["_add_variable_to_pool"]
Same comment from `test_add_dict_variable_to_pool_type_error`

2023-12-12 15:40 UTC, allisterakun commented on tests/test_input_manager.py
I just updated `test_input_manager.py` making sure all codes are run.
<img width="1869" alt="image" src="https://github.com/RuminantFarmSystems/MASM/assets/39185942/6e2cc61a-5e79-4652-85e9-54d25cfe92ef">

2023-12-12 16:38 UTC, Isgotkowitz approved these changes
LGTM, nice job Allister

2023-12-13 16:35 UTC, PooyaHekmati requested changes
I hate to return the PR again, but there are changes needed.

2023-12-13 16:35 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +                                                                                            None):
In Python, the standard and recommended practice is to raise exceptions, rather than returning them, for error handling and signaling exceptional situations in code. This approach is aligned with the design and idiomatic use of Python as a language.

1. **Use of `raise` Statement**: The `raise` statement in Python is specifically designed to force a specific exception to occur. When an exception is raised, it terminates the flow of the program, allowing the exception to propagate up the call stack until it is handled. This mechanism is intended for handling errors or other exceptional conditions that disrupt the normal flow of control within a code block [ref1](https://victoria.dev/blog/do-i-raise-or-return-errors-in-python/)  [ref2](https://realpython.com/python-raise-exception/).

2. **Avoiding Silent Failures**: Raising exceptions helps to avoid situations where functions fail silently. For instance, if a function encounters an error condition and only returns an error object instead of raising an exception, the calling code might inadvertently treat this as a normal return value, potentially leading to unnoticed errors or undefined behaviors [ref](https://victoria.dev/blog/do-i-raise-or-return-errors-in-python/).

3. **Error Propagation**: In Python, when an exception is raised in a function and not handled within that function, it propagates up to the caller. If it remains unhandled, it continues to propagate until it reaches the main program, potentially halting the program with an exception traceback. This propagation mechanism is an integral part of Python's error-handling approach, ensuring that exceptions are either properly handled or result in a clear indication of an unhandled error [ref](https://realpython.com/python-raise-exception/#:~:text=If%20your%20code%20raises%20an,halts%20with%20an%20exception%20traceback).

4. **Python's Philosophy**: Python's design encourages the use of exceptions for error handling. This contrasts with some other programming languages, like C or Go, which might encourage returning error codes. The idiomatic use of exceptions in Python includes the use of `try...except` constructs for handling these exceptions, a common approach seen throughout Python's standard library and the language itself [ref1](https://realpython.com/python-raise-exception/) [ref2](https://realpython.com/python-raise-exception/#:~:text=In%20contrast%2C%20Python%20encourages%20you,have%20many%20examples%20of%20it)

Based on these principles, it would be advisable to change the code to raise exceptions instead of returning them. This change would align the code with Python's best practices, improve its readability and maintainability, and ensure that error conditions are handled appropriately and consistently.

**This applies to all other cases as well. The docstrings and test cases have to be updated accordingly as well.**

2023-12-13 16:35 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +    def _metadata_properties_exists(self, variable_name: str, properties_blob_key: str) -> (bool,
either `_metadata_properties_exist` or `_metadata_property_exists`

2023-12-13 16:35 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +            om.add_error("No metadata found", f"No metadata is found for variable '{variable_name}' with given "
why is this an error?

2023-12-13 16:35 UTC, PooyaHekmati commented on RUFAS/input_manager.py
> +        is_dict_variable : bool
```suggestion
        is_variable_dict : bool
```
We don't say `Is developer Allister`, we say `is Allister a developer`

2023-12-13 18:22 UTC, allisterakun commented on RUFAS/input_manager.py
> +            om.add_error("No metadata found", f"No metadata is found for variable '{variable_name}' with given "
Because if there were no metadata properties found with the provided `properties_blob_key`, then there's no way we can validate the data.

2023-12-14 05:31 UTC, allisterakun commented on RUFAS/input_manager.py
> +                                                                                            None):
Done!

2023-12-15 18:34 UTC, Isgotkowitz approved these changes
Approving, but there are some minor changes that need to be made to docstrings.

Nice job Allister

2023-12-15 18:34 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        It validates the data against the provided metadata and adds the data to the InputManager pool if it is valid.
Added to notes section

2023-12-15 18:34 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +        It validates the data against the provided metadata and adds the data to the InputManager pool if it is valid.
Add to notes section

2023-12-15 18:34 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            If False, the function returns False without raising an error.
Needs to be updated  - runtime errors aren't raised anymore.

2023-12-15 18:34 UTC, Isgotkowitz commented on RUFAS/input_manager.py
> +            If False, the function returns False without raising an error.
I think either this docstring or the method behavior needs to be changed. Right now, the method doesn't raise a ValueError, it just doesn't catch the `ValueError` raised by `_add_variable_to_pool()` raises one.

2023-12-15 19:28 UTC, PooyaHekmati approved these changes
[![LGTM](https://lgtm.lol/p/125)](https://lgtm.lol/i/125)

2023-12-15 20:08 UTC, merged